### PR TITLE
[DateTimeRangePicker] Fix date format resolving from views on 24hr locales

### LINKED ISSUE #14334: [pickers][DateTimeRangePicker] Polish locale from dayjs breaks datetime format in DateTimeRangePicker since v.7.10.0
### Steps to reproduce

Link to live example:
Correct in 7.9.0: https://codesandbox.io/p/sandbox/mui-daterangepicker-format-issue-7-9-0-jg2c5f
Incorrect in 7.10.0: https://codesandbox.io/p/sandbox/mui-datetimerangepicker-format-issue-7-10-0-6hdc22
Incorrect in 7.14.0: https://codesandbox.io/p/sandbox/mui-datetimerangepicker-format-issue-latest-cdnst2

The issue appears when using polish locale:

```
      <LocalizationProvider
        dateAdapter={AdapterDayjs}
        adapterLocale={dayjs.locale("pl")}
      >
        <DateTimeRangePicker<Dayjs>
          value={[dayjs("2020-02-02T00:00:00"), dayjs("2020-02-03T00:00:00")]}
          slots={{ field: SingleInputDateTimeRangeField }}
          sx={{ "& .MuiInputBase-root": { width: "250px" } }}
        />
      </LocalizationProvider>
```

### Current behavior

On x-date-pickers version >= 7.10.0 the picker displays date in format `02 00:00 – 03 00:00`, not showing month and year.

### Expected behavior

On x-date-pickers version <= 7.9.0 the picker was working correctly displaying format: `02.02.2020 00:00 – 03.02.2020 00:00`

### Context

_No response_

### Your environment

Version that works:
    "dayjs": "1.11.13",
    "@mui/material": "5.16.7",
    "@mui/x-date-pickers-pro": "7.9.0"

Version that doesn't work:
    "dayjs": "1.11.13",
    "@mui/material": "5.16.7",
    "@mui/x-date-pickers-pro": "7.10.0"

**Search keywords**: locale, dayjs
**Order ID**: Order 80141

### PR DESCRIPTION
**Pull request by arthurbalduini**
Fixes #14334.
For `DateTimeRangePickers` the ["day"] case returns an incorrect format.

### CODE REVIEW

File: packages/x-date-pickers/src/internals/utils/date-utils.ts [hunk 1]
```diff
@@ -177,7 +177,7 @@ export const resolveDateFormat = <TDate extends PickerValidDate>(
   }
 
   if (areViewsEqual(views, ['day'])) {
-    return formats.dayOfMonth;
+    return formats.keyboardDate;
```
Comment (arthurbalduini) [inline packages/x-date-pickers/src/internals/utils/date-utils.ts:180]: We could perhaps remove this case and let it return the default format, do you see any problems with that ?

File: packages/x-date-pickers/src/internals/utils/date-time-utils.ts [hunk 2]
```diff
@@ -30,7 +35,7 @@ export const resolveDateTimeFormat = <TDate extends PickerValidDate>(
   views.forEach((view) => {
     if (isTimeView(view)) {
       timeViews.push(view as TimeView);
-    } else {
+    } else if (isDatePickerView(view)) {
```
Comment (LukasTy) [inline packages/x-date-pickers/src/internals/utils/date-time-utils.ts:38]: The problem was an oversight that we did not exclude `meridiem` view, which caused `resolveDateFormat` to always return `keyboardDate` in case of a locale with 12h clock.
On 24h clock the behavior was "correct".
I've adjusted the code to avoid this inconsistency and also added an exception to not resolve `dateFormat` on `DateTimeRange` pickers as they do not have different `date` views other than `day` for now.

**Review by LukasTy — APPROVED** [review]
I've adjusted the approach to one that looks more correct to me.
I'm not sure why we would have differentiated the behavior based on the presence of `value`. 🤔 

Let me know what you think about the solution. 😉

**Comment by arthurbalduini** [comment]
> I've adjusted the approach to one that looks more correct to me. I'm not sure why we would have differentiated the behavior based on the presence of `value`. 🤔
> 
> Let me know what you think about the solution. 😉

I assumed that veryfing if the value is an array (date range) would be more clear than adding a new parameter to the function to be used only in DateTimePickers, since the view verification was done in `resolveDateFormat()`.
Let's go with your solution
