### PR TITLE
[DataGrid] Fix order of spread props on toolbar items

### LINKED ISSUE #13416: [data grid] Toolbar button `slotProps` get overwritten by `slotProps.baseButton`
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/focused-pike-nzz36y?file=%2Fsrc%2FDemo.tsx

Steps:
1. Set some button prop overrides on the data grid like: `slotProps={{ baseButton: { variant: "contained", color: "primary" } }}`
2. Add a custom toolbar and render a button e.g. `GridToolbarColumnsButton`
3. Add some button prop overrides on the toolbar button e.g. `slotProps={{ button: { variant: "outlined", color: "secondary" } }}`

### Current behavior

The `slotProps.baseButton` props take precedence over the `slotProps.button` props on `GridToolbarColumnsButton`.

### Expected behavior

When rendering individual buttons within the toolbar, I should be able to customize the button variant, color etc.

In the above example, the toolbar column button should be the `outlined` variant and `secondary` color.

I haven't dived into this too much, but I think we need to switch the order of `{...buttonProps}` and `{...rootProps.slotProps?.baseButton}` on these buttons:
 https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/components/toolbar/GridToolbarColumnsButton.tsx#L72-L74

### Context

Trying to style toolbar buttons differently to the other buttons in the UI.

### Your environment

_No response_

**Search keywords**: data grid slotProps baseButton toolbar button props

### LINKED ISSUE #15550: [data grid] Insufficient top padding in toolbarContainer Component When Displaying Filter Badge
### Steps to reproduce

Steps:
1. Open this link to live example: https://mui.com/x/react-data-grid/filtering/
2. Set any filter

image

### Current behavior

_No response_

### Expected behavior

Display the entire badge component in the default setting

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid, toolbarContainer, toolbar, filter, badge

### PR DESCRIPTION
**Pull request by KenanYusuf**
Fixed the order of props being spread to toolbar items. Applying props to the individual toolbar items should take precedence over slot props applied at the root level.

Also added the ability to override badge props for `GridToolbarFilterButton`.

Fixes #13416
Closes #15550

### CODE REVIEW

**Review by romgrk — APPROVED** [review]

File: packages/x-data-grid/src/components/toolbar/GridToolbarColumnsButton.tsx [hunk 1]
```diff
@@ -69,9 +69,9 @@ const GridToolbarColumnsButton = React.forwardRef<HTMLButtonElement, GridToolbar
           aria-expanded={isOpen}
           aria-controls={isOpen ? columnPanelId : undefined}
           startIcon={<rootProps.slots.columnSelectorIcon />}
-          {...buttonProps}
           onClick={showColumns}
           {...rootProps.slotProps?.baseButton}
+          {...buttonProps}
```
Comment (marcelo-cardozo) [inline packages/x-data-grid/src/components/toolbar/GridToolbarColumnsButton.tsx:74]: hey @KenanYusuf i am seeing that this causes the showColumns function to not being called if the onClick is defined by the consumer

meaning the popover is not displayed to the user
