### PR TITLE
[fields] Fire `onChange` when filling a partial date

### LINKED ISSUE #8033: [pickers] `onChange` need to be called when cleaning a single section
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/happy-bhabha-xb64l0
(@mui/x-date-pickers@6.0.0-beta.5)

Steps:
1. Enter a valid date
2. Delete one part of the date with the keyboard (for example the months, so that "MM" will appear)
3. No update and no error is triggered (only after all parts are deleted)
4. Value is still the entered one from step 1

### PR DESCRIPTION
**Pull request by flaviendelangle**
Closes #8033

### CODE REVIEW

File: packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts [hunk 1]
```diff
@@ -200,10 +200,15 @@ export const useFieldState = <
 
   const clearActiveSection = () => {
     if (selectedSectionIndexes == null) {
-      return undefined;
+      return;
     }
 
     const activeSection = state.sections[selectedSectionIndexes.startIndex];
+
+    if (activeSection.value === '') {
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts:208]: We currently fire `onChange` even when pressing `Backspace` on an already empty section, which is not useful

File: packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts [hunk 2]
```diff
@@ -367,7 +354,7 @@ export const useFieldState = <
     const sections = fieldValueManager.getSectionsFromValue(
       utils,
       localeText,
-      state.sections,
+      null,
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts:357]: We now can have an invalid date in state, and if the date is invalid and `prevSections` is defined, then we re-use the sections, which is not what we want here.

File: packages/x-date-pickers/src/internals/utils/valueManagers.ts [hunk 3]
```diff
@@ -34,22 +34,29 @@ export const singleItemFieldValueManager: FieldValueManager<
 > = {
   updateReferenceValue: (utils, value, prevReferenceValue) =>
     value == null || !utils.isValid(value) ? prevReferenceValue : value,
-  getSectionsFromValue: (utils, localeText, prevSections, date, format) =>
-    addPositionPropertiesToSections(splitFormatIntoSections(utils, localeText, format, date)),
+  getSectionsFromValue: (utils, localeText, prevSections, date, format) => {
+    const shouldReUsePrevDateSections = !utils.isValid(date) && !!prevSections;
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/utils/valueManagers.ts:38]: Live for range fields, we now want the single item field to re-use the sections when the new value is invalid

**Review by LukasTy — COMMENTED** [review]
Leaving a few comments to think about the implications of such change a bit more deeply. 🤔

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx [hunk 4]
```diff
@@ -63,10 +63,10 @@ describe('<SingleInputDateRangeField /> - Editing', () => {
 
           // Start date
           userEvent.keyPress(input, { key: keyToClearValue });
-          expect(handleChange.callCount).to.equal(0);
+          expect(handleChange.callCount).to.equal(1);
           userEvent.keyPress(input, { key: 'ArrowRight' });
           userEvent.keyPress(input, { key: keyToClearValue });
-          expect(handleChange.callCount).to.equal(1);
+          expect(handleChange.callCount).to.equal(2);
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx:69]: OK so if I understand correctly, your 1st proposal would be to add a check that says "do not fire if the previous firing was with a partially filled date and the new firing is also with a partially filled date".

I would be interested to have the opinion of @sebastian-ludwig
And if we can't reach to an agreement on when `onChange` should be called, see how we can make that customizable.

[the remark this answers is not in the document]
Comment (LukasTy) [reply packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx:90]: > OK so if I understand correctly, your 1st proposal would be to add a check that says "do not fire if the previous firing was with a partially filled date and the new firing is also with a partially filled date".

Yes, both of my solutions are in essence the addition of comparison between the previous date and the currently changed one, if they do not differ (`null === null` and `'Invalid date' === 'Invalid date'`), why bother spamming `onChange` events and create the same problem we currently have when adding a somewhat simple check should be sufficient in order to avoid redundant emitting. 🤔 
The difference between the solutions is whether `'Invalid date' === null` or not. 🤔 
Because going with the notion of them being equal would mean that we basically once again remove one of the validation cases we have:
```js
case !adapter.utils.isValid(value):
  return 'invalidDate';
```

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx [hunk 5]
```diff
@@ -19,7 +19,7 @@ describe('<SingleInputDateRangeField /> - Editing', () => {
               defaultValue={[adapter.date(), adapter.addYears(adapter.date(), 1)]}
             />,
           );
-          const input = screen.getByRole('textbox');
+          const input = screen.getByRole<HTMLInputElement>('textbox');
```
Comment (LukasTy) [inline packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx:22]: Nitpick, I've created a util function `getTextbox` in order to avoid this duplicated typed getter everywhere. But in any case, it is also a perfectly viable solution. 👌 
P.S. Have you merged with the recent next? 🙈

File: packages/x-date-pickers/src/DateField/tests/selection.DateField.test.tsx [hunk 6]
```diff
@@ -77,7 +77,7 @@ describe('<DateField /> - Selection', () => {
 
     it('should select day on mobile', () => {
       render(<DateField />);
-      const input: HTMLInputElement = screen.getByRole('textbox');
+      const input: HTMLInputElement = screen.getByRole<HTMLInputElement>('textbox');
```
Comment (LukasTy) [inline packages/x-date-pickers/src/DateField/tests/selection.DateField.test.tsx:80]: If we are going with an explicit way, probably double typing is already redundant. 🙈 
```suggestion
      const input = screen.getByRole<HTMLInputElement>('textbox');
```

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx:90]: `null` is not an invalid value, so for me yes we should fire when changing from `null` to `Invalid Date`

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx (hunk 5 above)
Comment (flaviendelangle) [reply packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx:22]: Fixed :+1:

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx:90]: Behavior updated :+1:

[the remark this answers is not in the document]
Comment (LukasTy) [reply packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx:90]: I do really like the current behavior! ❤️ 
Will do some more in-depth testing, but IMHO it's a huge improvement. 👍

[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx:90]: It would be nice to have an "incompleteDate" error instead of "invalidDate".
But that will require deeper changes to the validation because the validation itself can't deduce this piece of information on its own...

File: packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx [hunk 7]
```diff
@@ -275,7 +275,28 @@ describe('<DateField /> - Editing', () => {
...
+          clickOnInput(input, 1);
+
+          // Select all sections
+          userEvent.keyPress(input, { key: 'a', ctrlKey: true });
+
+          userEvent.keyPress(input, { key: keyToClearValue });
+          expect(handleChange.callCount).to.equal(0);
+        });
+
+        it('should call `onChange` when clearing each section', () => {
```
Comment (LukasTy) [inline packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx:299]: After the behavior change this test becomes somewhat misleading or incomplete. 🤔 
We won't call `onChange` after **each** section is cleared if there are more than 2 sections.
Maybe it's worth to also check what kind of value or validation error is returned after each action on top of checking call count? 🤔

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (LukasTy) [reply packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx:90]: Sure, but I think that we firstly need to validate this behaviour and see if we'd get requests to not have this intermediate (`invalidDate`) step.
Like some users suggested, we might need to add `updateStrategy` or something along those lines to cater to users wanting more simple behaviour like **Spectrum** and maybe leave this one as default. 🤔

File: docs/data/date-pickers/fields/fields.md [hunk 8]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
 
 The field components have an internal state to update the visible value.
 
-It will only call the `onChange` callback when all the sections of the modified date are filled.
+It will only call the `onChange` callback when:
+
+- all the sections of the modified date are now filled
```
Comment (LukasTy) [inline docs/data/date-pickers/fields/fields.md:42]: Maybe avoid tying the "time domain" in the description? 🤔 
```suggestion
- all the sections of the modified date are filled
```

File: docs/data/date-pickers/fields/fields.md [hunk 9]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
...
+- all the sections of the modified date are now empty (will return `null` for the modified date)
```
Comment (LukasTy) [inline docs/data/date-pickers/fields/fields.md:43]:
```suggestion
- all the sections of the modified date are empty (will return `null` for the modified date)
```

File: docs/data/date-pickers/fields/fields.md [hunk 10]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
...
+- all the sections of the modified date were filled, and the user cleaned the content of one section
```
Comment (LukasTy) [inline docs/data/date-pickers/fields/fields.md:44]:
```suggestion
- all the sections of the modified date were filled, and the user cleaned the content of one section (will return `Invalid date` for modified date)
```
And maybe also add a point of firing the same when starting to enter date in an empty field? 🤔

**Review by LukasTy — COMMENTED** [review]
This is a really great improvement, good job! 💯 

As it's quite a big UX change, I'd love to hear @joserodolfofreitas and maybe @alexfauquette opinion on it. 🤔

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-date-pickers-pro/src/SingleInputDateRangeField/tests/editing.SingleInputDateRangeField.test.tsx:90]: A good point with the `incompleteDate` error is that you can let people ignore those specific errors.
Which would keep the firing behavior simple: we have an `onChange` that fires often but people can easily ignore some calls.
The only non-covered use-case I see is if some people want `onChange` to be called for every section change (what I initially did in this PR).

But I don't think it's worth adding a notion of "update strategy" yet.

File: packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx (hunk 7 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx]: Done :+1:

**Review by LukasTy — APPROVED** [review]
LGTM!. 👌 
But like I mentioned, I'd love to hear @joserodolfofreitas take on this or to at least have a look at this. 🙈

File: docs/data/date-pickers/fields/fields.md [hunk 11]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
...
+
+- all the sections of the modified date are filled
+- all the sections of the modified date are empty (will return `null` for the modified date)
+- all the sections of the modified date were filled, and the user cleaned the content of one section (will return `Invalid date` for modified date)
 
 #### On single element fields
 
-On a single date field (`DateField` / `DateTimeField` / `TimeField`),
-`onChange` will be called if all the sections are filled.
+On a single item field (`DateField` / `DateTimeField` / `TimeField`),
```
Comment (alexfauquette) [inline docs/data/date-pickers/fields/fields.md:48]: 'item' is confusing. I first though you were talking about a field with only year for example

File: docs/data/date-pickers/fields/fields.md [hunk 12]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
...
-`onChange` will be called if all the sections of the date you modified are filled,
-even if some sections of the other date are not filled.
+On a range field (`SingleInputDateRangeField` / `MultiInputDateRangeField` / ... ),
+`onChange` will be called if the date you are modifying is matching one of the condition above,
+even if the other date does not.
 
-In the demo below, changing the value of a start date section will fire `onChange` even if the end date is empty.
-But changing the value of an end date section will not fire `onChange` until the end date is fully completed:
+In the demo below, changing the value of a start date section will call `onChange` even if the end date is empty.
+But when editing the end date, `onChange` will only be called when filling the first section and the last one:
```
Comment (alexfauquette) [inline docs/data/date-pickers/fields/fields.md:62]: Are you sure? If I modify a section of the second date, I immediately receive the `Invalid Date`

https://deploy-preview-8082--material-ui-x.netlify.app/x/react-date-pickers/fields/#advanced

File: docs/data/date-pickers/fields/fields.md (hunk 11 above)
Comment (flaviendelangle) [reply docs/data/date-pickers/fields/fields.md:48]: I'm trying to avoid the term "date" or "value" since they describe something else.
Do you have another idea ?

Comment (alexfauquette) [reply docs/data/date-pickers/fields/fields.md:48]: For MIT components?

Comment (flaviendelangle) [reply docs/data/date-pickers/fields/fields.md:48]: I don't understand what you mean.

Comment (alexfauquette) [reply docs/data/date-pickers/fields/fields.md:48]: I was thinking MIT vs Pro, but not a great idea.

Maybe "On a simple field" which avoids the notion of number associated with "single"

File: docs/data/date-pickers/fields/fields.md (hunk 12 above)
Comment (flaviendelangle) [reply docs/data/date-pickers/fields/fields.md:62]: Indeed, I did not fix that wording, good catch !

Comment (flaviendelangle) [reply docs/data/date-pickers/fields/fields.md:62]: For me the sentence is correct
When you edit the end date, you have one `onChange` on the 1st edited section (with `Invalid Date`) and one `onChange` on the last edited section (with a valid date)

File: docs/data/date-pickers/fields/fields.md (hunk 11 above)
Comment (flaviendelangle) [reply docs/data/date-pickers/fields/fields.md:48]: Could work indeed :+1: 
I changed on my PR

File: docs/data/date-pickers/fields/fields.md (hunk 12 above)
Comment (alexfauquette) [reply docs/data/date-pickers/fields/fields.md:62]: Ok, I understood "first" and "last" according to their position, not "first one to be filled", and "last one to be filled" So it was making no sense 🙈

Maybe the sentence is not needed. It's nice to say that the `onChange` is called even if the end date is empty, but the second part is not related to the range fields. it's the same behavior as simple fields.

File: docs/data/date-pickers/fields/fields.md [hunk 13]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
 
 The field components have an internal state to update the visible value.
 
-It will only call the `onChange` callback when all the sections of the modified date are filled.
+It will only call the `onChange` callback when:
 
-#### On single element fields
+- all the sections of the modified date are filled
```
Comment (joserodolfofreitas) [inline docs/data/date-pickers/fields/fields.md:42]:
```suggestion
- The first section of the input is filled
- all the sections of the modified date are filled
```

File: docs/data/date-pickers/fields/fields.md [hunk 14]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
...
+- all the sections of the modified date are empty (will return `null` for the modified date)
+- all the sections of the modified date were filled, and the user cleaned the content of one section (will return `Invalid date` for modified date)
```
Comment (joserodolfofreitas) [inline docs/data/date-pickers/fields/fields.md:44]:
```suggestion
- user cleans the content of one section in a previously valid value (will return `Invalid date` for modified date)
```

File: docs/data/date-pickers/fields/fields.md [hunk 15]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
...
 
 {{"demo": "LifeCycleDateFieldEmpty.js", "defaultCodeOpen": false}}
 
 #### On range fields [<span class="plan-pro"></span>](/x/introduction/licensing/#pro-plan)
 
-On a date range field (`SingleInputDateRangeField` / `MultiInputDateRangeField`),
-`onChange` will be called if all the sections of the date you modified are filled,
-even if some sections of the other date are not filled.
+On range fields (`SingleInputDateRangeField` / `MultiInputDateRangeField` / ... ),
+`onChange` will be called if the date you are modifying is matching one of the condition above,
```
Comment (joserodolfofreitas) [inline docs/data/date-pickers/fields/fields.md:58]:
```suggestion
`onChange` will be called if any of the dates you are modifying matches one of the conditions above,
```

File: docs/data/date-pickers/fields/fields.md [hunk 16]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
...
+It will only call the `onChange` callback when:
 
-#### On single element fields
+- all the sections of the modified date are filled
+- all the sections of the modified date are empty (will return `null` for the modified date)
+- all the sections of the modified date were filled, and the user cleaned the content of one section (will return `Invalid date` for modified date)
 
-On a single date field (`DateField` / `DateTimeField` / `TimeField`),
-`onChange` will be called if all the sections are filled.
+#### On simple fields
```
Comment (joserodolfofreitas) [inline docs/data/date-pickers/fields/fields.md:46]: I think we don't need a specific section for "simple fields"; after the condition list, we can jump to the example, and it's introduction directly.

```suggestion
```

File: docs/data/date-pickers/fields/fields.md [hunk 17]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
...
 
-In the example below, `onChange` will not be fired until the date is fully completed:
+On simple fields (`DateField` / `DateTimeField` / `TimeField`),
```
Comment (joserodolfofreitas) [inline docs/data/date-pickers/fields/fields.md:48]:
```suggestion
```

File: docs/data/date-pickers/fields/fields.md [hunk 18]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
...
+`onChange` will be called if the date matches one of the condition above.
```
Comment (joserodolfofreitas) [inline docs/data/date-pickers/fields/fields.md:49]:
```suggestion
```

File: docs/data/date-pickers/fields/fields.md [hunk 19]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
...
+
+In the example below, `onChange` will be called once when filling the first section and once when filling the last one:
```
Comment (joserodolfofreitas) [inline docs/data/date-pickers/fields/fields.md:51]:
```suggestion
In the example below, `onChange` will be called when any of the conditions are triggered.
```

File: docs/data/date-pickers/fields/fields.md [hunk 20]
```diff
@@ -37,25 +37,29 @@ The single input range fields are not supported on the range pickers yet (you ca
...
-On a date range field (`SingleInputDateRangeField` / `MultiInputDateRangeField`),
-`onChange` will be called if all the sections of the date you modified are filled,
-even if some sections of the other date are not filled.
+On range fields (`SingleInputDateRangeField` / `MultiInputDateRangeField` / ... ),
+`onChange` will be called if the date you are modifying is matching one of the condition above,
+even if the other date does not.
 
-In the demo below, changing the value of a start date section will fire `onChange` even if the end date is empty.
-But changing the value of an end date section will not fire `onChange` until the end date is fully completed:
+In the demo below, changing the value of a start date section will call `onChange` even if the end date is empty.
```
Comment (joserodolfofreitas) [inline docs/data/date-pickers/fields/fields.md:61]:
```suggestion
In the demo below, changing the value of the start date will call `onChange` even if the end date is empty.
```

**Review by joserodolfofreitas — COMMENTED** [review]
It feels great! 
I tried out the examples, and I think you nailed it.

File: docs/data/date-pickers/fields/fields.md (hunk 14 above)
Comment (flaviendelangle) [reply docs/data/date-pickers/fields/fields.md:44]: I avoid using the term `valid` because it is used a lot in the validation, with a different meaning

I tried to reword the whole bullet point list :+1:

File: docs/data/date-pickers/fields/fields.md (hunk 15 above)
Comment (flaviendelangle) [reply docs/data/date-pickers/fields/fields.md:58]: That's not true
If you fill your start date, you have one of the date that matches one of the condition above.
And yet, when editing the end date, you won't have an `onChange` call when filling the 2nd section.

The rule is applied on the modified date, whatever value the other date might have.

Comment (joserodolfofreitas) [reply docs/data/date-pickers/fields/fields.md:54]: Got it!

**Review by joserodolfofreitas — COMMENTED** [review]
I wonder if we could make the condition list more digestible by using the end-users interaction as a reference point.

Something like:

- User fills one section of an empty input. The value equals `Invalid date`.
- User completes all sections of an input. The value reflects input.
- User cleans one section of a completed input. The value equals `Invalid date`.
- User cleans all sections of an input. The value equals `null`.

Also, I think that before explaining onChange, we should introduce the concept of "section". We're taking this as an obvious concept, but it may not be.
It can also be an opportunity to document their connection with a valid date and time values and their independence from the other fields.

**Comment by flaviendelangle** [comment]
> It can also be an opportunity to document their connection with a valid date and time values and their independence from the other sections on the field.

I don't understand this point

**Comment by flaviendelangle** [comment]
I added a small section to introduce the notion of `section`
