### PR TITLE
[TreeView] Fix usage of the `aria-selected` attribute

### LINKED ISSUE #14982: [tree view] All selectable items should have aria-selected set to false when they are not selected.
### Summary

All selectable items must have aria-selected=“false” by default (then aria-selected=“true” when selected). For the moment, we only have the aria-selected=“true” when it's selected, but without the aria-selected=“false”.

Accessibility issue reported by iValua.

**Search keywords**:

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #14982

The old behavior was linking to the ARIA doc which does not describes what was implemented...

### CODE REVIEW

File: packages/x-tree-view/src/TreeItem/TreeItem.tsx [hunk 1]
```diff
@@ -358,17 +358,17 @@ export const TreeItem = React.forwardRef(function TreeItem(
...
-     * Source: https://www.w3.org/WAI/ARIA/apg/patterns/treeview/
-     */
+  // https://www.w3.org/WAI/ARIA/apg/patterns/treeview/
+  let ariaSelected: boolean | undefined;
+  if (selected) {
+    // - each selected node has aria-selected set to true.
     ariaSelected = true;
+  } else if (disableSelection || disabled) {
+    // - if the tree contains nodes that are not selectable, aria-selected is not present on those nodes.
+    ariaSelected = undefined;
```
Comment (joserodolfofreitas) [inline packages/x-tree-view/src/TreeItem/TreeItem.tsx:368]: They mentioned that "without the aria-selected=“false”, NVDA doesn't render the information, so we don't know if the item is selected or not."
I'm not sure if NVDA does that only when there's at least one selected, but I'm wondering if, in order to "display" the items, it should always be `false` even when there's no selection or selection is disabled.

**Review by LukasTy — APPROVED** [review]
LGTM, nice improvement! 👍 👏

File: packages/x-tree-view/src/TreeItem/TreeItem.tsx (hunk 1 above)
Comment (joserodolfofreitas) [reply packages/x-tree-view/src/TreeItem/TreeItem.tsx:368]: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected states for Grid that setting aria-selected="false" on a focusable gridcell indicates the cell is selectable.
I believe the same logic applies to Tree items, so `ariaSelected=undefined` is the way to go indeed.

**Review by joserodolfofreitas — APPROVED** [review]
