### PR TITLE
[DataGrid] Make the pinned rows be on top of the no rows overlay

### LINKED ISSUE #9927: [data grid] No result overlay interferes with grid manipulation
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/strange-chaum-3znsww

Steps:
1. Pin all 4 rows
2. Try to unpin a row

### Current behavior 😯

When all rows in a grid are pinned, it is impossible to unpin them as the No result overlay block the user from clicking on a row. 

### Expected behavior 🤔

Either no overlay (as rows are presents) or the overlay shouldn't block the user from clicking on the pinned rows.

### Context 🔦

_No response_

### Your environment 🌎

System:
    OS: macOS 13.4.1
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 3.4.1 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Edge: 115.0.1901.183
    Safari: 16.5.2

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by DanailH**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #9927

### CODE REVIEW

File: packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx [hunk 1]
```diff
@@ -170,8 +170,8 @@ const VirtualScrollerPinnedRows = styled('div', {
   const boxShadowColor = getBoxShadowColor(theme);
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:170]: I am wondering if it'd be better to not show no rows overlay at all even if there are some pinned rows.

```diff
diff --git a/packages/grid/x-data-grid/src/components/base/GridOverlays.tsx b/packages/grid/x-data-grid/src/components/base/GridOverlays.tsx
index 1b1068045..21183218e 100644
--- a/packages/grid/x-data-grid/src/components/base/GridOverlays.tsx
+++ b/packages/grid/x-data-grid/src/components/base/GridOverlays.tsx
@@ -10,6 +10,7 @@ import { gridExpandedRowCountSelector } from '../../hooks/features/filter/gridFi
 import {
   gridRowCountSelector,
   gridRowsLoadingSelector,
+  gridPinnedRowsCountSelector,
 } from '../../hooks/features/rows/gridRowsSelector';
 import { useGridApiContext } from '../../hooks/utils/useGridApiContext';
 import { useGridRootProps } from '../../hooks/utils/useGridRootProps';
@@ -95,10 +96,11 @@ export function GridOverlays() {
   const rootProps = useGridRootProps();
 
   const totalRowCount = useGridSelector(apiRef, gridRowCountSelector);
+  const pinnedRowsCount = useGridSelector(apiRef, gridPinnedRowsCountSelector);
   const visibleRowCount = useGridSelector(apiRef, gridExpandedRowCountSelector);
   const loading = useGridSelector(apiRef, gridRowsLoadingSelector);
 
-  const showNoRowsOverlay = !loading && totalRowCount === 0;
+  const showNoRowsOverlay = !loading && totalRowCount === 0 && pinnedRowsCount === 0;
   const showNoResultsOverlay = !loading && totalRowCount > 0 && visibleRowCount === 0;
 
   let overlay: React.JSX.Element | null = null;
```

Because:

1. No rows not _actually_ true because we do have some rows (even though they are pinned but there are some rows).
2. Even if we assume that we are talking about the unpinned rows, the styling of no rows overlay isn't consistent as the text is always rendered in the middle, e.g compare it with 4 top pinned rows vs 2 top and two bottom pinned rows.
  - 4 top pinned (No rows overlay rendered but hidden behind pinned rows)
   image
  - 2 top pinned and 2 bottom pinned (shows as expected)
   image

What do you think?

Comment (DanailH) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:170]: That can also be an option. I'm ok with either one, to be honest.

**Comment by flaviendelangle** [comment]
Is it something that is testable?
We had quite a lot of z-index related issues and I feel like everytime we change something we have 75% chance of breaking something else :laughing:

**Comment by DanailH** [comment]
> Is it something that is testable? We had quite a lot of z-index related issues and I feel like everytime we change something we have 75% chance of breaking something else 😆

hmm I monkey-tested it with what pop-ups, overlays, and tooltips we have 😄

File: packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx (hunk 1 above)
Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:170]: We could also clarify further by having `No unpinned rows` in that case.

File: packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx [hunk 2]
```diff
@@ -170,8 +170,8 @@ const VirtualScrollerPinnedRows = styled('div', {
...
   return {
     position: 'sticky',
-    // should be above the detail panel
-    zIndex: 3,
+    // should be above the no rows overlay
+    zIndex: 5,
```
Comment (romgrk) [inline packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:174]: I like @yaredtsy's suggestion of adding the message over the unpinned content instead of over the whole content, but I'm not strongly opposed to this.

Comment (MBilalShafi) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:174]: Yes, showing the overlay only over the unpinned content + making the text `No unpinned rows` would be a better XP
Or better, 
```js
const message = pinnedRows.length > 0 ? 'No unpinned rows' : 'No rows'
```

Comment (DanailH) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:174]: This combination is probably the best direction. I'll update the PR accordingly.

**Comment by DanailH** [comment]
@romgrk @MBilalShafi I've updated the solution to include your comments. I've moved the `GridOverlays` component to an inner level and added a new `noUnpinnedRowsOverlay` slot component. This is the result

Screenshot 2023-08-15 at 16 00 08

Screenshot 2023-08-15 at 15 59 56

File: packages/grid/x-data-grid/src/components/base/GridOverlays.tsx [hunk 3]
```diff
@@ -97,9 +102,11 @@ export function GridOverlays() {
   const totalRowCount = useGridSelector(apiRef, gridRowCountSelector);
   const visibleRowCount = useGridSelector(apiRef, gridExpandedRowCountSelector);
   const loading = useGridSelector(apiRef, gridRowsLoadingSelector);
+  const pinnedRowsCount = useGridSelector(apiRef, gridPinnedRowsCountSelector);
 
   const showNoRowsOverlay = !loading && totalRowCount === 0;
   const showNoResultsOverlay = !loading && totalRowCount > 0 && visibleRowCount === 0;
+  const snowNoUnpinnedRowsOverlay = !loading && totalRowCount === 0 && pinnedRowsCount > 0;
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/components/base/GridOverlays.tsx:109]: _Optional:_ Do we have customization usecases which require a dedicated slot (`noUnpinnedRowsOverlay`) for this use-case. Could we avoid this slot and use this condition (`pinnedRowCount > 0`) in (`noRowsOverlay`) and render different **localeText** based on it?

**Review by MBilalShafi — APPROVED** [review]
Looks solid 🎉

File: packages/grid/x-data-grid/src/components/base/GridOverlays.tsx (hunk 3 above)
Comment (DanailH) [reply packages/grid/x-data-grid/src/components/base/GridOverlays.tsx:109]: Idk to be honest, I did it like this because it seems to have templates for the different use cases. This does give higher customizability.

File: packages/grid/x-data-grid/src/constants/localeTextConstants.ts [hunk 4]
```diff
@@ -3,6 +3,7 @@ import { GridLocaleText } from '../models/api/gridLocaleTextApi';
 export const GRID_DEFAULT_LOCALE_TEXT: GridLocaleText = {
   // Root
   noRowsLabel: 'No rows',
+  noUnpinnedRowsOverlayLabel: 'No unpinned rows found.',
   noResultsOverlayLabel: 'No results found.',
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/constants/localeTextConstants.ts:7]: Nitpick but the dot at the end of those labels seems a bit off to me. In general our labels don't take final dots because they're not really sentences, I'm wondering why we have one here.

File: packages/grid/x-data-grid/src/components/base/GridOverlays.tsx (hunk 3 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/base/GridOverlays.tsx:109]: +1 to have a single `noRowsOverlay` slot to make the customization easier

File: packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx [hunk 5]
```diff
@@ -443,6 +441,7 @@ const DataGridProVirtualScroller = React.forwardRef<
         </VirtualScrollerPinnedRows>
       ) : null}
       <GridVirtualScrollerContent {...contentProps}>
+        <GridOverlays />
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:444]: This change made the loading overlay move its position on scroll 😅

https://github.com/mui/mui-x/assets/13808724/dc4c4d4b-3c21-47af-bb2c-4aa55c0fdfd0

File: packages/grid/x-data-grid/src/constants/localeTextConstants.ts (hunk 4 above)
Comment (DanailH) [reply packages/grid/x-data-grid/src/constants/localeTextConstants.ts:7]: Good question, Idk to be honest but it looks more correct punctuation wise 🤔

File: packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx (hunk 5 above)
Comment (DanailH) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:444]: mm a bit of investigation - this one would be tricky not only because of the position of the overlay but because if it is `loading` then the overlay needs to cover all the rows (including the pinned ones)

Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:444]: Makes sense, I think leaving the overlay where it was is better then.

Comment (DanailH) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx]: I opted for a 3rd approach - keep the newly created slot and create an additional component `GridInnerOverlay` that is added deeper in the DOM. The result is no breaking changes to existing functionality and still the issue with the pinned columns is resolved.
If this is not an option then we are back to the simple fix of `z-index: 5` 😅

Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx]: Well the simple fix does seem nice in light of this information :sweat_smile: so I would suggest to go back to that at this point.

File: packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx (hunk 2 above)
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:174]: Should we increase zIndex for loading overlay?

Comment (DanailH) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx]: It's not going to work that way. Both the loading and the no rows overlays use the same container that has the `z-index`

Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx]: We can change the zIndex depending on the overlay type, something like this:

```diff
diff --git a/packages/grid/x-data-grid/src/components/base/GridOverlays.tsx b/packages/grid/x-data-grid/src/components/base/GridOverlays.tsx
index 1b1068045..7714e7c14 100644
--- a/packages/grid/x-data-grid/src/components/base/GridOverlays.tsx
+++ b/packages/grid/x-data-grid/src/components/base/GridOverlays.tsx
@@ -21,14 +21,17 @@ const GridOverlayWrapperRoot = styled('div', {
   name: 'MuiDataGrid',
   slot: 'OverlayWrapper',
   overridesResolver: (props, styles) => styles.overlayWrapper,
-})({
+})<{ overlayType: 'loadingOverlay' | string }>(({ overlayType }) => ({
   position: 'sticky', // To stay in place while scrolling
   top: 0,
   left: 0,
   width: 0, // To stay above the content instead of shifting it down
   height: 0, // To stay above the content instead of shifting it down
-  zIndex: 4, // Should be above pinned columns, pinned rows and detail panel
-});
+  zIndex:
+    overlayType === 'loadingOverlay'
+      ? 5 // Should be above pinned columns, pinned rows, and detail panel
+      : 4, // Should be above pinned columns and detail panel
+}));
 
 const GridOverlayWrapperInner = styled('div', {
   name: 'MuiDataGrid',
@@ -49,7 +52,7 @@ const useUtilityClasses = (ownerState: OwnerState) => {
   return composeClasses(slots, getDataGridUtilityClass, classes);
 };
 
-function GridOverlayWrapper(props: React.PropsWithChildren<{}>) {
+function GridOverlayWrapper(props: React.PropsWithChildren<{ overlayType: string }>) {
   const apiRef = useGridApiContext();
   const rootProps = useGridRootProps();
 
@@ -77,7 +80,7 @@ function GridOverlayWrapper(props: React.PropsWithChildren<{}>) {
   }
 
   return (
-    <GridOverlayWrapperRoot className={clsx(classes.root)}>
+    <GridOverlayWrapperRoot className={clsx(classes.root)} overlayType={overlayType}>
       <GridOverlayWrapperInner
         className={clsx(classes.inner)}
         style={{
@@ -102,16 +105,20 @@ export function GridOverlays() {
   const showNoResultsOverlay = !loading && totalRowCount > 0 && visibleRowCount === 0;
 
   let overlay: React.JSX.Element | null = null;
+  let overlayType = '';
 
   if (showNoRowsOverlay) {
+    overlayType = 'noRowsOverlay';
     overlay = <rootProps.slots.noRowsOverlay {...rootProps.slotProps?.noRowsOverlay} />;
   }
 
   if (showNoResultsOverlay) {
+    overlayType = 'noResultsOverlay';
     overlay = <rootProps.slots.noResultsOverlay {...rootProps.slotProps?.noResultsOverlay} />;
   }
 
   if (loading) {
+    overlayType = 'loadingOverlay';
     overlay = <rootProps.slots.loadingOverlay {...rootProps.slotProps?.loadingOverlay} />;
   }
 
@@ -119,5 +126,5 @@ export function GridOverlays() {
     return null;
   }
 
-  return <GridOverlayWrapper>{overlay}</GridOverlayWrapper>;
+  return <GridOverlayWrapper overlayType={overlayType}>{overlay}</GridOverlayWrapper>;
 }

```

Comment (DanailH) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx]: Got it. Updated

Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx]: Personal preference but I don't like too much using strings as constants. I generally do something like this:

```typescript
enum OverlayType {
  NoRows,
  NoResults,
  Loading,
}
```

**Review by cherniavskii — APPROVED** [review]

File: packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx (hunk 2 above)
Comment (DanailH) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx]: Yeah, I feel you. We had this argument so many times that idk to be honest which one is the better way. I honestly would opt for no strings but I know we had an unwritten rule that if something is used only once then we use strings (at least this was in the past).

Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx]: I prefer enums over unions because enums (without default values) use integers instead of strings. In many cases (this one included) it doesn't make much of a difference, but string comparisons can bring the performance down if used carelessly. [Here](https://github.com/json5/json5/pull/278) is an admittedly very specific use-case where string usage causes a 2x slowdown.

I also find enums easier to reason about, they feel less like a hack imho.

Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx]: > https://github.com/json5/json5/pull/278 is an admittedly very specific use-case where string usage causes a 2x slowdown.

Nice, great work! I'm surprised it hasn't been merged yet 😅

> I also find enums easier to reason about, they feel less like a hack IMHO.

I'm fine with using both internally depending on the use case and personal preference 👍🏻

When it comes to the public API and DX, how do you feel about this?

```tsx
import { DataGrid } from '@mui/x-data-grid';
// string union
<DataGrid filterMode="server" />
```

```tsx
import { DataGrid, GridFilterMode } from '@mui/x-data-grid';
// enum
<DataGrid filterMode={GridFilterMode.Server} />
```

I definitely prefer string union, because:
1. No need to import any additional types
2. Autocomplete

Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx]: @MBilalShafi feel free to chime in 🙂

Comment (MBilalShafi) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx]: Some really good arguments made and awesome work with the `parse()` performance PR Rom 🚀 

I kind of agree with preferring the unions, at least for the public API as the users will not have to learn what's a specific enum is called and import it, filterMode="server" is a good example.

But when there's already a learning curve, like with the overlay names, which we define and if customization is needed users will have to know the names anyways. In such cases, enums could make more sense as it looks more readable on top of the slight performance benefit it gives by using integers instead of strings.

Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx]: > Nice, great work! I'm surprised it hasn't been merged yet 😅

I had a feeling the maintainer wouldn't merge. It's good for performance, bad for readability. Did it mostly for fun though :sweat_smile: 

For the public API, I'll agree that unions are more ergonomic. JSX props feel more natural with a string than with an enum.

Internally, for the large majority of cases it won't matter, but imho it would be a good habit to use enums because in the few cases where it matters, we'll already be using the efficient solution.
