### PR TITLE
[pickers] Remove automatic switch between date and time or between range positions

### LINKED ISSUE #11829: [pickers][DateTimeRangePicker] Change OK button behavior
### Steps to reproduce

Link to live example: (required)

Steps:
1. go to basic example
2. input the first calendar date and click ok

https://github.com/mui/mui-x/assets/550141/832b74f1-160f-4eec-8997-c7d99d5ad311

### Current behavior

If users click the OK button on the `start` input, it closes the view.

### Expected behavior

If users click the OK button on the `start` input, it should move to the `end` input.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datetimerangepicker okbutton

### PR DESCRIPTION
**Pull request by flaviendelangle**
Closes #11829

## Changelog

- The view selection process has been updated to make it clear across all Pickers.
  Pickers no longer automatically switch between **date** and **time views** or **start** and **end positions**.
  Moving between views and range positions is achieved using the new "Next" action button.

### CODE REVIEW

File: test/utils/pickers/describeValue/testPickerActionBar.tsx [hunk 1]
```diff
@@ -156,15 +156,15 @@ export const testPickerActionBar: DescribeValueTestSuite<any, 'picker'> = (
...
+          slotProps: { actionBar: { actions: ['accept', 'nextOrAccept'] } },
           closeOnSelect: false,
         });
 
         // Change the value (already tested)
         setNewValue(values[0], { isOpened: true, selectSection, pressKey });
 
         // Accept the modifications
-        fireEvent.click(screen.getByText(/ok/i));
+        fireEvent.click(screen.getAllByRole('button', { name: 'OK' })[0]);
```
Comment (LukasTy) [inline test/utils/pickers/describeValue/testPickerActionBar.tsx:167]: Are there multiple `OK` buttons in the action bar at any time? 🤔

File: test/utils/pickers/describeValue/testPickerOpenCloseLifeCycle.tsx [hunk 2]
```diff
@@ -229,6 +229,11 @@ export const testPickerOpenCloseLifeCycle: DescribeValueTestSuite<PickerValidVal
       expect(onAccept.callCount).to.equal(0);
       expect(onClose.callCount).to.equal(0);
 
+      // Close the picker to reset the range position on range pickers
+      fireEvent.keyDown(document.activeElement!, { key: 'Escape' });
+      expect(onAccept.callCount).to.equal(1);
+      expect(onClose.callCount).to.equal(1);
```
Comment (LukasTy) [inline test/utils/pickers/describeValue/testPickerOpenCloseLifeCycle.tsx:235]: It seems that we are changing the intent of the test. 🤔 
Maybe we should go to the "next" step if there is a `Next` button? 🤔

File: packages/x-date-pickers/src/internals/hooks/usePicker/usePicker.tsx [hunk 3]
```diff
@@ -223,13 +241,15 @@ export const usePicker = <
...
-    setView,
-    view,
-    initialView: initialView ?? views[0],
-    views,
-  });
-  const wrappedGoToNextStep = useEventCallback(stepNavigation.goToNextStep);
+  const wrappedGoToNextStep = useEventCallback(goToNextStep);
+
+  const defaultActionBarActions = React.useMemo<PickersActionBarAction[]>(() => {
+    if (closeOnSelect && !hasSeveralSteps) {
```
Comment (LukasTy) [inline packages/x-date-pickers/src/internals/hooks/usePicker/usePicker.tsx:247]: This causes a behavioral change.
I.e. If `closeOnSelect={false}` on `DesktopDateRangePicker` - we get the `cancel` and `ok` actions. 🤔 

Are we ok with this? 🤔 
I feel like the good old duplication where necessary is sometimes safer. 🙈 😆

**Review by LukasTy — COMMENTED** [review]
LGTM overall, but honestly the regressions on the keyboard behavior (i.e. DesktopTimeRangePicker) seem really annoying. 🙈

File: test/utils/pickers/describeValue/testPickerActionBar.tsx (hunk 1 above)
Comment (flaviendelangle) [reply test/utils/pickers/describeValue/testPickerActionBar.tsx:167]: Yep, when you have `nextOrAccept` and `accept` actions and you are on the last step.
In which case we can click either of them, the result will be the same.

File: test/utils/pickers/describeValue/testPickerOpenCloseLifeCycle.tsx (hunk 2 above)
Comment (flaviendelangle) [reply test/utils/pickers/describeValue/testPickerOpenCloseLifeCycle.tsx:235]: We do go to `Next` inside `setNewValue`
Before this PR, the picker would close at the end of the selection, the test was able to then re-open the picker and select a new value.
I tried keeping this logic, but now I have to manually go back to the 1st step, and to do that I closed the picker (I don't have a previous step).

File: packages/x-date-pickers/src/internals/hooks/usePicker/usePicker.tsx (hunk 3 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePicker/usePicker.tsx:247]: I feel like the new behavior makes more sense
Otherwise, `closeOnSelect={false}` on a `DesktopDateRangePicker` is basically broken without manually overriding the actions.

**Review by noraleonte — APPROVED** [review]
Amazing work! 🎉 🚀 

The behavior seems a lot better to me, and with the new highlighting it's going to be ⭐ 🔥 

Leaving a few comments on the migration guide, but other than that it looks good to me 👌 

@joserodolfofreitas Maybe it's worth mentioning in the blog post?

File: docs/data/migration/migration-pickers-v7/migration-pickers-v7.md [hunk 4]
```diff
@@ -117,7 +125,29 @@ In example: usage of `AdapterDateFnsV3` would be replaced by `AdapterDateFns` an
...
+- The ""**OK**" action has to be clicked to confirm the selection and close the Picker.
+
+Here are a few examples of how the new behavior works:
+
+- On `<DesktopDateTimePicker />`:
+
+  - Previously selecting a date and selecting all time sections automatically closed the Picker.
+  - Now, the user has to click "**OK**" to confirm the selection and close the Picker regardless of the selection process.
+
+- On `<MobileDateTimeRangePicker />`:
```
[the remark this answers is not in the document]
Comment (LukasTy) [reply docs/data/migration/migration-pickers-v7/migration-pickers-v7.md:151]: Added a section: https://github.com/mui/mui-x/pull/17166/commits/529a8dc781f2b4244666402de536e47ea36ef56d 😉

**Review by LukasTy — APPROVED** [review]
Awesome work! 💯 🚀 💙

File: docs/data/migration/migration-pickers-v7/migration-pickers-v7.md [hunk 5]
```diff
@@ -117,7 +125,34 @@ In example: usage of `AdapterDateFnsV3` would be replaced by `AdapterDateFns` an
 
 ## Components breaking changes
 
-### New DOM structure for the field
+### ⚠️ Updated view selection process
+
+The view selection process has been updated to be more clear across all Pickers.
```
Comment (LukasTy) [inline docs/data/migration/migration-pickers-v7/migration-pickers-v7.md:130]:
```suggestion
The view selection process has been updated to make it clearer across all Pickers.
```

File: docs/data/migration/migration-pickers-v7/migration-pickers-v7.md [hunk 6]
```diff
@@ -117,7 +125,34 @@ In example: usage of `AdapterDateFnsV3` would be replaced by `AdapterDateFns` an
...
+Only `<DesktopDatePicker />` and `<DesktopDateRangePicker />` maintain the previous behavior of closing after the selection is complete and switching to end range position when start value is selected.
```
Comment (LukasTy) [inline docs/data/migration/migration-pickers-v7/migration-pickers-v7.md:131]:
```suggestion
Only `<DesktopDatePicker />` and `<DesktopDateRangePicker />` maintain the previous behavior of closing after the selection is complete and switching to the end range position when the start value is selected.
```

File: docs/data/migration/migration-pickers-v7/migration-pickers-v7.md [hunk 7]
```diff
@@ -117,7 +125,34 @@ In example: usage of `AdapterDateFnsV3` would be replaced by `AdapterDateFns` an
...
+In essence, the automatic range position and view switching has been removed in favor of manual confirmation.
```
Comment (LukasTy) [inline docs/data/migration/migration-pickers-v7/migration-pickers-v7.md:132]:
```suggestion
In essence, the automatic range position and view switching have been removed in favor of manual confirmation.
```

File: docs/data/migration/migration-pickers-v7/migration-pickers-v7.md [hunk 8]
```diff
@@ -117,7 +125,34 @@ In example: usage of `AdapterDateFnsV3` would be replaced by `AdapterDateFns` an
...
+The new default behavior for all other cases is as follows:
+
+- Selection on a given view has to be confirmed by clicking "**Next**" action button if there are other selection steps.
```
Comment (LukasTy) [inline docs/data/migration/migration-pickers-v7/migration-pickers-v7.md:135]:
```suggestion
- Selection on a given view has to be confirmed by clicking the "**Next**" action button if there are other selection steps.
```

File: docs/data/migration/migration-pickers-v7/migration-pickers-v7.md [hunk 9]
```diff
@@ -117,7 +125,34 @@ In example: usage of `AdapterDateFnsV3` would be replaced by `AdapterDateFns` an
...
+- The "**Next**" action is replaced with ""**OK**" if there is no next step.
+- The ""**OK**" action has to be clicked to confirm the selection and close the Picker.
```
Comment (LukasTy) [inline docs/data/migration/migration-pickers-v7/migration-pickers-v7.md:137]:
```suggestion
- The "**OK**" action has to be clicked to confirm the selection and close the Picker.
```

File: docs/data/migration/migration-pickers-v7/migration-pickers-v7.md [hunk 10]
```diff
@@ -117,7 +125,34 @@ In example: usage of `AdapterDateFnsV3` would be replaced by `AdapterDateFns` an
...
+Here are a few examples of how the new behavior works:
+
+- On `<DesktopDateTimePicker />`:
+
+  - Previously selecting a date and then selecting all time sections automatically closed the Picker.
+  - Now, the user has to click "**OK**" to confirm the selection and close the Picker regardless of the selection process.
+
+- On `<DesktopDateTimeRangePicker />`:
+
+  - Previously selecting a start date and then selecting all time sections automatically switched to end date selection step. After the last end time section was selected, the Picker closed.
```
Comment (LukasTy) [inline docs/data/migration/migration-pickers-v7/migration-pickers-v7.md:148]:
```suggestion
  - Previously selecting a start date and then selecting all time sections automatically switched to the end date selection step. After the last end time section was selected, the Picker closed.
```

File: docs/data/migration/migration-pickers-v7/migration-pickers-v7.md [hunk 11]
```diff
@@ -117,7 +125,34 @@ In example: usage of `AdapterDateFnsV3` would be replaced by `AdapterDateFns` an
...
+  - Now, the user has to click "**Next**" to confirm the start date and time selection to get to the end date and time selection step. Clicking "**OK**" while on the end date and time step confirms the selection and closes the Picker.
+
+- On `<MobileDateTimeRangePicker />`:
+  - Previously selecting a start date automatically switched to start time selection step. After the last time section was selected, the Picker switched to the end date step.
```
Comment (LukasTy) [inline docs/data/migration/migration-pickers-v7/migration-pickers-v7.md:152]:
```suggestion
  - Previously selecting a start date automatically switched to the start time selection step. After the last time section selection, the Picker switched to the end date step.
```

**Review by LukasTy — COMMENTED** [review]
Some Grammarly typo improvement suggestions.
