### PR TITLE
[DateRangePicker] Generalize the highlight between months

### LINKED ISSUE #8035: [pickers] Selected days not highlighted when using prop showDaysOutsideCurrentMonth
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
[DateRangePicker with showDaysOutsideCurrentMonth prop](https://codesandbox.io/s/boring-feistel-7ykmq0?file=/demo.tsx:2717-2744)

Steps:
1. Select the range 29/01/2023 - 04/02/2023

### Current behavior 😯

When **January** is in view, only the days in January are highlighted.
When **February** is in view, only the days in February are highlighted.

### Expected behavior 🤔

When using DateRangePicker with the showDaysOutsideCurrentMonth prop, all selected days should be highlighted even if they are in different months

### Context 🔦

I want the user to be able to automatically select a week after clicking on a day. When a day is clicked, the week including that day will be selected because in my context it only makes sense to select weeks, hence I used showDaysOutsideCurrentMonth.
I am using DateRangePicker for this, not sure if there is a better component.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.1
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.2
  npmPackages:
    @emotion/react: 11.10.4 => 11.10.4
    @emotion/styled: 11.10.4 => 11.10.4
    @mui/icons-material: 5.11.0 => 5.11.0
    @mui/lab: 5.0.0-alpha.113 => 5.0.0-alpha.113
    @mui/material: 5.11.1 => 5.11.1
    @mui/system: 5.11.1 => 5.11.1
    @mui/types: 7.2.3 => 7.2.3
    @mui/x-data-grid: 6.0.0-alpha.14 => 6.0.0-alpha.14
    @mui/x-data-grid-generator: 6.0.0-alpha.14 => 6.0.0-alpha.14
    @mui/x-data-grid-premium: 6.0.0-alpha.14 => 6.0.0-alpha.14
    @mui/x-data-grid-pro: 6.0.0-alpha.14 => 6.0.0-alpha.14
    @mui/x-date-pickers: 6.0.0-alpha.15 => 6.0.0-alpha.15
    @mui/x-date-pickers-pro: 6.0.0-alpha.15 => 6.0.0-alpha.15
    @types/react: 18.0.27 => 18.0.27
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    styled-components: 5.3.5 => 5.3.5
    typescript: 5.0.0-dev.20230217 => 5.0.0-dev.20230217
```
</details>

Used Chrome

### Order ID 💳 (optional)

54728

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #8035

Having it works for both single calendars and multiple calendars is more challenging than expected.

The reason being we need to round borders for the first and last day of the visible month.

For now, it was done with `ownerState.isStartOfHighlighting || ownerState.isStartOfMonth`. But with days outside of the month, `isStartOfMonth` does not work.

So I had to introduce new props more general such as `isFirstVisibleCell` which is similar to `isStartOfMonth` is `showDaysOutsideCurrentMonth=false`

### CODE REVIEW

File: packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx [hunk 1]
```diff
@@ -64,20 +70,29 @@ const useUtilityClasses = (ownerState: OwnerState) => {
...
-      (isEndOfHighlighting || isEndOfMonth) && 'rangeIntervalDayHighlightEnd',
+      isHighlighting && 'rangeIntervalDayHighlight',
+      isStartOfHighlighting && 'rangeIntervalDayHighlightStart',
+      isEndOfHighlighting && 'rangeIntervalDayHighlightEnd',
+      outsideCurrentMonth && 'rangeIntervalOutsideCurrentMonth',
+      isStartOfMonth && 'rangeIntervalStartOfMonth',
+      isEndOfMonth && 'rangeIntervalEndOfMonth',
+      isFirstVisibleCell && 'rangeIntervalFirstVisibleCell',
+      isLastVisibleCell && 'rangeIntervalLastVisibleCell',
+      isHiddenDayFiller && 'rangeIntervalHiddenDayFiller',
```
Comment (LukasTy) [inline packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx:91]: We should add explicit consumption of these classes allowing direct "slot" override without doing root: 
```js
{[`.&${someClass}`]: { ...rules } }
```
Enabling something like to work:
```js
MuiDateRangePickerDay: {
  styleOverrides: {
    // works
    rangeIntervalDayHighlightStart: {
      backgroundColor: 'olive',
    },
    // doesn't work
    rangeIntervalLastVisibleCell: {
      backgroundColor: 'green',
    },
  },
},
```

**Review by LukasTy — COMMENTED** [review]
Looks nice! 💯 
Great job! 👍 
Leaving a few comments for improvements we can make.

While navigating the api docs I noticed this minor inconsistency.
While we are at it maybe you could add this diff to the changes? 🤔 
```diff
diff --git a/docs/data/date-pickers/date-range-calendar/date-range-calendar.md b/docs/data/date-pickers/date-range-calendar/date-range-calendar.md
index b980cffae..a9272e0e0 100644
--- a/docs/data/date-pickers/date-range-calendar/date-range-calendar.md
+++ b/docs/data/date-pickers/date-range-calendar/date-range-calendar.md
@@ -6,7 +6,7 @@ githubLabel: 'component: DateRangePicker'
 packageName: '@mui/x-date-pickers-pro'
 ---
 
-# Date Calendar [<span class="plan-pro"></span>](/x/introduction/licensing/#pro-plan)
+# Date Range Calendar [<span class="plan-pro"></span>](/x/introduction/licensing/#pro-plan)
 
 <p class="description">The Date Range Calendar lets the user select a range of dates without any input or popper / modal.</p>
 
diff --git a/docs/pages/x/api/date-pickers/date-range-calendar.json b/docs/pages/x/api/date-pickers/date-range-calendar.json
index 1339f3a46..d04923bb8 100644
--- a/docs/pages/x/api/date-pickers/date-range-calendar.json
+++ b/docs/pages/x/api/date-pickers/date-range-calendar.json
@@ -79,6 +79,6 @@
   "forwardsRefTo": "HTMLDivElement",
   "filename": "/packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.tsx",
   "inheritance": null,
-  "demos": "<ul><li><a href=\"/x/react-date-pickers/date-range-calendar/\">Date Calendar </a></li>\n<li><a href=\"/x/react-date-pickers/date-range-picker/\">Date Ran
ge Picker </a></li></ul>",
+  "demos": "<ul><li><a href=\"/x/react-date-pickers/date-range-calendar/\">Date Range Calendar </a></li>\n<li><a href=\"/x/react-date-pickers/date-range-picker/\">Da
te Range Picker </a></li></ul>",
   "packages": [{ "packageName": "@mui/x-date-pickers-pro", "componentName": "DateRangeCalendar" }]
 }
```

File: packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx [hunk 2]
```diff
@@ -222,7 +252,14 @@ const DateRangePickerDayDay = styled(PickersDay, {
   }),
   ...(!ownerState.selected &&
     ownerState.isHighlighting && {
-      color: theme.palette.getContrastText(alpha(theme.palette.primary.light, 0.6)),
+      [`&.${dateRangePickerDayClasses.rangeIntervalOutsideCurrentMonth} .${dateRangePickerDayClasses.day}`]:
+        {
+          color: theme.palette.getContrastText(alpha(theme.palette.primary.light, 0.1)),
```
Comment (LukasTy) [inline packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx:257]: So this is probably the line responsible for this change and it was intentional?
**Before:**
Screenshot 2023-03-02 at 10 46 24

**After:**
Screenshot 2023-03-02 at 10 46 49

File: packages/x-date-pickers-pro/src/DateRangePickerDay/dateRangePickerDayClasses.ts [hunk 3]
```diff
@@ -6,20 +6,32 @@ import {
...
-  /** Styles applied to the root element if `isPreviewing=true` and `outsideCurrentMonth=false`. */
+  /** Styles applied to the root element if `isPreviewing=true`. */
   rangeIntervalDayPreview: string;
-  /** Styles applied to the root element if `isStartOfPreviewing=true` or `day` is the start of the month. */
+  /** Styles applied to the root element if `isStartOfPreviewing=true`. */
   rangeIntervalDayPreviewStart: string;
-  /** Styles applied to the root element if `isEndOfPreviewing=true` or `day` is the end of the month. */
+  /** Styles applied to the root element if `isEndOfPreviewing=true`. */
   rangeIntervalDayPreviewEnd: string;
+  /** Styles applied to the root element if `outsideCurrentMonth=true` */
```
Comment (LukasTy) [inline packages/x-date-pickers-pro/src/DateRangePickerDay/dateRangePickerDayClasses.ts:23]: This description also does not really match the fact that this class "Should" be applied to a selected range outside of the current month.
If we don't want or no longer need it, maybe change the class name to match it? 🤔

**Review by LukasTy — COMMENTED** [review]
Found a few other nitpicks that call for attention. 🙈

File: packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx [hunk 4]
```diff
@@ -64,20 +70,29 @@ const useUtilityClasses = (ownerState: OwnerState) => {
...
   const slots = {
     root: [
       'root',
-      isHighlighting && !outsideCurrentMonth && 'rangeIntervalDayHighlight',
-      (isStartOfHighlighting || isStartOfMonth) && 'rangeIntervalDayHighlightStart',
-      (isEndOfHighlighting || isEndOfMonth) && 'rangeIntervalDayHighlightEnd',
+      isHighlighting && 'rangeIntervalDayHighlight',
+      isStartOfHighlighting && 'rangeIntervalDayHighlightStart',
+      isEndOfHighlighting && 'rangeIntervalDayHighlightEnd',
+      outsideCurrentMonth && 'rangeIntervalOutsideCurrentMonth',
```
[the remark this answers is not in the document]
Comment (alexfauquette) [reply packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx:86]: > but it doesn't make sense having this class when outside of current month dates are not in the selected range and when overriding it looks a bit nasty in case of the following style override

Yes, I used `rangeInterval` like a prefix for all of root classes. I did not realised it was a prefix for days inside the selected range

[the remark this answers is not in the document]
Comment (LukasTy) [reply packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx]: Hm... That's a good point. 🤔 
Maybe I went too quickly to this conclusion...
After looking at the prefixes (class names) we currently have, it sort of makes sense to have it, because the selected days have `DayHighlight` naming.
But maybe that's a call for us to re-evaluate these class names consistency and correctness..? 🤔

[the remark this answers is not in the document]
Comment (alexfauquette) [reply packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx]: I just removed the `rangeInterval` prefix when it was not meaning full

File: packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx (hunk 2 above)
Comment (alexfauquette) [reply packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx]: Finally got it. I thought `&` was referring to the div wrapping the entire day, but it's referring to the button

File: packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx [hunk 5]
```diff
@@ -223,6 +259,9 @@ const DateRangePickerDayDay = styled(PickersDay, {
   ...(!ownerState.selected &&
     ownerState.isHighlighting && {
       color: theme.palette.getContrastText(alpha(theme.palette.primary.light, 0.6)),
+      [`&.${pickersDayClasses.dayOutsideMonth}`]: {
+        color: alpha(theme.palette.getContrastText(theme.palette.primary.light), 0.6),
```
Comment (LukasTy) [inline packages/x-date-pickers-pro/src/DateRangePickerDay/DateRangePickerDay.tsx:263]: Nitpick, but IMHO this could use a bit more alpha to be clearly visible. 🤔 
To me, 0.4 produced a very nice result. 👍

**Review by LukasTy — APPROVED** [review]
Great work and a big improvement! 🙇 🙏

**Comment by TiagoPortfolio** [comment]
Thank you @alexfauquette and @LukasTy , great work in such a short time!
Will this also work for previewing, i.e., will the days outside of the current month have the preview style?

**Comment by LukasTy** [comment]
> Will this also work for previewing, i.e., will the days outside of the current month have the preview style?

Yes, it will. 😉
