### PR TITLE
[DataGrid] Improve flex implementation

### LINKED ISSUE #3091: [DataGrid] Flex values below 1 cause unwanted horizontal scroll
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I would like to add a column that is always at the right end of the grid containing actions. To achieve this I've defined this column with `flex: 0.0001` (arbitrary small number). So in theory:

1. In tables without flex columns, its width fills the remaining empty space
2. In tables with flex columns, it won't use up any additional width

The problem is that in tables with flex columns I get unexpected horizontal scroll when using this column with flex lower than 1.

### Expected behavior 🤔

There shouldn't be any unwanted horizontal scroll if I have a column with flex value lower than 1.

### Steps to reproduce 🕹

Steps:

1. Create a DataGrid with multiple flex columns where one has flex value below 1

[Live demo](https://codesandbox.io/s/datagridpro-v5-quick-start-forked-id97f?file=/src/App.tsx)

### Context 🔦

I would like to have a column that is always at the right most end of the grid.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor                
    Memory: 1.90 GB / 15.92 GB
  Binaries:
    Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Managers:
    Maven: 3.6.3 - C:\Projects\_Tools\apache-maven-3.6.3\bin\mvn.CMD
    pip3: 21.2.3 - C:\Python39\Scripts\pip3.EXE
  Utilities:
    CMake: 3.15.4 - /c/Program Files/CMake/bin/cmake
    Git: 2.33.0. - /cmd/git
  Virtualization:
    Docker: 20.10.7 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  IDEs:
    VSCode: 1.61.2 - C:\Users\betko\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD  
    Visual Studio: 16.3.29324.140 (Visual Studio Community 2019)
  Languages:
    Java: javac 11 - /c/Projects/_Tools/jdk-11/bin/javac
    Perl: 5.34.0 - C:\Program Files\Git\usr\bin\perl.EXE
    PHP: 7.4.10 - C:\Users\betko\AppData\Roaming\php-7.4.10-Win32-vc15-x64\php.EXE
    Python: 3.9.7 - /c/Python39/python
  Browsers:
    Chrome: 95.0.4638.54
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.40)
    Internet Explorer: 11.0.19041.1202
```
</details>

### Order ID 💳 (optional)

#28342

### LINKED ISSUE #3982: [DataGrid] `flex` doesn't work properly
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

`DataGrid` doesn't seem to distribute the width proportionally to `flex` values

### Expected behavior 🤔

Column width should be distributed proportionally according to `flex` values.

Given the following `columns` definition:

```tsx
columns={[
  { field: "id", flex: 2 },
  { field: "username", flex: 1 },
  { field: "age", flex: 1 }
]}
```

I expect `id` column to be 2x wider than `username` or `age` column.
This is the case when using CSS flexbox: https://plnkr.co/edit/PvNn7XNrqkKFcuty?open=lib%2Fscript.js

### Steps to reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/columnsizinggrid-material-demo-forked-dxt67r?file=/demo.tsx
2. Check each column width in DevTools

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by cherniavskii**
Fixes #3982
Fixes #3091

### Motivation

See https://github.com/mui/mui-x/issues/3982

Implementation based on CSS Flexbox specification https://drafts.csswg.org/css-flexbox-1/#remaining-free-space

It's slower than current implementation because it loops over flex columns few times (depending on min/max violations). But:
- there's no way to avoid that if we want `flex` to behave exactly like CSS Flexbox
- `hydrateColumns` is not called too often, so it shouldn't impact the performance much

TODO:
- [x] Unit tests for `computeFlexColumnsWidth` function

### CODE REVIEW

File: packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.ts [hunk 1]
```diff
@@ -31,6 +31,130 @@ export const computeColumnTypes = (customColumnTypes: GridColumnTypesRecord = {}
...
+    // 5b: Calculate the remaining free space
+    flexColumnsLookup.frozenFields.forEach((field) => {
+      remainingFreeSpace -= flexColumnsLookup.all[field].computedWidth;
+      flexUnits -= flexColumnsLookup.all[field].flex!;
+    });
+    for (let i = 0; i < flexColumns.length; i += 1) {
+      const column = flexColumns[i];
+
+      if (
+        flexColumnsLookup.all[column.field] &&
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.ts:101]: Off-topic, but I think we should set `noImplicitAny: true` as soon as possible.
At some point I had a runtime error here, because I've used `flexColumnsLookup[column.field]` instead of `flexColumnsLookup.all[column.field]` and TypeScript didn't pick it up :/

There's an opened issue for it https://github.com/mui/mui-x/issues/479
@joserodolfofreitas can we add it to our backlog?

File: packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx [hunk 2]
```diff
@@ -438,13 +433,52 @@ describe('<DataGrid /> - Layout & Warnings', () => {
...
+            <DataGrid columns={columns} rows={rows} />
+          </div>,
+        );
+
+        expect(getColumnHeaderCell(0).offsetWidth).to.equal(50);
+        expect(getColumnHeaderCell(1).offsetWidth).to.equal(200);
+        expect(getColumnHeaderCell(2).offsetWidth).to.equal(50);
+      });
+
+      it('should ignore `minWidth` on flex columns when computed width is greater', () => {
```
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx:461]: I've approved it in argos, it was the only one that changed

File: packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.ts (hunk 1 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.ts:101]: I worked on it last summer
If you have time you can resume the effort, it's a pain :laughing:

File: packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.test.tsx [hunk 3]
```diff
@@ -0,0 +1,139 @@
+import { expect } from 'chai';
+import { computeFlexColumnsWidth } from './gridColumnsUtils';
+
+describe('gridColumnsUtils', () => {
+  describe('computeFlexColumnsWidth', () => {
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.test.tsx:5]: Feel free to suggest test scenarios if you have some in mind :)

File: packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.ts (hunk 1 above)
Comment (joserodolfofreitas) [reply packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.ts:101]: > There's an opened issue for it #479 @joserodolfofreitas can we add it to our backlog?
Done!
Good find, @cherniavskii!

Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.ts:101]: @cherniavskii #2505 for instance
I enable the rules, fix some TS errors, disable the rule and open a PR.
Doing everything in a single PR is too long.

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.ts:101]: Yeah, I was thinking about doing it gradually as well.
Starting with one package (I'm thinking `x-data-grid-pro`) and eventually reaching the point where we can enable the flag for this specific package (since each package has its own `tsconfig.json`).

Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.ts:101]: Yes now that we have distinct `tsconfig.json` per package it should be easier to advance on that topic

File: packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.test.tsx [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+        totalFlexUnits: getTotalFlexUnits(flexColumns),
+      });
+
+      expect(computedColumns[flexColumns[0].field].computedWidth).to.equal(75);
+      expect(computedColumns[flexColumns[1].field].computedWidth).to.equal(75);
+      expect(computedColumns[flexColumns[2].field].computedWidth).to.equal(50);
+    });
+
+    // https://github.com/mui/mui-x/issues/3091
+    it('should work with `flex` values < 0', () => {
```
Comment (flaviendelangle) [inline packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.test.tsx:68]:
```suggestion
    it('should work with `flex` values < 1', () => {
```

File: packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.test.tsx (hunk 3 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.test.tsx:5]: Maybe a test with 2 columns having max width, one being limited by its max width and the other not.
For instance :

1000px to allocate
Col1 has maxWidth 400
Col2 has maxWidth 800

=> output 400 / 600

File: packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.ts [hunk 5]
```diff
@@ -31,6 +31,130 @@ export const computeColumnTypes = (customColumnTypes: GridColumnTypesRecord = {}
...
+        computedWidth: number;
+        frozen: boolean;
+      }
+    >;
+    frozenFields: GridColDef['field'][];
+    freeze: (field: GridColDef['field']) => void;
+  } = {
+    all: {},
+    frozenFields: [],
+    freeze: function freeze(field: GridColDef['field']) {
```
Comment (flaviendelangle) [inline packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.ts:67]: I think we can avoid using `this`, which can always be a source of confusion when you don't know the code well.

**Review by flaviendelangle — COMMENTED** [review]
This implementation is a lot stronger of course

**Comment by cherniavskii** [comment]
@flaviendelangle 
> Maybe a test with 2 columns having max width, one being limited by its max width and the other not.
> For instance :
>
> 1000px to allocate
> Col1 has maxWidth 400
> Col2 has maxWidth 800
>
> => output 400 / 600

I think it's already there - https://github.com/mui/mui-x/pull/4006/files#diff-877ed0a1b46c1358b40fa12ad241ccda10b0421925abcc52f9c1aac5fba85baaR102
Unless you meant something else?

File: packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.test.tsx (hunk 3 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.test.tsx:5]: I think it's already there - https://github.com/mui/mui-x/pull/4006/files#diff-877ed0a1b46c1358b40fa12ad241ccda10b0421925abcc52f9c1aac5fba85baaR102
Unless you meant something else?

Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsUtils.test.tsx:5]: Here only one of the two columns has a maxWidth

**Review by flaviendelangle — APPROVED** [review]
