### PR TITLE
[DataGrid] Fix: column group change bug

### LINKED ISSUE #12885: [data grid] Error when column groups change
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/blissful-thompson-tq5g2m?file=%2Fsrc%2FDemo.js%3A8%2C28

Steps:
1. Navigate to repro sandbox
2. Wait for table to render
3. Start scrolling horizontally
4. After 5 seconds, error should appear

Repro video:
https://github.com/mui/mui-x/assets/8313853/8194ad90-1cf5-4444-81ac-8bb6efd6c47a

### Current behavior

When column groups change, the table does not react well, throwing an unhandled exception.

### Expected behavior

I would expect the groups to change without incident. If this can not work, I would expect the documentation to state this explicitly with justification.

### Context

We are creating groups dynamically by grouping certain columns together as data loads, and so we run into this issue in our app.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser used: Chrome

  System:
    OS: macOS 14.4.1
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 9.0.5 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 124.0.6367.62
    Edge: 124.0.2478.51
    Safari: 17.4.1
  npmPackages:
    @emotion/react: ~11.11.4 => 11.11.4 
    @emotion/styled: ~11.11.5 => 11.11.5 
    @mui/icons-material: ~5.15.15 => 5.15.15 
    @mui/lab: 5.0.0-alpha.170 => 5.0.0-alpha.170 
    @mui/material: ~5.15.15 => 5.15.15 
    @mui/system: ^5.15.15 => 5.15.15 
    @mui/x-data-grid-pro: ~7.3.0 => 7.3.0 
    react: ~18.2.0 => 18.2.0 
    react-dom: ~18.2.0 => 18.2.0 
```
</details>

**Search keywords**: column groups error

### PR DESCRIPTION
**Pull request by romgrk**
Closes #12885 

Before: https://codesandbox.io/p/sandbox/blissful-thompson-tq5g2m
After: https://codesandbox.io/p/sandbox/brave-cookies-2dzcvk

### CODE REVIEW

**Comment by MBilalShafi** [comment]
@romgrk Is it ok to review this one or do you want to check the failing tests first?

**Comment by romgrk** [comment]
It's ready now.

File: packages/x-data-grid/src/components/GridHeaders.tsx [hunk 1]
```diff
@@ -43,6 +44,7 @@ function GridHeaders() {
 
   const columnMenuState = useGridSelector(apiRef, gridColumnMenuSelector);
   const columnVisibility = useGridSelector(apiRef, gridColumnVisibilityModelSelector);
+  const columnGroupsModel = useGridSelector(apiRef, gridColumnGroupsUnwrappedModelSelector);
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/components/GridHeaders.tsx:47]: Can we move this state extraction to the file where it's being used to avoid some props being drilled down?
```diff
diff --git a/packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx b/packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx
index 8d027322a..3266722a1 100644
--- a/packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx
+++ b/packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx
@@ -28,10 +28,8 @@ import {
   gridColumnPositionsSelector,
   gridVisiblePinnedColumnDefinitionsSelector,
 } from '../columns';
-import {
-  GridGroupingStructure,
-  GridColumnsGroupingState,
-} from '../columnGrouping/gridColumnGroupsInterfaces';
+import { GridGroupingStructure } from '../columnGrouping/gridColumnGroupsInterfaces';
+import { gridColumnGroupsUnwrappedModelSelector } from '../columnGrouping/gridColumnGroupsSelector';
 import { GridScrollbarFillerCell as ScrollbarFiller } from '../../../components/GridScrollbarFillerCell';
 import { getPinnedCellOffset } from '../../../internals/utils/getPinnedCellOffset';
 import { GridColumnHeaderSeparatorSides } from '../../../components/columnHeaders/GridColumnHeaderSeparator';
@@ -58,7 +56,6 @@ export interface UseGridColumnHeadersProps {
   headerGroupingMaxDepth: number;
   columnMenuState: GridColumnMenuState;
   columnVisibility: GridColumnVisibilityModel;
-  columnGroupsModel: GridColumnsGroupingState['unwrappedGroupingModel'];
   columnGroupsHeaderStructure: GridGroupingStructure[][];
   hasOtherElementInTabSequence: boolean;
 }
@@ -92,7 +89,6 @@ export const useGridColumnHeaders = (props: UseGridColumnHeadersProps) => {
     headerGroupingMaxDepth,
     columnMenuState,
     columnVisibility,
-    columnGroupsModel,
     columnGroupsHeaderStructure,
     hasOtherElementInTabSequence,
   } = props;
@@ -104,7 +100,7 @@ export const useGridColumnHeaders = (props: UseGridColumnHeadersProps) => {
   const theme = useTheme();
   const rootProps = useGridRootProps();
   const hasVirtualization = useGridSelector(apiRef, gridVirtualizationColumnEnabledSelector);
-
+  const columnGroupsModel = useGridSelector(apiRef, gridColumnGroupsUnwrappedModelSelector);
   const dimensions = useGridSelector(apiRef, gridDimensionsSelector);
   const columnPositions = useGridSelector(apiRef, gridColumnPositionsSelector);
   const renderContext = useGridSelector(apiRef, gridRenderContextColumnsSelector);
```

**Review by MBilalShafi — APPROVED** [review]
I couldn't reproduce the issue anymore 👍 
Apart from one minor suggestion, it LGTM.

**Comment by cherniavskii** [comment]
Thanks for fixing it, I think I experienced the same issue when working on pivoting 👍🏻
