### PR TITLE
[data grid][pickers][tree-view] Fix shortcut with localization keyboard

### LINKED ISSUE #14219: [data grid] Copy & Paste on Cells using localize keyboard
### Steps to reproduce

Link to live example: (required)
https://mui.com/x/react-data-grid/clipboard/

Steps:
1. Copy&Paste working using only English localization Keyboard
2. Using Hebrew for example will not work, because the function is looking for the "v" key, instead of the KeyC
3. inside packages\x-data-grid-premium\src\hooks\features\clipboard,
handleCopy func:
https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/clipboard/useGridClipboard.ts
4. same thing for the paste shortcut,
image

### Current behavior

English language localization - Copy&Paste work
Changing to other Language (Computer) - Copy&Paste fail

### Expected behavior

Copy&Paste work on all localizations

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: copy paste copy&paste keyboard cell cells x-data-grid-premium

### PR DESCRIPTION
**Pull request by rotembarsela**
Closes #14219 

We also fix the date picker and tree view shortcuts.

### CODE REVIEW

File: packages/x-data-grid/src/utils/keyboardUtils.ts [hunk 1]
```diff
@@ -57,11 +57,23 @@ export const isHideMenuKey = (key: React.KeyboardEvent['key']) => isTabKey(key)
...
     (event.ctrlKey || event.metaKey) &&
-    event.key.toLowerCase() === 'v' &&
+    event.code === 'KeyV' &&
     !event.shiftKey &&
     !event.altKey
   ) {
     return true;
   }
   return false;
 }
```
Comment (michelengelen) [inline packages/x-data-grid/src/utils/keyboardUtils.ts:67]: I guess this could also be simplified

```tsx
export function isPasteShortcut(event: React.KeyboardEvent) {
  return (event.ctrlKey || event.metaKey) && event.code === 'KeyV' && !event.shiftKey && !event.altKey
}
```

File: packages/x-data-grid/src/utils/keyboardUtils.ts [hunk 2]
```diff
@@ -57,11 +57,23 @@ export const isHideMenuKey = (key: React.KeyboardEvent['key']) => isTabKey(key)
 export function isPasteShortcut(event: React.KeyboardEvent) {
   if (
     (event.ctrlKey || event.metaKey) &&
-    event.key.toLowerCase() === 'v' &&
```
Comment (michelengelen) [inline packages/x-data-grid/src/utils/keyboardUtils.ts:60]: not sure what the implications are ... we would definitely need some tests to secure this change

Comment (rotembarsela) [reply packages/x-data-grid/src/utils/keyboardUtils.ts:60]: it is the same issue as the CTRL+C shortcut, i will fix the test cases and push the changes

Comment (oliviertassinari) [reply packages/x-data-grid/src/utils/keyboardUtils.ts:60]: Related to https://github.com/mui/mui-x/pull/3660/files#r793084149

File: packages/x-data-grid/src/utils/keyboardUtils.ts [hunk 3]
```diff
@@ -57,11 +57,23 @@ export const isHideMenuKey = (key: React.KeyboardEvent['key']) => isTabKey(key)
...
+    event.code === 'KeyV' &&
```
Comment (oliviertassinari) [inline packages/x-data-grid/src/utils/keyboardUtils.ts:60]: This can't work, e.g.  event.code assumes a QWERTY keyboard layout which would be wrong with a Dvorak keyboard.

**Review by oliviertassinari — DISMISSED** [review]

File: packages/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts [hunk 4]
```diff
@@ -349,6 +349,7 @@ export const useGridClipboardImport = (
       if (!enableClipboardPaste) {
         return;
       }
+
```
Comment (oliviertassinari) [inline packages/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts:352]:
```suggestion
```

File: packages/x-data-grid/src/utils/keyboardUtils.ts (hunk 2 above)
Comment (oliviertassinari) [reply packages/x-data-grid/src/utils/keyboardUtils.ts:60]: Ok, so it seems that I broke it with https://github.com/mui/mui-x/pull/9220/files#r1216831312. 

I can reproduce the bug 

SCR-20240817-ufoh

and only `String.fromCharCode(event.keyCode)` seems to be usable to detect the shortcut correctly.

File: packages/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationInterfaces.ts [hunk 5]
```diff
@@ -74,7 +74,7 @@ export interface GridAggregationFunction<V = any, AV = V> {
   getCellValue?: (params: GridAggregationGetCellValueParams) => V;
 }
 
-interface GridAggregationParams<V = any> {
+export interface GridAggregationParams<V = any> {
```
Comment (oliviertassinari) [inline packages/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationInterfaces.ts:77]:
```suggestion
interface GridAggregationParams<V = any> {
```

File: scripts/x-data-grid-premium.exports.json [hunk 6]
```diff
@@ -95,6 +95,7 @@
   { "name": "gridAggregationLookupSelector", "kind": "Variable" },
   { "name": "GridAggregationModel", "kind": "TypeAlias" },
   { "name": "gridAggregationModelSelector", "kind": "Variable" },
+  { "name": "GridAggregationParams", "kind": "Interface" },
```
Comment (oliviertassinari) [inline scripts/x-data-grid-premium.exports.json:98]:
```suggestion
```

File: scripts/README.md [hunk 7]
```diff
@@ -30,7 +30,12 @@ pnpm release:changelog
 > `<!--/ DO_NOT_REMOVE /-->`
 > This string needs to stay where it gets inserted for the automated discord announcement to work.
 
+<<<<<<< HEAD
 You can also provide the GitHub token by setting `process.env.GITHUB_TOKEN` variable.
+=======
+You can also provide the github token by setting `process.env.GITHUB_TOKEN` variable.
+
+> > > > > > > dd20afe2668c15eb9f350ab171137c4f64931273
```
Comment (oliviertassinari) [inline scripts/README.md:38]:
```suggestion
You can also provide the GitHub token by setting `process.env.GITHUB_TOKEN` variable.
```

File: packages/x-data-grid/src/utils/keyboardUtils.ts [hunk 8]
```diff
@@ -45,13 +45,20 @@ export const isHideMenuKey = (key: React.KeyboardEvent['key']) => key === 'Tab'
 // In theory, on macOS, ctrl + v doesn't trigger a paste, so the function should return false.
 // However, maybe it's overkill to fix, so let's be lazy.
 export function isPasteShortcut(event: React.KeyboardEvent) {
-  if (
+  return (
     (event.ctrlKey || event.metaKey) &&
-    event.key.toLowerCase() === 'v' &&
+    String.fromCharCode(event.keyCode) === 'V' &&
```
Comment (oliviertassinari) [inline packages/x-data-grid/src/utils/keyboardUtils.ts:50]:
```suggestion
    // We can't use event.code === 'KeyV' as event.code assumes a QWERTY keyboard layout,
    // for example, it would be another letter on a Dvorak physical keyboard.
    // We can't use event.key === 'v' as event.key is not stable with key modifiers and keyboard layouts,
    // for example, it would be ה on Hebrew a keyboard layout.
    String.fromCharCode(event.keyCode) === 'V' &&
```

File: packages/x-data-grid/src/utils/keyboardUtils.ts [hunk 9]
```diff
@@ -45,13 +45,24 @@ export const isHideMenuKey = (key: React.KeyboardEvent['key']) => key === 'Tab'
...
 // However, maybe it's overkill to fix, so let's be lazy.
 export function isPasteShortcut(event: React.KeyboardEvent) {
-  if (
+  return (
     (event.ctrlKey || event.metaKey) &&
-    event.key.toLowerCase() === 'v' &&
+    // We can't use event.code === 'KeyV' as event.code assumes a QWERTY keyboard layout,
+    // for example, it would be another letter on a Dvorak physical keyboard.
+    // We can't use event.key === 'v' as event.key is not stable with key modifiers and keyboard layouts,
+    // for example, it would be ה on Hebrew a keyboard layout.
```
Comment (oliviertassinari) [inline packages/x-data-grid/src/utils/keyboardUtils.ts:53]:
```suggestion
    // for example, it would be ה on a Hebrew keyboard layout.
```

**Comment by oliviertassinari** [comment]
I have added some comments to help in the future, we have had so many iterations of this logic, so to make sure we build **up**. This looks good 👍, I have unsubscribed to notifications.

**Comment by oliviertassinari** [comment]
The date picker has the same problem:

https://github.com/mui/mui-x/blob/b217a276988e3942be4c5a2776705b836fc00fdb/packages/x-date-pickers/src/internals/hooks/useField/useField.ts#L128

**Comment by rotembarsela** [comment]
> The date picker has the same problem:
> 
> https://github.com/mui/mui-x/blob/b217a276988e3942be4c5a2776705b836fc00fdb/packages/x-date-pickers/src/internals/hooks/useField/useField.ts#L128

I think you forgot about handlePaste, it has the same problem, #43361

> The date picker has the same problem:
> 
> https://github.com/mui/mui-x/blob/b217a276988e3942be4c5a2776705b836fc00fdb/packages/x-date-pickers/src/internals/hooks/useField/useField.ts#L128

isPasteShortcut func has the same problem when trying to paste after the CTRL+C event,
https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/utils/keyboardUtils.ts

**Review by oliviertassinari — APPROVED** [review]
This looks good on my end
