### PR TITLE
[DateRangePicker] Add accessible name to calendar grid

### LINKED ISSUE #13534: [pickers] DateRangeCalendar `grid` is missing it's accessible name
### Steps to reproduce

Link to live example: https://mui.com/x/react-date-pickers/date-range-picker/#basic-usage

Steps:
1. on the above page open google chrome dev tools accessibility panel
2. open the DateRangePickers calendar
3. notice the `grid` missing a accessible name.

### Current behavior

The `grid` in the calendar does not have an accessible name.

### Expected behavior

The `grid` would have an accessible name of the current month/year.

DateRangePicker Today:
Screenshot 2024-06-18 at 9 23 52 AM

Compared to DatePicker Today:
Screenshot 2024-06-18 at 9 22 49 AM

### Context

The `grid` lacking an accessible name is bad for accessibility. Additionally it makes it very hard to query for a day relative to the correct calendar. In order to query for a day on the calendar in the same way that a visual user would should be something like this:
```
within(screen.getByRole('grid', {name: "January 2024"})).getByRole('gridcell', {name: "18"});
```

### Your environment

_No response_

**Search keywords**: DateRangePicker, DateRangeCalendar, accessibility, grid
**Order ID**: 82849

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #13534

- Add `id` and `aria-labelledby` relationship to `DateRangeCalendar` same as we have for `DateCalendar`.
- Update tests to benefit from this relationship instead of accessing parent elements and relying on consistent DOM.

### CODE REVIEW

File: packages/x-date-pickers-pro/src/PickersRangeCalendarHeader/PickersRangeCalendarHeader.tsx [hunk 1]
```diff
@@ -76,6 +78,7 @@ const PickersRangeCalendarHeader = React.forwardRef(function PickersRangeCalenda
       nextLabel={localeText.nextMonth}
       slots={slots}
       slotProps={slotProps}
+      labelId={`${labelId}-${monthIndex}-label`}
```
Comment (flaviendelangle) [inline packages/x-date-pickers-pro/src/PickersRangeCalendarHeader/PickersRangeCalendarHeader.tsx:81]: Could we just pass this ID from `DateRangeCalendar` instead of re-building it here?
So that people with a custom implementation of the header get this for free?

We would just have to move the definition of `labelId` from the `useSlotProps` to the JSX part in `DateRangeCalendar` like we do for `monthIndex`.

Comment (LukasTy) [reply packages/x-date-pickers-pro/src/PickersRangeCalendarHeader/PickersRangeCalendarHeader.tsx]: Thanks for a great observation! 🙏 
IMHO, it also cleaned the code up a bit.
I also added a JSDoc for this prop and thus there are some additional proptypes & API docs changes.

**Review by flaviendelangle — APPROVED** [review]
Looks great! :heart: 
Thanks for taking care of it
