### PR TITLE
[DataGridPro] Fix Tree Data and Row Grouping rows accessibility

### LINKED ISSUE #10032: [data grid] Expandable rows are not accessible
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

https://mui.com/x/react-data-grid/tree-data/

Steps:

1. Expand one of the rows
2. Inspect the accessibility tree

Order ID: 65425

### Current behavior 😯

The current data grid example for expandable rows is not accessible as it does not follow an the correct pattern.

To illustrate the issue, lets look at the component and its the accessibility tree:

Component

Accessibility tree, annotated to show missing aria properties

As the accessibility tree illustrates, there is nothing to relate to non-sighted users that one of the rows is expanded and that some of the rows are child rows of another.

### Expected behavior 🤔

When expandable rows are present the [Treegrid pattern](https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/) should be employed.

From an aria property point of view, this means adding properties like:
- `role=treegrid` to indicate this is a tree grid
- `aria-level` to determine the depth
- `aria-expanded` to say if the current row is expanded (leave it `undefined` to say this is a leaf node)
- `aria-setsize` to determine how many children there are
- `aria-posinset` to say what item you are on at the current level

I've not had a proper look at the keyboard interactions. They may be fine as or or require some changes too.

### Context 🔦

We've started using MUI recently, and are looking to replace our expandable row patterns with poor accessibility with standard approaches, and were hoping MUI had an out-of-the-box solution.

We pay for MUI-X, and were hoping data-grid would implement these correctly, but that doesn't seem to currently be the case.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```

Chrome Version 115.0.5790.171 (Official Build) (64-bit)

</details>

### PR DESCRIPTION
**Pull request by arminmeh**
Fixes #10032 

Used this as a reference
https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/examples/treegrid-1/

Also fixes the issue with the value of `aria-rowcount` as it was not updated after filtering
https://github.com/w3c/aria-practices/issues/465

### CODE REVIEW

File: packages/x-data-grid-pro/src/components/GridRow.tsx
[the remark this answers is not in the document]
Comment (arminmeh) [reply packages/x-data-grid-pro/src/components/GridRow.tsx:1]: I have moved the code to the hook, that makes it cleaner.

Regarding the wrapper, I made it specifically to avoid adding anything to the community version of the grid, since this is only needed when the tree data feature is enabled.

If the performance impact is significant, I am happy to move it.
Is your suggestion to use api to allow override?

[the remark this answers is not in the document]
Comment (arminmeh) [reply packages/x-data-grid-pro/src/components/GridRow.tsx:1]: Failing test shows me that it indeed impacts the performance, so I will have to make some adjustments here in any case

[the remark this answers is not in the document]
Comment (arminmeh) [reply packages/x-data-grid-pro/src/components/GridRow.tsx:1]: Logic is moved to a pipe processor for the tree grid

File: packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx [hunk 1]
```diff
@@ -204,6 +208,42 @@ export const useGridTreeDataPreProcessors = (
...
+
+      const filteredDescendantCount = filteredDescendantCountLookup[rowNode.id] ?? 0;
+      // aria-expanded should only be added to the rows that contain children
+      if (rowNode.type === 'group' && filteredDescendantCount > 0) {
+        ariaAttributes['aria-expanded'] = Boolean(rowNode.childrenExpanded);
+      }
+
+      // if the parent is null, set size and position cannot be determined
+      if (rowNode.parent !== null) {
+        ariaAttributes['aria-setsize'] =
```
Comment (cherniavskii) [inline packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx:235]: Should `aria-setsize` only reflect the number of direct children?

Comment (arminmeh) [reply packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx:235]: that is correct
used children.length before, but that is not the same as the selector count 
I will update this and add a test to cover this case

File: packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx
Comment (MBilalShafi) [inline packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx:1]: What do you think would be the accessibility requirements for the [lazily-loaded tree data](https://mui.com/x/react-data-grid/server-side-data/tree-data/)?

I assume it should add the correct aria attributes for the loaded tree or the nodes with known children count. Not sure what would be the `aria-setsize` value for the parents with unknown children count. Does the pattern support `-1` for that use case?

We might need to add the pipe processing listener method to `useGridDataSourceTreeDataPreProcessors` and make them run mutually exclusively. (Might need a master rebase since it was merged fairly recently)

File: packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx [hunk 2]
```diff
@@ -40,14 +41,15 @@ const DataGridPremiumRaw = React.forwardRef(function DataGridPremium<R extends G
 ) {
   const props = useDataGridPremiumProps(inProps);
   const privateApiRef = useDataGridPremiumComponent(props.apiRef, props);
-
+  const hooks = { useGridRowAriaAttributes };
+  const configuration = { hooks };
```
Comment (romgrk) [inline packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx:45]: These need to be defined outside of the component. Because they're objects they will trigger a re-render of every useContext otherwise.

File: packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx (hunk 1 above)
Comment (arminmeh) [reply packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx]: Updated. Added children count lookup to the existing filter state

File: packages/x-data-grid-pro/src/components/GridRow.tsx
[the remark this answers is not in the document]
Comment (arminmeh) [reply packages/x-data-grid-pro/src/components/GridRow.tsx:1]: As per conversation on Slack, additional context provider is created to allow overrides

File: packages/x-data-grid/src/components/GridRow.tsx [hunk 3]
```diff
@@ -140,12 +140,12 @@ const GridRow = React.forwardRef<HTMLDivElement, GridRowProps>(function GridRow(
     ...other
   } = props;
   const apiRef = useGridApiContext();
+  const gridConfiguration = useGridConfigurationContext();
```
Comment (romgrk) [inline packages/x-data-grid/src/components/GridRow.tsx:143]: I would rename to use:
```js
const configuration = useGridConfiguration()
```
I find it a bit verbose in its current format.

File: packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx (hunk 2 above)
Comment (arminmeh) [reply packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx]: Updated, thanks 🙂

File: packages/x-data-grid/src/components/GridRow.tsx (hunk 3 above)
Comment (arminmeh) [reply packages/x-data-grid/src/components/GridRow.tsx]: I agree. Updated

Comment (romgrk) [reply packages/x-data-grid/src/components/GridRow.tsx]: And `gridConfiguration` to `configuration` as well. The grid prefix is only for exported stuff, it's too verbose to prefix everything with "grid".

File: packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx
Comment (arminmeh) [reply packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx:1]: Based on these

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-setsize
> The value is the same for each item: an integer reflecting number of items in the complete set, or -1 if the set size is unknown
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-rowcount
> If the total number of rows is not known, include aria-rowcount="-1", which tells the browser to not count the total number of rows.

It looks like that indeed `-1` should be used as value for both `aria-setsize` and `aria-rowcount`,
but I couldn't find anything that suggests that the values for `aria-rowindex` and `aria-posinset` should be set differently. It seems that those are set with the data that you have at the moment

I see that in our response we get `rowCount`, so I guess that can be used to fill in the `aria-rowcount`
Maybe the response should also include set size in case you are fetching the children and we can use that for the `aria-setsize` value (and fallback to -1 if one of those is not returned)

File: packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx:1]: Comments on performance. Using `useGridSelector` to manage reactivity in the grid was done as a transition from the "rerender everything everytime" situation that we had previously, [see discussion here](https://github.com/mui/mui-x/discussions/9001). Although it allowed us to improve performance, it's still an imperfect solution because each time it's used, it adds one event listener to the grid store/state, until we switch to [event-based reactivity](https://mui-org.slack.com/archives/C05SBSU8NPR/p1709682177999449). So for each `useGridSelector` that we use in a row/cell component, we add tens or hundreds of event listeners that run on each state update. For that reason, I've often opted to select a bigger slice of the state in the parent of the rows, and pass the state as props down the tree.

I'm not saying you shouldn't use `useGridSelector` for this hook, but be mindful about the performance implications, and measure the performance impact on scrolling performance to ensure there's no regression.

File: packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+      if (selectedIdsLookup[rowId]) {
+        ariaAttributes['aria-selected'] = true;
+      }
+
+      return ariaAttributes;
+    },
+    [apiRef, selectedIdsLookup, headerGroupingMaxDepth],
+  );
+
+  return { getRowAriaAttributes };
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx:35]: Can we just return the function? The object wrapper creates another allocation each time this is ran.

Comment (arminmeh) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx]: Updated

File: packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx
Comment (MBilalShafi) [reply packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx:1]: > Maybe the response should also include set size in case you are fetching the children and we can use that for the aria-setsize value (and fallback to -1 if one of those is not returned)

We have a method `getChildrenCount` to compute the aria-setsize. It's currently being used to show the row count, it also supports `-1` for the unknown use case. Could it be used to set the `aria-setsize` value?

Comment (arminmeh) [reply packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx:1]: I will rebase with the main branch and try to add it in this PR

Comment (arminmeh) [reply packages/x-data-grid-pro/src/hooks/features/treeData/useGridTreeDataPreProcessors.tsx:1]: I have re-used the `getChildrenCount` call and updated the row prop from `hasServerChildren` to `serverChildrenCount`. That way, I can easily fill in children count lookup that is being used by the aria attributes hook.
since the data source is still unstable, I guess that the change is fine

File: packages/x-data-grid-pro/src/hooks/features/serverSideTreeData/useGridDataSourceTreeDataPreProcessors.tsx [hunk 5]
```diff
@@ -151,7 +151,7 @@ export const useGridDataSourceTreeDataPreProcessors = (
           path: [...parentPath, getGroupKey(params.dataRowIdToModelLookup[rowId])].map(
             (key): RowTreeBuilderGroupingCriterion => ({ key, field: null }),
           ),
-          hasServerChildren: !!count && count !== 0,
+          serverChildrenCount: count,
```
Comment (arminmeh) [inline packages/x-data-grid-pro/src/hooks/features/serverSideTreeData/useGridDataSourceTreeDataPreProcessors.tsx:154]: Reason
https://github.com/mui/mui-x/pull/13623#discussion_r1673672031

File: packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+    apiRef,
+    gridExpandedSortedRowIdsLookupSelector,
+  );
+
+  return React.useCallback(
+    (rowId: GridRowId, index: number) => {
+      const rowNode = apiRef.current.getRowNode(rowId);
+      const ariaAttributes = getRowAriaAttributesCommunity(rowId, index);
+
+      if (rowNode === null || props.treeData !== true) {
```
Comment (cherniavskii) [inline packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx:34]: This might be a topic for a follow-up PR, but should we reuse the same ARIA attributes for the row grouping as well?
Looking at https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/treegrid_role, I think we should also set `role="treegrid"` when row grouping is enabled.

**Review by cherniavskii — APPROVED** [review]

File: packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx (hunk 6 above)
Comment (arminmeh) [reply packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx]: I have added it in this PR

File: packages/x-data-grid-pro/src/hooks/features/serverSideTreeData/utils.ts [hunk 7]
```diff
@@ -3,16 +3,20 @@ import { getTreeNodeDescendants } from '@mui/x-data-grid/internals';
...
   const filteredRowsLookup: Record<GridRowId, boolean> = {};
+  const filteredChildrenCountLookup: Record<GridRowId, number> = {};
   const filteredDescendantCountLookup: Record<GridRowId, number> = {};
 
   const nodes = Object.values(rowTree);
   for (let i = 0; i < nodes.length; i += 1) {
     const node: any = nodes[i];
     filteredRowsLookup[node.id] = true;
+    filteredChildrenCountLookup[node.id] =
+      node.serverChildrenCount !== undefined ? node.serverChildrenCount : -1;
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/hooks/features/serverSideTreeData/utils.ts:14]:
```suggestion
    filteredChildrenCountLookup[node.id] =
      node.serverChildrenCount ?? -1;
```

File: packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx [hunk 8]
```diff
@@ -0,0 +1,34 @@
...
+import { useGridPrivateApiContext } from '../../utils/useGridPrivateApiContext';
+
+export const useGridRowAriaAttributes: GridRowInternalHook = () => {
+  const apiRef = useGridPrivateApiContext();
+  const selectedIdsLookup = useGridSelector(apiRef, selectedIdsLookupSelector);
+  const headerGroupingMaxDepth = useGridSelector(apiRef, gridColumnGroupsHeaderMaxDepthSelector);
+
+  return React.useCallback(
+    (rowId: GridRowId, index: number) => {
+      const rowNode = apiRef.current.getRowNode(rowId);
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx:16]: Fyi, some API methods are [basically just hidden selectors](https://github.com/mui/mui-x/blob/83c7554732b56d69abc1bb55a67046371084e2ae/packages/x-data-grid/src/hooks/features/rows/useGridRows.ts#L298). I'm not sure if you meant for this to be reactively bound though.

File: packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx
Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx:1]: I couldn't find a significant impact on performance, the `Store.update` are still within the same bounds as before:

image

File: packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx [hunk 9]
```diff
@@ -0,0 +1,69 @@
...
+    apiRef,
+    gridExpandedSortedRowIdsLookupSelector,
+  );
+
+  const addAttributes =
+    addTreeDataAttributes !== undefined ? addTreeDataAttributes : props.treeData === true;
+
+  return React.useCallback(
+    (rowId: GridRowId, index: number) => {
+      const rowNode = apiRef.current.getRowNode(rowId);
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx:34]: Same comment as https://github.com/mui/mui-x/pull/13623#discussion_r1680371383

File: packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx (hunk 8 above)
Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx:16]: `rowNode` is already fetched in `GridRow`, so you could pass it as a parameter here instead. It's not reactively bound in `GridRow` but it doesn't seem to have caused any bug as far as I know.

File: packages/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts [hunk 10]
```diff
@@ -96,6 +106,40 @@ export const gridFilteredSortedRowIdsSelector = createSelectorMemoized(
   (filteredSortedRowEntries) => filteredSortedRowEntries.map((row) => row.id),
 );
 
+/**
+ * Get the row ids accessible after the filtering process to position in the current tree level lookup.
+ * Does not contain the collapsed children.
+ * @category Filtering
+ */
+export const gridExpandedSortedRowIdsLookupSelector = createSelectorMemoized(
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts:114]: So IIUC, this one returns a count? The name sounds like it returns row ids, imho.

Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts:114]: And do we need to make this one public or could we `@ignore` it?

File: packages/x-data-grid/src/hooks/utils/useGridAriaAttributes.tsx [hunk 11]
```diff
@@ -2,30 +2,32 @@ import { gridVisibleColumnDefinitionsSelector } from '../features/columns/gridCo
...
+  const accessibleRowCount = useGridSelector(apiRef, gridExpandedRowCountSelector);
   const headerGroupingMaxDepth = useGridSelector(apiRef, gridColumnGroupsHeaderMaxDepthSelector);
   const pinnedRowsCount = useGridSelector(apiRef, gridPinnedRowsCountSelector);
 
   let role = 'grid';
-  if ((rootProps as any).treeData) {
+  if (
+    (rootProps as any).treeData ||
+    (rootProps as any).rowGroupingModel ||
+    (rootProps as any).initialState?.rowGrouping
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/utils/useGridAriaAttributes.tsx:22]: Why do we check the initial state? Would it be possible to cause a bug if the initial state has a row grouping entry, but later on the row grouping is removed?

File: packages/x-data-grid/src/models/gridRows.ts [hunk 12]
```diff
@@ -116,9 +116,9 @@ export interface GridDataGroupNode extends GridBasicGroupNode {
 
 export interface GridDataSourceGroupNode extends GridDataGroupNode {
   /**
-   * If true, this node has children on server.
+   * Number of children this node has on the server. Returns `-1` if unknown.
```
Comment (romgrk) [inline packages/x-data-grid/src/models/gridRows.ts:119]: I think `-1` means "non-zero", not just "unknown".

Comment (romgrk) [reply packages/x-data-grid/src/models/gridRows.ts:119]: cc @MBilalShafi could confirm

Comment (MBilalShafi) [reply packages/x-data-grid/src/models/gridRows.ts:119]: Yes, `-1` would mean there _are_ some children but the count is unknown.

Comment (MBilalShafi) [inline packages/x-data-grid/src/models/gridRows.ts:119]:
```suggestion
   * Number of children this node has on the server. Returns `-1` if there are some children but the count is unknown.
```

File: packages/x-data-grid/src/models/gridRows.ts [hunk 13]
```diff
@@ -116,9 +116,9 @@ export interface GridDataGroupNode extends GridBasicGroupNode {
...
    */
-  hasServerChildren: boolean;
+  serverChildrenCount?: number;
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/models/gridRows.ts:121]: Shouldn't it always have a value for the `GridDataSourceGroupNode`, at least as per the [signature](https://github.com/mui/mui-x/blob/8534f2db66707596a1aad7e641826124fa16e6a0/packages/x-data-grid/src/models/gridDataSource.ts#L72-L77) of `getChildrenCount` prop?

Did you find some cases where it could be passed as `undefined`?
```suggestion
  serverChildrenCount: number;
```

File: packages/x-data-grid-pro/src/hooks/features/serverSideTreeData/utils.ts (hunk 7 above)
Comment (MBilalShafi) [inline packages/x-data-grid-pro/src/hooks/features/serverSideTreeData/utils.ts:14]: I am wondering what will happen if a user uses the `getChildrenCount` as:
```tsx
function getChildrenCount(row) {
  if (row.hasChildren) { // for group nodes
    return row.childrenCount;
  }
  return undefined; // for leaf nodes
}
```

Or simply:
```tsx
function getChildrenCount(row) {
  if (row.hasChildren) { // for group nodes
    return row.childrenCount;
  }
}
```

This might not be the best usage as per the types, but we may expect someone to interpret it this way. So falling back to `-1` when `count='undefined'` might make the grid misinterpret this state value. Alternatively, could we expect `-1` to be explicitly passed by the users, to treat the default node as a leaf node (having `0` children), something like: 

```suggestion
      node.serverChildrenCount ?? 0;
```

What do you think?

**Review by MBilalShafi — COMMENTED** [review]
Looks great, really nice work 👏 
Dropped a few small nits/comments.

File: packages/x-data-grid-pro/src/utils/tree/insertDataRowInTree.ts [hunk 14]
```diff
@@ -99,7 +99,7 @@ export const insertDataRowInTree = ({
       // We create a leaf node for the data row.
       if (existingNodeIdWithPartialPath == null) {
         let node: GridLeafNode | GridDataSourceGroupNode;
-        if (hasServerChildren) {
+        if (serverChildrenCount !== undefined && serverChildrenCount !== 0) {
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/x-data-grid-pro/src/utils/tree/insertDataRowInTree.ts:102]: I find the current version more readable than the short one, in this context.

File: packages/x-data-grid/src/hooks/features/filter/useGridFilter.tsx [hunk 15]
```diff
@@ -46,6 +46,7 @@ export const filterStateInitializer: GridStateInitializer<
     filter: {
       filterModel: sanitizeFilterModel(filterModel, props.disableMultipleColumnsFiltering, apiRef),
       filteredRowsLookup: {},
+      filteredChildrenCountLookup: {},
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/filter/useGridFilter.tsx:49]: Not sure about this one. In the DOM and by extension javascript the term "children" is usually for direct children, and "descendants" is for all children including indirect ones. I'd keep it as "children". But that distinction could be added to the jsdoc description of the type.

[the remark this answers is not in the document]
Comment (MBilalShafi) [reply packages/x-data-grid/src/hooks/features/filter/useGridFilter.tsx:49]: Alright, it's more of a difference of understanding then. I personally have a mental model of including grand children in the term children.
Having a clear description could be fine. 👍

File: packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx (hunk 8 above)
Comment (arminmeh) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx:16]: I tend to choose primitives over objects as params since it increases flexibility and re-usability of the hooks/utils
in this particular case, I think it is fine to pass the row though, since the hook is only been used in one place

File: packages/x-data-grid-pro/src/hooks/features/serverSideTreeData/utils.ts (hunk 7 above)
Comment (arminmeh) [reply packages/x-data-grid-pro/src/hooks/features/serverSideTreeData/utils.ts]: It makes more sense that the fallback is `0` rather than `-1`
But the interface should prevent you from having the functions as you have written as you have to return a `number`
I will update the description in the [model](https://github.com/mui/mui-x/blob/v7.11.0/packages/x-data-grid/src/models/gridDataSource.ts#L77) to include the unknown children part from the [docs](https://github.com/mui/mui-x/blob/v7.11.0/docs/data/data-grid/server-side-data/tree-data.md?plain=1#L12)

File: packages/x-data-grid/src/models/gridRows.ts (hunk 13 above)
Comment (arminmeh) [reply packages/x-data-grid/src/models/gridRows.ts:121]: This was a mistake, fixed...

File: packages/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts (hunk 10 above)
Comment (arminmeh) [reply packages/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts:114]: As no one asked for it, I will add `@ignore`
It returns a lookup with a position (index) in the current tree level (after sorting and filtering)
I will rename it to `gridExpandedSortedRowTreeLevelPositionLookupSelector`

File: packages/x-data-grid/src/hooks/features/filter/useGridFilter.tsx (hunk 15 above)
[the remark this answers is not in the document]
Comment (arminmeh) [reply packages/x-data-grid/src/hooks/features/filter/useGridFilter.tsx:49]: What @romgrk mentioned was my logic for this one as well
right below this line, you have
`filteredDescendantCountLookup`
also, in the model for the children count it is stated
> Amount of children that are passing the filters or have children that are passing the filter (does not count grand children).

File: packages/x-data-grid-premium/src/hooks/features/rows/useGridRowAriaAttributes.tsx [hunk 16]
```diff
@@ -0,0 +1,12 @@
+import {
+  useGridRowAriaAttributes as useGridRowAriaAttributesPro,
+  useGridSelector,
+} from '@mui/x-data-grid-pro/internals';
+import { useGridPrivateApiContext } from '../../utils/useGridPrivateApiContext';
+import { gridRowGroupingModelSelector } from '../rowGrouping/gridRowGroupingSelector';
+
+export const useGridRowAriaAttributes = () => {
+  const apiRef = useGridPrivateApiContext();
+  const gridRowGroupingModel = useGridSelector(apiRef, gridRowGroupingModelSelector);
```
[the remark this answers is not in the document]
Comment (arminmeh) [reply packages/x-data-grid-premium/src/hooks/features/rows/useGridRowAriaAttributes.tsx:10]: Will update, thanks

File: packages/x-data-grid/src/hooks/utils/useGridAriaAttributes.tsx (hunk 11 above)
Comment (arminmeh) [reply packages/x-data-grid/src/hooks/utils/useGridAriaAttributes.tsx:22]: Took the first approach, since you will need it in your PR as well

File: packages/x-data-grid-pro/src/hooks/features/serverSideTreeData/utils.ts (hunk 7 above)
Comment (MBilalShafi) [reply packages/x-data-grid-pro/src/hooks/features/serverSideTreeData/utils.ts]: > But the interface should prevent you from having the functions as you have written as you have to return a number

You are right, but we have javascript only users too, they might not care much about the interface 😅 

> I will update the description in the [model](https://github.com/mui/mui-x/blob/v7.11.0/packages/x-data-grid/src/models/gridDataSource.ts#L77) to include the unknown children part from the [docs](https://github.com/mui/mui-x/blob/v7.11.0/docs/data/data-grid/server-side-data/tree-data.md?plain=1#L12)

👍

File: packages/x-data-grid/src/models/gridRows.ts [hunk 17]
```diff
@@ -116,9 +116,9 @@ export interface GridDataGroupNode extends GridBasicGroupNode {
 
 export interface GridDataSourceGroupNode extends GridDataGroupNode {
   /**
-   * If true, this node has children on server.
+   * Number of children this node has on the server. Returns `-1` if there are some children but the count is unknown.
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/models/gridRows.ts:119]: It's a number, not a function, right?
```suggestion
   * Number of children this node has on the server. Equals to `-1` if there are some children but the count is unknown.
```

File: packages/x-data-grid/src/hooks/utils/useGridAriaAttributes.tsx (hunk 11 above)
Comment (arminmeh) [reply packages/x-data-grid/src/hooks/utils/useGridAriaAttributes.tsx]: At the end, I took another approach
I am using the configuration that has been added to have different row aria attributes for the grid aria as well.
This removes the need to have interfaces and selectors from different grid packages.
Maybe something to consider in the PR you have linked above?

File: packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx [hunk 18]
```diff
@@ -0,0 +1,67 @@
...
+
+      const filteredChildrenCount = filteredChildrenCountLookup[rowNode.id] ?? 0;
+      // aria-expanded should only be added to the rows that contain children
+      if (rowNode.type === 'group' && filteredChildrenCount > 0) {
+        ariaAttributes['aria-expanded'] = Boolean(rowNode.childrenExpanded);
+      }
+
+      // if the parent is null, set size and position cannot be determined
+      if (rowNode.parent !== null) {
+        ariaAttributes['aria-setsize'] =
```
Comment (MBilalShafi) [inline packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx:50]: Should the pinned (aggregation) row be included in `aria-setsize` calculation?
In [this](https://deploy-preview-13623--material-ui-x.netlify.app/x/react-data-grid/#premium-plan) demo, the pinned row _does_ have an `aria-setsize` set but no `aria-posinset` set.

image

Also the `aria-setsize` calculation does not include this pinned row.

I can see two options:
1. If the pinned row should not be part of the aria attributes calculation, pinned row should not have a `aria-setsize` attribute too.
2. Otherwise, the `aria-setsize` should be calculated including the pinned row and it should also have a `aria-posinset` (18 in this specific case instead of 17)

What do you think?

File: packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx [hunk 19]
```diff
@@ -0,0 +1,67 @@
...
+  );
+
+  const addAttributes =
+    addTreeDataAttributes !== undefined ? addTreeDataAttributes : props.treeData === true;
+
+  return React.useCallback(
+    (rowNode: GridTreeNode, index: number) => {
+      const ariaAttributes = getRowAriaAttributesCommunity(rowNode, index);
+
+      if (!addAttributes || rowNode === null) {
```
Comment (MBilalShafi) [inline packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx:36]: Nitpick: Would remove the need to define `addAttributes` variable
```suggestion
      if (rowNode === null || (!props.treeData && !addTreeDataAttributes)) {
```

File: packages/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts [hunk 20]
```diff
@@ -96,6 +106,41 @@ export const gridFilteredSortedRowIdsSelector = createSelectorMemoized(
   (filteredSortedRowEntries) => filteredSortedRowEntries.map((row) => row.id),
 );
 
+/**
+ * Get the ids to position in the current tree level lookup of the rows accessible after the filtering process.
+ * Does not contain the collapsed children.
+ * @category Filtering
+ * @ignore - do not document.
+ */
+export const gridExpandedSortedRowTreeLevelPositionLookupSelector = createSelectorMemoized(
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts:115]: Did you already consider computing this lookup during the filtering as you did with the `filteredChildrenCountLookup` to remove one extra `O(n)` loop?

I am imagining the worst case with many unwrapped rows (for example using `defaultGroupingExpansionDepth="-1"`) might yield a slowdown, especially if the data size is more than usual.

What do you think?

**Comment by cherniavskii** [comment]
@arminmeh Can I use this PR to investigate the failing Netlify deployment issue? I'll be pushing commits to your branch if you don't mind it.
(I tried reproducing it in [separate](https://github.com/mui/mui-x/pull/14080) [PRs](https://github.com/mui/mui-x/pull/14081), but deployments worked just fine 😅)

File: packages/x-data-grid-pro/src/internals/index.ts [hunk 21]
```diff
@@ -22,6 +22,11 @@ export {
 } from '../hooks/features/detailPanel/useGridDetailPanel';
 export { useGridDetailPanelPreProcessors } from '../hooks/features/detailPanel/useGridDetailPanelPreProcessors';
 export { useGridInfiniteLoader } from '../hooks/features/infiniteLoader/useGridInfiniteLoader';
+
+// eslint-disable-next-line import/export
```
[the remark this answers is not in the document]
Comment (arminmeh) [reply packages/x-data-grid-pro/src/internals/index.ts:26]: I would still like to make it visible what is actually being replaced so I will group them together and disable the rule for the whole block

[the remark this answers is not in the document]
Comment (MBilalShafi) [reply packages/x-data-grid-pro/src/internals/index.ts:26]: Makes sense 👍

**Comment by arminmeh** [comment]
> @arminmeh Can I use this PR to investigate the failing Netlify deployment issue? I'll be pushing commits to your branch if you don't mind it. (I tried reproducing it in [separate](https://github.com/mui/mui-x/pull/14080) [PRs](https://github.com/mui/mui-x/pull/14081), but deployments worked just fine 😅)

@cherniavskii go ahead
Just a heads up. I have pushed another commit after your comment

File: packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx (hunk 19 above)
Comment (arminmeh) [reply packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx:36]: Will update it to
`if (rowNode === null || !(props.treeData || addTreeDataAttributes))`

File: packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx [hunk 22]
```diff
@@ -0,0 +1,29 @@
...
+  return React.useCallback(
+    (rowNode: GridTreeNode, index: number) => {
+      const ariaAttributes = {} as Record<string, string | number | boolean>;
+
+      const ariaRowIndex = index + headerGroupingMaxDepth + 2; // 1 for the header row and 1 as it's 1-based
+      ariaAttributes['aria-rowindex'] = ariaRowIndex;
+
+      if (selectedIdsLookup[rowNode.id]) {
+        ariaAttributes['aria-selected'] = true;
+      }
```
[the remark this answers is not in the document]
Comment (arminmeh) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowAriaAttributes.tsx:23]: Nice catch.
I will update this and add tests

File: packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx (hunk 18 above)
Comment (arminmeh) [reply packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx:50]: I see that pinned and aggregation rows are placed outside of the `rowgroup` element.
In the docs it is stated
> aria-posinset property
Defines an element's number or position in the current set of listitems or treeitems.

Which means that the set related attributes should be removed (option 1)

Comment (arminmeh) [reply packages/x-data-grid-pro/src/hooks/features/rows/useGridRowAriaAttributes.tsx:50]: I will also add tests to cover this

File: packages/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts (hunk 20 above)
Comment (arminmeh) [reply packages/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts:115]: I did.
Thing is, I need both, a tree structure and the lookups that are flattened out to determine position in a specific tree level. That info cannot be added to the node itself
So, to get it to here a couple of other selectors would have to be updated (possibly with a breaking change)
The measurements that we made show that this selector does not create a big performance impact, so I am thinking of leaving it as is.
The processing time does not depend on the tree structure since it goes through a flat Id list

File: packages/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx [hunk 23]
```diff
@@ -2381,6 +2382,45 @@ describe('<DataGridPremium /> - Row grouping', () => {
...
+            initialState={{ rowGrouping: { model: ['category1', 'category2'] } }}
+            defaultGroupingExpansionDepth={3}
+            rowGroupingColumnMode="multiple"
+          />,
+        );
+
+        const { filteredChildrenCountLookup, filteredDescendantCountLookup } =
+          apiRef.current.state.filter;
+
+        expect(filteredChildrenCountLookup['auto-generated-row-category1/Cat A']).to.equal(2);
```
Comment (cherniavskii) [inline packages/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx:2414]: Should we test `aria-posinset` and `aria-setsize` here instead of the internal state?

File: packages/x-data-grid-premium/src/hooks/utils/useGridAriaAttributes.tsx [hunk 24]
```diff
@@ -0,0 +1,20 @@
...
+} from '@mui/x-data-grid-pro/internals';
+import { useGridPrivateApiContext } from './useGridPrivateApiContext';
+import { gridRowGroupingSanitizedModelSelector } from '../features/rowGrouping/gridRowGroupingSelector';
+
+export const useGridAriaAttributes = (): React.HTMLAttributes<HTMLElement> => {
+  const ariaAttributesPro = useGridAriaAttributesPro();
+  const apiRef = useGridPrivateApiContext();
+  const gridRowGroupingModel = useGridSelector(apiRef, gridRowGroupingSanitizedModelSelector);
+
+  const ariaAttributesPremium = gridRowGroupingModel.length > 0 ? { role: 'treegrid' } : {};
```
Comment (cherniavskii) [inline packages/x-data-grid-premium/src/hooks/utils/useGridAriaAttributes.tsx:14]: When I changed the role from "grid" to "treegrid" for the tree data feature in https://github.com/mui/mui-x/pull/9496, I added the `ariaV7` experimental flag to avoid breaking changes.
While it's technically a "bugfix", perhaps we should do something similar here?
What do you think?

File: packages/x-data-grid-pro/src/tests/treeData.DataGridPro.test.tsx [hunk 25]
```diff
@@ -591,6 +592,47 @@ describe('<DataGridPro /> - Tree data', () => {
...
+          ]}
+          filterModel={{ items: [], quickFilterValues: ['A'] }}
+          defaultGroupingExpansionDepth={3}
+        />,
+      );
+
+      const { filteredChildrenCountLookup, filteredDescendantCountLookup } =
+        apiRef.current.state.filter;
+
+      expect(filteredChildrenCountLookup.A).to.equal(3);
```
Comment (cherniavskii) [inline packages/x-data-grid-pro/src/tests/treeData.DataGridPro.test.tsx:620]: Same as previously – test the outcome (aria attributes) instead of implementation details here?

File: packages/x-data-grid/src/components/GridRow.tsx [hunk 26]
```diff
@@ -307,6 +306,7 @@ const GridRow = React.forwardRef<HTMLDivElement, GridRowProps>(function GridRow(
   }, [isNotVisible, rowHeight, styleProp, minHeight, sizes, rootProps.rowSpacingType]);
 
   const rowClassNames = apiRef.current.unstable_applyPipeProcessors('rowClassName', [], rowId);
+  const ariaAttributes = rowNode ? getRowAriaAttributes(rowNode, index) : {};
```
Comment (cherniavskii) [inline packages/x-data-grid/src/components/GridRow.tsx:309]: Nitpick: no need to create a new object here.
```suggestion
  const ariaAttributes = rowNode ? getRowAriaAttributes(rowNode, index) : undefined;
```

File: scripts/x-data-grid-premium.exports.json [hunk 27]
```diff
@@ -306,6 +306,7 @@
   { "name": "gridExpandedRowCountSelector", "kind": "Variable" },
   { "name": "gridExpandedSortedRowEntriesSelector", "kind": "Variable" },
   { "name": "gridExpandedSortedRowIdsSelector", "kind": "Variable" },
+  { "name": "gridExpandedSortedRowTreeLevelPositionLookupSelector", "kind": "Variable" },
```
Comment (cherniavskii) [inline scripts/x-data-grid-premium.exports.json:309]: Perhaps we can keep these new selectors unexported for now to avoid increasing the API surface?

**Review by cherniavskii — APPROVED** [review]
Good job!

File: packages/x-data-grid-premium/src/hooks/utils/useGridAriaAttributes.tsx (hunk 24 above)
Comment (arminmeh) [reply packages/x-data-grid-premium/src/hooks/utils/useGridAriaAttributes.tsx]: I agree. Thanks for the reference
I have added a flag for the premium grid

File: scripts/x-data-grid-premium.exports.json (hunk 27 above)
Comment (arminmeh) [reply scripts/x-data-grid-premium.exports.json:309]: Is this used for the docs reference?
I see that all selectors are listed. This one has `@ignore` already (as some others in the list)

File: packages/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx (hunk 23 above)
Comment (arminmeh) [reply packages/x-data-grid-premium/src/tests/rowGrouping.DataGridPremium.test.tsx:2414]: this one actually tests new `filteredChildrenCountLookup`
aria attributes are tested further below

File: packages/x-data-grid-pro/src/tests/treeData.DataGridPro.test.tsx (hunk 25 above)
Comment (arminmeh) [reply packages/x-data-grid-pro/src/tests/treeData.DataGridPro.test.tsx:620]: this one actually tests new filteredChildrenCountLookup
aria attributes are tested further below

File: scripts/x-data-grid-premium.exports.json (hunk 27 above)
Comment (cherniavskii) [reply scripts/x-data-grid-premium.exports.json:309]: While not documented, it's still exported from the package, technically being a public API.
If there's no need to export it, I suggest not doing so.

File: packages/x-data-grid-premium/src/hooks/utils/useGridAriaAttributes.tsx (hunk 24 above)
Comment (cherniavskii) [reply packages/x-data-grid-premium/src/hooks/utils/useGridAriaAttributes.tsx]: We also need to document it, similar to https://v6.mui.com/x/react-data-grid/accessibility/#accessibility-changes-in-v7
And how about enabling it in the demos that are using `useDemoData`? https://github.com/mui/mui-x/pull/10204

Comment (arminmeh) [reply packages/x-data-grid-premium/src/hooks/utils/useGridAriaAttributes.tsx]: I have added the docs under the row grouping page, since this flag only affects grid with that feature.
I have also created a cleanup ticket and linked in in the umbrella ticket for the v8 preparation

Only full example grid is actually using demo data, the rest of them are using movie data hook for getting the content. I didn't want to pollute that hook since it is used everywhere, so I have explicitly added a new example in the accessibility section and enabled the experimental flag in the full example

File: packages/x-data-grid-pro/src/hooks/utils/useGridAriaAttributes.tsx [hunk 28]
```diff
@@ -0,0 +1,15 @@
+import * as React from 'react';
+import { useGridAriaAttributes as useGridAriaAttributesCommunity } from '@mui/x-data-grid/internals';
+import { useGridRootProps } from './useGridRootProps';
+
+export const useGridAriaAttributes = (): React.HTMLAttributes<HTMLElement> => {
+  const ariaAttributesCommunity = useGridAriaAttributesCommunity();
+  const rootProps = useGridRootProps();
+
+  const ariaAttributesPro = rootProps.treeData ? { role: 'treegrid' } : {};
```
Comment (MBilalShafi) [inline packages/x-data-grid-pro/src/hooks/utils/useGridAriaAttributes.tsx:9]: Should this also depend on `ariaV8` flag?
If yes, maybe add a section like [this](https://deploy-preview-13623--material-ui-x.netlify.app/x/react-data-grid/row-grouping/#accessibility-changes-in-v8) in tree data documentation [page](https://deploy-preview-13623--material-ui-x.netlify.app/x/react-data-grid/tree-data/) too?

**Review by MBilalShafi — APPROVED** [review]
LGTM, great work! 👏

File: packages/x-data-grid-pro/src/hooks/utils/useGridAriaAttributes.tsx (hunk 28 above)
Comment (arminmeh) [reply packages/x-data-grid-pro/src/hooks/utils/useGridAriaAttributes.tsx:9]: Pro attribute was already there, but it was added via the community gird hook
https://github.com/mui/mui-x/blob/51ec133c8d19d621d660f9c0864495d99dabea32/packages/x-data-grid/src/hooks/utils/useGridAriaAttributes.tsx#L21-L23
