### PR TITLE
[TreeView] Do not use outdated version of the state to compute new label first char in `RichTreeView`

### LINKED ISSUE #12510: [TreeView] `RichTreeView` throws error when using dynamic items
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/cool-leftpad-g472qt?file=%2Fsrc%2FDemo.tsx%3A44%2C5

Steps:
1. Filter tree items by clicking the "Filter items" button.
2. Go back to the initial tree items by clicking the "Unfilter items" button
3. Observe an exception is thrown:
```
Cannot read properties of undefined (reading 'label')
    at processItem (https://g472qt.csb.app/node_modules/
mui/x-tree-view/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.js:41:57
```

### Current behavior

When updating items prop to achieve filtering of the original items and then updating the items prop to revert to the original items then an error is thrown.

Error comes from [this line](https://github.com/LukasTy/mui-x/blob/b66a47275554caebbd61c3ad97a83defa6dab01c/packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts#L58) of code.

### Expected behavior

Any kind of updating to the items prop should not throw an error.

### Context

Filtering of tree items powered by a search text box.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

Error occurs on any browser.

```
  System:
    OS: macOS 14.4
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 122.0.6261.129
    Edge: 122.0.2365.92
    Safari: 17.4
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.4 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.38 
    @mui/core-downloads-tracker:  5.15.12 
    @mui/icons-material:  5.15.13 
    @mui/lab:  5.0.0-alpha.167 
    @mui/material:  5.15.12 
    @mui/private-theming:  5.15.12 
    @mui/styled-engine:  5.15.11 
    @mui/styles:  5.15.12 
    @mui/system:  5.15.12 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.13 
    @mui/x-tree-view:  6.17.0 
    @types/react:  18.2.65 
    react:  18.2.0 
    react-dom:  18.2.0 
    styled-components:  5.3.11 
    typescript: ~5.4.0 => 5.4.2 
```
</details>

**Search keywords**: richtreeview dynamic items

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #12510

### CODE REVIEW

File: packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.ts [hunk 1]
```diff
@@ -107,11 +107,13 @@ export const useTreeViewFocus: TreeViewPlugin<UseTreeViewFocusSignature> = ({
     }
 
     const node = instance.getNode(state.focusedNodeId);
-    const itemElement = document.getElementById(
-      instance.getTreeItemId(state.focusedNodeId, node.idAttribute),
-    );
-    if (itemElement) {
-      itemElement.blur();
+    if (node) {
```
Comment (flaviendelangle) [inline packages/x-tree-view/src/internals/plugins/useTreeViewFocus/useTreeViewFocus.ts:110]: Not directly related but I noticed this bug while writing the tests.
If we remove the currently focused item from `props.items`, then its `TreeItem`  while call `removeFocusedItem`, but the state does not contain the item anymore so it crashes.

File: packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts [hunk 2]
```diff
@@ -51,16 +50,13 @@ export const useTreeViewKeyboardNavigation: TreeViewPlugin<
...
-      const getItemId = params.getItemId;
-      const itemId = getItemId ? getItemId(item) : (item as { id: string }).id;
-      newFirstCharMap[itemId] = instance.getNode(itemId).label!.substring(0, 1).toLowerCase();
-      item.children?.forEach(processItem);
+    const processItem = (node: TreeViewNode) => {
+      newFirstCharMap[node.id] = node.label!.substring(0, 1).toLowerCase();
     };
 
-    params.items.forEach(processItem);
+    Object.values(state.nodes.nodeMap).forEach(processItem);
```
Comment (flaviendelangle) [inline packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:57]: Btw this will support stuff like `apiRef.current.updateItem` when we add this kind of API, the previous approach did not.

It's still far from perfect because we loop through the whole dataset, but until we actually have partial dataset update it's good enough.

File: packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.ts [hunk 3]
```diff
@@ -155,7 +155,18 @@ export const useTreeViewNodes: TreeViewPlugin<UseTreeViewNodesSignature> = ({
     return childrenIds;
   };
 
+  const isItemUpdatedPreventedRef = React.useRef(false);
```
Comment (noraleonte) [inline packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.ts:158]: This naming is a bit weird. Wouldn't it make sense to call this `isItemUpdatePreventedRef`?

**Review by noraleonte — APPROVED** [review]
Looks good to me! 🎉 
Left a tiny comment about naming 😬

File: packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.ts (hunk 3 above)
Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.ts:158]: You are entirely right, this naming was weird
I went for `areItemUpdatesPreventedRef` since we can have multiple updates
