### PR TITLE
[DataGrid] Fix error overlay not visible when `autoHeight` is enabled

### LINKED ISSUE #4088: [DataGrid] ErrorOverlay not visible with `autoHeight`
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using `<DataGrid autoHeight>` error overlay is not visible.

### Expected behavior 🤔

Error overlay should dictate grid’s height when grid has `autoHeight` property.

### Steps to reproduce 🕹

```
<DataGrid error autoHeight />
```

https://codesandbox.io/s/datagriddemo-material-demo-forked-2t3we4?file=/demo.tsx

### Context 🔦

_No response_

### Your environment 🌎

Tested on Chrome 98 and Firefox 97 on Linux and Safari 13.1.2 on macOS.

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
  Binaries:
    Node: 16.13.1 - ~/local/src/nvs/node/16.13.1/x64/bin/node
    Yarn: 1.22.17 - ~/local/src/nvs/node/16.13.1/x64/bin/yarn
    npm: 8.5.1 - ~/local/src/nvs/node/16.13.1/x64/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 97.0
  npmPackages:
    @emotion/react: latest => 11.8.1 
    @emotion/styled: latest => 11.8.1 
    @mui/base:  5.0.0-alpha.70 
    @mui/material: latest => 5.4.4 
    @mui/private-theming:  5.4.4 
    @mui/styled-engine:  5.4.4 
    @mui/system:  5.4.4 
    @mui/types:  7.1.2 
    @mui/utils:  5.4.4 
    @mui/x-data-grid: latest => 5.5.1 
    @types/react: latest => 17.0.39 
    react: latest => 17.0.2 
    react-dom: latest => 17.0.2 
    typescript: latest => 4.6.2 
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by cherniavskii**
Fixes #4088

Codesandbox: https://codesandbox.io/s/datagriddemo-material-demo-forked-y8hce8?file=/demo.tsx

### CODE REVIEW

File: packages/grid/x-data-grid/src/components/base/GridErrorHandler.tsx [hunk 1]
```diff
@@ -38,20 +21,11 @@ function GridErrorHandler(props: { children: React.ReactNode }) {
       logger={logger}
       render={(errorProps) => (
         <GridMainContainer>
-          <GridAutoSizer
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/base/GridErrorHandler.tsx:41]: I don't see any use case for having `GridAutoSizer` here.
It was added in https://github.com/mui/mui-x/pull/3558#discussion_r779934238, but I don't think it's necessary - here's the same demo with a package from this PR: https://codesandbox.io/s/datagriddemo-material-demo-forked-dzx7nl?file=/demo.tsx

File: packages/grid/x-data-grid/src/components/ErrorOverlay.tsx [hunk 2]
```diff
@@ -1,11 +1,21 @@
 import * as React from 'react';
+import { styled } from '@mui/material/styles';
 import { useGridApiContext } from '../hooks/utils/useGridApiContext';
 import { GridOverlay, GridOverlayProps } from './containers/GridOverlay';
 
+const ErrorGridOverlay = styled(GridOverlay, {
+  shouldForwardProp: (prop) => prop !== 'rowHeight',
+})((props: GridOverlayProps & { rowHeight: number }) => {
+  return {
+    minHeight: props.rowHeight,
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/ErrorOverlay.tsx:10]: Not sure about this minHeight. Maybe `3 * rowHeight` would be better?

File: packages/grid/x-data-grid/src/components/ErrorOverlay.tsx [hunk 3]
```diff
@@ -16,9 +26,9 @@ export const ErrorOverlay = React.forwardRef<HTMLDivElement, ErrorOverlayProps>(
     const defaultLabel = apiRef.current.getLocaleText('errorOverlayDefaultLabel');
 
     return (
-      <GridOverlay ref={ref} {...other}>
+      <ErrorGridOverlay ref={ref} {...other}>
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/components/ErrorOverlay.tsx:29]: `GridOverlay` is a styled component. You could use `sx`. You may need to fix some TS types to accept this prop.

File: packages/grid/x-data-grid/src/components/base/GridErrorHandler.tsx [hunk 4]
```diff
@@ -38,20 +21,11 @@ function GridErrorHandler(props: { children: React.ReactNode }) {
...
-                  {...errorProps}
-                  {...rootProps.componentsProps?.errorOverlay}
-                />
-              </ErrorOverlayWrapper>
-            )}
-          </GridAutoSizer>
+          <rootProps.components.ErrorOverlay
+            {...errorProps}
+            {...rootProps.componentsProps?.errorOverlay}
+            rowHeight={rootProps.rowHeight}
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/components/base/GridErrorHandler.tsx:27]: Two things:

- To get the row height prefer `gridDensityRowHeightSelector`. The prop is not aware of the current density.
- You could use `useGridRootProps` inside the overlay, instead of passing the prop.

File: packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx [hunk 5]
```diff
@@ -813,6 +813,28 @@ describe('<DataGrid /> - Layout & Warnings', () => {
...
+            <DataGrid
+              columns={[{ field: 'brand' }]}
+              rows={[]}
+              autoHeight
+              error={error}
+              rowHeight={rowHeight}
+            />
+          </div>,
+        );
+        const errorOverlayElement = document.querySelectorAll(
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx:832]: `document.querySelector` already returns the first element.

```suggestion
        const errorOverlayElement = document.querySelector(
```

**Review by m4theushw — COMMENTED** [review]
I left some suggestions. Overall looks good.

File: packages/grid/x-data-grid/src/components/ErrorOverlay.tsx (hunk 2 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/ErrorOverlay.tsx]: Right, I've updated it to use 2 * rowHeight for consistency

File: packages/grid/x-data-grid/src/components/ErrorOverlay.tsx (hunk 3 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/ErrorOverlay.tsx]: Nice

File: packages/grid/x-data-grid/src/components/base/GridErrorHandler.tsx (hunk 4 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/base/GridErrorHandler.tsx]: Didn't think about density, thanks!

File: packages/grid/x-data-grid/src/components/ErrorOverlay.tsx [hunk 6]
```diff
@@ -14,9 +16,10 @@ export const ErrorOverlay = React.forwardRef<HTMLDivElement, ErrorOverlayProps>(
     const { message, hasError, errorInfo, ...other } = props;
     const apiRef = useGridApiContext();
     const defaultLabel = apiRef.current.getLocaleText('errorOverlayDefaultLabel');
+    const rowHeight = useGridSelector(apiRef, gridDensityRowHeightSelector);
 
     return (
-      <GridOverlay ref={ref} {...other}>
+      <GridOverlay ref={ref} sx={{ width: '100%', minHeight: 2 * rowHeight }} {...other}>
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/components/ErrorOverlay.tsx:22]: Ok to keep `minHeight` even with `autoHeight=false` because the grid has `overflow: hidden`. If it didn't hide what overflows this could be a problem.

If you want to go further, the `sx` prop converts values between [0, 1] to a percentage. See  https://mui.com/system/the-sx-prop/#sizing

```suggestion
      <GridOverlay ref={ref} sx={{ width: 1, minHeight: 2 * rowHeight }} {...other}>
```

**Review by m4theushw — APPROVED** [review]

File: packages/grid/x-data-grid/src/components/ErrorOverlay.tsx (hunk 6 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/ErrorOverlay.tsx:22]: > Ok to keep minHeight even with autoHeight=false because the grid has overflow: hidden. If it didn't hide what overflows this could be a problem

Yeah, I was thinking about applying it conditionally, but as you said - it won't cause any harm anyway.

> sx prop converts values between [0, 1] to a percentage

Thanks, I didn't know about that.
In this particular case I prefer explicit `100%` though
