### PR TITLE
[scheduler] Add tests for drag and drop and event resizing + fix bug

### LINKED ISSUE #21481: [scheduler] Bug - an event can't be moved from time grid to day grid on the same day
You can move an event form the time grid to the day grid (week view) only if it's not the same day. If you try to do it in the same day it doesn't work

https://github.com/user-attachments/assets/8a0cfdaa-504b-4e4f-89e8-d82635ed772f

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #21481

### CODE REVIEW

File: packages/x-scheduler-headless-premium/src/timeline-grid/event/TimelineGridEvent.tsx [hunk 1]
```diff
@@ -25,10 +25,13 @@ import { useTimelineGridEventRowContext } from '../event-row/TimelineGridEventRo
...
 import { eventTimelinePremiumViewSelectors } from '../../event-timeline-premium-selectors';
+import { TimelineGridEventDataAttributes } from './TimelineGridEventDataAttributes';
 
 const overflowStateAttributesMapping = {
-  startingBeforeEdge: (value: boolean) => (value ? { 'data-starting-before-edge': '' } : null),
-  endingAfterEdge: (value: boolean) => (value ? { 'data-ending-after-edge': '' } : null),
+  startingBeforeEdge: (value: boolean) =>
+    value ? { [TimelineGridEventDataAttributes.startingBeforeEdge]: '' } : null,
+  endingAfterEdge: (value: boolean) =>
+    value ? { [TimelineGridEventDataAttributes.endingAfterEdge]: '' } : null,
```
Comment (rita-codes) [inline packages/x-scheduler-headless-premium/src/timeline-grid/event/TimelineGridEvent.tsx:34]: 🙇‍♀️

File: packages/x-scheduler-headless/src/internals/utils/SchedulerStore/SchedulerStore.types.ts [hunk 2]
```diff
@@ -311,7 +311,7 @@ export interface SchedulerParameters<TEvent extends object, TResource extends ob
  */
 export type UpdateRecurringEventParameters = {
   /**
-   * The start date of the occurrence affected by the update.
+   * The start date of the occurrence affected by the update before the update is applied.
```
Comment (rita-codes) [inline packages/x-scheduler-headless/src/internals/utils/SchedulerStore/SchedulerStore.types.ts:314]: 💯

Comment (flaviendelangle) [reply packages/x-scheduler-headless/src/internals/utils/SchedulerStore/SchedulerStore.types.ts:314]: Would be even cleaner to have the `occurrenceKey` in state as always :laughing:

**Comment by flaviendelangle** [comment]
> Generic question, should we rename WeekView.test.tsx? Right now that test file is covering all day events, time navigation and current time indicator; and we have now dragAndDrop.WeekView.test.tsx

I moved them in a `test` folder, we can split them in a follow up :+1:
