### PR TITLE
[pickers] Fix to `transform-origin` when popper opens to `top`

### LINKED ISSUE #10006: [pickers] Open animation origin bug when reversed
### Steps to reproduce 🕹

Link to live example:

Steps:
1. Open https://mui.com/x/react-date-pickers/#overview 
2. Make the popup open above
3. See how the animation transformation origin is wrong https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin, it's at the top center, rather at the bottom center of the popup.

### Current behavior 😯

https://github.com/mui/mui-x/assets/3165635/31370cb0-ba7f-48d6-a66f-07cc515eed2c

### Expected behavior 🤔

https://mui.com/material-ui/react-select/#with-a-dialog

https://github.com/mui/mui-x/assets/3165635/041d83ef-eb99-4120-baf1-386e39864f7b

We have another example in https://mui.com/material-ui/react-menu/#menulist-composition that might help with the implementation.

### Context 🔦

I have noticed answering https://github.com/mui/mui-x/pull/9781#issuecomment-1654540019.

It's also related to the design review I had on Joy UI in https://www.notion.so/mui-org/Olivier-design-review-on-Joy-Design-3ada9a7bcfa44b9fab1fe5032dfb33bb?pvs=4#fae949292c7a4eabacd2a377ba13cc86. Are we sure about the current animation? It doesn't feel great on my end. When you go to https://mui.com/x/react-date-pickers/#overview and click on the button, you have to wait for the open animation to complete. However, when you go to https://vercel.com/design/calendar or https://ui.shadcn.com/docs/components/date-picker, the animation is shorter, it feels clearly more responsive.

### Your environment 🌎

v6.11.1

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #10006 

The placement is `top-start` when the popper opens to the top, because of that the conditional style did not work.

Preview: https://deploy-preview-10069--material-ui-x.netlify.app/x/react-date-pickers/

### CODE REVIEW

File: packages/x-date-pickers/src/internals/components/PickersPopper.tsx [hunk 1]
```diff
@@ -113,7 +113,7 @@ const PickersPopperPaper = styled(MuiPaper, {
 }>(({ ownerState }) => ({
   transformOrigin: 'top center',
   outline: 0,
-  ...(ownerState.placement === 'top' && {
+  ...(ownerState.placement?.includes('top') && {
```
Comment (oliviertassinari) [inline packages/x-date-pickers/src/internals/components/PickersPopper.tsx:116]: The `?` defensive logic looks wrong. It's impossible for the placement to be undefined.

```suggestion
  ...(ownerState.placement.includes('top') && {
```

Maybe this would fix it:

```diff
diff --git a/packages/x-date-pickers/src/internals/components/PickersPopper.tsx b/packages/x-date-pickers/src/internals/components/PickersPopper.tsx
index 8a7963525..3c9d67be5 100644
--- a/packages/x-date-pickers/src/internals/components/PickersPopper.tsx
+++ b/packages/x-date-pickers/src/internals/components/PickersPopper.tsx
@@ -54,7 +54,7 @@ export interface PickersPopperSlotsComponentsProps {
   desktopPaper?: SlotComponentProps<
     typeof MuiPaper,
     {},
-    PickerPopperProps & { placement: PopperPlacementType | undefined }
+    PickerPopperProps & { placement: PopperPlacementType }
   >;
   /**
```

It's impossible because if we provide undefined, it crashes in https://popper.js.org/docs/v2/constructors/#placement.

Comment (LukasTy) [reply packages/x-date-pickers/src/internals/components/PickersPopper.tsx]: @oliviertassinari Thank you for the suggestion!
Fixed it with https://github.com/mui/mui-x/pull/10069/commits/bb39de6a09de65e221c75b4a0b7a4302bb74b295
Also discovered an issue with this slot props and created a fix for it: https://github.com/mui/mui-x/pull/10103

**Comment by oliviertassinari** [comment]
Awesome 👍 

To be fair, in https://github.com/mui/mui-x/issues/5490#issuecomment-1675283837, I have made the case for much less frequently flipping the popup to be shown on the top.

**Review by noraleonte — APPROVED** [review]
Very nice improvement! 🎉
