### PR TITLE
[DataGrid] Only update input with value prop if debounce is off

### LINKED ISSUE #5283: [data grid] Lag while typing
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

when I double-click on a cell that I want to edit when typing the component has a certain delay that erases words and does not allow me to type correctly

### Expected behavior 🤔

I wish to write: Hello, how are you?

Datagrid cell: Hllo, ow re yo

### Steps to reproduce 🕹

import { Alert, AlertProps, Box, Button, debounce, IconButton, Snackbar, Stack } from '@mui/material';
import { DataGrid, GridCellEditStopParams, GridCellEditStopReasons, GridColumns, GridRowModel, GridSelectionModel, GridToolbar, MuiEvent, useGridApiContext } from '@mui/x-data-grid';
import DeleteIcon from '@mui/icons-material/Delete';
import { useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react'
import Loading from '../../../Components/Loading.component';
import { UserContext } from '../../../Context/User/UserContext.context';
import Movie from '../../Domain/Domain-Model/Entities/Movie.model';
import MovieRepository from '../../Domain/Domain-Service/Repository/Implementation/movie.repository.service';
import Genre from '../../Domain/Domain-Model/Entities/Genre.model';
import { randomId } from '@mui/x-data-grid-generator'

const useChangeValidation = () => {
    return useCallback(
        (movie: Partial<Movie>) =>
            new Promise<Partial<Movie>>((resolve, reject) =>
                setTimeout(() => {
                    console.log(" useChangeValidation")
                    /*   if (movie.title === '') reject(new Error(`Error saving ${movie.idMovie}, it can not be empty`))
                       else resolve({ ...movie, title: movie.title });
                       if (movie.director === '') reject(new Error(`Error saving ${movie.idMovie}, it can not be empty`))
                       else resolve({ ...movie, director: movie.director });*/
                    resolve({ ...movie, director: movie.director })
                }, 0),
            ),
        [],
    );
};

export const MovieTable = (props: any) => {
    const [columns, setColumns] = useState<GridColumns<any>>([]);
    const [rows, setRows] = useState<any[]>([])
    const [movie_repository] = useState<MovieRepository>(new MovieRepository());
    const [user] = useContext(UserContext)
    const mutateRow = useChangeValidation();
    const [snackbar, setSnackbar] = useState<Pick<AlertProps, 'children' | 'severity'> | null>(null);
    const handleCloseSnackbar = () => setSnackbar(null);
    const [selectionModel, setSelectionModel] = useState<GridSelectionModel>([]);
    const rowsRef = useRef(rows);

    useEffect(
        () => {
            rowsRef.current = rows;
        },
        [rows],
    );

    const processRowUpdate = useCallback(
        async (row: GridRowModel) => {
            console.log("processRowUpdate")
            let apiCall = await movie_repository.putMovie(new Movie(row.id, row.title, row.releaseDate, row.director,
                new Genre((await movie_repository.getMovieById(row.id, user.token)).genre.idGenre as number, row.genero)), user.token)
            const response = await mutateRow(row);
            if (apiCall !== undefined) setSnackbar({ children: `Movie ${apiCall.title} successfully updated`, severity: 'success' });
            return response;
        },
        [mutateRow],
    );

    const handleProcessRowUpdateError = useCallback((error: Error) => {
        console.log("handleProcessRowUpdateError")
        setSnackbar({ children: error.message, severity: 'error' });
    }, []);

    const handleAddRow = () => {
        setRows((prevRows) => [{
            id: randomId(),
            title: '',
            releaseDate: '',
            director: '',
            genero: '',
        }, ...prevRows]);
    };

    async function handleDeleteRow(params: any) {
        let response = undefined;
        response = await movie_repository.deleteMovieById(params.id, user.token)
        if (response !== undefined) {
            setRows(rowsRef.current.filter(row => row.id !== params.id))
        }
    }
    useMemo(() => setColumns([
        { field: 'id', headerName: 'Id', width: 90, },
        { field: 'title', headerName: 'Título', width: 160, editable: true },
        { field: 'releaseDate', headerName: 'Fecha', type: 'dateTime', width: 220, editable: true },
        { field: 'director', headerName: 'Director', width: 160, editable: true },
        { field: 'genero', headerName: 'Género', width: 130, editable: true },
        {
            field: 'action', headerName: 'Action', width: 90, renderCell: (cellValues: any) => {
                return (
                    <IconButton aria-label="delete" size="large" onClick={(event) => { handleDeleteRow(cellValues); }}>
                        <DeleteIcon fontSize="inherit" />
                    </IconButton>
                );
            }
        }
    ]), [])

    useMemo(() => {
        let response: Movie[];
        (async () => {
            console.log("getAllMovies")
            response = await movie_repository.getAllMovies(user.token)
            if (response !== undefined) {
                setRows(response.map((row) => ({
                    id: row.idMovie,
                    title: row.title,
                    releaseDate: row.releaseDate,
                    director: row.director,
                    genero: row.genre.type
                })));
            }
        })()
    }, [])

    return (
        <>
            <div style={{
                height: '56vh', width: '60vw', marginLeft: '22%',
                marginTop: '5%'
            }}>
                <Box sx={{ width: '100%' }}>
                    <Box sx={{ height: 400, mt: 1 }}>
                        {rows.length > 0 ?
                            <>
                                <DataGrid
                                    rows={rows}
                                    columns={columns}
                                    editMode="row"
                                    onCellEditStop={(params: GridCellEditStopParams, event: MuiEvent) => {
                                        if (params.reason === GridCellEditStopReasons.cellFocusOut) {
                                            event.defaultMuiPrevented = true;
                                            alert('sto]ed')
                                        }
                                    }}
                                    //getRowId={(row) => row.id}
                                    processRowUpdate={processRowUpdate}
                                    onProcessRowUpdateError={handleProcessRowUpdateError}
                                    components={{ Toolbar: GridToolbar }}
                                    experimentalFeatures={{ newEditingApi: true, warnIfFocusStateIsNotSynced: true, preventCommitWhileValidating: true }}
                                    onSelectionModelChange={(newSelectionModel: any) => {
                                        setSelectionModel(newSelectionModel);
                                    }}
                                    selectionModel={selectionModel}
                                    // isRowSelectable={(params: GridRowParams) => params.row.action}
                                    checkboxSelection />
                                <Stack direction="row" spacing={1} sx={{ marginLeft: '54vw' }}>
                                    <Button size="small" onClick={handleAddRow}>
                                        Add a row
                                    </Button>
                                </Stack></> :
                            <Loading />
                        }
                        {!!snackbar && (
                            <Snackbar
                                open
                                onClose={handleCloseSnackbar}
                                anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
                                autoHideDuration={3000}>
                                <Alert {...snackbar} onClose={handleCloseSnackbar} />
                            </Snackbar>
                        )}
                    </Box>
                </Box>

            </div>
        </>
    )
}

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #5283

Preview: https://deploy-preview-5646--material-ui-x.netlify.app/x/react-data-grid/editing/

I don't have a precise explanation of why #5283 happens but I have a hypothesis. On each keystroke we call `apiRef.current.setEditCellValue` which debounces the state updates. When the debounce time expires, the global state is updated triggering a rerender of the entire grid. While the grid is rerendering, sometimes taking a long time, if the user presses another key this last key will be lost because the input value is changed to reflect the value in the state. I solved this problem here by ignoring the sync between the value in the global state and the value in the edit component's state **when** the reason for this sync to happen is a debounce event. In practical terms, `apiRef.current.setEditCellValue` now has a `reason` argument which can be accessed via `apiRef.current.unstable_getEditCellMeta`.

### CODE REVIEW

File: packages/grid/x-data-grid/src/components/cell/GridEditInputCell.tsx [hunk 1]
```diff
@@ -92,15 +92,31 @@ const GridEditInputCell = React.forwardRef<HTMLInputElement, GridEditInputCellPr
           await onValueChange(event, newValue);
         }
 
-        setValueState(newValue);
-        apiRef.current.setEditCellValue({ id, field, value: newValue, debounceMs }, event);
+        const column = apiRef.current.getColumn(field);
+
+        let parsedValue = newValue;
+        if (column.valueParser && rootProps.experimentalFeatures?.newEditingApi) {
+          parsedValue = column.valueParser(newValue, apiRef.current.getCellParams(id, field));
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/components/cell/GridEditInputCell.tsx:99]: Since we don't sync the value between the global state and the local state, when the call is debounced, we need to manually call the value parser and skip the one in `apiRef.current.setEditCellValue`.

**Review by DanailH — APPROVED** [review]
