### PR TITLE
[charts-pro] Fix zoom filtering adjusting axis too soon

### LINKED ISSUE #18991: [charts] Zoom filtering adjusts y axis too soon
In the example below, it should only adjust the y axis when the "E" bar is outside the drawing area. 

https://github.com/user-attachments/assets/233c97f1-f7c5-447a-9130-1268faa64f41

### PR DESCRIPTION
**Pull request by bernardobelchior**
Fix #18991.

Before:

https://github.com/user-attachments/assets/233c97f1-f7c5-447a-9130-1268faa64f41

After:

https://github.com/user-attachments/assets/1ea3d8c3-8ef5-439f-95cf-fd123ed6943e

### CODE REVIEW

File: packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.ts [hunk 1]
```diff
@@ -57,43 +63,80 @@ export function createAxisFilterMapper({
...
+
+    if (val == null) {
+      // If the value does not exist because of missing data point, or out of range index, we just ignore.
+      return true;
+    }
 
-      if (axis.scaleType === 'point' || axis.scaleType === 'band' || typeof val === 'string') {
-        return dataIndex >= minVal && dataIndex <= maxVal;
-      }
+    if (typeof val === 'string') {
```
Comment (bernardobelchior) [inline packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.ts]: I wonder if we can remove this from continuous scales 🤔 

I kept it because I didn't want to cause a breaking change, but it doesn't make sense for `val` to be a string here if we're using a continuous scale (which only supports numeric values).

If we can remove this, it should simplify this method since we'll no longer need to depend on `axisData`.

Comment (JCQuintas) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.ts]: i don't see why we would leave it here. It was probably added as a way to tell typescript to stop complaining about the last return, since checking `axis.scaleType` doesn't typecheck `val`

Comment (bernardobelchior) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.ts]: Yeah, makes sense. I separated the refactor into [this PR](https://github.com/mui/mui-x/pull/18998) so we can focus on the fix here.

That should allow me to test this use case more thoroughly without worrying whether the culprit is the refactor or the fix

File: packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.ts [hunk 2]
```diff
@@ -57,43 +63,80 @@ export function createAxisFilterMapper({
...
+  axisData: AxisConfig['data'],
+  zoomStart: number,
+  zoomEnd: number,
+  direction: 'x' | 'y',
+): ExtremumFilter {
+  const max = axisData?.length ?? 0;
 
-    [min, max] = getScale(continuousScaleType, extremums, [0, 100]).nice().domain();
+  const minVal = (zoomStart * max) / 100;
+  const maxVal = (zoomEnd * max) / 100;
```
Comment (alexfauquette) [inline packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.ts]: Since we are considering discret value, what about keeping every thing as before (accept equality) and just rounding the min/max

```suggestion
  const minVal = Math.floor((zoomStart * max) / 100);
  const maxVal = Math.ceil((zoomEnd * max) / 100);
```

Comment (bernardobelchior) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.ts]: Sorry, I didn't get what you mean. What are you suggesting?

Comment (alexfauquette) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.ts]: Your current solution is about doing the math in a continuous space, going from the first tick (the 0) to the last tick (the `data.length`) and then you do comarison with array indexes thanks to the `-1`

My proposal was to only consider indexes and manage extremes by rounding up and down
image

Comment (bernardobelchior) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.ts]: Sure, makes sense 👍

**Review by alexfauquette — APPROVED** [review]
