### PR TITLE
[pickers] Avoid calendar layout shifting when changing views

### LINKED ISSUE #5490: [pickers] Jumps between being expanded to the top/bottom
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When there is just enough space to show the day view at the bottom of the text field, but not enough space to show the year view, popover jumps between positions at the top and bottom of the text field when switching between the two views.

https://user-images.githubusercontent.com/1012600/178905178-a9e4f700-031b-49c7-8126-3eff93a67f55.mov

### Expected behavior 🤔

The popover should always be positioned based on the size of the largest supported view.

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/mui-picker-popover-312xyl?file=/src/App.tsx

Steps:
1. Depending on your system, you may need to tweak `pb: '340px'` prop so that there is just enough space for the day view below the text field, but even more space available above the text field, as shown in the attached video.
2. Open the popup.
3. Open Year picker and select any year. Popup should jump to above the text field.
4. Click anywhere outside the popup. Before closing it will quickly jump to below the text field, then it will close.

### Context 🔦

I want to use the various combinations of date picker views without any jarring relocations of the popup. Similar problem also exists when switching between the day and month views.

### Your environment 🌎

I used Google Chrome. BTW, I do have Edge installed, but the tool says "Edge: Not Found"

<details>
  <summary><code>npx @mui/envinfo</code></summary>
System:
    OS: macOS 12.4
  Binaries:
    Node: 16.13.1 - ~/opt/node/current/bin/node
    Yarn: 1.22.19 - ~/opt/node/current/bin/yarn
    npm: 8.13.2 - ~/opt/node/current/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Not Found
    Firefox: 101.0.1
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.9.3 => 11.9.3 
    @emotion/styled: ^11.9.3 => 11.9.3 
    @mui/base:  5.0.0-alpha.89 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/material: ^5.9.0 => 5.9.0 
    @mui/private-theming:  5.9.0 
    @mui/styled-engine:  5.8.7 
    @mui/system:  5.9.0 
    @mui/types:  7.1.4 
    @mui/utils:  5.9.0 
    @mui/x-date-pickers: ^5.0.0-beta.0 => 5.0.0-beta.0 
    @types/react: ^18.0.15 => 18.0.15 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: 4.7.4 => 4.7.4 
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #5490 

- Avoid the calendar layout shifting when changing views by setting a constant `height` on the `DateCalendar` component.
Had to also change the `maxHeight` on the `YearCalendar` to keep the overflown dates partially visible.
The only resulting change is that the `DateCalendar` will not be jumping and/or changing it's height depending on the active view or the amount of available year options.

- Use global/theme transition durations instead of using a custom longer (500ms) constant. The default for `complex` animations in the theme is 375ms.
- Use more dimensions constants.
- ~~Adjust year and month calendars padding to be more in line with [MD2 spec](https://m2.material.io/components/date-pickers#specs:~:text=28%20x%2028dp-,Year%20selection%20view,-Padding%0A%E2%80%A2%20Left%20padding): the spacing and size of buttons should be smaller on desktop (when more dense layout of 4 items per row is used).~~
- ~~Adjust month and year button size and spacing to be more in line with [MD2 spec](https://m2.material.io/components/date-pickers#specs:~:text=28%20x%2028dp-,Year%20selection%20view,-Padding%0A%E2%80%A2%20Left%20padding): the spacing and size of buttons should be smaller on desktop (when more dense layout of 4 items per row is used).
Without the change of margin we would no longer have visible overflown (as the maximum height of the container has changed - Date calendar) year items signalling that user can scroll for more options.~~
- Change the year button vertical margin from `8px` to `6px` to account for the reduced `YearCalendar` height to still show the "other" overflown years;
- Remove no longer relevant https://mui.com/x/react-date-pickers/custom-components/#popper section

I'd love to get feedback on the last two changes on spacing and sizing. My motive for going after it was the fact that after reducing the height, overflown `YearCalendar` items become invisible if you are not aware that the container can be scrolled.
Do you see other options to achieve the same behavior? 🤔

### CODE REVIEW

File: packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx [hunk 1]
```diff
@@ -73,6 +74,7 @@ const DateCalendarRoot = styled(PickerViewRoot, {
 })<{ ownerState: DateCalendarProps<any> }>({
   display: 'flex',
   flexDirection: 'column',
+  height: VIEW_HEIGHT,
```
Comment (LukasTy) [inline packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx:77]: This is the main change that fixes the underlying problem.
Everything else is just tying things together.

File: packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx [hunk 2]
```diff
@@ -55,13 +56,15 @@ const MonthCalendarRoot = styled('div', {
...
   display: 'flex',
   flexWrap: 'wrap',
   alignContent: 'stretch',
-  padding: '0 4px',
-  width: 320,
-});
+  padding: `0 ${ownerState.monthsPerRow === 3 ? 24 : 12}px`,
+  width: DIALOG_WIDTH,
+  // avoid padding increasing width over defined
+  boxSizing: 'border-box',
```
Comment (LukasTy) [inline packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx:66]: Fixes the [same problem](https://github.com/mui/mui-x/pull/10135/files#diff-4017baaeb5c193d67ea78afd13f45961209b9f5c674be61af5d6b02ddcff7d7cR69) that was on `YearCalendar` as well 🙈

File: packages/x-date-pickers/src/MonthCalendar/PickersMonth.tsx [hunk 3]
```diff
@@ -64,15 +64,15 @@ const PickersMonthButton = styled('button', {
...
+}>(({ theme, ownerState }) => ({
   color: 'unset',
   backgroundColor: 'transparent',
   border: 0,
   outline: 0,
   ...theme.typography.subtitle1,
-  margin: '8px 0',
-  height: 36,
-  width: 72,
+  margin: `${ownerState.monthsPerRow === 3 ? 6 : 3}px 0`,
```
Comment (LukasTy) [inline packages/x-date-pickers/src/MonthCalendar/PickersMonth.tsx:73]: I'm open to suggestions on this change.
it was not necessary.
I've only done it to be more in line with MD2 spacing spec if we are already adjusting it.

File: packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx (hunk 1 above)
Comment (noraleonte) [reply packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx:77]: I'm slightly worried about the `MonthCalendar` in this scenario (or the `YearCalendar` if there aren't too many options) because of the white space. 
image

But I think it's a good compromise considering the number of users who would actually  end up in this scenario vs the problem this change solves 👍

**Review by noraleonte — APPROVED** [review]
Huge improvement! 🎉 Thanks for tackling this 🛩️ 
I feel like it is a big step up from the previous doc example/workaround for the layout shift.

File: packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx (hunk 1 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx:77]: I understand the concern, but in our case, we do not even use the `monthsPerRow = 4` in case of Desktop pickers, which we should probably do, to keep in line with spacing and sizing convention based on MD2.
WDYT? 🤔 
Does seeing the same approach on https://material.angular.io/components/datepicker/overview#setting-the-calendar-starting-view alleviate some of the concerns? 🤔

Comment (noraleonte) [reply packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx:77]: Having seen another example for a similar approach is definitely reassuring 👍 
I think this solution is definitely solving a lot of issues, so my concern is mostly something I wanted to highlight, and definitely shouldn't be a blocker 💯

**Review by joserodolfofreitas — COMMENTED** [review]
Great improvements here! Thank you!

My only concern is the new padding for the year (although it's a good thing to follow md2)
- I'm actually fine with it, but I think the less dense view looks better, and I'm not sure that showing more options is advantageous for the user (in most cases), MD3 went for showing fewer options with the combo box.
- The alignment of the year option matrix feels a bit off. Can we fix that?
Screenshot 2023-10-04 at 10 50 27

**Comment by LukasTy** [comment]
@noraleonte @alexfauquette @joserodolfofreitas I've updated the PR avoiding any unwanted spacing and sizing changes in this scope. 👌 
If no one complained about this inconsistency until now, we can certainly wait until v7 for any updates on this regard. 👌

**Review by joserodolfofreitas — APPROVED** [review]
