### PR TITLE
[pickers] Fix time picker `viewRenderers` overriding

### LINKED ISSUE #8821: [pickers] Rendering a clock on desktop not working
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Despite the cool new time picker design I'd like to use the clock.

I have configured the theme like here https://mui.com/x/migration/migration-pickers-v5/#stop-rendering-a-clock-on-desktop.

### Current behavior 😯

I get a type error though for `MuiDesktopTimePicker` for `hours`, `minutes` and `seconds` although I am using the necessary import `import type {} from '@mui/x-date-pickers/themeAugmentation';`.

```
TS2322: Type '<TDate extends unknown>({ view, onViewChange, focusedView, onFocusedViewChange, views, value, defaultValue, onChange, className, classes, disableFuture, disablePast, minTime, maxTime, shouldDisableTime, shouldDisableClock, minutesStep, ampm, ampmInClock, components, componentsProps, slots, slotProps, readOnly, disab...' is not assignable to type 'PickerViewRenderer<unknown, TimeViewWithMeridiem, TimeViewRendererProps<TimeViewWithMeridiem, BaseClockProps<unknown, TimeViewWithMeridiem>>, {}>'.
  Types of parameters '__0' and 'props' are incompatible.
    Type 'PickerViewsRendererProps<unknown, TimeViewWithMeridiem, TimeViewRendererProps<TimeViewWithMeridiem, BaseClockProps<unknown, TimeViewWithMeridiem>>, {}>' is not assignable to type 'TimeViewRendererProps<TimeView, TimeClockProps<unknown>>'.
      Type 'PickerViewsRendererProps<unknown, TimeViewWithMeridiem, TimeViewRendererProps<TimeViewWithMeridiem, BaseClockProps<unknown, TimeViewWithMeridiem>>, {}>' is not assignable to type 'Omit<TimeClockProps<unknown>, "view" | "openTo" | "views" | "onViewChange">'.
        Types of property 'focusedView' are incompatible.
          Type '"seconds" | "minutes" | "hours" | "meridiem" | null' is not assignable to type 'TimeView | null | undefined'.
            Type '"meridiem"' is not assignable to type 'TimeView | null | undefined'.

TS2322: Type '<TDate extends unknown>({ view, onViewChange, focusedView, onFocusedViewChange, views, value, defaultValue, onChange, className, classes, disableFuture, disablePast, minTime, maxTime, shouldDisableTime, shouldDisableClock, minutesStep, ampm, ampmInClock, components, componentsProps, slots, slotProps, readOnly, disab...' is not assignable to type 'PickerViewRenderer<unknown, TimeViewWithMeridiem, TimeViewRendererProps<TimeViewWithMeridiem, BaseClockProps<unknown, TimeViewWithMeridiem>>, {}>'.

TS2322: Type '<TDate extends unknown>({ view, onViewChange, focusedView, onFocusedViewChange, views, value, defaultValue, onChange, className, classes, disableFuture, disablePast, minTime, maxTime, shouldDisableTime, shouldDisableClock, minutesStep, ampm, ampmInClock, components, componentsProps, slots, slotProps, readOnly, disab...' is not assignable to type 'PickerViewRenderer<unknown, TimeViewWithMeridiem, TimeViewRendererProps<TimeViewWithMeridiem, BaseClockProps<unknown, TimeViewWithMeridiem>>, {}>'.
```

### Expected behavior 🤔

No type error.

Am I missing something here?

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #8821

- Adjust `viewRenderers` typing to allow for both `TimeClock` as well as `DigitalClock` overriding.
- Avoid appending the `meridiem` view when some other renderer than `renderMultiSectionDigitalClockTimeView` is provided to the `hours` renderer. (i.e. providing `renderTimeViewClock`).
- Fix viewRenderers individual view entry typing to contain only the relevant `views` key. This allows passing `hours: renderDigitalClockTimeView` without errors complaining that the views have all possible views instead of only the one that is being overridden.
- Small typing fixes/improvements

### CODE REVIEW

File: packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx [hunk 1]
```diff
@@ -56,9 +56,13 @@ const DesktopTimePicker = React.forwardRef(function DesktopTimePicker<TDate>(
   const actionBarActions: PickersActionBarAction[] = shouldRenderTimeInASingleColumn
     ? []
     : ['accept'];
-  const views: readonly TimeViewWithMeridiem[] = defaultizedProps.ampm
-    ? [...defaultizedProps.views, 'meridiem']
-    : defaultizedProps.views;
+  // Need to avoid adding the `meridiem` view when unexpected renderer is specified
+  const shouldHoursRendererContainMeridiemView =
+    viewRenderers.hours?.name === renderMultiSectionDigitalClockTimeView.name;
```
Comment (LukasTy) [inline packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx:61]: If you have any better solutions—I'm welcome to suggestions 🙈 🤷

File: packages/x-date-pickers/src/timeViewRenderers/timeViewRenderers.tsx [hunk 2]
```diff
@@ -50,13 +50,13 @@ export const renderTimeViewClock = <TDate extends unknown>({
   autoFocus,
   showViewSwitcher,
   disableIgnoringDatePartForTimeValidation,
-}: TimeViewRendererProps<TimeView, TimeClockProps<TDate>>) => (
+}: TimeViewRendererProps<TimeViewWithMeridiem, TimeClockProps<TDate, TimeViewWithMeridiem>>) => (
   <TimeClock<TDate>
-    view={view}
+    view={view as TimeView}
```
Comment (LukasTy) [inline packages/x-date-pickers/src/timeViewRenderers/timeViewRenderers.tsx:55]: A bit hacky, I know. 🙈 
But do you know any better way how to support all the time renderers on `DesktopTimePicker`, which expects `TimeViewWithMeridiem` capable renderers. 🤷

File: packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx (hunk 1 above)
Comment (alexfauquette) [reply packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx:61]: Why can't you use the `shouldRenderTimeInASingleColumn`?

**Review by alexfauquette — APPROVED** [review]

File: packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx (hunk 1 above)
Comment (alexfauquette) [reply packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.tsx:61]: Ok, that's triky. Maybe better to keep your hacky solution for now, And come back on this issue when documenting how to customize those view
