### PR TITLE
[DataGrid] Fix order of `onClick` prop on toolbar buttons

### LINKED ISSUE #16355: [DataGrid] GridToolbarColumnsButton does not open popover the onClick button is defined
### Search keywords

GridToolbarColumnsButton

### Latest version

- [x] I have tested the latest version

### Affected products

_No response_

### Steps to reproduce

Steps:
1. Open this link to live example: https://stackblitz.com/edit/react-3lpvhggp?file=Demo.tsx
2. Click on the columns button
3. Popover is not displayed

### Current behavior

1. Open this link to live example: https://stackblitz.com/edit/react-3lpvhggp?file=Demo.tsx
2. Click on the columns button
3. Popover is not displayed

### Expected behavior

1. Open this link to live example: https://stackblitz.com/edit/react-3lpvhggp?file=Demo.tsx
2. Click on the columns button
3. Popover should be displayed, else provide a way to open/close the columns popover to the consumer

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 131.0.6778.265
    Edge: Not Found
    Safari: 16.3
  npmPackages:
    @mui/x-data-grid-premium: 7.24.1 
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by KenanYusuf**
Fixes #16355 

`onClick` needs to come after `{...buttonProps}` to ensure the button behavior works as expected when an `onClick` prop is passed to the toolbar button.

### CODE REVIEW

File: packages/x-data-grid/src/components/toolbar/GridToolbarColumnsButton.tsx [hunk 1]
```diff
@@ -69,14 +69,15 @@ const GridToolbarColumnsButton = forwardRef<HTMLButtonElement, GridToolbarColumn
...
+          {...buttonProps}
           onPointerUp={(event) => {
             if (preferencePanel.open) {
               event.stopPropagation();
             }
+            buttonProps.onPointerUp?.(event);
           }}
-          {...rootProps.slotProps?.baseButton}
-          {...buttonProps}
+          onClick={showColumns}
```
Comment (arminmeh) [inline packages/x-data-grid/src/components/toolbar/GridToolbarColumnsButton.tsx:80]: isn't this is now overriding custom `onClick` handler.
I think that the approach [suggested in the issue](https://github.com/mui/mui-x/issues/16355#issuecomment-2616193014) is the way to go

Comment (KenanYusuf) [reply packages/x-data-grid/src/components/toolbar/GridToolbarColumnsButton.tsx:80]: In the `showColumns` function we are calling `buttonProps.onClick?.(event)`

**Review by arminmeh — APPROVED** [review]
