### PR TITLE
[DataGridPremium] Support sort-dependent aggregation and improve performance

### LINKED ISSUE #18342: [data grid] Aggregation does not respond to sorting (+getCellValue not usable with pivoting)
### Search keywords

aggregation sorting pivot first last latest

### Latest version

- [x] I have tested the latest version

### Affected products

Data Grid

### Steps to reproduce

Steps:
1. Open this link to live example: https://stackblitz.com/edit/zvyat1a6?file=src%2FDemo.tsx
2. Sort by transaction date
3. See how the aggregated value for "Price (first)"  doesn't change

### Current behavior

Aggregation doesn't honor sorting, which prevents some aggregations such as "First/Last". This is especially an issue in pivoting and row grouping of data where values don't stack (e.g. share price), but you would want to show e.g. the latest share price for the quarter instead.

We work a lot with financial data, and thus find pivoting borderline useless until we get first/last (or better yet latest) aggregations to work.

I have also tried to hack this by overriding `getCellValue` and returning the whole row for it + comparing dates. But within pivoting, it returns values for all the rows, and new columns get autogenerated that hold the actual values for that specific column, but it's not possible to understand which dynamic column we're aggregating at a given point. Hence, overriding `getCellValue` breaks aggregation completely.

Reproduction: https://stackblitz.com/edit/zvyat1a6-eigrrkht?file=src%2FDemo.tsx
Check console, for every column that we're aggregating, all price values are available, hence Google's first share price becomes completely wrong ($1000, which it not even a valid value).

### Expected behavior

1. Aggregation values should be provided in a sorted order
2. getCellValue should only fetch values for the pivoted column, not all columns

### Context

Ag-grid offers this out of the box (click on values -> first(Gold)): https://www.ag-grid.com/javascript-data-grid/pivoting/

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by lauri865**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #18342 (the first part of it)

Adds a new `applySorting?: boolean` property to `GridAggregationFunction`

The only thing that probably needs additional polish is this:
```typescript
useGridEvent(apiRef, 'filteredRowsSet', applyAggregation);
useGridEvent(apiRef, 'sortedRowsSet', applyAggregation);
```

These can in some instances (on mount) be triggered sequentially if I remember correctly (correct me if I'm wrong), so might be some room for optimisation.

Changes:
* Optimized columns updates (-800ms with a large amount of columns)
* Optimized column group creation (50-100x improvement under large number of columns)
* Improved aggregation performance (from 6000ms+ -> 275ms in my test case)
* Removed `pivotModeChange` control state, because `pivotMode` is not strictly controlled, and in an uncontrolled mode, it delays updates by 1 render
* Fixed a case whereby rows are improperly restored (props.rows takes overrides any subsequent changes made via the apiRef)
* Created windowed and chunked aggregation logic, which calculates the current viewport instantly, and the rest in chunks to avoid locking the main thread. Chunksize logic could be improved further; one idea is to continue with the chunks until we hit X amount of ms, or recalculate chunkSize based on how long the previous chunk took.
* Deduplicated calls to `applyAggregation` (currently it was called many times in a row)
* Support for `applySorting` in aggregation functions
* Expose `field` to `getCellValue` in aggregation functions to make custom logic possible, especially in the context of pivoting where fields are automatically generated
* Fixed: column groups based on numbers were not sorted correctly, as all headernames were coerced to strings
* Fixed: pivoting doesn't initialize when rows are updated with `setRows` while `isLoading` internal state is still true. Common pattern would be to set rows within `useLayoutEffect` when `isLoading` is changing (to avoid flickering), and that can't be caught by the current logic since an upperlevel `useLayoutEffect` will always run before the update of the internal state. Deferred initializing `nonPivotDataRef` to the first row update (works with all of `setRows`,  `updateRows` and `props.rows`) instead of listening to the isLoading change of internal state.

Performance updates; before:

https://github.com/user-attachments/assets/34bd24b8-7f26-467e-83a9-9478e320adfc

After:

https://github.com/user-attachments/assets/d6985bdb-b078-4f84-99b3-913cbd85b9bd

### CODE REVIEW

**Comment by lauri865** [comment]
Now also exposed `field` to `getCellValue` that's required to pull the correct data for pivoting, fixing the second part of the issue.
I also exposed `api` in `aggregationFunction.apply`, as I've felt many times that I could build more flexible and performant aggregations if only I had more context to go by.

**Comment by lauri865** [comment]
Enabling pivot seems to trigger 5 instances of "filteredRowsSet" (each of them retriggers aggregations). And the same for "sortedRowsSet for whatever reason @cherniavskii 

Adding `applySorting` to the mix causes a visible slowdown.

Just press the toggle button and check console:
https://stackblitz.com/edit/g4dsphrl-sxhvdgqz?file=src%2FDemo.tsx,package.json

**Comment by lauri865** [comment]
I tried deduplicating some more expensive calls, but probably broke some tests (not sure if for functionality, but at least it will complain about `act()`.

One thing I still don't understand though – when stopping pivoting, columns get rehydrated 6 times:
6x `MUI X: useGridColumns - Columns pipe processing have changed, regenerating the columns`

**Comment by lauri865** [comment]
Did a bunch of optimisations in aggregation calculations. For a a large pivot table (10k rows, pivoted by date (value) and commodity in the dataset, summing "total in usd") – computation time went down from 6000ms+ to 375ms. A big culprit was nested function calls to access row values, which we can skip for pivoting + doing another full recursion over all rows/columns. isNumber custom function wrapper also added quite significant overhead for summing.

Can be still polished a bit I guess.

**Comment by lauri865** [comment]
From 375ms -> 260ms in my test case now that I stoped storing undefined values. I guess it's fair to assume that undefined has no meaning in aggreations, nulls might (although even that is slightly questionable, and could be optionally toggled). And there's tons of undefined values in pivoting at least.

**Comment by lauri865** [comment]
Fixed the last issue as well with cascading `hydrateColumns` updates by re-registering the `pipeApplier` when `pivotMode` changes. So the slow restore after pivoting in the after video should also hopefully be fixed now.

**Comment by lauri865** [comment]
Generalized the aggregation now for any depth. For traversal, we only fetch direct leaf values, otherwise merge the precomputed values on group level, instead of going through the nested tree over and over again.

**Comment by lauri865** [comment]
This took about 800ms when toggling a pivot with a large list of columns, now down to <1ms:
https://github.com/mui/mui-x/blob/8d434ffcb9d091293a682d79be94a81a9aa66812/packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts#L347-L353

There's still some room to optimise – 168ms just for columns + aggregation + row grouping – easy to lock up the main thread still:
* useGridColumns createColumnsState: 30.65087890625 ms
* useGridColumns setGridColumnsState: 138.465087890625 ms

**Comment by lauri865** [comment]
Toggling off pivoting doesn't lock up the UI anymore:

https://github.com/user-attachments/assets/e31021ba-b56f-4501-abe3-4ea9c173fec3

**Comment by lauri865** [comment]
Further improved column grouping performance by 50x+, which in my test case locked up the main thread, now fits into a single frame.  It was also previously run twice in a row when enabling pivoting.

**Comment by lauri865** [comment]
Implemented viewport aware, chunked aggregations to avoid locking. Switch animation runs buttery smooth even with 10k rows. With 100k rows it's still usable, but there's a slight lockup, depending on the dimensionality, but the bottleneck is not in aggregation anymore.

**Comment by lauri865** [comment]
New video added to the opening post ;)

**Comment by lauri865** [comment]
I'm not sure how to satisfy the tests without a lot of work. The quemicrotask and settimeout makes the test fail. Don't feel particularly like (=dont have the time for) updating all the  aggregation and pivoting tests with mock timers.

File: packages/x-data-grid-premium/src/hooks/features/aggregation/createAggregationLookup.ts [hunk 1]
```diff
@@ -62,39 +87,46 @@ const getGroupAggregatedValue = (
...
-          values: [],
-        };
-      }
-
+      let value;
       if (typeof aggregationFunction.getCellValue === 'function') {
-        aggregatedValues[j].values.push(aggregationFunction.getCellValue({ row }));
+        value = aggregationFunction.getCellValue({ field, row });
+      } else if (isPivotActive) {
+        // Since we know that pivoted fields are flat, we can use the row directly, and save lots of processing time
```
Comment (cherniavskii) [inline packages/x-data-grid-premium/src/hooks/features/aggregation/createAggregationLookup.ts:94]: That's a good assumption since all `valueGetter`s are being called when building the pivoted set of rows 👍🏻

File: packages/x-data-grid-generator/src/hooks/serverUtils.ts [hunk 2]
```diff
@@ -312,11 +312,14 @@ const applyAggregation = (
...
-      field,
-      groupId,
-    });
+    aggregateValues[`${field}Aggregate`] = aggregationFunction.apply(
+      {
+        values,
+        field,
+        groupId,
+      },
+      null as any, // we can't use apiRef here, and as long as we don't use advanced aggregation functions that depend on it, we're clear
```
Comment (cherniavskii) [inline packages/x-data-grid-generator/src/hooks/serverUtils.ts:321]: Yeah, that's fine.

> I also exposed api in aggregationFunction.apply, as I've felt many times that I could build more flexible and performant aggregations if only I had more context to go by.

BTW, do you have some specific examples you can share?

**Review by cherniavskii — COMMENTED** [review]
Thanks for the PR!
It's a lot to review, so I'll give it a few more passes. But overall, looks solid!

File: packages/x-data-grid-generator/src/hooks/serverUtils.ts (hunk 2 above)
Comment (lauri865) [reply packages/x-data-grid-generator/src/hooks/serverUtils.ts:321]: Sure, let's say you want to apply a weighted average calculation, and make the weight column configurable by the end-user. How would you achieve this?

**Comment by lauri865** [comment]
There's one last small thing I'd want to add - default sort order for columns. I'm yet to come across a situation where I'd like the (top level of) pivoted columns to appear in order they show up in the data. Especially not numerical categories or dates, but also imagine a list of countries showing up in a random order. So I always have to manually sort the columns anyways when changing them.

There's a few solutions:
1. Apply default sort ascending for columns added via the UI
2. The first, but only applying for the first level (although then we'd need to adjust when reordering)
3. The first, but only for number and date types
4. Globally inject a default, but then we'd need to add a null value to the interface to support unsorted views as well.

Thoughts @cherniavskii?

File: packages/x-data-grid-generator/src/hooks/serverUtils.ts (hunk 2 above)
Comment (cherniavskii) [reply packages/x-data-grid-generator/src/hooks/serverUtils.ts:321]: I would use a custom aggregation function with `getCellValue` and dynamically access the weights depending on the selected weight column. Something like this: https://stackblitz.com/edit/ucpxtjbq?file=src%2FDemo.tsx
If necessary, you could also access `apiRef` in the custom aggregation function.
WDYT?

**Comment by lauri865** [comment]
Fixed another issue that was bugging us that prevented pivoting from initializing when setting rows with `apiRef.current.setRows` while `isLoading` is changing from true -> false.

Also added a path to re-run state initializers to avoid cascading and conflicting states (e.g. changing `rowGroupingModel` ahead of setting rows would recalculate row groups on the old data, and the same for aggregation). That made brough a 100k row pivot to quite acceptable performance levels.

Note though: controlled mode is still quite unoptimized. It calculates the pivoting state, throws it away (ignores controlled state being set), and recalculates it once the upper-level state/prop updates (cc @cherniavskii).


100k rows:

https://github.com/user-attachments/assets/f5d739b5-0429-428d-a35b-275ab1e0d4d6

File: packages/x-data-grid-premium/src/hooks/features/pivoting/useGridPivoting.ts
Comment (cherniavskii) [inline packages/x-data-grid-premium/src/hooks/features/pivoting/useGridPivoting.ts:1]: > There's one last small thing I'd want to add - default sort order for columns.

You can use the controlled pivot model for this:
https://stackblitz.com/edit/m8vfrscs?file=src%2FDemo.tsx

But I'm also open to changing the default value.
How about using the first value from the column's `sortingOrder` list? https://mui.com/x/react-data-grid/sorting/#custom-sort-order

Comment (lauri865) [reply packages/x-data-grid-premium/src/hooks/features/pivoting/useGridPivoting.ts:1]: I think the first value of column's `sortingOrder` would be great.

Controlled prop: good point, however, since we treat pivoting model as persistent state (users can use it to explore data, navigate away, come back and continue), we'd rather not add a controlled prop for it (due to past scar tissue with performance and ease of restoring).

File: scripts/x-data-grid-premium.exports.json [hunk 3]
```diff
@@ -761,6 +761,7 @@
   { "name": "useKeepGroupedColumnsHidden", "kind": "Variable" },
   { "name": "useOnMount", "kind": "Function" },
   { "name": "useRunOnce", "kind": "Variable" },
+  { "name": "useRunOncePerLoop", "kind": "Function" },
```
Comment (romgrk) [inline scripts/x-data-grid-premium.exports.json:764]: I think we shouldn't expose our hook primitives, it forces those to follow semver rules and prevents refactoring them between major versions.

File: packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+        return;
+      }
+
+      if (isJSDOM) {
+        runner();
+      } else if (typeof queueMicrotask === 'function') {
+        queueMicrotask(runner);
+      } else {
+        Promise.resolve().then(runner);
+      }
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts]: The name of the hook doesn't exactly match its implementation. The microtask queue is run until it's empty, so if the scheduled callback somehow schedules itself again, it could run multiple times in a single tick of the event loop. I don't see the animation frame option being used. If that was removed, this hook could be renamed to something like `useScheduleAsMicrotask`. If what we need is really to run at most once per tick, then it should use a task, not a microtask.

Comment (romgrk) [reply packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts]: lint: `queueMicrotask` seems to be available in all our supported browsers, we can use it without guard.

Comment (lauri865) [reply packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts]: > The name of the hook doesn't exactly match its implementation. The microtask queue is run until it's empty, so if the scheduled callback somehow schedules itself again, it could run multiple times in a single tick of the event loop. I don't see the animation frame option being used. If that was removed, this hook could be renamed to something like `useScheduleAsMicrotask`. If what we need is really to run at most once per tick, then it should use a task, not a microtask.

Can you bring an example of how this is possible within the context of React? QueMicrotsk should put it at the end of the call stack, the only way it can schedule itself again is a straight up recursion that doesn't set any state (a state change would trigger a new render, and the microtask would run before that). Which is a) unlikely b) fine, since we want to avoid expensive calculations in the same frame that compute new state.

Comment (romgrk) [reply packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts]: I'm not opposed to the implementation, I'm just pointing out that the name doesn't strictly says what the implementation does. Hooks like this have a tendency to be re-used, and they might not be used by other maintainers in the same context with the same invariants.

> a state change would trigger a new render, and the microtask would run before that

I'm not completely sure about that, I feel like I've seen renders be started (back-to-back, due to effects) without microtasks by React, but I could be mistaken.

Comment (lauri865) [reply packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts]: Fair with callout with the name, just want to make sure it's functionally sound as well. I'm not sure if `useScheduleAsMicroTask` is better though – it doesn't describe when it's run. Microtask has different meanings, but in this context my aim at least is that it runs max once per render phase / event loop.

Example here: https://codesandbox.io/p/sandbox/ptnhjf
We trigger state updates from 2 layout effects, and 1 useEffect – `queueMicroTask` slots it after the last `useEffect`, even when called from within a useLayoutEffect, as the call stack is pre-defined for a functional components. Or at least that's what has been my understanding, and I've also used it in the past in such manner.

However, funnily, I asked ChatGPT about it, and it gaslighted me to believing that a `queueMicrotask` from `useLayoutEffect` would be called before `useEffect`. Even provided me with a code snippet that proved me right and its own very convincing claims wrong.

> I'm not completely sure about that, I feel like I've seen renders be started (back-to-back, due to effects) without microtasks by React, but I could be mistaken.

Could be the behaviour of React in the past, but with batched state updates, that can't be the case, can it? How would batching work if a state update would trigger a back-to-back render?

**Comment by lauri865** [comment]
Also implemented `exportState` with pivoting (we really needed it, since otherwise restored state is messed up).

File: packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts (hunk 4 above)
Comment (romgrk) [reply packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts]: > Could be the behaviour of React in the past, but with batched state updates, that can't be the case, can it? How would batching work if a state update would trigger a back-to-back render?

If a state update is triggered within an effect, React could determine that it still has time to run and trigger a new render phase. Besides, batching doesn't necessarily imply using microtasks, because React is at the root of the call stack it can batch updates done within the full render cycle without resorting to microtasks.

Anyway, if we can't find a better name I don't want to cause too much bikeshedding, the current name is acceptable.

**Review by cherniavskii — APPROVED** [review]
The changes look good to me, I'll look into failing tests!
Thanks again, Lauri!

File: packages/x-data-grid/src/hooks/core/pipeProcessing/useGridPipeProcessing.ts [hunk 5]
```diff
@@ -65,6 +69,8 @@ export const useGridPipeProcessing = (apiRef: RefObject<GridPrivateApiCommon>) =
     isRunning.current = false;
   }, []);
 
+  const runAppliersDeferred = useRunOncePerLoop(runAppliers, false, getGroupScopeKey);
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/core/pipeProcessing/useGridPipeProcessing.ts]: cc @romgrk I used the same approach with `useRunOncePerLoop` to only run appliers once after all pipe processors change. Before that, appliers were called after each pipe processor change, which in some cases hurts performance.
I modified `useRunOncePerLoop` to support scopes, so that a single hook can be used to schedule multiple appliers independently.
Any objections?

This change naturally inflicted a lot of updates to tests (mostly `await mictotasks()` at the end of the test to avoid React act warnings).
I think it's fine, and I'll mention this in the changelog and in the docs.

File: packages/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx [hunk 6]
```diff
@@ -325,8 +328,9 @@ describe('<DataGridPro /> - Detail panel', () => {
     // Because of https://react.dev/blog/2024/04/25/react-19-upgrade-guide#strict-mode-improvements
     // from React 19 it is:
     //   2x during state initialization
+    // + 2x during state initialization (StrictMode)
     // + 2x when sortedRowsSet is fired
-    const expectedCallCount = reactMajor >= 19 ? 4 : 8;
+    const expectedCallCount = reactMajor >= 19 ? 6 : 12;
```
Comment (cherniavskii) [inline packages/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx]: I'm not exactly sure why this needed to be updated...

File: packages/x-data-grid/src/hooks/core/pipeProcessing/useGridPipeProcessing.ts (hunk 5 above)
Comment (lauri865) [reply packages/x-data-grid/src/hooks/core/pipeProcessing/useGridPipeProcessing.ts]: Is there a case in which this could introduce flickering or other unwanted behaviour – e.g. some changes get flushed to DOM based on updated state, but pipe processing takes place after that (e.g. state changes -> DOM updates based on the change state -> columns get rehydrated only on the next render). Essentially the equivalent of setting state in `useEffect` vs. `useLayoutEffect`.

In the case of aggregation it's fine (especially with batched processing now), but broadly applying it to all pipe processors might make be a bit more questionable / tricky.

Alternative approach for this case would be to mark a group as pending for updates, and add a hook as the last entry in `useDatagridPremiumComponent` that clears the queue / triggers `runAppliers`.

Edit: could potentially explain the next comment regarding increased call count (just a guess at this point, haven't dug into it)

Edit 2: also, since formerly `runAppliers` was called effectively inline in the component body, any state updates from pipe processing will prevent effects from being run. But in the case of the new implementation with `useRunOncePerLoop`, all effects are run before the appliers, which could (in theory) negate performance gains from deduplicating calls to `runAppliers`. Check: https://codesandbox.io/p/sandbox/ptnhjf

Comment (lauri865) [reply packages/x-data-grid/src/hooks/core/pipeProcessing/useGridPipeProcessing.ts:72]: Or actually, the deduplication can be even easier for pipe processing – just accept the first call to `runPipeApplier` per render and set a flag to prevent further calls, which gets cleared in a `useEffect`.

Microtasks are needed only in relation to events, as there's a timing issue. Pipe processors depend on state / props, which are share across all hooks in the same render pass / component.

Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/core/pipeProcessing/useGridPipeProcessing.ts]: > Is there a case in which this could introduce flickering or other unwanted behaviour – e.g. some changes get flushed to DOM based on updated state, but pipe processing takes place after that (e.g. state changes -> DOM updates based on the change state -> columns get rehydrated only on the next render). Essentially the equivalent of setting state in useEffect vs. useLayoutEffect.

I haven't noticed anything like that.

> Alternative approach for this case would be to mark a group as pending for updates, and add a hook as the last entry in useDatagridPremiumComponent that clears the queue / triggers runAppliers.

That's a good idea, I'll give it a try 👍🏻

> But in the case of the new implementation with useRunOncePerLoop, all effects are run before the appliers, which could (in theory) negate performance gains from deduplicating calls to runAppliers. Check: [codesandbox.io/p/sandbox/ptnhjf](https://codesandbox.io/p/sandbox/ptnhjf)

Hmm, interesting. What would be a potential scenario where performance gains will be negated? In the demo you shared, `useRunOncePerLoop` results in less rerenders and less effect calls:

| useRunOncePerLoop | inline |
| ---- | ---- |
|  |  |

**Comment by lauri865** [comment]
Thanks for all the heavy lifting @cherniavskii for making this PR happen – and sorry for all the rework for tests this brought 🙏❤️

**Comment by cherniavskii** [comment]
@lauri865 Thank you for making it possible, we appreciate it!
