### PR TITLE
[DataGrid] Fix crash when `rows` and `rowModesModel` are updated simultaneously

### LINKED ISSUE #13358: DataGridPro: Error when changing rowModesModel and rows at the same time
### Search keywords

datagridpro

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-wbis3e?file=Demo.tsx

Steps:
1. Press the "Set some other row data button"

### Current behavior

Crashes with the following error
Error: MUI X: The data grid component requires all rows to have a unique `id` property.
Alternatively, you can use the `getRowId` prop to specify a custom id for each row.
A row was provided without id when calling updateRows():
{}

### Expected behavior

Should set the new rows to the row parameter and the new computed rowModesModel to the rowModesModel parameter without raising an error.

### Context

I want all my cells to be in edit mode at all times. This worked perfectly in 6.19.5, but no longer works on the latest version (7.6.1).

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

This is regardless of browser.
```
  System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.3.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (125.0.2535.67)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: 11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.43
    @mui/core-downloads-tracker:  5.15.18
    @mui/icons-material:  5.15.18
    @mui/material:  5.15.18
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.15
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-data-grid:  7.5.0
    @mui/x-data-grid-pro:  7.5.0
    @mui/x-date-pickers:  7.5.0
    @mui/x-date-pickers-pro:  7.5.0
    @mui/x-license:  7.2.0
    @mui/x-tree-view:  7.5.1
    @types/react: 18.3.2 => 18.3.2
    react: 18.3.1 => 18.3.1
    react-dom: 18.3.1 => 18.3.1
    typescript: 5.2.2 => 5.2.2
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by michelengelen**
Fix `DataGrid` crash when `rows` and `rowModesModel` are updated simultaneously

### Short Summary
This PR fixes a crash in the `DataGrid` that occurred when a row was removed from the `rows` prop while its corresponding entry was also being removed from (or changed in) the `rowModesModel`.

#### Root Cause
When a row mode changes from `Edit` to `View` (including when it's removed from the model), the `useGridRowEditing` hook attempts to persist any pending changes by calling `apiRef.current.updateRows`. If the row was simultaneously removed from the `rows` prop, `apiRef.current.getRow(id)` returned `undefined`, causing `updateRows` to be called with an invalid object (missing the `id` property), which triggered a validation error.

Fixes #13358

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts [hunk 1]
```diff
@@ -810,12 +810,24 @@ export const useGridRowEditing = (
...
+      const row = rowsLookup[id];
+      const originalId = row ? apiRef.current.getRowId(row) : id;
       if (params.mode === GridRowModes.Edit && prevMode === GridRowModes.View) {
         updateStateToStartRowEditMode({ id: originalId, ...params });
       } else if (params.mode === GridRowModes.View && prevMode === GridRowModes.Edit) {
-        updateStateToStopRowEditMode({ id: originalId, ...params });
+        if (row) {
+          updateStateToStopRowEditMode({ id: originalId, ...params });
+        } else {
+          updateOrDeleteRowState(id, null);
```
Comment (mj12albert) [inline packages/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts]: From Codex review:

> `rowModesModel` cleanup is skipped when the edited row is already deleted, which changes stop-edit lifecycle semantics and can leave stale `mode: 'view'` entries.
> The new `row`-missing branch only clears edit state and `prevRowValuesLookup`, but does not call `updateRowInRowModesModel(id, null)` (which the normal `finishRowEditMode` path does). This means uncontrolled mode can retain stale entries for deleted rows, and `onRowModesModelChange` may not emit the cleanup `{}` event that existing behavior expects (see rowEditing.DataGridPro.test.tsx:1513).
> 
> Is it intentional to change the stop-edit contract for deleted rows so model cleanup is no longer emitted? If not, the missing-row branch should likely also clear the row mode model entry.

Comment (michelengelen) [reply packages/x-data-grid/src/hooks/features/editing/useGridRowEditing.ts]: Nice catch from codex ... I did add the call to `updateRowInRowModesModel` to the `else` branch to clean up row modes as well.

**Comment by arminmeh** [comment]
This update changes the behavior reported in https://github.com/mui/mui-x/issues/13707 and implemented in https://github.com/mui/mui-x/pull/16741.

Is this the intention?
The expectation in the related issue is to avoid having an error, not to completely remove the callback call.

My point is, will there be people complaining about not having a call at all?

**Comment by michelengelen** [comment]
> This update changes the behavior reported in #13707 and implemented in #16741.
> 
> Is this the intention? The expectation in the related issue is to avoid having an error, not to completely remove the callback call.
> 
> My point is, will there be people complaining about not having a call at all?

That's a good point and I was thinking about this as well. But logically speaking this does not make a lot of sense, since the row is already deleted anyways, so why would you want a callback with a deleted row?

I can look into making this possible, but IMO it shouldn't fire `processRowUpdate` at all if the row does not exist anymore.

And as I wrote in [this comment](https://github.com/mui/mui-x/issues/13358#issuecomment-3873167899) the original issues does not happen anymore (likely due to #16741), so this is intended to fix a row reappearing when stopping edit mode after it got already deleted.

**Comment by michelengelen** [comment]
@arminmeh I have adjusted the flow to ensure that `processRowUpdate` gets called, but does not update row state afterwards, so the row will not reappear.
