### PR TITLE
[pickers] Let the field components handle their opening UI, and allow field editing on mobile pickers

### LINKED ISSUE #6217: [pickers] Offer a prop to start mobile picker in keyboard entry mode
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In our mobile app we find that users are much quicker able to type in a date in the past (e.g. Date of birth) than going through the MobileDatePicker and having to pick year, then month, then day.  But the pencil icon that's in the modal is often missed by users and we would like a prop that switches the 'default' view that first shows up to be this:
image

### Examples 🌈

https://mui.com/x/react-date-pickers/date-picker/

We want to be able to have this open first:
image

Then user can switch to this:
image

### Motivation 🔦

Dates far in the past are often easier to just type in on mobile and some less tech savvy users often miss the pencil icon to switch from the calendar entry view.

### Order ID 💳 (optional)

_No response_

### LINKED ISSUE #7869: [pickers] Support keyboard entry on mobile
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/silly-mirzakhani-dhigkw?file=/demo.tsx:1142-1158&resolutionWidth=320&resolutionHeight=675

Nothing happens if we add the prop `disableOpenPicker` to the component

### Current behavior 😯

`MobileTimePicker` is opening with standard Clock view for choosing the time even disableOpenPicker is present as `true`

### Expected behavior 🤔

The expectation to have a possibility to set the time without Clock, by typing as in `DesktopTimePicker`

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### LINKED ISSUE #14787: [fields] Move the logic of the fields opening to be in the field instead of in the picker
Part of #13188

Use the new `PickersFieldContext` and its new `onViewToggle` (name under discussion in #14606) to move all the opening logic from the picker hooks (`useDesktopPicker`, `useMobileRangePicker` etc...) to the field component.

This comes with several benefits:
- The single input range field will be able to open with an end adornment and the multi input range field when clicking the value
- All the slots related to the field will be resolved by the field and not by the picker which simplifies the logic
- No need for `useEnrichedRangePickerFieldProps` anymore (might need to keep it for v8 depending on the time we have but the goal is to eventually drop this hook)
- The props received by the fields are no longer tied to MUI APIs, which makes the building of custom hooks a lot simpler.

The main downside I see is that the field include some code that is not needed when used as standalone. But I think the top priority should always be the quality of the pickers over the quality of the field.

**Search keywords**:

### PR DESCRIPTION
**Pull request by flaviendelangle**
Closes #7869
Closes #14787 
Closes #6217

- [x] The non-range mobile pickers now open using a button (instead of click) 
- [x] The non-range mobile pickers have now an editable field
- [x] The opening logique of the non-range pickers is now handled by the field themselves
- [x] The `useClearableField` hook is no longer used internally. It can remain available for custom fields during v8, in v9  we will have the composition API for a better DX
- [x] The clear button and the opening button can now independently be rendered on the start of on the end of the field using the `openPickerButtonPosition` and `clearButtonPosition` field props.

Not in this PR:

- The single input range fields is using the new component that handles the adornments, but the opening button is always hidden (because the `useEnrichedRangePickerFieldProps` stills handle the opening on click)
- The multi input range fields are not yet using the new component that handles the adornments

## Extracted PRs

- #15701
- #15707
- #15763
- #15776

### CODE REVIEW

File: packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx [hunk 1]
```diff
@@ -0,0 +1,329 @@
...
+    ownerState,
+  });
+
+  const ClearButton = slots.clearButton ?? MuiIconButton;
+  // We don't want to forward the `ownerState` to the `<IconButton />` component, see mui/material-ui#34056
+  const { ownerState: clearButtonOwnerState, ...clearButtonProps } = useSlotProps({
+    elementType: ClearButton,
+    externalSlotProps: slotProps?.clearButton,
+    className: 'clearButton',
+    additionalProps: {
```
Comment (LukasTy) [inline packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx:161]: You probably forgot to provide the `sx` prop? 🤔 
https://github.com/mui/mui-x/blob/3b0bba2453c8b7a052b2e434260a2f8d911f8c62/packages/x-date-pickers/src/hooks/useClearableField.tsx#L104-L119

In this branch, the clearable button is always visible, whereas currently, it is only shown on hover or when the input is focused.

The biggest question is how do we approach the clearable behavior on the Mobile Picker - what behavior would bring enough value to users on Mobile? 🤔

**Review by LukasTy — COMMENTED** [review]
Great work! 💯 
Leaving some nitpicks, open questions and one noted "problem" regarding clear button visibility. 😉

**Comment by LukasTy** [comment]
Won't this also solve https://github.com/mui/mui-x/issues/6217? 🤔

File: docs/data/date-pickers/date-range-picker/date-range-picker.md [hunk 2]
```diff
@@ -46,10 +46,10 @@ Learn more about the _Controlled and uncontrolled_ pattern in the [React documen
 The component is available in four variants:
 
 - The `DesktopDateRangePicker` component which works best for mouse devices and large screens.
-  It renders the views inside a popover and allows editing values directly inside the field.
+  It renders the views inside a popover and a field for keyboard editing.
 
 - The `MobileDateRangePicker` component which works best for touch devices and small screens.
-  It renders the view inside a modal and does not allow editing values directly inside the field.
+  It renders the view inside a modal and a field for keyboard editing.
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply docs/data/date-pickers/date-range-picker/date-range-picker.md]: Indeed 
It will become editable once we switch to an end adornment for the mobile range pickers.
We must make sure to update those doc sentences then :+1:

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/SingleInputDateRangeField.tsx [hunk 3]
```diff
@@ -66,15 +62,14 @@ const SingleInputDateRangeField = React.forwardRef(function SingleInputDateRange
...
-  const processedFieldProps = useClearableField({
-    ...convertedFieldResponse,
-    slots,
-    slotProps,
-  });
-
-  return <TextField {...processedFieldProps} />;
+  return (
+    <PickerFieldUI
+      slots={{ openPickerIcon: CalendarIcon, ...slots }}
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-date-pickers-pro/src/SingleInputDateRangeField/SingleInputDateRangeField.tsx]: We discussed it during our meeting with @LukasTy 
I removed the slots that are picker-specific from the public API of the field and use a context instead to pass the information.

Having picker-specific code inside the field is not a problem to me since the vast majority of the users are using the pickers directly and we want mostly to optimize for this use case.

File: packages/x-date-pickers/src/DatePicker/tests/DatePicker.test.tsx [hunk 4]
```diff
@@ -1,20 +1,21 @@
...
+import { dialogClasses } from '@mui/material/Dialog';
 import { DatePicker } from '@mui/x-date-pickers/DatePicker';
-import { screen } from '@mui/internal-test-utils/createRenderer';
+import { fireEvent, screen } from '@mui/internal-test-utils/createRenderer';
 import { createPickerRenderer, stubMatchMedia } from 'test/utils/pickers';
-import { pickersInputBaseClasses } from '@mui/x-date-pickers/PickersTextField';
 
 describe('<DatePicker />', () => {
-  const { render } = createPickerRenderer();
+  const { render } = createPickerRenderer({ clock: 'fake' });
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-date-pickers/src/DatePicker/tests/DatePicker.test.tsx]: It works :ok_hand:

File: docs/data/date-pickers/custom-opening-button/CustomPropsOpeningButton.tsx.preview [hunk 5]
```diff
@@ -6,7 +6,7 @@
     },
     // Targets the `InputAdornment` component.
     inputAdornment: {
-      position: 'start',
+      component: 'span',
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply docs/data/date-pickers/custom-opening-button/CustomPropsOpeningButton.tsx.preview:9]: Yes: https://deploy-preview-15671--material-ui-x.netlify.app/x/migration/migration-pickers-v7/#slot-inputadornment

File: docs/data/date-pickers/custom-opening-button/custom-opening-button.md [hunk 6]
```diff
@@ -39,6 +39,12 @@ If you want to track the opening of the picker, you should use the `onOpen` / `o
 
 :::
 
+## Render the opening button at the start of the input
+
+You can use the `openPickerButtonPosition` on the `field` slot to set the opening button at the start of the input (on the left in lef-to-right direction, on the right in left-to-right direction):
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply docs/data/date-pickers/custom-opening-button/custom-opening-button.md:44]: Could you describe what is inconsistent in this demo?
I'm not sure to follow you

[the remark this answers is not in the document]
Comment (LukasTy) [reply docs/data/date-pickers/custom-opening-button/custom-opening-button.md:44]: I meant that technically this demo has nothing explicitlt to do with `RTL` behavior, it's just the default to swap elements.
I would suggest omitting the overly specific details about orientation specifics. 🤔

File: packages/x-date-pickers/src/DateTimePicker/tests/DateTimePicker.test.tsx [hunk 7]
```diff
@@ -3,18 +3,18 @@ import { expect } from 'chai';
...
+  it('should render in mobile mode when `useMediaQuery` returns `false`', async () => {
     const originalMatchMedia = window.matchMedia;
     window.matchMedia = stubMatchMedia(false);
 
-    render(<DateTimePicker />);
+    const { user } = render(<DateTimePicker />);
 
-    expect(screen.getByLabelText(/Choose date/)).to.have.class(pickersInputBaseClasses.input);
+    await user.click(screen.getByLabelText(/Choose date/));
+    expect(screen.getAllByRole('dialog')).to.have.length(1);
```
Comment (LukasTy) [inline packages/x-date-pickers/src/DateTimePicker/tests/DateTimePicker.test.tsx:17]: Nitpick: You could use the following:
```suggestion
    expect(screen.getByRole('dialog')).toBeVisible();
```

File: packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx [hunk 8]
```diff
@@ -0,0 +1,501 @@
...
+  }
+
+  if (
+    !textFieldProps.InputProps?.endAdornment &&
+    (clearButtonPosition === 'end' || openPickerButtonPosition === 'end')
+  ) {
+    textFieldProps.InputProps.endAdornment = (
+      <InputAdornment {...endInputAdornmentProps}>
+        {clearButtonPosition === 'end' && (
+          <ClearButton {...clearButtonProps}>
```
Comment (LukasTy) [inline packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx:238]: Based on the test failures we can see that this is a behavior change.
For now, the clear button is only rendered when the field is not empty.
Do we want/need this change?

File: packages/x-date-pickers/src/DatePicker/tests/DatePicker.test.tsx [hunk 9]
```diff
@@ -3,18 +3,18 @@ import { expect } from 'chai';
...
-  it('should render in mobile mode when `useMediaQuery` returns `false`', () => {
+  it('should render in mobile mode when `useMediaQuery` returns `false`', async () => {
     const originalMatchMedia = window.matchMedia;
     window.matchMedia = stubMatchMedia(false);
 
-    render(<DatePicker />);
+    const { user } = render(<DatePicker />);
 
-    expect(screen.getByLabelText(/Choose date/)).to.have.class(pickersInputBaseClasses.input);
+    await user.click(screen.getByLabelText(/Choose date/));
```
Comment (LukasTy) [inline packages/x-date-pickers/src/DatePicker/tests/DatePicker.test.tsx:16]: Maybe let's keep the test sync and use `fireEvent` instead? 🤔 
`userEvent` is flaky due to leaking test runtime. 🙈

**Review by LukasTy — COMMENTED** [review]
Great job refining it. 👍 💯 
A final round of comments and request from @noraleonte to check the clearable behavior on mobile.
Do you think always showing the clear button on mobile is a good UX? 🤔 

___
The return of focus behavior seems broken again. 🙈 
After closing the Picker, the focus should be returned to the button, while now it gets back to the field... 🙈 
Could we add tests to cover this use case? It seems it is somewhat fragile and this is the 2nd time we are "trying" to break it. 😆

File: packages/x-date-pickers/src/DateTimePicker/tests/DateTimePicker.test.tsx (hunk 7 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/DateTimePicker/tests/DateTimePicker.test.tsx:17]: It "works", but not because `toBeVisible` does the right check.

If you don't open the picker, you want a clean error message, and that's not the case here :/
`getByRole` crashes when 0 element match:

```
TestingLibraryElementError: Unable to find an element with the role "dialog"
```

If you replace with `queryByRole`, then it's `toBeVisible` that crashes because it tries to access `style` of an un-existing element:

```
TypeError: Cannot read properties of null (reading 'style')
```

I'm not a fan of having tests fails because the tools used don't support a scenario.
Reading the test, you don't know if it was supposed to fail or not.

If you prefer, the following also works:

```
expect(screen.queryByRole('dialog')).to.not.equal(null);
```

File: packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx (hunk 8 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/components/PickerFieldUI.tsx:237]: No, I mis-read the previous version
Reverted

File: packages/x-date-pickers/src/DateTimePicker/tests/DateTimePicker.test.tsx (hunk 7 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/DateTimePicker/tests/DateTimePicker.test.tsx]: Fair points. 👍 
Your last suggestion sounds the most optimal and correct given the assertions we have access to. 💯

**Comment by flaviendelangle** [comment]
> Do you think always showing the clear button on mobile is a good UX? 🤔

Unless I'm not checking correctly, it's also the behavior on master (and on v7).
It's debatable for sure.

File: packages/x-date-pickers/src/DatePicker/tests/DatePicker.test.tsx (hunk 9 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/DatePicker/tests/DatePicker.test.tsx]: image

Looks like the CI doesn't like when I use `fireEvent` :/

Comment (LukasTy) [reply packages/x-date-pickers/src/DatePicker/tests/DatePicker.test.tsx]: Oh shoot... Those inconsistencies are getting very old. 🙈 
It would have probably been fine with `clock: 'fake'` setting. 🤷

**Review by LukasTy — COMMENTED** [review]
> Unless I'm not checking correctly, it's also the behavior on master (and on v7).
> It's debatable for sure, but it's not related to this PR specifically 😁

The mobile variants are not clearable for now, because input is readonly. 🤔 
But yes, I agree, the desired Mobile behavior is not directly related to this PR and can be changed later. 👍 

We still have the flickering and focus regressions present in this PR. 🙈 

https://github.com/user-attachments/assets/67a09b89-ad64-4c80-97aa-ed75b21c308a

File: packages/x-date-pickers/src/DatePicker/tests/DatePicker.test.tsx (hunk 9 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/DatePicker/tests/DatePicker.test.tsx]: Do you prefer `userEvent`, `clock: 'fake'` or another solution ? :laughing:

**Comment by flaviendelangle** [comment]
> The mobile variants are not clearable for now, because input is readonly. 🤔

I was talking about the standalone field on mobile which was editable.
But indeed I missed that it changes the behavior when used inside a mobile picker.
For me it make sense to follow the behavior of the standalone field here. If the standalone field on mobile always show the clearable icon then I would also show it when used inside a mobile picker. And if we don't like this behavior then modify it for both.

File: packages/x-date-pickers/src/DatePicker/tests/DatePicker.test.tsx (hunk 9 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/DatePicker/tests/DatePicker.test.tsx]: Until fake clock mocking leaking is not fixed—`clock: 'fake'` and using `fireEvent` seems safer. 🙈

**Comment by LukasTy** [comment]
> > The mobile variants are not clearable for now, because input is readonly. 🤔
> 
> I was talking about the standalone field on mobile which was editable. But indeed I missed that it changes the behavior when used inside a mobile picker. For me it make sense to follow the behavior of the standalone field here. If the standalone field on mobile always show the clearable icon then I would also show it when used inside a mobile picker. And if we don't like this behavior then modify it for both.

Fair point. 🙈 
I was looking at Picker and you were probably looking at Field only. 😆

File: docs/data/date-pickers/custom-opening-button/custom-opening-button.md (hunk 6 above)
[the remark this answers is not in the document]
Comment (noraleonte) [reply docs/data/date-pickers/custom-opening-button/custom-opening-button.md:44]: I am with Lukas on this one. Maybe rephrasing it like this would make sense?
```suggestion
You can use the `openPickerButtonPosition` on the `field` slot to position the opening button on the right or left side of the input:
```

File: docs/data/migration/migration-pickers-v7/migration-pickers-v7.md [hunk 10]
```diff
@@ -262,6 +262,20 @@ const theme = createTheme({
 });
 ```
 
+### Field editing on mobile Pickers
+
+The field is now editable if rendered inside a mobile Picker.
+Before v8, if rendered inside a mobile Picker, the field was read-only, and clicking anywhere on it would open the Picker.
+The behavior is now the same as if rendered inside a desktop Picker:
```
Comment (noraleonte) [inline docs/data/migration/migration-pickers-v7/migration-pickers-v7.md:269]:
```suggestion
The mobile and desktop Pickers now behave similarly:
```

File: docs/data/migration/migration-pickers-v7/migration-pickers-v7.md [hunk 11]
```diff
@@ -262,6 +262,20 @@ const theme = createTheme({
...
+
+- clicking on the field allows editing value with the keyboard
```
Comment (noraleonte) [inline docs/data/migration/migration-pickers-v7/migration-pickers-v7.md:271]:
```suggestion
- clicking on the field allows editing the value with the keyboard
```

File: docs/data/migration/migration-pickers-v7/migration-pickers-v7.md [hunk 12]
```diff
@@ -262,6 +262,20 @@ const theme = createTheme({
...
+- clicking on the field adornment opens the Picker
```
Comment (noraleonte) [inline docs/data/migration/migration-pickers-v7/migration-pickers-v7.md:272]:
```suggestion
- clicking on the input adornment opens the Picker
```

**Review by noraleonte — APPROVED** [review]
Great improvement 🚀 🎉 

---
About the clearable behavior on mobile, I think it makes sense to keep it consistent with the standalone field: 
If the field is `clearable` and the `value` is set => show clearing button. Otherwise, don't show. 

On desktop we display the clearable button on hover, but that's not an option on mobile so we should always display I think.  We can open a conversation about alternatives separately, because I do see drawbacks of this depending on the width of the field for instance. But for this PR specifically, I think the clearing behavior on mobile is fine 👌

File: docs/data/date-pickers/custom-opening-button/custom-opening-button.md (hunk 6 above)
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply docs/data/date-pickers/custom-opening-button/custom-opening-button.md:44]: OK for me :+1:

**Comment by flaviendelangle** [comment]
> We still have the flickering and focus regressions present in this PR. 🙈

I was missing a `preventDefault()`.
The flickering is gone for me.
For the focus, I would love a double check though.

**Review by LukasTy — APPROVED** [review]
Awesome work! 🎉 💯 💙
