### PR TITLE
[DataGrid] Support advanced server-side pagination use cases

### LINKED ISSUE #409: [DataGrid] Server-side pagination for an unknown number of items
To enable server-side pagination for an unknown number of items in the TablePagination component, the value of the count prop must be -1. When the value of the DataGrid component's rowCount prop is set to -1, the server-side pagination functionality is not complete.

## Current Behavior 😯

"Total rows: -1" is rendered and the onPageChange function is not triggered.

## Expected Behavior 🤔

"Total rows: -1" should not render and the onPageChange function should trigger until there are no more pages to get from the server.

## Steps to Reproduce 🕹

Steps:

1. Go to [this CodeSandbox](https://codesandbox.io/s/1gjqg?file=/demo.js) which demos [this material-ui example](https://material-ui.com/components/data-grid/pagination/#server-side-pagination)
2. Navigate to demo.js
3. Change `rowCount={100}` to `rowCount={-1}` on line 55

## Context 🔦

Server-side pagination

## Benchmark

- https://www.ag-grid.com/javascript-grid/server-side-model-pagination/#server-pagination

### LINKED ISSUE #2843: [DataGrid] - Option to Disable Pagination while server request is loading
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When i am using server side pagination my goal is for a user to be able paginate and get the next page. 

We are using a graphQL API, and cursor based pagination. For pagination to work as intended, we need the request for the current page to complete, so we can get the cursors for the next page. As a result, we'd like the ability to disable the pagination buttons while content loads.

The inability to do this allows a user to hit next page any amount of times, and still request content based off the next page from the content currently being displayed.

An easy way to replicate this would be to hook up a table to server data with cursor based pagination, then throttle your speed. Then do the following
1. Let the table load 
2. Hit next page 5 times
3. Each request will be using the end cursor from page 1
4. Page six will load with the results from page 2

### Examples 🌈

_No response_

### Motivation 🔦

I am trying to use the datagrid in a way where server side pagination using cursors provides us the ability to go to the next page and reliably get the next results.

### Order ID 💳 (optional)

_No response_

### LINKED ISSUE #4323: [question] Are there plans to implement a DataGridPro footer that doesn't require a finite rowCount
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Say I have no way of knowing the total row count that the server has, thus not being able to provide a definite rowCount, is there a way to display the total rows differently? Similar to a "see more" or have the ">" button clickable until no records can be fetched from the server?

### Examples 🌈

image

### Motivation 🔦

I have a use case where the exact total count of data/rows is not known--i.e., DynamoDB table without scanning the whole table.

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by MBilalShafi**
Extracted from #12317
Resolves #409 
Partially implements #2843 
Fixes #4323 

Preview: https://deploy-preview-12474--material-ui-x.netlify.app/x/react-data-grid/pagination/#index-based-pagination

## Changelog

- Support for unknown and estimated row count in server-side pagination is added

### CODE REVIEW

File: packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx [hunk 1]
```diff
@@ -842,6 +853,13 @@ DataGridPremiumRaw.propTypes = {
    * @default false
    */
   pagination: PropTypes.bool,
+  /**
+   * The extra information about the pagination state of the Data Grid.
+   * Only applicable with `paginationMode="server"`.
+   */
+  paginationMeta: PropTypes.shape({
+    hasNextPage: PropTypes.bool,
```
Comment (MBilalShafi) [inline packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx:861]: Another interface could be to have `props.hasNextPage` callback, the reason I chose a meta object:
1. I am not exactly sure what params should be passed to this callback, paginationModel? (would be the same as onPaginationModelChange), rows? (could easily be fetched?), what else?
1. When we support cursor pagination internally in the data source, we'll have to store more values to it, like nextCursor, previousCursor, hasPreviousPage, etc.
1. All these values seem to be interrelated and should be invoked at the same times, for example, if hasNextPage updates, it's likely that nextCursor also updates (and also the others). So to avoid splitting them now and combining them later like we did with (page, pageSize) -> paginationModel, it seems more reasonable to have a structure like this from the start.

Opinions are welcome

Comment (flaviendelangle) [reply packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx:861]: If it is only for `paginationMode="server"`, you could consider giving it a name that provides this information (like `serverPaginationMeta`)

Comment (MBilalShafi) [reply packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx:861]: That could be better, yes. Though I wanted to make `paginationMeta` a second argument of the `onPaginationModelChange` call so that if some cursor information is stored there, the user can access it without using an additional selector, for that purpose I was more inclined not to make the naming more generic and not bound to the server-side. I am not sure yet, but I have a feeling there might be more general use cases where it could be useful. 🤷

**Review by romgrk — APPROVED** [review]
LGTM but I don't have much to comment, I haven't worked with the paginatinon code at all yet.

File: docs/data/data-grid/pagination/pagination.md [hunk 2]
```diff
@@ -122,7 +150,96 @@ React.useEffect(() => {
...
 
-### Cursor implementation
+#### Unknown row count
+
+When the row count is not available, you can use the following steps to enable server-side pagination:
+
+- Set the prop `paginationMode` to `server`
+- Set the `rowCount` as `-1` using one of the above mentioned ways to let the Grid know that the row count is not available
+- Since the `rowCount` is unknown, the Grid needs to know whether more records are available on the server. Pass the `paginationMeta.hasNextPage` boolean property to indicate whether more records are available.
+- Use the `onPaginationModelChange` prop to react to the `paginationModel` changes
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/pagination.md:160]: These sections are a bit hard to read, how about we organize everything into a table, and keep shorter descriptions for each of the scenario?
If I understand this correctly, the table should look like this:

|                              | Known row count | Unknown row count | Estimated row count |
| :--------------------------- | :-------------- | :---------------- | :------------------ |
| `rowCount`                   | `number`        | `-1`              | `-1`                |
| `paginationMeta.hasNextPage` | —               | `boolean`         | `boolean`           |
| `estimatedRowCount`          | —               | —                 | `number`            |

<details>
<summary>Raw markdown</summary>

```
|                              | Known row count | Unknown row count | Estimated row count |
| :--------------------------- | :-------------- | :---------------- | :------------------ |
| `rowCount`                   | `number`        | `-1`              | `-1`                |
| `paginationMeta.hasNextPage` | —               | `boolean`         | `boolean`           |
| `estimatedRowCount`          | —               | —                 | `number`            |
```
</details>

What do you think?

File: docs/data/data-grid/pagination/pagination.md [hunk 3]
```diff
@@ -122,7 +150,96 @@ React.useEffect(() => {
...
+
+The `hasNextPage` must not be set to `false` until there are _actually_ no records left to fetch, because when `hasNextPage` becomes `false`, the Grid considers this as the last page and tries to set the `rowCount` value to a finite value.
+
+Relying on this behavior of the Grid should be the last resort though, the preferred way is to set the `rowCount` to the actual number of rows fetched from the server as soon as the information is available since the Grid cannot guess if the rows in the last page are less than the page size, and the incorrect number might be displayed in the pagination UI.
+
+For example the if the row count is `15` and the page size is `10`, on the last page, when `hasNextPage` becomes false the Grid will set the row count to be `page (2) * pageSize (10) = (20)` showing `10-20 of 20` which is incorrect, the correct value should be `10-15 of 15`.
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/pagination.md:166]: Do we really need this warning?
I think this is acceptable behavior when the row count is unknown, we don't have to discourage the users to do this if this is their use case.

One thing to clarify here – the incorrect number might appear only while fetching of the last page, and once the page is fetched – we update it with the actual number of rows (all of them have been fetched). Is this correct?

File: docs/data/data-grid/pagination/pagination.md (hunk 2 above)
Comment (cherniavskii) [reply docs/data/data-grid/pagination/pagination.md:160]: The `paginationMode` and `onPaginationModelChange` can be covered once in the "Index-based pagination" section too.

File: packages/x-data-grid-generator/src/hooks/useQuery.ts [hunk 4]
```diff
@@ -146,9 +146,11 @@ export const loadServerRows = (
     firstRowIndex = page * pageSize;
     lastRowIndex = (page + 1) * pageSize;
   }
+  const hasNextPage = lastRowIndex < filteredRows.length;
```
Comment (cherniavskii) [inline packages/x-data-grid-generator/src/hooks/useQuery.ts:149]:
```suggestion
  const hasNextPage = lastRowIndex < filteredRows.length - 1;
```
Since index is 0-based.

File: packages/x-data-grid/src/models/props/DataGridProps.ts [hunk 5]
```diff
@@ -411,8 +411,15 @@ export interface DataGridPropsWithoutDefaultValue<R extends GridValidRowModel =
   /**
    * Set the total number of rows, if it is different from the length of the value `rows` prop.
    * If some rows have children (for instance in the tree data), this number represents the amount of top level rows.
+   * Works only with the server-side data. Ignored when `paginationMode === 'client'`
    */
   rowCount?: number;
+  /**
+   * Use if the actual rowCount is not known upfront, but an estimation is available.
+   * If some rows have children (for instance in the tree data), this number represents the amount of top level rows.
+   * Applicable only with the server-side data and when `rowCount="-1"`
```
Comment (cherniavskii) [inline packages/x-data-grid/src/models/props/DataGridProps.ts:420]:
```suggestion
   * Applicable only with `paginationMode="server"` and when `rowCount="-1"`
```

File: packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx [hunk 6]
```diff
@@ -716,6 +722,11 @@ DataGridPremiumRaw.propTypes = {
    * @param {GridCallbackDetails} details Additional details for this callback.
    */
   onMenuOpen: PropTypes.func,
+  /**
+   * Callback fired when the pagination meta has changed.
+   * @param {GridPaginationMeta} paginationMeta Updated pagination meta.
+   */
+  onPaginationMetaChange: PropTypes.func,
```
Comment (cherniavskii) [inline packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx:729]: Not sure I understand this one, can pagination meta be changed by the data grid?

File: packages/x-data-grid/src/models/props/DataGridProps.ts [hunk 7]
```diff
@@ -411,8 +411,15 @@ export interface DataGridPropsWithoutDefaultValue<R extends GridValidRowModel =
   /**
    * Set the total number of rows, if it is different from the length of the value `rows` prop.
    * If some rows have children (for instance in the tree data), this number represents the amount of top level rows.
+   * Works only with the server-side data. Ignored when `paginationMode === 'client'`
```
Comment (cherniavskii) [inline packages/x-data-grid/src/models/props/DataGridProps.ts:414]:
```suggestion
   * Only works with `paginationMode="server"`, ignored when `paginationMode="client"`.
```

File: packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx (hunk 6 above)
Comment (MBilalShafi) [reply packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx:729]: The idea is to update the `paginationMeta` from the `dataSource` internally to handle index and cursor pagination with the three possibilities of the row count (known, unknown, and estimated)
So, not right now, but yes the Grid is likely to update the pagination meta internally when fetching data using the `dataSource` and store hasNextPage, nextCursor, and other information based on the currently active feature.
So the users could subscribe to `onPaginationMetaChange` if they want to get in sync with the internal state.

Does that make sense?

File: docs/data/data-grid/pagination/pagination.md (hunk 2 above)
Comment (MBilalShafi) [reply docs/data/data-grid/pagination/pagination.md:160]: I agree it's a bit cluttered, thanks for the suggestions. I'll try to accommodate them.

File: packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx (hunk 6 above)
Comment (cherniavskii) [reply packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx:729]: Ah, got it. So the idea would be for the data source to provide the pagination meta, then the grid will update the paginationMeta state and call `onPaginationMetaChange`.
Makes sense to me 👍🏻

File: docs/data/data-grid/pagination/pagination.md [hunk 8]
```diff
@@ -120,14 +160,84 @@ React.useEffect(() => {
...
+
+const paginationMeta = React.useMemo(() => {
+  if (
+    hasNextPage !== undefined &&
+    paginationMetaRef.current?.hasNextPage !== hasNextPage
+  ) {
+    paginationMetaRef.current = { hasNextPage };
+  }
+  return paginationMetaRef.current;
+}, [hasNextPage]);
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/pagination.md:186]: This approach looks better than `useEffect` in the "Known row count" section 👍🏻
Would you mind updating it there?

Comment (MBilalShafi) [reply docs/data/data-grid/pagination/pagination.md:186]: Not at all, seems a nice idea 👍

File: packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts [hunk 9]
```diff
@@ -109,6 +119,49 @@ export const useGridRowCount = (
...
+   */
+  const handlePaginationMetaChange = React.useCallback(
+    (meta: GridPaginationState['meta']) => {
+      if (props.paginationMode === 'client') {
+        return;
+      }
+
+      if (!meta.hasNextPage && rowCountState === -1) {
+        apiRef.current.setRowCount(
+          paginationModel.pageSize * paginationModel.page + paginationModel.pageSize,
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts]:
```suggestion
          paginationModel.pageSize * paginationModel.page + gridRowCountSelector(apiRef),
```

How about doing this instead?
Then users won't have to set rowCount on the last page: https://github.com/mui/mui-x/pull/12474/files#diff-d5340f1a8a49834c73bed351907ef06eceda3faba1ca045fc35da9ca17a41932R51-R56

File: docs/data/data-grid/pagination/pagination.md (hunk 3 above)
Comment (MBilalShafi) [reply docs/data/data-grid/pagination/pagination.md]: > the incorrect number might appear only while fetching of the last page, and once the page is fetched – we update it with the actual number of rows (all of them have been fetched). Is this correct?

@cherniavskii Now, yes (done in https://github.com/mui/mui-x/pull/12474/commits/4f8f45dff590622d1284677a46c941c9cb230c5d), thanks for pointing it out.

Previously I was aligned to off-load this responsibility to the user (that they explicitly have to set the updated `rowCount` prop especially if the last page size on server is less that `paginationModel.pageSIze`), because loading could be set to `false` in one render cycle while rows might be updated in multiple render cycles or at a later point in time depending on how the user is fetching them, so it didn't seem safe to make it a default behavior.

However, on a rethought, it seemed fine to me (as well as a better DX) since it could be opted out by controlling the `rowCount` prop.

Removed the warning as well, since the behavior is pretty much self-explanatory to me now. Let me know if you feel like adding a couple of line may still help.

File: packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts (hunk 9 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts]: Oh, I was too late with this suggestion 😅

File: packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts [hunk 10]
```diff
@@ -109,6 +120,33 @@ export const useGridRowCount = (
...
+  const handlePaginationModelChange = React.useCallback(
+    (model: GridPaginationState['paginationModel']) => {
+      if (props.paginationMode === 'client' || !previousPageSize.current) {
+        return;
+      }
+      if (model.pageSize !== previousPageSize.current) {
+        // The page size has changed
+        previousPageSize.current = model.pageSize;
+        if (rowCountState !== -1) {
+          // Row count unknown and page size changed, reset the page
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts:135]: The comment doesn't seem to match the condition

File: docs/data/data-grid/pagination/pagination.md (hunk 2 above)
Comment (MBilalShafi) [reply docs/data/data-grid/pagination/pagination.md]: @cherniavskii I did some revamping thanks to your suggestions, however, it still doesn't feel super clear readability-wise. 😞 

I am thinking of dividing this page into sub-pages. For now:

- Pagination
  - Overview
  - Server-side pagination
  - Recipes
  
The recipes section could be started with this example: https://mui.com/x/react-data-grid/pagination/#custom-pagination-ui, we could add more later.

Would it be an overkill though? Wdyt?

File: packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts (hunk 9 above)
Comment (MBilalShafi) [reply packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts]: Unfortunately, this may not work in some scenarios since the handler could run before (when the meta updates), while the rows would update later, also we need to consider the top-level rows here, to be able to work fine with nested data.

I removed this handler and moved the logic to the `useEffect` to react to the rows update better.

Let me know how you feel about it.

File: packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts [hunk 11]
```diff
@@ -123,8 +161,35 @@ export const useGridRowCount = (
...
+      isLastPage &&
+      (rowCountState === -1 || rowCountState % paginationModel.pageSize === 0) &&
+      visibleTopLevelRowCount < paginationModel.pageSize
+    ) {
+      // Actual count of the rows is less than the page size, reflect the value
+      apiRef.current.setRowCount(
+        (rowCountState !== -1
+          ? rowCountState - paginationModel.pageSize
+          : paginationModel.pageSize * paginationModel.page) + visibleTopLevelRowCount,
+      );
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts:184]: Shouldn't this be simpler?
```suggestion
    if (isLastPage && rowCountState === -1) {
      apiRef.current.setRowCount(paginationModel.pageSize * paginationModel.page) + visibleTopLevelRowCount);
```

And maybe keeping `handlePaginationMetaChange` would make more sense?
See https://github.com/mui/mui-x/pull/12474#discussion_r1553347579

Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts:184]: After reading https://github.com/mui/mui-x/pull/12474#discussion_r1553368477, I understand that `handlePaginationMetaChange` won't work.
Perhaps add a separate `useEffect` to handle unknown row count specifically?

```ts
  React.useEffect(() => {
    if (props.paginationMode === 'client') {
      apiRef.current.setRowCount(visibleTopLevelRowCount);
    } else if (props.rowCount != null) {
      apiRef.current.setRowCount(props.rowCount);
    }
  }, [apiRef, visibleTopLevelRowCount, props.paginationMode, props.rowCount]);
  
  const isLastPage = paginationMeta.hasNextPage === false;
  React.useEffect(() => {
    if (isLastPage && rowCountState === -1) {
      apiRef.current.setRowCount(paginationModel.pageSize * paginationModel.page) + visibleTopLevelRowCount);
    }
  }, [apiRef, isLastPage, rowCountState, paginationModel, visibleTopLevelRowCount])
```

Comment (MBilalShafi) [reply packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts]: Yeah, let's do it. I didn't do it previously because many dependencies were common, but this does seem better. Thanks!

File: docs/data/data-grid/pagination/CursorPaginationGrid.js [hunk 12]
```diff
@@ -37,38 +48,94 @@ export default function CursorPaginationGrid() {
...
-  }, [paginationModel.page, isLoading, pageInfo?.nextCursor]);
+  }, [paginationModel.page, isLoading, nextCursor]);
 
   // Some API clients return undefined while loading
   // Following lines are here to prevent `rowCountState` from being undefined during the loading
-  const [rowCountState, setRowCountState] = React.useState(
-    pageInfo?.totalRowCount || 0,
-  );
+  const [rowCountState, setRowCountState] = React.useState(totalRowCount || 0);
   React.useEffect(() => {
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/CursorPaginationGrid.js:74]: Use `React.useMemo` instead, similar to https://github.com/mui/mui-x/pull/12474#discussion_r1553170263?

File: docs/data/data-grid/pagination/ServerPaginationGridEstimated.tsx [hunk 13]
```diff
@@ -0,0 +1,66 @@
...
+  React.useEffect(() => {
+    if (hasNextPage !== undefined) {
+      setPaginationMeta((prev) => {
+        if (prev.hasNextPage !== hasNextPage) {
+          return { ...prev, hasNextPage };
+        }
+        return prev;
+      });
+    }
+  }, [hasNextPage]);
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/ServerPaginationGridEstimated.tsx:37]:
```suggestion
  const paginationMetaRef = React.useRef<GridPaginationMeta>({});
  // Memoize to avoid flickering when the `hasNextPage` is `undefined` during refetch
  const paginationMeta = React.useMemo(() => {
    if (
      hasNextPage !== undefined &&
      paginationMetaRef.current?.hasNextPage !== hasNextPage
    ) {
      paginationMetaRef.current = { hasNextPage };
    }
    return paginationMetaRef.current;
  }, [hasNextPage]);
```

File: docs/data/data-grid/pagination/ServerPaginationGridEstimated.tsx [hunk 14]
```diff
@@ -0,0 +1,66 @@
...
+          rows={rows}
+          {...data}
+          initialState={{ ...data.initialState, pagination: { rowCount: -1 } }}
+          estimatedRowCount={100}
+          paginationMeta={paginationMeta}
+          loading={isLoading}
+          pageSizeOptions={[10, 25, 50, 100]}
+          paginationModel={paginationModel}
+          paginationMode="server"
+          onPaginationModelChange={handlePaginationModelChange}
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/ServerPaginationGridEstimated.tsx:61]:
```suggestion

  return (
    <div style={{ width: '100%' }}>
      <Button onClick={() => apiRef.current.setRowCount(1000)}>Set Row Count</Button>
      <div style={{ height: 400 }}>
        <DataGrid
          apiRef={apiRef}
          rows={rows}
          {...data}
          initialState={{ ...data.initialState, pagination: { rowCount: -1 } }}
          estimatedRowCount={100}
          paginationMeta={paginationMeta}
          loading={isLoading}
          pageSizeOptions={[10, 25, 50, 100]}
          paginationModel={paginationModel}
          paginationMode="server"
          onPaginationModelChange={setPaginationModel}
```

File: docs/data/data-grid/pagination/ServerPaginationGridNoRowCount.tsx [hunk 15]
```diff
@@ -0,0 +1,74 @@
...
+    },
+    [],
+  );
+
+  React.useEffect(() => {
+    if (paginationMeta?.hasNextPage === false) {
+      // On last page set the row count to the number of rows
+      apiRef.current.setRowCount(rowLength);
+    }
+  }, [apiRef, paginationMeta]);
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/ServerPaginationGridNoRowCount.tsx:56]: This can be removed now?

File: docs/data/data-grid/pagination/ServerPaginationGridNoRowCount.tsx [hunk 16]
```diff
@@ -0,0 +1,74 @@
...
+    }
+    return paginationMetaRef.current;
+  }, [hasNextPage]);
+
+  const handlePaginationModelChange = React.useCallback(
+    (newPaginationModel: GridPaginationModel) => {
+      setPaginationModel(newPaginationModel);
+    },
+    [],
+  );
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/ServerPaginationGridNoRowCount.tsx:49]: No need for this, we can pass `setPaginationModel` to `onPaginationModelChange `

File: packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts [hunk 17]
```diff
@@ -110,21 +118,48 @@ export const useGridRowCount = (
...
+      if (model.pageSize !== previousPageSize.current) {
+        previousPageSize.current = model.pageSize;
+        if (rowCountState === -1) {
+          // Row count unknown and page size changed, reset the page
+          apiRef.current.setPage(0);
+          return;
+        }
+        const lastPage = Math.max(0, Math.ceil(rowCountState / model.pageSize) - 1);
+        if (model.page > lastPage) {
+          apiRef.current.setPage(lastPage);
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts:137]: Why do we need to do this?

File: docs/data/data-grid/pagination/ServerPaginationGridEstimated.tsx (hunk 14 above)
Comment (cherniavskii) [reply docs/data/data-grid/pagination/ServerPaginationGridEstimated.tsx:61]: The diff is hard to read, my point was to do this: `onPaginationModelChange={setPaginationModel}`

Comment (MBilalShafi) [reply docs/data/data-grid/pagination/ServerPaginationGridEstimated.tsx:61]: Yup got it

File: docs/data/data-grid/pagination/CursorPaginationGrid.js (hunk 12 above)
Comment (MBilalShafi) [reply docs/data/data-grid/pagination/CursorPaginationGrid.js:74]: I'm afraid switching from state to memoized variable here might not give the best results.
1. When controlling the `rowCount`: It will block the default behavior of the Grid i.e. setting the `rowCount` to a finite ( > 0 ) number when `hasNextPage` becomes `false` (as we can't pass `onRowCountChange`)
2. When initializing the `rowCount`: It will make the switching between `known`, `unknown`, and `estimated` row counts not work as expected as the grid will not react to the updation of `initialState.pagination.rowCount`
Wdyt?

File: packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts (hunk 9 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts]: Looks great!

File: docs/data/data-grid/pagination/pagination.md [hunk 18]
```diff
@@ -94,40 +94,155 @@ const [paginationModel, setPaginationModel] = React.useState({
...
+
+|                              | Known row count | Unknown row count | Estimated row count |
+| :--------------------------- | :-------------- | :---------------- | :------------------ |
+| `rowCount`                   | `number`        | `-1`              | `-1`                |
+| `paginationMeta.hasNextPage` | —               | `boolean`         | `boolean`           |
+| `estimatedRowCount`          | —               | —                 | `number`            |
+
+The following examples demonstrate each of these scenarios:
+
+#### Known row count
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/pagination.md:147]: Could we keep the pagination buttons active while loading, as it currently is on `master`?
https://mui.com/x/react-data-grid/pagination/#basic-implementation
This allows switching pages faster if necessary.

File: docs/data/data-grid/pagination/pagination.md [hunk 19]
```diff
@@ -94,40 +94,155 @@ const [paginationModel, setPaginationModel] = React.useState({
...
+There could be two possibilities after providing the initial props (as mentioned in the table above):
+
+1. The actual row count is fetched from the server lazily and provided to the Grid using the `rowCount` prop. The `estimatedRowCount` prop will be ignored once the `rowCount` prop is set to a positive value.
+2. The user has already reached the estimated last page and the actual row count is still not available, in that case, the Grid could take the help of the `hasNextPage='false'` to know that the last page is fetched and try to set a value like in the unknown row count use case.
+
+The following example demonstrates the use of the `estimatedRowCount` and `hasNextPage` props to handle the case when the actual row count is not initially available. The actual row count is `1000` but the Grid is initially provided with an estimated row count of `100`.
+
+The Grid keeps fetching the next page until `hasNextPage` is `false` or the actual row count is provided to the Grid lazily, you can do that by clicking the "Set Row Count" button.
+
+{{"demo": "ServerPaginationGridEstimated.js", "bg": "inline"}}
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/pagination.md:208]: This might be out of this PR's scope, but did you consider custom pagination components in this scenario?
E.g. the one with individual page buttons in https://mui.com/x/react-data-grid/components/#pagination

In this particular example, it looks wrong: https://codesandbox.io/p/sandbox/inspiring-cherry-svvzh6



- It shows only page 1 (although `estimatedRowCount` could be utilized here)
- And more importantly, the arrow buttons are disabled. This seems to be caused by https://github.com/mui/mui-x/pull/12474/files?w=1#diff-79d72ca24d1e0278032ce56430db49ef25dc59fd363d0d063912654cddc850ceR14

File: packages/x-data-grid/src/hooks/features/pagination/gridPaginationUtils.ts [hunk 20]
```diff
@@ -1,27 +1,22 @@
...
 export const defaultPageSize = (autoPageSize: boolean) => (autoPageSize ? 0 : 100);
 
-export const getPageCount = (rowCount: number, pageSize: number): number => {
+export const getPageCount = (rowCount: number, pageSize: number, page: number): number => {
   if (pageSize > 0 && rowCount > 0) {
     return Math.ceil(rowCount / pageSize);
   }
 
+  if (rowCount === -1) {
+    return page + 1;
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/pagination/gridPaginationUtils.ts:14]: Since `page` is 0-based, should we assume there's always one more page after the current one when `rowCount === -1`?

```suggestion
    return page + 1 + 1;
```

File: docs/data/data-grid/pagination/pagination.md [hunk 21]
```diff
@@ -94,40 +94,155 @@ const [paginationModel, setPaginationModel] = React.useState({
...
+  }
+  return paginationMetaRef.current;
+}, [hasNextPage]);
+```
+
+{{"demo": "ServerPaginationGridNoRowCount.js", "bg": "inline"}}
+
+#### Estimated row count
+
+There could be possibilities when the accurate row count is not initially available for many reasons such as:
```
[the remark this answers is not in the document]
Comment (MBilalShafi) [reply docs/data/data-grid/pagination/pagination.md:197]: > Would it be technically correct to say that the "Estimated row count" case is identical to the "Unknown row count", with the difference that the estimatedRowCount is used to show more detailed info in the pagination footer?

Yes!

I wanted to explain the rationale for the use case as it's kind of an edge case and not many people face this problem with the BE data fetching. But yeah, it's a bit wordy. I tried to reduce it based on your suggestions. Lemme know hyf.

File: docs/data/data-grid/pagination/CursorPaginationGrid.js (hunk 12 above)
Comment (cherniavskii) [reply docs/data/data-grid/pagination/CursorPaginationGrid.js:74]: Makes sense to me 👍🏻

File: docs/data/data-grid/pagination/pagination.md (hunk 21 above)
[the remark this answers is not in the document]
Comment (cherniavskii) [reply docs/data/data-grid/pagination/pagination.md]: Nice!

File: docs/data/data-grid/pagination/pagination.md (hunk 18 above)
Comment (cherniavskii) [reply docs/data/data-grid/pagination/pagination.md:147]: Thanks for linking to that issue, I wasn't aware of it.

> I am trying to use the datagrid in a way where server side pagination using cursors provides us the ability to go to the next page and reliably get the next results.

From what I can observe in https://deploy-preview-12474--material-ui-x.netlify.app/x/react-data-grid/pagination/#cursor-based-pagination, even though the pagination buttons aren't disabled while loading, I can't skip pages by clicking while loading 👍🏻

File: docs/data/data-grid/pagination/pagination.md (hunk 19 above)
Comment (cherniavskii) [reply docs/data/data-grid/pagination/pagination.md:209]: Here's the updated demo: https://codesandbox.io/p/sandbox/affectionate-violet-qfjdgw?file=%2Fsrc%2FDemo.tsx

File: packages/x-data-grid/src/components/GridPagination.tsx [hunk 22]
```diff
@@ -28,6 +30,25 @@ const GridPaginationRoot = styled(TablePagination)(({ theme }) => ({
...
+): TablePaginationProps['labelDisplayedRows'] => {
+  return ({ from, to, count, page }: LabelDisplayedRowsArgs) =>
+    labelDisplayedRows({ from, to, count, page, estimated });
+};
+
+const defaultLabelDisplayedRows: WrappedLabelDisplayedRows = ({ from, to, count, estimated }) => {
+  if (!estimated) {
+    return `${from}–${to} of ${count !== -1 ? count : `more than ${to}`}`;
+  }
+  return `${from}–${to} of ${count !== -1 ? count : `more than ${estimated > to ? estimated : to}`}`;
```
Comment (cherniavskii) [inline packages/x-data-grid/src/components/GridPagination.tsx:49]: Would it work if instead of wrapping we pass different `to` value depending on situation?
`to: estimated > to ? estimated : to `

File: packages/x-data-grid/src/components/GridPagination.tsx [hunk 23]
```diff
@@ -28,6 +30,25 @@ const GridPaginationRoot = styled(TablePagination)(({ theme }) => ({
...
+  labelDisplayedRows: WrappedLabelDisplayedRows,
+  estimated?: number,
+): TablePaginationProps['labelDisplayedRows'] => {
+  return ({ from, to, count, page }: LabelDisplayedRowsArgs) =>
+    labelDisplayedRows({ from, to, count, page, estimated });
+};
+
+const defaultLabelDisplayedRows: WrappedLabelDisplayedRows = ({ from, to, count, estimated }) => {
+  if (!estimated) {
+    return `${from}–${to} of ${count !== -1 ? count : `more than ${to}`}`;
```
Comment (flaviendelangle) [inline packages/x-data-grid/src/components/GridPagination.tsx:47]: Shouldn't this sentence be in the localization?
Even if people can override it, that way people just have to pass there usual locale (which they probably already do) and they have a translated app.

File: packages/x-data-grid/src/components/GridPagination.tsx (hunk 22 above)
Comment (MBilalShafi) [reply packages/x-data-grid/src/components/GridPagination.tsx:49]: To achieve something like this, we need at least 3 values, `from`, `to`, and `estimated`, since all of them are different.
image

Does it make sense?

File: packages/x-data-grid/src/components/GridPagination.tsx (hunk 23 above)
Comment (MBilalShafi) [reply packages/x-data-grid/src/components/GridPagination.tsx:47]: Yes, ideally `estimated` should be supported by the `@mui/material/TablePagination` (since that's where its localization is coming from). It would also mean a minimum peer dependency bump apart from adding the support in that component.
Until feasible, we can provide this workaround to our users to achieve the localization for the estimated row count use case. See the info callout just above [this](https://deploy-preview-12474--material-ui-x.netlify.app/x/react-data-grid/pagination/#cursor-based-pagination) docs section.

Or your suggestion is more about moving localization for this function (`labelDisplayedRows`) to the Grid localization already?

Comment (flaviendelangle) [reply packages/x-data-grid/src/components/GridPagination.tsx:47]: I was thinking about the grid localization, but it's true that it could also belong to the `TablePagination` one...
IMHO if we plan to put it in `TablePagination`, then we could create the PR in the core repo to make sure that we have it for our next major.

File: packages/x-data-grid/src/components/GridPagination.tsx (hunk 22 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/components/GridPagination.tsx:49]: Oh, got it.
In that case how about we fork TablePagination translations and move them to our locales? Then we can adapt `labelDisplayedRows` to work with every locale.
What do you think?

File: docs/data/data-grid/pagination/pagination.md [hunk 24]
```diff
@@ -94,40 +94,158 @@ const [paginationModel, setPaginationModel] = React.useState({
...
+  }
+  return paginationMetaRef.current;
+}, [hasNextPage]);
+```
+
+:::
+
+#### Estimated row count
+
+Estimated row count could be considered a hybrid approach of known and unknown row count cases, where the actual row count is not initially available, but an estimated row count is available.
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/pagination.md:199]:
```suggestion
Estimated row count could be considered a hybrid approach that switches between the "Known row count" and "Unknown row count" use cases.
```

File: docs/data/data-grid/pagination/pagination.md [hunk 25]
```diff
@@ -94,40 +94,158 @@ const [paginationModel, setPaginationModel] = React.useState({
...
+
+Initially, when an `estimatedRowCount` is set and `rowCount='-1'`, the grid work identical to the "Unknown row count" use case, with the exception that the `estimatedRowCount` is used to show more detailed information in the pagination footer.
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/pagination.md:201]:
```suggestion
Initially, when an `estimatedRowCount` is set and `rowCount={-1}`, the Data Grid behaves as in the "Unknown row count" use case, but with the `estimatedRowCount` value shown in the pagination footer.
```

File: docs/data/data-grid/pagination/pagination.md [hunk 26]
```diff
@@ -94,40 +94,158 @@ const [paginationModel, setPaginationModel] = React.useState({
...
+
+Once the current row count exceeds the `estimatedRowCount`, the Grid will ignore the `estimatedRowCount` and completely work as the "Unknown row count" use case.
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/pagination.md:203]:
```suggestion
If the number of rows loaded exceeds the `estimatedRowCount`, the Data Grid ignores the `estimatedRowCount` and the behavior is identical to the "Unknown row count" use case.
```

File: docs/data/data-grid/pagination/pagination.md [hunk 27]
```diff
@@ -94,40 +94,158 @@ const [paginationModel, setPaginationModel] = React.useState({
...
+
+Meanwhile, if the `rowCount` is set to a valid value (either by updating the `rowCount` prop or setting `hasNextPage='false'`), the Grid will shift to the "Known row count" use case.
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/pagination.md:205]:
```suggestion
When the `hasNextPage` returns `false` or `rowCount` is set to a positive number, the Data Grid switches to the "Known row count" behavior.
```

File: docs/data/data-grid/pagination/pagination.md [hunk 28]
```diff
@@ -94,40 +94,158 @@ const [paginationModel, setPaginationModel] = React.useState({
...
+
+The following example demonstrates this scenario. The actual row count is `1000` but the Grid is initially provided with an estimated row count of `100`. You can set the `rowCount` value by hitting the "Set Row Count" button.
```
Comment (cherniavskii) [inline docs/data/data-grid/pagination/pagination.md:207]:
```suggestion
In the following example, the actual row count is `1000` but the Data Grid is initially provided with `estimatedRowCount={100}`.
You can set the `rowCount` to the actual row count by pressing the "Set Row Count" button.
```

**Review by cherniavskii — APPROVED** [review]
Final feedback on the docs mostly to follow our [Writing style guide](https://www.notion.so/mui-org/Writing-style-guide-2a957a4168a54d47b14bae026d06a24b#f481ccf46d8f44a7b51be0fa355679db) and make the docs more compact.

Thanks for working on it, it's a great addition to the server-side pagination! 🚀

File: packages/x-data-grid/src/components/GridPagination.tsx (hunk 22 above)
Comment (MBilalShafi) [reply packages/x-data-grid/src/components/GridPagination.tsx:49]: That's an interesting point.

I initially thought a bit further. i.e. forking the whole `TablePagination` component on our side instead of translations only.
But there were a few reasons why I decided not to go with that approach fat that point.

1. The proper fix would be to do that on the core side since the component belongs in the core. If we move it to the X side, we may miss future updates on the core side (same with the translations)
2. The estimated row count use case doesn't target a huge number of users, we did have a few requests for its support but I doubt that it will be demanded soon by many users, so is the effort even worth it?

I concluded that wrapping could be a nice middle ground. Meanwhile, we could add this functionality on the core side as Flavien [suggested](https://github.com/mui/mui-x/pull/12474#discussion_r1568962914), and when after a major release, we bump the peer dependency on the core we remove this workaround.

Another side of the coin is the material-less grid which we are working on. That makes the argument of completely moving the component (`TablePagination`) on the Grid side a bit stronger, but again there comes a discussion about the implementation of the material-less version since we haven't yet figured out how the isolation between material and material-less versions will work. CC @romgrk (Correct me if I am wrong)

Anyhow, if it looks OK to you, we can proceed with the current workaround for now and settle on something better later?

File: docs/data/data-grid/pagination/pagination.md [hunk 29]
```diff
@@ -94,40 +94,158 @@ const [paginationModel, setPaginationModel] = React.useState({
...
+- Use the `onPaginationModelChange` prop to react to the page changes and load the data from the server
+
+The server-side pagination can be further categorized into sub-types based on the availability of the total number of rows or `rowCount`.
+
+The Grid uses the `rowCount` to calculate the number of pages and to show the information about the current state of the pagination in the footer.
+You can provide the `rowCount` in one of the following ways:
+
+- Initialize - use `initialState.pagination.rowCount` prop to initialize the `rowCount`
+- Control - use the `rowCount` prop along with `onRowCountChange` to control the `rowCount` and reflect the changes when the row count is updated
+- Set using the `apiRef` - use the `apiRef.current.setRowCount` method to set the `rowCount` after the Grid is initialized
```
[the remark this answers is not in the document]
Comment (MBilalShafi) [reply docs/data/data-grid/pagination/pagination.md]: This [way](https://www.notion.so/mui-org/Writing-style-guide-2a957a4168a54d47b14bae026d06a24b?pvs=4#e6b1ebbe81fd48de92eea2c30b0d3d1d) of listing different radio items seemed a bit better looking, I added a similar. Let me know how you feel.

File: packages/x-data-grid/src/components/GridPagination.tsx (hunk 22 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/components/GridPagination.tsx:49]: > we could add this functionality on the core side as Flavien https://github.com/mui/mui-x/pull/12474#discussion_r1568962914, and when after a major release, we bump the peer dependency on the core we remove this workaround.

This sounds good to me. I'm not sure bumping the peer dependency on the core is a good idea though, since it would force users to upgrade even if they don't need this. Perhaps a better option would be showing a warning in the docs with the minimum supported version of `@mui/material` required for this to work.

Comment (flaviendelangle) [reply packages/x-data-grid/src/components/GridPagination.tsx:49]: > I'm not sure bumping the peer dependency on the core is a good idea though

My proposal is:

1. To implement something on X that do not require bumping the peer dep
2. To have the core support whatever we think is the best DX, if this best DX requires a change on the core
3. To bump the peer dep on the next major (we will probably need it for other topics anyway)
