### PR TITLE
[DataGrid] Fix theme `defaultProps` causing unwanted re-renders

### LINKED ISSUE #17128: [data grid] Theme `MuiDataGrid.defaultProps` makes all cells re-render
Hello team, we use premium data grid (Order #106061)

## Steps to reproduce

It seems that `theme.components.MuiDataGrid.defaultProps` makes cell re-render across all rows.

## Steps:

Repo: https://github.com/ik-southpole/mui-data-grid-default-props.git

1. Setup
```bash
git clone https://github.com/ik-southpole/mui-data-grid-default-props.git
cd mui-data-grid-default-props
npm i
npm run dev
```

2. Double click on any cell to edit
3. See all cells re-render
4. Go to `src/page.tsx`, remove `defaultProps` from `theme`.
5. Double click on any cell - only row cells are re-rendered.

## Problem:

All cells re-render causes performance issues for no reason.

https://github.com/user-attachments/assets/bd92caa0-2e21-424a-9518-316a8f3a53ca

### Current behavior

All cells render

### Expected behavior

Only row affected re-render

### Context

_No response_

### Your environment

```
  System:
    OS: macOS 15.1.1
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 11.2.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.14.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 134.0.6998.166
    Edge: Not Found
    Safari: 18.1.1
  npmPackages:
    @emotion/react: ^11.14.0 => 11.14.0 
    @emotion/styled: ^11.14.0 => 11.14.0 
    @mui/core-downloads-tracker:  6.4.8 
    @mui/material: ^6.4.8 => 6.4.8 
    @mui/private-theming:  6.4.8 
    @mui/styled-engine:  6.4.8 
    @mui/system:  6.4.8 
    @mui/types:  7.2.24 
    @mui/utils:  6.4.8 
    @mui/x-data-grid:  7.28.1 
    @mui/x-data-grid-premium: ^7.28.1 => 7.28.1 
    @mui/x-data-grid-pro:  7.28.1 
    @mui/x-internals:  7.28.0 
    @mui/x-license:  7.28.0 
    @types/react: ^19 => 19.0.12 
    react: ^19.0.0 => 19.0.0 
    react-dom: ^19.0.0 => 19.0.0 
    typescript: ^5 => 5.8.2 
```

**Search keywords**: MuiDataGrid defaultProps render

Order ID: 106061

### PR DESCRIPTION
**Pull request by KenanYusuf**
This PR is fixes #17128 using an alternate approach to https://github.com/mui/material-ui/pull/45943

### Before

All cells change value when entering edit mode.

https://codesandbox.io/p/sandbox/17490-before-76t4mt

https://github.com/user-attachments/assets/0004b2dd-efbd-4afb-b843-be8d93425d3e

### After

Only the selected cell changes value when entering edit mode.

https://codesandbox.io/p/sandbox/17490-after-ftlktq

https://github.com/user-attachments/assets/ce6c8472-97c0-4b7c-9440-cf1846ef5ad5

### CODE REVIEW

File: packages/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumProps.ts [hunk 1]
```diff
@@ -64,12 +65,11 @@ export const DATA_GRID_PREMIUM_PROPS_DEFAULT_VALUES: DataGridPremiumPropsWithDef
 const defaultSlots = DATA_GRID_PREMIUM_DEFAULT_SLOTS_COMPONENTS;
 
 export const useDataGridPremiumProps = (inProps: DataGridPremiumProps) => {
-  const themedProps =
-    // eslint-disable-next-line material-ui/mui-name-matches-component-name
-    useThemeProps({
```
Comment (KenanYusuf) [inline packages/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumProps.ts:69]: The returned value from `useThemeProps` is not memoized. See https://github.com/mui/material-ui/pull/45943

**Review by romgrk — APPROVED** [review]

**Review by MBilalShafi — APPROVED** [review]
