### PR TITLE
[DataGridPremium] Fix selection propagation issues with controlled state

### LINKED ISSUE #15619: [data grid] Using `rowSelectionPropagation` and `rowSelectionModel` at the same time cause a crash
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/sandbox/selectionpropagation-and-selectionmodel-issue-svqxrm
2. Wait a few seconds for the grid to crash

### Current behavior

Initially, while our data is loading, we provide an empty rows array to the Grid. As soon as the data is received and the final rows array is created and provided to the Grid, a crash occurs.

Providing the "isLoading" flag to the Grid does not prevent the issue from happening.

A workaround is to wait a render frame before providing the rowSelectionModel to the grid, after the final rows array has been provided to the Grid.

### Expected behavior

The grid should not crash.

### Context

We were trying to have both row grouping with row propagation and row model selection to allow the user to select rows and do operations on them with an action menu.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: rowSelectionPropagation rowSelectionModel row grouping
**Order ID**: 100223

### LINKED ISSUE #15753: [data grid] Bug with selection, row grouping and rowSelectionPropagation
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/sandbox/mystifying-panini-m4ghxj
2. wait 2 seconds after the table is loaded
3. Check checkbox of "James Cameron" in the group of "20th Century Fox"

### Current behavior

All the children of group "James Cameron" are selected, the group's checkbox is in the intermediate state.

### Expected behavior

Having
```
rowSelectionPropagation={{ parents: true, descendants: true }}
```
I would expect the checkbox of group "James Cameron" is selected, when all its children are (programmatically) selected. The docs says:
> Selecting all the filtered descendants of a parent selects the parent automatically

https://mui.com/x/react-data-grid/row-grouping/#automatic-parents-and-children-selection 

Deselecting and selecting one of the children makes the parent selected as expected.

### Context

Related to https://github.com/mui/mui-x/issues/15382

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
  Binaries:
    Node: 22.12.0 - /usr/local/bin/node
    npm: 10.9.0 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 131.0.6778.108
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/core-downloads-tracker:  6.1.6 
    @mui/icons-material: ^6.1.6 => 6.1.6 
    @mui/material: ^6.1.6 => 6.1.6 
    @mui/private-theming:  6.1.6 
    @mui/styled-engine:  6.1.6 
    @mui/system:  6.1.6 
    @mui/types:  7.2.19 
    @mui/utils:  6.1.6 
    @mui/x-charts: ^7.22.1 => 7.22.1 
    @mui/x-charts-vendor:  7.20.0 
    @mui/x-data-grid:  7.23.0 
    @mui/x-data-grid-generator:  7.23.0 
    @mui/x-data-grid-premium: ^7.23.0 => 7.23.0 
    @mui/x-data-grid-pro:  7.23.0 
    @mui/x-date-pickers:  7.22.1 
    @mui/x-date-pickers-pro: ^7.22.1 => 7.22.1 
    @mui/x-internals:  7.21.0 
    @mui/x-license:  7.23.0 
    @mui/x-tree-view: ^7.22.1 => 7.22.1 
    @types/react:  18.3.12 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 

```
</details>

**Search keywords**: rowSelectionPropagation datagrid row grouping
**Order ID**: 101072

### PR DESCRIPTION
**Pull request by MBilalShafi**
Fixes #15753
Fixes #15619

Controlled state is different from the regular `removeOutdatedSelection` that runs on filtering, sorting, etc. since we also want to propagate the changes of selected parents down their unselected descendants. `syncControlledState` handles that.

### CODE REVIEW

File: packages/x-data-grid/src/models/api/gridRowSelectionApi.ts [hunk 1]
```diff
@@ -33,6 +33,9 @@ export interface GridRowSelectionApi {
   /**
    * Updates the selected rows to be those passed to the `rowIds` argument.
    * Any row already selected will be unselected.
+   *
+   * ⚠️ Caution: `setRowSelectionModel` doesn't apply the selection propagation automatically.
```
Comment (arminmeh) [inline packages/x-data-grid/src/models/api/gridRowSelectionApi.ts:37]: would a better API be that there is an additional optional flag to say if you want to apply propagation or not?

by default, it can follow the props value and with the flag you can override that for a specific scenario.
internally it can use current `getPropagatedRowSelectionModel` to fill in the missing parts.

File: packages/x-data-grid/src/models/api/gridRowSelectionApi.ts [hunk 2]
```diff
@@ -33,6 +33,9 @@ export interface GridRowSelectionApi {
...
+   * Pass model returned by API method `getPropagatedRowSelectionModel` instead to apply the selection propagation.
    * @param {readonly GridRowId[]} rowIds The row ids to select.
```
Comment (arminmeh) [inline packages/x-data-grid/src/models/api/gridRowSelectionApi.ts:39]:
```suggestion
   * @param {gridRowSelectionModel} rowSelectionModel The new row selection model
```

File: packages/x-data-grid/src/models/api/gridRowSelectionApi.ts [hunk 3]
```diff
@@ -33,6 +33,9 @@ export interface GridRowSelectionApi {
   /**
    * Updates the selected rows to be those passed to the `rowIds` argument.
    * Any row already selected will be unselected.
```
Comment (arminmeh) [inline packages/x-data-grid/src/models/api/gridRowSelectionApi.ts:35]: Sets the new row selection model.

File: packages/x-data-grid/src/models/api/gridRowSelectionApi.ts [hunk 4]
```diff
@@ -33,6 +33,9 @@ export interface GridRowSelectionApi {
...
+   *
+   * ⚠️ Caution: `setRowSelectionModel` doesn't apply the selection propagation automatically.
+   * Pass model returned by API method `getPropagatedRowSelectionModel` instead to apply the selection propagation.
    * @param {readonly GridRowId[]} rowIds The row ids to select.
    */
   setRowSelectionModel: (rowIds: GridRowSelectionModel) => void;
```
Comment (arminmeh) [inline packages/x-data-grid/src/models/api/gridRowSelectionApi.ts:41]:
```suggestion
  setRowSelectionModel: (rowSelectionModel: GridRowSelectionModel) => void;
```

Comment (MBilalShafi) [reply packages/x-data-grid/src/models/api/gridRowSelectionApi.ts]: Nice catch. 👍

File: packages/x-data-grid/src/models/api/gridRowSelectionApi.ts (hunk 1 above)
Comment (MBilalShafi) [reply packages/x-data-grid/src/models/api/gridRowSelectionApi.ts:36]: I initially considered this as well. However, I opted for the current approach based on the following reasoning:
1.	All state setter methods (`setXXXModel`) follow a consistent signature and are designed solely to update the state with the provided value. Introducing an additional parameter could break this convention.
2. There might be some potential use cases for `getPropagatedRowSelectionModel` in userland, similar to how [getFilterState](https://mui.com/x/react-data-grid/filtering-recipes/#calculating-filtered-rows-in-advance) is utilized.

However, I don’t have a strong preference on this. Do you find this reasoning compelling?

Comment (arminmeh) [reply packages/x-data-grid/src/models/api/gridRowSelectionApi.ts:36]: That makes sense. Let's leave it then as it is now

But the thing that I am missing now is some additional explanation in https://mui.com/x/react-data-grid/row-grouping/#automatic-parents-and-children-selection about this

Would you mind adding a section and/or demo covering this behavior?

Comment (MBilalShafi) [reply packages/x-data-grid/src/models/api/gridRowSelectionApi.ts:36]: I didn’t explicitly add this information to the documentation for the following reasons:
1. This use case doesn’t seem very common in userland, and we should encourage the use of `selectRows` over `setRowSelectionModel` whenever possible.
2. There are already two ways for users to discover this:
   - The [API reference](https://deploy-preview-16810--material-ui-x.netlify.app/x/react-data-grid/row-selection/#apiref) in the documentation.
   - JSDoc annotations available directly in the IDE.

That said, this is based on my assumption, and I’m open to reconsidering. Do you think adding a dedicated section would provide significant value for some users?

Comment (MBilalShafi) [reply packages/x-data-grid/src/models/api/gridRowSelectionApi.ts:36]: On a rethough, I guess a warning callout _does_ make sense in this case, I'll add it, thanks for the suggestion.

Comment (MBilalShafi) [reply packages/x-data-grid/src/models/api/gridRowSelectionApi.ts:36]: @arminmeh I added the warnings: https://github.com/mui/mui-x/pull/16810/commits/39b3a2619b147255b249170c2949abd2771dcd59

P.S: Since the list of warnings was getting larger and larger, I combined them into one, lmk how it feels. 😄

File: docs/data/data-grid/row-grouping/row-grouping.md [hunk 5]
```diff
@@ -346,12 +346,30 @@ The selected rows that do not pass the filtering criteria are automatically dese
...
+There are a few limitations to the row selection propagation:
 
-:::warning
-Row selection propagation is a client-side feature and is not supported with the [server-side data source](/x/react-data-grid/server-side-data/).
-:::
+- If `props.disableMultipleRowSelection` is set to `true`, the row selection propagation doesn't apply.
+
+- Row selection propagation is a client-side feature and is not supported with the [server-side data source](/x/react-data-grid/server-side-data/).
+
+- If you are using the state setter method `apiRef.current.setRowSelectionModel` you need to explicitly compute the selection model with the rows with propagation changes applied using `apiRef.current.getPropagatedRowSelectionModel` and pass it.
```
Comment (arminmeh) [inline docs/data/data-grid/row-grouping/row-grouping.md:355]:
```suggestion
- If you are using the state setter method `apiRef.current.setRowSelectionModel()` you need to explicitly compute the selection model with the rows with propagation changes applied using `apiRef.current.getPropagatedRowSelectionModel()` and pass it.
```

**Review by arminmeh — APPROVED** [review]

File: packages/x-data-grid/src/models/api/gridRowSelectionApi.ts (hunk 1 above)
Comment (philicious) [reply packages/x-data-grid/src/models/api/gridRowSelectionApi.ts:36]: affected user here: oh yes thanks for adding that info to doc!

**Comment by philicious** [comment]
@MBilalShafi thanks for the fix! I saw this in v8 beta, will it also be backported to v7?

**Comment by MBilalShafi** [comment]
@philicious Already ported to v7, should be available in v7.28.0.
