### PR TITLE
[data grid] Performance: DOM changes

### LINKED ISSUE #10570: [datagrid] Autosize Columns - Headers being cut off
### Steps to reproduce

Link to live example: [(MUI Docs Example)](https://mui.com/x/react-data-grid/column-dimensions/#system-ColumnAutosizing.js)

Steps:
1. Using autosize options:

```
    autosizeOnMount={true},
    autosizeOptions: { includeOutliers: true, includeHeaders: true }
```
2. On a mobile device or using dev tools mobile screen size - see the column header being cut off:

Screenshot 2023-10-03 at 8 03 21 PM

### Current behavior

The column headers are unreadable on mobile using autosizing

### Expected behavior

For the column headers to be readable

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.1
  Binaries:
    Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
    npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 122.0.6261.94
    Edge: Not Found
    Safari: 17.1
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.38 
    @mui/core-downloads-tracker:  5.15.12 
    @mui/icons-material: ^5.15.12 => 5.15.12 
    @mui/lab: 5.0.0-alpha.167 => 5.0.0-alpha.167 
    @mui/material: ^5.15.12 => 5.15.12 
    @mui/private-theming:  5.15.12 
    @mui/styled-engine:  5.15.11 
    @mui/styles: ^5.15.12 => 5.15.12 
    @mui/system: ^5.15.12 => 5.15.12 
    @mui/types:  7.2.13 
    @mui/utils: ^5.15.12 => 5.15.12 
    @mui/x-data-grid:  7.0.0-beta.5 
    @mui/x-data-grid-premium: 7.0.0-beta.5 => 7.0.0-beta.5 
    @mui/x-data-grid-pro:  7.0.0-beta.5 
    @mui/x-license:  7.0.0-beta.2 
    @mui/x-license-pro: 7.0.0-beta.0 => 7.0.0-beta.0 
    @types/react: ^18.2.63 => 18.2.63 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.3.3 => 5.3.3 
```
</details>

**Search keywords**: datagrid column autosizing
**Order ID**: 56883

### PR DESCRIPTION
**Pull request by romgrk**
Closes #10570 

Changes:
 - Remove the `.cell > .cellContent` DOM node. Fewer DOM nodes means a faster rendering.
 - Remove some styles to remove complexity & improve performance.
 - Rework autosizing to make it work with the new layout and make it more robust.

Before: https://deploy-preview-12012--material-ui-x.netlify.app/x/react-data-grid/#pro-plan
After: https://deploy-preview-12013--material-ui-x.netlify.app/x/react-data-grid/#pro-plan

Further help with #11866

### CODE REVIEW

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 1]
```diff
@@ -440,18 +450,21 @@ export const GridRootStyles = styled('div', {
 
     /* Cell styles */
     [`& .${c.cell}`]: {
-      display: 'flex',
-      alignItems: 'center',
```
Comment (romgrk) [inline packages/x-data-grid/src/components/containers/GridRootStyles.ts:444]: To make things work for string cells without a wrapper, cells need to not be `display: flex` by default (because it messes with `text-overflow: ellipsis`). This breaks the positioning of every column that relied on `align-items: center`, in other words most custom cells. To make the transition as painless as possible, here are the options we have:
 1. Export `gridClasses['cell--flex']` that restores those styles. Users can use `cellClassName: gridClasses['cell--flex']` in their column definition.
 1. Add something like a `display: 'flex'` option on the `GridColDef` itself to make even more convenient to restore the flex behavior
 2. Go the opposite way and make `display: flex` the default, and adjust the styles of every string column with one of the options above.

Comment (romgrk) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:444]: Went for `display: 'flex'`, it seemed like the most convenient option.

**Comment by romgrk** [comment]
There are a few argos changes, I feel like the remaining ones are acceptable. The one that's really apparent is that sibling cells of dynamic height cells have their content top-aligned rather than centered, which isn't necessarily wrong, more like different.

**Review by oliviertassinari — COMMENTED** [review]
Linked #3587 to make it easier to follow the history.

It would have probably been great to add a visual regression test in #3446. It seems to me that we are good on this PR, but it would have helped us move with more confidence.
Same thoughts with #3955, it's not clear that we have tests:

- Visual regression test for overflow: https://mui.com/x/react-data-grid/column-definition/#expand-cell-renderer
- renderCell with text and overflow: ?

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 1 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:444]: I don't love this breaking change, can we avoid it?
Did you consider using `::before`? https://codesandbox.io/p/sandbox/bitter-thunder-9w47cl?file=%2Findex.html%3A19%2C21
Not sure if it's any better than 2 DOM nodes performance-wise though.
What do you think?

Comment (romgrk) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:444]: Performance-wise there is no difference between `::before` and a DOM node, in both cases the browser will create a layout object at that location.

Maybe instead we could check if the cell child is a string or an object, and change the display based on that?

Comment (cherniavskii) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:444]: > Maybe instead we could check if the cell child is a string or an object, and change the display based on that?

Yes, something like this:
```tsx
if (typeof children !== 'string' && typeof children !== 'number') {
  classNames.push(gridClasses['cell--flex']);
}
```

The downside is that the text won't be truncated in this case:

```tsx
renderCell: ({ value }) => <div>{value}</div>
```

Did the removal of the `.cellContent` element improve scrolling performance? Do you have any numbers?

Comment (romgrk) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:444]: I don't love the runtime check for string/object because it feels a bit obscure from a user POV that it would do that, but I'm ok with it. What do you think about the `display` field on the columns? Should we keep it for users to adjust that easily?

> Did the removal of the .cellContent element improve scrolling performance? Do you have any numbers?

Yes, we got a 5% improvement over scripting & rendering. It's not a huge improvement but I think it's worth it. If we keep accumulating the improvements, we'll be more performant than the competition (ag-grid). I think with all of the recent ones and #12023 we might be there soon, I'll need to benchmark.

| Before | After |
| --- | --- |
| Screenshot from 2024-02-12 19-28-58 | Screenshot from 2024-02-12 19-28-08 |

*Test: scroll a large list with `scroller.scrollTo({ top: 100_000, behavior: 'smooth' })`*

Comment (oliviertassinari) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:444]: To be fair, AG Grid is rarely the fastest in the benchmark https://dzone.com/articles/data-grid-performance-comparison, https://medium.com/@david.greene_40229/the-fastest-javascript-data-grid-a-performance-analysis-d7a34389593e. I suspect they differentiate with the depth of the features available.

Now, I think we should be centered on what do our users want, I'm all for a slick UX 😁

Comment (romgrk) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:444]: Good to know, though the benchmarks in those links seem outdated and don't match what I feel ag-grid current performance is. It would be neat to create benchmarks to compare with other grids. Then we'll be able to write our own article comparing performance where we claim we're the fastest.

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 2]
```diff
@@ -621,6 +639,21 @@ export const GridRootStyles = styled('div', {
       alignSelf: 'stretch',
       marginRight: t.spacing(2),
     },
+
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:641]: I'd rather leave this one in, having a space between the classes of different components helps navigate this file. The idea is to have something like this:

```
.cell {}
.cell--left {}
.cell--right {}

.scrollbarFiller {}
.scrollbarFiller--header {}
.scrollbarFiller--pinned {}
```

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 1 above)
Comment (oliviertassinari) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:444]: A blog post on all the techniques and learnings we used to make it fast sounds 👌

Comment (romgrk) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:444]: I was also thinking about reworking our [docs demos](https://mui.com/x/react-data-grid/demo/). In the current state, it feels a bit cramped and unintuitive to use, when compared with e.g. the [ag-grid demo](https://ag-grid.com/example/):

| DataGrid | AG-grid |
| --- | --- |
| image | image |

Maybe even making a similar dataset to what ag-grid uses, so people can do a 1-1 comparison. Grid performance in particular is not really displayed in the docs, we only have small datasets examples. I've been assuming ag-grid is the main competition btw. We should also probably create a feature-by-feature comparison to other grids, with the latest changes we are going to be more performant and more accessible to screen readers than other grids, it would be nice to highlight.

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (oliviertassinari) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:641]: Then to add a comment. I think it's feels arbitrary otherwis.

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 1 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:444]: IMHO, the added `GridColDef['display']` makes it harder to reuse the custom cell renderer:

```tsx
import { renderEmail } from './grid-utils';

const columns = [
  {
    field: 'email',
    renderCell: renderEmail,
    display: 'flex',
  }
]
```

This could be solved by extracting a custom column though:

```tsx
import { emailColumn } from './grid-utils';

const columns = [
  {
    field: 'email',
    ...emailColumn, // already has `display: 'flex'` applied
  }
]
```

I think it's OK

File: docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md [hunk 3]
```diff
@@ -460,10 +461,12 @@ See the [Direct state access](/x/react-data-grid/state/#direct-selector-access)
  }
 ```
 
-### CSS classes
+### CSS classes and styling
 
 - You can now style a row's hover state using just `:hover` instead of `.Mui-hovered`.
 - The `.MuiDataGrid--pinnedColumns-(left\|right)` class for pinned columns has been removed.
+- The `.MuiDataGrid-cell--withRenderer` class has been removed.
+- The cell element isn't `display: flex` by default. You can use `cellClassName: gridClasses['cell--flex']` to restore the behavior.
```
Comment (cherniavskii) [inline docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md:469]: Needs to be updated to `display: 'flex'` instead

File: docs/pages/x/api/data-grid/data-grid-pro.json [hunk 4]
```diff
@@ -1375,6 +1369,30 @@
       "description": "Styles applied to the horizontal scrollbar.",
       "isGlobal": false
     },
+    {
+      "key": "scrollbarFiller",
```
Comment (cherniavskii) [inline docs/pages/x/api/data-grid/data-grid-pro.json:1373]: Should we ignore the scrollbar filler classes?

File: packages/x-data-grid-generator/src/renderer/renderProgress.tsx
Comment (cherniavskii) [inline packages/x-data-grid-generator/src/renderer/renderProgress.tsx:1]: I don't get this change in Argos: https://app.argos-ci.com/mui/mui-x/builds/17744/76165287
I cannot reproduce this in the preview deployment: https://deploy-preview-12013--material-ui-x.netlify.app/x/react-data-grid/api-object/#inside-the-data-grid



Any ideas? Could this be related to OS font rendering?

File: docs/data/data-grid/column-dimensions/ColumnAutosizing.js
Comment (cherniavskii) [inline docs/data/data-grid/column-dimensions/ColumnAutosizing.js:1]: Looks like the vertical centering is gone:
- https://app.argos-ci.com/mui/mui-x/builds/17744/76165330
- https://app.argos-ci.com/mui/mui-x/builds/17744/76165366

Can we keep it by default?

**Review by cherniavskii — APPROVED** [review]

File: docs/pages/x/api/data-grid/data-grid-pro.json (hunk 4 above)
Comment (romgrk) [reply docs/pages/x/api/data-grid/data-grid-pro.json:1373]: Wdym by ignore? I already have the `@ignore - do not document` on there, but the export script still picks these ones up.

File: packages/x-data-grid-generator/src/renderer/renderProgress.tsx
Comment (romgrk) [reply packages/x-data-grid-generator/src/renderer/renderProgress.tsx:1]: I figured it's a text underline rendering issue caused by the change in `display` value, I would think it's an upstream chromium issue.

File: docs/data/data-grid/column-dimensions/ColumnAutosizing.js
Comment (romgrk) [reply docs/data/data-grid/column-dimensions/ColumnAutosizing.js:1]: No, I couldn't find a way to preserve that while satisfying the other constraints. CSS doesn't do vertical centering well unless it's in flex/grid mode. Vertical padding would mess up the space available, and the trick for text cells was to set the `line-height` to `height` (copied from ag-grid).

File: packages/x-data-grid-generator/src/renderer/renderProgress.tsx
Comment (cherniavskii) [reply packages/x-data-grid-generator/src/renderer/renderProgress.tsx:1]: @romgrk I cannot reproduce it on MacOS (Chromium: 121.0.6167.139).
Can you reproduce it on Linux?

File: docs/data/data-grid/column-dimensions/ColumnAutosizing.js
Comment (cherniavskii) [reply docs/data/data-grid/column-dimensions/ColumnAutosizing.js:1]: > the trick for text cells was to set the line-height to height

In the linked demos, the cells impacted *are* text cells.
Should we add `display: 'flex'` then?
Also, could you mention this change in the migration guide?

File: docs/pages/x/api/data-grid/data-grid-pro.json (hunk 4 above)
Comment (cherniavskii) [reply docs/pages/x/api/data-grid/data-grid-pro.json]: I've merged `next` into the branch - they're properly ignored now

File: packages/x-data-grid-generator/src/renderer/renderProgress.tsx
Comment (romgrk) [reply packages/x-data-grid-generator/src/renderer/renderProgress.tsx:1]: No, the underline is cropped cleanly:
image

File: docs/data/data-grid/column-dimensions/ColumnAutosizing.js
Comment (romgrk) [reply docs/data/data-grid/column-dimensions/ColumnAutosizing.js:1]: Yes, that's the one case I couldn't make work, but as I [mention above](https://github.com/mui/mui-x/pull/12013#issuecomment-1937114701), I don't feel it's necessarily wrong. Trying to fix it would introduce too much magic imho, so I'd leave that change as it is.

I've added a note to the guide.

Comment (cherniavskii) [reply docs/data/data-grid/column-dimensions/ColumnAutosizing.js:1]: Alright, thanks for the clarification.
