### PR TITLE
[fields] Allow to reset the value from the outside

### LINKED ISSUE #8285: [DatePicker] value is not reset correctly
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/reset-mui-datepicker-v6-fyrxxu?file=/demo.tsx

Steps:
1. Press Reset
2. Focus the DatePicker field

### Current behavior 😯

When using the DatePicker as a controlled component and reset the value via state update, the old value will remain when the picker is focused.

### Expected behavior 🤔

In v5 the value can be reset programmatically. This made it easy to reset forms, for example. https://codesandbox.io/s/reset-mui-datepicker-v5-fkle7i?file=/demo.tsx

### Context 🔦

_No response_

### Your environment 🌎

@mui/x-date-pickers: 6.0.2

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #8285

### CODE REVIEW

File: packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts [hunk 1]
```diff
@@ -371,7 +371,7 @@ export const useFieldState = <
       const sections = fieldValueManager.getSectionsFromValue(
         utils,
         localeText,
-        state.sections,
+        null,
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts:374]: If we pass the `state.sections`, it will be used whenever the new date is null.

**Review by LukasTy — APPROVED** [review]
