### PR TITLE
[charts] Update Popper position outside of react

### LINKED ISSUE #14746: [charts] CPU spike when hovering on the chart
### Steps to reproduce

Link to live example: (required) https://drive.google.com/file/d/19hOtxsfqvliGRWg99a7IkYPql6RejmMc/view?usp=drive_link

https://mui.com/x/react-charts/lines/
SCR-20241015-mykz

https://recharts.org/en-US/examples
SCR-20241015-myob

I have htop opened on the left side. The top process (chrome tab) can be ignored as it's the meet video call with recording that I used to create the above video. The interesting process is the second row (highlighted). You can follow the CPU spikes as I hover on the respective charts. Now, this is not a very rigorous way to test performance but since the difference is quite obvious I thought it would be acceptable to share it without spending a lot of time making the test more accurate. 

Steps:
1. Display any line chart or bar chart on a page (with tooltip enabled)
2. Hover on the chart continuously with your mouse to make the tooltip appear at different ticks
3. Use a tool to monitor CPU usage such as top or htop.
4. You should notice significant CPU spikes as you hover on the chart. The spike disappears as soon as you stop hovering.

I assume that this has to do with the code rending the tooltip or the mark but I haven't tried to disable these yet.
Recharts has a similar behaviour but doesn't spike as dramatically as MUI X-charts. I also tried with Chart.JS but since they use canvas I thought it might not be as fair/useful a comparison.

Hopefully, this is helpful. If not, feel free to close. 
Thank you for your time.

### Current behavior

When hovering continuously on charts, CPU usage stays unexpectedly high.

### Expected behavior

CPU should stay relatively stable when showing the same chart with the same tooltips.

### Context

We create dashboard pages with many charts on it so it's very common for people to be hovering on charts continuously even without wanting to do so. When hovering continuously on line charts and bar charts (maybe other types of charts too), I noticed that my laptop fan was going at full speed. Looking at htop, I found out that the chrome tab with the mui/x-charts was using close to 100% CPU. I compared the same behavior with Recharts charts and the CPU was never above 50%. Since our users don't necessarily have very powerful machines, this CPU usage might make the application unresponsive frequently.

### Your environment

The following is the summary of my system but this seems to be happening on the MUI X-charts documentation page too so I don't think the issue is specific to my system.
 
<details>
  <summary><code>npx @mui/envinfo</code></summary>

$ npx @mui/envinfo
  System:
    OS: Linux 6.9 Pop!_OS 22.04 LTS
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 9.1.4 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.58
  npmPackages:
    @mui/core-downloads-tracker:  6.1.0 
    @mui/icons-material: 6.1.0 => 6.1.0 
    @mui/material: 6.1.0 => 6.1.0 
    @mui/private-theming:  6.1.0 
    @mui/styled-engine:  6.1.0 
    @mui/styled-engine-sc: ^6.1.0 => 6.1.0 
    @mui/styles: ^6.1.0 => 6.1.0 
    @mui/system:  6.1.0 
    @mui/types:  7.2.16 
    @mui/utils:  5.16.6 
    @mui/x-charts: ^7.18.0 => 7.18.0 
    @mui/x-charts-vendor:  7.18.0 
    @mui/x-date-pickers: ^7.16.0 => 7.16.0 
    @mui/x-internals:  7.16.0 
    @mui/x-tree-view: ^7.16.0 => 7.16.0 
    @types/react: 18.0.26 => 18.0.26 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    styled-components: ^6.1.13 => 6.1.13 
    typescript: ^4.9.5 => 4.9.5 
</details>

**Search keywords**: charts CPU

### PR DESCRIPTION
**Pull request by alexfauquette**
Part of #14746

The issue seems to come from the `onMouseMove` which trigger at high frequency costly functions:

- Updating the tooltip
- Updating the context that tracks interaction.

In this PR I initially proposed to throttle those updates. 200ms for the interaction, because highlight can suffer a little delay without issue. And 50ms for the tooltip since it's reaction needs to be smoother.

We could gain additional performances by going from 50ms to 200ms for the tooltip, and smoothening it with transition but it creates a weird effect of the tooltip following your mouse like a ghost

After the first feedback, this PR is modified to only move tooltip placement from react state to vanilla JS update.

The management of the context state remains to do

### CODE REVIEW

**Comment by romgrk** [comment]
This is an area where you would benefit from doing things outside of react. The tooltip position update could easily be a vanilla JS event handler that updates its position without going through react, the same way we use popperjs in other parts of the codebase. That would allow for high-frequency updates without the UX degradation.

File: packages/x-charts/src/ChartsTooltip/utils.tsx [hunk 1]
```diff
@@ -74,13 +75,16 @@ export function useMouseTracker(): UseMouseTrackerReturnValue {
       });
     };
 
+    const throttledHandleMove = throttle(handleMove, 50);
```
Comment (oliviertassinari) [inline packages/x-charts/src/ChartsTooltip/utils.tsx:78]: 50ms, so 20 Hz. This feels very lagging on my screen. I think we can't go lower than 120 Hz, so 8ms.

Comment (romgrk) [reply packages/x-charts/src/ChartsTooltip/utils.tsx:78]: And tbh even with no throttling there is usually some base amount of lag, because the OS compositor draws the mouse as the last step just before redrawing the monitor, to make the mouse feel as responsive as possible. Meanwhile apps have access to a less recent mouse position. So anything that doesn't go through the native OS APIs will always have some lag.

File: packages/x-charts/src/internals/throttle.ts [hunk 2]
```diff
@@ -0,0 +1,33 @@
+export interface Cancelable {
+  clear(): void;
+}
+
+// Corresponds to 10 frames at 60 Hz.
+// A few bytes payload overhead when lodash/debounce is ~3 kB and debounce ~300 B.
+export default function throttle<T extends (...args: any[]) => any>(func: T, wait = 166) {
```
Comment (oliviertassinari) [inline packages/x-charts/src/internals/throttle.ts:7]: I guess it duplicate with `packages/x-internals/src/throttle/throttle.ts`

**Review by oliviertassinari — COMMENTED** [review]
> This is an area where you would benefit from doing things outside of react. The tooltip position update could easily be a vanilla JS event handler that updates its position without going through react, the same way we use popperjs in other parts of the codebase.

💯 to go in this direction. Throttle sounds wrong in the first place. For example, https://mui.com/material-ui/react-tooltip/#follow-cursor is fast enough comparatively, with a x6 CPU slow-down, so I don't think we need this.

I had a bit of a closer look, what I see:

1. **Context propagation**. We group different values in a context value, we update some of the context, we don't need the rest of the context, but React is blind to it, it forces a rerender for any part of the context change, e.g. with InteractionContext. It sounds similar to the work that @flaviendelangle is doing on the tree view to isolate state changes. We need something like the grid has, or  https://github.com/mui/mui-x/issues/12405.

2. **Unnecessary re-renders**. The `useMouseTracker()` + `generateVirtualElement()` has the right primitives but the implementation forces a lot of re-renders, we should be able to easily refactor this.

With those two, I would expect we are back to 🚀.

File: docs/data/charts/tooltip/CustomAxisTooltip.js [hunk 3]
```diff
@@ -3,22 +3,80 @@ import NoSsr from '@mui/material/NoSsr';
...
+      element.removeEventListener('pointermove', handleMove);
+    };
+  }, [svgRef]);
+
+  return { ...pointer, popperRef, anchorEl: virtualElement.current };
+}
+
 export function CustomAxisTooltip() {
   const tooltipData = useAxisTooltip();
-  const mousePosition = useMouseTracker(); // Track the mouse position on chart.
```
[the remark this answers is not in the document]
Comment (alexfauquette) [reply docs/data/charts/tooltip/CustomAxisTooltip.js:11]: The initial idea of `useMouseTracker` was to provide an abstraction that could help devs whatever the tootlip they use:

The hook was returning the pointer position and its type. Then up to the user to place the tooltip.

The issue of such a hook is that not all library have this notion of `.update()` for example [floating-ui](https://floating-ui.com/docs/useclientpoint) seems to use a hook to update coordinates 

The height and pointer type are not an issue. It's mostly to distinguish mousse/fingers so we only measure it during the first interaction. That's why I still save them in a state

File: packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx [hunk 4]
```diff
@@ -133,14 +129,18 @@ function ChartsTooltip<T extends ChartSeriesType>(inProps: ChartsTooltipProps<T>
   });
   const { trigger = 'axis', itemContent, axisContent, slots, slotProps } = props;
 
-  const mousePosition = useMouseTracker();
+  const svgRef = useSvgRef();
+  const pointerType = usePointerType();
+
+  const popperRef: PopperProps['popperRef'] = React.useRef(null);
+  const virtualElement = React.useRef(generateVirtualElement({ x: 0, y: 0 }));
```
Comment (romgrk) [inline packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx:136]: For these type of cases the `useLazyRef` hook from the `@mui/utils` is useful. It allows to separate initialization and rendering, so the `generateVirtualElement({ ... })` doesn't need to run at every render (creates GC pressure for no reason).

Something like this:

```js
function createVirtualElement() {
  return generateVirtualElement({ x: 0, y: 0 })
}

// then here
const virtualElement = useLazyRef(createVirtualElement)
```

Comment (alexfauquette) [reply packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx]: I added it. But the react compiler seems to do not hunderstand that `useLazyRef` returns a ref. So I had to do the lazy implemetation directly

Comment (romgrk) [reply packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx]: The react compiler or eslint? From what I read on the compiler I would have expected it to be smart enough for that.

**Review by romgrk — APPROVED** [review]

File: packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx (hunk 4 above)
Comment (alexfauquette) [reply packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx]: The eslint(react-compiler/react-compiler)

When I do `virtualElement.current = ....`
> Mutating a value returned from a function whose return value should not be mutated eslint(react-compiler/react-compiler)

And when I don't put `virtualElement` in the dependency array of the `useEffect`

> React Hook React.useEffect has a missing dependency: 'virtualElement'. Either include it or remove the dependency array.eslint[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)

For the first one, I could disable eslint on the line.
For the second one, I just realized I could add the `virtualElement` to let dependency array since it is a ref it will never trigger the effect
