### PR TITLE
[DataGridPremium] Fix aggregation with sorting

### LINKED ISSUE #19370: Column aggregation breaks if sortModel is passed to props
### Search keywords

aggregation sort model sorting sortModel

### Latest version

- [x] I have tested the latest version

### Affected products

Data Grid

### Steps to reproduce

Steps:
1. Open this link to live example: https://stackblitz.com/edit/github-p76sjn2j?file=src%2Fdemo.tsx
2. No further steps necessary to reproduce the bug.
   * The bug seemingly only happens the first time the data grid is rendered - triggering a re-render by editing the file will "fix" it. When this happens, you can refresh stackblitz's preview page to have it happen again.

### Current behavior

Aggregated columns don't show their expected value on the first time the data grid is rendered.

### Expected behavior

Aggregated columns should always show their expected value.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 11 10.0.26100
  Binaries:
    Node: 24.3.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    npm: 11.4.2 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (139.0.3405.119)
  npmPackages:
    @emotion/react: 11.14.0 => 11.14.0
    @emotion/styled: 11.14.0 => 11.14.0
    @mui/core-downloads-tracker:  7.2.0
    @mui/icons-material: 7.0.2 => 7.0.2
    @mui/lab: ^7.0.0-beta.14 => 7.0.0-beta.14
    @mui/material: ^7.2.0 => 7.2.0
    @mui/private-theming:  7.2.0
    @mui/styled-engine:  7.2.0
    @mui/system:  7.2.0
    @mui/types:  7.4.5
    @mui/utils:  7.3.1
    @mui/x-data-grid: ^8.9.1 => 8.10.2
    @mui/x-data-grid-premium: ^8.9.1 => 8.10.2
    @mui/x-data-grid-pro:  8.10.2
    @mui/x-date-pickers: ^8.9.0 => 8.9.2
    @mui/x-date-pickers-pro: ^8.9.2 => 8.9.2
    @mui/x-internals:  8.9.2
    @mui/x-license:  8.9.2
    @mui/x-telemetry:  8.5.3
    @mui/x-tree-view: ^8.10.0 => 8.10.0
    @mui/x-virtualizer:  0.1.3
    @types/react: 19.1.2 => 19.1.2
    react: 19.1.0 => 19.1.0
    react-dom: 19.1.0 => 19.1.0
    typescript: 5.8.3 => 5.8.3
```
</details>

### Order ID or Support key 💳 (optional)

107216

### PR DESCRIPTION
**Pull request by lauri865**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #19370
Closes #19891

Avoids cancelling the aggregation process early, as well as includes sortColumns (if aggregated) in the initial chunk / viewport to speed up things visually.

### CODE REVIEW

**Comment by lauri865** [comment]
There's one more issue that should be fixed. In case of row grouping (probably tree data as well) with sorting, there's a flash of unsorted content on first mount.

**Comment by lauri865** [comment]
@romgrk, I noticed that `useStoreEffect` doesn't have any equality check built on, so it can cause cascading state updates. Noticed that e.g. the below state setter runs multiple times in one render pass:
https://github.com/mui/mui-x/blob/ae64f957b34f594cdd26443814c6dfea3cb68c41/packages/x-data-grid/src/hooks/core/useGridVirtualizer.tsx#L341

Not sure if I broke something by adding the equality check now, but...

File: packages/x-data-grid-premium/src/hooks/features/aggregation/useGridAggregation.ts [hunk 1]
```diff
@@ -89,126 +90,129 @@ export const useGridAggregation = (
...
+
+    const renderContext = gridRenderContextSelector(apiRef);
+    const visibleColumns = gridVisibleColumnFieldsSelector(apiRef);
+
+    const chunks: string[][] = [];
+    const sortFields = gridSortModelSelector(apiRef).map((s) => s.field);
+    const visibleAggregatedFields = visibleColumns
+      .slice(renderContext.firstColumnIndex, renderContext.lastColumnIndex + 1)
+      .filter((field) => aggregatedFields.includes(field));
+    const visibleAggregatedFieldsWithSort = visibleAggregatedFields.concat(
```
Comment (cherniavskii) [inline packages/x-data-grid-premium/src/hooks/features/aggregation/useGridAggregation.ts]: OK, so IIUC instead of calling `applyAggregation('sort')` on sort model change, sorted columns are now included in the first chunk, correct?

File: packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts:1]: Can you explain why the implementation changed?

File: packages/x-internals/src/store/useStoreEffect.ts [hunk 2]
```diff
@@ -36,7 +37,9 @@ function initialize<State, Value>(params?: {
     subscribe: () => {
       instance.dispose ??= store.subscribe((state) => {
         const nextState = selector(state);
-        instance.effect(previousState, nextState);
+        if (!argsEqual(previousState, nextState)) {
+          instance.effect(previousState, nextState);
+        }
```
Comment (romgrk) [inline packages/x-internals/src/store/useStoreEffect.ts]: I think we can try this optimization, the store is still an evolving API. I would keep it simple though, just `Object.is`. Do you have any objection to that?

Comment (lauri865) [reply packages/x-internals/src/store/useStoreEffect.ts]: Object.is is fine. I added the other check initially because I had a thought about replacing multiple events with a single Effect that selects multiple parts of the state. But that was misguided on my part anyways, because the effects are synchronously run on setting state, hence that wouldn't help deduplicate events in any case.

File: packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts
Comment (lauri865) [reply packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts:1]: Yes, so, when I went with the previous implementation, I was under the assumption that filtering, etc. doesn't depend on aggregation, hence, we want to guarantee maximum level of deduplication with the queueMicrotask approach. But the case is actually that sorting under certain circumstances (=when sorting an aggregated row **with** grouping) can depend on aggregation, hence, we cannot defer without incurring visual flicker on mount.

Check this reproduction:
https://stackblitz.com/edit/xdrrihtc?file=src%2FDemo.tsx

File: packages/x-data-grid-premium/src/hooks/features/aggregation/useGridAggregation.ts (hunk 1 above)
Comment (lauri865) [reply packages/x-data-grid-premium/src/hooks/features/aggregation/useGridAggregation.ts]: It's two different things.

applyAggregation('sort') needs to run only when there are sort dependent aggregations (rank, median, first/last, etc.).

But Sort columns were included in the initial chunk due to what I wrote in the next comment. We want them to be included in the first chunk (=these columns affect "viewport" due to potentially changing the row order, regardless of whether they are in the renderContext or not) so that we don't end up with a visual flicker.

**Comment by lauri865** [comment]
@romgrk, another thing I noted on the virtualizer decoupling is that there's now more render passes required to reconcile the initial state for rows to be rendered than before (5 passes in total with static data / columns).

In v8.9.1 rows were rendered on the 3rd render pass already vs. 5th. (<~15ms in vs 60ms+ now)

**Comment by lauri865** [comment]
Also, there's no way this can run properly:

https://github.com/mui/mui-x/blob/bf48426bd1a835119b83c38bb64325ee8048a7b9/packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx#L87

`useVirtualization` uses inputs that are provided during rendering as params, and an event is run outside of rendering in connection to store updates. So, the `forceUpdateRenderContext` will never have access to the fresh state (=rows in this case).

Previously inputs were accessed directly from the store (=had access to update values outside of rendering).

**Comment by lauri865** [comment]
Also, the virtualizer used to be isolated from the rest of the Datagrid feature hooks, which was great for performance, since a virtualizer can update quite frequently.

Now, by including it in the root of the grid in `useDataGridComponent` under `useGridVirtualization`, means that everything under that tree needs to re-evaluate when scrolling, as the root state updates quite frequently.

This is bad imho. And shouldn't have been released under a minor version.

**Comment by lauri865** [comment]
Added an experimental refactor that takes mount performance back to the old baselines if not slightly better (<15ms vs. 60m = 4x better; in 3 render passes vs. 5 currently). The structure is closer to how it used to be as well where Virtualizer doesn't affect the whole grid's feature hook tree with its state updates.

No need for hacky commiting setters into a store that consumer that very store (=source for memory leaks), or state setting whenever a ref changes.

**Comment by lauri865** [comment]
@MBilalShafi, I don't understand why the call count should be 2 here:

https://github.com/mui/mui-x/blob/b1c29146d8b8f8f88ec8911f2906d0aa17025427/packages/x-data-grid/src/tests/rowSpanning.DataGrid.test.tsx#L286

It starts from a non-spanned state, so there's nothing to reset from when updating the rows? Or am I misunderstanding something here?


PS: if anyone knows why the Netlify deploys started failing here, would appreciate it.

**Comment by lauri865** [comment]
Hopefully tests should be passing now. Still no idea what's happening with Netlify – pnpm run docs:build works fine on my end.

File: packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/utils/useRunOncePerLoop.ts:1]: Yeah, I can see the flickering.
But I don't understand the difference between initialState and controlled sort model you mentioned here:

```
        // Passing an initial sort model works as expected:
        // initialState={{
        //   sorting: {
        //     sortModel: [],
        //   },
        // }}
        //
        // Passing a controlled sort model does not:
        // initialState={initialState}
```
The behavior seems to be identical if I switch to controlled sort model.

**Comment by romgrk** [comment]
> Now, by including it in the root of the grid in `useDataGridComponent` under `useGridVirtualization`, means that everything under that tree needs to re-evaluate when scrolling, as the root state updates quite frequently.

Agreed, I was hoping to refactor that part away faster but that PR introduced a few uncaught regressions that delayed the process.

> No need for hacky commiting setters into a store that consumer that very store (

I was also hoping to get rid of that part, in fact in #19465 I rename that part to `legacyAPI`. I couldn't touch it much because it's exposed in one of the datagrid slots, so modifying it would technically be a breaking change. I want to move the reactivity model to store/selectors everywhere instead of "getters", so that components can individually select/build their props from the minimal slice of state required from the store. The end goal is to have less stuff re-rendering during scrolling.

I plan to place props in the store (or memoized selectors), e.g. `{ virtualization: { props: { container: { ... }, scroller: { ... }, ... } } }`, so `GridVirtualScroller` doesn't need to pull all the "getters" anymore, each component can select its props and re-render independently, e.g. `const containerProps = useSelector(store, s => s.virtualization.props.container)`

File: packages/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumComponent.tsx
Comment (cherniavskii) [inline packages/x-data-grid-premium/src/DataGridPremium/useDataGridPremiumComponent.tsx:1]: > Added an experimental refactor that takes mount performance back to the old baselines if not slightly better (<15ms vs. 60m = 4x better; in 3 render passes vs. 5 currently).

Can you share the the details of your setup for measurements?
I'll try to add a benchmark for mount performance to track regressions.

File: packages/x-data-grid/src/hooks/core/useGridVirtualizer.tsx [hunk 3]
```diff
@@ -338,7 +335,7 @@ export function useGridVirtualizer(
     apiRef.current.store.state.virtualization = virtualizer.store.state.virtualization;
   });
 
-  useStoreEffect(virtualizer.store, Dimensions.selectors.dimensions, (_, dimensions) => {
+  useStoreEffect(virtualizer.store, Dimensions.selectors.dimensions, (prev, dimensions) => {
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/core/useGridVirtualizer.tsx]: This change can be reverted, to stay consistent with the other similar lines.
```suggestion
  useStoreEffect(virtualizer.store, Dimensions.selectors.dimensions, (_, dimensions) => {
```

File: packages/x-data-grid/src/hooks/features/columns/useGridColumnSpanning.ts [hunk 4]
```diff
@@ -12,12 +12,15 @@ import { GridPrivateApiCommunity } from '../../../models/api/gridApiCommunity';
...
-  const calculateColSpan = virtualizer.api.calculateColSpan;
+  const resetColSpan: GridColumnSpanningPrivateApi['resetColSpan'] = () => {
+    return apiRef.current.virtualizer.api.resetColSpan();
+  };
+  const getCellColSpanInfo: GridColumnSpanningApi['unstable_getCellColSpanInfo'] = (...params) => {
+    return apiRef.current.virtualizer.api.getCellColSpanInfo(...params);
+  };
+  const calculateColSpan: GridColumnSpanningPrivateApi['calculateColSpan'] = (...params) => {
+    apiRef.current.virtualizer.api.calculateColSpan(...params);
+  };
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/columns/useGridColumnSpanning.ts:23]: What's this change about?

File: packages/x-virtualizer/src/features/virtualization.ts [hunk 5]
```diff
@@ -606,19 +625,46 @@ function useVirtualization(store: Store<BaseState>, params: VirtualizerParams, a
...
+          // We want to initialize the grid dimensions as soon as possible to avoid flickering
+          api.updateDimensions(isFirstSizing.current);
+          isFirstSizing.current = false;
+        } else {
+          api.debouncedUpdateDimensions();
+        }
+      });
     }
-  };
+  });
```
Comment (romgrk) [inline packages/x-virtualizer/src/features/virtualization.ts:674]: Could you explain why it was needed to move this here? This section of code makes more sense in the "dimensions" feature.

File: packages/x-data-grid/src/hooks/core/useGridVirtualizer.tsx [hunk 6]
```diff
@@ -159,8 +158,6 @@ export function useGridVirtualizer(
   const { getRowHeight, getEstimatedRowHeight, getRowSpacing } = rootProps;
   // </ROWS_META>
 
-  const focusedVirtualCell = useGridSelector(apiRef, gridFocusedVirtualCellSelector);
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/core/useGridVirtualizer.tsx:162]: I remember trying out this implementation in the virtualizer PR but I [reverted it](https://github.com/mui/mui-x/pull/18275/commits/091025a2f5a87731f53e401b6ae5fce75a446603) due to a bug, although I can't remember which one. If everything is working we can keep it as is though.

Comment (romgrk) [reply packages/x-data-grid/src/hooks/core/useGridVirtualizer.tsx:162]: It's probably the cause of [the remaining failing test](https://app.circleci.com/pipelines/github/mui/mui-x/106445/workflows/cf1f9ad8-f747-406f-95ea-7038a778d548/jobs/649832).

File: packages/x-data-grid/src/hooks/features/columns/useGridColumnSpanning.ts (hunk 4 above)
Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/columns/useGridColumnSpanning.ts:23]: Since we cannot initialize the virtualizer in the root component without also adopting its state, we need to call the functions via apiRef.

Virtualizer is registered in GridVirtualScroller, but some effects of the other components may already need to call these functions. Hence we cannot wait until the next render pass for them to become available.

If you'd do:
```typescript
const resetColSpan = apiRef.current.virtualizer.resetColSpan
```

And there's e.g. this code in a feature hook:
```typescript
useEffect(()=>apiRef.current.resetColSpan(),[])
```

It would fail, because resetColSpan is undefined at this stage. But by creating callbacks, we can read the values from the apiRef, which will have been registered by the time the `useEffect` gets invoked.

Not ideal in terms of coupling. But that would be a bigger rewrite to overcome that.

File: packages/x-virtualizer/src/features/virtualization.ts (hunk 5 above)
Comment (lauri865) [reply packages/x-virtualizer/src/features/virtualization.ts:674]: Because you need to force another render for it to work under the dimensions feature currently, in order to pick up the node ref.

If you really want to decouple it, either `getContainerProps` should be returned from the dimension, or dimensions should expose an api method to observe the root node that can be called from the `virtualization`.

**Comment by romgrk** [comment]
> This is bad imho. And shouldn't have been released under a minor version.

Also agreed on that one, tbh the virtualizer PR caused way more issues than is acceptable. Due to previous experiences I try to avoid huge PRs and have been focusing on smaller incremental changes, but for the virtualizer this approach was unsuccessful. The upcoming refactor has been slower and more careful.

**Comment by lauri865** [comment]
> > This is bad imho. And shouldn't have been released under a minor version.
> 
> Also agreed on that one, tbh the virtualizer PR caused way more issues than is acceptable. Due to previous experiences I try to avoid huge PRs and have been focusing on smaller incremental changes, but for the virtualizer this approach was unsuccessful. The upcoming refactor has been slower and more careful.

I can only imagine the difficulty in ripping something so domain-specific out and generalising it.

But maybe we can add a few tests to make sure the core experience doesn't break. E.g. the number of render passes to fully render a grid with virtualization and static props. Performance timing is difficult, but drifts on the first are generally quite correlated with timings as well.

A thought for further refactors – I think the rows should be decoupled from renderContext calculations if at all feasible. Then you can avoid having to mix state from different phases, which should reduce the surface area for bugs significantly, do ahead of time calculations (e.g. rowSpanning doesn't need to wait for the next render to happen to calculate spanned rows for the new renderContext / set of rows).

That all being said, I'm not sure what your plans are with the virtualizer. But IMHO there's a whole host of benefits to having a domain specific virtualizer for the datagrid (generic API and maximum performance contradictory forces usually). So, please just don't sacrifice the performance of the core product for the sake of having a generic virtualizer. We use tanstack virtualizer in other parts of our app, and that works perfectly fine for us, but would take a lot of work to optimise it for e.g. tanstack/table properly with all the bells and whistles of the datagrid.

**Comment by lauri865** [comment]
Tests are passing 🎉

**Comment by romgrk** [comment]
> generic API and maximum performance contradictory forces usually

That's indeed one of my concerns with our upcoming refactor. We want the virtualizer to be usable in our other products, some grid-like (data grid, scheduler, gantt chart), some list-like (base-ui combobox, tree view). I plan to decouple and share the parts that can be shared (features: dimensions, colspan, rowspan), and some others will have different implementations optimized for their use-case (feature: virtualization).

I haven't done optimization work on the virtualization in a whille, I'm also planning to do some of that in the next week(s). I'm aware that the recent work wasn't good for performance, but it's hopefully setting up the foundations (notably with the store and its fine-grained re-renders) for a more performant implementation.

**Comment by lauri865** [comment]
Since I was measuring first mount activity, I also managed to deduplicate calls to filtering/sorting in DataGridPro / DataGridPremium on mount.

What happened is:
1. useFirstRender -> apply(Sorting/Filtering)
2. hydrateColumns is guaranteed to mutate column state for anything above the community package
3. columnsChange triggers new -> apply(Sorting/Filtering) within the same render pass

Just skipping the first step now for Pro and above, and only filtering / sorting after initial column hydration.

I had to implement the changes (except for the memoization fix) from #19807 to make it work though. So maybe it either makes sense to move those changes over there or merge everything in here (meaning one liner for the memo fix on top of what's already here). Wdyt?

**Comment by lauri865** [comment]
@MBilalShafi, FYI, I removed the state initialisation calculations from rowSpanning, and resorted to EMPTY_STATE for all cases as the initial state. The initial calcs were not really being used anyways, as the events 'sortedRowsSet', 'filteredRowsSet', 'columnsChange' onMount would reset the initial state and re-run the calcs.

**Comment by romgrk** [comment]
> So maybe it either makes sense to move those changes over there or merge everything in here

We can merge everything in here.

**Comment by lauri865** [comment]
Yep, I already did, and the call count went down here instead of up in the previous PR (for both, but also R18).

**Comment by lauri865** [comment]
I think you wrote it somewhere (can't find it), but a really welcomed future change would be to put rootProps in a store instead of using a context for it. Currently rootProps is like a plague in the Datagrid that keeps biting us by accident. We have a pretty optimised implementation for the datagrid that memoises most props automatically that shouldn't mutate anyways between renders, however, every once in a while one prop slips through that changes more often than it should, and whenever it does, essentially **every single component** in the tree has to re-render (almost all components or their parents make use of useGridRootProps) and can cause performance issues.

Maybe the best would even be if rootProps was stored in a layer / component above `useDatagridComponent`, so each feature hook could use `useStoreEffect` to sync the controlled props, etc. without having to re-evaluate unrelated feature hooks on every prop change, and without having to resort to useEffect for syncing controlled state with the internal state.

Just a thought.

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts [hunk 7]
```diff
@@ -320,12 +249,16 @@ export const useGridRowSpanning = (
   useGridEvent(apiRef, 'columnsChange', runIf(props.rowSpanning, resetRowSpanningState));
 
   React.useEffect(() => {
+    const store = apiRef.current.virtualizer?.store;
+    if (!store) {
+      return;
+    }
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts:255]: This seems to be causing a regression, the feature flag is no longer being honored after intial render.

https://github.com/user-attachments/assets/16d32614-d197-4213-ad1a-1c56ebd8deaa

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts [hunk 8]
```diff
@@ -300,18 +223,24 @@ export const useGridRowSpanning = (
   // - The sorting is applied
   // - The `paginationModel` is updated
   // - The rows are updated
+  const { schedule: deferredUpdateRowSpawnningState, cancel } =
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts]: Nit:
```diff
- const { schedule: deferredUpdateRowSpawnningState, cancel } =
+ const { schedule: deferredUpdateRowSpanningState, cancel } =
```

**Comment by lauri865** [comment]
Added a performance experiment, which finally lets the Datagrid root component mount in one pass (useGridRowCount was the missing piece; so everything above the virtualizer doesn't need to re-render unless props change). Not too happy with the code, but just experimenting with useStoreEffect instead of useEffect. Measured 15-25% improved initial mount performance with 4x slowdown in dev with the DatagridPremiumDemo.tsx w/o loading state (haven't tested prod yet).

Happy to roll back the changes, but was just curious about the impact.

**Comment by lauri865** [comment]
These virtual scrollbars give me so much grief. They work relatively well in the docs when the viewport is small, but with a larger viewport scrolling on the virtual scrollbar (vs. main body) results in jankiness / ghosting, especially on a 120hz monitor. Feels like frames being dropped, but FPS is the same as when scrolling the main body, and the main thread is doing the same amount of work. 

Try this with 4x slowdown, compare scrolling on the body vs. scrollbar (in full screen):
https://stackblitz.com/edit/dch5gole

In our production case (without any CPU slowdown), scrolling the body is buttery smooth even if the main thread is doing non-trivial amount of work (charts, images, etc.), scrolling on scrollbar is janky as hell. It looks much better when Chrome's energy saver is turned on, so maybe a frame-limiter could help, but if anyone has better ideas, I'm all ears. 

I exposed the scrollbar component as a slot, so we can experiment with alternatives without having to rebuild the datagrid package each time. On Safari, as always, the experience is even worse.

File: packages/x-data-grid/src/models/gridSlotsComponent.ts [hunk 9]
```diff
@@ -232,4 +232,9 @@ export interface GridSlotsComponent extends GridBaseSlots, GridIconSlotsComponen
    * @default GridRow
    */
   row: React.JSXElementConstructor<GridSlotProps['row']>;
+  /**
+   * Component rendered for vertical and horizontal scrollbars.
+   * @default GridVirtualScrollbar
+   */
+  scrollbar: React.JSXElementConstructor<GridSlotProps['scrollbar']>;
```
Comment (romgrk) [inline packages/x-data-grid/src/models/gridSlotsComponent.ts]: I don't like exposing this slot because that component becomes part of the public API and it becomes much harder to do changes on it - avoiding breaking changes is a recurrent limitation when we do optimizations/refactors. Could we remove this change from the PR? We can keep discussing it, and possibly release it under an `experimental` or `unstable_` flag to let us keep working on it.

Comment (romgrk) [reply packages/x-data-grid/src/models/gridSlotsComponent.ts]: > These virtual scrollbars give me so much grief.

We want to make it possible to toggle virtual scrolling with a flag (in the virtualizer), and possibly even enable adaptive virtual scrolling (low speed is native scroll, high speed is virtual scroll), but we need to be able to make those changes without breaking the public API.

File: packages/x-data-grid/src/hooks/features/columns/useGridColumnSpanning.ts
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/columns/useGridColumnSpanning.ts:1]: Is this slight change in column spanning behavior expected? (more rows flicker on re-render)

[Before](https://mui.com/x/react-data-grid/column-spanning/#function-signature):

https://github.com/user-attachments/assets/02be710e-ea61-49d7-a15b-31543a49b2ab

[After](https://deploy-preview-19892--material-ui-x.netlify.app/x/react-data-grid/column-spanning/#function-signature):

https://github.com/user-attachments/assets/812e7a13-27d9-475c-bd0c-ad5bf4f83d89

Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/columns/useGridColumnSpanning.ts]: Hmm, strange. Can't seem to reproduce this in development, only prod; although I see that it should happen the same based on state changes. Perhaps DEV is just sufficiently slower so you don't see it visually.

It did work the same prior to virtualization refactor: https://deploy-preview-18827--material-ui-x.netlify.app/x/react-data-grid/column-spanning/

Not 100% sure, but I don't think the underlying reasons have changed (virtualizer doesn't know that the main container is a flex parent that can grow, so it recursively expands when renderContext expands). Perhaps the performance regressions in the current virtualisation implementation just mask the issue.

**Comment by romgrk** [comment]
To merge this we need to fix tests for R18 and revert the scrollbar slot. I have another PR waiting for this one which will conflict, I might have to merge it soon.

**Comment by lauri865** [comment]
IIRC, the R18 errors are related to event handler cleanups in `packages/x-virtualizer/src/features/virtualization.ts`. I think if they're done in the ref callback itself, it should work fine (<=R18, cleanup when node = null, >=R19 return a cleanup function). Wanted to avoid versioned logic, but not sure it's possible, at least not with the current implementation (and in StrictMode).

I don't have bandwidth until end of this week to do it myself though.

**Comment by romgrk** [comment]
Is the ref callback cleanup logic really useful? I've been trying to fix the remaining issues with that but it feels like whack-a-mole, with R18 and R19 having slightly different behaviors.

**Comment by lauri865** [comment]
> Is the ref callback cleanup logic really useful? I've been trying to fix the remaining issues with that but it feels like whack-a-mole, with R18 and R19 having slightly different behaviors.

It can cause detached DOM node memory leaks in some instances, so better safe than sorry. I pushed a change that should (hopefully) fix it.

**Comment by lauri865** [comment]
Tests are passing! 🎉

Except for one scheduler / base-ui related test which shouldn't be related to this PR.

**Comment by lauri865** [comment]
And everything passing on a 2nd run.

**Comment by romgrk** [comment]
> Is the ref callback cleanup logic really useful?

I wasn't clear, what I meant is is it necessary to manually attach event listeners (which causes the need for the cleanup logic)? As the tests are passing I'm fine with it, just curious.

I'll try to fix the minor row spanning regression before merging this.

**Comment by lauri865** [comment]
> > Is the ref callback cleanup logic really useful?
> 
> I wasn't clear, what I meant is is it necessary to manually attach event listeners (which causes the need for the cleanup logic)? As the tests are passing I'm fine with it, just curious.
> 
> I'll try to fix the minor row spanning regression before merging this.

Gotcha. Well, it's not strictly necessary, as from React 17 onwards these handlers are passive anyways. But if the idea is to abstract the virtualizer into a separate package, it's probably a good idea anyways. Directly attached / prop-based handlers are best left to the developers to use/consume without having to think about composition with the virtualizer and potentially breaking virtualizer by attaching an additional `onScroll` handler to the scrollable container. That's inline with how every other virtualizer library works I believe.

File: packages/x-data-grid/src/hooks/features/columns/useGridColumnSpanning.ts
Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/columns/useGridColumnSpanning.ts:1]: That demo height is set as `fit-content`, which prevents the grid from knowing the available space ahead of time. I've added `autoHeight` as a fix.

File: packages/x-data-grid/src/hooks/features/pagination/useGridPaginationModel.ts [hunk 10]
```diff
@@ -255,7 +255,9 @@ export const useGridPaginationModel = (
 
       const pageCount = gridPageCountSelector(apiRef);
       if (paginationModel.page > pageCount - 1) {
-        apiRef.current.setPage(Math.max(0, pageCount - 1));
+        queueMicrotask(() => {
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/pagination/useGridPaginationModel.ts:258]: What's was the reason for this change?
It changed the number of `onPaginationModelChange` calls from 1 to 2 when the filter model is set.
Before, setPage calls were batched in a single state update, now they cause 2 state updates.

Debouncing seems to set it back to 1 state update: https://github.com/mui/mui-x/pull/20332/files#diff-307c4e14314b8e477344a66cc87aaa51c9b1643b5ee8a8e9ba2640429eff22d5
