### PR TITLE
[data grid] Fix pagination state with unknown row count when controlled by `paginationMeta`

### LINKED ISSUE #20667: [data grid] PaginationMeta  + unknow row count does not work (even in the demo)
### Steps to reproduce

Steps:
1. [Open this link to live example: (required)](https://codesandbox.io/embed/hggysd?module=/src/Demo.tsx&fontsize=12) (MUI DEMO)

### Current behavior

It stopped working in the new version 8.22. In the previous version I was able to make it work if I didn’t pass a rowCount; everything else was practically the same. But now, just like in the demo, it has stopped working.”

Another thing is that, if you dont pass a rowCount in paginationMode="server" i always got a console log with a warning, even tho i should not pass rowCount for the paginationMeta to work

I confirmed that paginationMeta.hasNextPage is working correcly and changing the values when it should, it just does not apply to the pagination.

### Expected behavior

Pagination has next page should stop when the paginationmeta.hasNextPage set to false.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: paginationmeta, unknow row count, hasNextPage

### PR DESCRIPTION
**Pull request by mj12albert**
Preview: https://stackblitz.com/edit/mz7lzksi?file=src%2FDemo.tsx

Made it work when `rowCount` is not explicitly specified, technically `rowCount={-1}` could work as well but looks sketchy

Fixes https://github.com/mui/mui-x/issues/20667

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts [hunk 1]
```diff
@@ -26,10 +26,12 @@ export const useGridRowCount = (
 
   const previousPageSize = useLazyRef(() => gridPaginationModelSelector(apiRef).pageSize);
 
+  const onRowCountChangeProp = props.onRowCountChange;
```
Comment (mj12albert) [inline packages/x-data-grid/src/hooks/features/pagination/useGridRowCount.ts:29]: Don't know why eslint complains when I pass `props.onRowCountChange` into a deps array despite that other props in this file are not destructured before they go into a deps array

**Review by siriwatknp — APPROVED** [review]
👍

**Comment by kayb-proxora** [comment]
@michelengelen Would it be possible to include this fix in the latest v8 as well?

**Comment by michelengelen** [comment]
> @michelengelen Would it be possible to include this fix in the latest v8 as well?

Hi @kayb-proxora, thanks for the nudge!

We looked into whether this could be cherry-picked to v8, but unfortunately it's not straightforward enough for us to take on. The commit conflicts with 23 files in the v8 branch. 21 of those are locale files with trivial but tedious conflicts in commented-out template code, and 4 are actual logic files. The most notable one is `useGridRowCount.ts`, where v8's implementation has diverged enough from master that the fix would need to be manually adapted rather than applied verbatim.

Since we're now on v9 and only do clean cherry-picks to older branches, this one falls outside of what we can support. Upgrading to v9 would be the recommended path to get this fix.

**Comment by kayb-proxora** [comment]
@michelengelen Thank you very much for the detailed explanation. In this case, we will schedule a migration to V9.
