### PR TITLE
[charts] Support `slots`/`slotProps` for the tooltip

### LINKED ISSUE #10497: [Charts] If a chart is in a drawer, it's tooltip is not visible (it is below the drawer)
### Steps to reproduce

Link to live example: 
https://codesandbox.io/s/recursing-oskar-73gcnt?file=/Demo.js

Steps:
1. Create a drawer from MUI
2. Place a chart in the drawer
3. Hover over a point within the chart: the tooltip will not appear. Yet if you inspect the elements tree in the browser, you will see that the tooltip does appear. But it does so below the drawer and is therefore not visible for the user.

I have set the opacity of the drawer to 0.5 so you can see that the tooltip is behind it.

### Current behavior

When a chart is used in a drawer, it's tooltip will show below the drawer's paper root.

### Expected behavior

The tooltip of a chart should be always visible regardless of it's parent component.

### Context

I have a use case where I have a table with data. The user can open the rows in order to see details and some data within a chart for each row.
I want my user's focus to be entirely on the chart, similar to the drawers we see in Google Cloud Console (when for example editing some data from a table - it opens in a drawer while the rest of the content is slightly greyed out with an overlay).
Therefore I have used a drawer for this purpose. So far I cannot figure out a fix - and maybe I should have used a custom Paper component with transition. But the drawer seemed very convenient at first because it looks like exactly the element I require.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Chrome and Codesandbox, not OS relevant
```
</details>

**Search keywords**: drawer, tooltip, chart

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #10497

### CODE REVIEW

File: packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx [hunk 1]
```diff
@@ -1,8 +1,9 @@
 import * as React from 'react';
 import PropTypes from 'prop-types';
 import { unstable_composeClasses as composeClasses } from '@mui/utils';
-import { Popper } from '@mui/base/Popper';
+import Popper, { PopperProps } from '@mui/material/Popper';
```
Comment (LukasTy) [inline packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx:4]: Was there any problem with the `base` Popper when doing this change? 🤔

**Review by LukasTy — COMMENTED** [review]
The change makes sense, but IMHO, it should not be a problem in the first place as it's not in case of pickers: https://github.com/mui/mui-x/issues/10035
WDYT? 🤔

File: packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx (hunk 1 above)
Comment (alexfauquette) [reply packages/x-charts/src/ChartsTooltip/ChartsTooltip.tsx:4]: Thanks for the catch. I tried to use the new [Popup](https://mui.com/base-ui/react-popup/) but I reverted to material instead of base

**Comment by alexfauquette** [comment]
Nice point. I made the `zIndex` correct as in the date picker. And fixed your feedback

**Comment by evgeniiarts** [comment]
@alexfauquette Thank you kindly for fixing the issue, in my opinion this works now intuitively and as expected from a developer perspective.
And sorry for the delayed response, I was not on Github lately. 

Great to see how swiftly and effectively you people react to raised issues.
