### PR TITLE
[charts-pro] Fix voronoi interaction with zoom

### LINKED ISSUE #18908: [charts-pro] Weird behavior when finding closest point in zoomed in scatter chart
The closest point logic seems to be selecting a random point when no points are visible. 

https://github.com/user-attachments/assets/51cfac8b-4998-4cfb-98f2-dcfdee2b7641

In this case, we should either show no tooltip (because there are no visible points) or show the tooltip of the closest point (even if invisible). It seems our current logic is the former, so we should keep it.

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #18908

The issue came from a trick that works for static charts but not zoom ones.

To avoid having to manage coordinates all points outside of the drawing area were moved to a "trash coordinate" at (-drawing_width, -drawing_height) such that any moint inside the drawing area will be closer to the pointer than the trash coordinate.

Here is an illustration of the transformation where from the real data (the left chart) we move all points outside the drawing are (black rectangle) to the trash point (the red one) and give this representation to the delauney computation

image

If you have no data in the drawing area, the closer point is the trash point which contains all the scatter point. So Delauney retruns the first data point.

This PR effectively remove the data point that are outside of the drawing area and store an index mappping from delauney  to series

### CODE REVIEW

File: packages/x-charts/src/internals/plugins/featurePlugins/useChartVoronoi/useChartVoronoi.ts [hunk 1]
```diff
@@ -18,7 +18,25 @@ import {
...
+  /**
+   * The series id
+   */
+  seriesId: SeriesId;
+  /**
+   * The first index in the voronoi data that is about this series.
+   */
+  startIndex: number;
+  /**
+   * The first index in the voronoi data that is outside this series.
```
Comment (bernardobelchior) [inline packages/x-charts/src/internals/plugins/featurePlugins/useChartVoronoi/useChartVoronoi.ts:31]: Nit: since this is called "endIndex", it should probably represent the last index, not the first one of the next series. 

No need to fix it now as it is already like this and I might need to change it for the performance improvement.

Comment (alexfauquette) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartVoronoi/useChartVoronoi.ts:31]: It's to have the same behavior as the `slice(start, end)` method. `start` is included, and `end` is excluded

Comment (bernardobelchior) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartVoronoi/useChartVoronoi.ts:31]: Yeah, but at the moment it seems the `end` is included?

Comment (alexfauquette) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartVoronoi/useChartVoronoi.ts:31]: Would it be clearer if I use the same expression as in the `slice()` [docs from MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice)?

```suggestion
   * The index at which the series end in voronoid data.
   * Ends up to but not including `endIndex`.
```
