### PR TITLE
[DataGridPremium] Fix cell selection throwing index error on second page and beyond

### LINKED ISSUE #10260: Error when Clicking Last Row Hyperlink in DataGrid Premium with Pagination
### Order ID

69192

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Issue Description:
When using the DataGrid Premium with pagination, clicking the hyperlink in the first column of the last row on the last page results in an exception error. This issue does not occur when pagination is not used.

Steps to Reproduce:

Enable pagination in the DataGrid Premium.
Navigate to the last page of the pagination.
Click the hyperlink in the first column of the last row.
Expected Behavior:
The hyperlink should function correctly, and no exceptions should be thrown.

Actual Behavior:
An exception error is encountered when clicking the hyperlink in the described scenario as shown in the below image
Screenshot 2023-09-07 at 4 01 35 PM

Additional Information:

**Column Array:** 
 const columns: GridColDef[] = [
      {
        field: 'col1',
        headerName: 'Project id',
        flex: 0.7,
        align: 'left',
        headerAlign: 'left',
        headerClassName: `${classes.headerColumn}`,
        renderCell: (params) => {
          console.log(params.row?.templateId);
          localStorage.removeItem('projectStatus');
          localStorage.removeItem('templateId');
          localStorage.removeItem('templateName');
          return (
            <a
              href={`/create-rfi/project-summary?view=true&&id=${params.id}`}
              className={`app-theme-color cursorPointer`}
            >
              <strong>{params.value}</strong>
            </a>
          );
        },
        hideable: false,
      },
      {
        field: 'col2',
        headerName: 'Project name',
        flex: 1.5,
        align: 'left',
        headerAlign: 'left',
        headerClassName: `${classes.headerColumn}`,
      },
      {
        field: 'col3',
        headerName: 'Role',
        flex: 1,
        align: 'left',
        headerAlign: 'left',
        headerClassName: `${classes.headerColumn}`,
      },
      {
        field: 'col4',
        headerName: 'Active suppliers',
        flex: 1,
        align: 'center',
        headerAlign: 'left',
        headerClassName: `${classes.headerColumn}`,
      },
      {
        field: 'col5',
        headerName: 'Date',
        flex: 1,
        align: 'left',
        headerAlign: 'left',
        headerClassName: `${classes.headerColumn}`,
      },
      {
        field: 'col6',
        headerName: 'Status',
        flex: 1,
        align: 'left',
        headerAlign: 'left',
        headerClassName: `${classes.headerColumn}`,
      },
      {
        field: 'col7',
        align: 'right',
        headerName: 'Actions',
        flex: 0.5,
        headerAlign: 'left',
        headerClassName: `${classes.headerColumn}`,
      },
    ];
    
**Rows Array:**
 [{
    "id": "f99c8bf430833",
    "col1": "23008",
    "col2": "add",
    "col3": "Owner",
    "col4": "-",
    "col5": "07-Sep-2023",
    "col6": "created",
    "testStatus": "Not created",
    "status": "created"
}]. This is just one array object out of all the array of objects

**Props Used in DataGrid:** 
   <DataGridPremium
            style={{
              width: '100%',
              border: 0,
              borderRadius: 0,
              padding: '0.75rem',
              paddingRight: '0.5rem',
              height: displayImage ? '' : '80vh',
            }}
            classes={{
              columnHeader: `app-theme-background-light app-theme-color-white`,
              sortIcon: classes.whiteColour,
              menuIconButton: classes.whiteColour,
            }}
            rows={rows}
            columns={columns}
            ref={ref}
            filterModel={filterModel}
            onFilterModelChange={(newFilterModel) =>
              setFilterModel(newFilterModel)
            }
            slotProps={{ panel: { anchorEl } }}
            experimentalFeatures={{ clipboardPaste: true }}
            disableRowSelectionOnClick
            unstable_cellSelection
            initialState={{
              pagination: {
                paginationModel: { pageSize: 10, page: 0 },
              },
            }}
            pagination={rows?.length ? true : false}
            getRowClassName={(params) =>
              params.indexRelativeToCurrentPage % 2 === 0 ? 'greyRows' : 'odd'
            }
            onClipboardCopy={(copiedString) => console.log(copiedString)}
            unstable_ignoreValueFormatterDuringExport
            localeText={{ noRowsLabel: '' }}
            pageSizeOptions={[10, 25, 50]}
            disableAggregation
          />

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### LINKED ISSUE #10777: [DataGrid] Error thrown when clicking last row of the data starting from the 2nd page
### Steps to reproduce

This is a reproducible [codesandbox](https://codesandbox.io/embed/cocky-jones-l7mnvn?fontsize=14&hidenavigation=1&theme=dark)
1. Enable pagination and `unstable_cellSelection` in the DataGrid Premium.
2. Click next page.
3. Click on any cells of the last row.

### Current behavior

Exception thrown

image

### Expected behavior

Cell should be able to click without exceptions

### Context

Previous issue #10260 seems to be closed and inactive but I could produce the same error with different approach.

I would like to implement clipboard copy & pasting with client mode pagination so I could add new data in new rows and paginate. Without `unstable_cellSelection` I wouldn't able to achieve cell selection for copying / pasting.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: datagrid pagination cell selection unstable_cellSelection
**Order ID**: 76422

### PR DESCRIPTION
**Pull request by MBilalShafi**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fix #10777
- Before: https://codesandbox.io/embed/cocky-jones-l7mnvn?fontsize=14&hidenavigation=1&theme=dark
- After: https://codesandbox.io/s/reverent-aj-6r83vw

Fix #10260

### CODE REVIEW

File: packages/grid/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts [hunk 1]
```diff
@@ -486,7 +488,9 @@ export const useGridCellSelection = (
         newClasses.push(gridClasses['cell--rangeTop']);
       }
 
-      if (rowIndex < visibleRows.range.lastRowIndex) {
+      // https://github.com/mui/mui-x/issues/10777
+      const rowIndexRelativeToRange = rowIndex + paginationModel.page * paginationModel.pageSize;
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts:492]: Alternatively, we could compute this by:
```suggestion
      const rowIndexRelativeToRange = rowIndex + visibleRows.range.firstRowIndex;
```
Not sure how reliable this will be though.

**Review by cherniavskii — APPROVED** [review]
Great! 🎉
