### PR TITLE
[fields] Fix input refocusing after clearing a value

### LINKED ISSUE #12574: [fields] The input loses focus after pressing on clear button
### Steps to reproduce

Link to live example: (required)
https://mui.com/x/react-date-pickers/date-picker/#clearing-the-value
Steps:
1. Type in some date
2. Press on clear button
3. Try to type again
4. Grey text (placeholder?) is shown and you couldn't type in numbers. Only for some amount of time (~2 seconds) or until some other random event - couldn't figure it out yet

Focusing on something else and focusing the field again helps

https://github.com/mui/mui-x/assets/4249082/abd2e69d-e474-43e4-af5c-727cdfc14e68

### Current behavior

Grey text (placeholder?) is shown and you couldn't type in new date

### Expected behavior

Value is changable

### Context

Issue appeared after upgrading to v7.0.0 from ^6.19.2. Before upgrade everything works as expected

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser: latest Chrome
```
</details>

**Search keywords**: clear, focus lost, couldn't type

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #12574 

- Add e2e tests asserting that current focusing behavior after clearing value is broken
- Call `isFieldFocused` function instead of only checking it's existence

### CODE REVIEW

File: packages/x-date-pickers/src/internals/hooks/useField/useField.ts [hunk 1]
```diff
@@ -275,10 +275,12 @@ export const useField = <
     event.preventDefault();
     onClear?.(event, ...(args as []));
     clearValue();
-    setSelectedSections(sectionOrder.startIndex);
 
-    if (!interactions.isFieldFocused) {
+    if (!interactions.isFieldFocused()) {
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useField/useField.ts:279]: :facepalm: :facepalm: :facepalm: :facepalm: :facepalm: :facepalm: :facepalm: :facepalm: 

Thanks for fixing it

**Review by flaviendelangle — APPROVED** [review]

File: packages/x-date-pickers/src/internals/hooks/useField/useField.ts (hunk 1 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/useField/useField.ts:279]: P.S. Didn't want to risk it again, that's why I took a bit longer than expected. 🙈 
At first, I tried tailoring a unit test—which proved to be nearly impossible to achieve reliably.
Then, I resorted to writing an e2e test, which also posed challenges due to Firefox's `getSelection` behavior... 🙈 🤷
