### PR TITLE
[DataGridPro] Improve column grouping and column pinning friendship

### LINKED ISSUE #7041: [data grid] Is there a way to fix this right pin issue when using column grouping?
### Order ID 💳

51218

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Weird behavior  when pinning any column to the right under the last column group

Codesandbox straight from [MUI's Defining Column Group demo](https://mui.com/x/react-data-grid/column-groups/#define-column-groups)

https://user-images.githubusercontent.com/15187771/204563407-fb6c743a-049d-479b-a8b8-bb65ba64a9fc.mov

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 12.6
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.0
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3 
    @emotion/styled: ^11.8.1 => 11.9.3 
    @mui/base:  5.0.0-alpha.85 
    @mui/icons-material:  5.8.4 
    @mui/lab:  5.0.0-alpha.86 
    @mui/material:  5.8.4 
    @mui/private-theming:  5.8.4 
    @mui/styled-engine:  5.8.0 
    @mui/styles:  5.8.4 
    @mui/system:  5.8.4 
    @mui/types:  7.1.4 
    @mui/utils:  5.10.6 
    @mui/x-data-grid:  5.17.9 
    @mui/x-data-grid-pro:  5.17.9 
    @mui/x-date-pickers:  5.0.0-alpha.6 
    @mui/x-license-pro:  5.17.0 
    @types/react:  17.0.47 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript:  4.7.4 
```
</details>

### LINKED ISSUE #9286: DataGridPro: Pinned column header (that's not in a group) covers other non-grouped column headers next to it (when there are some other column groups)
### Order ID or Support key 💳 (optional)

66195

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/stoic-morning-cnpmzf?file=/demo.tsx

Steps:
Pin either of the first non-group columns in DataGridPro and see how they are covering with white section other non-group header cells next to them.
 
It is also reproducible on the [MUI docs page](https://mui.com/x/react-data-grid/column-groups/#column-reordering).

### Current behaviour 😯
https://github.com/mui/mui-x/assets/55355611/2fc4f21a-933b-4142-ae9e-2cddeca49132

When you have some column groups but first columns on the left are actually non-group columns (at least 2 non-group columns in a row) if you pin any of the start non-group columns, their header cells expand so that they cover other non-group header cells next to them.

### Expected behaviour 🤔

Pinned columns should work exactly the same way as when there are no groups or when you pin a non-group column from bet

ween groups.

### Context 🔦

We're now extensively using DataGridPro with both grouping and pinning functionality, so we need to having this stuff work together in a very flexible way.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: macOS 13.3.1
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.4
```
</details>

### PR DESCRIPTION
**Pull request by MBilalShafi**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #7041 
- Before: https://codesandbox.io/s/serene-feather-rrdrg7?file=/Demo.tsx
- After: https://codesandbox.io/s/tender-mccarthy-znsr3c?file=/Demo.tsx

Fixes #9286 
- Before: https://codesandbox.io/s/loving-borg-zqh3rc?file=/demo.tsx
- After: https://codesandbox.io/s/dark-moon-ffqz28?file=/package.json

### CODE REVIEW

File: packages/grid/x-data-grid/src/hooks/features/columnGrouping/useGridColumnGrouping.ts [hunk 1]
```diff
@@ -63,6 +63,8 @@ export const columnGroupsStateInitializer: GridStateInitializer<
   const columnGroupsHeaderStructure = getColumnGroupsHeaderStructure(
     columnFields,
     unwrappedGroupingModel,
+    // @ts-expect-error Move this part to `Pro` package
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/hooks/features/columnGrouping/useGridColumnGrouping.ts:66]: To avoid these we had to duplicate a lot of logic in Pro package (by copying this hook and updating the section which handles `pinning` part)
Suggestions are welcome!

Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/columnGrouping/useGridColumnGrouping.ts:66]: Why are these comments using `@ts-...`?

Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/hooks/features/columnGrouping/useGridColumnGrouping.ts:66]: Because we are trying to access part of the state in MIT package which is typed in the Pro package (column pinning), so the typescript complains, in order to make him happy I have to use `@ts-expect-error`
I guess we are following the same for some other flags too which have to access in a lower package.

**Review by romgrk — APPROVED** [review]

File: packages/grid/x-data-grid/src/hooks/features/columnGrouping/useGridColumnGrouping.ts (hunk 1 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/features/columnGrouping/useGridColumnGrouping.ts:66]: Ideally, we would use a pipe processor to spread the logic between packages, but I think it's not worth it in this case since it will bring unnecessary complexity 👍🏻

**Review by cherniavskii — APPROVED** [review]

File: packages/grid/x-data-grid/src/hooks/features/columnGrouping/useGridColumnGrouping.ts (hunk 1 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/hooks/features/columnGrouping/useGridColumnGrouping.ts:66]: Exactly, in this case, and other cases like keyboard navigation for header filters for example, I am thinking of extracting most of the functions from the actual hook (as reusable ones) and having dedicated hooks in each package with the differences added on top of it.

It might be tougher to achieve but a step forward towards https://github.com/mui/mui-x/issues/7358
