### PR TITLE
[DataGrid] Add support for margin between rows

### LINKED ISSUE #2144: [DataGrid] Allow to add margin between rows
When applying custom style to rows, e.g. specifying row height and margin-bottom to achieve extra space between rows, the last rows of the grid are not visible, because the parent container has a height that seems to be calculated without taking the extra margin into account.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

In the example on https://codesandbox.io/s/quizzical-meitner-cuff9 I styled the rows to have an extra green border after being selected and also 5px margin on the bottom so that the space between the rows is bigger. Without the `disableExtendRowFullWidth` attribute the right border isn't visible probably also because of the precalculated size of the parent containers. When using `disableExtendRowFullWidth` attribute, I am able to work around this issue with right border by specifying fixed size of the grid's parent element, but since I am trying to make the whole thing responsive, this isn't the best solution.

## Expected Behavior 🤔

I would like to be able to customize the height, borders and spacing of rows without breaking the layout.

## Steps to Reproduce 🕹

https://codesandbox.io/s/quizzical-meitner-cuff9

Steps:

1. Select a row or two
2. Scroll down to the end of the grid

## Context 🔦

We're trying to adapt the component as close to the UI/UX requirements as possible.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

Browser used: Chrome..
  
System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.19.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.67)

</details>

## Order id 💳

Still doing POC without having a license.

### PR DESCRIPTION
**Pull request by m4theushw**
Closes #2144 

Preview: https://deploy-preview-3848--material-ui-x.netlify.app/components/data-grid/rows/#row-spacing

In #3387, we added a pre-processor to allow to customize the final row height. This way, we got almost for free the support for custom margins between rows. This PR proposes to add a new `getRowSpacing` prop where developers can pass the top and bottom margin values for each row. Since `border` also behaves like `margin` the prop doesn't really add the margins, but takes these values into account when calculating the content size and which rows to render during scroll.

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/utils/useCurrentPageRows.ts [hunk 1]
```diff
@@ -41,11 +42,19 @@ export const useCurrentPageRows = (
 ) => {
   const response = getCurrentPageRows(apiRef, props);
 
+  const lookup = React.useMemo(() => {
```
Comment (flaviendelangle) [inline packages/grid/_modules_/grid/hooks/utils/useCurrentPageRows.ts:45]: If you put non-trivial computation here they will be computed for each hook that calls `useCurrentPageRows` and will not take advantage of the selector memoization.
For very large list of rows I think this is to be avoided.

If you are only using it in 1 or 2 `useCurrentPageRows`, I would move the `lookup` computation to the hook / components which calls `useCurrentPageRows`.

If you are using it in more, I would move the `lookup` computation in `getCurrentPageRows` in selectors (one for the paginated version and one for the non-paginated version).

File: packages/grid/_modules_/grid/models/gridRows.ts [hunk 2]
```diff
@@ -80,7 +80,16 @@ export type GridRowsLookup = Record<GridRowId, GridRowModel>;
  */
 export type GridRowId = string | number;
 
-export type GridRowEntry = { id: GridRowId; model: GridRowModel };
+export interface GridRowEntry {
+  /**
+   * The row model of the row that the current cell belongs to.
```
Comment (flaviendelangle) [inline packages/grid/_modules_/grid/models/gridRows.ts:85]: We are using this interface in a lot of selectors that are not related to cells.
Could we rephrase these descriptions to be more generic ?

File: packages/grid/_modules_/grid/models/params/gridRowParams.ts [hunk 3]
```diff
@@ -29,7 +29,21 @@ export interface GridRowParams<R extends GridRowModel = GridRowModel> {
...
 
 /**
- * Object passed as parameter in the row getRowHeight callback.
+ * Object passed as parameter in the row `getRowClassName` callback prop.
+ */
+export interface GridRowClassNameParams extends GridRowParams {
+  /**
+   * Whether this row is the first visible or not.
+   */
+  isFirstVisible: boolean;
```
Comment (flaviendelangle) [inline packages/grid/_modules_/grid/models/params/gridRowParams.ts:38]: Right now we mostly use the term "visible" to refer to the rows after sorting + filtering + children colapsing processed.

From what I understand, the `isFirstVisible` and `isLastVisible` is used here to talk about the paginated rows (and when pagination is off, all the sorted + filtered + collapsed rows).

I don't think we should use `visible` here.
Not in v5 because it conflicts with other usages of the term `visible` and makes it incoherent.
Not in v6 because I think we should stop using the term `visible` which is not clear (as we saw that each dev in the team has a different definition based on the day and the use case).

______

I would be in favor of using the term `page` even if the pagination is off since it's like it we had `pageSize=Infinity` and pagination on.

So `isFirstInPage` for instance.

But if you have a better idea I'm open to suggestion.
Just let's avoid term that can be understood in various ways.

**Review by joserodolfofreitas — APPROVED** [review]
Nice feature. 
I'm adding a suggestion to make the example more granular.

**Comment by siriwatknp** [comment]
👋 The [migration PR](https://github.com/mui/mui-x/pull/3730) has been merged.

Please follow these steps to make sure that the contents are all updated. (Sorry for the inconvenience)

1. pull latest master from upstream to your branch
2. if your PR has changes on the `*.md` or demo files, you are likely to encounter conflict because all of them have been moved to the new folder.
   2.1 revert the change on those markdown files you did
   2.2 pull latest master from upstream (you should not see conflict)
   2.3 make the changes again at `docs/data/material/*`
3. run `yarn docs:api`
    - you might see the changes in `docs/pages/material/api/*` if your PR touches some of the components
    - it is okay if there is no changes

If you are struggle with the steps above, feel free to tag @siriwatknp

File: packages/grid/_modules_/grid/models/params/gridRowParams.ts (hunk 3 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/models/params/gridRowParams.ts:38]: By using "visible" I wanted to adopt the same concept from [AG Grid](https://ag-grid.com/react-data-grid/grid-api/#reference-displayedRows). The visible (or displayed) rows are those you can see by only scrolling the grid. In the past it was heavily misused but I would ignore and start using "visible" in this way from now.

Comment (flaviendelangle) [reply packages/grid/_modules_/grid/models/params/gridRowParams.ts:38]: If we are acting that `visible` should mean "accessible by scroll"
Then could we 

1. Create an issue for renaming everything to this new nomenclature or at least put a line in #3287 
2. Be more precise in the description of this prop, at least until v6 `Wheter this row is the first row reachable by scrolling or not.` or something similar. So that we are sure people understand `visible` in the correct way

**Review by flaviendelangle — COMMENTED** [review]
What is the reason behind the public api you made for this feature ?
Why the user have tu set the CSS margin itself ? Couldn't we do it automatically, so he just have to set a row spacing and everything works ?

I feel like your approach is very flexible but not very intuitive. 
For the variable row height for instance, we are not asking to the user to set the CSS height himself.

**Comment by m4theushw** [comment]
> Why the user have tu set the CSS margin itself ? Couldn't we do it automatically, so he just have to set a row spacing and everything works ?

It's because border also behaves like a margin but it can have color and style. If we set everything automatically `getRowSpacing` would have to return a object of CSS properties, and for border we need to parse the value to extract the width.

File: docs/src/pages/components/data-grid/rows/rows.md [hunk 4]
```diff
@@ -100,6 +100,15 @@ If you need some rows to have different row heights this can be achieved using t
 > <DataGridPro getRowHeight={handleGetRowHeight} />
 > ```
 
+## Row spacing
+
+By using the `getRowSpacing` prop you can specify the vertical space between rows.
+This prop is called with a [`GridRowSpacingParams`](/api/data-grid/grid-row-spacing-params/) object.
+Observe that the value specified will only be used internally to calculate which rows to render during scroll and for space allocation.
```
[the remark this answers is not in the document]
Comment (m4theushw) [reply docs/src/pages/components/data-grid/rows/rows.md]: I added a better explanation of how to use the new prop and that `getRowClassName` should be also used.

**Comment by flaviendelangle** [comment]
Could we have something like `getRowSpacing: (params: XXX) => ({ type: 'margin' | 'border', value: number })`
And set `borderWidth` if `type === 'border'` or `margin` if `type === 'margin'` ?

I would like to have the insight of the rest of the team.
Because the current api feels weird to me.

File: packages/grid/x-data-grid/src/internals/hooks/features/rows/useGridRowsMeta.ts [hunk 5]
```diff
@@ -44,16 +48,11 @@ export const useGridRowsMeta = (
...
-      paginationMode,
-    });
-
     apiRef.current.setState((state) => {
       const positions: number[] = [];
       const densityFactor = gridDensityFactorSelector(state, apiRef.current.instanceId);
       const currentRowHeight = gridDensityRowHeightSelector(state, apiRef.current.instanceId);
-      const currentPageTotalHeight = rows.reduce((acc: number, row) => {
+      const currentPageTotalHeight = currentPage.rows.reduce((acc: number, row) => {
         positions.push(acc);
```
Comment (alexfauquette) [inline packages/grid/x-data-grid/src/internals/hooks/features/rows/useGridRowsMeta.ts:56]: Should the position start with `initialHeights.spacingTop`?

**Review by alexfauquette — COMMENTED** [review]
It seems there is a problem with the detail panel. The gap between the row and the detail increase along rows
image

https://codesandbox.io/s/create-react-app-with-typescript-forked-olcpk5?file=/src/App.tsx

One thing I do not understand is why specifying `spacingTop` and `spacingBottom` if at the end we just sum those two values

File: packages/grid/x-data-grid/src/internals/models/params/gridRowParams.ts [hunk 6]
```diff
@@ -29,7 +29,21 @@ export interface GridRowParams<R extends GridRowModel = GridRowModel> {
 }
 
 /**
- * Object passed as parameter in the row getRowHeight callback.
+ * Object passed as parameter in the row `getRowClassName` callback prop.
```
Comment (DanailH) [inline packages/grid/x-data-grid/src/internals/models/params/gridRowParams.ts:32]: Can we do something like:
```
interface GridRowPossitionVisibility {
  /**
   * Whether this row is the first visible or not.
   */
  isFirstVisible: boolean;
  /**
   * Whether this row is the last visible or not.
   */
  isLastVisible: boolean;
}
```
and then use that to build the 2 new interfaces?

File: packages/grid/x-data-grid/src/internals/hooks/features/rows/useGridRowsMeta.ts (hunk 5 above)
Comment (m4theushw) [reply packages/grid/x-data-grid/src/internals/hooks/features/rows/useGridRowsMeta.ts]: I didn't understand. This `positions.push(acc);` is adding the position of the previous row. Note that `positions[0]` is always 0.

File: packages/grid/x-data-grid/src/internals/models/params/gridRowParams.ts (hunk 6 above)
Comment (m4theushw) [reply packages/grid/x-data-grid/src/internals/models/params/gridRowParams.ts]: Done.

**Comment by m4theushw** [comment]
> It seems there is a problem with the detail panel. The gap between the row and the detail increase along rows

@alexfauquette True, I was not adding the top space when positioning the detail panel. Now it's fixed. However, I noted that adding bottom margin with `getRowSpacing` to a row that also has a detail panel doesn't work because both features relay on `marginBottom`. Changing to border also doesn't work. I added a paragraph explaining this limitation to the docs. If someone complains about it there's a possible solution which is to create a "fake margin" on each row by using a div.

---

> Could we have something like getRowSpacing: (params: XXX) => ({ type: 'margin' | 'border', value: number })

@flaviendelangle I added a new `rowSpacingType` prop to configure to use border or margin. That way users can only use one type.

File: packages/grid/x-data-grid/src/internals/hooks/features/rows/useGridRowsMeta.ts (hunk 5 above)
Comment (alexfauquette) [reply packages/grid/x-data-grid/src/internals/hooks/features/rows/useGridRowsMeta.ts]: My idea was the following:
If the first row has a `margin-top: 5px` which in your system correspond to `initialHeights.spacingTop=5` then the firs row position should reflect this margin with `positions[0] = '5px'`

Comment (m4theushw) [reply packages/grid/x-data-grid/src/internals/hooks/features/rows/useGridRowsMeta.ts]: With `initialHeights.spacingTop > 0` the `positions` array is more like how many pixels should I scroll to reach the beginning of the top margin of a row. Although visually the margin is outside the row, here it's part of the row so I think makes sense to keep 0 as the initial value. I don't want to change because I also don't know the consequences of this yet. But one problem of not discounting the margin is that when navigating with the keyboard it scroll up to the top margin. Maybe we could have a option in `scrollToIndexes` to control de behavior. #4013 asks for more parameters.

File: packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts [hunk 7]
```diff
@@ -142,12 +143,24 @@ export const useGridRows = (
...
+  const currentPage = useCurrentPageRows(apiRef, props);
 
   const getRow = React.useCallback<GridRowApi['getRow']>(
     (id) => gridRowsLookupSelector(apiRef)[id] ?? null,
     [apiRef],
   );
 
+  const lookup = React.useMemo(
+    () =>
+      currentPage.rows.reduce((acc, { id }, index) => {
```
Comment (flaviendelangle) [inline packages/grid/x-data-grid/src/hooks/features/rows/useGridRows.ts:155]:
```suggestion
      currentPage.rows.reduce<Record<GridRowId, number>>((acc, { id }, index) => {
```

This should also work by the way

File: packages/grid/x-data-grid/src/models/api/gridSortApi.ts [hunk 8]
```diff
@@ -53,6 +53,7 @@ export interface GridSortApi {
    * The index is based on the sorted but unfiltered row list.
    * @param {GridRowId} id The `GridRowId` of the row.
    * @returns {number} The index of the row.
+   * @deprecated Use `unstable_getRowIndexRelativeToCurrentPage` instead.
```
Comment (flaviendelangle) [inline packages/grid/x-data-grid/src/models/api/gridSortApi.ts:56]: We advise users to use a private API instead of a public one ?
Does this mean that `unstable_getRowIndexRelativeToCurrentPage` will become public at some point ?

Comment (m4theushw) [reply packages/grid/x-data-grid/src/models/api/gridSortApi.ts]: It would be public in v6 and replace `getRowIndex`. I made it public now.

File: docs/data/data-grid/rows/RowMarginGrid.tsx [hunk 9]
```diff
@@ -0,0 +1,32 @@
...
+    };
+  }, []);
+
+  return (
+    <div style={{ height: 400, width: '100%' }}>
+      <DataGrid
+        {...data}
+        getRowSpacing={getRowSpacing}
+        sx={{
+          '& .MuiDataGrid-row': {
```
[the remark this answers is not in the document]
Comment (m4theushw) [reply docs/data/data-grid/rows/RowMarginGrid.tsx]: I changed to `gridClasses`. Note that no other demo is using it. If we use it here we should start using it in the future demos to keep consistency.

**Review by flaviendelangle — APPROVED** [review]

File: docs/data/data-grid/rows/RowMarginGrid.js [hunk 10]
```diff
@@ -0,0 +1,32 @@
...
+  }, []);
+
+  return (
+    <div style={{ height: 400, width: '100%' }}>
+      <DataGrid
+        {...data}
+        getRowSpacing={getRowSpacing}
+        sx={{
+          [`& .${gridClasses.row}`]: {
+            bgcolor: (theme) => (theme.palette.mode === 'dark' ? '#000' : '#efefef'),
```
[the remark this answers is not in the document]
Comment (m4theushw) [reply docs/data/data-grid/rows/RowMarginGrid.js]: Either `#000` or `theme.palette.background.default` mix with the page background and I can't see the difference. I changed to other colors.

File: docs/data/data-grid/rows/rows.md [hunk 11]
```diff
@@ -100,6 +100,36 @@ If you need some rows to have different row heights this can be achieved using t
...
+```tsx
+<DataGrid
+  getRowSpacing={...}
+  rowSpacingType="border"
+  sx={{ '& .MuiDataGrid-row': { borderTopColor: 'yellow', borderTopStyle: 'solid' } }}
+/>
+```
+
+> ⚠ Adding a bottom margin or border to rows that also have a [detail panel](/components/data-grid/group-pivot/#master-detail) is not recommended.
+> As alternative, increase the top spacing of the next row to compensate.
```
[the remark this answers is not in the document]
Comment (m4theushw) [reply docs/data/data-grid/rows/rows.md]: It's simpler to always compensate. I improved the explanation. I think that if the user wants to apply a margin when the panel is closed and once it opens change the margin he is doing something very specific to explain in a warning message.

[the remark this answers is not in the document]
Comment (alexfauquette) [reply docs/data/data-grid/rows/rows.md]: It is the word "compensate" that miss leads me. I thought it means users have to compensate for the size of the expended detail panel. An explanation like that could be enough.

> Adding a bottom margin or bottom border to rows that also have a [detail panel](/components/data-grid/group-pivot/#master-detail) is not recommended because the detail panel relays on the bottom margin to work.
> 
> As an alternative, only use the top spacing to define the space between rows.

**Review by alexfauquette — APPROVED** [review]

File: docs/data/data-grid/rows/rows.md (hunk 11 above)
[the remark this answers is not in the document]
Comment (m4theushw) [reply docs/data/data-grid/rows/rows.md]: Updated.
