### PR TITLE
[DataGrid] Use the same bundling scripts as the core repository

### LINKED ISSUE #50: [RFC] Use Babel
In order to build on top of the same foundation and to save time, I think that we should reuse the existing build steps of the main repository by leveraging Babel. It appears that reproducing the same building pipeline will provide the maximum consistency. For instance

- [x] we would like to remove the requirement from yarn link & yarn build in order to work on the documentation or the storybook.
- [ ] we will likely want to keep the same production optimizations: https://github.com/mui-org/material-ui/blob/2ed7b23dc35cf72265065506e406427dbcf06a77/babel.config.js#L35.
- [ ] we would like to rely on our [browserlist](https://github.com/mui-org/material-ui-x/blob/HEAD/.browserslistrc) to guarantee browser support, something TypeScript doesn't support microsoft/TypeScript#19183
- [ ] we don't want to minimize the source in the npm package

### LINKED ISSUE #51: [RFC] Use same tsconfig.json as main repository
It appears we already have a [tsconfig.json file in the main repository](https://github.com/mui-org/material-ui/blob/2ed7b23dc35cf72265065506e406427dbcf06a77/tsconfig.json) that differs [from the one here](https://github.com/mui-org/material-ui-x/blob/071759e8a74fbb852270896a09c2de05bce9bc5f/tsconfig.json), let's make sure we share the same rules.

### LINKED ISSUE #924: [RFC] Better isolate DataGridPro from DataGrid
## Summary 💡

The two components should be better isolated. `XGrid` should be able to grow in complexity and package size without harming the bundle size of `DataGrid`. In the current configuration, both packages have the exact same size

## Motivation 🔦

- `DataGrid` is in competition in the space of a similar open-source data grid. The bundle size is one of the dimensions developers look at. I think that the biggest decision influence happens when one package looks disproportionally bigger than an equivalent solution. So this issue might be the one that has the most influence on this matter. I'm not sure that we will need to the same depth as we did in the main repository.

  If you look at the bundle size of ag-Grid, you can see that it can quickly get out of hand: [ag-grid-community](https://bundlephobia.com/result?p=ag-grid-community): 193 kB gzipped. They have tried to isolate features, but the core seems to be about the same size: [@ag-grid-community/core](https://bundlephobia.com/result?p=@ag-grid-community/core): 191 kB gzipped (it's only with the enterprise features that it seems to make a difference).

- The license should be better isolated. It's not OK to have all the content of `/packages/grid/_modules_` exported under an MIT licensed package.
- This effort should allow us to make the grid, and its feature more composable. It would be great to invest time in a plugin system. Some prior-arts: https://datatables.net/manual/plug-ins/.

### LINKED ISSUE #3967: [DataGrid] Have to use `import type {}` to import theme augmentation, which is not needed for the core packages
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

ModuleNotFoundError

Could not find module in path: '@mui/x-data-grid/themeAugmentation' relative to '/src/App.tsx'

### Expected behavior 🤔

Can import TypeScript theme augmentation.

### Steps to reproduce 🕹

[CodeSandbox](https://codesandbox.io/s/datagrid-v5-quick-start-forked-01ktk1?file=/src/App.tsx)

### Context 🔦

Cannot customize data grid in theme. https://github.com/mui/mui-x/issues/1755

If I look at differences between `@mui/lab` and `@mui/x-data-grid`, `@mui/lab` does provide an empty index.js file in `themeAugmentation`, while `@mui/x-data-grid/themeAugmentation` does not. Could be related, could be irrelevant.

### Your environment 🌎

see codesandbox

### Order ID 💳 (optional)

_No response_

### LINKED ISSUE #4024: [core] `yarn docs:api` ignores some interfaces
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

`yarn docs:api` (specifically `buildInterfacesDocumentation.ts`) seems to ignore some of the interfaces like `GridApi`, `GridCellParams` and `GridColDef`.
When one of those interfaces change, docs are not updated.

<details>
  <summary>Ouput</summary>

```sh
$ yarn docs:api
yarn run v1.22.17
$ yarn docs:api:build
$ cross-env BABEL_ENV=development babel-node -i "/node_modules/(?!@mui)/" -x .ts,.tsx,.js ./docs/scripts/api/buildApi.ts
[BABEL] Note: The code generator has deoptimised the styling of /Users/andrew/workspace/material-ui-x/node_modules/typescript/lib/typescript.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/andrew/workspace/material-ui-x/node_modules/lodash/lodash.js as it exceeds the max of 500KB.
Could not resolve "@mui/monorepo/packages/typescript-to-proptypes/src" in file /Users/andrew/workspace/material-ui-x/node_modules/@mui/monorepo/docs/src/modules/utils/parseStyles.ts.
Built API docs for GridRowParams
Built API docs for GridCsvExportOptions
Built API docs for GridPrintExportOptions
Built API docs for GridFilterModel
Built API docs for GridFilterItem
Built API docs for GridFilterOperator
Built JSON file for GridSelectionApi
Built JSON file for GridFilterApi
Built JSON file for GridSortApi
Built JSON file for GridPaginationApi
Built JSON file for GridCsvExportApi
Built JSON file for GridScrollApi
Built JSON file for GridEditingApi
Built JSON file for GridRowGroupingApi
Built JSON file for GridColumnPinningApi
Built JSON file for GridDetailPanelApi
Built JSON file for GridPrintExportApi
Built JSON file for GridDisableVirtualizationApi
Built API docs for GridRowParams
Built API docs for GridCsvExportOptions
Built API docs for GridPrintExportOptions
Built API docs for GridFilterModel
Built API docs for GridFilterItem
Built API docs for GridFilterOperator
Built JSON file for GridSelectionApi
Built JSON file for GridFilterApi
Built JSON file for GridSortApi
Built JSON file for GridPaginationApi
Built JSON file for GridCsvExportApi
Built JSON file for GridScrollApi
Built JSON file for GridEditingApi
Built JSON file for GridRowGroupingApi
Built JSON file for GridColumnPinningApi
Built JSON file for GridDetailPanelApi
Built JSON file for GridPrintExportApi
Built JSON file for GridDisableVirtualizationApi
Built API docs for DataGrid
Built API docs for DataGridPro
Built API docs for DataGrid
Built API docs for DataGridPro
Built events file
Built events file
✨  Done in 21.87s.
```
</details>

### Expected behavior 🤔

`yarn docs:api` builds all interfaces declared in `buildInterfacesDocumentation.ts`

### Steps to reproduce 🕹

Steps:

1. Add any property to `GridColDef`, for example:
```ts
/**
 * Test
 */
test?: boolean;
```
2. Build api docs: `yarn docs:api`
3. Observe no changes in `grid-col-def.md`

### Context 🔦

I've discovered it in https://github.com/mui/mui-x/pull/4020 where I added a property to `GridColDef`

Tested on latest master branch (`af155b`)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
Part of #18
Fixes #50
Fixes #51
Fixes #924 
Fixes #3967
Fixes #4024

Follow up on #3953

[Codesandbox for DataGridPro](https://codesandbox.io/s/datagridpro-v5-quick-start-forked-l4w31y?file=/package.json)

[Doc preview](https://deploy-preview-3965--material-ui-x.netlify.app/api/data-grid/grid-api/), you can see the "pro" icon on the methods only accessible on the pro version of the interface.

_____

- [x] Tested on Create React App / Webpack (dev and prod builds) by @flaviendelangle 
- [x] Tested on Next JS (dev and prod builds) by @cherniavskii 
- [x] Tested on Vite JS by @cherniavskii 
- [x] Tested on Codesandbox by @flaviendelangle 

- [x] Documentation accessible 
- [x] Storybook accessible

### CODE REVIEW

File: packages/grid/x-data-grid/src/internals/models/api/gridColumnApi.ts [hunk 1]
```diff
@@ -47,12 +47,12 @@ export interface GridColumnApi {
...
    * @deprecated Use `apiRef.current.updateColumns` instead.
    */
-  updateColumn: (col: GridColDef) => void;
+  updateColumn: <Api extends GridApiCommon = GridApiCommon>(col: GridColDef<Api>) => void;
   /**
    * Updates the definition of multiple columns at the same time.
    * @param {GridColDef[]} cols The new column [[GridColDef]] objects.
    */
-  updateColumns: (cols: GridColDef[]) => void;
+  updateColumns: <Api extends GridApiCommon = GridApiCommon>(cols: GridColDef<Api>[]) => void;
```
Comment (flaviendelangle) [inline packages/grid/x-data-grid/src/internals/models/api/gridColumnApi.ts:55]: For column methods I added the API as a generic because I can't easily now which version of `GridApi` is used from inside one of `GridApi` methods.

File: docs/scripts/api/buildInterfacesDocumentation.ts [hunk 2]
```diff
@@ -138,9 +178,18 @@ function generateMarkdownFromProperties(
   object.properties.forEach((property) => {
     const defaultValue = property.tags.default?.text?.[0].text;
 
+    let planImg: string;
+    if (property.projects.includes('x-data-grid')) {
+      planImg = '';
+    } else if (property.projects.includes('x-data-grid-pro')) {
+      planImg = ' <span class="plan-pro"></span>';
```
Comment (cherniavskii) [inline docs/scripts/api/buildInterfacesDocumentation.ts:185]: I like the idea of having icons here as well!
Can we also link to a pro plan page, as we do for example [here](https://mui.com/components/data-grid/selection/#multiple-row-selection)?
And maybe adding `title="Pro plan"`, so it's clear what that icon means

Comment (flaviendelangle) [reply docs/scripts/api/buildInterfacesDocumentation.ts]: Done

The `title="Pro plan"` could also be interested when we use those icons for doc sections.

File: packages/storybook/tsconfig.json [hunk 3]
```diff
@@ -4,7 +4,8 @@
     "outDir": "build/",
     "rootDirs": ["src"],
     "types": ["node", "requestidlecallback"],
-    "sourceMap": true
```
Comment (cherniavskii) [inline packages/storybook/tsconfig.json:7]: DataGrid doesn't work in storybook in PR's netlify deployment: https://deploy-preview-3965--material-ui-x.netlify.app/storybook
Screenshot 2022-02-22 at 11 28 09

Comment (cherniavskii) [reply packages/storybook/tsconfig.json:7]: RELEASE_INFO wasn't replaced in storybook:
Screenshot 2022-02-22 at 11 59 06

---

It's not an issue in packages available on CodeSandbox CI:

Screenshot 2022-02-22 at 12 00 00

Comment (flaviendelangle) [reply packages/storybook/tsconfig.json:7]: Probably a wrong config on `babel.config.js`

File: tsconfig.json [hunk 4]
```diff
@@ -1,23 +1,13 @@
 {
+  "extends": "@mui/monorepo/tsconfig.json",
   "compilerOptions": {
```
Comment (cherniavskii) [inline tsconfig.json:3]: I've started to experience this issue in VSCode:
> To enable project-wide JavaScript/TypeScript language features, exclude large folders with source files that you do not work on.

I've experienced it in `material-ui` repository, but never in `material-ui-x`.
I've found this suggestion: https://github.com/microsoft/TypeScript/issues/12750#issuecomment-265806038 and adding proper excludes seem to solve the issue for me:

```suggestion
  "exclude": ["**/.*/*", "**/build/*", "**/node_modules/*", "docs/export/*"],
  "compilerOptions": {
```

Let's try it and if it works then we can move it upstream

Comment (cherniavskii) [reply tsconfig.json:3]: Spoke too soon I guess - the issue is still there :/

File: packages/grid/x-data-grid-pro/tsconfig.json [hunk 5]
```diff
@@ -1,9 +1,7 @@
 {
   "extends": "../../../tsconfig.json",
   "compilerOptions": {
-    "noEmit": true,
-    "allowJs": true,
-    "types": ["mocha", "node", "chai", "chai-dom"]
+    "types": ["react", "mocha", "node"]
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/tsconfig.json:4]: `yarn typescript` fails on my machine:

```sh
$ yarn typescript
yarn run v1.22.17
$ lerna run --no-bail --parallel typescript
lerna notice cli v4.0.0
lerna info Executing command in 6 packages: "yarn run typescript"
docs: $ tsc -p tsconfig.json
@mui/x-data-grid: $ tsc -p tsconfig.json
@mui/x-data-grid-generator: $ tsc -p tsconfig.json
@mui/x-data-grid-pro: $ tsc -p tsconfig.json
storybook: $ tsc -p tsconfig.json
@mui/x-license-pro: $ tsc -p tsconfig.json
@mui/x-data-grid: src/internals/utils/createSelector.test.ts(12,37): error TS2339: Property 'toWarnDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/internals/utils/createSelector.test.ts(15,44): error TS2339: Property 'toWarnDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/cells.DataGrid.test.tsx(38,37): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/cells.DataGrid.test.tsx(50,37): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/cells.DataGrid.test.tsx(64,35): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/cells.DataGrid.test.tsx(77,35): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/cells.DataGrid.test.tsx(96,35): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/cells.DataGrid.test.tsx(120,8): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/columnHeaders.DataGrid.test.tsx(37,46): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/columnHeaders.DataGrid.test.tsx(49,46): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/components.DataGrid.test.tsx(61,37): error TS2339: Property 'attr' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/components.DataGrid.test.tsx(75,33): error TS2339: Property 'attr' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/components.DataGrid.test.tsx(127,8): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/components.DataGrid.test.tsx(148,12): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/filtering.DataGrid.test.tsx(61,10): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/keyboard.DataGrid.test.tsx(508,25): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(119,59): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(128,50): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(175,12): error TS2339: Property 'toWarnDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(214,12): error TS2339: Property 'toWarnDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(228,12): error TS2339: Property 'toWarnDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(250,12): error TS2339: Property 'toWarnDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(308,23): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(344,23): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(378,29): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(442,29): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(474,29): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(538,29): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(564,29): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(604,29): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(617,29): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(658,29): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(667,29): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(686,29): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(839,10): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(863,10): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/layout.DataGrid.test.tsx(972,38): error TS2339: Property 'toHaveComputedStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/pagination.DataGrid.test.tsx(344,10): error TS2339: Property 'toWarnDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/pagination.DataGrid.test.tsx(354,10): error TS2339: Property 'toWarnDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/pagination.DataGrid.test.tsx(362,10): error TS2339: Property 'toWarnDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/pagination.DataGrid.test.tsx(518,72): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/pagination.DataGrid.test.tsx(520,72): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/rows.DataGrid.test.tsx(108,31): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/rows.DataGrid.test.tsx(109,31): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/rows.DataGrid.test.tsx(110,35): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/rows.DataGrid.test.tsx(142,10): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/selection.DataGrid.test.tsx(419,32): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/selection.DataGrid.test.tsx(420,36): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/selection.DataGrid.test.tsx(421,34): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/selection.DataGrid.test.tsx(425,34): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/selection.DataGrid.test.tsx(428,34): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/selection.DataGrid.test.tsx(430,32): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/selection.DataGrid.test.tsx(431,36): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/selection.DataGrid.test.tsx(513,69): error TS2339: Property 'attr' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/selection.DataGrid.test.tsx(519,69): error TS2339: Property 'attr' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/selection.DataGrid.test.tsx(536,14): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/selection.DataGrid.test.tsx(700,10): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/selection.DataGrid.test.tsx(712,14): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/sorting.DataGrid.test.tsx(495,10): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/toolbar.DataGrid.test.tsx(60,45): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/toolbar.DataGrid.test.tsx(64,46): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/toolbar.DataGrid.test.tsx(86,45): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/toolbar.DataGrid.test.tsx(90,46): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/toolbar.DataGrid.test.tsx(103,45): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/toolbar.DataGrid.test.tsx(107,46): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/toolbar.DataGrid.test.tsx(120,45): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/toolbar.DataGrid.test.tsx(124,46): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid: src/tests/toolbar.DataGrid.test.tsx(254,22): error TS2339: Property 'toHaveFocus' does not exist on type 'Assertion'.
@mui/x-data-grid: error Command failed with exit code 2.
@mui/x-data-grid: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(72,36): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(74,34): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(77,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(85,36): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(87,34): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(96,36): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(99,34): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(109,33): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(115,31): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(116,30): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(125,33): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(131,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(140,33): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(162,30): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(197,30): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(226,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(227,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(236,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(237,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(241,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(242,30): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(251,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(252,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(265,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(266,30): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(280,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(285,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(295,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(296,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(305,26): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(308,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(309,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(310,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(319,26): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(322,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(323,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(333,26): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(344,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(345,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(361,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(362,30): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(363,26): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(378,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(379,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(380,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(398,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(399,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(400,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(418,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(419,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(420,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(441,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(442,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(463,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(464,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(483,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(484,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(505,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(506,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(553,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(555,26): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(587,30): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(589,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(591,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(607,30): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(609,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(612,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(633,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(634,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(635,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(659,41): error TS2339: Property 'toHaveFocus' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(756,31): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(761,29): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(762,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(781,31): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(786,29): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(787,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(856,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(899,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(902,30): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/cellEditing.DataGridPro.test.tsx(904,30): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnHeaders.DataGridPro.test.tsx(170,53): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnHeaders.DataGridPro.test.tsx(173,53): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnHeaders.DataGridPro.test.tsx(175,57): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(77,75): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(78,76): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(79,74): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(82,71): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(83,72): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(84,70): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(94,71): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(95,72): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(96,70): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(98,75): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(99,76): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(100,74): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(112,24): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(119,24): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(131,32): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(137,32): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(147,26): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(154,26): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(155,31): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(165,26): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(172,26): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(173,31): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(183,55): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columnPinning.DataGridPro.test.tsx(184,55): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(101,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(102,29): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(122,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(123,29): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(169,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(170,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(174,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(175,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(186,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(187,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(197,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(198,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(209,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(210,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(214,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(215,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(226,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(227,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(231,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(232,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(243,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(244,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(254,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(255,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(266,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(267,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(277,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(278,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(289,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(290,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(294,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(295,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(306,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(307,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(317,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(318,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(329,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(339,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(345,40): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/columns.DataGridPro.test.tsx(390,8): error TS2339: Property 'toWarnDev' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/components.DataGridPro.test.tsx(37,72): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/detailPanel.DataGridPro.test.tsx(36,23): error TS2339: Property 'toHaveComputedStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/detailPanel.DataGridPro.test.tsx(45,65): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/detailPanel.DataGridPro.test.tsx(47,23): error TS2339: Property 'toHaveComputedStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/detailPanel.DataGridPro.test.tsx(95,39): error TS2339: Property 'toHaveComputedStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/detailPanel.DataGridPro.test.tsx(99,39): error TS2339: Property 'toHaveComputedStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/detailPanel.DataGridPro.test.tsx(362,31): error TS2339: Property 'toHaveComputedStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(119,34): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(120,30): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(167,34): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(168,30): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(200,34): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(201,30): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(248,34): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(249,30): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(283,35): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(284,36): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(312,60): error TS2339: Property 'toHaveFocus' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(339,31): error TS2339: Property 'toHaveFocus' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(363,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(367,41): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(390,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(394,41): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(433,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(464,30): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(540,63): error TS2339: Property 'toHaveFocus' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(631,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(682,63): error TS2339: Property 'toHaveFocus' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(825,44): error TS2339: Property 'toHaveFocus' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/editComponents.DataGridPro.test.tsx(855,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/events.DataGridPro.test.tsx(219,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/events.DataGridPro.test.tsx(235,30): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/export.DataGridPro.test.tsx(644,10): error TS2339: Property 'toWarnDev' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/layout.DataGridPro.test.tsx(61,55): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/layout.DataGridPro.test.tsx(62,55): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/layout.DataGridPro.test.tsx(77,59): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/layout.DataGridPro.test.tsx(125,27): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/layout.DataGridPro.test.tsx(131,27): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/layout.DataGridPro.test.tsx(184,27): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/layout.DataGridPro.test.tsx(190,27): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/layout.DataGridPro.test.tsx(224,38): error TS2339: Property 'toHaveComputedStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/reorder.DataGridPro.test.tsx(319,31): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/reorder.DataGridPro.test.tsx(320,35): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(67,35): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(69,31): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(74,35): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(79,31): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(89,31): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(90,31): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(91,35): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(92,35): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(93,35): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(94,35): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(106,26): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(119,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(132,29): error TS2339: Property 'toHaveFocus' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(148,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(149,28): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(157,50): error TS2339: Property 'toHaveFocus' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(221,34): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(222,35): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(245,34): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(246,35): error TS2339: Property 'attribute' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(274,30): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(275,26): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(368,26): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowEditing.DataGridPro.test.tsx(432,35): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowGrouping.DataGridPro.test.tsx(742,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowGrouping.DataGridPro.test.tsx(746,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowGrouping.DataGridPro.test.tsx(753,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowGrouping.DataGridPro.test.tsx(1017,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowGrouping.DataGridPro.test.tsx(1018,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowGrouping.DataGridPro.test.tsx(1022,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowGrouping.DataGridPro.test.tsx(1023,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowGrouping.DataGridPro.test.tsx(1030,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rowGrouping.DataGridPro.test.tsx(1031,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rows.DataGridPro.test.tsx(106,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rows.DataGridPro.test.tsx(107,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rows.DataGridPro.test.tsx(111,28): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rows.DataGridPro.test.tsx(112,32): error TS2339: Property 'class' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rows.DataGridPro.test.tsx(398,32): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rows.DataGridPro.test.tsx(444,32): error TS2339: Property 'attr' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rows.DataGridPro.test.tsx(448,32): error TS2339: Property 'attr' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rows.DataGridPro.test.tsx(461,35): error TS2339: Property 'attr' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rows.DataGridPro.test.tsx(466,35): error TS2339: Property 'attr' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rows.DataGridPro.test.tsx(488,34): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rows.DataGridPro.test.tsx(509,34): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/rows.DataGridPro.test.tsx(526,34): error TS2339: Property 'text' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/selection.DataGridPro.test.tsx(122,41): error TS2339: Property 'attr' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/selection.DataGridPro.test.tsx(132,10): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/selection.DataGridPro.test.tsx(198,41): error TS2339: Property 'attr' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/treeData.DataGridPro.test.tsx(398,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/treeData.DataGridPro.test.tsx(400,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/treeData.DataGridPro.test.tsx(407,38): error TS2339: Property 'toHaveInlineStyle' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: src/tests/treeData.DataGridPro.test.tsx(509,10): error TS2339: Property 'toErrorDev' does not exist on type 'Assertion'.
@mui/x-data-grid-pro: error Command failed with exit code 2.
@mui/x-data-grid-pro: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! Received non-zero exit code 2 during execution
lerna success run Ran npm script 'typescript' in 6 packages in 15.4s:
lerna success - docs
lerna success - storybook
lerna success - @mui/x-license-pro
lerna success - @mui/x-data-grid-generator
lerna success - @mui/x-data-grid-pro
lerna success - @mui/x-data-grid
error Command failed with exit code 2
```

File: babel.config.js [hunk 6]
```diff
@@ -59,12 +71,13 @@ module.exports = function getBabelConfig(api) {
         version: '^7.4.4',
       },
     ],
-    [
-      'babel-plugin-transform-react-remove-prop-types',
-      {
-        mode: 'unsafe-wrap',
-      },
-    ],
+    // [
```
[the remark this answers is not in the document]
Comment (m4theushw) [reply babel.config.js:74]: Yes, it can save bandwidth in production by removing the prop-types. Without it, the prop-types are always bundled.

File: tsconfig.json (hunk 4 above)
Comment (cherniavskii) [reply tsconfig.json:3]: Using this for now - seems to work better

```suggestion
  "exclude": ["**/.*/**/*", "**/build/**/*", "**/node_modules/**/*", "docs/export/**/*"],
  "compilerOptions": {
```

File: packages/grid/x-data-grid-pro/tsconfig.json (hunk 5 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid-pro/tsconfig.json:4]: I think it's caused by your `  "exclude": ["**/.*/**/*", "**/build/**/*", "**/node_modules/**/*", "docs/export/**/*"],`

File: packages/storybook/tsconfig.json (hunk 3 above)
Comment (flaviendelangle) [reply packages/storybook/tsconfig.json:7]: I updated the Storybook config, it should solve the problem
I'll test once deployed

File: packages/grid/x-data-grid-pro/tsconfig.json (hunk 5 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/tsconfig.json:4]: Right, we probably need to include `@mui/monorepo`, but exclude all other `node_modules`

File: packages/grid/x-data-grid/package.json [hunk 7]
```diff
@@ -3,19 +3,17 @@
   "version": "5.5.1",
   "description": "The community edition of the data grid component (MUI X).",
   "author": "MUI Team",
-  "main": "build/index-cjs.js",
-  "module": "build/index-esm.js",
-  "types": "build/x-data-grid.d.ts",
+  "main": "src/index.ts",
```
Comment (m4theushw) [inline packages/grid/x-data-grid/package.json:6]:
```suggestion
  "main": "src/index.js",
```

Comment (flaviendelangle) [reply packages/grid/x-data-grid/package.json:6]: Why ? Pre-build there is no `src/index.js`
The build process changes those fields, the `package.json` released has a `main` and a `module` pointing to various bundles

File: packages/grid/x-data-grid/src/internals/public.ts [hunk 8]
```diff
@@ -0,0 +1,12 @@
+// Only export the variable and types that should be publicly exposed and re-exported from `@mui/x-data-grid-pro`
+export * from './components/public';
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/public.ts:2]: I can revert the logic yes

File: packages/grid/x-data-grid/src/internals/models/api/gridColumnApi.ts (hunk 1 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/models/api/gridColumnApi.ts:55]: Not sure to understand your poin here.
If the method does not have the generic to pass it to the interface, how does the user override it ?

File: packages/grid/x-data-grid/package.json (hunk 7 above)
Comment (m4theushw) [reply packages/grid/x-data-grid/package.json:6]: If it will add the correct extension during build, then there're other `package.json`s pointing to a non-existing `index.js`, e.g. `packages/grid/x-data-grid-pro/package.json`.

Comment (flaviendelangle) [reply packages/grid/x-data-grid/package.json:6]: Indeed, fixed for `x-data-grid-pro`, `x-data-grid-generator` and `x-license-pro`

File: packages/storybook/tsconfig.json (hunk 3 above)
Comment (flaviendelangle) [reply packages/storybook/tsconfig.json:7]: Fixed

File: packages/grid/x-data-grid/src/internals/public.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/public.ts:2]: @m4theushw small point to consider here `packages/x-data-grid/src/internals/index.ts` must be the private version 
So that we can import it from `@mui/x-data-grid/internals`

If we switch the other `index.ts` to be the public exports, it would be a small inconsistency.

Do you still want to do the switch ?

File: packages/grid/x-data-grid/src/internals/models/api/gridColumnApi.ts (hunk 1 above)
Comment (m4theushw) [reply packages/grid/x-data-grid/src/internals/models/api/gridColumnApi.ts:55]: We are repeating `<Api extends GridApiCommon = GridApiCommon>` in almost every method. I was hoping that we could move the generic to the interface but it didn't work. Even passing the correct API in `GridApiPro` it goes back to `GridApiCommunity`. We'll be able to simplify the types once we remove `api` from the params.

```diff
diff --git a/packages/grid/x-data-grid/src/internals/models/api/gridColumnApi.ts b/packages/grid/x-data-grid/src/internals/models/api/gridColumnApi.ts
index 8865f822c..d51a02a8c 100644
--- a/packages/grid/x-data-grid/src/internals/models/api/gridColumnApi.ts
+++ b/packages/grid/x-data-grid/src/internals/models/api/gridColumnApi.ts
@@ -6,23 +6,23 @@ import type { GridApiCommon } from './gridApiCommon';
  * The column API interface that is available in the grid [[apiRef]].
  * TODO: Differentiate interfaces based on the plan
  */
-export interface GridColumnApi {
+export interface GridColumnApi<Api extends GridApiCommon = GridApiCommon> {
   /**
    * Returns the [[GridColDef]] for the given `field`.
    * @param {string} field The column field.
    * @returns {{GridStateColDef}} The [[GridStateColDef]].
    */
-  getColumn: <Api extends GridApiCommon = GridApiCommon>(field: string) => GridStateColDef<Api>;
+  getColumn: (field: string) => GridStateColDef<Api>;
```

Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/models/api/gridColumnApi.ts:55]: Yes, this generic is a pain.
I think we could stop typing the `api` in the params once it's deprecated.

File: packages/grid/x-data-grid/src/internals/public.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (m4theushw) [reply packages/grid/x-data-grid/src/internals/public.ts:2]: It confuses me because we have a `public.ts` file inside an `internals` folder. We import from `internals` even things already public. I'm favor of using `index.ts` for public exports because it's how JavaScript modules work. Based on that, I have the following proposal:

1. Move everything inside `packages/grid/x-data-grid/src/internals/` one level up. `packages/grid/x-data-grid/src/internals/gridClasses.ts` becomes `packages/grid/x-data-grid/src/gridClasses.ts`.
2. Re-exports the public modules in `packages/grid/x-data-grid/src/index.ts`
3. Inside `packages/grid/x-data-grid/src/internals/index` we export only the true internal modules.

> I prefer the public, because filename index.ts is common, whereas with public.ts I would think "Be careful, this is the public export, are you sure it is the interface you want to maintain?"

In the past we had the bad habit of including everything inside `index.ts`. Because of that, many things were exported by mistake. Now we tend to include in it only things used in a demo or that users will certainly want. I think with the export snapshot we don't have this problem anymore.

[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/public.ts:2]: But how do you handle deep colocated elements ?
For instance in `packages/grid/x-data-grid/src/internals/hooks/features/columns/gridColumnsInterfaces.ts` we have both public and private interfaces.
And splitting those files into two distincts folders seems very complicated to me.

Making `index.ts` public and `private.ts` private is fine for me.
But making `@mui/x-data-grid/internals` not containing the public stuff is a lot of work and I don't see the point?

[the remark this answers is not in the document]
Comment (m4theushw) [reply packages/grid/x-data-grid/src/internals/public.ts:2]: > But how do you handle deep colocated elements ?

By individually exporting the interfaces, instead of usuing `export * from`. We need to enable `isolatedModules` for that.

```diff
diff --git a/packages/grid/x-data-grid/src/internals/hooks/features/columns/index.ts b/packages/grid/x-data-grid/src/internals/hooks/features/columns/index.ts
index 524807ffb..6d4f470ce 100644
--- a/packages/grid/x-data-grid/src/internals/hooks/features/columns/index.ts
+++ b/packages/grid/x-data-grid/src/internals/hooks/features/columns/index.ts
@@ -1,4 +1,9 @@
 export * from './gridColumnsSelector';
-export * from './gridColumnsInterfaces';
+export {
+  GridColumnLookup,
+  GridColumnsState,
+  GridColumnsInitialState,
+  GridColumnVisibilityModel,
+} from './gridColumnsInterfaces';
 export * from './gridColumnsUtils';
 export * from './useGridColumns';
```

Keeping a file only for public/private exports works but I think it requires more mental effort to ignore the `index.ts` when we need to think if something will be included in the public API or not. I initially proposed to rename to `private.ts` but maybe this will only avoid a little bit the confusion.

[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/public.ts:2]: >  We need to enable isolatedModules for that.

Don't think we need it, we are already exporting it like that on some files.

But that's not my main concern.
It more that I don't get the folder architecture you want.
In which file would be `GridColumnsRawState` for instance ? It's private, must be accessible from `@mui/x-data-grid-pro`, but highly linked to public elements that are currently in the same file.

Would you put it in an entirely different file, in `src/internals/....` (whereas the publci would be in `src/hooks/...`.
Or would you have `src/internals/index.ts` export directly from the deep file where is curently is ?


Note that `src/internals/index.ts` is needed instead of `src/internals.ts` for bundling reason. Even if it's the only file of its directory.

[the remark this answers is not in the document]
Comment (m4theushw) [reply packages/grid/x-data-grid/src/internals/public.ts:2]: > It more that I don't get the folder architecture you want.

```
package.json
src/DataGrid.tsx
src/index <- Exports to be available under @mui/x-data-grid
src/hooks/features/columns/index.ts
src/hooks/features/columns/gridColumnsInterfaces.ts <- GridColumnsRawState is still here
src/internals/index.ts <- Exports to be available under @mui/x-data-grid/internals
```

Contents of `src/hooks/features/columns/index.ts`:

```ts
export * from './gridColumnsSelector';
export * from './gridColumnsInterfaces';
export {
  GridColumnLookup,
  GridColumnsState,
  GridColumnsInitialState,
  GridColumnVisibilityModel,
} from './gridColumnsInterfaces';
export * from './gridColumnsUtils';
export * from './useGridColumns';
```

Contents of `src/internals/index.ts`:

```tsx
exports { GridColumnsRawState } from '../hooks/features/columns/gridColumnsInterfaces';
```

This resembles what we had before the introduction of the `internals` folder. Also, forces us to import true internal things from a different import in DataGridPro.

[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/public.ts:2]: I can't have files at the root of `src`
Otherwise, the core bundling strategy don't work correctly and I get bundle duplication (and React context problems)

So to make things work, I would need to do:

```
package.json
src/DataGrid/DataGrid.tsx <- The folder would also contains `useDataGridProps.ts` and `useDataGridComponent.ts`
src/index.ts <- Exports to be available under @mui/x-data-grid
src/hooks/features/columns/index.ts
src/hooks/features/columns/gridColumnsInterfaces.ts <- GridColumnsRawState is still here
src/internals/index.ts <- Exports to be available under @mui/x-data-grid/internals
```

[the remark this answers is not in the document]
Comment (m4theushw) [reply packages/grid/x-data-grid/src/internals/public.ts:2]: > I can't have files at the root of src

Which type of file can't be at the root of `src`? Your example contains files at this location.

If the structure you proposed can be done I would agree to adopt it. It's flatter than having an `internals` folder wrapping everything. The core bundling process can be improved later to avoid to create a folder for `DataGrid.tsx`.

[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/internals/public.ts:2]: Any file not named `index.ts`
It is the `topLevelPathImportsCanBePackages` condition on the bundling process.
The condition make sense.

File: babel.config.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (m4theushw) [reply babel.config.js:63]: I'm only waiting this comment to addressed to approve. We have lots of prop-types and if developers don't remove them it will be included in the production bundle. Everything else seems good.

**Comment by chess1** [comment]
Hi @flaviendelangle =]
Do you know what is the estimation of this PR to be merged?

I am also having this issue on my end.
Thanks!

**Comment by flaviendelangle** [comment]
@chess1 which issue are you having ?

I hope we will be able to release this week but it's unsure.
These changes are massive and we want to test them a lot.

**Comment by chess1** [comment]
Sorry, relates to https://github.com/mui/mui-x/issues/3967

**Comment by flaviendelangle** [comment]
@chess1 `import type {} from '@mui/x-data-grid/themeAugmentation';` should work

**Comment by flaviendelangle** [comment]
Valided during monday's meeting
