### PR TITLE
[datagrid] Fix typing of GridActionsCellItem

### LINKED ISSUE #4654: Typing of custom component to render in GridActionsCellItem
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Why using version `5.6.1` of `mui-x/data-grid` we were using the `component` prop of the underlying `ButtonBase` component in order to integrate with `react-router` as follows:
```js
<GridActionsCellItem
                        component={RouterLink}
                        to={`/notes`}
                        icon={<NoteIcon/>}
                        label="Notes"
                    />,
```

While Updating to versions older then `5.7.0` we are experiencing typing error stating that `GridActionsCellItem` doesn't have this prop enymore.

I followed the history of this component [here](https://github.com/mui/mui-x/commits/master/packages/grid/x-data-grid/src/components/cell/GridActionsCellItem.tsx) but it seems that nothin relevant has been changed.

I found [this](https://github.com/mui/mui-x/commit/a55478c44364734517f7517072cbba50a9360131) commit containing bundling changes and did manged to find out that the difference between the latest version and the last version that has this feature working is type called `GridActionsCellItem` that has been added to the typing file in addition to `GridActionsCellItemProps`.

### LINKED ISSUE #4656: StaticDateRangePicker orientation prop has no effect
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

By default the StaticDateRangePicker is displayed with 2 calendars side by side (which is landscape orientation).

grafik

If you change the **orientation prop to portrait** the two calendars are still side by side.

grafik

### Expected behavior 🤔

If you change the orientation prop to portrait the calendars should be displayed **one below the other** or the prop should be removed from the component and API reference.

grafik

### Steps to reproduce 🕹

[https://codesandbox.io/s/staticdaterangepickerdemo-material-demo-forked-uor7jq?file=%2Fdemo.js](https://codesandbox.io/s/staticdaterangepickerdemo-material-demo-forked-uor7jq?file=%2Fdemo.js)

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by romgrk**
Fixes #4654

Fix typing, add `component`.

https://github.com/mui/mui-x/issues/4654#issuecomment-1119956263

### CODE REVIEW

File: packages/grid/x-data-grid/src/components/cell/GridActionsCellItem.tsx [hunk 1]
```diff
@@ -8,6 +8,7 @@ import { useGridRootProps } from '../../hooks/utils/useGridRootProps';
 export type GridActionsCellItemProps = {
   label: string;
   icon?: React.ReactElement;
+  component?: React.ElementType;
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/components/cell/GridActionsCellItem.tsx:11]: How about adding a comment to link it to where it comes from
```suggestion
  // https://mui.com/material-ui/api/button-base/#ButtonBase-prop-component
  component?: React.ElementType;
```

**Review by MBilalShafi — APPROVED** [review]

**Review by cherniavskii — APPROVED** [review]
