### PR TITLE
[DataGrid] Refactor row state propagation

### LINKED ISSUE #16170: [data grid] Grid constantly updating a columns width which causes "flickering"
### Steps to reproduce

Steps:
1. [Open this link to live example](https://mui.com/x/react-data-grid/demo/) This is the official Docs page.
2. Reduce the width of the window, and at one point, the Grid starts to "shake".

### Current behavior

https://github.com/user-attachments/assets/699294e8-06ba-446a-9f14-8257397b2773

It happens with Chrome and Firefox too.

### Expected behavior

The Grid changes it's layout when we're resizing the window and stays in that state.

### Context

I think it is only happening when the Grid uses flex column widths.
As you can see on the video, the "Column menu" cell keeps changing between being in one line or two.
If I inspect the DOM, a div with class `MuiDataGrid-scrollbarFiller MuiDataGrid-scrollbarFiller-borderTop` keeps appearing and disappearing.

### Your environment

It is happening with all recent versions locally, and on the Docs page it happens when switching it to v8 alpha as well.
<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.7.1
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 9.12.3 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.265
    Edge: 131.0.2903.147
    Safari: 17.6
  npmPackages:
    @emotion/react:  11.13.0 
    @emotion/styled:  11.13.0 
    @mui/icons-material: ^5.16.11 => 5.16.11 
    @mui/material: ^5.16.11 => 5.16.11 
    @mui/x-data-grid-pro: 7.19.0 => 7.19.0 
    react:  18.2.0 
    react-dom:  18.2.0 
```
</details>

**Search keywords**: data grid, layout, width, flickering

### LINKED ISSUE #16225: [data grid] Deleting a row throws "row id not found" error
### Steps to reproduce

Steps:
1. Open this [link](https://react-bec9us.stackblitz.io/) in your browser
2. Open the console to check error
3. spam the delete button

### Current behavior

As you can see in this video if i press delete button instantaneously then i'm getting "No row with id xxxxxxxxxx found"

https://github.com/user-attachments/assets/eeafa26e-92c7-4048-8298-f6b3f71d7706

Code: https://stackblitz.com/run?file=Demo.js

### Expected behavior

if i delete row instantaneously it should not give error 

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: error on click of delete icon

**Order ID**: 91701

### PR DESCRIPTION
**Pull request by lauri865**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

After some further thoughts on #15616, probably better to try and fix the root cause of the row existence checks instead.

@romgrk, what if anything am I breaking here? Fixes the need for try/catch and out of order state propagation (currently on removing a row, first all the cells re-render to null, then the rows unmount. After this change, a row would be responsible for cells being rendered or not).

Fixes https://github.com/mui/mui-x/issues/16234
Before: https://codesandbox.io/p/sandbox/xenodochial-hooks-t2dymf
After: https://codesandbox.io/p/sandbox/unruffled-bas-pztmw9

Fixes #16181
Fixes #16170
Fixes #16225

Fixes race conditions in updating rows / columns
Fixes row editing state re-rendering all rows, and extracted actual editing state into a selector to avoid it working due to side effects of other selectors 
Fixes columns always being rehydrated on resize (only needed for flex columns)
Fixes pinned columns propagation (happens in one render pass, rather than two)
Fixes `rowSpanning` with pagination being correctly processed on initialization
Fixes serverSide lazy loader incorrectly resetting state / scroll on mount (and a flaky test)
Fixes flaky test with server side aggregation (trying to test for aggregation before data has been loaded)
Fixes autoresize (=expand columns) with pinned columns (previously didn't expand to full width due to wrong `availableWidth` / 'viewPortInnerSize.width' excluding pinned columns)

### Breaking changes

- `viewportInnerSize.width` now includes pinned columns' widths (fixes recursive loops in updating dimensions <-> columns) (Edit: probably should be reclassified as a bugfix, ref: https://github.com/mui/mui-x/pull/15627#issuecomment-2605833070)

### CODE REVIEW

**Comment by lauri865** [comment]
All tests should pass now. To me this approach makes much more sense:
* Baseline row state is owned and provided by rows that render the cells.
* We sprinkle in reactivity to cells based on more atomic selectors, which makes state flow more understandable and debuggable. Currently, all the valueGetters, formatters, etc. have to re-evaluate on each and every state change, which is wasteful.

I was slightly confused why the master detail test started failing, but after looking into it, I'm more worried that it worked the way it did – a breeding ground for race conditions.

Also squeezed in a tiny change that fixes every row selection checkbox re-rendering on every selection model change. Was such a tiny change that I didn't bother making it a new

File: packages/x-data-grid/src/components/GridRow.tsx [hunk 1]
```diff
@@ -277,6 +277,11 @@ const GridRow = React.forwardRef<HTMLDivElement, GridRowProps>(function GridRow(
     rowClassNames.push(rootProps.getRowClassName(rowParams));
   }
 
+  /* Start of rendering */
+  if (!rowNode) {
+    return null;
+  }
+
```
Comment (romgrk) [inline packages/x-data-grid/src/components/GridRow.tsx:284]: Is moving this block required?

I prefer to keep functional components organized as if it were a class component:

```
class GridRow {
  constructor() { ... }
  onClick() { ... }
  getCell() { ... }
  render() {}
}
```

```
function GridRow {
  /* initialization code */
  const onClick = () => { ... }
  const getCell = () => { ... }
  /* render code */
}
```

In particular for large components, it helps readability a lot to keep all render code grouped rather than spread in-between "class methods".

File: packages/x-data-grid/src/hooks/features/rows/useGridParamsApi.ts [hunk 2]
```diff
@@ -55,14 +55,14 @@ export function useGridParamsApi(
...
+    (id, field, rowParam, rowNodeParam) => {
       const colDef = (
         props.unstable_listView
           ? gridListColumnSelector(apiRef.current.state)
           : apiRef.current.getColumn(field)
       ) as GridStateColDef;
-      const row = apiRef.current.getRow(id);
-      const rowNode = apiRef.current.getRowNode(id);
+      const row = rowParam ?? apiRef.current.getRow(id);
+      const rowNode = rowNodeParam ?? apiRef.current.getRowNode(id);
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/rows/useGridParamsApi.ts:65]: I understand why we're adding those params, but this change looks ugly to me, in particular for a function that is part of the public API. How about we add an alternative function on the private API that has the ideal format for the current use-case?

Alternatively, we could also consider skipping this function in `GridCell` and instead copy part of its logic, a bit of code duplication isn't necessarily a bad idea.

Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/rows/useGridParamsApi.ts:65]: This would be a fairly simple change, and would keep the public API clean:
```
getCellParams(id, field) {
  return internal_getCellParams(id, field, getRow(id), getRowNode(id))
}
internal_getCellParams(id, field, row, rowNode) {
  /* ... */
}
```

Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/rows/useGridParamsApi.ts:65]: Very much agree in general. But since it started from a proof of concept, I didn't want to redesign any apis within its scope to make it a non-breaking change initially, which can surely be improved upon, especially if we're open to breaking changes.

I tried to avoid copying the logic into the component, as then it's way too easy to create a divergence in behavior vs. what we expose in the public API.

The 2nd suggestion makes the most sense, as long as the public API calls the internal one, as you suggested.

File: packages/x-data-grid/src/components/GridRow.tsx (hunk 1 above)
Comment (lauri865) [reply packages/x-data-grid/src/components/GridRow.tsx:284]: I like grouping logic, but here the balance is between a pretty large dead code path (defining an anyonymous function that should never be called, unless rowNode exists) vs. grouping logic. Not that clear what's more readable.

After this change, if you were to accidentally remove the rowNode check on component-level, the types would break (good imho), which is better than adding an extra conditional in the getCell that would open up the potential for using the compnent in currently unintended/undesigned ways.

Probably the right question here to ask is why the component needs to (try to) mount without a rowNode to begin with.

File: packages/x-data-grid/src/components/cell/GridCell.tsx [hunk 3]
```diff
@@ -183,33 +190,29 @@ const GridCell = React.forwardRef<HTMLDivElement, GridCellProps>(function GridCe
...
-
-      const result = apiRef.current.getCellParams<any, any, any, GridTreeNodeWithRender>(
-        rowId,
-        field,
-      );
-      result.api = apiRef.current;
-      return result;
-    },
-    objectShallowCompare,
+  const cellParams = apiRef.current.getCellParams<any, any, any, GridTreeNodeWithRender>(
```
[the remark this answers is not in the document]
Comment (lauri865) [reply packages/x-data-grid/src/components/cell/GridCell.tsx:199]: That's actually one of the core changes that is a step in the right direction imho, tried to explain it briefly here: https://github.com/mui/mui-x/pull/15627#issuecomment-2506490646

The current behaviour casts an incredibly wide net to cell-level reactivity that opens it up to race conditions, and prevents from carefully managing state propagation.

Should cell valueGetter and valueFormatter of each cell in the datagrid (renderecontext) re-evaluate whenever any part of grid state changes? (focus, tabindex, rendercontext, etc.?). The currently do, but I would argue they shouldn't. They should only be re-evaluated if the row changes (through edits or row updates).

Imagine if you define a valueFormatter that formats the cell value based on external state. Changing that external state wouldn't update the rendered cell value, but changing the focus or scrolling  a bit would suddenly trigger the cell to re-render with a new value. What?!

Want to understand why the cell re-rendered? Most of the cases, the answer is that getCellParams changed. But why did they change? Good luck understanding that.

So, ideally:
* Row data is provided by row (or editing api)
* Rest of the conditions why the cell should re-render independent of the row should be carefully managed based on atomic selectors. As you can see, the scope currently is not that wide in order to make the tests pass. This should result in both more optimised code as well as more understandable state flow within the grid.

File: packages/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx [hunk 4]
```diff
@@ -19,8 +29,17 @@ const useUtilityClasses = (ownerState: OwnerState) => {
...
+  (expandedRowIds, rowId: GridRowId) => {
+    return expandedRowIds.includes(rowId);
+  },
+);
+
 function GridDetailPanelToggleCell(props: GridRenderCellParams) {
-  const { id, value: isExpanded } = props;
+  const { id, row, api } = props;
+  const rowId = api.getRowId(row);
+  const isExpanded = useGridSelectorV8({ current: api as GridApiPro }, isExpandedSelector, rowId);
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx:42]: Turned this into a selector with argument. Will conflict with #15200, need to coordinate the merge, cc @MBilalShafi.

Comment (romgrk) [reply packages/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx:42]: And it's memoized because `.includes()` is an `O(n)` operation. In the very worst but possible scenario, a user could have all detail panel open, in which case running `.includes()` on each row would be expensive.

Comment (cherniavskii) [reply packages/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx:42]: Looks like a perfect use case for a `Set`, I'll open a PR for v8

File: packages/x-data-grid/src/components/cell/GridCell.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/x-data-grid/src/components/cell/GridCell.tsx]: Okay, this explains why `tabIndex` and `hasFocus` are overridden with the values using `useGridSelector`.

@romgrk Does this make sense to you?

File: packages/x-data-grid/src/components/GridRow.tsx
Comment (cherniavskii) [inline packages/x-data-grid/src/components/GridRow.tsx:1]: @romgrk It should be safe to cherry-pick this PR to v7 once we merge it. Any objections?

File: packages/x-data-grid/src/components/GridRow.tsx (hunk 1 above)
Comment (romgrk) [reply packages/x-data-grid/src/components/GridRow.tsx:284]: > Probably the right question here to ask is why the component needs to (try to) mount without a rowNode to begin with.

Absolutely, the answer is often that the codebase went through many architectural & maintainer changes, and we haven't got around to refactoring everything.

File: packages/x-data-grid/src/components/cell/GridCell.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/x-data-grid/src/components/cell/GridCell.tsx]: > Imagine if you define a valueFormatter that formats the cell value based on external state. Changing that external state wouldn't update the rendered cell value, but changing the focus or scrolling a bit would suddenly trigger the cell to re-render with a new value. What?!

The solution to that would be the approach that we've been introducing of adding some props to the grid's store reactivity model. In this case, `valueFormatter` changes should trigger a store update.

> @romgrk Does this make sense to you?

No, it still doesn't. AFAICT, we would be losing reactivity for the `cellParams` values other than the ones overriden with `useGridSelector` values. And I see some of them for which it would be problematic, e.g. `cellMode` or `isEditable`.

> Want to understand why the cell re-rendered? Most of the cases, the answer is that getCellParams changed. But why did they change? Good luck understanding that.

`getCellParams` has been problematic for a long time (perf-wise and logic-wise), I haven't been able to get rid of it because it would be a breaking change, some of the API uses `GridCellParams`. I think if we want to fix everything cleanly, we need to decompose that function into more logical parts than "here's every bit of cell data". But that would prevent cherry-picking this PR in v7.

Thoughts?

File: packages/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx (hunk 4 above)
Comment (MBilalShafi) [reply packages/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx:42]: @lauri865 #15200 has been merged, kindly rebase with master, you could replace `useGridSelectorV8` with `useGridSelector`.

File: packages/x-data-grid/src/components/cell/GridCell.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (lauri865) [reply packages/x-data-grid/src/components/cell/GridCell.tsx]: I don't think that's quite true that reactivity is lost. A bunch of tests would be failing if that were the case, and cell editing wouldn't work. Any `colDef` update propagates through the row as it is already. Whereas `tabIndex` and `focus` live in unrelated store to columns/rows.

Complete decomposition and granular cell-level reactivity would be a much bigger rewrite. My quick assessment currently is that it's not worth it and would needlessly complicate the code, as there's too many interrelated layers. One would need to ask what are the specific use cases where this would bring meaningful performance gains – I'm personally not seeing it. Maybe editing in theory, but since editing apis expose the whole row for various reasons, that's also not really the case.

[the remark this answers is not in the document]
Comment (lauri865) [reply packages/x-data-grid/src/components/cell/GridCell.tsx]: https://github.com/mui/mui-x/blob/521c696fd095520fb4fdde75b5b42875eb57d4a5/packages/x-data-grid/src/components/GridRow.tsx#L338

[the remark this answers is not in the document]
Comment (romgrk) [reply packages/x-data-grid/src/components/cell/GridCell.tsx]: > A bunch of tests would be failing if that were the case

But I don't think we have 100% test coverage, I think we're in the 80s or 90s.

> I don't think that's quite true that reactivity is lost.

But there is still nothing that explicitly binds cell reactivity to those values; the binding is more like a coincidental side-effect that might break under edge-cases or unrelated refactors. If you ask me why `tabIndex` works, it's because it's bound through `useGridSelector`. If you ask me why `isEditable` works: I don't know. And I feel uncomfortable merging code that works for unknown reasons.

> Complete decomposition and granular cell-level reactivity would be a much bigger rewrite.

It doesn't feel like a big change to me, splitting `getCellParams` into a few small functions is all it would take. I'll take a look at the code again tomorrow to see if I can do something v7-compatible.

[the remark this answers is not in the document]
Comment (lauri865) [reply packages/x-data-grid/src/components/cell/GridCell.tsx]: I agree with the rationale that it shouldn't work due to side-effects. However, `isEditable` is not the case – every input to `isEditable` already triggers a re-render through the row->cell tree. It's not a side-effect by any means, but logical flow of state. Adding a selector as well just introduces extraneous work for no benefit. It will simply trigger a re-render from both the Cell within and Row as well.

On a second look, the only thing I actually think needs extracting out is `cellMode`, which does probably work due to side-effects.

The mental model to me is:
1. Everything in the row -> cell tree that depends directly on the row / cell store shouldn't need additional selectors, as the mere existence of a rendered cell means it's already reactive to these slices of the store.
2. Additional global state that affects how the particular cell is rendered (tabIndex, focus, cellMode) needs selectors.

Does that make sense to you or am I thinking completely wrong here?

[the remark this answers is not in the document]
Comment (lauri865) [reply packages/x-data-grid/src/components/cell/GridCell.tsx]: Or actually, `cellMode` is not even a sideEffect – it depends on the same slice of the state that is already selected in the `GridRow`:
https://github.com/mui/mui-x/blob/2700d7e093c64873ac8fd5af5b58e22fefa11f28/packages/x-data-grid/src/components/GridRow.tsx#L346

`editCellState` prop:
https://github.com/mui/mui-x/blob/2700d7e093c64873ac8fd5af5b58e22fefa11f28/packages/x-data-grid/src/components/GridRow.tsx#L322

`getCellMode` prop depends on the same slice of the state:
https://github.com/mui/mui-x/blob/2700d7e093c64873ac8fd5af5b58e22fefa11f28/packages/x-data-grid/src/hooks/features/editing/useGridCellEditing.ts#L254-L261

So, there are two options:
1. `cellMode` should be a prop of a cell
2. `editRowsState` selector should be removed from the row, and there should be a `editCellState` selector withing `GridCell`. On first look, I don't see why the whole row needs to re-render in response to that, since it's only used to pass a prop to cells, so it could be handled within cells themselves.

[the remark this answers is not in the document]
Comment (romgrk) [reply packages/x-data-grid/src/components/cell/GridCell.tsx]: As long as it's an explicit reactive binding (through a prop or through a selector) I'm happy with that, but option 2 sounds better. I didn't touch the editing code when I did the reactivity refactor so there's leftover stuff from the old "reactivity" architecture (re-render everything anytime anything changes).

Once the editing state is split into an `editCellState` selector, all that is left to do would be to split `value` and `formattedValue` logic, and we could get rid of `getCellParams` in `GridCell`. The other values (`id, field, row, rowNode, colDef`) are all available through props.

If you want to go ahead with that please do, otherwise I'll see if I can complete this tomorrow. Btw we appreciate all the PRs you submitted, we're a bit short on time with v8 preparation and we've been slow to review & merge them, but they're all great.

File: packages/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx (hunk 4 above)
Comment (lauri865) [reply packages/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx]: done

File: packages/x-data-grid/src/components/cell/GridCell.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (lauri865) [reply packages/x-data-grid/src/components/cell/GridCell.tsx]: Fixed it up now. Seems to work well. There was one thing that seems to have worked due to side-effects (already before this PR) in the GridRow, moved it to a discrete selector:
https://github.com/mui/mui-x/blob/33cc4c95a262da6953510b339c4916fa3d565873/packages/x-data-grid/src/components/GridRow.tsx#L127

There are some additional re-renderings that can be fixed when stopping editing that should speed up editing in large grids, but that should be done when other PRs have been merged around memoization + GridRoot + `forwardRef` patch.

I'm a bit reluctant to drop `getCellParams` altogether in `GridCell` as it opens up an easy divergence between the public API and internal logic. I refactored it a bit to make sure we don't do any unnecessary operations there though, but still keep a solid contract. Unless we need to extract `value` and `formattedValue` logic into selector hooks, I don't really see the point either. And I don't currently see a reason why we would need to use hooks there. If we do, we should come up with a test case that it solves, otherwise it's probably just redundant operations.

File: packages/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx [hunk 5]
```diff
@@ -19,8 +29,17 @@ const useUtilityClasses = (ownerState: OwnerState) => {
   return composeClasses(slots, getDataGridUtilityClass, classes);
 };
 
+const isExpandedSelector = createSelectorMemoized(
+  gridDetailPanelExpandedRowIdsSelector,
+  (expandedRowIds, rowId: GridRowId) => {
+    return expandedRowIds.has(rowId);
+  },
+);
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/components/GridDetailPanelToggleCell.tsx:37]: Now that we use a `Set` for selection state, we can replace `createSelectorMemoized` with `createSelector`.

File: scripts/x-data-grid-premium.exports.json [hunk 6]
```diff
@@ -451,6 +452,7 @@
   { "name": "GridPanelWrapper", "kind": "Variable" },
   { "name": "GridPanelWrapperProps", "kind": "Interface" },
   { "name": "GridParamsApi", "kind": "Interface" },
+  { "name": "GridParamsPrivateApi", "kind": "Interface" },
```
Comment (romgrk) [inline scripts/x-data-grid-premium.exports.json:455]: Probably shouldn't be exported publically.

Comment (lauri865) [reply scripts/x-data-grid-premium.exports.json:455]: Is there a convention to prevent it from being exported yet have it co-located with the public interface? Not entirely sure what this file does to be honest (haven't dug into it), but also saw `GridRowProPrivateApi` as a part of it, which doesn't show up in any docs.

Comment (romgrk) [reply scripts/x-data-grid-premium.exports.json:455]: AFAIU, this is auto-generated from the exports available at `@mui/x-data-grid{,-pro,-premium}`, so anything exported from the root `index.ts(x)` ends up here.

> Is there a convention to prevent it from being exported yet have it co-located with the public interface? 

No, somewhat annoying but if there is an `export * from '...'` that ends up in the root `index.ts(x)`, it needs to be replaced with `export { a, b, c } from '...'`.

Comment (lauri865) [reply scripts/x-data-grid-premium.exports.json]: Ok, but that's good enough. I was afraid it scans models directory or something. Fixed that.

**Comment by lauri865** [comment]
@romgrk, there's one last bug I'd love to fix as a part of this PR (present already before the PR)

If you pin a column to left, you see a visible flash of content:
https://next.mui.com/x/react-data-grid/#commercial-licenses

There's two issues:
* initially RenderContext is out of sync with – `GridRow` tries to render the newly pinned column both as a part of `pinnedColumns` as well as part of the middle cells. I don't think it's ever painted though, but still extra render pass.
* columnPositions is out of sync with the new ordering for at least 2 render passes (which I guess is the cause of the actual visible flash)

This seems to fix the 2nd issue, but I'm not sure if there's a better way:
```typescript
const visibleColumnsSelector = React.useCallback(
    () => () =>
      listView
        ? [gridListColumnSelector(apiRef.current.state)!]
        : gridVisibleColumnDefinitionsSelector(apiRef),
    [apiRef, listView],
  );
const visibleColumns = useGridSelector(apiRef, visibleColumnsSelector);
```

Any thoughts?

**Comment by lauri865** [comment]
I actually don't even understand why the above works. How can selector even be a function that returns a function? Was a copy-paste mistake.

What does work however is to call `hydrateColumns` directly in `pinColumn` and `unpinColumn`:
```typescript
apiRef.current.setPinnedColumns(newPinnedColumns);
apiRef.current.requestPipeProcessorsApplication('hydrateColumns');
```

Seems to fix both of the issues. I'm not sure what's currently even calling the hydration, but it happens a couple of render passes later.

**Comment by lauri865** [comment]
Aha, I understand what's happening currently (I think). Pinned columns change -> changes `viewportInnerSize` in `useGridDimensions` -> triggers `handleGridSizeChange` in `useGridColumns` -> triggers `hydrateColumns`. Quite complex chain.

With the above change now `hydrateColumns` would be triggered twice I guess though. So, I wonder if we can get rid of that somehow as well.

**Comment by lauri865** [comment]
After more debugging, I finally understand what trigger column hydration here.
1. `useGridColumnPinningPreProcessors`
2. Dependency array of `reorderPinnedColumns` changes
3. `useGridRegisterPipeProcessor` registers `registerPreProcessor` in `useEffect` (crux of the issue)
4. `registerPipeProcessor` in `useGridPipeProcessing` detects that processor has changed
5. Triggers `runAppliers` that triggers `hydrateColumns`

I will make triggering `hydrateColumns` more explicit to fix this, and make the callback stable.

**Comment by lauri865** [comment]
Ok, managed to fix this. With the memoization PR together, changing pinning will now happen in one render pass, instead of 3-4 I think (meaning all rows re-rendered 4 times due to it).

I also refactored `useGridColumns` to rehydrate column widths based on `viewportOuterWidth` instead of `innerWidth`. `innerWidth` can change independent of `outerWidth` only due to `pinnedColumns`, and what happens is we rehydrate columns twice, triggering unnecessary re-rendering and operations.

Please take a look when you have a moment @romgrk 🙏

**Comment by lauri865** [comment]
The last fix I added as a part of this PR could be considered breaking, although could also potentially be classified as a bug.

`viewportInnerSize.width` currently is calculated by subtracting pinnedColumns, except for the `autoHeight` implementation, which doesn't (and which I would consider the right of the two approaches, both semantically and functionality-wise, unless I'm missing something). I wonder if it is legacy artefact that's been left in when pinnedColumns were actually rendered in separate containers / rows.

This has two negative implications:
* Potentially recursive event loop (`viewportInnerSize.width` depends on column widths and columnWidths depend on `viewportInnerSize.width`). I think it could be the root cause of some `maximum update depth errors` that have been popping up that have so far been fixed with dimension rounding instead.
* Plus any pinned column that gets resized, added or removed will trigger re-evaluation of column widths twice

None of the internal consumers actually seem to depend on the width without pinned columns, but rather on the actual inner viewport width. Meaning that there's likely many unnecessary operations happening when pinned columns are present, resized or modified.

----
On a slightly different note. It also seems like the below code doesn't seem to serve any function, as it always returns 0 for `cellOffset`, at least after the state propagation has been fixed. I left it in for the time being, as it does serve some styling function for us to detect last/first columns in respective pinned sections in CSS. However, by simply adding `firstPinnedColumn` and `lastPinnedColumn` classes, the prop + dom element + calculation can probably be removed in v8. Unless there's an additional function to it that I'm not seeing?

```typescript
<div
  role="presentation"
  className={gridClasses.cellOffsetLeft}
  style={{ width: offsetLeft }}
/>
```

**Comment by lauri865** [comment]
@romgrk, I merged recent updates into the PR, and all tests are passing (except for one flaky one, which is being fixed it seems, ref #16202).

@MBilalShafi, can you review the last commit regarding row spanning?

A row spanning related test started failing as a result of this PR:
`Row spanning pagination should only compute the row spanning state for current page FAILED`

The problem is with the state initialisation, which doesn't take into account the pagination page size. Hence, it will eagerly evaluate it for 20 rows even if pagination is enabled (`=DEFAULT_ROWS_TO_PROCESS`). I think previously the test still passed, because of unnecessary events firing that forced row pinning to re-evaluate immediately, even though there was no need, hiding the issue.

[I also changed the `processedRange` initialisation:](https://github.com/mui/mui-x/blob/a2c7b004f806738cdb27ca8f8f420a903769a8f8/packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts#L227-L237)
From: `Object.keys(apiRef.current.state.rowSpanning.spannedCells).length > 0`
To: `apiRef.current.state.rowSpanning !== EMPTY_STATE`

Felt like the correct approach, as otherwise it will just ignore any already processed range when no spannable rows were found, reprocessing everything once again. Just a nitpick, but caught my attention during debugging the test(s) where initially processed range was incorrect in some instances.

**Comment by lauri865** [comment]
@arminmeh, the below code block seems seems to have a bug in logic if I'm not mistaken? A datasource related test started failing in this PR. `Data source lazy loader Infinite loading should reset the scroll position when sorting is applied FAILED`.

`loadingTrigger.current` and `newLoadingTrigger` will always be equal in the called function:
https://github.com/mui/mui-x/blob/37e6a41f11d9cc43fe28864ad59465aeec21e5f0/packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts#L232-L246

The root cause of the failing test is that this scroll reset seems to be invoked during first load:
https://github.com/mui/mui-x/blob/37e6a41f11d9cc43fe28864ad59465aeec21e5f0/packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts#L262

Which runs after, hence scroll gets reset and row 10 is never accessible to the test:
https://github.com/mui/mui-x/blob/37e6a41f11d9cc43fe28864ad59465aeec21e5f0/packages/x-data-grid-pro/src/tests/dataSourceLazyLoader.DataGridPro.test.tsx#L213

This seems to fix the issue:
https://github.com/mui/mui-x/pull/15627/commits/a6af9ee753cb869dc86d158db55f74a1a0743af0

File: packages/x-data-grid/src/components/GridRow.tsx
Comment (cherniavskii) [inline packages/x-data-grid/src/components/GridRow.tsx:1]: > It also seems like the below code doesn't seem to serve any function, as it always returns 0 for cellOffset, at least after the state propagation has been fixed.

This element is necessary for virtualization to work:

Comment (lauri865) [reply packages/x-data-grid/src/components/GridRow.tsx:1]: Right, makes total sense. Thanks! 🙏

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts [hunk 7]
```diff
@@ -225,11 +230,12 @@ export const useGridRowSpanning = (
   props: Pick<DataGridProcessedProps, 'rowSpanning' | 'pagination' | 'paginationMode'>,
 ): void => {
   const processedRange = useLazyRef<RowRange, void>(() => {
-    return Object.keys(apiRef.current.state.rowSpanning.spannedCells).length > 0
+    return apiRef.current.state.rowSpanning !== EMPTY_STATE
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts:233]: From https://github.com/mui/mui-x/pull/15627#issuecomment-2594152245

> Felt like the correct approach, as otherwise it will just ignore any already processed range when no spannable rows were found, reprocessing everything once again. Just a nitpick, but caught my attention during debugging the test(s) where initially processed range was incorrect in some instances.

Not sure I follow this. Doesn't the proposed change mean that when there are no spanned cells, we will try calculating `processedRange` instead of returning `EMPTY_RANGE`?

cc @MBilalShafi

File: packages/x-data-grid/src/hooks/features/rows/useGridRows.ts [hunk 8]
```diff
@@ -267,7 +257,14 @@ export const useGridRows = (
 
   const getRowIndexRelativeToVisibleRows = React.useCallback<
     GridRowApi['getRowIndexRelativeToVisibleRows']
-  >((id) => lookup[id], [lookup]);
+  >(
+    (id) => {
+      const row = apiRef.current.getRow(id);
+      const rows = getVisibleRows(apiRef);
+      return rows.rowToIndexMap.get(row)!;
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/rows/useGridRows.ts:264]: Sidenote: Why did you use the row model as a key instead of the row id?

Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/rows/useGridRows.ts:264]: It's more performant and memory efficient, especially if your ids are UUIDs. The key is essentially the object reference.

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts (hunk 7 above)
Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts:233]: If during the first invocation of `useGridRowSpanning` the `rowSpanning` state is anything other than `EMPTY_RANGE`, it means that the state initialiser has already processed an initial range.

Initial `processedRange` thus should be equal to the `rangeToProcess` in the state initialiser.

TBH, not quite a fan that this logic is split and replicated between the hook and initialiser. Maybe should throw it in the state instead or use state cache instead of refs. But didn't want to change too much within this PR.

File: packages/x-data-grid/src/hooks/features/rows/useGridRows.ts (hunk 8 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/rows/useGridRows.ts:264]: Got it. Do you think it's possible that the `row` could refer to a different object than the key in `rows.rowToIndexMap`? E.g. on rows updates/editing?

**Comment by lauri865** [comment]
Last commit I promise, but fixed `listView` state propagation as well, since it was in the same vain. Fixes #16234

Issues:
* Incorrect `renderContext`
* Prop and state are update in different cycles, leading to potential cases where no columns get rendered (e.g. `listView` prop is enabled, but `listViewColumn` is not inserted to the state yet
* `colDef` override made it possible for random cells to render with the `listViewColumn` colDef, resulting in rendering errors (wrong value and cellParams passed to the `renderCell`)

File: packages/x-data-grid/src/hooks/features/rows/useGridRows.ts (hunk 8 above)
Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/rows/useGridRows.ts:264]: Good question. There is only once instance that I can see that tries to call with a non-existent row and that's `useGridFocus`:
https://github.com/mui/mui-x/blob/4497258e9f9867b4ee29346bca16e83a6322b9c5/packages/x-data-grid/src/hooks/features/focus/useGridFocus.ts#L428-L434

There's an easy fix for that though – since we want to access currently rendered focused row index, we can get it from the dom (pushed a fix):
```typescript
const rowEl = apiRef.current.getRowElement(lastFocusedRowId);
const lastFocusedRowIndex = rowEl?.dataset.rowindex ? Number(rowEl?.dataset.rowindex) : 0;
```

Every other instance should probably in theory only benefit from having access to the most up to date value. Unless you can think of something else? 🤔

**Comment by arminmeh** [comment]
> @arminmeh, the below code block seems seems to have a bug in logic if I'm not mistaken? A datasource related browser test started failing in this PR. Data source lazy loader Infinite loading should reset the scroll position when sorting is applied FAILED.

>loadingTrigger.current and newLoadingTrigger will always be equal in the called function, and the null check if irrelevant, so it's always run:

Indeed.
Thanks for the fix. Appreciate it.

File: packages/x-data-grid/src/hooks/features/rows/useGridRows.ts (hunk 8 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/rows/useGridRows.ts:264]: > Unless you can think of something else? 🤔

I don't have any specific use cases in mind, but wouldn't it be safer to use row id as the key?
Performance-wise, there shouldn't be much difference because we still have to get `row` by the `rowId` before calling `rowToIndexMap.get`.

File: packages/x-data-grid/src/hooks/features/listView/useGridListView.tsx
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/listView/useGridListView.tsx:1]: > fixed listView state propagation as well, since it was in the same vain. Fixes https://github.com/mui/mui-x/issues/16234

@lauri865 I added the before/after demos in the PR description, but can I ask you to extract this into a separate PR? We would want to cherry-pick it to the `v7.x` branch, which will be harder to do if it's part of this PR.

File: packages/x-data-grid/src/hooks/features/rows/useGridRows.ts (hunk 8 above)
Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/rows/useGridRows.ts]: The performance cost of getting the row was not significant in my testing (0 to 0.00X ms, even with random access and scrolling fast). But I changed it back to `rowId`-based anyways, and avoided two maps now. Thanks for challenging 🙏

**Comment by lauri865** [comment]
If we use a `rowId` based `Map` instead of an object, calling `getRowIndexRelativeToVisibleRows` no longer works with incorrect type (e.g. if ids are strings, you can't access it with an equivalent number). Not sure if not supporting javascript oddities would be considered a breaking change or not (personally, I wouldn't), but worth noting at least.

File: packages/x-data-grid/src/hooks/features/listView/useGridListView.tsx
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/listView/useGridListView.tsx:1]: I shared my thoughts on cherry-picking this PR to v7 in https://github.com/mui/mui-x/pull/15627#pullrequestreview-2563052144
Unless there are strong arguments for cherry-picking, it won't be cherry-picked.

Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/listView/useGridListView.tsx:1]: Well, for one, it fixes a ton of issues that users have complained about.

Do you have a rough timeline for v8 RC (or some kind of stability)? I understand that working on split versions is a PITA.

**Comment by cherniavskii** [comment]
> calling `getRowIndexRelativeToVisibleRows` no longer works with incorrect type (e.g. if ids are strings, you can't access it with an equivalent number). Not sure if not supporting javascript oddities would be considered a breaking change or not (personally, I wouldn't), but worth noting at least.

Hmm, I did not foresee this, but I think this is the correct behavior because nothing prevents you from having both `"4"` and `4` as row IDs in the same dataset. That wouldn't work correctly with an object.
The only potential inconvenience with this is trying to use row IDs extracted from DOM data attributes (always strings), while the actual IDs are numbers. But I still prefer the row ID type to be strict, without implicit typecasting.

**Comment by lauri865** [comment]
> > calling `getRowIndexRelativeToVisibleRows` no longer works with incorrect type (e.g. if ids are strings, you can't access it with an equivalent number). Not sure if not supporting javascript oddities would be considered a breaking change or not (personally, I wouldn't), but worth noting at least.
> 
> Hmm, I did not foresee this, but I think this is the correct behavior because nothing prevents you from having both `"4"` and `4` as row IDs in the same dataset. That wouldn't work correctly with an object. The only potential inconvenience with this is trying to use row IDs extracted from DOM data attributes (always strings), while the actual IDs are numbers. But I still prefer the row ID type to be strict, without implicit typecasting.

I agree with that. I've been only bitten by this implicit behaviour.

Regarding the `viewport` change, I would definitely categorise it as a bug fix, rather than a breaking change. There's many calculations that are wrong due to that:
1. https://stackblitz.com/edit/react-b1esajbm?file=package.json,Demo.tsx - try autosizing with expand and pinned columns – doesn't fill the width.
2. This is wrong: https://github.com/mui/mui-x/blob/b28668445a35251b4b93c5e05b993edad132f580/packages/x-data-grid/src/components/GridScrollArea.tsx#L87
3. Plus the discrepancy between `autoHeight` (correct) and regular values (been struggling with that in custom plugins)

File: packages/x-data-grid/src/hooks/features/listView/useGridListView.tsx
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/listView/useGridListView.tsx:1]: Thanks for updating the PR description and linking related issues!
I considered this PR mostly as performance optimization/internal refactoring, but now I do see that it's fixing quite a lot of bugs 👍🏻
Cherry-picking to v7 makes sense to me now.
We can discuss how to proceed with `viewportInnerSize` in the cherry-pick PR.

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts (hunk 7 above)
Comment (MBilalShafi) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts:233]: The change makes sense to me, it's practically the same with a relatively better check.

Not sure about moving it to state since it might introduce another reactive binding which I'd prefer to avoid, I'm thinking about going a bit anti-pattern and storing the initial processed range in a static variable outside the hook to avoid any splitting of the logic, since we know the execution order of initializer and the feature hook.

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts [hunk 9]
```diff
@@ -123,7 +124,7 @@ const computeRowSpanningState = (
       // Scan the next rows
       let relativeIndex = index + 1;
       while (
-        relativeIndex <= range.lastRowIndex &&
+        relativeIndex < rangeToProcess.lastRowIndex &&
```
[the remark this answers is not in the document]
Comment (MBilalShafi) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts:127]: I think we might want to revert it as it causes unnecessary behavior for the cells that span beyond `rangeToProcess`
1. Cell gets auto deselected on fast scroll
2. A visible flickering is observed on scroll
3. Cell navigation doesn't work for these cells

The current performance for large datasets is not great and I have an impression we could move part of it to background/lazy processing for improving it, but ignoring the cells that go beyond the `rangeToProcess` would be something I'd like to avoid at this point, to preserve the UX for small to mid size datasets.

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts (hunk 7 above)
Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts:233]: Why not store it under e.g. `apiRef.current.caches.rowSpanning.initialProcessedRange` or alike?

Comment (MBilalShafi) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts:233]: That would also make sense, we generally put things in `caches.something` if it's shared between multiple hooks or multiple render cycles but this one also seem a nice candidate.

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts]: I agree, should be reverted (done). Now that I re-read the change, I must have mistakenly committed it when fixing state initialisation.

File: packages/x-data-grid/src/hooks/features/listView/useGridListView.tsx
Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/listView/useGridListView.tsx:1]: Extracted the initial range calculation to a separate function for now, the one-liner got very difficult to read:
https://github.com/mui/mui-x/pull/15627/commits/93d11d088256457d68001ee6367058f515eb2c35

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts (hunk 7 above)
Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts]: Extracted initial page calculation to a separate function:
https://github.com/mui/mui-x/commit/93d11d088256457d68001ee6367058f515eb2c35

File: packages/x-data-grid/src/components/GridRow.tsx [hunk 10]
```diff
@@ -24,11 +24,26 @@ import { GRID_ACTIONS_COLUMN_TYPE } from '../colDef/gridActionsColDef';
...
+  gridEditRowsStateSelector,
+  gridRowIsEditingSelector,
+} from '../hooks/features/editing/gridEditingSelectors';
 import { GridScrollbarFillerCell as ScrollbarFiller } from './GridScrollbarFillerCell';
 import { getPinnedCellOffset } from '../internals/utils/getPinnedCellOffset';
 import { useGridConfiguration } from '../hooks/utils/useGridConfiguration';
 import { useGridPrivateApiContext } from '../hooks/utils/useGridPrivateApiContext';
+import { createSelector } from '../utils/createSelector';
+
+const gridIsRowReorderingEnabledSelector = createSelector(
```
Comment (romgrk) [inline packages/x-data-grid/src/components/GridRow.tsx:37]: lint: for a local selector, the `grid` prefix is not necessary.

File: packages/x-data-grid/src/components/GridRow.tsx [hunk 11]
```diff
@@ -24,11 +24,26 @@ import { GRID_ACTIONS_COLUMN_TYPE } from '../colDef/gridActionsColDef';
...
+  gridEditRowsStateSelector,
+  (editRows, rowReordering: boolean) => {
+    if (!rowReordering) {
+      return false;
+    }
+    const isEditingRows = Object.keys(editRows).length > 0;
+    return !isEditingRows;
```
Comment (romgrk) [inline packages/x-data-grid/src/components/GridRow.tsx:44]: lint: `isObjectEmpty` from [here](https://github.com/mui/material-ui/pull/44254/files#diff-2e2bf359aad78bc8207b44ace4a935b35fafaf18815d147697e1ec0b122fd860)

File: packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts [hunk 12]
```diff
@@ -199,7 +201,7 @@ export function useGridDimensions(
         height: rootDimensionsRef.current.height,
       };
       viewportInnerSize = {
-        width: Math.max(0, viewportOuterSize.width - leftPinnedWidth - rightPinnedWidth),
+        width: Math.max(0, viewportOuterSize.width),
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts:204]: IIUC, we're changing the meaning of `viewportInnerSize` to now include pinned columns?

**Review by romgrk — APPROVED** [review]
LGTM, and I've added a few refactoring commit.

File: packages/x-data-grid/src/components/cell/GridCell.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/x-data-grid/src/components/cell/GridCell.tsx]: > I'm a bit hesitant to drop getCellParams altogether in GridCell as it opens up an easy divergence between the public API and internal logic.

Not as long as we use the `GridCellParams` type.

I still think this section could be improved a bit, but I'm happy enough to merge it as it is.

**Review by cherniavskii — APPROVED** [review]
