### PR TITLE
[pickers] Fix DST issue with `America/Asuncion` timezone and `AdapterMoment`

### LINKED ISSUE #14730: [pickers] `DateCalendar` shows duplicate dates for DST when using `AdapterMoment`
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/y6cws5

Steps:
1. Scroll to October with the timezone set to `America/Asuncion` on the StaticDatePicker
2. October 5th is shown twice in the calendar and every day in October after that is shifted by a day (Ex Oct 8th is shown as a Wednesday, but it should be a Tuesday

CleanShot 2024-09-25 at 12 23 33

### Current behavior

October 5th is shown twice in the StaticDatePicker for the `America/Asuncion` timezone causing all dates to be shifted by a day

### Expected behavior

October 5th should only be shown on Saturday.

### Context

_No response_

### Your environment

See the code sandbox here: https://codesandbox.io/p/sandbox/y6cws5

**Search keywords**: daylight savings DST moment

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #14730

### CODE REVIEW

File: packages/x-date-pickers/src/AdapterMoment/AdapterMoment.ts [hunk 1]
```diff
@@ -522,14 +522,25 @@ export class AdapterMoment implements MuiPickersAdapter<string> {
...
     const nestedWeeks: Moment[][] = [];
 
     while (current.isBefore(end)) {
       const weekNumber = Math.floor(count / 7);
       nestedWeeks[weekNumber] = nestedWeeks[weekNumber] || [];
       nestedWeeks[weekNumber].push(current);
 
+      const prevDayOfYear = currentDayOfYear;
       current = this.addDays(current, 1);
+      currentDayOfYear = current.get('dayOfYear');
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/AdapterMoment/AdapterMoment.ts:535]: The original snippet uses `.diff` but it also work if you just check the `dayOfYear` property which is a lot cheaper to access.

Comment (LukasTy) [reply packages/x-date-pickers/src/AdapterMoment/AdapterMoment.ts:535]: Nice, this is a way more efficient and easier to understand solution.
Great job. 👍

**Review by LukasTy — APPROVED** [review]
This does not feel like a very high price to pay for covering "maintenance mode" adapter edge-cases. 👌
