### PR TITLE
[fields] Fix RTL navigation

### LINKED ISSUE #8284: Fields components ways reverse in RTL
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Click month in input
2. Press Left Arrow Key and Date input select
3. Cursor move to right and year selected

### Current behavior 😯

_No response_

### Expected behavior 🤔

_No response_

### Context 🔦

_No response_

### Your environment 🌎

[codesandbox](https://codesandbox.io/p/github/fakhamatia/material-dashboard-react/main?file=%2Fsrc%2FApp.js&selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A175%2C%22startColumn%22%3A30%2C%22startLineNumber%22%3A175%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522clfqnyuhz00cug4j9cylxfk85%2522%252C%2522openFiles%2522%253A%255B%2522%252Fsrc%252FApp.js%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfqnvwng00112g6huhwnuk1j%2522%253A%257B%2522key%2522%253A%2522clfqnvwng00112g6huhwnuk1j%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clfqnvwng00122g6ho7mtvlnk%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Frtl%2522%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clfqnvwng00112g6huhwnuk1j%2522%252C%2522spacesOrder%2522%253A%255B%2522clfqnvwng00112g6huhwnuk1j%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)
`/rtl` route

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #8284

### CODE REVIEW

File: docs/data/date-pickers/calendar-systems/AdapterHijri.tsx [hunk 1]
```diff
@@ -2,12 +2,22 @@ import * as React from 'react';
 import moment from 'moment-hijri';
 import { AdapterMomentHijri } from '@mui/x-date-pickers/AdapterMomentHijri';
 import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
-import { DatePicker } from '@mui/x-date-pickers/DatePicker';
+import { DateTimePicker } from '@mui/x-date-pickers/DateTimePicker';
+import { createTheme, ThemeProvider } from '@mui/material/styles';
+
+const theme = createTheme({ direction: 'rtl' });
```
Comment (LukasTy) [inline docs/data/date-pickers/calendar-systems/AdapterHijri.tsx:8]: This causes issues when using a dark docs page theme. 🙈 
Screenshot 2023-04-05 at 12 51 31

I propose to use the existing theme and extend it. Or feel free to come up with a better solution. 👌 
```diff
diff --git a/docs/data/date-pickers/calendar-systems/AdapterJalali.tsx b/docs/data/date-pickers/calendar-systems/AdapterJalali.tsx
index b869ec8ea..2a9ede08a 100644
--- a/docs/data/date-pickers/calendar-systems/AdapterJalali.tsx
+++ b/docs/data/date-pickers/calendar-systems/AdapterJalali.tsx
@@ -1,12 +1,16 @@
 import * as React from 'react';
+import useTheme from '@mui/system/useTheme';
 import { AdapterDateFnsJalali } from '@mui/x-date-pickers/AdapterDateFnsJalali';
 import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
 import { DateTimePicker } from '@mui/x-date-pickers/DateTimePicker';
 import { createTheme, ThemeProvider } from '@mui/material/styles';
 
-const theme = createTheme({ direction: 'rtl' });
-
 export default function AdapterJalali() {
+  const existingTheme = useTheme();
+  const theme = React.useMemo(
+    () => createTheme({ direction: 'rtl' }, existingTheme),
+    [existingTheme],
+  );
   return (
     <ThemeProvider theme={theme}>
       <div dir="rtl">
```

File: packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts [hunk 2]
```diff
@@ -899,7 +899,11 @@ export const getSectionOrder = (
   while (RTLIndex >= 0) {
     groupedSectionsEnd = sections.findIndex(
       // eslint-disable-next-line @typescript-eslint/no-loop-func
-      (section, index) => index >= groupedSectionsStart && section.endSeparator?.includes(' '),
+      (section, index) =>
+        index >= groupedSectionsStart &&
+        section.endSeparator?.includes(' ') &&
+        // Special case where the spaces were nto there in the initial input
+        section.endSeparator !== ' / ',
```
Comment (LukasTy) [inline packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts:906]: @flaviendelangle FYI, this might need adjustment depending on the approach we select for the format issue. 😉

File: docs/data/date-pickers/calendar-systems/AdapterHijri.tsx (hunk 1 above)
Comment (alexfauquette) [reply docs/data/date-pickers/calendar-systems/AdapterHijri.tsx]: Nice catch. I went to the [docs solution](https://mui.com/material-ui/customization/theming/#nesting-the-theme) providing a function to the `theme` props

**Review by LukasTy — APPROVED** [review]
Great job! 👏
