### PR TITLE
[DataGrid] Support state export and restore on grid density

### LINKED ISSUE #4572: [data grid] `apiRef` `restoreState` and `exportState` does not support the density
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The density state is not saved. All other state is saved correctly

### Expected behavior 🤔

_No response_

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by MBilalShafi**
Resolves #4572

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/density/useGridDensity.tsx [hunk 1]
```diff
@@ -43,15 +47,62 @@ export const useGridDensity = (
...
   const densityApi: GridDensityApi = {
     setDensity,
   };
 
   useGridApiMethod(apiRef, densityApi, 'public');
+
+  /**
+   * PRE-PROCESSING
+   */
+  const stateExportPreProcessing = React.useCallback<GridPipeProcessor<'exportState'>>(
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/density/useGridDensity.tsx:59]: We shouldn't be using `/**` comments for section annotations, those have a defined meaning and are picked-up by the LSP servers. The `stateExportPreProcessing` would have the comment above as its JSDoc comment.

**Review by romgrk — APPROVED** [review]

File: packages/x-data-grid/src/hooks/features/density/useGridDensity.tsx (hunk 1 above)
Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/density/useGridDensity.tsx:59]: It feels wrong to use JSDoc comments that way. I think we should avoid it for new code and update the rest as we touch that code.
