### PR TITLE
[DataGrid] Fix disabled typography variants crashing grid

### LINKED ISSUE #17812: [data grid] disabled variants leads to runtime error
### Search keywords

DataGrid, formatFont, variants, body1, caption

### Latest version

- [x] I have tested the latest version

### Affected products

Data Grid

### Steps to reproduce

Steps:
1. Open this link to live example: https://stackblitz.com/edit/ritphqqu?file=src%2Ftheme.ts,src%2Findex.tsx
2. Comment in to have the variant `body1` disabled as documented here: https://mui.com/material-ui/customization/typography/#adding-amp-disabling-variants

    ```diff
    export const theme = createTheme({
      typography: {
        // Comment in to see breaking DataGrid
    -    // body1: undefined,
    +   body1: undefined,
      },
    });
    ```

### Current behavior

DataGrid crash with console error:

```txt
@mui_x-data-grid.js?v=33698ce7:47800 Uncaught TypeError: Cannot read properties of undefined (reading 'fontWeight')
    at formatFont (@mui_x-data-grid.js?v=33698ce7:47800:18)
    at transformTheme (@mui_x-data-grid.js?v=33698ce7:47734:102)
    at @mui_x-data-grid.js?v=33698ce7:47714:23
    at mountMemo (react-dom_client.js?v=47e3fc84:5050:25)
    at Object.useMemo (react-dom_client.js?v=47e3fc84:16511:20)
    at exports.useMemo (chunk-37AZBUIX.js?v=7d05f891:939:36)
    at Object.useMaterialCSSVariables [as useCSSVariables] (@mui_x-data-grid.js?v=33698ce7:47712:19)
    at GridCSSVariablesContext (@mui_x-data-grid.js?v=33698ce7:3393:36)
    at react-stack-bottom-frame (react-dom_client.js?v=47e3fc84:17422:20)
    at renderWithHooks (react-dom_client.js?v=47e3fc84:4204:24)
```

### Expected behavior

DataGrid does not crash or at least does not depend on hardcoded typography variants

### Context

We use a custom theme where all the [13 default variants](https://mui.com/material-ui/customization/typography/#variants) are disabled.

### Your environment

_No response_

### Order ID or Support key 💳 (optional)

107362

### PR DESCRIPTION
**Pull request by KenanYusuf**
Fixes #17812 

Before: https://codesandbox.io/p/sandbox/elegant-brahmagupta-rf32c9

After: https://codesandbox.io/p/sandbox/silly-ully-36dkrv

### CODE REVIEW

File: packages/x-data-grid/src/material/variables.ts [hunk 1]
```diff
@@ -71,9 +71,9 @@ function transformTheme(t: Theme): GridCSSVariablesInterface {
     [k.typography.fontWeight.regular]: t.typography.fontWeightRegular as string,
     [k.typography.fontWeight.medium]: t.typography.fontWeightMedium as string,
     [k.typography.fontWeight.bold]: t.typography.fontWeightBold as string,
-    [k.typography.font.body]: fontBody,
-    [k.typography.font.small]: fontSmall,
-    [k.typography.font.large]: fontLarge,
+    ...(fontBody ? { [k.typography.font.body]: fontBody } : {}),
+    ...(fontSmall ? { [k.typography.font.small]: fontSmall } : {}),
+    ...(fontLarge ? { [k.typography.font.large]: fontLarge } : {}),
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/material/variables.ts:76]: IMO It makes sense not to output the variable at all if the value is `undefined` — this requires changing the returned value to reflect that the whole vars object may not be present.

File: packages/x-data-grid/src/material/variables.ts [hunk 2]
```diff
@@ -118,5 +118,10 @@ function removeOpacity(color: string) {
 }
 
 function formatFont(font: React.CSSProperties) {
```
Comment (arminmeh) [inline packages/x-data-grid/src/material/variables.ts:120]: should the argument type be updated to reflect the possibility below?

File: packages/x-data-grid/src/material/variables.ts [hunk 3]
```diff
@@ -71,9 +71,9 @@ function transformTheme(t: Theme): GridCSSVariablesInterface {
...
     [k.typography.fontWeight.medium]: t.typography.fontWeightMedium as string,
     [k.typography.fontWeight.bold]: t.typography.fontWeightBold as string,
-    [k.typography.font.body]: fontBody,
-    [k.typography.font.small]: fontSmall,
-    [k.typography.font.large]: fontLarge,
+    ...(fontBody ? { [k.typography.font.body]: fontBody } : {}),
+    ...(fontSmall ? { [k.typography.font.small]: fontSmall } : {}),
+    ...(fontLarge ? { [k.typography.font.large]: fontLarge } : {}),
 
     [k.transitions.easing.easeIn]: t.transitions.easing.easeIn,
```
Comment (arminmeh) [inline packages/x-data-grid/src/material/variables.ts:78]: do we need to account for other theme overrides (like in this line, if `transitions` is set to `undefined`)?

File: packages/x-data-grid/src/material/variables.ts (hunk 1 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/material/variables.ts:76]: OTOH, with `Partial` it's easy to miss some variables unintentionally.
How about checking for `undefined` values here instead?
https://github.com/mui/mui-x/blob/49b9d7d9a1fabdfb10f8d38ab4bc8e32530e2fa5/packages/x-data-grid/src/utils/css/context.tsx#L49-L51

**Review by cherniavskii — APPROVED** [review]

File: packages/x-data-grid/src/material/variables.ts (hunk 1 above)
Comment (KenanYusuf) [reply packages/x-data-grid/src/material/variables.ts]: Makes a lot of sense to check there 👍 

Updated https://github.com/mui/mui-x/pull/17934/commits/00e27a1e18f02726b4424cce956f8873f9df6fd0#diff-801af99c5063996ab3739e0aa3be8d1cbc857f7dff6ef590695083340525cbcaR49

**Review by arminmeh — APPROVED** [review]
