### PR TITLE
[DataGrid] Fix 'ResizeObserver loop limit exceeded' error

### LINKED ISSUE #8733: ResizeObserver loop error in react error overlay in dev mode
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

This requires cloning and running in dev mode to reproduce, production mode doesn't have the error overlay
https://github.com/cmdcolin/x-data-grid-resizeobserver-loop-error

Steps:
1. Clone the repo https://github.com/cmdcolin/x-data-grid-resizeobserver-loop-error
2. Run yarn
3. Run yarn start
4. Add another row of "<DataGrid>" to the set

This only affects the very latest version of @mui/x-data-grid 6.2.1 with the ResizeObserver change

Note: in my larger project, I get this error without modifying source code, but this was the simplest way I found to reproduce the issue in a smaller project e.g. to add another datagrid to the page was the best way to reproduce it in this small example

### Current behavior 😯

Creates a react-error-overlay saying "ResizeObserver loop limit exceeded"

image

This is a dev mode only phenomenon to create the large overlay

### Expected behavior 🤔

It would be nice if there was no error from this. There may be workarounds such as this stackoverflow answer suggests https://stackoverflow.com/a/58701523/2129219, but there are tradeoffs to using that potentially, so might be worth considering alternative solutions

Noted by another user here https://github.com/mui/mui-x/pull/8091#issuecomment-1517594743

### Context 🔦

I am using @mui/x-data-grid in dev mode in a create-react-app v5 instance, and it has these error overlays when a global error occurs

We could maybe configure our create-react-app config to ignore this error in dev mode, but we ship a library that uses x-data-grid and it is difficult to tell people to use a particular create-react-app v5 config for example

### Your environment 🌎

Unable to complete the npx @mui/envinfo, but the yarn.lock in the linked repo should be reproducible

Chromium Version 112.0.5615.49 (Official Build) snap (64-bit)
Firefox Nightly 114.0a1 (2023-04-23) (64-bit)

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #8733 

Based https://stackoverflow.com/a/58701523 and https://github.com/nolimits4web/swiper/pull/5441

### CODE REVIEW

File: packages/grid/x-data-grid/src/components/base/GridBody.tsx [hunk 1]
```diff
@@ -88,14 +89,20 @@ function GridBody(props: GridBodyProps) {
     }
 
     const observer = new ResizeObserver(() => {
-      apiRef.current.computeSizeAndPublishResizeEvent();
+      animationFrame.current = window.requestAnimationFrame(() => {
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/base/GridBody.tsx:92]: Nit: Would a local variable instead of the ref work here?

**Review by cherniavskii — APPROVED** [review]
