### PR TITLE
[license] Add new license status 'Out of scope'

### LINKED ISSUE #5246: [license] Confusing out of scope license error message
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The error message when using the wrong scope (premium feature with a pro plan) is confusing.

> MUI: Invalid license key.
> 
> Your MUI X license key isn't valid. Please check your license key installation https://mui.com/r/x-license-key-installation.
> 
> To purchase a license, please visit https://mui.com/r/x-get-license.

### Expected behavior 🤔

I would expect a clear error message with action steps on how to solve it. Here is an example of what it could look like:

> MUI: Out of scope license key.
> 
> Your MUI X license key isn't valid.
> You are rendering a DataGridPremium component that requires a license key with the "premium" feature scope but your license key has the "pro" feature scope.
> 
> You can solve the issue by purchasing a premium license at https://mui.com/r/x-get-license?scope=premium.
> Alternatively, you can replace the import on DataGridPremium with DataGridPro.

### Steps to reproduce 🕹

Steps:

1. https://codesandbox.io/s/data-grid-pro-forked-2l3i5e?file=/src/App.tsx

### Context 🔦

This is a standalone issue for this comment https://github.com/mui/mui-x/issues/1364#issuecomment-1125080338. The problem was raised in https://groups.google.com/a/mui.com/g/x/c/HPmXe5P7emI/m/AxaJwlHjBQAJ?utm_medium=email&utm_source=footer.

### Your environment 🌎

MUI X v5.12.2

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #5246

### CODE REVIEW

**Review by joserodolfofreitas — COMMENTED** [review]
Perhaps we can add documentation to this message on
https://mui.com/x/advanced-components/#license-key-installation

File: packages/x-license-pro/src/verifyLicense/verifyLicense.ts [hunk 1]
```diff
@@ -159,7 +159,7 @@ export function verifyLicense({
   }
 
   if (!acceptedScopes.includes(license.scope)) {
-    return LicenseStatus.Invalid;
+    return LicenseStatus.OutOfScope;
```
Comment (oliviertassinari) [inline packages/x-license-pro/src/verifyLicense/verifyLicense.ts:162]: Maybe we should return more context on the error, here we could return the scope of the license, and the missing scope.

**Review by oliviertassinari — COMMENTED** [review]
Based on https://github.com/mui/mui-x/issues/5246#issuecomment-1160166171, I think that a test case would be great, as there will be future refactoring.

**Comment by joserodolfofreitas** [comment]
> Perhaps we can add documentation to this message on https://mui.com/x/advanced-components/#license-key-installation

We can close #4692 first.

File: packages/x-license-pro/src/verifyLicense/verifyLicense.ts (hunk 1 above)
Comment (oliviertassinari) [reply packages/x-license-pro/src/verifyLicense/verifyLicense.ts:162]: @flaviendelangle Updated to be clearer.

Comment (flaviendelangle) [reply packages/x-license-pro/src/verifyLicense/verifyLicense.ts:162]: OK
I agree :+1:

Comment (flaviendelangle) [reply packages/x-license-pro/src/verifyLicense/verifyLicense.ts:162]: @oliviertassinari test case added

File: packages/grid/x-data-grid-premium/src/tests/license.DataGridPremium.test.tsx [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+import addYears from 'date-fns/addYears';
+import { expect } from 'chai';
+// @ts-ignore Remove once the test utils are typed
+import { createRenderer } from '@mui/monorepo/test/utils';
+import { DataGridPremium, LicenseInfo } from '@mui/x-data-grid-premium';
+import { generateLicense } from '@mui/x-license-pro';
+
+describe('<DataGridPro /> - Layout', () => {
+  const { render } = createRenderer();
+
```
Comment (oliviertassinari) [inline packages/grid/x-data-grid-premium/src/tests/license.DataGridPremium.test.tsx:11]: There might need the need for some clean-up logic between tests:

https://github.com/mui/mui-x/blob/645c8098b5e304726350a53f087a17eebd129d6a/packages/x-license-pro/src/useLicenseVerifier/useLicenseVerifier.test.tsx#L24-L34

File: packages/x-license-pro/src/utils/licenseErrorMessageUtils.ts [hunk 3]
```diff
@@ -20,6 +20,17 @@ export function showInvalidLicenseError() {
   ]);
 }
 
+export function showOutOfScopeLicenseError() {
+  showError([
+    'MUI: Out of scope license key.',
+    '',
+    'Your MUI X license key isn\'t valid. You are rendering a DataGridPremium component that requires a license key with the "premium" feature scope but your license key has the "pro" feature scope',
```
Comment (oliviertassinari) [inline packages/x-license-pro/src/utils/licenseErrorMessageUtils.ts:27]:
```suggestion
    'Your MUI X license key isn\'t valid. You are rendering a DataGridPremium component that requires a license key with the "premium" feature scope but your license key has the "pro" feature scope.',
```

**Review by oliviertassinari — COMMENTED** [review]
Nice 👍

File: packages/grid/x-data-grid-premium/src/tests/license.DataGridPremium.test.tsx (hunk 2 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid-premium/src/tests/license.DataGridPremium.test.tsx:11]: That's a tricky one
If I export `sharedLicenseStatuses`, I'm giving an easy way to totally bypass the validation by manually setting it to valid.
I can add a `LicenseInfo.reset` method and modify `useLicenseVerifier` to have it work.

**Review by joserodolfofreitas — COMMENTED** [review]
Nice addition!
Can we add a section for the new message at
https://mui.com/x/introduction/licensing/#validation-failures ?

File: packages/grid/x-data-grid-premium/src/tests/license.DataGridPremium.test.tsx (hunk 2 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid-premium/src/tests/license.DataGridPremium.test.tsx:11]: Since #6043 I am setting the license key at the before each test so we don't need to clean it up anymore.

**Comment by flaviendelangle** [comment]
@joserodolfofreitas doc added

File: docs/data/introduction/licensing/licensing.md [hunk 4]
```diff
@@ -213,6 +213,11 @@ For example, if you purchase a one-year license today, you will be able to updat
 Those versions will always be available for use in a deployed application,
 however you'll be required to renew your license if you need to continue development with a version released after twelve months.
 
+#### Out of scope license key
+
+This error indicates that the component you are trying to use is not included in your license.
+This can happen if you try to use `DataGridPremium` with a pro license.
```
Comment (oliviertassinari) [inline docs/data/introduction/licensing/licensing.md:219]: To match the capitalization used in https://mui.com/x/introduction/licensing/#upgrading-from-pro-to-premium?

```suggestion
This can happen if you try to use `DataGridPremium` with a Pro license.
```

File: packages/x-license-pro/src/utils/licenseErrorMessageUtils.ts [hunk 5]
```diff
@@ -20,6 +20,17 @@ export function showInvalidLicenseError() {
   ]);
 }
 
+export function showOutOfScopeLicenseError() {
+  showError([
+    'MUI: Out of scope license key.',
+    '',
+    'Your MUI X license key isn\'t valid. You are rendering a DataGridPremium component that requires a license key with the "premium" feature scope but your license key has the "pro" feature scope.',
+    '',
+    'You can solve the issue by purchasing a premium license at https://mui.com/r/x-get-license?scope=premium',
```
Comment (oliviertassinari) [inline packages/x-license-pro/src/utils/licenseErrorMessageUtils.ts:29]: It seems that we use Pro and Premium as a noun.

```suggestion
    'You can solve the issue by purchasing a Premium license at https://mui.com/r/x-get-license?scope=premium',
```

**Review by oliviertassinari — COMMENTED** [review]
It looks good.

**Review by oliviertassinari — APPROVED** [review]
