### PR TITLE
[pickers] Fix `YearCalendar` and `MonthCalendar` a11y

### LINKED ISSUE #9916: [DatePicker] a11y issue with selected state of Year and Date buttons
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The visually selected Date and Year lack any attributes which make is clear to screen readers that this button is in a selected state.  Auditors recommend setting the button to aria-pressed="true" or "false" to indicate its state.

### Expected behavior 🤔

UI components such as Date and Year buttons should convey their selected/not selected state to screen readers. 
Pls add aria-pressed="true" or "false"

### Steps to reproduce 🕹

Steps:

1. Go to Date Picker demo, Basic Usage:  https://mui.com/components/date-picker/#basic-usage
2. using Devtools, choose the current date that is selected:
Screen Shot 2022-02-15 at 10 00 52 AM

3. Note under Element pane in devtools that there is no aria attribute indicating the selected state of the button
4. using Devtools, choose the current year that is selected:
Screen Shot 2022-02-15 at 10 02 31 AM

5. Note under Element pane in devtools that there is no aria attribute indicating the selected state of the button

### Context 🔦

W3C ARIA Recommendation: https://www.w3.org/TR/wai-aria-1.1/#aria-pressed

### Your environment 🌎

using the demo page

### LINKED ISSUE #10141: [pickers] With NVDA, openTo='year' cursor does not move
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/funny-archimedes-rgc9q4?file=/Demo.js

Steps:
1. Enable NVDA screen reader (Windows specific)
2. Open the datepicker in Chrome (also happens in Firefox and Edge)
3. Attempt to move around the datepicker with the keyboard.  The screenreader will read off the options, but the cursor will not move.
4. Also, when navigating to the side, individual characters are read off as though they are separate buttons.  IE 2022 is read off as 2 2 0 2 if navigating left, and 2 0 2 2 if navigating right.

### Current behavior 😯

The cursor indicating the selected date does not move when NVDA is enabled.  Navigating sideways also behaves oddly by reading individual characters.

### Expected behavior 🤔

The cursor should move regardless of whether NVDA is enabled.  Navigating side to side should read the entire entry at once.

### Context 🔦

We are attempting to make our apps 508 compliant, and this has been flagged as an accessibility issue.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
Note - this is my machine.  However I have a mac, and thus no NVDA.  Can't run npx on the machine of the person that has NVDA.
```
  System:
    OS: macOS 13.4
  Binaries:
    Node: 18.16.0 - ~/Library/Caches/fnm_multishells/67800_1692887358564/bin/node
    Yarn: 1.22.19 - ~/.homebrew/bin/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/67800_1692887358564/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Edge: Not Found
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base:  5.0.0-alpha.112
    @mui/core-downloads-tracker:  5.11.3
    @mui/material: ^5.11.0 => 5.11.3
    @mui/private-theming:  5.11.2
    @mui/styled-engine:  5.11.0
    @mui/system:  5.11.2
    @mui/types:  7.2.3
    @mui/utils:  5.11.2
    @mui/x-date-pickers: ^5.0.10 => 5.0.13
    @types/react:  18.0.26
    react: ^16.13.1 => 16.14.0
    react-dom: ^16.13.1 => 16.14.0
    typescript: ^4.0.3 => 4.1.5
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #9916 
Fixes #10141

I've looked into replicating the role structure that the DayCalendar has and it seems that it's not really possible without a breaking change.
The structure needs to include a `grid -> row -> cell` structure to work properly.
We can't introduce such a structure without a breaking change, because that would change the DOM structure and possibly impact someone depending on the current structure.

The simplest and still logical solution seemed to use `radiogroup` role as the behavior of the `YearCalendar` and `MonthCalendar` components is essentially just that - a group of radio buttons from which only one can be selected at a time.

## Important note
I've looked into all possible solutions I could think of that would avoid a **breaking change** (not changing the role) but to no avail.
Essentially, our existing structure and given roles are incorrect and impossible to fix without any breaking change.
IMHO, this **breaking change** is the least we could do. The other change would also involve changing the DOM structure, which could end up being a more annoying change as compared to just a role change.
What do you think, is it a justifiable compromise for shipping within a minor release?

# Changelog
The `YearCalendar` and `MonthCalendar` items role has been changed from `button` to `radio` in order to improve the component's a11y support.
If you were relying on the mentioned components having a `button` role for items, you will need to update your usage to expect a `radio` role instead.

### CODE REVIEW

File: packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx [hunk 1]
```diff
@@ -274,6 +278,7 @@ export const MonthCalendar = React.forwardRef(function MonthCalendar<TDate>(
             onFocus={handleMonthFocus}
             onBlur={handleMonthBlur}
             aria-current={todayMonth === monthNumber ? 'date' : undefined}
+            aria-label={monthLabel}
```
Comment (LukasTy) [inline packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx:281]: Without this, the label of each of the months was a bit cumbersome in the context of a screen reader. Hearing `Sep` or `Jan` might not be enough to understand what is happening. 🤔

**Review by flaviendelangle — APPROVED** [review]
Looks great :ok_hand:
