### PR TITLE
[pickers] Support localized start of the week on `AdapterLuxon`

### LINKED ISSUE #10805: [pickers] Support changing start of week day on `AdapterLuxon`
Created from: https://github.com/mui/mui-x/issues/10790#issuecomment-1779380605

> > Do I understand it correctly that after the recent change, we no longer support changing the start of the weekday on Luxon adapter by overriding the getWeekdays method?
> 
> Yes, it's an unexpected regression that we must adress somehow I guess. I would like us to discuss if we have a better solution than this override. Two APIs that I can think about:
> 
> * a prop on `LocalizationProvider` to set the start of the date that would only be used by Luxon, just like moment uses the `dateLibInstance` prop
> * a new static method on `AdapterLuxon` (`AdapterLuxon.setCustomWeekStart`) that returns a Luxon adapter with the correct start of week

There is also the concern of whether we are willing to risk breaking something we don't know.
Luxon currently doesn't support such a feature natively, because the `Intl` API doesn't have the full support of `getWeekInfo`: https://github.com/moment/luxon/issues/954

Considering our position as "consumers" of the given library, we could simply refrain from coming up with custom implementations until a native one is provided by `luxon`. 🤔 

Relevant issue and a proposed custom adapter: https://github.com/mui/mui-x/issues/7670#issuecomment-1401929311 that we basically broke with: https://github.com/mui/mui-x/pull/10345.

**Search keywords**:

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #10805

#### Highlight 

- 🚀 The Date and Time Pickers now support localized week when using `AdapterLuxon`.

  When using Luxon 3.4.4 or higher, the start of the week will be defined by the date locale (e.g.: Sunday for `en-US`, Monday for `fr-FR`).

#### Breaking changes

- The Date and Time Pickers now use the localized week when using `AdapterLuxon` and Luxon v3.4.4 or higher is installed.
This new behavior allows `AdapterLuxon` to have the same behavior as the other adapters.

  If you want to keep the start of the week on Monday even if your locale says otherwise, you can hardcode the week settings as follows:

  ```ts
  import { Settings } from 'luxon';
  
  Settings.defaultWeekSettings = {
    firstDay: 1,
    minimalDays: Info.getMinimumDaysInFirstWeek(),
    weekend: [6, 7],
  };
  ```

### CODE REVIEW

File: packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts [hunk 1]
```diff
@@ -356,13 +371,13 @@ export class AdapterLuxon implements MuiPickersAdapter<DateTime, string> {
...
     const comparingInValueTimezone = this.setTimezone(comparing, this.getTimezone(value));
-    const diff = value.diff(comparingInValueTimezone.startOf('year'), 'years').toObject();
+    const diff = value.diff(this.startOfYear(comparingInValueTimezone), 'years').toObject();
     return diff.years! < 0;
   };
 
   public isBeforeDay = (value: DateTime, comparing: DateTime) => {
     const comparingInValueTimezone = this.setTimezone(comparing, this.getTimezone(value));
-    const diff = value.diff(comparingInValueTimezone.startOf('day'), 'days').toObject();
+    const diff = value.diff(this.startOfDay(comparingInValueTimezone), 'days').toObject();
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts:380]: Not directly related but I moved all the `startOf` / `endOf` to use our custom methods in case we have other additional behaviors in the future

File: packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts [hunk 2]
```diff
@@ -529,17 +552,16 @@ export class AdapterLuxon implements MuiPickersAdapter<DateTime, string> {
...
+    const firstDay = this.startOfWeek(this.startOfMonth(cleanValue));
+    const lastDay = this.endOfWeek(this.endOfMonth(cleanValue));
+
+    const { days } = lastDay.diff(firstDay, 'days').toObject();
 
     const weeks: DateTime[][] = [];
     new Array<number>(Math.round(days!))
       .fill(0)
       .map((_, i) => i)
-      .map((day) => cleanValue.startOf('month').startOf('week').plus({ days: day }))
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts:542]: Bonus perf improvement, we were creating ~30 time the same date

File: packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts [hunk 3]
```diff
@@ -353,7 +353,11 @@ export class AdapterLuxon implements MuiPickersAdapter<DateTime, string> {
   };
 
   public startOfWeek = (value: DateTime) => {
-    return value.startOf('week');
+    return value.startOf(
+      'week',
+      // @ts-ignore
+      { useLocaleWeeks: true },
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts:359]: The types do not include the new APIs yet, I can remove those comment later.
For older versions of Luxon, this param should be ignored and the behavior should just be like before. 
I think we can bump the minimal version of Luxon in v8 to unify everyones behavior, but keep supporting older one in v7 to avoid forcing a very-recent version.

File: docs/data/migration/migration-pickers-v6/migration-pickers-v6.md [hunk 4]
```diff
@@ -125,7 +125,24 @@ To keep the same behavior, you can replace it by `hasLeadingZerosInFormat`
  );
 ```
 
-## Removed formats
+## Date management
+
+### Use localized week with luxon
+
+The Date and Time Pickers now use the localized week when using `AdapterLuxon` and Luxon v3.4.4 or higher is installed.
```
Comment (michelengelen) [inline docs/data/migration/migration-pickers-v6/migration-pickers-v6.md:132]: can we add this to the `peerDependencies` maybe?

File: docs/data/migration/migration-pickers-v6/migration-pickers-v6.md [hunk 5]
```diff
@@ -125,7 +125,24 @@ To keep the same behavior, you can replace it by `hasLeadingZerosInFormat`
...
+This new behavior allows `AdapterLuxon` to have the same behavior as the other adapters.
```
Comment (michelengelen) [inline docs/data/migration/migration-pickers-v6/migration-pickers-v6.md:133]: This feels a bit strange to read.
Maybe:
```suggestion
This improvement aligns `AdapterLuxon` with the behavior of other adapters.
```

**Review by michelengelen — APPROVED** [review]
just a nit ... LGTM!

File: docs/data/migration/migration-pickers-v6/migration-pickers-v6.md (hunk 4 above)
Comment (flaviendelangle) [reply docs/data/migration/migration-pickers-v6/migration-pickers-v6.md:132]: We are still supporting Luxon < 3.4.4, if we change the peer deps we would force a more recent version than needed.
