### PR TITLE
[DataGrid] Add debounce option to `setEditCellValue`

### LINKED ISSUE #3729: [DataGrid] - CellEdit - Debounce revert value when enter key is pressed quickly
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Current behavior 😯

Cell commit is reversed when Enter key is pressed before debounce timed out, and cell is getting back unwantedly to edit mode.

### Expected behavior 🤔

Commit is persistant and cell stays in view mode.

### Steps to reproduce 🕹

https://codesandbox.io/s/muddy-snow-ljr8g

Steps:

1. Click a cell to edit
2. Edit it and quickly press Enter key to validate
3. Cell goes to view mode and gets back to edit mode 
4. (bonus) Press Escape and you'll lose your edit.

### Context 🔦

I list a lot of storageBoxes which need to be daily updated and use datagrid to manage the display of the data.
When operator makes a lot of changes, some mistakes can be done along the way, and current printed data may be wrong

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

System:
    OS: macOS 12.0
  Binaries:
    Node: 17.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.2 - ~/Documents/Code/ldcb-webapp/node_modules/.bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Not Found
    Firefox: 84.0.2
    Safari: 15.0
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.65 
    @mui/icons-material: ^5.3.0 => 5.3.0 
    @mui/lab: 5.0.0-alpha.65 => 5.0.0-alpha.65 
    @mui/material: ^5.3.0 => 5.3.0 
    @mui/private-theming:  5.3.0 
    @mui/styled-engine:  5.3.0 
    @mui/styles: ^5.3.0 => 5.3.0 
    @mui/system:  5.3.0 
    @mui/types:  7.1.0 
    @mui/utils:  5.3.0 
    @mui/x-data-grid-pro: ^5.3.0 => 5.3.0 
    @mui/x-license-pro:  5.3.0 
    @types/react:  17.0.38 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 

</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #3729

### CODE REVIEW

File: packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx [hunk 1]
```diff
@@ -60,18 +67,13 @@ function GridEditInputCell(props: GridRenderEditCellParams & Omit<InputBaseProps
...
-    () => debounce(api.setEditCellValue, SUBMIT_FILTER_STROKE_TIME),
-    [api.setEditCellValue],
-  );
-
   const handleChange = React.useCallback(
     (event) => {
       const newValue = event.target.value;
       setValueState(newValue);
-      debouncedSetEditCellValue({ id, field, value: newValue }, event);
+      api.setEditCellValue({ id, field, value: newValue, debounceMs }, event);
```
Comment (flaviendelangle) [inline packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx:74]: If we remove `api` from the `GridCellParams` in v6 maybe we should avoid using it in our components and use `useGridApiContext`

Non-blocking for this PR

File: packages/grid/_modules_/grid/hooks/features/editRows/useGridEditing.ts [hunk 2]
```diff
@@ -29,6 +29,8 @@ export function useGridEditing(apiRef: GridApiRef, props: DataGridProcessedProps
   useGridRowEditing(apiRef, props);
   useGridStateInit(apiRef, (state) => ({ ...state, editRows: {} }));
 
+  const debounceMap = React.useRef({});
```
Comment (flaviendelangle) [inline packages/grid/_modules_/grid/hooks/features/editRows/useGridEditing.ts:32]:
```suggestion
  const debounceMap = React.useRef<{
    [id: GridRowId]: { [field: string]: [NodeJS.Timeout, () => void] };
  }>({});
```

File: packages/grid/_modules_/grid/hooks/features/editRows/useGridEditing.ts [hunk 3]
```diff
@@ -47,21 +49,73 @@ export function useGridEditing(apiRef: GridApiRef, props: DataGridProcessedProps
...
+
+    const timeout = setTimeout(() => {
+      callback();
+      delete debounceMap.current[id][field];
+    }, debounceMs);
+
+    debounceMap.current[id][field] = [timeout, callbackToRunImmediately];
+  };
+
+  const runPendingEditCellValueChangeDebounce = React.useCallback((id, maybeField) => {
```
Comment (flaviendelangle) [inline packages/grid/_modules_/grid/hooks/features/editRows/useGridEditing.ts:87]:
```suggestion
  const runPendingEditCellValueChangeDebounce = React.useCallback<GridEditingSharedApi<"unstable_runPendingEditCellValueChangeDebounce">>((id, maybeField) => {
```

File: packages/grid/_modules_/grid/models/api/gridEditingApi.ts [hunk 4]
```diff
@@ -40,6 +40,13 @@ export interface GridEditingSharedApi {
     params: GridEditCellValueParams,
     event?: MuiBaseEvent,
   ) => Promise<boolean> | void;
+  /**
+   * @ignore - do not document.
+   */
+  unstable_runPendingEditCellValueChangeDebounce: (
```
Comment (flaviendelangle) [inline packages/grid/_modules_/grid/models/api/gridEditingApi.ts:46]: Could you document the params even if it is not on the doc ?
Because the `maybeField` is kind of cryptic to me right now. I suppose that when there is no field it because we update the whole row.

File: packages/grid/_modules_/grid/models/api/gridEditingApi.ts [hunk 5]
```diff
@@ -110,7 +117,7 @@ export interface GridCellEditingApi extends GridEditingSharedApi {
   /**
    * @ignore - do not document.
    */
-  unstable_setCellEditingEditCellValue: (params: GridEditCellValueParams) => void;
+  unstable_setCellEditingEditCellValue: (params: GridEditCellValueParams) => Promise<boolean>;
```
Comment (flaviendelangle) [inline packages/grid/_modules_/grid/models/api/gridEditingApi.ts:120]: Same, document when is the promise resolved

File: packages/grid/_modules_/grid/hooks/features/editRows/useGridEditing.ts (hunk 2 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/editRows/useGridEditing.ts]: Done. I used `Record`.

File: packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx (hunk 1 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx:74]: I'll do in another PR. There're a few components also using the API from the `api` prop.

**Review by flaviendelangle — APPROVED** [review]

**Comment by siriwatknp** [comment]
👋 The [migration PR](https://github.com/mui/mui-x/pull/3730) has been merged.

Please follow these steps to make sure that the contents are all updated. (Sorry for the inconvenience)

1. pull latest master from upstream to your branch
2. if your PR has changes on the `*.md` or demo files, you are likely to encounter conflict because all of them have been moved to the new folder.
   2.1 revert the change on those markdown files you did
   2.2 pull latest master from upstream (you should not see conflict)
   2.3 make the changes again at `docs/data/material/*`
3. run `yarn docs:api`
    - you might see the changes in `docs/pages/material/api/*` if your PR touches some of the components
    - it is okay if there is no changes

If you are struggle with the steps above, feel free to tag @siriwatknp

**Comment by SpainTrain** [comment]
Super excited to see this fixed :champagne:
