### PR TITLE
[DataGrid] Fix `onRowSelectionModelChange` firing unnecessarily on initial render

### LINKED ISSUE #14859: [data grid] Updates handled with `onRowSelectionModelChange` while using `treeData` results in an error
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/mui-datagrid-treedata-repro-ircjfa0?file=README.md,package.json

Steps:
1. Using sample component [here](https://mui.com/x/react-data-grid/tree-data/#gaps-in-the-tree)
2. Add some state for the selection model as in the live example linked above
3. Update the state in `onRowSelectionModelChange`
4. Upon rendering there is the error:
   ```
   Warning: Cannot update a component (`Repro`) while rendering a different component (`ForwardRef(DataGridPro)`). To locate the bad setState() call inside `ForwardRef(DataGridPro)`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at DataGridPro
    at div
    at Repro
   ```

### Current behavior

An error (well, a warning logged to `console.error`)

### Expected behavior

There shouldn't be an error

### Context

This fails in 7.19.0 but works in 7.18.0

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.0 undefined
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.13.3 => 11.13.3 
    @emotion/styled: 11.13.0 => 11.13.0 
    @mui/core-downloads-tracker:  6.1.2 
    @mui/material:  6.1.2 
    @mui/private-theming:  6.1.2 
    @mui/styled-engine:  6.1.2 
    @mui/system:  6.1.2 
    @mui/types:  7.2.17 
    @mui/utils:  6.1.2 
    @mui/x-data-grid:  7.19.0 
    @mui/x-data-grid-pro: 7.19.0 => 7.19.0 
    @mui/x-internals:  7.18.0 
    @mui/x-license:  7.18.0 
    @types/react:  18.3.11 
    react: 18.3.1 => 18.3.1 
    react-dom: 18.3.1 => 18.3.1 
```

Also fails on a Windows machine when run in an Electron app; the above is for the StackBlitz repro
</details>

**Search keywords**: DataGridPro treeData state error react
**Order ID**: 65425

### PR DESCRIPTION
**Pull request by MBilalShafi**
Fixes #14859 
- Before: https://codesandbox.io/p/sandbox/festive-pasteur-55fj99
- After: https://codesandbox.io/p/sandbox/bold-meadow-68z2d5

_Context:_ https://github.com/mui/mui-x/issues/14859#issuecomment-2404613592

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts [hunk 1]
```diff
@@ -442,8 +442,13 @@ export const useGridRowSelection = (
   /*
    * EVENTS
    */
+  const isFirstRender = React.useRef(true);
   const removeOutdatedSelection = React.useCallback(
     (sortModelUpdated = false) => {
+      if (isFirstRender.current) {
+        isFirstRender.current = false;
+        return;
+      }
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:451]: This could be a useful utility hook if we find ourselves needing to do it in a few places. I have seen a `useUpdateEffect` hook in another codebase that encapsulates this behaviour.

**Review by KenanYusuf — APPROVED** [review]

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts (hunk 1 above)
Comment (MBilalShafi) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:451]: `useUpdateEffect` could be helpful yes 👍 
Although in this specific case the function is not executed in an effect, rather it's binded to a Grid event, so `useUpdateEffect` might not work as expected.

**Review by cherniavskii — APPROVED** [review]

**Comment by igortas** [comment]
@MBilalShafi  @arminmeh this is is still issue in latest version.
