### PR TITLE
[pickers] Adds new `source` property to `onChange` and `onAccept` context object

### LINKED ISSUE #19830: [pickers] onAccept is fired before entering the complete date when using the input field
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/sandbox/upbeat-pasteur-8vfjyw
2. Enter a date via the input field
3. Open the console and notice that dates are being accepted before completely entering the last date part

### Current behavior

`onAccept` is fired as soon as the user start filling in the last date part. 

```
 Date accepted 2026-10-02T08:01:00.000Z
 Date accepted 2026-10-02T08:12:00.000Z 
```

I want to enter `2026-10-02 08:12` but the date is accepted as soon as I entered the first minutes digit. This contrast with the picker alternative where I actually need to click `ok` before `onAccept` is fired.

### Expected behavior

I expect `onAccept` to always behave similarly to the picker. Ideally it should only fire after the user gives the go.

### Context

My use case is to make a request after the user has selected a date. The date field is part of a "dialog" that closes after the user picked a date. Since `onAccept` is fired before the completion of the entire field, my approach is now a mess of a UX.

In v6 (version I'm upgrading from), I'd just use `onBlur` on the textfield. I don't think this approach works now.

From a developer perspective, the current behavior is a bit ambiguous as it doesn't wait for a clear signal from the user, which the picker does. If I want to make this work, I'd need to detect `onAccept` from the picker and `onAccept` from the imput field. In the second case I'd also need to somehow decide if the user is still typing...

Solutions have been discussed in https://github.com/mui/mui-x/issues/8375. I've hesitated commenting there instead of opening a new issue but #8375 can be considered `completed`?

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: onAccept

### PR DESCRIPTION
**Pull request by michelengelen**
This pull request introduces a new `source` property to the date/time picker lifecycle and event handler context, enabling clearer differentiation between changes initiated by the picker UI and those from direct field input.

The documentation is updated to explain this addition, and the codebase is refactored to consistently set and propagate the `source` property throughout picker interactions and event handlers.

Fixes #19830

### CODE REVIEW

File: packages/x-date-pickers/src/internals/components/PickerProvider.tsx [hunk 1]
```diff
@@ -308,6 +308,11 @@ export interface SetValueActionOptions<TError = string | null> {
    * It should not be defined if the change does not come from a shortcut.
    */
   shortcut?: PickersShortcutsItemContext;
+  /**
+   * Source of the change.
+   * If not provided, it will be inferred as "picker" when a `shortcut` is present, otherwise defaults to "field".
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/components/PickerProvider.tsx]: Are you sure about this inferrance?

Comment (michelengelen) [reply packages/x-date-pickers/src/internals/components/PickerProvider.tsx]: I did test this with the demos from the docs, so I think it should be picking up everything as it is intended to do. Or did I miss something?

https://github.com/user-attachments/assets/91cd4f85-8178-48fe-a088-2ccfd8cc4e3c

Comment (michelengelen) [reply packages/x-date-pickers/src/internals/components/PickerProvider.tsx]: do you think it would make sense to also include `'shortcut'` as an option?

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/components/PickerProvider.tsx]: Oh I see
It feels fragile to me. If tomorrow we add a new UI that updates the value, we can easily have it flagged as `source: "field"` by mistake.

WDYT about instead making this property required in `SetValueActionOptions`?
Or at least put `picker` as the default since it's the one triggered by all UIs except the field, and then have the field explicitely put `source: "field"`.

Side note, maybe it's worth being more precise thant `picker` (have `source: "field" | "view" | "shortcut" | ...`
But no strong preference here.

Comment (michelengelen) [reply packages/x-date-pickers/src/internals/components/PickerProvider.tsx]: yes, that makes sense ... so, top get this straight the proposal would be this:

```ts
export interface SetValueActionOptions<TError = string | null> {
  ...
  /**
   * Source of the change.
   * @default 'picker'
   */
  source: 'picker' | 'field' | 'view' | 'shortcut';
  ...
}
```

Correct?

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/components/PickerProvider.tsx]: Which UI would use "picker"? Maybe we can call it "picker-overlay" if it's toolbar, tabs etc... because everything is "picker" in the end.
Or split it into "toolbar" | "tabs" | etc...

Comment (michelengelen) [reply packages/x-date-pickers/src/internals/components/PickerProvider.tsx]: @flaviendelangle I have added a new commit with a similar approach to what you suggested, but with this it is even possible to create more general handling if the granular approach is too much. So basically I kept the source as is, but extended that with more granular sub-sources, e.g. `'picker:actionBar:ok'`. That way the user can determine easily where that change came from. WDYT?

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/components/PickerProvider.tsx]:
```ts
const clearValue = useEventCallback(() =>
    setValue(valueManager.emptyValue, { source: 'picker:actionBar:clear' }),
  );
```

This is wrong, `clearValue` can be called from anywhere, not only from the action bar.

WDYT about keeping `"field" | "view" | "unknown"`
For those two, we know that the change has to come from the requested place (for `field` it's the field that sets the source, for the view, the method is passed directly to the view and is not accessible elsewhere).
And then we can see if people ask for other places and react accordingly.

I have no idea if `actionBar:ok` is usefull, or if `actionBar` would be enough, so I propose to wait and see what users want :+1:

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/components/PickerProvider.tsx]: @michelengelen looks good to me :ok_hand: 

Just one last question: what is the reasoning behind using "picker" rather than "view"? Can it be used from elsewhere than the view?

Comment (michelengelen) [reply packages/x-date-pickers/src/internals/components/PickerProvider.tsx]: No particular reason. Maybe because it is a "Picker" overlay? Not against naming it view though.

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/components/PickerProvider.tsx]: My main struggle with "picker" is that everything is "picker" since the component itself is a picker.
At least it's the nomenclature that we are using. We have the field (the input to type the date with the keyboard) and the view (the UI to select the date with the mouse). Together (and with the shortcuts, the toolbar, the tabs and the action bar) they form the picker component.

File: docs/data/date-pickers/lifecycle/lifecycle.md [hunk 2]
```diff
@@ -206,8 +206,14 @@ The `onAccept` callback lets you get the final value selected by the user withou
 <DatePicker onAccept={(value) => sendValueToServer(value)} />
 ```
 
-:::success
-You can use the second argument passed to the `onAccept` callback to get the validation error associated with the current value:
+The `onAccept` callback receives a second argument `context` with extra information about why and how the value was accepted.
+
+- `validationError`: the validation result of the accepted value.
+- `source`: compound source describing where the acceptance originated from. Typical values include:
```
Comment (flaviendelangle) [inline docs/data/date-pickers/lifecycle/lifecycle.md]: I think we can copy paste the section you wrote for `onChange` which is clearer 👍

File: docs/data/date-pickers/lifecycle/lifecycle.md [hunk 3]
```diff
@@ -399,3 +430,37 @@ The following demo shows how to extend the Date Field component by adding an `on
...
 
 {{"demo": "ServerInteraction.js"}}
+
+### Source values in `context.source`
+
+Pickers expose a simplified `context.source` string that indicates where a change or acceptance originated from.
+The value is one of:
+
+- `'field'` — committed from the input field (typing, paste, arrow keys, clear, Enter, etc.).
+- `'picker'` — any interaction inside the picker UI (calendar/clock views, toolbar, action bar, shortcuts, dismiss, etc.).
```
Comment (flaviendelangle) [inline docs/data/date-pickers/lifecycle/lifecycle.md]:
```suggestion
- `'view'` — any interaction inside the picker's view
```

And do we agree that for toolbar, action bar etc... it's "unknown" for now?

Comment (michelengelen) [reply docs/data/date-pickers/lifecycle/lifecycle.md]: not too sure ... aren't those technically parts of the view?

**Review by flaviendelangle — APPROVED** [review]

File: docs/data/date-pickers/lifecycle/lifecycle.md (hunk 3 above)
Comment (flaviendelangle) [reply docs/data/date-pickers/lifecycle/lifecycle.md]: That's debatable
For me no, but it may just be my interpretation of our nomenclature. I don't think we clearly state if they are part of it or not.
For me the view is what changes when you switch the "view" props.

Anyway, given the current state of the MUI X picker, I'm totally fine going in either direction :+1:

Comment (michelengelen) [reply docs/data/date-pickers/lifecycle/lifecycle.md]: Makes sense, but for me this could also be part of it, as those elements are part of the overlay, which I considered the view ... maybe we should add an anatomy graphic to the docs for better alignment on it 🤷🏼
