### PR TITLE
[DataGrid] Restore focus after `GridMenu` closes

### LINKED ISSUE #10241: [datagrid] Toolbar panels don't restore focus after closing with `Escape`
### Steps to reproduce 🕹

* For  Density selector: 
   Link to live example: https://mui.com/x/react-data-grid/accessibility/#density
  
  Steps:
  1. Go to the live example link.
  2. Navigate with keyboard or click with the mouse the density button in the DataGrid.
  3. Select any option in the menu or press esc.

* For  GridActionsCellItem with showInMenu enabled: 
    Link to live example: https://mui.com/x/react-data-grid/accessibility/#density
  
  Steps:
  1. Go to the live example link.
  2. Reach the DataGrid example.
  3. Go to the last column.
  4. Press/select the icon with the three dots.
  5. Select any option in the menu or press esc.

### Current behavior 😯

The menu with the set of options disappears (as expected) after one of the options is selected or if the esc button is pressed, but the cursor ceases to exist and there is no focused element whatsoever. 

### Expected behavior 🤔

Focus should return to the button that caused the menu to appear.

### Context 🔦

Give users the capability to navigate throughout the entire DataGrid and options using only Keyboard.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Used browser: Google Chrome.
   System:
    OS: macOS 13.4
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Edge: Not Found
    Safari: 16.5
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.14 
    @mui/core-downloads-tracker:  5.14.8 
    @mui/icons-material: ^5.14.1 => 5.14.8 
    @mui/material: ^5.14.2 => 5.14.8 
    @mui/private-theming:  5.14.8 
    @mui/styled-engine:  5.14.8 
    @mui/system:  5.14.8 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.8 
    @mui/x-data-grid: ^6.10.2 => 6.12.1 
    @types/react: 18.2.17 => 18.2.17 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 5.1.6 => 5.1.6 
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by romgrk**
Closes #10241

Restore focus after the grid menu closes. Not sure about this implementation, read the comment below & the issue above.

### CODE REVIEW

File: packages/grid/x-data-grid/src/components/menu/GridMenu.tsx [hunk 1]
```diff
@@ -70,6 +70,17 @@ function GridMenu(props: GridMenuProps) {
...
+  React.useEffect(() => {
+    if (open) {
+      savedFocusRef.current =
+        document.activeElement instanceof HTMLElement ? document.activeElement : null;
+    } else {
+      savedFocusRef.current?.focus?.();
+      savedFocusRef.current = null;
+    }
+  }, [open]);
+
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/components/menu/GridMenu.tsx:83]: I have very mixed feelings about this solution. It's small and it works, but it relies on the fact that:
 - we know the focus is going to be managed downstream when this prop changes
 - this effect runs before the effect downstream (before the focus is programatically modified), which I'm not sure if we can guarantee

If you look at the previous commit, there is also another somewhat sacrilegious implementation that does the same thing but during the render phase :| which ensures we save the focus before it has a chance to be modified, but it's a side-effect in the render phase.

Please let me know if you think this is acceptable, otherwise we can look into other solutions.

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/menu/GridMenu.tsx:83]: Looks good to me.
What do you think about using `useLayoutEffect` (or rather `useEnhancedEffect`) instead?

**Review by cherniavskii — APPROVED** [review]
