### PR TITLE
[pickers] Remove `PickersDay` and `DateRangePickerDay` and promote their `2` versions as replacements

### LINKED ISSUE #21615: [question] MuiDateRangePickerDay-day applying display inline which causes the date columns to be misaligned
### The problem in depth

When displaying a basic DateRangePicker, the dates appear centered and misaligned from the day headers. Upon inspection, the MuiDateRangePickerDay-day style is applying `display: inline` which is preventing the width properties from having any effect. I do not see `display: inline` when running the sample code from the documentation in StackBlitz in the same browser. I do not have any overrides for date range pickers in my theme and I see this issue when running in Storybook and when running in my application.

```typescript
const theme = createTheme({
    cssVariables: true,
    palette: {
        action: {
            disabled: Colors.content.disabled,
            disabledBackground: Colors.disabled,
            hover: Colors.state.hover,
        },
        primary: {
            main: Colors.primary,
            contrastText: Colors.content.primary,
        },
        neutral: {
            main: Colors.neutral,
            contrastText: Colors.content.disabled,
        },
        secondary: {
            main: Colors.secondary,
            contrastText: Colors.content.secondary,
        },
        tertiary: {
            main: Colors.tertiary,
            contrastText: Colors.content.tertiary,
        },
        background: {
            default: Colors.surface.base,
            paper: Colors.surface.elevated,
        },
        text: {
            primary: Colors.content.base,
            secondary: Colors.content.alternate,
            disabled: Colors.content.disabled,
        },
        info: {
            main: Colors.primary,
            contrastText: Colors.content.info,
        },
        error: {
            main: Colors.surface.error,
            contrastText: Colors.content.error,
        },
        success: {
            main: Colors.success,
            contrastText: Colors.content.success,
        },
        divider: Colors.divider,
    },
    typography: Typography,
    shape: {
        borderRadius: tokens.sizes.borderRadius,
    },

    components: {
        MuiTab: {
            styleOverrides: {
                root: {
                    textTransform: 'none',
                    justifyContent: 'space-between',
                    fontWeight: Fonts.fontWeight.regular,
                    flexGrow: 1,
                    alignItems: 'center',
                    minHeight: '54px',
                    backgroundColor: Colors.surface.dim,
                    color: Colors.content.base,
                    marginRight: tokens.sizes.spacingBase * 1,
                    borderRadius: `${tokens.sizes.borderRadius}px ${tokens.sizes.borderRadius}px 0 0`,
                    '&.MuiButtonBase-root': {
                        marginBottom: '3px',
                    },
                    '&.Mui-selected': {
                        backgroundColor: Colors.surface.infoSubtle,
                        color: Colors.content.infoSubtle,
                        fontWeight: Fonts.fontWeight['medium'],
                    },
                    '&.Mui-disabled': {
                        backgroundColor: Colors.disabled,
                    },
                },
            },
        },
        MuiTabs: {
            styleOverrides: {
                indicator: {
                    height: '3px',
                },
            },
        },
        MuiScopedCssBaseline: {
            styleOverrides: {
                root: [
                    `
                    /* cyrillic-ext */
                    @font-face {
                    font-family: 'Roboto';
                    font-style: normal;
                    font-weight: 400;
                    src: url(https://fonts.gstatic.com/s/roboto/v32/KFOmCnqEu92Fr1Mu72xKKTU1Kvnz.woff2) format('woff2');
                    unicode-range: U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
                    }
                    /* cyrillic */
                    @font-face {
                    font-family: 'Roboto';
                    font-style: normal;
                    font-weight: 400;
                    src: url(https://fonts.gstatic.com/s/roboto/v32/KFOmCnqEu92Fr1Mu5mxKKTU1Kvnz.woff2) format('woff2');
                    unicode-range: U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
                    }
                    /* greek-ext */
                    @font-face {
                    font-family: 'Roboto';
                    font-style: normal;
                    font-weight: 400;
                    src: url(https://fonts.gstatic.com/s/roboto/v32/KFOmCnqEu92Fr1Mu7mxKKTU1Kvnz.woff2) format('woff2');
                    unicode-range: U+1F00-1FFF;
                    }
                    /* greek */
                    @font-face {
                    font-family: 'Roboto';
                    font-style: normal;
                    font-weight: 400;
                    src: url(https://fonts.gstatic.com/s/roboto/v32/KFOmCnqEu92Fr1Mu4WxKKTU1Kvnz.woff2) format('woff2');
                    unicode-range: U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF;
                    }
                    /* vietnamese */
                    @font-face {
                    font-family: 'Roboto';
                    font-style: normal;
                    font-weight: 400;
                    src: url(https://fonts.gstatic.com/s/roboto/v32/KFOmCnqEu92Fr1Mu7WxKKTU1Kvnz.woff2) format('woff2');
                    unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB;
                    }
                    /* latin-ext */
                    @font-face {
                    font-family: 'Roboto';
                    font-style: normal;
                    font-weight: 400;
                    src: url(https://fonts.gstatic.com/s/roboto/v32/KFOmCnqEu92Fr1Mu7GxKKTU1Kvnz.woff2) format('woff2');
                    unicode-range: U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF;
                    }
                    /* latin */
                    @font-face {
                    font-family: 'Roboto';
                    font-style: normal;
                    font-weight: 400;
                    src: url(https://fonts.gstatic.com/s/roboto/v32/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2) format('woff2');
                    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
                    }
            `,
                ],
            },
        },
        MuiLink: {
            styleOverrides: {
                root: {
                    '&.MuiLink-sizeLarge': {
                        fontFamily: Fonts.family,
                        fontSize: Fonts.size['base'],
                        lineHeight: Fonts.lineHeight['relaxed'],
                        letterSpacing: Fonts.letterSpacing['slightlyOpen'],
                        fontWeight: Fonts.fontWeight['medium'],
                    },
                    '&.MuiLink-sizeMedium': {
                        fontFamily: Fonts.family,
                        fontSize: Fonts.size['small'],
                        lineHeight: Fonts.lineHeight['normal'],
                        letterSpacing: Fonts.letterSpacing['open'],
                        fontWeight: Fonts.fontWeight['medium'],
                    },
                    '&.MuiLink-sizeSmall': {
                        fontFamily: Fonts.family,
                        fontSize: Fonts.size['x-small'],
                        lineHeight: Fonts.lineHeight['snug'],
                        letterSpacing: Fonts.letterSpacing['relaxed'],
                        fontWeight: Fonts.fontWeight['medium'],
                    },
                },
            },
        },

        MuiButton: {
            styleOverrides: {
                root: {
                    borderRadius: Sizes.borderRadius,
                    textTransform: 'uppercase',
                    '&.MuiButton-contained.Mui-disabled': {
                        background: Colors.surface.disabled,
                    },
                    '&.MuiButton-sizeLarge': {
                        height: '56px',
                        fontFamily: Fonts.family,
                        fontSize: Fonts.size['base'],
                        lineHeight: Fonts.lineHeight['relaxed'],
                        letterSpacing: Fonts.letterSpacing['slightlyOpen'],
                        fontWeight: Fonts.fontWeight['medium'],
                    },
                    '&.MuiButton-sizeMedium': {
                        height: '40px',
                        fontFamily: Fonts.family,
                        fontSize: Fonts.size['small'],
                        lineHeight: Fonts.lineHeight['normal'],
                        letterSpacing: Fonts.letterSpacing['open'],
                        fontWeight: Fonts.fontWeight['medium'],
                    },
                    '&.MuiButton-sizeSmall': {
                        height: '32px',

                        fontFamily: Fonts.family,
                        fontSize: Fonts.size['x-small'],
                        lineHeight: Fonts.lineHeight['snug'],
                        letterSpacing: Fonts.letterSpacing['relaxed'],
                        fontWeight: Fonts.fontWeight['medium'],
                    },
                },
            },
        },

        MuiCheckbox: {
            styleOverrides: {
                root: {
                    paddingTop: 0,
                    paddingRight: tokens.sizes.spacingBase * 2,
                    paddingBottom: 0,
                },
            },
        },
        MuiAlert: {
            styleOverrides: {
                root: {
                    '&.MuiAlert-outlined': {
                        backgroundColor: Colors.surface.elevated,
                        '& .MuiAlert-message': {
                            color: Colors.content.base,
                        },
                    },
                    '&.MuiAlert-outlinedError': {
                        borderColor: Colors.surface.error,
                    },
                    '&.MuiAlert-outlinedInfo': {
                        borderColor: Colors.surface.info,
                    },
                    '&.MuiAlert-outlinedSuccess': {
                        borderColor: Colors.surface.success,
                    },
                    '&.MuiAlert-outlinedWarning': {
                        borderColor: Colors.surface.warning,
                    },
                    '&.MuiAlert-standardError': {
                        backgroundColor: Colors.surface.errorSubtle,
                        color: Colors.content.errorSubtle,
                    },
                    '&.MuiAlert-standardInfo': {
                        backgroundColor: Colors.surface.infoSubtle,
                        color: Colors.content.infoSubtle,
                    },
                    '&.MuiAlert-standardSuccess': {
                        backgroundColor: Colors.surface.successSubtle,
                        color: Colors.content.successSubtle,
                    },
                    '&.MuiAlert-standardWarning': {
                        backgroundColor: Colors.surface.warningSubtle,
                        color: Colors.content.warningSubtle,
                    },

                    '&.MuiAlert-filledError': {
                        backgroundColor: Colors.surface.error,
                        color: Colors.content.error,
                    },
                    '&.MuiAlert-filledInfo': {
                        backgroundColor: Colors.surface.info,
                        color: Colors.content.info,
                    },
                    '&.MuiAlert-filledSuccess': {
                        backgroundColor: Colors.surface.success,
                        color: Colors.content.success,
                    },
                    '&.MuiAlert-filledWarning': {
                        backgroundColor: Colors.surface.warning,
                        color: Colors.content.warning,
                    },
                },
            },
        },
        MuiRadio: {
            styleOverrides: {
                root: {
                    paddingTop: 0,
                    paddingRight: tokens.sizes.spacingBase * 2,
                    paddingBottom: 0,
                },
            },
        },

        MuiAutocomplete: {
            defaultProps: {
                slotProps: {
                    paper: {
                        elevation: 6,
                    },
                },
            },

            styleOverrides: {
                option: {
                    paddingLeft: Sizes.spacingBase * 4,
                },
                root: {
                    '& .MuiAutocomplete-endAdornment': {
                        right: `${Sizes.spacingBase * 4}px  !important`,
                    },
                },
            },
        },

        MuiChip: {
            styleOverrides: {
                root: {
                    '&.MuiChip-outlined': {
                        backgroundColor: Colors.surface.elevated,
                    },
                },
            },
        },
        MuiFab: {
            styleOverrides: {
                root: {
                    '&.MuiFab-neutral': {
                        color: Colors.content.disabled,
                        backgroundColor: Colors.surface.disabled,
                    },
                },
            },
        },
        MuiIcon: {
            styleOverrides: {
                root: {
                    fontSize: Fonts.size['large'],
                },
            },
        },
        MuiSvgIcon: {
            styleOverrides: {
                root: {
                    fontSize: Fonts.size['large'],
                },
            },
        },
        MuiInputBase: {
            styleOverrides: {
                root: {
                    backgroundColor: Colors.surface.elevated,

                    '& .MuiInputBase-input': {
                        '&:-webkit-autofill': {
                            WebkitBoxShadow: `0 0 0 1000px ${Primary[95]} inset !important`,
                            'caret-color': Colors.content.base,
                            color: Colors.content.base,
                            WebkitTextFillColor: Colors.content.base,
                        },
                    },
                },
            },
        },

        MuiDataGrid: {
            styleOverrides: {
                footerContainer: {
                    minHeight: 'unset',
                },
                cell: {
                    borderColor: Colors.surface.disabled,
                },
                root: {
                    borderWidth: 0,
                    backgroundColor: Colors.surface.elevated,

                    '& .MuiDataGrid-toolbarContainer': {
                        borderWidth: 0,
                    },
                    '& .MuiDataGrid-columnHeaders': {
                        borderWidth: 0,
                    },
                    '& .MuiDataGrid-row:hover': {
                        backgroundColor: Colors.state.hover,
                    },
                    '& .MuiDataGrid-row:hover .MuiDataGrid-cell': {
                        backgroundColor: Colors.state.hover,
                    },
                    '& .MuiDataGrid-cell--pinnedRight, & .MuiDataGrid-columnHeader--pinnedRight':
                        {
                            backgroundColor: Colors.surface.dim + ' !important',
                        },

                    '& .MuiDataGrid-cell--withRightBorder': {
                        boxShadow: `3px 0px 4px 0px rgba(170,170,170,.4)`,
                        clipPath: `inset(0px -10px -10px -10px)`,
                    },
                    '& .MuiDataGrid-cell--withLeftBorder': {
                        boxShadow: `-3px 0px 4px 0px rgba(170,170,170,.4)`,
                        clipPath: `inset(0px -10px -10px -10px)`,
                    },

                    '& .MuiDataGrid-columnHeader--withRightBorder': {
                        borderRightWidth: 0,
                        boxShadow: `3px 0px 4px 0px rgba(170,170,170,.4)`,
                        clipPath: `inset(0px -10px -10px -10px)`,
                    },
                    '& .MuiDataGrid-columnHeader--withLeftBorder': {
                        borderLeftWidth: 0,
                        boxShadow: `-3px 0px 4px 0px rgba(170,170,170,.4)`,
                        clipPath: `inset(0px -10px -10px -10px)`,
                    },
                    '& div.MuiDataGrid-columnHeader': {
                        backgroundColor: Colors.surface.elevated,
                        borderColor: Colors.content.primary,
                        borderLeftWidth: 0,
                        color: Colors.text.alternate,
                        ...TextElements.labelLarge,
                    },
                    '& div.MuiDataGrid-columnHeader  .MuiDataGrid-columnHeaderTitle':
                        {
                            color: Colors.content.alternate,
                            ...TextElements.labelLarge,
                        },
                    '& div.MuiDataGrid-columnHeaders > [role="row"]:first-child':
                        {
                            borderBottomWidth: 2,
                            borderLeftWidth: 0,
                            borderRightWidth: 0,
                            borderTopWidth: 0,
                            borderImage: `linear-gradient(to left, ${Colors.swatch.primary[40]} 0%, ${Colors.swatch.primary[60]} 100%) 1`,
                            borderStyle: 'solid',
                        },
                    '& .MuiTablePagination-selectLabel': {
                        ...TextElements.bodySmall,
                        color: Colors.tertiary,
                    },
                    '& .MuiTablePagination-displayedRows': {
                        ...TextElements.bodySmall,
                        color: Colors.text.base,
                    },
                    '& .MuiPaginationItem-root': {
                        ...TextElements.bodySmall,
                    },
                    '& .MuiDataGrid-selectedRowCount': {
                        ...TextElements.bodySmall,
                        color: Colors.text.base,
                    },
                },
            },
        },
        MuiSwitch: {
            styleOverrides: {
                switchBase: {
                    '& .MuiSwitch-thumb': {
                        color: Colors.surface.elevated,
                    },
                    '& + .MuiSwitch-track': {
                        backgroundColor: Colors.surface.disabled,
                    },
                },
            },
        },
        MuiDialogContent: {
            styleOverrides: {
                root: {
                    padding: tokens.sizes.spacingBase * 6,
                },
            },
        },
        MuiDialogActions: {
            styleOverrides: {
                root: {
                    padding: tokens.sizes.spacingBase * 6,
                    paddingTop: 0,
                },
            },
        },
        MuiMenuList: {
            styleOverrides: {
                root: {
                    padding: 0,
                },
            },
        },
        MuiList: {
            styleOverrides: {
                root: {
                    padding: 0,
                },
            },
        },
        MuiFormHelperText: {
            styleOverrides: {
                root: {
                    marginLeft: 0,
                    marginRight: 0,
                },
            },
        },
    },
});
```
Image

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Google Chrome Version 145.0.7632.117
   System:
    OS: macOS 15.6.1
  Binaries:
    Node: 24.9.0 - /Users/ryanholstad2/.nvm/versions/node/v24.9.0/bin/node
    npm: 10.9.4 - /Volumes/Macintosh HD/Users/rholstad/Documents/kwi-components/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 145.0.7632.117
    Edge: Not Found
    Firefox: Not Found
    Safari: 18.6
  npmPackages:
    @emotion/react: ^11.13.0 => 11.14.0 
    @emotion/styled: ^11.13.0 => 11.14.1 
    @mui/core-downloads-tracker:  7.3.8 
    @mui/icons-material: ^7.3.4 => 7.3.4 
    @mui/material: ^7.3.8 => 7.3.8 
    @mui/private-theming:  7.3.8 
    @mui/styled-engine:  7.3.8 
    @mui/system:  7.3.8 
    @mui/types:  7.4.11 
    @mui/utils:  7.3.8 
    @mui/x-charts: ^7.28.0 => 7.28.0 
    @mui/x-charts-vendor:  7.20.0 
    @mui/x-data-grid:  8.13.1 
    @mui/x-data-grid-pro: 8.13.1 => 8.13.1 
    @mui/x-date-pickers:  8.27.2 
    @mui/x-date-pickers-pro: ^8.27.2 => 8.27.2 
    @mui/x-internals:  8.12.0 
    @mui/x-license:  8.12.0 
    @mui/x-telemetry:  8.12.0 
    @mui/x-virtualizer:  0.2.2 
    @types/react: ^18.3.3 => 18.3.23 
    react:  18.3.1 
    react-dom:  18.3.1 
    typescript: ^5.7.2 => 5.9.2 
```
</details>

**Search keywords**: MuiDateRangePickerDay,date range, inline, centered, misaligned

**Order ID**: 121582

### PR DESCRIPTION
**Pull request by michelengelen**
Fixes #21615.

**Summary:** This PR removes the old `PickersDay` component and promotes `PickerDay2` as the new `PickerDay`, along with doing the same for `DateRangePickerDay2` → `DateRangePickerDay`.

Key changes:

- **Removed `PickersDay`** (old multi-element day component using nested spans + `ButtonBase`) and **removed `PickerDay2`** as a separate component
- **Introduced `PickerDay`** — a single-element day component (formerly `PickerDay2`) using CSS pseudo-elements for highlights, with `--PickerDay-size` and `--PickerDay-horizontalMargin` CSS variables for sizing
- **Removed `disableMargin` prop** — replaced by the `--PickerDay-horizontalMargin` CSS variable
- **Made `onDaySelect` required** on the new `PickerDay`
- **Updated `DateRangePickerDay`** similarly (removed old version, promoted `DateRangePickerDay2`)
- **Codemods** added: `rename-pickers-day` (renames imports/theme keys), `remove-disable-margin` (replaces prop with CSS variable), included in `preset-safe`
- **Migration guide** updated in migration-pickers-v8.md with detailed instructions
- **Updated all docs demos**, API pages, theme augmentation types, and exports

### CODE REVIEW

File: packages/x-date-pickers/src/PickersDay/PickersDay.tsx [hunk 1]
```diff
@@ -53,6 +53,7 @@ const useUtilityClasses = (
 
 const styleArg = ({ theme }: { theme: Theme }) => ({
   ...theme.typography.caption,
+  display: 'block',
```
Comment (LukasTy) [inline packages/x-date-pickers/src/PickersDay/PickersDay.tsx]: Wouldn't `flex` work here?
As it stands now, this is a tiny BC for anyone who used a week picker example from our docs.

**Comment by michelengelen** [comment]
> * nitpick: this doesn't look like a pro (DateRangePicker) package change in any way

Yes, you are right ... I just took this since it was reported from that component in the bug-issue. Will change that.

> * Have you considered the change for [PickersDay2](https://deploy-preview-21739--material-ui-x.netlify.app/x/react-date-pickers/custom-components/#day) as well?

No, thanks for pointing me to that though.

>   * Side note: WDYT, @noraleonte, is that component ready to replace the OG one?
>     It's a breaking change, because of styling requirements. So, now, or wait another ~year 🙈

If possible in any way I would like to include any breaking changes now, ideally with this release. So if there is a decision to be made I would go for it now.

> * Now that I have seen this, I can not unsee it. 🙈
>   How come the day number is not vertically aligned within the button? 😂

🫣 

>   @noraleonte, have you noticed this? Do you have a better fix for this than `line-height: 1`? 🤔

File: packages/x-date-pickers/src/PickersDay/PickersDay.tsx (hunk 1 above)
Comment (michelengelen) [reply packages/x-date-pickers/src/PickersDay/PickersDay.tsx]: Would work as well ... I just took the value that was initially set for this.

**Comment by michelengelen** [comment]
> @noraleonte, have you noticed this? Do you have a better fix for this than `line-height: 1`? 🤔

@LukasTy I would love to use [text-box](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/text-box), but it seems we are a bit early for this, since it is not yet widely adopted

File: packages/x-date-pickers/src/PickersDay/PickersDay.tsx (hunk 1 above)
Comment (siriwatknp) [reply packages/x-date-pickers/src/PickersDay/PickersDay.tsx]: agree, it should not impact the docs demo.

**Comment by noraleonte** [comment]
> WDYT, @noraleonte, is that component ready to replace the OG one?
> It's a breaking change, because of styling requirements. So, now, or wait another ~year 🙈

I think it might be, but seems a bit short notice to include it in this release 🙈 I'm not worried about the component not being ready, it's more that it's a breaking change, comes with a migration guide + we need to check all the demos are still working properly (customization ones especially) 🙈 

> @noraleonte, have you noticed this? Do you have a better fix for this than line-height: 1? 🤔

I haven't noticed it but now it's bugging me. Present in `PickersDay2` as well btw 🙈 `line-height` seems to do the job here. Agree with Michel that we should wait a bit for `text-box`

**Comment by LukasTy** [comment]
So, to conclude, I see two paths:

## Lazy

- Remove change in `WeekPicker`
- Set `display: flex` on `PickersDay` and `PickersDay2`
- Add a migration page entry notifying about the change and urging upgraders to double-check if all is good in their custom implementations (should be fine in at least 99% of cases)

## Proper bad-ass 😆 

- Remove change in `WeekPicker`
- Remove `PickersDay`
- Remove https://mui.com/x/react-date-pickers/custom-components/#day demo
- Set `display: flex` on `PickersDay2`
- Rename `PickersDay2` to `PickersDay` and `DateRangePickerDay2` to `DateRangePickerDay`
- Add codemod removing the `slots={{ day: PickerDay2 }}` and `slots={{ day: DateRangePickerDay2 }}` usages
- Add migration guide entry about this component change as well as the `display: flex`
- Hope Argos is happy and do some manual testing 👌

In both cases, I'd urge setting `line-height: 1` to fix vertical alignment.

Does that sound about right, @noraleonte?

I leave the decision to @michelengelen.

**Comment by noraleonte** [comment]
Yes, that's a pretty accurate summary 👌

**Comment by michelengelen** [comment]
- [x] Fix the !isDayOutsideMonth overridesResolver bug (Critical)
- [x] Restore the license verifier in DateRangePickerDay (Critical)
- [x] Restore the DateRangePickerDayClasses type export or document removal (Critical)
- [x] Fix borderOffset → valid CSS property or remove it
- [x] Remove dead CSS classes from the interface, or add a deprecation note
- [x] Complete the migration guide with class changes, structural changes, and correct component names
- [x] Add a test file for the remove-picker-day-2 codemod
- [x] Wire up or remove the disableMargin prop from DateRangePickerDay
- [x] Restore JSDoc on the exported DateRangePickerDay

**Comment by LukasTy** [comment]
## PR Review: [PickersDay] Remove `PickersDay` and promote `PickerDay2` as a replacement

**148 files, +2146/−3454.** Removes `PickersDay`, promotes `PickerDay2` → `PickerDay`; removes `DateRangePickerDay2`, rewrites `DateRangePickerDay` from 3-nested-element wrapper to a flat `ButtonBase` with pseudo-element highlights.

---

### Critical / High

**1. Stale API doc URLs (`/pickers-day/` → should be `/picker-day/`)**

The API page was renamed from `pickers-day.js` → `picker-day.js`, so the URL is now `/picker-day/`. But ~16 generated JSON files and the `DayCalendar.tsx` source JSDoc still link to the old path:

```
"Check the [PickerDay](https://mui.com/x/api/date-pickers/pickers-day/) component."
```

These will all be broken links on the docs site. Affects `date-calendar.json`, `date-picker.json`, all desktop/mobile/static picker variants, and their translation files.

**2. `PickerDayClasses` not exported**

The old `PickersDay/index.ts` exported `PickersDayClasses`. The new `PickerDay/index.ts` only exports `PickerDayClassKey`, **not** `PickerDayClasses`. Users typing `classes: Partial<PickersDayClasses>` have no replacement type to import.

**3. `defaultMuiPrevented` no longer set in click handlers**

Old `PickersDay` set `event.defaultMuiPrevented = true` in `handleClick` (via `MuiEvent`). The new `DateRangePickerDay` (which no longer wraps `PickersDay`) uses plain `React.MouseEvent` and does not set this flag. If parent components rely on it to avoid double-processing click events, behavior will break silently.

**4. `disableMargin` default behavior change in `DateRangePickerDay`**

The old `DateRangePickerDay` always hardcoded `disableMargin={true}` on the inner `PickersDay`. Now `DateRangePickerDay` is standalone and `disableMargin` defaults to `false`. This means range picker days will render with margins by default. The `CustomDateRangePickerDay` demo now explicitly passes `disableMargin: true`, hinting this may need to be the internal default for `DateRangeCalendar`, or at least mentioned prominently in the migration guide.

---

### Medium

**5. Codemod `rename-pickers-day` misses identifiers**

The rename map covers 7 identifiers but misses:

- `PickersDayClasses` → `PickerDayClasses`
- `getPickersDayUtilityClass` → `getPickerDayUtilityClass`

Both were public exports. Users importing them won't get their code updated.

**6. No codemod for `PickerDay2*` → `PickerDay*` type renames**

The `remove-picker-day-2` codemod only strips `slots={{ day: PickerDay2 }}`. Users who imported `PickerDay2Props`, `PickerDay2OwnerState`, `pickerDay2Classes`, `DateRangePickerDay2Props`, etc. have no automated migration to the new non-"2" names.

**7. `data-testid` changes may break user/integration tests**

- `DateRangePreview` testid is gone entirely (not mentioned in migration guide)
- Users who queried nested `DateRangePickerDay` button inside `DateRangeHighlight` will break since it's now a single element
- `PickerDay` now respects a custom `data-testid` prop, falling back to `'day'` — subtle behavior change

**8. Migration guide gaps**

The guide documents `DateRangePickerDay` class renames well but omits:

- `outsideCurrentMonth` → `dayOutsideMonth` rename
- `firstVisibleCell` / `lastVisibleCell` → removed with no replacement
- `hiddenDayFiller` → `fillerCell`
- `PickersDay` class key: `dayWithMargin` removed, replaced by inverted `dayWithoutMargin` (logic flip)
- `hiddenDaySpacingFiller` → `fillerCell`
- No codemod for `DateRangePickerDay` or `PickerDay` class key renames

**9. Missing `PickerDay` entry in `index.md`**

The old `PickersDay` entry is removed from `docs/pages/x/api/date-pickers/index.md` but no `PickerDay` replacement is added. The API index page will be missing the link.

---

### Low / Cosmetic

**10. Stale comment in `dimensions.ts`**

The pro package's `dimensions.ts` has a comment saying `// adding the extra height of the range day element height difference (40px vs 36px)` but `DAY_RANGE_SIZE` is now 36 (same as `DAY_SIZE`), so there's no longer a difference.

**11. Today indicator visual change**

Old `PickersDay` used `border: 1px solid` (adds to dimensions). New `PickerDay` uses `outline: 1px solid` with `outlineOffset: -1` (doesn't affect layout). Subtle visual difference, not documented.

**12. Hover styles removed for unselected range days**

Old `DateRangeCalendar` had `dayOutsideRangeInterval` hover with a grey border. This block was removed. Days outside the selection range no longer show a hover border.

**13. Drag styling simplified**

Old code applied `opacity: 0.6` to non-start/end highlighted days during drag. New code only sets `cursor: grabbing`. The opacity during drag is lost.

**14. `DateRangePickerDayProps` has duplicate callback declarations**

Extends `PickerDayProps` (which already declares `onFocus`, `onBlur`, `onKeyDown`, etc.) but then re-declares the same callbacks. Compatible in TypeScript but unnecessary type surface.

**15. Internal styled component renames add noise**

`PickersCalendarDayRoot` → `PickerCalendarDayRoot`, etc. in `DayCalendar.tsx` are purely internal variable renames. They add ~100 lines of diff noise while the MUI slot name `MuiDayCalendar` correctly stays the same.

**16. Translation file sourced from wrong origin**

`date-range-picker-day-2/date-range-picker-day-2.json` is renamed to `picker-day/picker-day.json`. The `PickerDay` translations should arguably derive from `picker-day-2` or `pickers-day`, not the range variant.

---

### What looks good

- License verifier properly preserved in `DateRangePickerDay`
- The `!isDayOutsideMonth` overridesResolver bug from `DateRangePickerDay2` is fixed
- `display: flex` and `line-height: 1` added per review discussion
- `isDaySelected` logic updated to include individual selections — well documented
- Codemod for slot removal (`remove-picker-day-2`) is solid, handles variable-based slots
- Filler cells now render as `<div>` (via `as="div"`) instead of `ButtonBase` — better semantics/a11y
- Bundle size decreased nicely (−3.68KB / −9.21KB)
- `styleOverrides` test added for `DateRangePickerDay`
- No stale references to old names in production code

**Comment by LukasTy** [comment]
On another note, seeing that even the theme entry keys changed, I'm slightly hesitant about completely ditching the old day component.
What would be your take on:
- Keep the old day components as `PickersDayOld`
- Add `deprecated` and a warning in the console on dev mode if they are rendered

On the other hand, we can introduce these additions during the stable if there is enough people having trouble migrating away, even with codemods and guides. 🤔

**Comment by LukasTy** [comment]
This demo needs some serious tweaking to make it look like before.
Screenshot 2026-03-25 at 15 44 31

Maybe AI can help?

**Comment by LukasTy** [comment]
Unrelated note, but date range dragging seems completely broken on `next`. 🙈

**Comment by LukasTy** [comment]
I'm not sure we should be re-adding `disableMargin` prop to the component.
It was there only to serve as a dirty override to achieve continuous selected range background highlighting.
Given that now it is done with pseudo-elements (`::before` and `::after`), I think the prop should be avoidable. 🤔

**Comment by LukasTy** [comment]
> Unrelated note, but date range dragging seems completely broken on `next`. 🙈

Please disregard this comment. It must have been some caching problem. 🤷 
It works as expected, but there is some selected day regression when it is in the selected range:
That `opacity` style rule looked pretty relevant. 🤔 

https://github.com/user-attachments/assets/43cf3920-a797-46d1-83e0-84f34ef9068e

File: docs/data/date-pickers/custom-components/custom-components.md [hunk 2]
```diff
@@ -188,34 +188,6 @@ You can pass a custom component to replace the year button, as shown below:
...
-
-{{"demo": "PickerDay2Demo.js"}}
-
-Use the `--PickerDay-horizontalMargin` and `--PickerDay-size` CSS variables to easily customize the dimensions and spacing of the day slot.
-
-{{"demo": "PickerDay2DemoCSSVars.js"}}
-
-Customize the look and feel by creating a custom theme with `styleOverrides`.
-
-{{"demo": "PickerDay2DemoCustomTheme.js"}}
```
Comment (LukasTy) [inline docs/data/date-pickers/custom-components/custom-components.md:217]: Looking at the info here, I think we need to backtrack the removal of it.
It explains why we moved towards this new `day` component with a simpler structure.
Could we rephrase it and bring back the demos?
Then we could add a small piece of information and link to this section in the migration guide.

People need to know why and what's better and easier to do in the new version.

WDYT?

File: docs/data/date-pickers/date-calendar/WeekPicker.tsx [hunk 3]
```diff
@@ -56,19 +56,18 @@ const isInSameWeek = (dayA: Dayjs, dayB: Dayjs | null | undefined) => {
...
   const { day, selectedDay, hoveredDay, ...other } = props;
 
   return (
-    <CustomPickersDay
+    <CustomPickerDay
       {...other}
       day={day}
-      sx={{ px: 2.5 }}
-      disableMargin
+      sx={{ px: 2.5, mx: 0 }}
```
Comment (LukasTy) [inline docs/data/date-pickers/date-calendar/WeekPicker.tsx]: Given that the new day components support CSS variables for margin and width, I propose this instead in the styled day component:
```css
'--PickerDay-horizontalMargin': 0,
// Ensures the day increases width, accounting for the padding, matching the width of the week number cell
boxSizing: 'content-box',
paddingLeft: '2px',
paddingRight: '2px',
```
It no longer fights with the defined CSS variable size. WDYT?

File: docs/data/date-pickers/date-range-calendar/CustomDateRangePickerDay.tsx [hunk 4]
```diff
@@ -48,6 +48,7 @@ export default function CustomDateRangePickerDay() {
         <DateRangeCalendar
           defaultValue={[dayjs('2022-04-17'), dayjs('2022-04-21')]}
           slots={{ day: DateRangePickerDay }}
+          slotProps={{ day: { sx: { px: 2.5, mx: 0 } } }}
```
Comment (LukasTy) [inline docs/data/date-pickers/date-range-calendar/CustomDateRangePickerDay.tsx]: Same here, could we override the style in a single place and in a way that relies on the new styling paradigm?
```css
'--PickerDay-horizontalMargin': 0,
// Ensures the day increases width, accounting for the padding, matching the width of the week number cell
boxSizing: 'content-box',
paddingLeft: '2px',
paddingRight: '2px',
```

File: docs/src/modules/components/overview/pickers/themes/customTheme.ts [hunk 5]
```diff
@@ -314,7 +314,7 @@ export const getCustomTheme = (mode: PaletteMode, config: Config): ThemeOptions
             minWidth: theme.mixins.density.width * 7 + theme.mixins.density.spacing * 6,
             '&.MuiDayCalendar-slideTransition': {
               minWidth: theme.mixins.density.width * 7 + theme.mixins.density.spacing * 6,
-              minHeight: theme.mixins.density.height * 7 + theme.mixins.density.spacing * 6,
+              minHeight: theme.mixins.density.height * 7,
```
Comment (LukasTy) [inline docs/src/modules/components/overview/pickers/themes/customTheme.ts]: This was incorrect.
It should be like this (6 weeks and 6 margins):

```suggestion
              minHeight: theme.mixins.density.height * 6  + theme.mixins.density.spacing * 6,
```

File: docs/src/modules/components/overview/pickers/themes/customTheme.ts [hunk 6]
```diff
@@ -389,45 +389,57 @@ export const getCustomTheme = (mode: PaletteMode, config: Config): ThemeOptions
...
+                  backgroundColor: theme.palette.grey[700],
+                }),
               },
-              [`&.${dateRangePickerDayClasses.rangeIntervalDayHighlight}`]: {
-                borderRadius: theme.shape.borderRadius,
+
+            [`&.${dateRangePickerDayClasses.previewStart}:hover, &.${dateRangePickerDayClasses.previewEnd}:hover`]:
+              {
+                outline: '1px solid #FFF',
+                outlineOffset: '-1px',
```
Comment (LukasTy) [inline docs/src/modules/components/overview/pickers/themes/customTheme.ts:395]: The results seem slightly different.
The changes, as well, kind of don't correlate. 🙈 

### Current

https://github.com/user-attachments/assets/e530a130-4d1c-4411-b194-f018c0416fab

### This branch

https://github.com/user-attachments/assets/3206fb59-50e0-4f31-b4a0-c6b9458da747

File: docs/src/modules/components/overview/pickers/CustomLayoutRangePicker.tsx [hunk 7]
```diff
@@ -119,6 +119,9 @@ export default function CustomLayoutPicker({ layout }: { layout: Layout }) {
         shortcuts: {
           items: shortcutsItems,
         },
+        day: {
+          sx: { mx: 0 },
+        },
```
Comment (LukasTy) [inline docs/src/modules/components/overview/pickers/CustomLayoutRangePicker.tsx]: As in other places, we should add `'--PickerDay-horizontalMargin': 0,` in the `customTheme.MuiDateRangePickerDay.styleOverrides.root` instead.

File: docs/src/modules/components/PickersPlayground.tsx [hunk 8]
```diff
@@ -391,7 +391,7 @@ export default function PickersPlayground() {
           },
         }),
         day: {
-          disableMargin: disableDayMargin,
+          sx: disableDayMargin ? { mx: 0 } : undefined,
```
Comment (LukasTy) [inline docs/src/modules/components/PickersPlayground.tsx]: This no longer makes sense.
The prop has been removed from the component. The demo showcases how different props change the components and I think this particular switch should be removed.

File: docs/translations/api-docs/date-pickers/date-calendar/date-calendar.json [hunk 9]
```diff
@@ -146,7 +146,7 @@
       }
     },
     "showDaysOutsideCurrentMonth": {
-      "description": "If <code>true</code>, days outside the current month are rendered:<br>- if <code>fixedWeekNumber</code> is defined, renders days to have the weeks requested.<br>- if <code>fixedWeekNumber</code> is not defined, renders day to fill the first and last week of the current month.<br>- ignored if <code>calendars</code> equals more than <code>1</code> on range pickers."
+      "description": "If <code>true</code>, days outside the current month are shown."
```
Comment (LukasTy) [inline docs/translations/api-docs/date-pickers/date-calendar/date-calendar.json]: WDYT, could we keep the previous description?
It feels like it was useful and explained the interconnect between props.

File: packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.test.tsx [hunk 10]
```diff
@@ -249,6 +249,39 @@ describe('<DateRangeCalendar />', () => {
         expect(document.activeElement).toHaveAccessibleName('2');
       });
 
+      it('should emit "onChange" when drag events target a nested day element', () => {
```
Comment (LukasTy) [inline packages/x-date-pickers-pro/src/DateRangeCalendar/DateRangeCalendar.test.tsx]: Could we extract this addition to https://github.com/mui/mui-x/pull/21868?
Or do you believe it has a place here?

File: packages/x-date-pickers-pro/src/DateRangePickerDay/dateRangePickerDayClasses.ts [hunk 11]
```diff
@@ -4,40 +4,28 @@ import generateUtilityClasses from '@mui/utils/generateUtilityClasses';
...
-  /** Styles applied to the day element. */
-  day: string;
-  /** Styles applied to the day element if `isHighlighting=false`. */
-  dayOutsideRangeInterval: string;
-  /** Styles applied to the day element if `selected=false` and `isHighlighting=true`. */
-  dayInsideRangeInterval: string;
-  /** Styles applied to the day element if `selected=false`. */
-  notSelectedDate: string;
+  previewed: string;
+  draggable: string;
```
Comment (LukasTy) [inline packages/x-date-pickers-pro/src/DateRangePickerDay/dateRangePickerDayClasses.ts:44]: We need all of these to have descriptions to have proper API Doc.

File: packages/x-date-pickers-pro/src/internals/constants/dimensions.ts [hunk 12]
```diff
@@ -2,6 +2,6 @@ import { DAY_MARGIN, VIEW_HEIGHT } from '@mui/x-date-pickers/internals';
 
 export { DAY_MARGIN } from '@mui/x-date-pickers/internals';
 
-export const DAY_RANGE_SIZE = 40;
+export const DAY_RANGE_SIZE = 36;
```
Comment (LukasTy) [inline packages/x-date-pickers-pro/src/internals/constants/dimensions.ts]: Since it's now the same as `DAY_SIZE`, could we import and use that?

File: packages/x-date-pickers/src/PickerDay/PickerDay.tsx [hunk 13]
```diff
@@ -43,28 +43,30 @@ const useUtilityClasses = (
...
       ownerState.isDayFillerCell && styles.fillerCell,
     ];
   },
-})<{ ownerState: PickerDay2OwnerState }>(({ theme }) => ({
+})<{ ownerState: PickerDayOwnerState }>(({ theme }) => ({
   '--PickerDay-horizontalMargin': `${DAY_MARGIN}px`,
   '--PickerDay-size': `${DAY_SIZE}px`,
   ...theme.typography.caption,
+  lineHeight: 1,
+  display: 'flex',
```
Comment (LukasTy) [inline packages/x-date-pickers/src/PickerDay/PickerDay.tsx:69]: Would you agree that we should propagate these changes to v8 to actually fix the issue?

P.S. It looks like we need to add `flex: 1`.

https://github.com/user-attachments/assets/f1189815-7a5e-4cce-a280-fda55e1588e2

File: packages/x-date-pickers/src/PickerDay/PickerDay.types.ts [hunk 14]
```diff
@@ -0,0 +1,133 @@
...
+  /**
+   * If `true`, the day is the last visible cell of the month.
+   * @default false
+   */
+  isLastVisibleCell: boolean;
+  /**
+   * If `true`, the day is being animated.
+   * @default false
+   */
+  isAnimating?: boolean;
```
Comment (LukasTy) [inline packages/x-date-pickers/src/PickerDay/PickerDay.types.ts:78]: @noraleonte am I missing something? But it looks unused. 🤔

File: packages/x-date-pickers/src/PickerDay/PickerDay.types.ts [hunk 15]
```diff
@@ -0,0 +1,133 @@
...
+   */
+  showDaysOutsideCurrentMonth?: boolean;
+}
+
+export interface PickerDayProps
+  extends
+    ExportedPickerDayProps,
+    Omit<
+      ButtonBaseProps,
+      'classes' | 'onFocus' | 'onBlur' | 'onKeyDown' | 'onMouseDown' | 'onClick' | 'onMouseEnter'
```
Comment (LukasTy) [inline packages/x-date-pickers/src/PickerDay/PickerDay.types.ts]: 🙈 
https://deploy-preview-21739--material-ui-x.netlify.app/x/api/date-pickers/picker-day/#picker-day-prop-LinkComponent
```suggestion
      'classes' | 'onFocus' | 'onBlur' | 'onKeyDown' | 'onMouseDown' | 'onClick' | 'onMouseEnter' | 'LinkComponent'
```

File: docs/src/modules/components/overview/pickers/themes/customTheme.ts (hunk 5 above)
Comment (michelengelen) [reply docs/src/modules/components/overview/pickers/themes/customTheme.ts]: Yes, but that stretches the transition container too much and leaves a blank row at the bottom. This looks weird

Comment (LukasTy) [reply docs/src/modules/components/overview/pickers/themes/customTheme.ts]: Are you sure?
I checked locally, and it sets exactly the same height as the actual content height. 🙈 🤷

Comment (michelengelen) [reply docs/src/modules/components/overview/pickers/themes/customTheme.ts]: https://github.com/user-attachments/assets/6f117306-6cb2-4d2b-94c0-d4d2491b100f

Seems, like it is still a tiny bit too big, but hardly noticable

Should we have a deeper look after merging?

File: docs/src/modules/components/overview/pickers/themes/customTheme.ts (hunk 6 above)
Comment (michelengelen) [reply docs/src/modules/components/overview/pickers/themes/customTheme.ts:395]: same as above ... I would either handle this in a follow-up, or you need to take over next week

Comment (LukasTy) [reply docs/src/modules/components/overview/pickers/themes/customTheme.ts:395]: I can finalize the PR, don't stress it. 👌

File: docs/src/modules/components/overview/pickers/themes/customTheme.ts (hunk 5 above)
Comment (LukasTy) [reply docs/src/modules/components/overview/pickers/themes/customTheme.ts]: Addressed it with my suggestion. Confirmed the heights are aligned.
Also fixed the existing inconsistency in `compact` density.
Screenshot 2026-03-31 at 10 03 26

File: docs/src/modules/components/overview/pickers/themes/customTheme.ts (hunk 6 above)
Comment (LukasTy) [reply docs/src/modules/components/overview/pickers/themes/customTheme.ts:395]: Fixed this with https://github.com/mui/mui-x/pull/21739/changes/e567d9c28ab7c0b745fe91cf7960ead79067f9fe.

File: packages/x-date-pickers/src/PickerDay/PickerDay.tsx (hunk 13 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/PickerDay/PickerDay.tsx:69]: I removed it, since it's causing this issue and also no longer seems necessary after the latest CSS changes. 🤷 
Screenshot 2026-03-31 at 10 20 35

File: packages/x-date-pickers/src/PickerDay/PickerDay.types.ts (hunk 14 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/PickerDay/PickerDay.types.ts:78]: Nevermind, it was already here, just not documented (didn't have JSDoc ).

**Comment by LukasTy** [comment]
Comments on https://github.com/mui/mui-x/pull/21739#pullrequestreview-4034925354:



> 1. Bug in `overridesResolver` (Medium severity)

Yes, it's an intentional bugfix.

> 2. `onDaySelect` null check added without explanation

Reverted the prop to be required.

> 3. `preset-safe` codemod ordering

Added a `preset-safe` integration coverage.

> 4. Missing test coverage for `PickerDay` itself

I removed the newly added classes, since they were not on the original component, nor the `PickerDay2` had it.

> 5. Theme component name backwards compatibility

It's handled by the codemods.

> 6. `DateRangePickerDay` rewrite is large

Claude, it's not a rewrite; we replaced the `DateRangePickerDay` with `DateRangePickerDay2` whilst renaming it. ℹ️

**Comment by LukasTy** [comment]
# Claude Opus 4.6 review

## Summary

**Author:** @michelengelen (with significant follow-up work by @LukasTy)  
**Status:** 1 approval (flaviendelangle), 2 pending reviewers (mj12albert, siriwatknp)  
**Labels:** `breaking change`, `scope: pickers`, `type: enhancement`  
**Stats:** +3,688 / -3,257 across 168 files | 108 commits  
**Fixes:** [#21615](https://github.com/mui/mui-x/issues/21615)  
**State:** Has merge conflicts (marked `PR: out-of-date`)

---

## What it does

1. **Removes `PickersDay`** (multi-element legacy component) and **`PickerDay2`** / **`DateRangePickerDay2`** (the "v2" components)
2. **Renames** `PickerDay2` -> `PickerDay`, `DateRangePickerDay2` -> `DateRangePickerDay` (so the improved implementations take the canonical names)
3. **Removes `disableMargin` prop** (margin is now controlled via `--PickerDay-horizontalMargin` CSS variable)
4. **Simplifies DOM** from multi-element (nested `<span>` + `<ButtonBase>`) to single `<ButtonBase>` with `::before`/`::after` pseudo-elements for selection/preview highlights
5. **Adds 5 codemods** for automated migration
6. **Comprehensive v8->v9 migration docs** with before/after examples

---

## Strengths

### 1. Excellent migration tooling
5 codemods cover all facets:
- `rename-pickers-day` (`PickersDay` -> `PickerDay`, all types, imports, theme names)
- `rename-picker-day-2` (`PickerDay2`/`DateRangePickerDay2` -> canonical names)
- `remove-picker-day-2` (removes now-redundant `slots={{ day: PickerDay2 }}`)
- `rename-picker-classes` (class key renames)
- `remove-disable-margin` (replaces `disableMargin` with CSS variable approach)

Each has `actual.spec.tsx` / `expected.spec.tsx` test fixtures. The `preset-safe` now has integration test coverage per LukasTy's follow-up commit.

### 2. Well-documented breaking changes
The migration guide in migration-pickers-v8.md clearly covers: component renames, class renames, `disableMargin` removal, `data-testid` changes, selection behavior changes, all with before/after code examples.

### 3. Architecture improvement
Moving from multi-element to single-element + pseudo-elements for range highlights:
- Reduces DOM complexity
- Fixes the `display: inline` alignment bug ([#21615](https://github.com/mui/mui-x/issues/21615))
- CSS variables (`--PickerDay-size`, `--PickerDay-horizontalMargin`) make theming more ergonomic
- `line-height: 1` / `display: flex` fix vertical text alignment

### 4. Bundle size win
`@mui/x-date-pickers`: -3.77KB (-1.64%)  
`@mui/x-date-pickers-pro`: -9.17KB (-2.81%)

---

## Issues found

### Critical

**1. Merge conflicts** - The PR has unresolved conflicts with `master` (flagged by the bot 2 days ago). Must be resolved before merge.

### Medium

**2. `overridesResolver` bug in `PickerDay2` (existing, to be fixed by this PR)**  
The current PickerDay2.tsx line 60 has:
```ts
!ownerState.isDayOutsideMonth && styles.dayOutsideMonth,
```
This applies `dayOutsideMonth` styles when the day is *inside* the month - logically inverted. The same bug exists in DateRangePickerDay2.tsx line 121. According to the PR discussion, LukasTy confirmed this is an intentional bugfix being addressed in the PR (changed to `ownerState.isDayOutsideMonth`). Good.

**3. `DateRangePickerDay2` directory still exists**  
The `DateRangePickerDay2/` directory with all its files still exists on `master`. The PR needs to fully remove it, along with removing the `PickerDay2/` directory and the old `PickersDay/` directory. Confirm these are all cleaned up in the PR branch.

**4. `usePickerDayOwnerState` still accepts `disableMargin`**  
The shared hook usePickerDayOwnerState.ts still has `disableMargin` in its parameter interface and in the returned owner state. If `disableMargin` is being removed from the public API, this internal hook needs updating too, or at minimum the prop should become optional/unused in the new `PickerDay`.

### Low

**5. 108 commits**  
This is a lot of commits for a single PR. History is noisy with many "merge master", "fix", "tweak", "rebuild" commits. Consider squash-merging to keep the history clean.

**6. `DateRangePickerDay` test note**  
The test file DateRangePickerDay.test.tsx has a skip comment: `"TODO: Fix DateRangePickerDays is not spreading props on root"`. This pre-existing issue persists into the new component.

**7. Demo `WeekPicker` removes `sx={{ px: 2.5 }}` and `disableMargin`**  
The `WeekPicker.tsx` demo drops `sx={{ px: 2.5 }}` and `disableMargin` without replacement. The new CSS variable approach should be documented in the demo or the migration guide should explicitly address the WeekPicker use case (setting `--PickerDay-horizontalMargin: 0`).

**8. `customTheme.ts` complexity**  
The overview demo theme file went from using simple class-based styleOverrides (`rangeIntervalDayHighlight`, `rangeIntervalDayPreview`, etc.) to nested pseudo-element selectors (`::before`, `::after`). This is functionally correct but more complex for users to customize. The migration guide should perhaps note this shift in approach.

---

## Checklist

| Item | Status |
|---|---|
| Merge conflicts resolved | Blocking |
| 1 approval (flaviendelangle) | Done |
| 2 pending reviewers (mj12albert, siriwatknp) | Pending |
| Codemods have test coverage | Done |
| `preset-safe` integration test | Done (eaf01be) |
| Migration docs | Done |
| API JSON pages regenerated | Done |
| Translation files updated | Done |
| Bundle size acceptable | Done (-1.6% / -2.8%) |
| Demo files updated | Done |
| `proptypes` / `docs:api` regenerated | Done |
| `disableMargin` -> CSS variable documented | Done |
| Argos visual regression | Needs check |

---

## Merge Readiness Score: **7/10**

**Breakdown:**
- **Code quality:** 8/10 - Clean architecture, good patterns, CSS variable approach is solid
- **Test coverage:** 7/10 - Codemods well tested; component-level tests could be stronger (existing tests pass but few new ones added for the renamed component)
- **Documentation:** 9/10 - Migration guide is thorough and actionable
- **CI/Merge status:** 4/10 - Has merge conflicts, `PR: out-of-date` label, 2 requested reviewers haven't approved
- **Breaking change management:** 9/10 - 5 codemods, preset-safe integration, clear migration path

**Blockers to merge:**
1. Resolve merge conflicts with `master`
2. Get remaining reviewer approvals (mj12albert, siriwatknp)
3. Verify Argos visual regression tests pass after conflict resolution

**Comment by LukasTy** [comment]
The last review seems like it is stale or AI borked it quite a bit. 🙈 

## A final re-review

### Status

- All previous review items have been addressed
- `onDaySelect` is correctly required in both types (`PickerDayProps`) and PropTypes (`.isRequired`)
- Old directories (`PickersDay/`, `PickerDay2/`, `DateRangePickerDay2/`) are fully removed from the PR branch
- `disableMargin` is fully removed from `usePickerDayOwnerState`, types, and components
- Codemod preset-safe ordering is correct and well-documented with a comment explaining why `removePickerDay2` must run before `renamePickerDay2`
- Theme augmentation is clean: `MuiPickerDay` and `MuiDateRangePickerDay` only, no stale names
- Export JSONs are clean; no `PickerDay2`, `PickersDay`, or `DateRangePickerDay2` entries remain
- Preset-safe integration test covers all 6 codemods with idempotency check

### Remaining issues

**1. `borderRadius` inconsistency between `PickerDay` and `DateRangePickerDay`** (low)

`PickerDay` uses `borderRadius: 'calc(var(--PickerDay-size) / 2)'`, which correctly adapts when a user overrides `--PickerDay-size`. `DateRangePickerDay` hardcodes `borderRadius: '18px'`. If a user sets `--PickerDay-size: 24px`, `PickerDay` becomes a circle (radius 12px) but `DateRangePickerDay` retains radius 18px. Consider using the same `calc()` expression in `DateRangePickerDay` for consistency.

**2. `remove-disable-margin` codemod missing from migration guide** (low)

The migration guide documents 5 codemods: `rename-picker-classes`, `rename-field-ref`, `rename-picker-day-2`, `remove-picker-day-2`, and `rename-pickers-day`. But `remove-disable-margin` is missing — even though it exists, has tests, is in `preset-safe`, and is documented in the codemod README.md. Users reading only the migration guide would miss it.

**3. No blockers remain**

The merge conflicts have been resolved (latest commit is a merge with master). The code is clean, well-structured, and the codemods + migration docs are comprehensive.

### Summary

The PR is in good shape. The two items above are minor polish — neither blocks merging. The architecture (single-element day with pseudo-elements for highlights), CSS variable approach, and codemod coverage are all solid.
