### PR TITLE
[charts] Fix line highlight position with RTL

### LINKED ISSUE #16987: [charts] dots highlights places are incorrect in RTL
### Steps to reproduce

Link to live example:
We could just look at the Line demo
https://mui.com/x/react-charts/lines/

Steps:

1. Set the direction of the settings to Right to Left

### Current behavior

The dots highlights are misplaced when dir=rtl.

Image

### Expected behavior

The dots highlights appears when the dir=ltr.

Image

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
I am using Firefox 136.0.1 (64-bit)

System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 22.5.1 - X:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - X:\Program Files\nodejs\npm.CMD
    pnpm: 10.6.3 - X:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (134.0.3124.68)
  npmPackages:
    @emotion/react: ^11.14.0 => 11.14.0
    @emotion/styled: ^11.14.0 => 11.14.0
    @mui/icons-material: ^6.4.1 => 6.4.1
    @mui/material: ^6.4.1 => 6.4.1
    @mui/system: ^6.4.3 => 6.4.3
    @mui/x-charts: ^7.27.1 => 7.27.1
    @mui/x-data-grid: ^7.27.3 => 7.27.3
    @types/react: ^18.3.18 => 18.3.18
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    typescript: ~5.6.2 => 5.6.3

</details>

**Search keywords**: mui mui-x charts highlights rtl

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #16987

The RTL impacted the `styled()` result. We could [use the `/* @noflip */`](https://mui.com/material-ui/customization/right-to-left/#opting-out-of-rtl-locally) to fix that. But I moved this style to SVG attributes such that:
1. It's not impacted anymore by the `styled`
2. It reduced the style specificity and reduce the usage of material lib

### CODE REVIEW

File: packages/x-charts/src/LineChart/LineHighlightElement.tsx [hunk 1]
```diff
@@ -104,6 +96,9 @@ function LineHighlightElement(props: LineHighlightElementProps) {
       pointerEvents="none"
       ownerState={ownerState}
       className={classes.root}
+      transform={`translate(${x}, ${y})`}
```
Comment (bernardobelchior) [inline packages/x-charts/src/LineChart/LineHighlightElement.tsx:99]: Unlike the CSS version, the SVG transform does not require a comma ([source](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform#translate)).

```suggestion
      transform={`translate(${x} ${y})`}
```

The CSS version should also work, but since there's [this warning](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform#transform_functions) I'm not sure if it's better to be safe:

image

**Review by bernardobelchior — APPROVED** [review]

**Comment by alexfauquette** [comment]
It seems I will need to swich from one attribute to another according the the react version 🙃
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72218

**Review by bernardobelchior — APPROVED** [review]
