### PR TITLE
[pickers] Rework the date lifecycle in `usePickerState` 

### LINKED ISSUE #4358: [Date Time Picker] Calls onChange(null) on ClickAway during edit

### LINKED ISSUE #4395: [DatePicker] Changes value after closing it
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Calendar Picker displays a calendar with the current date being highlighted.
If you then select the Year view-mode, and go to the previous year and the exact same date, you'll find out that the same date is selected, and if you exit the menu the date returns to the previous year.

### Expected behavior 🤔

Calendar Picker should either, allow me to select the same day from the previous year, and not overwrite it when the picker is closed.

This doesn't happen, if instead you change each month until you find the one you're looking for.

### Steps to reproduce 🕹

Steps:

1. Select a date.
2. Accept the date.
3. Open the calendar picker once again.
4. Click the arrow next to the Month and Year.
5. Go to any other year.
6. Try to pick the same Month and day from that different year.

I believe with just this you can get the problem to reproduce.
```tsx
export default function Calendar({ onChange, value, maxDate, minDate, title }: CalendarProps): JSX.Element {
    const [isOpen, setIsOpen] = useState(false);
    const [internalDate, setInternalDate] = useState<Date | null>(value);

    const onChangeHandler = (val: Date | null) => {
        // Just a external callback
        onChange(val ?? undefined);

        setInternalDate(val);
    };

    return (
        <LocalizationProvider dateAdapter={AdapterDateFns}>
            <DatePicker
                views={['year', 'month', 'day']}
                openTo={'month'}
                onChange={onChangeHandler}
                value={internalDate}
                minDate={minDate}
                maxDate={maxDate}
                // Added for the sake of being able to manually open the calendar when you click the input.
                open={isOpen}
                onClose={() => setIsOpen(false)}
                onOpen={() => setIsOpen(true)}
                renderInput={({ inputRef, inputProps, InputProps }) => {
                    return (
                        <>
                            <input
                                ref={inputRef}
                                {...inputProps}
                                className={cx('input', 'input-adornment')}
                                onClick={() => setIsOpen(true)}
                                title={title}
                                readOnly
                            />
                            {InputProps?.endAdornment}
                        </>
                    );
                }}
            />
        </LocalizationProvider>
    );
}
```

### Context 🔦

I want to change the date from the same year to the previous year.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### LINKED ISSUE #4407: [DateRangePicker] When disableCloseOnSelect is true, it does not update start/end dates on close

### LINKED ISSUE #4438: [DateTimePicker] Cancel button doesn't work on mobile
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Changes are not canceled when the CANCEL button is pressed.
Selecting a date will fire onChange, and the date will be updated.

It has already been fixed in the DatePicker variant ( mui/material-ui#30731 )

### Expected behavior 🤔

Make the firing timing of onChange only when the OK button is pressed.

### Steps to reproduce 🕹

Steps:
It can be simply reproduced even in the component demo

1. visit https://mui.com/components/date-time-picker/#responsiveness
2. change the date in the top field
3. hit 'cancel'
4. the date will still update

### Context 🔦

_No response_

### Your environment 🌎

_No response_

### LINKED ISSUE #4445: [DateTimePicker] Resets to the previous state after clicking away

### LINKED ISSUE #4469: [DesktopDatePicker] previous value appears without picking a date.

### LINKED ISSUE #4478: [DatePicker] Input value is cleared when closing the datepicker
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Input value is cleared after open and close the datepicker dialog.

### Expected behavior 🤔

Input value should stay the same

### Steps to reproduce 🕹

Steps:

1. Open https://codesandbox.io/s/k860y9?file=/demo.js (official demo)
2. Type valid date in input (for example 03/03/2022)
3. Blur the input
4. Open Datepicker Dialog (click at the calendar icon)
5. Close Datepicker Dialog (just click outside the dialog or press 'Esc' button)
6. See that input value is empty

### Context 🔦

https://codesandbox.io/s/k860y9?file=/demo.js

### Your environment 🌎

environment from the official sandbox

### LINKED ISSUE #4541: [DateRangePicker] Problem when typing on desktop
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hi guys!

I'm encountering problems after migrating to version 5. In the current version, when desktop, typing and pressing tab to confirm the date is cleared, while in the previous version it worked fine. Selecting from calendars works fine.

Any idea how to get around the problem?

Thanks a lot!

### Expected behavior 🤔

_No response_

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### LINKED ISSUE #4544: [DateRangePicker] Cannot reset to currentDate after selecting range from DateRangePicker
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

1. Selecting a start date and end date in the date range picker. The dates are selected correctly.  
2. Then click on the reset button, which resets the start date and end date to today.
3. Then, open the date picker and close it without selecting any dates.
4. Then the dates are reseted to previously selected dates, which should not be the case if no date is selected.

### Expected behavior 🤔

1. Selecting a start date and end date in the date range picker. The dates are selected correctly.  
2. Then click on the reset button, which resets the start date and end date to today.
3. Then, open the date picker and close it without selecting any dates.
4. The dates in the picker should be the todays dates only.

### Steps to reproduce 🕹

Steps:

1. Here is the link to the above issue https://codesandbox.io/s/responsivedaterangepicker-material-demo-forked-mjyqtq?file=/demo.tsx

### Context 🔦

I am testing the Date Range Picker to be used in a project and while doing it I came across this bug so I wanted to report it.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### LINKED ISSUE #4545: [DateRangePicker] `onClose` and `onAccept` both get executed whether you tap Ok or Cancel
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In all three cases both `onClose` and `onAccept` are called:
1. click out of the picker
2. click OK
3. click Cancel

### Expected behavior 🤔

`onAccept` should only be called when you click OK

### Steps to reproduce 🕹

```` javascript
import * as React from 'react';
import TextField from '@mui/material/TextField';
import DateRangePicker from '@mui/lab/DateRangePicker';
import AdapterDateFns from '@mui/lab/AdapterDateFns';
import LocalizationProvider from '@mui/lab/LocalizationProvider';
import Box from '@mui/material/Box';

export default function BasicDateRangePicker() {
  const [value, setValue] = React.useState([null, null]);

  return (
    <LocalizationProvider dateAdapter={AdapterDateFns}>
      <DateRangePicker
        startText="Check-in"
        endText="Check-out"
        value={value}
        onChange={(newValue) => {
          setValue(newValue);
        }}
        onAccept={() => console.log("accepted")}
        onClose={() => console.log("canceled")}
        renderInput={(startProps, endProps) => (
          <React.Fragment>
            <TextField {...startProps} />
            <Box sx={{ mx: 2 }}> to </Box>
            <TextField {...endProps} />
          </React.Fragment>
        )}
      />
    </LocalizationProvider>
  );
}

````

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### LINKED ISSUE #4567: DatePicker restores previous value on clicking outside of it's popper
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If two DatePickers share the same value (for example stored as a state value), assigning a new value from the first DatePicker firstly seems to update the value of the second DatePicker. But actually, opening the popper of the second DatePicker and closing it, by clicking outside of it, makes the shared value to be restored to the previous value that was assigned once from the second DatePicker. Apparently, the problem occurs any time, when the value passed to the DatePicker gets updated somehow outside of that same DatePicker, sinche always in such circumstances opening the popper of that DatePicker and closing it restores value to the previous one.

### Expected behavior 🤔

I'd expect that rising shared state to the parent component would be more transparent, and that DatePickers would not memorize somehow internally previous values. Indeed, if two DatePickers would share the same value, updating it from the first DatePicker should update completely the second DatePicker as well, so that simply opening and closing the popper of the second DatePicker would not change that value.

### Steps to reproduce 🕹

Steps:

1. Implement a component with a Date state value (let it be today by default for example) and two simple DatePickers, that share that value. Launch it.
2. Set some new date from the first DatePicker.
3. Open the second DatePicker and close it by clicking outside.
4. The shared value is restored to the previous one.

### Context 🔦

I've encountered this issue in my project with one of DatePickers which was accepting a date value, stored in a Redux store. And this value can be updated as well from another place in my app. So it gets particularly annoing and unpredictable when opening and closing that DatePicker without changing the value resotres the value back to the previous one and changes lots of things in the app. I thought it was something in my code, by I looked to the DatePicker docs page and found the exact same issue on that page as well with 4 different DatePickers sharing same value.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 8.31 GB / 15.92 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.34.1.
  IDEs:
    VSCode: 1.66.2 - C:\Users\Painkiller\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.0.32112.339 (Visual Studio Community 2022)
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.39)
    Internet Explorer: 11.0.19041.1566
```
</details>

### Order ID 💳 (optional)

_No response_

### LINKED ISSUE #4580: [DatePicker] Clicking outside the popper resets the state set by inline edit
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If you inline edit the date, click the date picker icon and then click outside without selecting a date the state will reset to the previous value that was set by using a date picker.

### Expected behavior 🤔

If you open the date picker and click outside without selecting a date it shouldn't change the state set by inline edit.

### Steps to reproduce 🕹

Steps:

1. Inline edit the date, the state will change.
2. Click on the date picker icon.
3. Click outside the popper and the state changes to the previous value (not the one set by an inline edit).

codesandbox link: https://codesandbox.io/s/epic-breeze-fsxgpe?file=/src/Demo.tsx

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Version 100.0.4896.88 (Official Build) (64-bit)
  npmPackages:
    @emotion/react: ^11.8.2 => 11.8.2
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.76
    @mui/icons-material: ^5.5.1 => 5.5.1
    @mui/lab: ^5.0.0-alpha.77 => 5.0.0-alpha.77
    @mui/material: ^5.5.3 => 5.5.3
    @mui/private-theming:  5.6.1
    @mui/styled-engine:  5.6.1
    @mui/system:  5.6.1
    @mui/types:  7.1.3
    @mui/utils:  5.6.1
    @mui/x-date-pickers:  5.0.0-alpha.0
    @types/react: ^17.0.43 => 17.0.43
    react: ^18.0.0 => 18.0.0
    react-dom: ^18.0.0 => 18.0.0
    typescript: ^4.6.3 => 4.6.3
```
</details>

### LINKED ISSUE #4643: [DatePicker] Picker resets to previous value when opening
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Current behavior 😯

Case 1.
If I delete the content of a DatePicker manually, and then click the calendar icon two times, the earlier date will pop up again.
iShot2022-04-23_19 38 04

Case 2.
If I change the content and do the same thing as mentioned above, strange behavior also exists.
iShot2022-04-23_19 45 53

I don't know whether it's designed like this, or it's an unexpected behavior, or I used it in a wrong way. Hope there can be a support for me, thx.

Code sample is here: [MUI-DatePicker](https://mui.com/zh/x/react-date-pickers/getting-started/)

### Expected behavior 🤔

I think after I click the icon two times, the content of the picker should remain empty if I have deleted it, or it should keep the value if I changed it manually.

### Steps to reproduce 🕹

Steps: Please view the gif above

1.
2.
3.
4.

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### LINKED ISSUE #4677: [DatePicker] Feed in date in input filed, Select popup without selecting a date click outside. Inputted date is wiped out
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

MUI DatePicker,
Issue 1)  Feed in date in input field, Select popup without selecting a date click outside. Inputed date is wiped out.
Issue 2) Select the date from popup picker. Edit the date using input field. Open the picker again,(You can see the curretly inputted date getting displayed). Click outside the picker to make it close. Now the previously picker selected date come up in the datepicker.

### Expected behavior 🤔

We should see the last edited date in the field. 

### Steps to reproduce 🕹

Steps:

1. Select the date from popup picker
2.  Edit the date using keyboard in input box tpo a different date
3. Open the picker again, and click outside the picker to close it.
4. Edited date is gone, Old selected date get dispaled.

### Context 🔦

It creates inconsistencey  in the functionality. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
## Issues

Fixes #4469
Fixes #4478
Fixes #4438
Fixes #4567
Fixes #4545
Fixes #4544
Fixes #4580
Fixes #4407
Fixes #4541
Fixes #4643
Fixes #4395
Fixes #4358
Fixes #4445
Fixes #4677

## Goal

Clarify how the date should be updated when opening / closing the picker.

## Changes

- Behavior
  - [x] Do not call `onAccept` when the new accepted value equals the previous one
  - [x] Do not call `onChange` when the new value equals the previous one
  - [x] Commit value when dismissing the picker 
  - [x] Create new `wrapperProps.onCancel` to reset to the last accepted value
  - [x] Replace the `disableCloseOnSelect` prop with a `closeOnSelect` prop (the default values are also inverted) 

- Tests
  - [x] `MobileDatePicker`
  - [x] `DesktopDatePicker`
  - [x] `MobileDateTimePicker`
  - [x] `DesktopDateTimePicker`
  - [x] `MobileDateRangePicker`
  - [x] `DesktopDateRangePicker`
  - [x] `MobileTimePicker`
  - [x] `DesktopTimePicker`

## What's next ?

- Clean the other tests to always use the new utilities
- Test the lifecyle of static pickers

## Changelog (breaking change)

- Rework the auto-closing behavior of the pickers.
  
  The `disableCloseOnSelect` prop has been replaced by a new `closeOnSelect` prop which has the opposite behavior.
  The default behavior remains the same (close after the last step on desktop but not on mobile).

  ```diff
  // If you don't want to close after the last step
  -<DatePicker disableCloseOnSelect={false} />
  +<DatePicker closeOnSelect />

  // If you want to close after the last step
  -<DatePicker disableCloseOnSelect />
  +<DatePicker closeOnSelect={false} />
  ```

### CODE REVIEW

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 1]
```diff
@@ -21,14 +21,42 @@ export interface PickerStateValueManager<TInputValue, TDateValue> {
...
+   */
+  | 'accept'
+  /**
+   * Set the draft and committed date to the action value
+   */
+  | 'commit'
+  /**
+   * Set the draft date to the action value
+   */
+  | 'draft';
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:55]: If I correctly understand the pipeline, the only situation in which the difference between `'commit'` and `'accept'` is relevant is when `shouldCloseOnSelect===false`.

In this specific case, you need to keep track of the value before opening the input to do the reset, and this value is saved in `accepted` property.

If that's correct, what about renaming `accepted` with something like `initialValue`, `valueBeforeEditing`, `resetTraget`, or anything that does not refer to validation

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 2]
```diff
@@ -69,95 +111,109 @@ export const usePickerState = <TInput, TDateValue>(
...
         }
       }
     },
     [onAccept, onChange, setIsOpen],
   );
 
+  // Set the draft and committed date to equal the new prop value.
+  if (!valueManager.areValuesEqual(utils, dateState.committed, parsedDateValue)) {
+    setDate({ type: 'commit', value: parsedDateValue, internal: true });
+  }
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:140]: Currently it is not the case (my `accepted` is basically the `initialDate` you have on master)
This date is used when clicking "reset", so for me it must only be set on explicit user validation or when opening the picker.

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts (hunk 1 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:55]: Yes
I am very unsure of the use case and I am gathering all the issues related for this problem to make sure I am not breaking stuff
But the idea is what you described

I don't like the "initialValue" name because for it's not initial, when you click the "Accept" it updates this value.
The best is probably "resetTarget"

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 3]
```diff
@@ -69,95 +115,109 @@ export const usePickerState = <TInput, TDateValue>(
...
+        }
+      },
       onSetToday: () => {
-        const now = utils.date() as TDateValue;
-        dispatch({ type: 'update', payload: now });
-        acceptDate(now, !disableCloseOnSelect);
+        if (shouldCloseOnSelect) {
+          setDate({ value: utils.date()!, type: 'accept', closePicker: true });
+        } else {
+          setDate({ value: utils.date()!, type: 'commit' });
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:178]: The previous version did not took the default version of `disableCloseOnSelect` into account (see `pickerProps.onDateChange` where we do use this default version).

I don't know what should be the behavior here
Should the "Today" button behave like "Accept" (ie: close even if disableCloseOnSelect = true) or should it behave like a regular date selection (ie: only close if disableCloseOnSelect = false).

@BGehrels what do you think ?

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 4]
```diff
@@ -41,127 +79,162 @@ interface PickerStateProps<TInput, TDateValue> {
...
+        // Reset all date in state to the empty value and close picker
+        setDate({ value: valueManager.emptyValue, action: 'acceptAndClose' });
+      },
+      onAccept: () => {
+        // Set all date in state to equal the current draft value and close picker
+        setDate({ value: dateState.draft, action: 'acceptAndClose' });
+      },
+      onDismiss: () => {
+        if (shouldCloseOnSelect) {
+          // Set all dates in state to equal the last accepted date
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:169]:
```suggestion
          // Closing input before finishing to enter the date reset input value
```

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 5]
```diff
@@ -41,127 +79,162 @@ interface PickerStateProps<TInput, TDateValue> {
...
+          // e.g. Reset the state to the last accepted value
+          setDate({ value: dateState.resetTarget, action: 'acceptAndClose' });
+        } else {
+          // Set all dates in state to equal the last committed date
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:173]:
```suggestion
          // Set input value to the committed one
          // Equivalent to resetting if no value entered and validating if valid value entere
```

I'm wondering, is it possible for the user to enter a date that will be committed and then modify the input such that the new displayed value is not valid. If it's possible we should check that `draft` is the same date as `committed`

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:173]: I am not following you here
From what I understand, when you edit the input, we only fire the `onChange` when the date is valid (by definition since we call `onChange` with a date)
So `props.value` always contain a valid date.

Do you mean "not valid" as "not a valid date" or as "a date that make no sense" (for instance having year '19' while typing 1997) ?

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts (hunk 4 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:169]: "Closing input" ?

The naming I see is

- Input => the actual TextField
- View => the "menu" opened when we click on the icon

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 6]
```diff
@@ -175,15 +248,19 @@ export const usePickerState = <TInput, TDateValue>(
       onChange: handleInputChange,
       open: isOpen,
       rawValue: value,
-      openPicker: () => setIsOpen(true),
+      openPicker: () => {
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:251]: Need to test when controlling `props.open` and the user open the picker not through the input.
It will not reset the value, so the bug we are trying to solve will still appear.

This reset should probably be done in a `useEffect` when `isOpen` changes

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts (hunk 4 above)
Comment (alexfauquette) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:169]: So "Closing view".
I'm still confused about the distinction between the TextFields and Views management

My point is that this `if` condition is not straight forward, because as a naive reader I would expect a `shouldSelectOnClose` instead of the `shouldCloseOnSelect`. So the comment should give context about when the `onDismiss` is used, and why it depends on `shouldCloseOnSelect`

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts (hunk 5 above)
Comment (alexfauquette) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:173]: Ok, I was inventing problems that can not occur 😅

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts (hunk 4 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:169]: > I'm still confused about the distinction between the TextFields and Views management

Same
This RFC https://github.com/mui/mui-x/issues/4484 could help us clarify the naming.

____

I think we can distinguish two things:

- The documentation of the methods `onDismiss`, `onSetToday` etc... which have zero JSDoc, are defined in `PickersModalDialogProps` / `PrivateWrapperProps` and `wrapperProps`

- The comment inside those methods

My comments were more about internal mixture.
But we should probably add a clean documentation that could even be used on the doc at some point.

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts (hunk 3 above)
Comment (BGehrels) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts]: Phu, depends on the primary use case (we are not using it):

- If it's to select a date, i would close/switch to the TimePicker when it is clicked (What is your preferred Delivery date? Today, 5:30! - 3 clicks)
- If it's to quickly get back to the current calendar page i would leave it open (Preselection is 1987, today is 2022, i don't want to click "next year" 35 times, get me there fast, please).

Do you have user research/tracking insights which of those two is more relevant? My gut feeling would say the first one, so immediately closing the picker would make most sense - especially, since you can always reopen it in case you wanted the later case.

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts]: > Do you have user research/tracking insights which of those two is more relevant?

Not yet, I think I will try to propose a behavior a clear as possible in most scenarios and to list clearly those where there is a debate (the one you pointed out about the rest when dismissing a multi-views picker for instance).

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 7]
```diff
@@ -69,99 +151,98 @@ export const usePickerState = <TInput, TDateValue>(
...
-        setIsOpen(false);
-        setInitialDate(acceptedDate);
-        if (onAccept) {
-          onAccept(acceptedDate);
-        }
-      }
-    },
-    [onAccept, onChange, setIsOpen],
-  );
+  const shouldCloseOnSelect = !(disableCloseOnSelect ?? wrapperVariant === 'mobile');
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:166]: Now that you put a default value with `disableCloseOnSelect = wrapperVariant === 'mobile'` I assume you can remove the `??`

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 8]
```diff
@@ -69,99 +151,98 @@ export const usePickerState = <TInput, TDateValue>(
...
+      onClear: () => {
+        // Reset all date in state to the empty value and close picker
+        setDate({ value: valueManager.emptyValue, action: 'acceptAndClose' });
+      },
+      onAccept: () => {
+        // Set all date in state to equal the current draft value and close picker
+        setDate({ value: dateState.draft, action: 'acceptAndClose' });
+      },
+      onDismiss: () => {
+        if (shouldCloseOnSelect) {
```
Comment (m4theushw) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:180]: Why do you need to check `shouldCloseOnSelect` here? As I understand, if `onDismiss` is called then we need to set the date based on whether it is full or partial.

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 9]
```diff
@@ -41,26 +81,68 @@ interface PickerStateProps<TInput, TDateValue> {
...
   );
 
-  const [lastValidDateValue, setLastValidDateValue] = React.useState<TDateValue | null>(
-    parsedDateValue,
+  const [lastValidDateValue, setLastValidDateValue] = React.useState<TDate | null>(parsedDateValue);
+
+  const [dateState, setDateState] = React.useState<DateState<TDate>>(() => ({
+    committed: parsedDateValue,
+    draft: parsedDateValue,
+    resetTarget: parsedDateValue,
```
Comment (m4theushw) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:108]: Why "target"? Maybe `fallback`?

Comment (m4theushw) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:108]: Why "target"? Maybe `fallback`?

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 10]
```diff
@@ -69,99 +151,98 @@ export const usePickerState = <TInput, TDateValue>(
...
-
-  // Mobile keyboard view is a special case.
-  // When it's open picker should work like closed, because we are just showing text field
-  const [isMobileKeyboardViewOpen, setMobileKeyboardViewOpen] = React.useState(false);
+  React.useEffect(() => {
+    if (isOpen) {
+      // Update all dates in state to equal the current prop value
+      setDate({ action: 'setAll', value: parsedDateValue, internal: true });
+    }
+  }, [isOpen]); // eslint-disable-line react-hooks/exhaustive-deps
```
Comment (m4theushw) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:159]: It's rare when we need to use `// eslint-disable-line react-hooks/exhaustive-deps`. Why you added it?

File: packages/x-date-pickers/src/internals/models/props/basePickerProps.tsx [hunk 11]
```diff
@@ -8,7 +8,7 @@ export interface BasePickerProps<TInputValue, TDateValue> {
   className?: string;
   /**
    * If `true` the popup or dialog will immediately close after submitting full date.
-   * @default `true` for Desktop, `false` for Mobile (based on the chosen wrapper and `desktopModeMediaQuery` prop).
+   * @default `false` for Desktop, `true` for Mobile (based on the chosen wrapper and `desktopModeMediaQuery` prop).
```
[the remark this answers is not in the document]
Comment (alexfauquette) [reply packages/x-date-pickers/src/internals/models/props/basePickerProps.tsx:11]: The value is not used directly so the developers do not care. The behavior of the component is controlled by `shouldCloseOnSelect` defined previously as follow
```js
const shouldCloseOnSelect = !(disableCloseOnSelect ?? wrapperVariant === 'mobile');
```

In this PR the default value is now defined as follow
```js
const { disableCloseOnSelect = wrapperVariant === 'mobile', onAccept, onChange, value } = props;
```

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts (hunk 8 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:180]: The behavior of `onDismiss` is under discussion
On `master` now we reset the date
But if `shouldCloseOnSelect = false`, then we probably want to `acceptAndClose` because clicking outside of the picker is the main way to validate the value.

Things become more complicated for multi-step input,
If a user sets the date and time, then re-open the picker, select a date and close : should it keep the new date or not ?
Currently it does not, but one might argue that it should.

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts (hunk 10 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:159]: We don't want `parsedDateValue` as a deps, otherwise we would reset the state way to often

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts (hunk 7 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:166]: Users should still be able to override it right ?

**Comment by BGehrels** [comment]
I have the feeling that you are struggling a bit with the question how to meaningfully weave cancellability/dismissability into the desktop workflow. I quick thought from outside: Is there actually a use case for cancel/dismiss at all on desktop?

On mobile, a picker is usually full screen and modal, so the UX metaphor is something like a good old MS Windows wizard. These ones always have a cancel button. because it's the only way to get out. Also, there is often is no Keyboard-Only way to enter or correct a date in mobile apps - the picker is the only interactive element to modify a date.

On desktop a picker is usually combined with some input field (as done in your demo examples). In this case a user will use this picker as an alternative to typing. So the UX metaphor of the picker is that of a domain specific "easy" keyboard. On a keyboard i do not have an cancel button or dismiss feature to get rid of a half typed value. When i blur the input, there will still be the half typed value in there. And the well trained and understood way to dismiss a wrong value is to focus the field and hit backspace/DEL until its gone.

Conclusion: On Desktop the relevant criterion is not "close on select or not" but "is there an underlying text field". If the later is the case every item the user selected in the date & time picker (year/month/day/hour/minute/...) should be persistent as long as you don't select another one. As if you had year/month/date/hour/minute-Buttons on your keyboard and pressed one of them. No Dismissal of values. User should use backspace in the underlying input if she wants to get rid of typed values.

(Sorry in case this is the wrong place for the discussion, i'm really confused by the plethora of tickets connected to this ticket.)

**Comment by flaviendelangle** [comment]
@BGehrels Thank you for your detailed explanation.

Yes, the main point I am struggling with is the cancel behavior on desktop.
What you describe make sense.

We would then have the following (correct me if I'm wrong):

Dismissing can occur due to two type of events:

- Clicking outside of the panel
- Pressing <key>Escape</key>

1. Always accept the value on Desktop pickers when clicking outside or the panel

2. Always accept the value on Desktop pickers when pressing <key>Escape</key> (I would like the opinion of the team on this one)

3. Always accept the value on Mobile pickers when pressing outside of the modal

4. Add a "Cancel" button on Static pickers (`StaticDatePicker` for instance) just like on mobile (should there be a "OK" button ? Not sure since we already call `onChange` on intermediate changes, this button would just call `onAccept` but would have no impact on our UI).

@joserodolfofreitas @alexfauquette

**Comment by alexfauquette** [comment]
For me, it sounds good

On Desktop updates from the view are always accepted, and if you need to reset, the developers can always add a little cross to clear the view. It does not surprise me that <kbd>Esc</kbd> accept the value

About adding buttons, why not letting a slot for actions such that developers can put the button they wants

**Comment by m4theushw** [comment]
> Always accept the value on Mobile pickers when pressing outside of the modal

On Android, clicking outside of a `input[type="date"]` is the same as clicking the Cancel button. The value is only updated when clicking the Define button (OK button here).

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 12]
```diff
@@ -41,127 +79,158 @@ interface PickerStateProps<TInput, TDateValue> {
...
+      if (
+        !params.internal &&
+        !valueManager.areValuesEqual(utils, dateState.committed, params.value)
+      ) {
+        onChange(params.value);
+      }
 
-      if (needClosePicker) {
+      if (params.action === 'acceptAndClose') {
         setIsOpen(false);
```
Comment (m4theushw) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:132]: Are you aware that it doesn't close after selecting the dates in https://deploy-preview-4408--material-ui-x.netlify.app/x/react-date-pickers/date-range-picker/?

`ClickAwayListener` tries to restore the focus after closing, but the `onFocus` on the input makes it to open again.

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:132]: Yes

It is https://github.com/mui/mui-x/issues/4439
I will try to fix it after :+1:

**Comment by flaviendelangle** [comment]
> > Always accept the value on Mobile pickers when pressing outside of the modal
> 
> On Android, clicking outside of a `input[type="date"]` is the same as clicking the Cancel button. The value is only updated when clicking the Define button (OK button here).


@alexfauquette @joserodolfofreitas I would like your opinion on this one

**Comment by joserodolfofreitas** [comment]
> Always accept the value on Desktop pickers when clicking outside or the panel

+1

> Always accept the value on Desktop pickers when pressing Escape (I would like the opinion of the team on this one)

I'd expect that pressing escape should be considered as an undo operation for the date range picker (undoing the first input) but it should accept the initial date in the date time picker (when you escape from the clock view).
Are there other cases where you can escape after an initial input?

> Always accept the value on Mobile pickers when pressing outside of the modal

I'd expect to accept the value. (Angular Material behaves like that)

> Add a "Cancel" button on Static pickers (StaticDatePicker for instance) just like on mobile (should there be a "OK" button ? Not sure since we already call onChange on intermediate changes, this button would just call onAccept but would have no impact on our UI).

I think a "Clear" button makes sense in this case.

**Comment by flaviendelangle** [comment]
> I'd expect that pressing escape should be considered as an undo operation for the date range picker (undoing the first input) but it should accept the initial date in the date time picker (when you escape from the clock view).

So you would undo the operation of the current view but not the operations before that ?
It brings a lot of additional complexity to the lifecyle to "semi-reset".

> Are there other cases where you can escape after an initial input?

Almost all pickers are multi-view yes.
`DatePicker` => year and date
`TimePicker` => hour and minutes (and seconds)
etc...
____

> I think a "Clear" button makes sense in this case.

Clear and Cancel are currently two distinct buttons
Clear : set the "empty" value (`null` for all pickers except the range ones which have `[null, null]`)
Cancel: set the last validated value (the initial value or the value the last time it was closed basically)

For the static pickers, the `Cancel` still differs from the `Clear` if there is an initial value.

**Comment by alexfauquette** [comment]
I had an overview about testing, sounds to be clearly better. Will have a closer look

About validating on close, for me the current behavior is ok. Maybe letting developers control this behavior, but that's clearly anther PR

**Comment by flaviendelangle** [comment]
> Maybe letting developers control this behavior, but that's clearly anther PR

I also think in the future we should allow deeper customization on the lifecycle
But I think it is something that we can easily do wrong. So I would wait a few months to have more knowledge before starting this project.

**Review by alexfauquette — APPROVED** [review]
Tests are really good. I've seen nothing to change

I agree we could try to have something more semantic like you did for `openPicker`. It would be nice for writing action, but also checking state updates. 

For example to check callback we could have an helper such has 
```js
hasCall({
	onChange: ['2010-01-01T00:00:00.000']
})
```
to check that only `onChange` has been called with the argument `'2010-01-01T00:00:00.000'`.

----

About changing `disableCloseOnSelect` to `closeOnSelect`, yes it seems clearer to avoid the `disable` for something which is not always enabled by default.

It could be done in another PR if you prefer

**Comment by flaviendelangle** [comment]
> It could be done in another PR if you prefer

I had moved so much of the logic of `disableCloseOnSelect` in this PR that it would probably be easier to do it here

File: test/utils/pickers-utils.tsx [hunk 13]
```diff
@@ -74,6 +80,123 @@ export function createPickerRenderer({
...
+    case 'mobile': {
+      switch (params.type) {
+        case 'date':
+        case 'date-time':
+        case 'time': {
+          return userEvent.mousePress(screen.getByRole('textbox'));
+        }
+
+        case 'date-range': {
+          return userEvent.mousePress(
```
Comment (m4theushw) [inline test/utils/pickers-utils.tsx:128]: Why the difference between mobile and desktop? Could `userEvent.focus` be used here?

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 14]
```diff
@@ -21,18 +23,54 @@ export interface PickerStateValueManager<TInputValue, TDateValue> {
...
+  | 'setDraft';
+
+interface DateStateAction<DraftValue> {
+  action: DateStateActionType;
+  value: DraftValue;
+  /**
+   * If `true`, do not fire the `onChange` callback
+   * @default false
+   */
+  internal?: boolean;
```
Comment (m4theushw) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:69]: `internal` has no meaning.

```suggestion
  skipOnChangeCall?: boolean;
```

File: test/utils/pickers-utils.tsx [hunk 15]
```diff
@@ -74,6 +80,123 @@ export function createPickerRenderer({
...
+  | {
+      type: 'date-range';
+      variant: 'mobile' | 'desktop';
+      initialFocus: 'start' | 'end';
+    };
+
+export const openPicker = (params: OpenPickerParams) => {
+  switch (params.variant) {
+    case 'desktop': {
+      switch (params.type) {
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply test/utils/pickers-utils.tsx:97]: > Could you unify the logics to open the picker?

What do you mean by that ?

File: test/utils/pickers-utils.tsx [hunk 16]
```diff
@@ -74,6 +80,123 @@ export function createPickerRenderer({
...
+        case 'date':
+        case 'date-time': {
+          return userEvent.mousePress(screen.getByLabelText(/choose date/i));
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply test/utils/pickers-utils.tsx:100]: On desktop we are not clicking on the textbox but on the side icon

File: test/utils/pickers-utils.tsx (hunk 13 above)
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply test/utils/pickers-utils.tsx:128]: `userEvent.focus` does not work, I don't know why
I don't want to change this behavior now since we have issues showing that the whole "open on focus" / "close on blur" has problems that will need deeper changes soon.

File: test/utils/pickers-utils.tsx (hunk 15 above)
[the remark this answers is not in the document]
Comment (m4theushw) [reply test/utils/pickers-utils.tsx:97]: The logic to open the date range is almost the same between desktop and mobile, only the event changes. In the other hand, the logic to open the date and time picker is very similar only changing the element passed to `userEvent.mousePress`. I think this helper method can be simplified.

File: test/utils/pickers-utils.tsx (hunk 13 above)
[the remark this answers is not in the document]
Comment (m4theushw) [reply test/utils/pickers-utils.tsx:128]: I might be explained by https://github.com/mui/mui-x/blob/ebb0e3b1a4d940b02ca20abd61ade86fce9b6e94/packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerInput.tsx#L154-L155

`openOnFocus` is only true on desktop.

File: test/utils/pickers-utils.tsx (hunk 16 above)
[the remark this answers is not in the document]
Comment (m4theushw) [reply test/utils/pickers-utils.tsx:100]: Ignore my comment. I didn't realize that the label was not overriding the text input's label.

File: test/utils/pickers-utils.tsx (hunk 13 above)
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply test/utils/pickers-utils.tsx:128]: Maybe
This PR is big enough as it is but we will investigate

**Comment by SaeedZhiany** [comment]
@flaviendelangle 

Thanks for your work, when we can expect to have this change on an npm release?

**Comment by flaviendelangle** [comment]
Most likely next week :+1:

**Comment by sameswar** [comment]
Which version of date picker has this change? What should be the version we need to use to render this!

**Comment by alexfauquette** [comment]
@sameswar merged pull requests are available in the next release. So it should be `@5.0.0-alpha.3` the day of the next release is not yet decided, probably in less than a week

File: docs/pages/x/api/date-pickers/date-picker.json [hunk 17]
```diff
@@ -11,6 +11,10 @@
     "className": { "type": { "name": "string" } },
     "clearable": { "type": { "name": "bool" } },
     "clearText": { "type": { "name": "node" }, "default": "'Clear'" },
+    "closeOnSelect": {
+      "type": { "name": "bool" },
+      "default": "`true` for Desktop, `false` for Mobile (based on the chosen wrapper and `desktopModeMediaQuery` prop)."
+    },
```
Comment (oliviertassinari) [inline docs/pages/x/api/date-pickers/date-picker.json:17]: Do we have more context on this change? If we follow https://mui.com/material-ui/guides/api/#prop-naming. I would expect the prop to be called `disableCloseOnSelect` since the desktop is more important than mobile (in terms of usage frequency).

**Review by oliviertassinari — COMMENTED** [review]
This is epic (with some duplicates so cheating 😛).

Screenshot 2022-05-15 at 02 17 48

We would have to search deep into the project history to find a similar instance, maybe https://github.com/mui/material-ui/pull/17037, but likely would need to look at 2016 or 2017 ish. I would almost want to praise it but the number of diffs makes me wonder if this could have been split into multiple PRs 😁

File: docs/pages/x/api/date-pickers/date-picker.json (hunk 17 above)
Comment (flaviendelangle) [reply docs/pages/x/api/date-pickers/date-picker.json:17]: For me `disableCloseOnSelect` is harder to understand than `closeOnSelect` and the weight for of the desktop vs mobile does not counter this complexity.

While working on the code related to this prop, I had at least 3 times to switch the behavior because I wrote it in the wrong order.
And the doc was inversed (it was written for `closeOnSelect` not `disableCloseOnSelect`)

I don't think `disableXXX` with a dynamic default value that can be `true` or `false` is a good practice. It's not readable when you don't know the codebase well enough.

**Comment by kfirevron** [comment]
using Datepicker still saves the value... 
steps to reproduce : 
1.click on day sets the value.
2.closing popup.
3.click clear icon and set value to null.
4.click on open popup.
5.click outside the popup old value showing in the input.


please help if there is any solution ? i am on mui 5.8.0

**Comment by flaviendelangle** [comment]
@kfirevron which version of `@mui/x-date-picker` are you using ?

**Comment by kfirevron** [comment]
@flaviendelangle we used the mui datepicker directly and not from x-date-picker.. maybe thats the problem ?

**Comment by flaviendelangle** [comment]
You mean the pickers exported from `@mui/lab` ?

If so yes, they are deprecated in favor of `@mui/x-date-picker` and will be removed soon
You have more details about this migration [here](https://mui.com/blog/lab-date-pickers-to-mui-x/)

File: docs/pages/x/api/date-pickers/date-picker.json (hunk 17 above)
Comment (oliviertassinari) [reply docs/pages/x/api/date-pickers/date-picker.json:17]: > I don't think disableXXX with a **dynamic** default value that can be true or false is a good practice. 

Alright, deal, sounds like we have a new rule for prop names with dynamic default. I would be in favor of adding this to https://mui.com/material-ui/guides/api/#prop-naming

**Comment by igorSurz** [comment]
Hello dear developers, I am struggling for 3 days, please help
 "@mui/x-date-pickers-pro": "^5.0.4", 
The date time picker reverts its initial state if we click away, I have read all these topics and the developers marked this bug as solved😨

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by igorSurz** [comment]
> Hi,
> 
> Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

OMG!!! thanks to linter, I was importing pickers from `@lab` and not from `@mui/x-date-pickers/`
@flaviendelangle Thank you, my friend, I wish you to live to 120 years🙏🏻🙏🏻🙏🏻

**Comment by djwondersco** [comment]
Hello! Having issue similar to [#4438](https://github.com/mui/mui-x/issues/4438) but instead of clicking 'Cancel', clicking outside the MobileDateTimePicker triggers the onAccept event. Here is the scenario:

Scenario 4 (MobileDateTimePicker)
Open the picker (no log)
Click on a date (onChange)
Click on a hour (onChange)
Click on a minute (onChange)
Click on 'Cancel' (onChange, onClose)
