### PR TITLE
[TreeView] Use the order in which the items are displayed for type-ahead

### LINKED ISSUE #12826: [TreeView] Type-ahead do not respect the order of the items
### Steps to reproduce

Link to live example: (required)

Steps:
1. Go to https://stackblitz.com/edit/react-y8wvxr?file=Demo.tsx
2. Focus the 1st item (A3)
3. Type "A"

### Current behavior

"A1" is focus

### Expected behavior

"A2" should be focused

### Context

The code uses `Object.keys` which is not ordered and in any case the order in which is item are registered in the first char map is not reliable.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: type-ahead

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #12826 

Not sure if this is a bug fix or just a behavior change.
The current type-ahead was alphabetical, if you have the items `["A3", "A2", "A1"]`, you focus `"A3"` and press `"a"`, the focus goes to `"A1"` because it's the 1st matching item alphabetically. 
This PR switches for a search based on the displayed order (you focus `"A2"` because it is the 1st matching item below the currently focused one.

IMHO this is a lot more consistent, it's the approach taken by [this TreeView](https://clarity.design/documentation/tree-view) for instance.

Nice side-effect, we no longer generate the list of the 1st letter of **every item** on each keystroke 
Now that `getNextNavigableItem` is cheap it's a lot more efficient that way

### Follow up

Add test in #12811

### CODE REVIEW

File: packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts [hunk 1]
```diff
@@ -55,47 +46,31 @@ export const useTreeViewKeyboardNavigation: TreeViewPlugin<
...
-    if (start >= firstCharIds.length) {
-      start = 0;
-    }
+  const getFirstMatchingItem = (itemId: string, query: string) => {
+    const cleanQuery = query.toLowerCase();
 
-    // Check remaining slots in the menu
-    index = findNextFirstChar(firstChars, start, lowercaseChar);
+    const getNextItem = (itemIdToCheck: string) => {
+      const nextItemId = getNextNavigableItem(instance, itemIdToCheck);
```
Comment (michelengelen) [inline packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:53]: could have sworn that the correct term is `navigatable` ... just looked it up! `navigable` sounds weird! 🤷🏼

File: packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts [hunk 2]
```diff
@@ -55,47 +46,31 @@ export const useTreeViewKeyboardNavigation: TreeViewPlugin<
...
+      // We reached the end of the tree, check from the beginning
+      if (nextItemId == null) {
```
Comment (michelengelen) [inline packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:55]: nit:

```suggestion
      if (nextItemId === null) {
```

**Review by michelengelen — APPROVED** [review]
nit only ... LGTM
