### PR TITLE
[DateRangePicker] Fix touch based range dragging

### LINKED ISSUE #10332: [DateRangePicker]: Not able to select same start date and end date in mobile
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://wx43td.csb.app/ 
Codesandbox link: https://codesandbox.io/s/date-range-picker-demo-wx43td?file=/Demo.tsx:494-515

Steps:
1. Simulate `mobile viewport` in chrome dev tools. 
2. Select a date range, for example, `10 Sep, 2023` to `12 Sep, 2023`
3. Now try to click `10 Sep, 2023` two times.

### Current behavior 😯

Not able to select same date as start date and end date in mobile but it works fine in desktop.

Date Range stays the same, that is, `10 Sep, 2023` to `12 Sep, 2023` (according to the example mentioned in the steps to reproduce).

### Expected behavior 🤔

Both Start date and end date should be `10 Sep, 2023` (as per the example mentioned in the steps to reproduce).

### Context 🔦

User is unable to select a single day in the mobile version of `StaticDateRangePicker` which is an essential use case for our product.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 12.1
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Edge: Not Found
    Safari: 15.2
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base: ^5.0.0-alpha.87 => 5.0.0-beta.13 
    @mui/core-downloads-tracker:  5.12.2 
    @mui/icons-material: ^5.11.16 => 5.11.16 
    @mui/lab: ^5.0.0-alpha.128 => 5.0.0-alpha.128 
    @mui/material: ^5.12.2 => 5.12.2 
    @mui/styled-engine:  5.12.0 
    @mui/styles:  5.10.3 
    @mui/system: ^5.12.1 => 5.12.1 
    @mui/types:  7.2.4 
    @mui/utils:  5.10.3 
    @mui/x-data-grid:  5.17.26 
    @mui/x-data-grid-pro: ^5.17.26 => 5.17.26 
    @mui/x-date-pickers: ^6.13.0 => 6.13.0 
    @mui/x-date-pickers-pro: ^6.13.0 => 6.13.0 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react: ^17.0.52 => 17.0.52 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.9.5 => 4.9.5 
```
</details>

### Order ID or Support key 💳 (optional)

74055

### PR DESCRIPTION
**Pull request by michelengelen**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

~~⚠️ This PR is a replacement for #10403 since the commit history got corrupted and included changes not related to this change.~~ (did not notice that those changes came from @LukasTy .. Sry 🙇🏼 )

### Description
Touch based range dragging was preventing the selection of a date, when a range was set already. With this change it is possible to select a single date from the range, even if it is the start-date.

Fixes #10332 

### Video
https://github.com/mui/mui-x/assets/32863416/05fca116-18eb-40c4-93bf-27158544bc48

### CODE REVIEW

File: packages/x-date-pickers-pro/src/DateRangeCalendar/useDragRange.ts [hunk 1]
```diff
@@ -173,10 +167,19 @@ const useDragRangeEvents = <TDate>({
 
   const handleTouchMove = useEventCallback((event: React.TouchEvent<HTMLButtonElement>) => {
     const target = resolveElementFromTouch(event);
-    if (!isDragging || !target) {
+    if (!target) {
       return;
     }
 
+    event.stopPropagation();
```
Comment (LukasTy) [inline packages/x-date-pickers-pro/src/DateRangeCalendar/useDragRange.ts:174]: Could you double-check if this is actually needed? 🤔 
Stopping event propagation is evil and dangerous. 🙈 

Based on a quick check, it did not seem to impact the behavior. 🤷

**Review by LukasTy — COMMENTED** [review]
Was there a specific reason for not porting the relevant e2e test? 🤔 
https://github.com/mui/mui-x/pull/10403/commits/91e348fd0788e36b93f481e5e8ca903e03533d36

And I mentioned in the previous PR, given the circumstances, I'd like to leave the `approval` honour to @flaviendelangle or @noraleonte. 🤞

**Comment by michelengelen** [comment]
> Was there a specific reason for not porting the relevant e2e test? 🤔 [91e348f](https://github.com/mui/mui-x/commit/91e348fd0788e36b93f481e5e8ca903e03533d36)

Oh, those came from you? I was under the impression that those came from a broken sync/merge with the `upstream` 🙈 ... I just now noticed that they have been pushed to the branch directly. I was already questioning my git skills! 😜 

I will cherry pick those commits and incorporate them here if that's ok.

> And I mentioned in the previous PR, given the circumstances, I'd like to leave the `approval` honour to @flaviendelangle or @noraleonte. 🤞

Yes, that's why I did add @flaviendelangle as reviewer as well.

**Comment by LukasTy** [comment]
> I will cherry pick those commits and incorporate them here if that's ok.

Yup. Sounds good. 👌 
Had to tinker a bit to come up with a working e2e solution covering this behavior, would be a shame to not incorporate it. 🙈

**Comment by michelengelen** [comment]
Thanks @LukasTy for providing the tests! 💪🏼

File: packages/x-date-pickers-pro/src/DateRangeCalendar/useDragRange.ts [hunk 2]
```diff
@@ -173,14 +167,29 @@ const useDragRangeEvents = <TDate>({
...
     }
 
     const newDate = resolveDateFromTarget(target, utils, timezone);
     if (newDate) {
       setRangeDragDay(newDate);
     }
+
+    // this prevents initiating drag when user starts touchmove outside and then moves over a draggable element
+    const targetsAreIdentical = target === event.changedTouches[0].target;
+    if (!(targetsAreIdentical && isElementDraggable(newDate))) {
```
Comment (LukasTy) [inline packages/x-date-pickers-pro/src/DateRangeCalendar/useDragRange.ts:181]: Nice fix. 👌 💯

**Review by LukasTy — COMMENTED** [review]
LGTM.
Nice additional fix! 🚀 
However, as discussed, leaving the approval right to other reviewers. 🙈

File: packages/x-date-pickers-pro/src/DateRangeCalendar/useDragRange.ts (hunk 2 above)
Comment (flaviendelangle) [inline packages/x-date-pickers-pro/src/DateRangeCalendar/useDragRange.ts:181]: I personally find the following easier to read:

```suggestion
    if (!targetsAreIdentical || !isElementDraggable(newDate)) {
```

Maybe it's just because I never write `!(A & B)` so my brain is not as fast as reading it

**Review by flaviendelangle — APPROVED** [review]
Looks great :ok_hand:

File: packages/x-date-pickers-pro/src/DateRangeCalendar/useDragRange.ts (hunk 2 above)
Comment (michelengelen) [reply packages/x-date-pickers-pro/src/DateRangeCalendar/useDragRange.ts:181]: its ok either way .. i do struggle with your approach as i am more used to `!(A && B)` (mentally). 🙇🏼

Comment (flaviendelangle) [reply packages/x-date-pickers-pro/src/DateRangeCalendar/useDragRange.ts]: :laughing: Yeah it's quite subjective
