### PR TITLE
[data grid] Refactor column merge logic to prioritize defined properties only

### LINKED ISSUE #15317: [data grid] Following 7.19.0 release setting a column definition prop to undefined doesn't reset the prop when `type` is set
### Steps to reproduce

Link to live example: (required)

Steps:
1. Set one of the column definition's render props (e.g. `renderCell`) to a dynamic value (based on another state)
2. Set the type of the column definition
3. Trigger a change to the value of the render prop in Step 1

https://stackblitz.com/edit/github-3rk5go-nd8osk?file=src%2Fdemo.tsx 

### Current behavior

The Grid state doesn't reset to its default when the "render" prop is set back to undefined when the "type" of the column is specified but it does when the "type" is not set.

### Expected behavior

If one of the props in the column definition object is updated to `undefined` after previously being set, then the MUI default for that prop should be used even when the `type` of the column definition is set. 

### Context

It stopped working following the 7.19.0 release. After some investigation I found it broke after #14456 was merged.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: undefined, column definition
**Order ID**: 91184

### PR DESCRIPTION
**Pull request by michelengelen**
This PR polishes and type-aligns the column merge changes introduced to correctly fall back to a column type’s default renderers when an override is toggled back to `undefined`.

Fixes #15317

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts [hunk 1]
```diff
@@ -390,11 +390,19 @@ export const createColumnsState = ({
...
+    const mergedProps = {
       ...getDefaultColTypeDef(newColumn.type),
-      ...newColumn,
+      ...newColumnDefinedProps,
+      field,
       hasBeenResized,
-    });
+    };
+
+    columnsState.lookup[field] = resolveProps(existingState, mergedProps);
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts]: Can be done in a single loop with less allocations:


```suggestion
    const mergedProps = {
      ...getDefaultColTypeDef(newColumn.type),
      hasBeenResized,
      field,
    };
    let key: keyof GridColDef;
    for (key in newColumn) {
      if (newColumn[key] !== undefined && key !== 'field') {
        mergedProps[key] = newColumn[key] as any;
      }
    }

    columnsState.lookup[field] = resolveProps(existingState, mergedProps);
```

Comment (michelengelen) [reply packages/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts]: had this before and was running into typescript issues with this, so i changed it to the nested loop
