### PR TITLE
[DataGrid] Fix no row with id error

### LINKED ISSUE #19120: [data grid] No row with id ... found (since v8.9.2)
### Steps to reproduce

Steps:
1. Open this link to [live example](https://stackblitz.com/edit/hp1umeup?file=src%2FDemo.tsx)
2. Click the button twice and get an error - `Uncaught MissingRowIdError: No row with id #66e5925c-c055-5ed1-bf5b-8369a2c64e1a found`.

### Current behavior

_No response_

### Expected behavior

should not crash

### Context

This happens only after adding `getRowClassName`.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)
114057

**Search keywords**: no row with id

### PR DESCRIPTION
**Pull request by romgrk**
Closes #19120

### CODE REVIEW

File: packages/x-data-grid/src/components/GridRow.tsx [hunk 1]
```diff
@@ -285,6 +285,11 @@ const GridRow = forwardRef<HTMLDivElement, GridRowProps>(function GridRow(props,
     return rowStyle;
   }, [isNotVisible, rowHeight, styleProp, heightEntry, rootProps.rowSpacingType]);
 
+  // HACK: Sometimes, the rowNode has already been removed from the state but the row is still rendered.
+  if (!rowNode) {
+    return null;
+  }
```
Comment (romgrk) [inline packages/x-data-grid/src/components/GridRow.tsx:291]: This is the state management issues again, the derived state is computed asynchronously so the `rows` model is already updated while the rendered rows (`gridVisibleRowsSelector`) are lagging behind.

**Review by MBilalShafi — APPROVED** [review]
