### PR TITLE
[pickers] Sync internal state with controlled value

### LINKED ISSUE #8663: [pickers] Controlled DatePicker resets to first value set on popover close.
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/romantic-spence-3l6fvs?file=/demo.tsx

Steps:
1. Load the example. Notice the date picker has a date populated. It is a controlled input.
2. Click the calendar icon to open the date picker popover, but **do not select a date**
3. Click away from the popover to close it.
4. Notice that the date is cleared.

### Current behavior 😯

This demo creates a controlled input with `null` as it's initial value. When the component mounts, setState is called to set a date value. It seems like the DatePicker memoizes the first value it received (null). If the picker is opened, then closed without selecting a value, the picker is reset to null, instead of the `value` prop that is being passed in.

### Expected behavior 🤔

If I have a fully controlled input, I would expect it to always display the value being passed in as the `value` prop.

### Context 🔦

I'm using the DatePicker as a controlled input in a form. When we initially display the form, we don't have all the data to populate it, so we initialize the form inputs with empty values. In the case of the DatePicker, that is `null`. Once the data is fetched, the DatePicker's value prop will be updated to show the currently selected date. If the user opens the popover, then closes it again without selecting a value, the date value gets cleared.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 112.0.5615.121
    Edge: Not Found
    Firefox: 110.0.1
    Safari: 16.3
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.5
    @emotion/styled: ^11.10.4 => 11.10.5
    @mui/base: ^5.0.0-alpha.103 => 5.0.0-alpha.104
    @mui/core-downloads-tracker:  5.10.12
    @mui/icons-material: ^5.10.9 => 5.10.9
    @mui/material: ^5.10.11 => 5.10.12
    @mui/private-theming:  5.10.9
    @mui/styled-engine:  5.10.8
    @mui/system:  5.10.12
    @mui/types:  7.2.0
    @mui/utils:  5.10.9
    @mui/x-date-pickers:  6.2.0
    @mui/x-date-pickers-pro: ^6.2.0 => 6.2.0
    @mui/x-license-pro: ^5.17.0 => 5.17.0
    @types/react: ^18.0.24 => 18.0.24
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.8.4 => 4.8.4
```
</details>

### Order ID or Support key 💳 (optional)

16787

### LINKED ISSUE #8684: [DateRangePicker] once externally cleared, the picker shows previously set value if the user cancels out of the popover
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/confident-lovelace-8f10vm?file=/demo.tsx

Steps:
1. Select start and end date on range picker
2. Click the Clear button
3. Click on either date range input fields (start or end) to invoke the popover
4. Do not click on any dates and instead click outside the popover to dismiss it

### Current behavior 😯

The previously selected dates appear in the input fields but the value from the component is correct (`[null, null]`)

### Expected behavior 🤔

The values in the start and end range inputs should match the state value of the component

### Context 🔦

I am trying to create a component where the user can either pick a range type based on enumerations (`LastWeek | Today | ThisWeek | AllTime`) or through the DateRangePicker. When a user clicks on an enumeration value, the date range picker should clear and stay clear even when the user opens, doesn't select a range, and dismisses the popover by clicking outside of it.

This issue was introduced in 6.2.0 and does not exist in 6.1.0. I believe this to be the https://github.com/mui/mui-x/blob/e28dd9825d70b789735ca79908c24f03de5e2599/packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts#L220 offending line as the validator ends up setting the value of the component based on the draft value passed into it.

### Your environment 🌎

Running Chrome Version 111.0.5563.149 (Official Build) (64-bit)
<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: latest => 11.10.5
    @emotion/styled: latest => 11.10.5
    @mui/base:  5.0.0-alpha.117
    @mui/core-downloads-tracker:  5.11.8
    @mui/icons-material: latest => 5.11.0
    @mui/material: latest => 5.11.8
    @mui/private-theming:  5.11.7
    @mui/styled-engine:  5.11.8
    @mui/system:  5.11.8
    @mui/types:  7.2.3
    @mui/utils:  5.12.0
    @mui/x-data-grid:  6.2.0
    @mui/x-data-grid-pro: ^6.2.0 => 6.2.0
    @mui/x-date-pickers:  6.1.0
    @mui/x-date-pickers-pro: 6.1.0 => 6.1.0
    @mui/x-license-pro:  6.0.4
    @types/react:  18.0.27
    react: latest => 18.2.0
    react-dom: latest => 18.2.0
    typescript:  4.9.5
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #8663
Fix #8684

If we update the controlled value with a side effect, the new value should be committed and published. Otherwise dismiss and cancel action will be incoherent with what the dev implemented

### CODE REVIEW

File: packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts [hunk 1]
```diff
@@ -281,7 +281,13 @@ export const usePickerValue = <
     (dateState.lastControlledValue === undefined ||
       !valueManager.areValuesEqual(utils, dateState.lastControlledValue, inValue))
   ) {
-    setDateState((prev) => ({ ...prev, lastControlledValue: inValue, draft: inValue }));
+    setDateState((prev) => ({
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts:284]: For me we don't want to do that
Otherwise, when controlling your picker, you basically will never have an `onAccept` call on mobile since `onChange` will have been fired on the last view, `value` will have been updated and thus `dateState.lastCommittedValue` will equal the current value.

You can test it using the following example, open the picker, change the value and press "OK", it will not log anything

```tsx
import * as React from "react";
import moment, {Moment} from "moment";
import { DemoContainer } from "@mui/x-date-pickers/internals/demo";
import { AdapterMoment } from "@mui/x-date-pickers/AdapterMoment";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { MobileDatePicker } from "@mui/x-date-pickers/MobileDatePicker";

export default function BasicDatePicker() {
    const [date, setDate] = React.useState<Moment | null>(null);

    React.useEffect(() => {
        setDate(moment("2023-04-20"));
    }, []);

    return (
        <LocalizationProvider dateAdapter={AdapterMoment}>
            <DemoContainer components={["DatePicker"]}>
                <MobileDatePicker label="Basic date picker" value={date} onChange={setDate} onAccept={console.log} />
            </DemoContainer>
        </LocalizationProvider>
    );
}
```

I think the following diff is what we want

```diff
--- a/packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts
+++ b/packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts
@@ -270,18 +270,25 @@ export const usePickerValue = <
     }
   });
 
-  React.useEffect(() => {
-    if (isOpen) {
-      setDateState((prev) => ({ ...prev, lastCommittedValue: dateState.draft }));
-    }
-  }, [isOpen]); // eslint-disable-line react-hooks/exhaustive-deps
-
   if (
     inValue !== undefined &&
     (dateState.lastControlledValue === undefined ||
       !valueManager.areValuesEqual(utils, dateState.lastControlledValue, inValue))
   ) {
-    setDateState((prev) => ({ ...prev, lastControlledValue: inValue, draft: inValue }));
+    const isUpdateComingFromPicker = valueManager.areValuesEqual(utils, dateState.draft, inValue);
+
+    setDateState((prev) => ({
+      ...prev,
+      lastControlledValue: inValue,
+      ...(isUpdateComingFromPicker
+        ? {}
+        : {
+            lastCommittedValue: inValue,
+            lastPublishedValue: inValue,
+            draft: inValue,
+            hasBeenModifiedSinceMount: true,
+          }),
+    }));
   }
 
   const handleClear = useEventCallback(() => {
```

1. Always update `dateState.lastControlledValue` and `dateState.draft` when `props.value` changes
2. Always update the whole state when `props.value` changes AND is not equal to `dateState.draft` (i.e: it's a true external update)

**Comment by flaviendelangle** [comment]
This PR could probably also fix #8684

**Comment by alexfauquette** [comment]
> This PR could probably also fix https://github.com/mui/mui-x/issues/8684

Yes, I've added two tests:

- to detect the edge case you catch on my first proposal
- to detect the two issues opened

File: packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.test.tsx [hunk 2]
```diff
@@ -210,6 +216,46 @@ describe('<MobileDatePicker />', () => {
...
+      // Clean value using external control
+      setProps({ value: null });
+      expectInputValue(getTextbox(), '');
+
+      // Open and Dismiss the picker
+      userEvent.mousePress(screen.getByRole('textbox'));
+      userEvent.keyPress(document.activeElement!, { key: 'Escape' });
+      clock.runToLast();
+
+      // Verrify it's still a clean value
```
Comment (LukasTy) [inline packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.test.tsx:256]:
```suggestion
      // Verify it's still a clean value
```

File: packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts (hunk 1 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts:279]: Looks like a really nice solution! 👍

**Review by LukasTy — APPROVED** [review]
Very welcome fix! 🙏 🚀 
IMHO, we should aim to including it into the next (todays) release. 🙈

**Review by flaviendelangle — APPROVED** [review]
Nice fix !

**Comment by cherniavskii** [comment]
The merge commit seems to fail on the `master` branch: https://github.com/mui/mui-x/commits/master
Screenshot 2023-04-20 at 15 29 23

**Comment by flaviendelangle** [comment]
image

Looks like the branch was not up to date wit master
It's just a testing issue, no problem with the published package :pray:

**Comment by LukasTy** [comment]
Yeah, it's an unfortunate issue when merging stale branch. 🙈 
This was merged firstly and caused the issue...
https://github.com/mui/mui-x/commit/a654d4dc933cd5470b37c7687ad67e81e8c095dd#diff-55ddcd22d9bcd495df072548331e61a489744ae4828e53bc0bd096a80295a5cc

**Comment by MBilalShafi** [comment]
It was causing the CI to fail on https://github.com/mui/mui-x/pull/8690, I updated it there, should we fix this in a separate PR though?

**Comment by LukasTy** [comment]
> It was causing the CI to fail on #8690, I updated it there, should we fix this in a separate PR though?

I don't see the point of a separate PR. IMO, your fix would do nicely! 👌
