### PR TITLE
[pickers] Fix `aria-labelledby` assignment to dialog

### LINKED ISSUE #5632: [MobileDatePicker] Broken ARIA reference
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When scanning for accessibility issues using the app Wave. The MobileDatePicker generate the follow issue: 
"Broken ARIA reference "

 

### Expected behavior 🤔

The MobileDatePicker should not generate any accessibility issues.

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/responsivedatepickers-demo-mui-x-forked-wuwiu7?file=/demo.tsx

Steps:
1. Install the Wave extension in a chrome browser.
2. Click on the MobileDatePicker  or DatePiker with props desktopModeMediaQuery='never' to open a selection window
3. Scan the page with a Date Picker on.

MicrosoftTeams-image

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #5632 

Explicitly pass `aria-labelledby` referencing toolbar or text field label if toolbar is hidden

- [x] support mobile pickers
- [x] handle case when both label and toolbar are hidden
- [x] support mobile range picker
- [x] support desktop pickers
- [x] add test coverage

P.S. Desktop range pickers currently don't need similar changes, because they only support interaction through input element—the dialog is not being focused.

### CODE REVIEW

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx [hunk 1]
```diff
@@ -129,6 +151,36 @@ export const useDesktopPicker = <
...
+      labelledById = `${labelId}-label`;
+    } else {
+      labelledById = undefined;
+    }
+  }
+  if (
+    !labelledById &&
+    // ts complains about unknown prop access without casting
+    !(innerSlotProps?.popper as any)?.['aria-labelledby'] &&
+    process.env.NODE_ENV !== 'production' &&
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:166]: Try to set `if(process.env.NODE_ENV !== 'production')` and then another if inside with the other consitions.
That way, the `if` code is removed in production.

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx [hunk 2]
```diff
@@ -129,6 +151,36 @@ export const useDesktopPicker = <
...
+    // exclude cases of pickers without any available views (i.e. DesktopTimePicker)
+    Object.values(viewRenderers).filter(Boolean).length > 0
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:168]: Should be equivalent to `hasUIView`

File: packages/x-date-pickers/src/PickersLayout/PickersLayout.types.ts [hunk 3]
```diff
@@ -43,6 +43,10 @@ export interface ExportedPickersLayoutSlotsComponentsProps<TValue, TView extends
    * Props passed down to the layoutRoot component.
    */
   layout?: Partial<PickersLayoutProps<TValue, TView>>;
+  /**
+   * Props passed down to the toolbar component.
+   */
+  toolbar?: ExportedBaseToolbarProps;
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/PickersLayout/PickersLayout.types.ts:49]: Most of the time (if not always), we are using `ExportedXXX` to say that an interface contains only props exposed on the closest public component (here the picker).

The main goal being to avoid using `Omit` on the component typing to keep it clean and avoid inconsistencies between pickers.

If I understand correctly, your problem is that you need the slot `toolbar` to be accessible at the headless level (`useDesktopPicker` and `useMobilePicker`.
But if you just move it to the `Exposed` slots of the layout, then the pickers which are adding other props to the `toolbar` slots complains.

The solution you took is to `Omit` the `toolbar` slot coming from the headless interfaces.
It works, but if we could avoid introducing back any `Omit` at the component level it would be great.

An alternative is to create a `Exported` interface for the slots at the headless level:

```diff
--- a/packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.types.ts
+++ b/packages/x-date-pickers/src/DesktopDatePicker/DesktopDatePicker.types.ts
@@ -1,6 +1,6 @@
 import {
   UseDesktopPickerSlotsComponent,
-  UseDesktopPickerSlotsComponentsProps,
+  ExportedUseDesktopPickerSlotsComponentsProps,
   DesktopOnlyPickerProps,
 } from '../internals/hooks/useDesktopPicker';
 import {
@@ -19,7 +19,7 @@ export interface DesktopDatePickerSlotsComponent<TDate>
 
 export interface DesktopDatePickerSlotsComponentsProps<TDate>
   extends BaseDatePickerSlotsComponentsProps<TDate>,
-    UseDesktopPickerSlotsComponentsProps<TDate, DateView> {}
+    ExportedUseDesktopPickerSlotsComponentsProps<TDate, DateView> {}
 
 export interface DesktopDatePickerProps<TDate>
   extends BaseDatePickerProps<TDate>,
diff --git a/packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.types.ts b/packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.types.ts
index 13b04c563..979c499cb 100644
--- a/packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.types.ts
+++ b/packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePicker.types.ts
@@ -1,6 +1,6 @@
 import {
   UseDesktopPickerSlotsComponent,
-  UseDesktopPickerSlotsComponentsProps,
+  ExportedUseDesktopPickerSlotsComponentsProps,
   DesktopOnlyPickerProps,
 } from '../internals/hooks/useDesktopPicker';
 import {
@@ -22,7 +22,7 @@ export interface DesktopDateTimePickerSlotsComponent<TDate>
 
 export interface DesktopDateTimePickerSlotsComponentsProps<TDate>
   extends BaseDateTimePickerSlotsComponentsProps<TDate>,
-    Omit<UseDesktopPickerSlotsComponentsProps<TDate, DateOrTimeView>, 'toolbar'> {}
+    ExportedUseDesktopPickerSlotsComponentsProps<TDate, DateOrTimeView> {}
 
 export interface DesktopDateTimePickerProps<TDate>
   extends BaseDateTimePickerProps<TDate>,
diff --git a/packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.types.ts b/packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.types.ts
index 51e6e1293..994d41755 100644
--- a/packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.types.ts
+++ b/packages/x-date-pickers/src/DesktopTimePicker/DesktopTimePicker.types.ts
@@ -1,6 +1,6 @@
 import {
   UseDesktopPickerSlotsComponent,
-  UseDesktopPickerSlotsComponentsProps,
+  ExportedUseDesktopPickerSlotsComponentsProps,
   DesktopOnlyPickerProps,
 } from '../internals/hooks/useDesktopPicker';
 import {
@@ -19,7 +19,7 @@ export interface DesktopTimePickerSlotsComponent<TDate>
 
 export interface DesktopTimePickerSlotsComponentsProps<TDate>
   extends BaseTimePickerSlotsComponentsProps,
-    Omit<UseDesktopPickerSlotsComponentsProps<TDate, TimeView>, 'toolbar'> {}
+    ExportedUseDesktopPickerSlotsComponentsProps<TDate, TimeView> {}
 
 export interface DesktopTimePickerProps<TDate>
   extends BaseTimePickerProps<TDate>,
diff --git a/packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.types.ts b/packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.types.ts
index 99e1576ba..83639c495 100644
--- a/packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.types.ts
+++ b/packages/x-date-pickers/src/MobileDatePicker/MobileDatePicker.types.ts
@@ -1,7 +1,7 @@
 import {
   UseMobilePickerSlotsComponent,
-  UseMobilePickerSlotsComponentsProps,
   MobileOnlyPickerProps,
+  ExportedUseMobilePickerSlotsComponentsProps,
 } from '../internals/hooks/useMobilePicker';
 import {
   BaseDatePickerProps,
@@ -19,7 +19,7 @@ export interface MobileDatePickerSlotsComponent<TDate>
 
 export interface MobileDatePickerSlotsComponentsProps<TDate>
   extends BaseDatePickerSlotsComponentsProps<TDate>,
-    UseMobilePickerSlotsComponentsProps<TDate, DateView> {}
+    ExportedUseMobilePickerSlotsComponentsProps<TDate, DateView> {}
 
 export interface MobileDatePickerProps<TDate>
   extends BaseDatePickerProps<TDate>,
diff --git a/packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.types.ts b/packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.types.ts
index 9abfefceb..ea2247309 100644
--- a/packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.types.ts
+++ b/packages/x-date-pickers/src/MobileDateTimePicker/MobileDateTimePicker.types.ts
@@ -1,6 +1,6 @@
 import {
   UseMobilePickerSlotsComponent,
-  UseMobilePickerSlotsComponentsProps,
+  ExportedUseMobilePickerSlotsComponentsProps,
   MobileOnlyPickerProps,
 } from '../internals/hooks/useMobilePicker';
 import {
@@ -19,7 +19,7 @@ export interface MobileDateTimePickerSlotsComponent<TDate>
 
 export interface MobileDateTimePickerSlotsComponentsProps<TDate>
   extends BaseDateTimePickerSlotsComponentsProps<TDate>,
-    Omit<UseMobilePickerSlotsComponentsProps<TDate, DateOrTimeView>, 'toolbar'> {}
+    ExportedUseMobilePickerSlotsComponentsProps<TDate, DateOrTimeView> {}
 
 export interface MobileDateTimePickerProps<TDate>
   extends BaseDateTimePickerProps<TDate>,
diff --git a/packages/x-date-pickers/src/MobileTimePicker/MobileTimePicker.types.ts b/packages/x-date-pickers/src/MobileTimePicker/MobileTimePicker.types.ts
index 4f03f5962..8dacf5a07 100644
--- a/packages/x-date-pickers/src/MobileTimePicker/MobileTimePicker.types.ts
+++ b/packages/x-date-pickers/src/MobileTimePicker/MobileTimePicker.types.ts
@@ -1,6 +1,6 @@
 import {
   UseMobilePickerSlotsComponent,
-  UseMobilePickerSlotsComponentsProps,
+  ExportedUseMobilePickerSlotsComponentsProps,
   MobileOnlyPickerProps,
 } from '../internals/hooks/useMobilePicker';
 import {
@@ -19,7 +19,7 @@ export interface MobileTimePickerSlotsComponent<TDate>
 
 export interface MobileTimePickerSlotsComponentsProps<TDate>
   extends BaseTimePickerSlotsComponentsProps,
-    Omit<UseMobilePickerSlotsComponentsProps<TDate, TimeView>, 'toolbar'> {}
+    ExportedUseMobilePickerSlotsComponentsProps<TDate, TimeView> {}
 
 export interface MobileTimePickerProps<TDate>
   extends BaseTimePickerProps<TDate>,
diff --git a/packages/x-date-pickers/src/PickersLayout/PickersLayout.types.ts b/packages/x-date-pickers/src/PickersLayout/PickersLayout.types.ts
index e0b2e19ee..7908f61b5 100644
--- a/packages/x-date-pickers/src/PickersLayout/PickersLayout.types.ts
+++ b/packages/x-date-pickers/src/PickersLayout/PickersLayout.types.ts
@@ -43,10 +43,6 @@ export interface ExportedPickersLayoutSlotsComponentsProps<TValue, TView extends
    * Props passed down to the layoutRoot component.
    */
   layout?: Partial<PickersLayoutProps<TValue, TView>>;
-  /**
-   * Props passed down to the toolbar component.
-   */
-  toolbar?: ExportedBaseToolbarProps;
 }
 
 export interface PickersLayoutSlotsComponent<TValue, TView extends DateOrTimeView>
@@ -68,6 +64,10 @@ export interface PickersLayoutSlotsComponentsProps<TValue, TView extends DateOrT
    * Props passed down to the tabs component.
    */
   tabs?: ExportedBaseTabsProps;
+  /**
+   * Props passed down to the toolbar component.
+   */
+  toolbar?: ExportedBaseToolbarProps;
 }
 
 export interface PickersLayoutProps<TValue, TView extends DateOrTimeView>
diff --git a/packages/x-date-pickers/src/internals/hooks/useDesktopPicker/index.ts b/packages/x-date-pickers/src/internals/hooks/useDesktopPicker/index.ts
index 2d7ec95c5..b7d3c5fd8 100644
--- a/packages/x-date-pickers/src/internals/hooks/useDesktopPicker/index.ts
+++ b/packages/x-date-pickers/src/internals/hooks/useDesktopPicker/index.ts
@@ -2,5 +2,6 @@ export { useDesktopPicker } from './useDesktopPicker';
 export type {
   UseDesktopPickerSlotsComponent,
   UseDesktopPickerSlotsComponentsProps,
+  ExportedUseDesktopPickerSlotsComponentsProps,
   DesktopOnlyPickerProps,
 } from './useDesktopPicker.types';
diff --git a/packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.types.ts b/packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.types.ts
index 06e81d72d..3c805cd6c 100644
--- a/packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.types.ts
+++ b/packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.types.ts
@@ -18,6 +18,7 @@ import { BaseFieldProps } from '../../models/fields';
 import {
   ExportedPickersLayoutSlotsComponent,
   ExportedPickersLayoutSlotsComponentsProps,
+  PickersLayoutSlotsComponentsProps,
 } from '../../../PickersLayout/PickersLayout.types';
 import { UsePickerValueNonStaticProps } from '../usePicker/usePickerValue';
 import { UsePickerViewsNonStaticProps, UsePickerViewsProps } from '../usePicker/usePickerViews';
@@ -53,6 +54,10 @@ export interface UseDesktopPickerSlotsComponent<TDate, TView extends DateOrTimeV
 }
 
 export interface UseDesktopPickerSlotsComponentsProps<TDate, TView extends DateOrTimeView>
+  extends ExportedUseDesktopPickerSlotsComponentsProps<TDate, TView>,
+    Pick<PickersLayoutSlotsComponentsProps<TDate | null, TView>, 'toolbar'> {}
+
+export interface ExportedUseDesktopPickerSlotsComponentsProps<TDate, TView extends DateOrTimeView>
   extends PickersPopperSlotsComponentsProps,
     ExportedPickersLayoutSlotsComponentsProps<TDate | null, TView> {
   field?: SlotComponentProps<
diff --git a/packages/x-date-pickers/src/internals/hooks/useMobilePicker/index.ts b/packages/x-date-pickers/src/internals/hooks/useMobilePicker/index.ts
index f38c04003..761b84a6d 100644
--- a/packages/x-date-pickers/src/internals/hooks/useMobilePicker/index.ts
+++ b/packages/x-date-pickers/src/internals/hooks/useMobilePicker/index.ts
@@ -2,5 +2,6 @@ export { useMobilePicker } from './useMobilePicker';
 export type {
   UseMobilePickerSlotsComponent,
   UseMobilePickerSlotsComponentsProps,
+  ExportedUseMobilePickerSlotsComponentsProps,
   MobileOnlyPickerProps,
 } from './useMobilePicker.types';
diff --git a/packages/x-date-pickers/src/internals/hooks/useMobilePicker/useMobilePicker.types.ts b/packages/x-date-pickers/src/internals/hooks/useMobilePicker/useMobilePicker.types.ts
index ceae1cd31..951539bf5 100644
--- a/packages/x-date-pickers/src/internals/hooks/useMobilePicker/useMobilePicker.types.ts
+++ b/packages/x-date-pickers/src/internals/hooks/useMobilePicker/useMobilePicker.types.ts
@@ -16,6 +16,7 @@ import { BaseFieldProps } from '../../models/fields';
 import {
   ExportedPickersLayoutSlotsComponent,
   ExportedPickersLayoutSlotsComponentsProps,
+  PickersLayoutSlotsComponentsProps,
 } from '../../../PickersLayout/PickersLayout.types';
 import { UsePickerValueNonStaticProps } from '../usePicker/usePickerValue';
 import { UsePickerViewsNonStaticProps, UsePickerViewsProps } from '../usePicker/usePickerViews';
@@ -36,7 +37,7 @@ export interface UseMobilePickerSlotsComponent<TDate, TView extends DateOrTimeVi
   TextField?: React.ElementType<TextFieldProps>;
 }
 
-export interface UseMobilePickerSlotsComponentsProps<TDate, TView extends DateOrTimeView>
+export interface ExportedUseMobilePickerSlotsComponentsProps<TDate, TView extends DateOrTimeView>
   extends PickersModalDialogSlotsComponentsProps,
     ExportedPickersLayoutSlotsComponentsProps<TDate | null, TView> {
   field?: SlotComponentProps<
@@ -47,6 +48,10 @@ export interface UseMobilePickerSlotsComponentsProps<TDate, TView extends DateOr
   textField?: SlotComponentProps<typeof TextField, {}, Record<string, any>>;
 }
 
+export interface UseMobilePickerSlotsComponentsProps<TDate, TView extends DateOrTimeView>
+  extends ExportedUseMobilePickerSlotsComponentsProps<TDate, TView>,
+    Pick<PickersLayoutSlotsComponentsProps<TDate | null, TView>, 'toolbar'> {}
+
 export interface MobileOnlyPickerProps<TDate>
   extends BaseNonStaticPickerProps,
     UsePickerValueNonStaticProps<TDate | null>,
```

It is slightly more verbose for sure, but it avoids the `Omit` on each picker, keeping the tweaking at the headless level.

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx [hunk 4]
```diff
@@ -13,6 +13,13 @@ import { WrapperVariantContext } from '../../components/wrappers/WrapperVariantC
 import { BaseFieldProps } from '../../models/fields';
 import { PickersLayout } from '../../../PickersLayout';
 import { InferError } from '../validation/useValidation';
+import { buildWarning } from '../../utils/warning';
+
+const ariaLabelledByCantBeResolvedWarning = buildWarning([
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:18]: That's not strictly speaking a breaking change.
But it's something I am pretty sure will cause warning in a lot of application.
I would be interested to know how the core handles similar situations where people have a non accessible app.
Do we force them to be accessible with a warning, or do we let them be ?

@mnajdova maybe

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx [hunk 5]
```diff
@@ -2,7 +2,7 @@ import * as React from 'react';
 import { resolveComponentProps, useSlotProps } from '@mui/base/utils';
 import MuiInputAdornment from '@mui/material/InputAdornment';
 import IconButton from '@mui/material/IconButton';
-import useForkRef from '@mui/utils/useForkRef';
+import { unstable_useId as useId, unstable_useForkRef as useForkRef } from '@mui/utils';
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:5]: I know that we are not following this rule well, but I would prefer to avoid root import from any package
We could add a lint rule at some point

See https://github.com/mui/material-ui/issues/35840

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx (hunk 1 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:166]: Should our build process do it? 🤔 
It does not seem to happen after I've tested it. 🙈

Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:166]: Or did you only mean that it could by an option if someone would choose so?
Because yeah, I think we ought to ship it so that others writing tests would also be able to see this warning pop up.

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx (hunk 5 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:5]: We could do a once over the x packages and replace existing root imports. 🤔

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:5]: We would have to check if `@mui/utils` have clean nested export for everything (I think it does not have any `@mui/` deps re-exports so it should be fine)

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx (hunk 1 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:166]: I think it's usually people's build step which removes all the `if(process.env.NODE_END !== 'production') {}` because it is transformed into `if(false) {}` which is automatically removed.

The change I propose (and that we are applying on our others dev-only warnings) it just here to allow their build step to strip it correctly :+1:

Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:166]: Yeah, was thinking about just that. 👌 
Will update, thanks for spotting it. 😉

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx (hunk 2 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:168]: Yes, it is, thanks for spotting. 😉

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx (hunk 4 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:18]: It could be a breaking change for someone, who also has configured testing framework to fail when encountering `console.warn` or `console.error`. 🤔

File: packages/x-date-pickers/src/PickersLayout/PickersLayout.types.ts (hunk 3 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/PickersLayout/PickersLayout.types.ts]: Yes, indeed, you understood my requirement correctly.
I've played around with your suggested diff and it seems to cover my requirement with a cleaner solution. I'll go with it, thanks. 👍

Comment (flaviendelangle) [reply packages/x-date-pickers/src/PickersLayout/PickersLayout.types.ts]: By the way, I have the same problem with the `Field` slot
The current typing is not correct and fire errors if you try to pass a custom `field` slot on your picker.
We will need to remove it from the exported slot of `useDesktopPicker` and define it at the component level instead (or in a `NonStaticDatePickerSlotsComponent` interface if we want to share between mobile and desktop variants.

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx (hunk 4 above)
Comment (alexfauquette) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:19]: Their is also the scenario of a developer being accessible thanks to other methods, such as `aria-label`. They would get the warning even if they do not need it.

I do no remember warning from material about accessibility. But all their components have an explanation about what should be provided to be accessible.

Maybe the solution is to do not use warning but encourage its usage thanks to  section in the documentation

Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx:19]: Very good point.
I also noticed that even in our docs we sometimes do not have a `label` provided and warning is thrown in such cases.
I'll remove the warnings and look for the best place to provide the documentation in. 👌

File: packages/x-date-pickers-pro/src/internal/hooks/useMobileRangePicker/useMobileRangePicker.tsx [hunk 6]
```diff
@@ -155,16 +172,47 @@ export const useMobileRangePicker = <
...
+    if (!finalLocaleText?.start && !finalLocaleText?.end) {
+      labelledById = undefined;
+    } else {
+      if (finalLocaleText.start) {
+        labelledById = `${labelId}-start-label`;
+      }
+      if (finalLocaleText.end) {
+        labelledById += ` ${labelId}-end-label`;
+      }
+    }
```
[the remark this answers is not in the document]
Comment (LukasTy) [reply packages/x-date-pickers-pro/src/internal/hooks/useMobileRangePicker/useMobileRangePicker.tsx:201]: > Would it be ok if the `aria-labelledby` start with a space (case with only `end` defined)?

It shouldn't be a problem, but indeed, i did not think about it, but your solution is cleaner. 👍

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx (hunk 4 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx]: I've added a section about a11y [here](https://github.com/mui/mui-x/pull/7608/files#diff-fa38598fe4ffcdee6ccec38dd96a24cef9faf2bb723808ad0af55f4c75a51571R86). What do you think?

File: docs/data/date-pickers/base-concepts/base-concepts.md [hunk 7]
```diff
@@ -83,6 +83,19 @@ There are many components available, each fitting specific use cases. Use the fo
 
 {{"demo": "ComponentExplorerNoSnap.js", "hideToolbar": true}}
 
+## Accessibility
+
+Both `Desktop` and `Mobile` Date and Time Pickers are using `role="dialog"` to display their interactive view parts and thus they should follow [Modal accessibility guidelines](/material-ui/react-modal/#accessibility).
+This behavior is automated as much as possible, ensuring that the Date and Time Pickers are accessible in most cases.
+A correct `aria-labelledby` value is assigned to the dialog component based on the following rules:
+
+- Use `toolbar` id if it is not hidden;
```
Comment (alexfauquette) [inline docs/data/date-pickers/base-concepts/base-concepts.md:92]:
```suggestion
- Use `toolbar` id if the toolbar is visible;
```
 or 
```suggestion
- Use the id of the toolbar if it exists;
```

File: docs/data/date-pickers/base-concepts/base-concepts.md [hunk 8]
```diff
@@ -83,6 +83,19 @@ There are many components available, each fitting specific use cases. Use the fo
...
+- Use `label` id (or `start` and `end` ids in case of range picker) if `toolbar` is hidden;
```
Comment (alexfauquette) [inline docs/data/date-pickers/base-concepts/base-concepts.md:93]:
```suggestion
- Use the id of the input label if the toolbar is hidden;
```

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx (hunk 4 above)
Comment (mnajdova) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx]: > Do we force them to be accessible with a warning, or do we let them be ?

I don't think we even warn for issues regarding a11y.

**Review by alexfauquette — APPROVED** [review]

File: packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx (hunk 4 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/useDesktopPicker/useDesktopPicker.tsx]: @mnajdova Thank you for the confirmation.
We've updated the solution to include documentation section and removed the warnings. 👌
