### PR TITLE
[pickers] Fix `AdapterDateFnsV3` generated method types

### LINKED ISSUE #13226: [pickers] AdapterDateFnsV3: Wrong types generated
### Steps to reproduce

Link to live example: (https://codesandbox.io/p/sandbox/brave-matsumoto-9t8tqx?file=%2Fsrc%2FDemo.tsx%3A16%2C2)

Steps:
1. Open sandbox
2. Check produced TS type of `const res` in `test` function
3. Or open [AdapterDateFnsV3](https://codesandbox.io/p/sandbox/brave-matsumoto-9t8tqx?file=%2Fnode_modules%2F.store%2F%40mui%2Fx-date-pickers%407.5.0%2Fnode_modules%2F%40mui%2Fx-date-pickers%2FAdapterDateFnsV3%2FAdapterDateFnsV3.d.ts%3A78%2C55) file 

### Current behavior

Return types of `AdapterDateFnsV3` functions are mostly `any` instead of their actual values
image

### Expected behavior

Correspond to `MuiPickersAdapter` [interface](https://github.com/mui/mui-x/blob/4a77854effb40ad0b13aefc5c16811ca67d46fa4/packages/x-date-pickers/src/models/adapters.ts#L162)

### Context

I'm trying to write an extended version of `DateUtilsAdapterV3` with some custom utility functions and they reuse function if `DateUtilsAdapterV3`, which provides wrong typings.

### Your environment

Executed in a devbox: https://codesandbox.io/p/devbox/y8p8k9?file=%2Fsrc%2FDemo.tsx%3A5%2C48

<details>
  <summary><code>npx @mui/envinfo</code></summary>
```
  Don't forget to mention which browser you used.
    System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: latest => 11.11.4 
    @emotion/styled: latest => 11.11.5 
    @mui/material: next => 6.0.0-alpha.8 
    @mui/x-date-pickers: latest => 7.5.1 
    @types/react: latest => 18.3.2 
    react: latest => 18.3.1 
    react-dom: latest => 18.3.1 
    typescript: latest => 5.4.5
```
</details>

Used browser: Version 125.0.6422.61 (Official Build) (arm64)

**Search keywords**: adapterdatefnsv3 date-fns date-fns-v3

### PR DESCRIPTION
**Pull request by alexey-kozlenkov**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #13226 as suggested in the comments.

Applied to both `AdapterDateFnsJalaliV3` & `AdapterDateFnsV3` who rely on date-fns-v3
UPD: Applied to Adapters based on **date-fns-v2** as well so the don't lose types when dependency is switched to date-fns-v3

### CODE REVIEW

File: packages/x-date-pickers/src/AdapterDateFnsV3/AdapterDateFnsV3.ts [hunk 1]
```diff
@@ -103,31 +103,32 @@ export class AdapterDateFns
     super({ locale: locale ?? enUS, formats, longFormatters });
   }
 
-  public parse = (value: string, format: string) => {
+  // TODO: remove explicit returns in all methods when date-fns-v3 becomes default
+  public parse = (value: string, format: string): Date | null => {
```
Comment (alexey-kozlenkov) [inline packages/x-date-pickers/src/AdapterDateFnsV3/AdapterDateFnsV3.ts:107]: Not sure if using just `Date` in these returns would work if client dev re-defines it.
Perhaps should be smth like `PickerValidDateLookup['date-fns']` instead? 
Maintainers please advise 🙏

Comment (LukasTy) [reply packages/x-date-pickers/src/AdapterDateFnsV3/AdapterDateFnsV3.ts:107]: > Not sure if using just `Date` in these returns would work if client dev re-defines `PickerValidDateLookup` value.

I'm pretty sure that it shouldn't be a problem. 👌 
The `PickerValidDateLookup` type is not designed for that behavior and would not work on existing adapters as well, because they are statically typing the `TDate` as `Date`. 🙈 🤷 
https://github.com/mui/mui-x/blob/a10624a9c65d9b3301b1c8bd28b43dc1c2a22f20/packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts#L85

**Review by LukasTy — COMMENTED** [review]
Thank you for your contribution! 🙏 

I think that adding explicit types to the `V2` adapters wouldn't hurt as well as it would allow us to avoid this problem if we keep both adapters, but just swap the defaults (use v3 in the repo as the default).
It's not a deal-breaker, but depending on who would take on that work and reviewing it, this additional work could help avoiding a very similar problem with V2 adapter in that case.
WDYT? 🤔

File: packages/x-date-pickers/src/AdapterDateFnsV3/AdapterDateFnsV3.ts (hunk 1 above)
Comment (alexey-kozlenkov) [reply packages/x-date-pickers/src/AdapterDateFnsV3/AdapterDateFnsV3.ts:107]: Gotcha

**Comment by alexey-kozlenkov** [comment]
@LukasTy makes sense. I’m away from laptop till next week, will come back to it Monday and supply for date-fns v2

**Comment by LukasTy** [comment]
> makes sense. I’m away from laptop till next week, will come back to it Monday and supply for date-fns v2

Ok, thanks for the update, let's wait for next week. 👌 
Have a nice time off. 😉

**Comment by alexey-kozlenkov** [comment]
@LukasTy all done. Have a look please once you have time 🙌

**Review by LukasTy — APPROVED** [review]
Thank you so much for taking care of it! 🙏 
Great job. 👏 💯
