### PR TITLE
[core] Fix shortcuts when Caps Lock enabled

### LINKED ISSUE #11790: [data grid] Unable to Paste Row Data in Data Grid with CAPS Lock Key Enabled
### Steps to reproduce

Link to live example: https://mui.com/x/react-data-grid/clipboard/

Steps:
1. Go to the **Clipboard paste** section
2. Copy several columns of data from a spreadsheet (e.g., Excel)
3. Enable the CAPS lock key
4. Click on the first cell
5. Attempt to paste data using CTRL + V

### Current behavior

When attempting to paste a row of data with CTRL + V while the CAPS lock key is enabled, nothing will happen.  However, if you disable the CAPS lock key, the data will be pasted as expected.

### Expected behavior

Row data should be successfully pasted regardless of the status of the CAPS lock key

### Context

Trying to allow users to paste rows of data from Excel to a data grid for uploading

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Version 120.0.6099.225 (Official Build) (64-bit)
    Edge: Version 120.0.2210.144 (Official build) (64-bit)
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.9
    @mui/core-downloads-tracker:  5.14.3
    @mui/icons-material: ^5.8.4 => 5.8.4
    @mui/material: ^5.12.3 => 5.14.3
    @mui/private-theming:  5.13.7
    @mui/styled-engine:  5.13.2
    @mui/styles: ^5.9.3 => 5.9.3
    @mui/system:  5.14.3
    @mui/types:  7.2.4
    @mui/utils:  5.14.3
    @mui/x-data-grid: ^6.3.1 => 6.18.6
    @mui/x-data-grid-premium: ^6.10.2 => 6.18.6
    @mui/x-data-grid-pro:  6.18.6
    @mui/x-date-pickers: ^6.2.1 => 6.2.1
    @mui/x-license-pro:  6.10.2
    @types/react: 18.0.13 => 18.0.13
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ~4.7.2 => 4.7.4
```
</details>

**Search keywords**: caps lock, data grid, past

### PR DESCRIPTION
**Pull request by oliviertassinari**
IMHO, if we close #11790, I think it should be after we fully fixed the issue. #11965 is a step, but there is more. Here is a quick PR to go more in depth:

- `toLowerCase` is missing in a good chunk of other cases
- We don't need a double if
- We can apply the same alternative keys check in all the other places
- Left a note about a bug in macOS but I suspect it's overkill to fix (not worth the extra bundle size)

### CODE REVIEW

File: packages/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts [hunk 1]
```diff
@@ -304,11 +304,13 @@ function defaultPasteResolver({
   });
 }
 
-const isPasteShortcut = (event: React.KeyboardEvent) => {
```
Comment (oliviertassinari) [inline packages/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts:307]: Revert that arrow function, it goes against the style convention in the org.

**Review by romgrk — APPROVED** [review]
