### PR TITLE
[core] Drop usage of `GRID_EXPERIMENTAL_ENABLED` env variable

### LINKED ISSUE #5673: `process.env` is undefined
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently, under `envConstants.ts`, the following code is checking whether `GRID_EXPERIMENTAL_ENABLED` is present.

A check is done whether `process` is defined or not, and if it is, it assumes it has `env` property on it.
That's not always the case, it could be undefined which makes the code break.

### Expected behavior 🤔

It should be able to cope and acknowledge that `process.env` is not always defined.

### Steps to reproduce 🕹

_No response_

### Context 🔦

I'm running `cypress` component testing via `vite` and it doesn't inject `env` to `process` as one would expect. 
In such a case, the app crashes and I'm not able to test my code.

### Your environment 🌎

_No response_

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by ar7casper**
Fixes #5673

When using cypress with `vite`, envConstants.ts fails cause it assumes `process.env` is defined, where it might be undefined.

### CODE REVIEW

File: packages/grid/x-data-grid/src/constants/envConstants.ts [hunk 1]
```diff
@@ -22,13 +22,13 @@ let experimentalEnabled = false;
 
 if (
   typeof process !== 'undefined' &&
-  process.env.GRID_EXPERIMENTAL_ENABLED !== undefined &&
+  process.env?.GRID_EXPERIMENTAL_ENABLED !== undefined &&
```
Comment (LukasTy) [inline packages/grid/x-data-grid/src/constants/envConstants.ts:25]: Thank you for your contribution!

What do you think about making in the initial check more explicit?
```ts
process?.env &&
process.env.GRID_EXPERIMENTAL_ENABLED !== undefined &&
```
The same idea/suggestion would apply to the L30 & L31.

Comment (ar7casper) [reply packages/grid/x-data-grid/src/constants/envConstants.ts:25]: @LukasTy We could, but essentially these are the same -

`process?.env?.Foo`
`process && process.env && process.env.Foo`.

Comment (LukasTy) [reply packages/grid/x-data-grid/src/constants/envConstants.ts:25]: Yes, they are, my idea was that in this case the existing check for `process` is redundant as it is defined in your runtime as well, but what is undefined is actually `env` object.
That's why I was suggesting to replace the existing check to actually safe-guard against environments where `env` object is not exposed/loaded.

File: packages/grid/x-data-grid/src/constants/envConstants.ts [hunk 2]
```diff
@@ -22,13 +22,13 @@ let experimentalEnabled = false;
 
 if (
   typeof process !== 'undefined' &&
-  process.env.GRID_EXPERIMENTAL_ENABLED !== undefined &&
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/constants/envConstants.ts:25]: I haven't used this flag and didn't even know it exists.
We rather use `experimentalFeatures` prop which is usually mentioned in the docs and - see [Editing](https://mui.com/x/react-data-grid/editing/) or [Aggregation](https://mui.com/x/react-data-grid/aggregation/) for example.

There's only one place using this flag:
https://github.com/mui/mui-x/blob/9593984c724e16cf6a06b244c427a7d3b197a564/packages/grid/x-data-grid/src/components/panel/GridColumnsPanel.tsx#L156

You can see it in action in [this PR deployment](https://deploy-preview-4863--material-ui-x.netlify.app/x/react-data-grid/demo/), but those are just disabled buttons that do nothing:

Screenshot 2022-08-01 at 14 24 00

So I'm not sure what was the goal here.

I would rather remove this flag from the codebase completely.
We can keep exporting `GRID_EXPERIMENTAL_ENABLED` set to `false` just for the sake of 100% backward compatibility.

Comment (LukasTy) [reply packages/grid/x-data-grid/src/constants/envConstants.ts:25]: Totally agree with your suggestion if we can go this route.
I've also checked it and didn't understand the reason behind it, because even with it enabled the feature does seem disabled.
Maybe @DanailH remembers the reason behind it?

Comment (DanailH) [reply packages/grid/x-data-grid/src/constants/envConstants.ts:25]: I think this was added before because of the documentation - so specific features did not appear there.

Comment (ar7casper) [reply packages/grid/x-data-grid/src/constants/envConstants.ts:25]: @LukasTy @DanailH @cherniavskii 

Would you like me to update the PR with - 
```typescript
export const GRID_EXPERIMENTAL_ENABLED = false
```
?

Comment (LukasTy) [reply packages/grid/x-data-grid/src/constants/envConstants.ts:25]: To me it would seem like a reasonable fix, at least for now, but I don't know what is/was the teams plan with this unfinished column re-ordering feature, hence whoever worked on it could suggest the best course of action.

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/constants/envConstants.ts:25]: @ar7casper I think so, unless @DanailH has objections

Comment (DanailH) [reply packages/grid/x-data-grid/src/constants/envConstants.ts:25]: I think we can move forward.

Comment (ar7casper) [reply packages/grid/x-data-grid/src/constants/envConstants.ts:25]: @DanailH @cherniavskii Done, can you allow the pipeline please?

Comment (LukasTy) [reply packages/grid/x-data-grid/src/constants/envConstants.ts:25]: Should we maybe also remove the logic related to populating `GRID_EXPERIMENTAL_ENABLED` environment variable as well?
There are two instances. One in `docs/next.config.js` and other in `packages/storybook/.storybook/main.ts`

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/constants/envConstants.ts:25]: I've updated the PR to remove unnecessary occurrences of `GRID_EXPERIMENTAL_ENABLED`

**Review by cherniavskii — APPROVED** [review]

**Review by LukasTy — APPROVED** [review]
