### PR TITLE
[DataGridPro] Fix selection propagation issue on initialization

### LINKED ISSUE #15382: [Datagrid] Bug when initializing selection with row grouping and `rowSelectionPropagation`
### Search keywords

rowSelectionPropagation datagrid row grouping

### Latest version

- [X] I have tested the latest version

### Affected products

Data Grid

### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/lucid-snow-58c6ld

Steps:
1. Open the group of "20th Century Fox"
2. Open "James Cameron"

### Current behavior

All the children of group "James Cameron" are selected, the group's checkbox is in the intermediate state.

### Expected behavior

Having
```
rowSelectionPropagation={{ parents: true, descendants: true }}
```
I would expect the checkbox of group "James Cameron" is selected. The docs says:
> Selecting all the filtered descendants of a parent selects the parent automatically

https://mui.com/x/react-data-grid/row-grouping/#automatic-parents-and-children-selection 

Deselecting and selecting one of the children makes the parent selected as expected.

Maybe there's a race condition during loading the table. 

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
  Binaries:
    Node: 18.19.1 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 130.0.6723.116
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/core-downloads-tracker:  6.1.6 
    @mui/icons-material: ^6.1.6 => 6.1.6 
    @mui/material: ^6.1.6 => 6.1.6 
    @mui/private-theming:  6.1.6 
    @mui/styled-engine:  6.1.6 
    @mui/system:  6.1.6 
    @mui/types:  7.2.19 
    @mui/utils:  6.1.6 
    @mui/x-charts: ^7.22.1 => 7.22.1 
    @mui/x-charts-vendor:  7.20.0 
    @mui/x-data-grid:  7.22.1 
    @mui/x-data-grid-premium: ^7.22.1 => 7.22.1 
    @mui/x-data-grid-pro:  7.22.1 
    @mui/x-date-pickers:  7.22.1 
    @mui/x-date-pickers-pro: ^7.22.1 => 7.22.1 
    @mui/x-internals:  7.21.0 
    @mui/x-license:  7.21.0 
    @mui/x-tree-view: ^7.22.1 => 7.22.1 
    @types/react:  18.3.12 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 

```
</details>

### Order ID or Support key 💳 (optional)

101072

### PR DESCRIPTION
**Pull request by MBilalShafi**
Fixes #15382

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts [hunk 1]
```diff
@@ -453,9 +453,6 @@ export const useGridRowSelection = (
   const isFirstRender = React.useRef(true);
   const removeOutdatedSelection = React.useCallback(
     (sortModelUpdated = false) => {
-      if (isFirstRender.current) {
```
Comment (arminmeh) [inline packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:456]: `isFirstRender` is not used anymore. it can be cleared from the file

with that
how does this affect https://github.com/mui/mui-x/pull/14909
since that was the only change added to address that issue

Comment (MBilalShafi) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:456]: Thanks, cleaned up `isFirstRender`.

> how does this affect https://github.com/mui/mui-x/pull/14909

#15184 removed the root cause for #14909, `isFirstRender` ref was not needed anymore for that fix.
