### PR TITLE
[clock picker] Should call shouldDisableTime with the hours with meridiem

### LINKED ISSUE #4403: [ClockPicker] `shouldDisableTime` does not work properly in AM / PM mode
### Duplicates

- [X] I have searched the existing issues

This thing was for an older version but doesn't seem to have been fixed https://github.com/mui/material-ui-pickers/issues/2117

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When TimePicker is in AM/PM mode shouldDisableTime receives timeValue (number) and clockType ("hours" | "minutes" | "seconds"). The issue is that since timeValue is an integer from 0-12 and we aren't able to tell whether AM or PM is selected on the time picker there is not enough information available to select dates.

### Expected behavior 🤔

timeValue should always be in 24 hour format or am / pm should be passed to the function.

### Steps to reproduce 🕹

Steps:

1. You can use the code below to see this

```tsx
    const [startTimeValue, setStartTimeValue] = useState<Date | null>(new Date());

    function hasNoAvailibityForTime(timeValue: any, clockType: string) {
        console.log(timeValue); // how do we know whether the timeValue is am or pm?
    }

      <TimePicker
          label={'Start Time'}
          value={startTimeValue}
          onChange={setStartTimeValue}
          renderInput={(params) => <TextField {...params} />}
          shouldDisableTime={hasNoAvailibityForTime}
          ampm={true}
          views={['hours']}
      />
```

### Context 🔦

I am using this component to allow others to select an available time on someone's calendar. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
npx: installed 2 in 2.254s

  System:
    OS: macOS 12.2.1
  Binaries:
    Node: 14.17.3 - ~/.asdf/installs/nodejs/14.17.3/bin/node
    Yarn: Not Found
    npm: 6.14.13 - ~/.asdf/installs/nodejs/14.17.3/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Edge: Not Found
    Firefox: 98.0
    Safari: 15.3
  npmPackages:
    @emotion/react: ^11.8.1 => 11.8.1
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.70
    @mui/icons-material: ^5.4.4 => 5.4.4
    @mui/lab: ^5.0.0-alpha.73 => 5.0.0-alpha.73
    @mui/material: ^5.4.4 => 5.4.4
    @mui/private-theming:  5.4.4
    @mui/styled-engine:  5.4.4
    @mui/system:  5.4.4
    @mui/types:  7.1.2
    @mui/utils:  5.4.4
    @types/react: ^16.14.6 => 16.14.8
    react: ^16.14.0 => 16.14.0
    react-dom: ^16.12.0 => 16.13.1
    styled-components: ^5.0.0 => 5.1.1
    typescript: ^4.2.4 => 4.3.2
```
</details>

I used firefox

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #4403

We were passing the raw value to `shouldDisableTime`
So when using AM/PM, we were passing `3` for `3PM` instead of `15`.

### CODE REVIEW

File: packages/x-date-pickers/src/ClockPicker/ClockPicker.tsx [hunk 1]
```diff
@@ -263,7 +263,10 @@ export const ClockPicker = React.forwardRef(function ClockPicker<TDate extends u
         return false;
       }
 
-      const validateTimeValue = (getRequestedTimePoint: (when: 'start' | 'end') => TDate) => {
+      const validateTimeValue = (
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/ClockPicker/ClockPicker.tsx:266]: I find this whole method with the pipe very convoluted
But I don't want to change anything non-trivial before knowing the codebase better

File: packages/x-date-pickers/src/ClockPicker/ClockPicker.test.tsx [hunk 2]
```diff
@@ -170,6 +170,28 @@ describe('<ClockPicker />', () => {
...
+      />,
+    );
+
+    const hours = shouldDisableTime
+      .getCalls()
+      .filter((el) => el.lastArg === 'hours')
+      .map((el) => el.firstArg);
+
+    // Should be called with every hour from 0PM to 11PM (12 - 23) + with the current date hour
+    expect(Math.max(...hours)).to.equal(23);
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/ClockPicker/ClockPicker.test.tsx:192]: I get a bit confused about what you are testing
```suggestion
    // Should be called with every hour post meridiem (from 12 to 23) since current date hour is 6PM
    expect(Math.min(...hours)).to.equal(12);
    expect(Math.max(...hours)).to.equal(23);
```

**Review by alexfauquette — APPROVED** [review]
