### PR TITLE
[docs] Fix column pinning for "Disable detail panel content scroll" section

### LINKED ISSUE #14850: [docs] Pinning functionality dose not work for columns in docs example
### Steps to reproduce

Link to live example: https://mui.com/x/react-data-grid/master-detail/#disable-detail-panel-content-scroll

Steps:
1. Click on any column menu
2. Click on Pin to left or Pin to right
3. Dose not work

Solution: Using pinnedColumns and onPinnedColumnsChange

Code:

  ```
const [pinnedColumns, setPinnedColumns] = useState({
    left: [GRID_DETAIL_PANEL_TOGGLE_FIELD],
  });

  const handlePinnedColumnsChange = useCallback((updatedPinnedColumns) => {
    setPinnedColumns(updatedPinnedColumns);
  }, []);

<DataGridPremium
{ ...props }
          pinnedColumns={pinnedColumns}
          onPinnedColumnsChange={handlePinnedColumnsChange}
 />
```

### Current behavior

With current behavior pinning dose not work  because pinnedColumns prop of data grid is staticky  GRID_DETAIL_PANEL_TOGGLE_FIELD

### Expected behavior

Works correctly all features of data grid

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: pin, pin to left, pin to right

### PR DESCRIPTION
**Pull request by kalyan90**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

This PR is created to address https://github.com/mui/mui-x/issues/14850

Unable to attach labels to the PR, can someone please help with attaching the `component: data grid` & `bug` & `docs` labels

Fixes #14850

### CODE REVIEW

File: docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx [hunk 1]
```diff
@@ -205,7 +204,6 @@ export default function FullWidthDetailPanel() {
       <DataGridPro
         columns={columns}
         rows={rows}
-        pinnedColumns={{ left: [GRID_DETAIL_PANEL_TOGGLE_FIELD] }}
```
Comment (arminmeh) [inline docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx:208]: This was used to keep toggle buttons on the left.
After it is removed, pinning a column to the left will result in the following
pinning

You need to use API to [control the pinned](https://mui.com/x/react-data-grid/column-pinning/#controlling-the-pinned-columns) columns and always keep the `GRID_DETAIL_PANEL_TOGGLE_FIELD` at the most left column

**Review by arminmeh — CHANGES_REQUESTED** [review]

File: docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx (hunk 1 above)
Comment (kalyan90) [reply docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx:208]: got that

Comment (kalyan90) [reply docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx:208]: @arminmeh updated the PR, please have a look when you get sometime. Thank you

**Review by arminmeh — APPROVED** [review]

**Comment by kalyan90** [comment]
@arminmeh I don't have merge access, can you please help merge this PR.

**Comment by arminmeh** [comment]
Thanks for the contribution @kalyan90

File: docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx (hunk 1 above)
Comment (cherniavskii) [reply docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx:208]: Alternatively, `initialState` could be used.
