### PR TITLE
[charts] Propagate the axis scale to the `valueFormatter`

### LINKED ISSUE #16350: [charts] `tickerNumber` doesn't work along with `valueFormatter`
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/test-muix-log-87lwwq

Steps:
Create a LineChart using log scale with property tickNumber on yAxis
```jsx
export default function LineChartDemo() {
  return (
    <LineChart
      width={500}
      height={300}
      series={[
        {
          data: pData,
          label: "pv",
          yAxisId: "leftAxisId",
        },
        { data: uData, label: "uv", yAxisId: "leftAxisId" },
      ]}
      xAxis={[{ scaleType: "point", data: xLabels }]}
      yAxis={[
        {
          id: "leftAxisId",
          scaleType: "log",
          tickNumber: 4,
        },
      ]}
    />
  );
}
```

Image

 Then add a valueFormatter function in yAxis
```jsx
export default function LineChartDemo() {
  return (
    <LineChart
      width={500}
      height={300}
      series={[
        {
          data: pData,
          label: "pv",
          yAxisId: "leftAxisId",
        },
        { data: uData, label: "uv", yAxisId: "leftAxisId" },
      ]}
      xAxis={[{ scaleType: "point", data: xLabels }]}
      yAxis={[
        {
          id: "leftAxisId",
          scaleType: "log",
          tickNumber: 4,
          valueFormatter: (v) => v //this will invalidate tickNumber
        },
      ]}
    />
  );
}
```

Image

### Current behavior

When the yAxis.valueFormatter property is added, the tickNumber no longer works.

### Expected behavior

The property tickNumber shouldn't be affected by valueFormatter function.

### Context

I am trying to change the format of tick values on yAxis, example: convert 300,000 to 300k. However, the default formatter from MUIX doesn't do that. Then I use the property `valueFormatter` function to fix that. However this causes another issue: The number of ticks increases and the yAxis has too many values that is hard to see. I tried to fix it using the property `tickNumber` but it doesn't work along with `valueFormatter`.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 14.6
  Binaries:
    Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
    pnpm: 9.11.0 - ~/.nvm/versions/node/v18.20.4/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.267
    Edge: Not Found
    Safari: 17.6
```
</details>

**Search keywords**: valueFormatter, log, tickNumber

**Order ID**: 98924

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #16350

I did not propagate the scale to the legend formatter, because in such case, it's not clear is it's the axis scale, or the color-scale to pass. And not that much usefull.

### CODE REVIEW

**Review by bernardobelchior — APPROVED** [review]

File: docs/data/charts/axis/FormatterD3.tsx [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+          dataKey: 'frequency',
+          tickNumber: 20,
+          valueFormatter: (f, context) => {
+            if (context.location === 'tick') {
+              const d3Text = (
+                context.scale as ScaleLogarithmic<number, number, never>
+              ).tickFormat(
+                30,
+                'e',
+              )(f);
```
Comment (JCQuintas) [inline docs/data/charts/axis/FormatterD3.tsx:43]: 😭 I tried to fix this typing, but there are too many generics 😆

Technically it should be possible to use the correct type based on the `scaleType: 'log'`. But due to how our generics are setup and the usage/initialization/direct-override of the types everywhere, typescript can't automatically deduce the types

**Review by JCQuintas — APPROVED** [review]
