### PR TITLE
[data grid]  fix onColumnWidthChange called before autosize affects column width

### LINKED ISSUE #12005: [data grid] onColumnWidthChange called before autosize affects column width
### Steps to reproduce

Link to live example: https://react-tud9tc.stackblitz.io

Steps:
1. open console to see logs
2. resize column by dragging => new column width is logged as expected
3. autosize column by double-clicking its edge => old column width is logged (wrong behavior)
4. autosize column again => correct column width after autosize is logged

### Current behavior

`onColumnWidthChange` gets called before autosizing is completed. It is instead called with the column width before autosizing. The second time autosizing calls `onColumnWidthChange` again, this time with the correct width.

### Expected behavior

`onColumnWidthChange` gets called with the new column width after autosizing is completed 

### Context

Saving column widths changed by the user in external storage, so it can be retrieved and applied if the same DataGrid is opened again by said user.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
  Used Chrome 121.0.6167.141 even though not listed

```
System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Chromium (121.0.2277.106)
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/icons-material: ^5.15.9 => 5.15.9
    @mui/material: ^5.15.9 => 5.15.9
    @mui/x-data-grid-pro: ^6.19.3 => 6.19.3
    @types/react: ^18.2.47 => 18.2.47
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.3.3 => 5.3.3
```
</details>

**Search keywords**: autosize

### PR DESCRIPTION
**Pull request by shaharyar-shamshi**
Fixes #12005

### CODE REVIEW

File: packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx [hunk 1]
```diff
@@ -378,6 +379,20 @@ export const useGridColumnResize = (
...
 
+    if (previousMouseClickEvent.current) {
+      const prevTimeStamp = previousMouseClickEvent.current.timeStamp;
+      const prevClientX = previousMouseClickEvent.current.clientX;
+      const prevClientY = previousMouseClickEvent.current.clientY;
+      if (
+        nativeEvent.timeStamp - prevTimeStamp < 300 &&
+        nativeEvent.clientX === prevClientX &&
+        prevClientY === nativeEvent.clientY
+      ) {
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:390]: Can you explain the logic behind this logic?

File: packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx [hunk 2]
```diff
@@ -610,6 +625,8 @@ export const useGridColumnResize = (
       const doc = ownerDocument(apiRef.current.rootElementRef!.current);
       doc.body.style.cursor = 'col-resize';
 
+      previousMouseClickEvent.current = event;
+
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:629]: I seem to recall something about react reusing its events, not sure if it still applies, but maybe we could store the native event directly?

Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:629]: I stored it just for the comparison when mouseUp event occur. 

And used ref to persist it between renders

File: packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx (hunk 1 above)
Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:390]: So overall logic is. 

Mouse double click is combination of 2 mouseup and mousedown event. 

But according to our previous logic whenever mousedown event used to occur we add the event listeners to listen mouseup event and resize according. 


This logic had a collision with the mouse double click so just to distinguish between mouse double click and mouse up/ mouse down event I compared the time interval between mouse down and mouseup event and their coordinate if it is same this directly means user wants to do double click. 

Hope I am able to explain this

File: packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx (hunk 2 above)
Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:629]: yes you are correct I just checked we need to store the nativeEvent instead of syntheticEvent

File: packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx (hunk 1 above)
Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx]: @romgrk if you can kindly check

**Comment by shaharyar-shamshi** [comment]
@romgrk Added the test case if you can review

File: packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx [hunk 3]
```diff
@@ -378,6 +379,29 @@ export const useGridColumnResize = (
...
+        nativeEvent.clientX === prevClientX &&
+        nativeEvent.clientY === prevClientY
+      ) {
+        // If the conditions are met, it indicates that the current event is part of a double-click,
+        // so we clear the previous mouse click event and return early to ignore it.
+        previousMouseClickEvent.current = undefined;
+        return;
+      }
+    }
+
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:404]: Is it possible to reduce a bit the comments here? No need to explain what the code is doing, comments should explain why code is needed, if there is a need to explain.

Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx]: @romgrk done

**Comment by romgrk** [comment]
I seem to be able to reproduce the original issue with this PR: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-f9skhw?file=%2Fsrc%2Fdemo.tsx%3A113%2C1

**Comment by romgrk** [comment]
Updated permissions.

**Comment by shaharyar-shamshi** [comment]
> Updated permissions.

 Basically React state updates are asynchronous but this element key is the DOM element but state update hasn't yet propagated to the DOM before being accessed that's the reason we are getting the old value in the element key but new value elsewhere like in key colDef and width.

**Comment by shaharyar-shamshi** [comment]
Only way that I can figure out as of now to access the DOM element after state change is done in this commit

https://github.com/mui/mui-x/pull/12140/commits/4bcd99b5acef095684de2630ba8228403e7579ea

But here I have to disable the eslint because I have to trigger the useEffect isAutosizingRef.current but Mutable values like 'isAutosizingRef.current' aren't valid dependencies because mutating them doesn't re-render the component .

@romgrk if you can suggest any better approach

File: packages/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx [hunk 4]
```diff
@@ -150,6 +150,26 @@ describe('<DataGridPro /> - Columns', () => {
       expect(onColumnWidthChange.args[0][0].width).to.equal(120);
     });
 
+    it('should call onColumnWidthChange with correct width after resizing and then clicking the seprator', async () => {
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx:153]: typo

Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx]: fixed

**Comment by romgrk** [comment]
Wouldn't it be better to dispatch a `columnWidthChange` event in the `autosizeColumns` function?

**Comment by shaharyar-shamshi** [comment]
> Wouldn't it be better to dispatch a `columnWidthChange` event in the `autosizeColumns` function?

Problem with this approach is when we disptach the `columnWidthChange` event  we have to access the DOM element as well but State update being asynchronous the width is still not propagated to DOM so we get outdated element.clientWidth

**Comment by romgrk** [comment]
But the widths are available at `gridColDef.width`. The widths are set first in the state, then in the DOM, not the other way around.

**Comment by shaharyar-shamshi** [comment]
> But the widths are available at `gridColDef.width`. The widths are set first in the state, then in the DOM, not the other way around.


```
apiRef.current.publishEvent('columnWidthChange', {
        element: apiRef.current.getColumnHeaderElement(colDefRef.current.field),
        colDef: { ...colDefRef.current, width },
        width,
      });
```

here you can see we have to publish three key element, colDef, width here key element is the DOM element which is doesn't get updated immediately that the main reason I have to use useEffect to access the updated element after the DOM updation.

In your example also (https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-f9skhw?file=%2Fsrc%2Fdemo.tsx%3A76%2C6) the element.clientWidth was actually wrong not  params.width.

**Comment by shaharyar-shamshi** [comment]
I hope this is clear or should I make one short video explaining this

File: packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx [hunk 5]
```diff
@@ -646,6 +667,21 @@ export const useGridColumnResize = (
...
+      const width: number = column.width as number;
+      apiRef.current.publishEvent('columnWidthChange', {
+        element: apiRef.current.getColumnHeaderElement(colDefRef.current.field),
+        colDef: { ...colDefRef.current, width },
+        width,
+      });
+    }
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [isAutosizingRef.current]);
+
```
[the remark this answers is not in the document]
Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:684]: then you will get outdated element with old clientWidth.

this problem will persist

https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-q953tj?file=%2Fsrc%2Fdemo.tsx%3A82%2C1

[the remark this answers is not in the document]
Comment (romgrk) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:684]: That's not an issue, it's ok to publish the event if we have the correct width, the element doesn't matter.

[the remark this answers is not in the document]
Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:684]: okk

[the remark this answers is not in the document]
Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx]: done

File: packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx [hunk 6]
```diff
@@ -702,6 +723,17 @@ export const useGridColumnResize = (
...
+        if (colDefRef.current) {
+          const columnsState = gridColumnsStateSelector(apiRef.current.state);
+          const column: GridStateColDef = columnsState.lookup[colDefRef.current.field];
+          const width: number = column.width as number;
+          apiRef.current.publishEvent('columnWidthChange', {
+            element: apiRef.current.getColumnHeaderElement(colDefRef.current.field),
+            colDef: { ...colDefRef.current, width },
+            width,
+          });
+        }
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:736]: This is incorrect. You have the column definitions in `newColumns`, you shouldn't use the one stored in that ref. You should fire the event for each column in `newColumns` for which the width has changed.

Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:736]: newColumns is an array should I trigger this event for only one column for which the autoResize is done or each of the element of the array.

```
if (colDefRef.current) {
          const updatedColumn: GridStateColDef | undefined = newColumns.find((newColumn) => {
            return newColumn.field === colDefRef.current?.field;
          });

          if (updatedColumn) {
            const width: number = updatedColumn.width as number;
            apiRef.current.publishEvent('columnWidthChange', {
              element: apiRef.current.getColumnHeaderElement(colDefRef.current.field),
              colDef: updatedColumn,
              width,
            });
          }
        }
```

Comment (romgrk) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:736]: The `autosizeColumns` can operate on multiple columns, not just one. The `if` guard here does not apply, `colDefRef` belongs to the resize logic. We need to trigger the event for each column that changed width.

Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx]: Done

File: packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx [hunk 7]
```diff
@@ -702,6 +723,15 @@ export const useGridColumnResize = (
...
         apiRef.current.updateColumns(newColumns);
+
+        newColumns.forEach((newColumn) => {
+          const width: number = newColumn.width as number;
+          apiRef.current.publishEvent('columnWidthChange', {
+            element: apiRef.current.getColumnHeaderElement(newColumn.field),
+            colDef: newColumn,
+            width,
+          });
+        });
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:734]: This will trigger for all columns regardless of if they have changed. You have the original columns in `columns`.

You can avoid typings like this, the inference knows it's a number:
```ts
const width: number = newColumn.width as number;
```

Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:734]: We are doing something wrong this implementation is correct.

let me Explain in detail

There are two possibility of calling autosizeColumns function

1.  through doubleClick event Listener https://github.com/mui/mui-x/blob/next/packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx#L743  from here handleColumnSeparatorDoubleClick calls the autosizeColumns and over here it pass the exact column which is being resized 
2.  At the time of mounting when user pass autoResizeOnMount prop https://github.com/mui/mui-x/blob/next/packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx#L716

here each of the column is being resized on mounting

In our case to solve this bug we only need to concentrate on case 1 when the autosizeColumns is called on double click.

So on double click event from https://github.com/mui/mui-x/blob/next/packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx#L661

we get only one column that needs to be resized and we need not check on all the columns.

Now in case 2 when autOResizeOnMount is called in that case all the columns should be resized and we need to decide whether to publish event or not.

So from both the case we can figure it out that either all of the column will be resized or only 1 will be resized.


if we want to disable the event publish on all column resize (case 2) we just need to add one condition


```
if (userOptions?.columns) {
          newColumns.forEach((newColumn) => {
            const width = newColumn.width;
            apiRef.current.publishEvent('columnWidthChange', {
              element: apiRef.current.getColumnHeaderElement(newColumn.field),
              colDef: newColumn,
              width,
            });
          });
        }

```

Comment (romgrk) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:734]: There is no need for an `if` guard, just check the array and dispatch one event for each column that actually changed. Compare `newColumn.width !== columns[index].width` in the `.forEach` loop to figure out which ones changed.

The autosize function is part of the public API and can be called programatically with any number of columns.

Comment (shaharyar-shamshi) [reply packages/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx]: Done

**Review by romgrk — APPROVED** [review]
