### PR TITLE
[DataGrid] Use `baseTooltip` slot for column header sort icon

### LINKED ISSUE #11327: [data grid] ColumnHeader sorting icon has old Tooltip
### Steps to reproduce

[DataGrid codesandbox template](https://codesandbox.io/s/github/mui/mui-x/tree/master/templates/x-data-grid?file=/src/demo.tsx)

### Current behavior

the menu icon has a newer design of the tooltip. The sort icon has an old one with hard edges and black color

I think there is the <rootProps.slots.baseTooltip> missing in /components/columnHeaders/GridColumnHeaderSortIcon.tsx

### Expected behavior

All icons should have the same tooltip

### Context

_No response_

### Your environment

_No response_

**Search keywords**: datagrid header icons

### PR DESCRIPTION
**Pull request by kzhgit**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

## Description

This PR updates the column header sort icon to use the `baseTooltip` slot, ensuring consistency with other header icons (filter and menu icons) and enabling tooltip customization.

### Problem
Previously, the sort icon used only the native browser tooltip (via the `title` attribute), while other header icons (filter, menu) used the `baseTooltip` slot. This inconsistency prevented users from customizing the sort icon tooltip appearance.

### Solution
- Wrapped [GridColumnSortButton](cci:1://file:///Users/maejimakazuho/Desktop/OSS/mui-x/packages/x-data-grid/src/components/GridColumnSortButton.tsx:68:0-108:1) with `rootProps.slots.baseTooltip` in [GridColumnHeaderSortIcon](cci:1://file:///Users/maejimakazuho/Desktop/OSS/mui-x/packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderSortIcon.tsx:9:0-24:1)
- Passed `title={undefined}` to [GridColumnSortButton](cci:1://file:///Users/maejimakazuho/Desktop/OSS/mui-x/packages/x-data-grid/src/components/GridColumnSortButton.tsx:68:0-108:1) to suppress the native tooltip and prevent double tooltips
- Added `enterDelay={1000}` to match the behavior of other header icons

### Changes
- Modified [packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderSortIcon.tsx](cci:7://file:///Users/maejimakazuho/Desktop/OSS/mui-x/packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderSortIcon.tsx:0:0-0:0)
- Added regression test in [packages/x-data-grid/src/tests/columnHeaders.DataGrid.test.tsx](cci:7://file:///Users/maejimakazuho/Desktop/OSS/mui-x/packages/x-data-grid/src/tests/columnHeaders.DataGrid.test.tsx:0:0-0:0)

## Related Issues
Fixes #11327  
Supersedes #11348 and #11349

## Testing
Added a test case that verifies:
- The sort icon is wrapped by the `baseTooltip` component
- The native `title` attribute is removed from the button to prevent double tooltips

```bash
npx vitest run packages/x-data-grid/src/tests/columnHeaders.DataGrid.test.tsx
```
→ All tests pass ✅

### CODE REVIEW

File: packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderSortIcon.tsx [hunk 1]
```diff
@@ -2,14 +2,25 @@ import * as React from 'react';
...
-    <GridIconButtonContainer>
-      <GridColumnSortButton {...props} tabIndex={-1} />
-    </GridIconButtonContainer>
+    <rootProps.slots.baseTooltip
+      title={apiRef.current.getLocaleText('columnHeaderSortIconLabel')}
+      enterDelay={1000}
+      {...rootProps.slotProps?.baseTooltip}
+    >
+      <GridIconButtonContainer>
+        <GridColumnSortButton title={undefined} {...props} tabIndex={-1} />
```
Comment (arminmeh) [inline packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderSortIcon.tsx]: Why not add it directly to the `GridColumnSortButton`?
It would cover the pivoting sort button as well
https://deploy-preview-20460--material-ui-x.netlify.app/x/react-data-grid/pivoting/#controlled-pivoting

Comment (kzhgit) [reply packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderSortIcon.tsx]: @arminmeh 
Thanks for the suggestion! You're right.

I've updated the implementation to add `baseTooltip` directly to GridColumnSortButton instead of GridColumnHeaderSortIcon.
