### PR TITLE
[tree view] Cleanup `onKeyDown` handler

### LINKED ISSUE #10397: [TreeView] Refactor event handling to avoid stopping propagation
Created from https://github.com/mui/mui-x/pull/10123#discussion_r1328759654

Investigate the possibility of not using `event.stopPropagation`, but relying on `preventDefault` and `isDefaultPrevented` or a similar mechanism to control the event flow.

### LINKED ISSUE #10577: TreeView captures CTRL + ENTER key
### Steps to reproduce

The demo's of the component can be used.

### Current behavior

Pressing ENTER selects/deselects an item, but so does CTRL+ENTER.

### Expected behavior

The component to ignore CTRL+ENTER key events.

### Context

This is also a problem in single select, which is my case,.
The user can achieve selection with the SPACEBAR - isn't that enough?
Selection with ENTER is maybe ok, but CTRL+ENTER should not be captured especially not in single select mode. 

I think the issue is in this [codeblock](https://github.com/mui/mui-x/blob/fc7afacff3e8dad390072eb9e73e4aed48fb7bc7/packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts#L179C22-L179C22).

### Your environment

N/A - the component demo's demonstrate the problem

**Search keywords**: ctrl enter

### PR DESCRIPTION
**Pull request by flaviendelangle**
Closes #10577
Closes #10397

- Improve the overall readability of the function 
- Support `defaultMuiPrevented`
- Do not stop the propagation of the event
- Only prevent the default behavior when we really use the event for some custom behavior

### CODE REVIEW

File: packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts [hunk 1]
```diff
@@ -137,159 +102,220 @@ export const useTreeViewKeyboardNavigation: TreeViewPlugin<
...
+  // ARIA specification: https://www.w3.org/WAI/ARIA/apg/patterns/treeview/#keyboardinteraction
   const createHandleKeyDown =
-    (otherHandlers: EventHandlers) => (event: React.KeyboardEvent<HTMLUListElement>) => {
+    (otherHandlers: EventHandlers) =>
+    (event: React.KeyboardEvent<HTMLUListElement> & MuiCancellableEvent) => {
       otherHandlers.onKeyDown?.(event);
 
-      let flag = false;
-      const key = event.key;
+      if (event.defaultMuiPrevented) {
```
Comment (LukasTy) [inline packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:125]: Do you think that this feature will be transparent enough for the users? 🤔 
Have you considered checking `event.defaultPrevented` instead?
It seems that in cases, where this behavior is supported, we do explicitly [document it](https://mui.com/material-ui/react-autocomplete/#events). 🤔 
If we go with `defaultMuiPrevented`, do we agree that it should be explicitly documented?

**Review by LukasTy — COMMENTED** [review]
Nice improvement. 👍 
LGTM, but not approving yet before discussing the `defaultMuiPrevented` topic.

File: packages/x-tree-view/src/TreeItem/TreeItem.test.tsx [hunk 2]
```diff
@@ -1141,6 +1141,36 @@ describe('<TreeItem />', () => {
...
+              <TreeItem nodeId="one" label="one" data-testid="one" />
+            </SimpleTreeView>,
+          );
+
+          act(() => {
+            getByRole('tree').focus();
+          });
+          fireEvent.keyDown(getByRole('tree'), { key: 'Enter' });
+
+          expect(getByTestId('one')).to.have.attribute('aria-selected');
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-tree-view/src/TreeItem/TreeItem.test.tsx:1157]: I kept the DX used on the other tests, but I did not think about the alternative tbh

File: packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts (hunk 1 above)
Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:125]: `defaultMuiPrevented` is a pattern that a several recent core components uses and the grid as well.
I think the reasoning behind it is to be able to distinguish browser behavior and MUI behavior. To let people say "hey I want the browser behavior, but not the MUI one".

With that being said, I can't find any doc about it except in this tech file: https://github.com/mui/material-ui/blob/master/packages/mui-base/CONTRIBUTING.md
Once the pattern is widely used in the MUI codebase, it should probably have a dedicated doc section somewhere.
And the Tree View `onKeyDown` event is probably common enough to justify a doc examples as well.

Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:125]: Maybe @michaldudak has more context here

Comment (michaldudak) [reply packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:125]: AFAIK Material UI uses this pattern in several places, and I adopted it in Base UI as well (it was necessary to have an option to prevent just the library code from executing).
I agree about the docs lacking in this area. I'm making a note to update them.

File: packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts [hunk 3]
```diff
@@ -137,159 +102,220 @@ export const useTreeViewKeyboardNavigation: TreeViewPlugin<
...
+          event.preventDefault();
           break;
-        case 'End':
+        }
+
+        // Focuses the last node in the tree
+        case key === 'End': {
+          instance.focusNode(event, getLastNode(instance));
+
+          // Multi select behavior when pressing Ctrl + Shirt + End
```
Comment (noraleonte) [inline packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:276]:
```suggestion
          // Multi select behavior when pressing Ctrl + Shift + End
```

**Review by noraleonte — APPROVED** [review]
Nice improvement! 🎉 The changes make sense and overall looks a lot cleaner 👍

File: packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts (hunk 1 above)
Comment (LukasTy) [reply packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:125]: @flaviendelangle If you think that not providing an explicit documentation section about this possibility in the current state of all products documentation is fine, I'm not blocking the PR merging, but IMHO, such a section wouldn't hurt. 😉

**Review by LukasTy — APPROVED** [review]

File: packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts (hunk 1 above)
Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:125]: I was wondering if this shouldn't be addressed at the API page level.
To have the `onKeyDown` prop listed [here](https://next.mui.com/x/api/tree-view/rich-tree-view/) with a description that sends to a MUI-wide page explaining how to use `defaultMuiPrevented`.

If we want to do it on the product pages, we could create a new "Interaction" pages on both `SimpleTreeView` and `RichTreeView` and add a section "Customize the keyboard behaviors".
Or we wait for the "Accessibility" page and we put it there since it will be the page that explains the keyboard behavior in depth.

What do you think?

Comment (LukasTy) [reply packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:125]: Good points. 👍 
The first suggestion sounds the best, but AFAIK, it's more or less a future solution.
I'm not against just waiting a bit until there is a common page that we can link to. 🤔 

Adding this info to the `Accessibility` page is also an option, but I'd argue that it is not the best place for such content. 🤔 
We could link to the above-mentioned page there. 💡

I'm not the biggest fan of the `Interaction` page suggestion if it would only include this information, but IMHO it's a better alternative than the `Accessibility` page. 🤔

Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:125]: We could re-purpose the `Accessibility` page to be more a `Keyboard usage` page (this name is terrible though).

Tbh I did not add this doc section because I did not find a good place to put it :laughing:

Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/plugins/useTreeViewKeyboardNavigation/useTreeViewKeyboardNavigation.ts:125]: I'll merge without a doc, we can discuss later what we want to do :+1:

**Comment by ilbrando** [comment]
It appears to me that the prop `defaultMuiPrevented` is not part of the typings for `onKeyDown`. Am I right about this, or am I missing something? Intellisence gives me this: `DOMAttributes<HTMLUListElement>.onKeyDown?: KeyboardEventHandler<HTMLUListElement> | undefined`

**Comment by flaviendelangle** [comment]
Our key down handler is called by the item component since #12226)
I will update the typing of `TreeItem2Props` and `TreeItemProps` to respect the event handlers that support `defaultMuiPrevented`.
I will comment also #9962 with the updated example because the current one no longer works.
