### PR TITLE
[DataGrid] Stop calling `onRowClick` when clicking in cells with interactive elements

### LINKED ISSUE #3805: [DataGrid] onRowClick is also triggered when selecting a checkbox
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After updating to 5.4.0 I noticed that selecting a row checkbox also triggers the onRowClick callback.
Previously that wasn't the case and I couldn't find a workaround yet to avoid that.

In my situation that new behavior breaks the logic of our product because on a onRowClick call I redirect the user to a detail page of the grid entry and on checkbox selection the user can perform actions on one or several selected entries. For now I did revert back to 5.3.0 to fix it.

### Expected behavior 🤔

On checkbox selection the onRowClick callback shouldn't be triggered like it was before 5.4.0.

### Steps to reproduce 🕹

_No response_

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

35878

### LINKED ISSUE #3897: [DataGridPro]: Clicking inside checkbox for rowSelection fires onRowClick
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In Data Grid Pro >v5.3, a click on selection checkbox (which appears with `checkboxSelection`) now also fires `onRowClick`

This seems like a regression. Couldn't find anything in docs or changelog around this change

### Expected behavior 🤔

In Data Grid Pro <v5.3 with option `checkboxSelection`, clicking on checkbox, would only select the row, but not fire the `onRowClick`

I don't expect `onRowClick` to fire on `rowSelection` (using the dedicated checkbox)

### Steps to reproduce 🕹

Example for v5.3 [expected behaviour]: https://codesandbox.io/s/disableclickselectiongrid-material-demo-forked-4fj2j?file=/demo.js

Click on checkbox and observe console.log (nothing should happen)

Example for v5.5 [latest]: https://codesandbox.io/s/disableclickselectiongrid-material-demo-forked-3w6jo?file=/package.json
Click on checkbox and see the onRowClick executing in console

### Context 🔦

We have a data-grid-pro license and this introduced a bug into site.
We have to pin the version to 5.3.0 for now until this is fixed.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>
This bug is reproducible in Chrome/Firefox Windows/Mac OS X

### Order ID 💳 (optional)

#31725

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #3897
Fixes #3805

See https://github.com/mui/mui-x/issues/3897#issuecomment-1034096713

Two users complained (#3897 and #3805) that `onRowClick` was being called when clicking any cell. Although they can use `onCellClick` and filter in their side this is not good. This PR contains a fix which doesn't call `onRowClick` when clicking in special columns (checkbox, detail panel toggle and action buttons). The `rowClick` event was only being used for selection so I changed to listen to `cellClick`. `cellClick` will be always fired.

### CODE REVIEW

File: packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts [hunk 1]
```diff
@@ -329,26 +331,26 @@ export const useGridSelection = (
...
-      if (field === GRID_CHECKBOX_SELECTION_COL_DEF.field) {
+      if (params.field === GRID_CHECKBOX_SELECTION_COL_DEF.field) {
         // click on checkbox should not trigger row selection
         return;
       }
 
-      if (field) {
-        const column = apiRef.current.getColumn(field);
-        if (column.type === 'actions') {
+      if (params.field === GRID_DETAIL_PANEL_TOGGLE_FIELD) {
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts:345]: Fixes #3945

**Comment by alexfauquette** [comment]
I'm not sure preventing the event `onRowClick` in special cases is a good approach. If you `onCellClick` is dispatch, I would expect to have `onRowClick` too. Your proposal is like adding a `stopPropagation()` in the `GridEvents`.

I would be in favor of adding a helper, or passing the information directly in the event params for users to know if the click occurred on one of the following cases

- GRID_CHECKBOX_CELL
- GRID_TOGGLE_DETAIL_PANEL_CELL
- GRID_TOGGLE_TREE_CELL
- GRID_CELL_IN_EDIT_MODE
- GRID_ACTION_CELL

To adapt their code, developers could do something like this, assuming we provide `getActiveTarget`
```js
handleRowClick = (params, event) => {
	 // returns on of the above constant is the target makes a action on the grid.
	 // If not, return null
	const activeTarget = getActiveTarget(params, event);
	if(activeTarget) {
		return
	}
	...
}
```

The question is: Do we consider that removing a `stopPropagation` is an improvement or a regression

**Comment by m4theushw** [comment]
@alexfauquette AG Grid doesn't call `onRowClick` when clicking in the checkbox to select the row. Users seem to expect the same. Also, it's a regression because before we had `event.stopPropagation()` which blocked this event. Passing the field makes this callback useless, because `onCellClick` already has the field.

> The question is: Do we consider that removing a stopPropagation is an improvement or a regression

It's a improvement for the focus but which caused a regression in another part.

File: packages/grid/_modules_/grid/components/GridRow.tsx [hunk 2]
```diff
@@ -133,6 +142,41 @@ function GridRow(props: React.HTMLAttributes<HTMLDivElement> & GridRowProps) {
...
+
+        // User opened a detail panel
+        if (field === GRID_DETAIL_PANEL_TOGGLE_FIELD) {
+          return;
+        }
+
+        // User is editing a cell
+        if (apiRef.current.getCellMode(rowId, field) === GridCellModes.Edit) {
+          return;
+        }
```
Comment (alexfauquette) [inline packages/grid/_modules_/grid/components/GridRow.tsx:166]: Except if some users complained about it, I'm wondering if is not better to wait for v6 for this case. In v6 we could change the behavior, such that a row is not selected when clicking on a cell in edit mode.

This would allow keeping row selection sync with `handleRowClick`

Comment (m4theushw) [reply packages/grid/_modules_/grid/components/GridRow.tsx]: > In v6 we could change the behavior, such that a row is not selected when clicking on a cell in edit mode.

To be clear, this PR changed to listen to `cellClick` to select rows. To prevent selection on click we have the `disableSelectionOnClick` prop which is enabled in most demos that use cell editing.

The change you highlighted I did it only to keep in sync with the idea that we don't fire `rowClick` when clicking on cells with interactive elements. In reality, binding something to the row click (like in #3805 where it opens a detail panel) + cell editing might have accessibility implications because the click outside the current cell (which can be in another cell) is used to cancel the editing.

File: packages/grid/x-data-grid/src/components/GridRow.tsx [hunk 3]
```diff
@@ -133,6 +141,41 @@ function GridRow(props: React.HTMLAttributes<HTMLDivElement> & GridRowProps) {
...
+      // Check if the field is available because the cell that fills the empty
+      // space of the row has no field.
+      if (field) {
+        // User clicked in the checkbox added by checkboxSelection
+        if (field === GRID_CHECKBOX_SELECTION_COL_DEF.field) {
+          return;
+        }
+
+        // User opened a detail panel
+        if (field === '__detail_panel_toggle__') {
```
Comment (alexfauquette) [inline packages/grid/x-data-grid/src/components/GridRow.tsx:158]: Not for this PR but should we have a file with all the const in `data-grid` folder, including the pro const?

**Review by alexfauquette — APPROVED** [review]
