### PR TITLE
[charts] Fix highlight regression

### LINKED ISSUE #19433: [charts] Series highlight demo not working properly
### Steps to reproduce

Steps:

1. Open this link to live example: https://mui.com/x/react-charts/highlighting/#highlighting-series
2. Currently, only the scatter chart responds to the drop-down options, while the other three charts don't react.

On the same page, https://mui.com/x/react-charts/highlighting/#synchronizing-highlights also seem to not work.

### Expected behavior

These demos work in v7: https://v7.mui.com/x/react-charts/highlighting/

**Search keywords**: highlight series

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #19433

### CODE REVIEW

File: packages/x-charts/src/hooks/useInteractionItemProps.ts [hunk 1]
```diff
@@ -27,18 +28,22 @@ export const useInteractionItemProps = (
...
+  });
 
-  const onPointerLeave = React.useCallback(() => {
+  const onPointerLeave = useEventCallback(() => {
     interactionActive.current = false;
-    instance.removeItemInteraction(data);
+    instance.removeItemInteraction(dataRef.current);
     instance.clearHighlight();
-  }, [instance, data]);
+  });
```
Comment (bernardobelchior) [inline packages/x-charts/src/hooks/useInteractionItemProps.ts]: Isn't this enough? 



```suggestion
  const onPointerEnter = useEventCallback(() => {
interactionActive.current = true;
    instance.setItemInteraction(data);
    instance.setHighlight(data);
  });

  const onPointerLeave = useEventCallback(() => {
interactionActive.current = false;
    instance.removeItemInteraction(data);
instance.clearHighlight();
  });
```


`useEventCallback` (implementation [here](https://github.com/mui/material-ui/blob/ef895a4362ea62a375f4f68705a5d5304e048c61/packages/mui-utils/src/useEventCallback/useEventCallback.ts#L15)) updates the function on every render, so I don't think we need to store `data` in a ref
