### PR TITLE
[charts] Fix line interaction with `area` and `conectNulls`

### LINKED ISSUE #22185: [charts] Refine gitItemAtPosition edge case for the line chart
> wouldnt it be clearer without the areas? 🤔

It would not be the same behavior.

The fact that the blue line has some priority over the red area is nice

image

But we have issue. The yellow area should not overflow on the red one.

image

I modified a bit the line values to make those overlap easier to spot

_Originally posted by @alexfauquette in https://github.com/mui/mui-x/issues/22181#issuecomment-4312326303_

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #22185

### CODE REVIEW

File: packages/x-charts/src/LineChart/seriesConfig/getItemAtPosition.ts [hunk 1]
```diff
@@ -198,6 +199,9 @@ export default function getItemAtPosition(
     const { left, right } = bracket;
     const { visibleStackedData, data, connectNulls, curve } = seriesItem;
 
+    if (!connectNulls && (data[left] == null || data[right] == null)) {
+      continue;
+    }
```
Comment (alexfauquette) [inline packages/x-charts/src/LineChart/seriesConfig/getItemAtPosition.ts:204]: The closest series was computed as if `connectNulls` was always set to `true`

Now if `!connectNulls` the series is not considered if there is a nullish point in the segment

File: packages/x-charts/src/LineChart/seriesConfig/getItemAtPosition.ts [hunk 2]
```diff
@@ -259,7 +263,11 @@ export default function getItemAtPosition(
   }
 
   // Step 2: If the closest line is within the proximity threshold, pick it.
-  if (closestItem && closestDistance <= LINE_PROXIMITY_THRESHOLD) {
+  if (
+    closestItem &&
+    closestDistance <= LINE_PROXIMITY_THRESHOLD &&
+    !series.series[closestItem.seriesId].area
+  ) {
```
Comment (alexfauquette) [inline packages/x-charts/src/LineChart/seriesConfig/getItemAtPosition.ts:270]: On this argo screenshot you can see that the yellow area overflow on top of the red one.

It's because we are inside the line proximity threshold.

So for series with `ærea: true` I remove the threshold. to interact with it it must be either:
- exactly on the area
- the closest series

Image

**Review by JCQuintas — APPROVED** [review]

File: packages/x-charts/src/LineChart/seriesConfig/getItemAtPosition.ts [hunk 3]
```diff
@@ -298,14 +306,7 @@ export default function getItemAtPosition(
...
-      const leftIsNull = data[left] == null;
-      const rightIsNull = data[right] == null;
-
-      if (leftIsNull && rightIsNull) {
-        continue;
-      }
-
-      if ((leftIsNull || rightIsNull) && !connectNulls) {
+      if ((data[left] == null || data[right] == null) && !connectNulls) {
         continue;
```
Comment (alexfauquette) [inline packages/x-charts/src/LineChart/seriesConfig/getItemAtPosition.ts:310]: If left and right are both null and `connectNulls===true` their is some connection so we can not skip computation.

For example with data set to `[10, null, null, 11]` if we connect nulls, line is plot between indexes 1 and 2

File: packages/x-charts/src/LineChart/seriesConfig/getItemAtPosition.ts [hunk 4]
```diff
@@ -320,25 +321,6 @@ export default function getItemAtPosition(
 
       const getPixelX = (idx: number) => xPosition(xData[idx]);
 
-      if (left === right) {
```
Comment (alexfauquette) [inline packages/x-charts/src/LineChart/seriesConfig/getItemAtPosition.ts:323]: This was an edge case I made impossible in the previous PR.
