### PR TITLE
[DataGrid] Allow to filter non-filterable columns programmatically

### LINKED ISSUE #11527: [data grid] Filtering on non filterable columns yield weird behavior
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/morning-shadow-mskhc8?file=%2Fsrc%2FDemo.tsx%3A61%2C13

Steps:
1. Open filter panel
2. Observe the column shown in filter panel is `ID` while the `filterModel` has `firstName`
3. Try to close the filter panel by clearing the cross

### Current behavior

1. The column shown in filter panel is `ID` while the `filterModel` has `firstName`
2. The filter panel is not closable by cross icon, since clearing is not happening

### Expected behavior

In the light of #10552, the `filterModel` should be respected for unfilterable columns, the UI interactions on such filters should be disabled.

### Context

Discovered while working on https://github.com/mui/mui-x/issues/10552

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: filtering

### PR DESCRIPTION
**Pull request by MBilalShafi**
- Handles `colDef.filterable` part of #10552
- Fixes #11527 

**ToDos:**
- [x] Update tests
- [x] Update docs (added a [section](https://deploy-preview-11538--material-ui-x.netlify.app/x/react-data-grid/filtering/#read-only-filters) specific to filter, another generic covering the broader concept [covered](https://github.com/mui/mui-x/pull/11512/files#diff-b0bc26aa7c4578943f90e1bbb46dcc7bbb257bdb11d434ff3ad34e257aacebf9R63-R93) in the other PR, could possibly be added to the upcoming FAQ page too)
- [x] Update migration guide (this generic [one](https://github.com/mui/mui-x/pull/11512/files#diff-32b8ccbf3738b9aa1a6038454e185a6aea9b2c175ab3ab7f1eb2302d8b625ff2R101-R104) added in the other PR should serve the broader concept)

Doc: https://deploy-preview-11538--material-ui-x.netlify.app/x/react-data-grid/filtering/#read-only-filters
Example usage: https://codesandbox.io/p/sandbox/bold-platform-9jg53c?file=%2Fsrc%2FDemo.tsx%3A41%2C9

### Breaking changes

- Non-filterable columns could now be filtered programmatically by controlling or initialing `filterModel`, or by updating the `filterModel` by API method `apiRef.current.setFilterModel`.

### CODE REVIEW

File: docs/data/data-grid/filtering/ReadOnlyFilters.js
Comment (MBilalShafi) [inline docs/data/data-grid/filtering/ReadOnlyFilters.js:1]: Since the MIT Grid allows one filter at a max, I have allowed clearing the read-only filter by adding a filter on another column. Users can prevent this by controlling the filter and not updating the `filterModel` on `filterModelChange`.

File: packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx [hunk 1]
```diff
@@ -232,6 +238,7 @@ const GridFilterForm = React.forwardRef<HTMLDivElement, GridFilterFormProps>(
     const classes = useUtilityClasses(rootProps);
     const valueRef = React.useRef<any>(null);
     const filterSelectorRef = React.useRef<HTMLInputElement>(null);
+    const multiFilterOperator = filterModel.logicOperator ?? GridLogicOperator.And;
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx:241]: Solves https://codesandbox.io/p/sandbox/zealous-shamir-jktxkz?file=%2Fsrc%2FDemo.tsx%3A20%2C11 i.e `filterModel.logicOperator` is `undefined` on initializing multiple filters. This issue is on next and not on master. Let me know if there's a better fix you are aware of.

File: docs/data/data-grid/filtering/index.md [hunk 2]
```diff
@@ -103,6 +103,26 @@ You can use the `onFilterModelChange` prop to listen to changes to the filters a
 
 {{"demo": "ControlledFilters.js", "bg": "inline", "defaultCodeOpen": false}}
 
+### Read-only filters
+
+You can initialize the `filterModel`, set the `filterModel` prop, or use `apiRef.current.setFilterModel` to define the filters for columns with `colDef.filterable` set to `false`. These filters will be applied but the user won't be able to change them.
```
Comment (MBilalShafi) [inline docs/data/data-grid/filtering/index.md:108]: A small possible positive side effect would be [this kind of filtering](https://github.com/mui/mui-x/issues/8357) will now be [possible](https://codesandbox.io/p/sandbox/stoic-brattain-dpyvjz?file=%2Fsrc%2FDemo.tsx%3A129%2C56) in read-only mode without [tweaking](https://github.com/mui/mui-x/issues/8357#issuecomment-1483231110) `groupingColDef.`

File: packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterPanel.tsx [hunk 3]
```diff
@@ -165,32 +165,47 @@ const GridFilterPanel = React.forwardRef<HTMLDivElement, GridFilterPanelProps>(
 
     const hasMultipleFilters = items.length > 1;
 
-    const addNewFilter = () => {
+    const { readOnlyFilters, validFilters } = React.useMemo(() => {
+      const filterableFields = new Set(filterableColumns.map((col) => col.field));
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterPanel.tsx:169]: TODO: Use `filteredColumnsLookup` instead

File: docs/data/data-grid/filtering/index.md [hunk 4]
```diff
@@ -127,6 +127,26 @@ In the example below, the _rating_ column can not be filtered.
 
 {{"demo": "DisableFilteringGridSomeColumns.js", "bg": "inline", "defaultCodeOpen": false}}
 
+### Filter non-filterable columns programmatically
```
Comment (MBilalShafi) [inline docs/data/data-grid/filtering/index.md:130]: Update in context of https://github.com/mui/mui-x/pull/11512#discussion_r1444724567
Sidenote: I've kept internal variable naming to have the keyword `readOnly` for better understanding. The alternative `disabled` may also convey `not visible at all`, so to me `readOnly` is the more appropriate term.
Let me know if there's a disagreement.

**Review by cherniavskii — APPROVED** [review]

File: packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx (hunk 1 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx:241]: Shouldn't it be `Or` by default? https://github.com/mui/mui-x/blob/243ae70b89855bcaf58d665c4818758e1bea09a3/packages/grid/x-data-grid/src/models/gridFilterModel.ts#L16-L18

File: docs/pages/x/api/date-pickers/desktop-date-range-picker.json [hunk 5]
```diff
@@ -205,30 +205,6 @@
       "default": "ArrowDropDown",
       "class": null
     },
-    {
```
[the remark this answers is not in the document]
Comment (alexfauquette) [reply docs/pages/x/api/date-pickers/desktop-date-range-picker.json:208]: @michaldudak Should we sort them in a specific order?

File: packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx (hunk 1 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx:241]: Interesting point. @cherniavskii 
I feel this `@default GridLogicOperator.Or` statement is incorrect. Because if you check the current behavior on https://mui.com/x/react-data-grid/filtering/multi-filters/ it's `GridLogicOperator.And` (try adding 2-3 filters without touching logic operator)
Any suggestions if I should update the default value on this prop or the default behavior on the attached demo is incorrect?

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx:241]: Indeed, here we set the default logic operator:

https://github.com/mui/mui-x/blob/69f1ca43a31f0dec0f0702a6959c7b3106dc9941/packages/grid/x-data-grid/src/hooks/features/filter/gridFilterState.ts#L8-L10

Feel free to update the jsdoc to reflect the actual default value 👍🏻

File: docs/pages/x/api/date-pickers/desktop-date-range-picker.json (hunk 5 above)
[the remark this answers is not in the document]
Comment (michaldudak) [reply docs/pages/x/api/date-pickers/desktop-date-range-picker.json]: IMO slots order should reflect the source. Usually we want to have the root slot at the top. Or we could sort them alphabetically but place 'root' at the top.

[the remark this answers is not in the document]
Comment (alexfauquette) [reply docs/pages/x/api/date-pickers/desktop-date-range-picker.json]: By the way it can be a configuration parameter: `sortingStrategy: { porps, classes, slots }` with either the sort callback or null if no sorting

File: packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx (hunk 1 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/panel/filterPanel/GridFilterForm.tsx:241]: @WillCDev Which prop are you referring to?
