### PR TITLE
[DataGridPro] Fix detail panel not taking full width

### LINKED ISSUE #4607: [data grid] Detail panel doesn't take full width
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Dear MUI Team, 

The latest version 5.9.0 seemed to have introduced a regression issue to the Master Panel Content Detail feature. On the version 5.8.0 and below, when I had the grid with multiple columns and horizontal virtual scroller, the content inside the detail panel would occupy 100% of that virtual scroller (desired behavior), but instead it occupies only initially rendered width of the columns that are visible in the scroller. 

### Expected behavior 🤔

I want the inner detail panel content to be as wide as the virtual scrolller. I render a data grid with the same columns as the main grid, and want the columns to align accurately, and not get cut-off.

Or as an alternative I would like to pick whether I want to fill the entire width of the virtual scroller, or just the visible viewport.

### Steps to reproduce 🕹

Steps:
Using sandboxes from documentation:
1. https://codesandbox.io/s/kxcgmm?file=/demo.js 
2. Make sure that the screen is narrow enough for column horizontal scroll to appear. 
3. Verify that the master detail content expands all the way to the width of all virtual columns.
4. In v5.9.0 https://codesandbox.io/s/basicdetailpanels-material-demo-forked-lssefy?file=/demo.js
5. step 2. 
6. Notice how the content inside panel shrinks to the original width of the initially visible columns in the horizontal scroller.

### Context 🔦

I noticed the change when migrating over our package from 5.5.1 to 5.9.0 to support the additional initial state orderedFields and dimensions states.

The content inside one of the grids that was using master detail panel shrunk without making any css change

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.

 System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 100.0.4896.127
    Edge: Spartan (44.19041.906.0), Chromium (98.0.1108.62)
  npmPackages:
    @emotion/react: ^11.4.1 => 11.5.0
    @emotion/styled: ^11.3.0 => 11.3.0
    @mui/base:  5.0.0-alpha.67
    @mui/core:  5.0.0-alpha.51
    @mui/icons-material: ^5.0.1 => 5.4.2
    @mui/lab: ^5.0.0-alpha.48 => 5.0.0-alpha.51
    @mui/material: ^5.0.1 => 5.4.0
    @mui/private-theming:  5.3.0
    @mui/styled-engine:  5.3.0
    @mui/styles: ^5.0.1 => 5.0.1
    @mui/system: ^5.0.1 => 5.4.0
    @mui/types:  7.1.0
    @mui/utils:  5.6.1
    @mui/x-data-grid:  5.9.0
    @mui/x-data-grid-pro: ^5.9.0 => 5.9.0
    @mui/x-license-pro:  5.9.0
    @types/react: ^17.0.21 => 17.0.34
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.3.2 => 4.4.4

BROWSER: Chrome Version 100.0.4896.127 (Official Build) (64-bit)

```
</details>

### Order ID 💳 (optional)

31986

### PR DESCRIPTION
**Pull request by cherniavskii**
Fixes #4607

Codesandbox: https://codesandbox.io/s/basicdetailpanels-material-demo-npttjb

### CODE REVIEW

File: packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx [hunk 1]
```diff
@@ -101,7 +101,10 @@ const VirtualScrollerDetailPanels = styled('div', {
   name: 'MuiDataGrid',
   slot: 'DetailPanels',
   overridesResolver: (props, styles) => styles.detailPanels,
-})({});
+})({
+  position: 'relative',
+  zIndex: -1, // To make scroll grabbing work in Safari (see https://github.com/mui/mui-x/issues/4360)
```
Comment (m4theushw) [inline packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:106]: It broke https://deploy-preview-4610--material-ui-x.netlify.app/x/react-data-grid/master-detail/#disable-detail-panel-content-scroll

The detail panel should go over the pinned columns.

image

Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:106]: Yes, without `zIndex: -1` opening detail panel causes this issue https://github.com/mui/mui-x/issues/4360
I'll try to find another solution, this scroll issue keeps haunting me 😀

Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:106]: I don't see a simple solution to that, so I propose to remove `zIndex: -1` and ignore scroll grabbing issue, because:
- it's Safari only
- it appears only when detail panel is open
- IMHO not a lot of people grab the scrollbar on MacOS, if otherwise - let's wait for user reports
