### PR TITLE
[data grid] Improve print support

### LINKED ISSUE #6272: [data grid] Print export scrolls the page to the bottom
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Scroll to the bottom

### Expected behavior 🤔

No scroll change

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Open https://next--material-ui-x.netlify.app/x/react-data-grid/export/#enabling-export
2. Click on print
Screenshot 2022-09-23 at 21 34 24
3. Your scroll position is messed up 💥

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.6
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Edge: Not Found
    Firefox: 105.0
    Safari: 16.0
  npmPackages:
    typescript: ^4.6.4 => 4.6.4
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by oliviertassinari**
This seems to be an opportunity to:

1. Fix #6272
2. Show the print window faster, no need to wait for the page to load
3. Remove the HTTP header iframe limitation
4. Remove the dependency on https://github.com/mui/mui-x/pull/4149#issuecomment-1064109395

Before: https://mui.com/x/react-data-grid/export/#default-toolbar
After: https://deploy-preview-6273--material-ui-x.netlify.app/x/react-data-grid/export/#default-toolbar

Tested in Firefox, Safari, Chrome, latest versions

---

I have left a couple of TODO for a clean-up follow-up. I was also surprised with how we document the print export. If you:
1. open https://mui.com/.
2. search for print export: 
Screenshot 2022-09-24 at 00 55 30

3. click on the first link, you will land on https://mui.com/x/react-data-grid/export/#print-export, without a demo. I was disoriented by this, I struggled a bit to find a demo where I could see the feature in action. Would it make sense to add one?

### CODE REVIEW

File: test/utils/createDOM.js [hunk 1]
```diff
@@ -23,6 +23,7 @@ const blacklist = ['sessionStorage', 'localStorage'];
 function createDOM() {
   const dom = new JSDOM('', {
     pretendToBeVisual: true,
+    url: 'http://localhost',
```
Comment (oliviertassinari) [inline test/utils/createDOM.js:26]: To prove that it has no effect. I don't know if we need this URL parameter to be honest, we could remove it.

File: test/regressions/index.test.js [hunk 2]
```diff
@@ -195,9 +199,13 @@ async function main() {
...
             resolve();
           } else {
-            reject();
+            reject(code);
           }
         });
+
+        ffmpeg.stderr.on('data', (data) => {
+          console.error(`stderr: ${data}`);
+        });
```
Comment (oliviertassinari) [inline test/regressions/index.test.js:208]: To help understand why it fails locally.

File: test/regressions/TestViewer.js [hunk 3]
```diff
@@ -6,7 +6,9 @@ import GlobalStyles from '@mui/material/GlobalStyles';
 import { useLocation } from 'react-router-dom';
 import { useFakeTimers } from 'sinon';
 
-const StyledBox = styled(Box)(({ theme, isDataGridTest }) => ({
+const StyledBox = styled(Box, {
+  shouldForwardProp: (prop) => prop !== 'isDataGridTest',
```
Comment (oliviertassinari) [inline test/regressions/TestViewer.js:10]: Leaking prop on the DOM node (React warning)

File: packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx [hunk 4]
```diff
@@ -262,15 +266,21 @@ export const useGridPrintExport = (
...
       } else {
-        printWindow.onload = () => handlePrintWindowLoad(printWindow, options);
-        printWindow.contentWindow!.onafterprint = () => handlePrintWindowAfterPrint(printWindow);
+        printWindow.onload = () => {
+          handlePrintWindowLoad(printWindow, options);
+          printWindow.contentWindow!.onafterprint = () => {
+            handlePrintWindowAfterPrint(printWindow);
+          };
+        };
+        doc.current!.body.appendChild(printWindow);
```
Comment (oliviertassinari) [inline packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx:283]: Set the load event listener **after** appending the child.

File: packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx [hunk 5]
```diff
@@ -262,15 +266,21 @@ export const useGridPrintExport = (
 
       await updateGridColumnsForPrint(options?.fields, options?.allColumns);
       apiRef.current.unstable_disableVirtualization();
+      await raf(); // wait for the state changes to take action
```
Comment (oliviertassinari) [inline packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx:269]: This was already missing, but since we do no longer make a network request, the print displays a lot faster, which in the tests doesn't leave enough time for the API calls to render.

File: packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx [hunk 6]
```diff
@@ -101,11 +107,7 @@ export const useGridPrintExport = (
         ...options,
       };
 
-      // Some agents, such as IE11 and Enzyme (as of 2 Jun 2020) continuously call the
-      // `onload` callback. This ensures that it is only called once.
-      printWindow.onload = null;
```
Comment (oliviertassinari) [inline packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx:106]: IE 11 and enzyme are legacy, I'm not aware that we support them.

File: packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx [hunk 7]
```diff
@@ -54,6 +62,7 @@ export const useGridPrintExport = (
   const updateGridColumnsForPrint = React.useCallback(
     (fields?: string[], allColumns?: boolean) =>
       new Promise<void>((resolve) => {
+        // TODO remove unused Promise
```
Comment (flaviendelangle) [inline packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx:65]: Are those `TODO` here because it's breaking ?
If so, we started the alpha phase so we can do the breaking change I think.

File: packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx [hunk 8]
```diff
@@ -158,9 +160,11 @@ export const useGridPrintExport = (
         gridFooterElementHeight
       }px`;
 
-      // Remove all loaded elements from the current host
-      printDoc.body.innerHTML = '';
-      printDoc.body.appendChild(gridClone);
+      // printDoc.body.appendChild(gridClone); should be enough but a clone isolation bug in Safari
```
Comment (flaviendelangle) [inline packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx:163]: If you have a link to the bug report to help future evolution of this method

**Review by flaviendelangle — APPROVED** [review]
No problem with dropping IE11 support if that's what the company is doing elsewhere.

**Review by DanailH — APPROVED** [review]
Nice cleanup

File: packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx (hunk 7 above)
Comment (oliviertassinari) [reply packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx:65]: > Are those TODO here because it's breaking?

The TODO is here because it would make it harder to review what changed in the PR.

File: packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx (hunk 8 above)
Comment (oliviertassinari) [reply packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx:163]: I can't find it in https://bugs.webkit.org/buglist.cgi?quicksearch=cloneNode.

File: packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx (hunk 7 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx:65]: Make sense
We can make a follow up after that to remove the promise then

File: packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx (hunk 8 above)
Comment (oliviertassinari) [reply packages/grid/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx:163]: On Safari 16.0, after a print without using `innerHTML` to cleanly deep clone:

Screenshot 2022-09-26 at 13 14 07
