### PR TITLE
[datagrid] Fix scroll jumping

### LINKED ISSUE #19017: [data grid] Scroll jumping in firefox 141
### Steps to reproduce

Steps:
1. Open this link to live example in Firefox (at least version 141, not sure about previous versions):   [https://stackblitz.com/edit/y9stnxbw-rj7v8zne](https://stackblitz.com/edit/y9stnxbw-rj7v8zne) 
2. Try to scroll through the data grid using the scroll wheel
3. Observe the scroll position jumping back up when approaching a grouped row

It doesn't seem to happen with `disableVirtualization` or while using Google Chrome.

https://github.com/user-attachments/assets/6640c53f-514b-4ad8-ad3b-b90f270ce5da

### Current behavior

Very hard to scroll all the way to the bottom, the scroll position jumps back up.

### Expected behavior

Scrolling should be smooth.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: tree data firefox

### PR DESCRIPTION
**Pull request by romgrk**
Closes #19017 

The effect was running too often because the container wasn't stable. Adding/removing the `ResizeObserver` seems to cause scroll jumps on firefox (and maybe chrome).

### CODE REVIEW

**Review by cherniavskii — APPROVED** [review]

File: packages/x-virtualizer/src/features/dimensions.ts [hunk 1]
```diff
@@ -259,7 +258,7 @@ function useDimensions(store: Store<BaseState>, params: VirtualizerParams, _api:
   );
   React.useEffect(() => debouncedUpdateDimensions?.clear, [debouncedUpdateDimensions]);
 
-  useLayoutEffect(() => observeRootNode(refs.container.current, store), [refs, store]);
+  useLayoutEffect(() => observeRootNode(containerNode, store), [containerNode, store]);
```
Comment (cherniavskii) [inline packages/x-virtualizer/src/features/dimensions.ts:261]: This change broke horizontal virtualization: https://deploy-preview-19156--material-ui-x.netlify.app/x/react-data-grid/#pro-version

Comment (cherniavskii) [reply packages/x-virtualizer/src/features/dimensions.ts:261]: Hmm, I don't understand why it doesn't work as expected though:

```tsx
const containerNode = refs.container.current;

console.log('render', containerNode);

React.useLayoutEffect(() => {
  console.log('useLayoutEffect', containerNode);
  return observeRootNode(containerNode, store);
}, [containerNode, store]);
```

Logs:

```
render null
dimensions.ts:261 render null
dimensions.ts:264 useLayoutEffect null
dimensions.ts:527 observeRootNode null
dimensions.ts:261 render null
dimensions.ts:261 render null
dimensions.ts:261 render <div class=​"MuiDataGrid-main MuiDataGrid-main--hiddenContent css-1bgckiu-MuiDataGrid-main" tabindex=​"-1" role=​"grid" aria-colcount=​"30" aria-rowcount=​"1" aria-multiselectable=​"true">​…​</div>​flex
dimensions.ts:261 render <div class=​"MuiDataGrid-main MuiDataGrid-main--hiddenContent css-1bgckiu-MuiDataGrid-main" tabindex=​"-1" role=​"grid" aria-colcount=​"30" aria-rowcount=​"1" aria-multiselectable=​"true">​…​</div>​flex
dimensions.ts:261 render <div class=​"MuiDataGrid-main MuiDataGrid-main--hiddenContent css-1bgckiu-MuiDataGrid-main" tabindex=​"-1" role=​"grid" aria-colcount=​"30" aria-rowcount=​"1" aria-multiselectable=​"true">​…​</div>​flex
dimensions.ts:261 render <div class=​"MuiDataGrid-main css-1bgckiu-MuiDataGrid-main" tabindex=​"-1" role=​"grid" aria-colcount=​"30" aria-rowcount=​"100001" aria-multiselectable=​"true">​…​</div>​flex
dimensions.ts:261 render <div class=​"MuiDataGrid-main css-1bgckiu-MuiDataGrid-main" tabindex=​"-1" role=​"grid" aria-colcount=​"30" aria-rowcount=​"100001" aria-multiselectable=​"true">​…​</div>​flex
dimensions.ts:261 render <div class=​"MuiDataGrid-main css-1bgckiu-MuiDataGrid-main" tabindex=​"-1" role=​"grid" aria-colcount=​"30" aria-rowcount=​"100001" aria-multiselectable=​"true">​…​</div>​flex
dimensions.ts:261 render <div class=​"MuiDataGrid-main css-1bgckiu-MuiDataGrid-main" tabindex=​"-1" role=​"grid" aria-colcount=​"30" aria-rowcount=​"100001" aria-multiselectable=​"true">​…​</div>​flex
dimensions.ts:261 render <div class=​"MuiDataGrid-main css-1bgckiu-MuiDataGrid-main" tabindex=​"-1" role=​"grid" aria-colcount=​"30" aria-rowcount=​"100001" aria-multiselectable=​"true">​…​</div>​flex
```

How come `useLayoutEffect` doesn't rerun when `containerNode` clearly changes and there are rerenders? 🤔

Comment (cherniavskii) [reply packages/x-virtualizer/src/features/dimensions.ts:261]: I tried moving this effect to the very top of the hook to make sure that it's not cancelled by another effect that has state update inside, but the behavior is the same.
This looks like a React bug to me.

Comment (cherniavskii) [reply packages/x-virtualizer/src/features/dimensions.ts:261]: Or a nextjs bug – I can't reproduce the issue in stackblitz using the packages built from this branch: https://stackblitz.com/edit/kygkymrj?file=package.json

Comment (cherniavskii) [reply packages/x-virtualizer/src/features/dimensions.ts:261]: Commenting out this line makes layout effect run after containerNode changes and everything seems to work fine: https://github.com/mui/mui-x/blob/040047bce5449d106cabc6a8f11e2b9a62c78014/packages/x-virtualizer/src/features/dimensions.ts#L271

This means that the layout effect is indeed cancelled because of state update in `useStoreEffect`

Comment (romgrk) [reply packages/x-virtualizer/src/features/dimensions.ts:261]: For some reason, the issue doesn't appear for me in the playground page, it only appears in the other docs pages.

I'll refactor the state update away from the store effect.

Comment (cherniavskii) [reply packages/x-virtualizer/src/features/dimensions.ts:261]: I can reproduce it on playground page:

Comment (romgrk) [reply packages/x-virtualizer/src/features/dimensions.ts:261]: How's your playground page setup? Mine works [like this](https://mui-org.slack.com/archives/C011VC970AW/p1753911459263929?thread_ts=1753870469.744829&cid=C011VC970AW), which has been reported (by others) to avoid some nextjs issues, maybe I should configure it differently.

Comment (romgrk) [reply packages/x-virtualizer/src/features/dimensions.ts:261]: I can confirm that if I remove the shell that I have in my playground page, I observe the same issues that are otherwise present only in the rest of the pages.
