### PR TITLE
[DataGrid] Fix `columnsManagementRow` style override slot not working

### LINKED ISSUE #18403: [data grid] `columnsManagementRow` style override slot not working
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/sandbox/eloquent-mirzakhani-5hd5xp
2. Click the column header menu
3. Click on "Manage columns"

### Current behavior

The items in the column management menu should have red backgrounds (indicating the `styleOverrides` worked)

### Expected behavior

The items in the column management menu do not have red backgrounds.

See comments in `index.tsx` in the CodeSandbox.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 15.5
  Binaries:
    Node: 22.14.0 - ~/.asdf/installs/nodejs/22.14.0/bin/node
    npm: 10.9.2 - ~/.asdf/installs/nodejs/22.14.0/bin/npm
    pnpm: 9.9.0 - ~/.asdf/installs/nodejs/22.14.0/bin/pnpm
  Browsers:
    Chrome: 137.0.7151.104
    Edge: Not Found
    Safari: 18.5
  npmPackages:
    @emotion/react: ~11.14.0 => 11.14.0
    @emotion/styled: ~11.14.0 => 11.14.0
    @mui/icons-material: ~7.1.1 => 7.1.1
    @mui/lab: 7.0.0-beta.13 => 7.0.0-beta.13
    @mui/material: ~7.1.1 => 7.1.1
    @mui/system: ~7.1.1 => 7.1.1
    @mui/utils: ~7.1.1 => 7.1.1
    @mui/x-data-grid-premium: ~8.5.2 => 8.5.2
    @mui/x-license: ~8.5.2 => 8.5.2
    @mui/x-tree-view-pro: ~8.5.0 => 8.5.0
    @types/react: ~19.1.6 => 19.1.6
    react: ~19.1.0 => 19.1.0
    react-dom: ~19.1.0 => 19.1.0
    typescript: catalog:default => 5.8.2
```
</details>

**Search keywords**: columnsManagementRow,style override,styleOverrides

**Order ID**: 101098

### PR DESCRIPTION
**Pull request by dwrth**
Closes #18403

`GridColumnsManagementRow` slot was not available

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

File: packages/x-data-grid/src/components/columnsManagement/GridColumnsManagement.tsx [hunk 1]
```diff
@@ -456,4 +457,9 @@ const GridColumnsManagementEmptyText = styled('div', {
   font: vars.typography.font.body,
 });
 
+const GridColumnsManagementRow = styled('button', {
```
Comment (arminmeh) [inline packages/x-data-grid/src/components/columnsManagement/GridColumnsManagement.tsx]: Shouldn't this be
```suggestion
const GridColumnsManagementRow = styled('input', {
```
?

Comment (dwrth) [reply packages/x-data-grid/src/components/columnsManagement/GridColumnsManagement.tsx]: Yes true!

Edit: Or not :D I have added the proper element type now, similar to how it was handled in `packages/x-data-grid-premium/src/components/pivotPanel/GridPivotPanelField.tsx`

**Review by arminmeh — APPROVED** [review]
