### PR TITLE
[DataGrid] Update quick filter input when model is modified

### LINKED ISSUE #4921: QuickFilter: quick filter input is not reflecting data grid filter model
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using DataGridPro with filterModel (saving the sate in Redux), then quick filter input doesn't work well: records get filtered but quick filter input is not updated when setting / resetting filter model.

### Expected behavior 🤔

Quick filter inout should honor filterModel and reflect what is saved in the model.

### Steps to reproduce 🕹

Cannot work on your DataGrid / DataGridPro templates since they are broken. 

This is the error I get:

    TypeError
    (0 , $csb___mui_utils.unstable_generateUtilityClasses) is not a function

Here is what I'm trying to do:
https://codesandbox.io/s/data-grid-pro-forked-yn7vwj

### Context 🔦

I use DataGridPro in a controlled mode saving filterModel, sortModel, columnVisibilityModel, pinnedColumns in redux, because the interaction with records (details, edit, delete) is managed in different pages. 
When going back to the list the state must be restored.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  I'm using Google Chrome.

  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Edge: Not Found
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.7.0 => 11.9.0
    @emotion/styled: ^11.6.0 => 11.8.1
    @mui/base:  5.0.0-alpha.81
    @mui/icons-material: ^5.2.1 => 5.8.0
    @mui/lab: ^5.0.0-alpha.59 => 5.0.0-alpha.82
    @mui/material: ^5.2.3 => 5.8.0
    @mui/private-theming:  5.8.0
    @mui/styled-engine:  5.8.0
    @mui/styles: ^5.2.3 => 5.8.0
    @mui/system:  5.8.0
    @mui/types:  7.1.3
    @mui/utils:  5.8.0
    @mui/x-data-grid:  5.11.0
    @mui/x-data-grid-pro: ^5.2.0 => 5.11.0
    @mui/x-date-pickers:  5.0.0-alpha.0
    @mui/x-date-pickers-pro: ^5.0.0-alpha.1 => 5.0.0-alpha.3
    @mui/x-license-pro:  5.11.0
    @types/react:  18.0.9
    react: ^17.0.1 => 17.0.2
    react-dom: ^17.0.1 => 17.0.2
    styled-components: ^5.3.0 => 5.3.5
    typescript:  4.6.4
```
</details>

### Order ID 💳 (optional)

#32735

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #4921

I assume the quick filter value is rarely modified from somewhere else. It can be reset by clicking a button, or when putting back a saved state.

From this, I propose to add a prop to the input named `quickFilterFormatter`. This prop is used only if the quick filter state is updated and does not correspond anymore to the input content. In such a case, we use this `quickFilterFormatter` to update the input content.

### CODE REVIEW

File: packages/grid/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx [hunk 1]
```diff
@@ -39,12 +65,39 @@ export type GridToolbarQuickFilterProps = TextFieldProps & {
...
+  const {
+    quickFilterParser = defaultSearchValueParser,
+    quickFilterFormatter = defaultSearchValueFormatter,
+    debounceMs = 500,
+    ...other
+  } = props;
 
   const apiRef = useGridApiContext();
   const rootProps = useGridRootProps();
+  const quickFilterValues = gridQuickFilterValuesSelector(apiRef);
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx:77]: Pass to `useGridSelector`?

File: packages/grid/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx [hunk 2]
```diff
@@ -39,12 +65,39 @@ export type GridToolbarQuickFilterProps = TextFieldProps & {
...
 
-  const [searchValue, setSearchValue] = React.useState('');
+  const [searchValue, setSearchValue] = React.useState(
+    quickFilterFormatter(quickFilterValues ?? []),
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx:80]: To not call `quickFilterFormatter` on every render.

```suggestion
    () => quickFilterFormatter(quickFilterValues ?? []),
```

File: packages/grid/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx [hunk 3]
```diff
@@ -39,12 +65,39 @@ export type GridToolbarQuickFilterProps = TextFieldProps & {
...
+
+  const [prevQuickFilterValues, setPrevQuickFilterValues] = React.useState(quickFilterValues);
+
+  React.useEffect(() => {
+    if (!isDeepEqual(prevQuickFilterValues, quickFilterValues)) {
+      // The model of quick filter value has been updated
+      setPrevQuickFilterValues(quickFilterValues);
+      if (!isDeepEqual(quickFilterParser(searchValue), quickFilterValues)) {
+        // The input value and the new model are un-sync so we will update the input
+        setSearchValue(quickFilterFormatter(quickFilterValues ?? []));
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx:91]: It's calling this effect twice. You can do two things to improve it:
- use a ref for `prevQuickFilterValues`, since it's not part of the state of the component
- instead of `setSearchValue` do `setSearchValue(prevSearchValue => { ... })` to remove `searchValue` from the dependencies.

**Review by m4theushw — COMMENTED** [review]
Could you add a test?

File: packages/grid/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx (hunk 2 above)
Comment (alexfauquette) [reply packages/grid/x-data-grid/src/components/toolbar/GridToolbarQuickFilter.tsx:80]: I don't get why. The default value provided in `React.useState` should be computed only in the first render. After the first render, this parameter has no effect on the value of the state

File: packages/grid/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts [hunk 4]
```diff
@@ -19,6 +19,15 @@ export const gridFilterModelSelector = createSelector(
   (filterState) => filterState.filterModel,
 );
 
+/**
+ * Get the current quick filter values.
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts:23]:
```suggestion
 * Gets the current quick filter values.
```

File: docs/data/data-grid/filtering/filtering.md [hunk 5]
```diff
@@ -368,13 +368,16 @@ The values used by the quick filter are obtained by splitting with space.
 If you want to implement a more advanced logic, the `<GridToolbarQuickFilter/>` component accepts a prop `quickFilterParser`.
 This function takes the string from the search text field and returns an array of values.
 
+If you control the `quickFilterValues` either by controlling `filterModel` or with the initial state, you should provide a `quickFilterFormatter` which will be used to update the content of the input.
```
Comment (m4theushw) [inline docs/data/data-grid/filtering/filtering.md:371]: I didn't understand this part. There's a default value formatter, the user doesn't need to pass one.

File: packages/grid/x-data-grid/src/tests/quickFiltering.DataGrid.test.tsx [hunk 6]
```diff
@@ -85,6 +86,60 @@ describe('<DataGrid /> - Quick Filter', () => {
...
+      setProps({
+        filterModel: {
+          items: [],
+          quickFilterValues: [],
+        },
+      });
+      expect(container.querySelector('input[type=search]').value).to.equal('');
+    });
+
+    it('should allows to customize input formatting', () => {
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/tests/quickFiltering.DataGrid.test.tsx:123]:
```suggestion
    it('should allow to customize input formatting', () => {
```

File: packages/grid/x-data-grid/src/tests/quickFiltering.DataGrid.test.tsx [hunk 7]
```diff
@@ -85,6 +86,60 @@ describe('<DataGrid /> - Quick Filter', () => {
...
+
+    it('should no prettify user input', () => {
+      const { container } = render(<TestCase />);
+
+      fireEvent.change(container.querySelector('input[type=search]'), {
+        target: { value: 'adidas   nike' },
+      });
+      clock.runToLast();
+
+      expect(container.querySelector('input[type=search]').value).to.equal('adidas   nike');
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/tests/quickFiltering.DataGrid.test.tsx:98]: Better to query the `role`.

```suggestion
      fireEvent.change(screen.getByRole('searchbox'), {
        target: { value: 'adidas   nike' },
      });
      clock.runToLast();

      expect(screen.getByRole('searchbox').value).to.equal('adidas   nike');
```

x other tests.

File: docs/data/data-grid/filtering/filtering.md (hunk 5 above)
Comment (alexfauquette) [reply docs/data/data-grid/filtering/filtering.md:371]: I tried to be more explicit

File: packages/grid/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts (hunk 4 above)
Comment (alexfauquette) [reply packages/grid/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts:23]: All the other lines are with `Get`

Comment (m4theushw) [reply packages/grid/x-data-grid/src/hooks/features/filter/gridFilterSelector.ts:23]: That's inconsistent because all API methods use the present tense. Anyway, leave as it is and we can fix all later.

**Review by m4theushw — APPROVED** [review]
Looks good!
