### PR TITLE
[pickers] Always use `props.value` when it changes

### LINKED ISSUE #10424: [pickers] Reset the value of the input field using controlled value
### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.

### Current behavior 😯

I am using <DesktopDatePicker /> in my React + MUI application... My calendar date selections are working fine as expected. But the user is allowed to type invalid dates in the input field e.g 31st of November or 13th month of the year.  if user types an invalid value in the input field then instead of updating the state value my code reset it to previous value by using the inputRefs. 

It changes the value to previous one but when i open the calendar it again change the value(in input field) to invalid date. 

Can you help how to handle this ?

### Expected behavior 🤔

Expectation is that if the date is invalid, set it back to valid one programmatically both in calendar and the input field. 

### Context 🔦

as a work around, i have used key attribute and re-render on each invalid date. I would like to get a proper solution.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
Closes #10424

### CODE REVIEW

File: packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts [hunk 1]
```diff
@@ -302,15 +302,7 @@ export const usePickerValue = <
...
-  if (
-    inValueWithTimezoneToRender !== undefined &&
-    (dateState.lastControlledValue === undefined ||
-      !valueManager.areValuesEqual(
-        utils,
-        dateState.lastControlledValue,
-        inValueWithTimezoneToRender,
-      ))
-  ) {
+  if (dateState.lastControlledValue !== inValueWithoutRenderTimezone) {
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/usePicker/usePickerValue.ts:305]: We compare the old `props.value` with the new `props.value` (without any processing done to it)
If it changed:

1. We set the new `props.value` in the state
2. If the new derived `props.value` with the right timezone is not equal to the current draft, we update the draft

**Review by michelengelen — APPROVED** [review]

**Comment by LukasTy** [comment]
@flaviendelangle I think that the PR only partially fixes the issue.

Essentially, we should always keep the bound value as the source of truth, even if it didn't change.

In this example, any change should not change the value as with the native input.
https://stackblitz.com/edit/react-ly6xoy?file=Demo.tsx

**Comment by flaviendelangle** [comment]
I think we can create a dedicated issue for this exact behavior: #15530
It's not only at the picker level, it's mostly the field that works this way. I do agree that it would  be nice to mimic to browser input here. The main challenge will probably be to handle invalid date correctly.
We might also have a breaking change if people do checks before storing the value in state and they don't handle invalid values correctly.
