### PR TITLE
[DataGrid] Fix focus steal issue with `<Dialog />`

### LINKED ISSUE #21063: [data grid] 8.26.0 is broken
### The problem in depth

In the actions column of my table, I have buttons which can open dialogs:
Image

Inside those dialogs there can be forms:

Image

Typing in a field inside a form in a dialog breaks with @mui/x-data-grid-pro v8.26.0

Reverting to 8.25.0 fixes the issue.

This is a suspicious PR that touches grid column actions, perhaps this broke it?
https://github.com/mui/mui-x/pull/20994

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>
```
  System:
    OS: Linux 6.18 Arch Linux
  Binaries:
    Node: 24.3.0 - /home/l0gicgate/.nvm/versions/node/v24.3.0/bin/node
    npm: 11.4.2 - /home/l0gicgate/.nvm/versions/node/v24.3.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Version 143.0.7499.192 (Official Build) Arch Linux (64-bit)
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.14.0 => 11.14.0 
    @emotion/styled: ^11.14.1 => 11.14.1 
    @mui/core-downloads-tracker:  7.3.7 
    @mui/lab: ^7.0.0 => 7.0.0 
    @mui/material: ^7.3.7 => 7.3.7 
    @mui/material-nextjs: ^7.3.7 => 7.3.7 
    @mui/private-theming:  7.3.7 
    @mui/styled-engine:  7.3.7 
    @mui/system:  7.3.7 
    @mui/types:  7.4.10 
    @mui/utils:  7.3.7 
    @mui/x-charts: ^8.26.0 => 8.26.0 
    @mui/x-charts-vendor:  8.26.0 
    @mui/x-data-grid:  8.25.0 
    @mui/x-data-grid-pro: 8.25.0 => 8.25.0 
    @mui/x-internal-gestures:  0.4.0 
    @mui/x-internals:  8.26.0 
    @mui/x-license: ^8.26.0 => 8.26.0 
    @mui/x-telemetry:  8.20.0 
    @mui/x-virtualizer:  0.3.2 
    @types/react: ^19.2.9 => 19.2.9 
    react: ^19.2.3 => 19.2.3 
    react-dom: ^19.2.3 => 19.2.3 
    typescript: ^5.9.3 => 5.9.3 
```
</details>

**Search keywords**: Event bubbling

**Order ID**: 122868

### PR DESCRIPTION
**Pull request by MBilalShafi**
## 🎯 Fix focus being stolen from inputs in `<Dialog />` opened from `renderCell()`                        
                                                                                                            
  ### 🐛 Problem                                                                                            
                                                                                                            
  When rendering a `Dialog` (or any Portal-based component) from a `renderCell()` callback, typing in an input
   inside the dialog caused the input to immediately lose focus. Each keypress would steal focus back to the
   grid cell.
   
**Demos:**
- Before: https://stackblitz.com/edit/y6imucnf
- After: https://stackblitz.com/edit/y6imucnf-2rmd7esk                                                                           
                                                                                                            
**Reproduction steps:**      
1. 🖱️ Open the dialog and focus the input                                                                 
2. ⌨️ Try to type - the input loses focus after each keypress     
                                                                                                            
  ### 🔍 Root Cause                                                                                         
                                                                                                            
  React synthetic events bubble through the **React component tree**, not the DOM tree. This means events   
  from Portal content (like a Dialog) still bubble to parent React components, even though the Portal       
  renders outside the cell's DOM hierarchy.                                                                 
                                                                                                            
  The `handleCellKeyDown` handler was receiving these bubbled events and calling `setCellFocus()`. Inside   
  `setCellFocus()`, there was an aggressive focus synchronization block that detected when the DOM's        
  `activeElement` was outside the cell element and forcibly called `cellElement.focus()` to "correct" this  
  state.                                                                                                    
                                                                                                            
  **Why this was problematic:**                                                                             
  1. 📤 The cell's `onKeyDown` received events from Portal content via React's synthetic event bubbling     
  2. 🔎 The focus sync detected the activeElement (the dialog input) was outside the cell DOM               
  3. 🚨 It called `cellElement.focus()`, stealing focus from the dialog input                               
                                                                                                            
  ### ✅ Solution                                                                                           
                                                                                                            
  Removed the aggressive focus synchronization block from `setCellFocus()`. This block was attempting to    
  keep DOM focus in sync with grid state, but it incorrectly assumed that focus outside the cell was always 
  unintentional.                                                                                            
                                                                                                            
  The existing `handleDocumentClick` logic already handles focus management correctly by checking           
  `cellElement?.contains(event.target)` before making focus decisions.                                      
                                                                                                            
  > 💡 **Note:** The history feature (undo/redo) is unaffected by this change because it has specialized    
  focus restoration logic in `defaultHistoryHandlers` that handles focus management independently.          
                                                                                                            
  ### 📁 Changes                                                                                            
                                                                                                            
  | File | Description |                                                                                    
  |------|-------------|                                                                                    
  | `useGridFocus.ts` | 🗑️ Removed the focus sync block that was calling `cellElement.focus()` when activeElement was outside the cell |                                                                      
  | `rows.DataGrid.test.tsx` | 🧪 Added regression test for Dialog input focus retention |                  
                                                                                                            
  ### 🧪 Test Plan                                                                                          
                                                                                                            
  - [x] ✅ Browser tests pass (Chromium)                                                                    
  - [x] ✅ New test verifies typing in Dialog input doesn't lose focus
 
 ---
                                  
  🔗 Fixes #21063

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/focus/useGridFocus.ts [hunk 1]
```diff
@@ -67,31 +66,6 @@ export const useGridFocus = (
     (id, field) => {
       const focusedCell = gridFocusCellSelector(apiRef);
       if (focusedCell?.id === id && focusedCell?.field === field) {
-        /**
```
Comment (arminmeh) [inline packages/x-data-grid/src/hooks/features/focus/useGridFocus.ts:70]: I have added this while working on undo/redo

What it was trying to solve was the loss of focus when undoing/redoing changes on the same cell.

https://github.com/user-attachments/assets/fa07507a-dae7-40be-aef1-cfd79278effa

You can see that undoing changes on different cells works fine, but repeated undo/redo on the same cell changes the content while the focus is lost.

Comment (arminmeh) [reply packages/x-data-grid/src/hooks/features/focus/useGridFocus.ts:70]: Since the issue reported is a bigger problem than the loss of focus on undo/redo, I am fine to remove this to resolve the regression and find another way to fix undo/redo.
