### PR TITLE
[charts] Fix Tooltip crash with out of range lines

### LINKED ISSUE #11893: [docs] Charts demo `ConnectNulls` crashes
- [ ] I have [searched for similar issues](https://github.com/mui/mui-x/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20ConnectNulls%20crashes) in this repository and believe that this is not a duplicate.

## Steps to reproduce
1. Visit https://deploy-preview-11620--material-ui-x.netlify.app/x/react-charts/lines/#connect-missing-points
2. Mouseover one of the last two data points
3. demo *ConnectNulls* crashes

## Your environment
| Tech         | Version |
|--------------|---------|
| Version  | v7.0.0-beta.0  |
| Netlify deploy | https://65b7c52b4d468a0008aefda0--material-ui-x.netlify.app |
| Browser      | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 |

**Search keywords**:

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #11893

If some series stop earlier, the default tooltip called the formatter with `undefined` which was no handled by the default formatter.

I tried to improve the typing, but not that much a success

### CODE REVIEW

File: packages/x-charts/src/ChartsTooltip/DefaultChartsAxisTooltipContent.tsx [hunk 1]
```diff
@@ -33,31 +33,36 @@ function DefaultChartsAxisTooltipContent(props: ChartsAxisContentProps) {
...
-                  <ChartsTooltipMark
-                    ownerState={{ color }}
-                    boxShadow={1}
-                    className={classes.mark}
-                  />
-                </ChartsTooltipCell>
+          {series
+            .filter((item): item is ChartSeriesDefaultized<CartesianChartSeriesType> =>
+              ['bar', 'line', 'scatter'].includes(item.type),
+            )
```
Comment (LukasTy) [inline packages/x-charts/src/ChartsTooltip/DefaultChartsAxisTooltipContent.tsx:39]: Nitpick: WDYT, would it make sense to extract it into a variable outside of JSX? 🤔

**Review by LukasTy — APPROVED** [review]

File: packages/x-charts/src/ChartsTooltip/DefaultChartsAxisTooltipContent.tsx (hunk 1 above)
Comment (alexfauquette) [reply packages/x-charts/src/ChartsTooltip/DefaultChartsAxisTooltipContent.tsx]: Very good idea. I also did it for the container
