### PR TITLE
[DataGrid] Don't evaluate hasEval when disableEval is set

### LINKED ISSUE #11465: `hasEval` detection leads to CSP warnings and reports
### Steps to reproduce

1. Setup Content-Security-Policy that does not allow `'unsafe-eval'` (like `Content-Security-Policy: script-src 'self'`)
2. Visit a site that imports "@mui/x-data-grid"

### Current behavior

The `hasEval` detection added in https://github.com/mui/mui-x/issues/10056 is always automatically executed, even if the undocumented option `disableEval` is used. The `hasEval` detection runs an obfuscated version of `eval("true")` which gets blocked. This leads to CSP warnings in the browser, which are also reported via `Report-To`.

### Expected behavior

I would prefer if `eval()` isn't used at all, but if that's not an option, then it should not be used if `disableEval` is set to true. Doing the computation of `hasEval` lazily (and only if `disableEval` is not set) would solve the problem.

### Context

I'm trying to use the datagrid component in a secure way. Having Content-Security-Policy headers is highly recommended and disallowing arbitrary `eval()`s is the whole point of CSP. Having a report endpoint to catch possible security breaches (and errors within dev) is also recommended and having to continuously filter out false reports because of `eval("true")` within mui-x is really annoying and might hide more serious attacks or bugs.

### Your environment

_No response_

**Search keywords**: datagrid csp eval

### PR DESCRIPTION
**Pull request by reihwald**
Merry christmas!

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #11465 

I had the same issue as #11465 and changed the evaluation of hasEval so that it no longer writes a warning/error in the console in case eval is blocked by the csp. 

I also made disableEval appeir in the DataGrid API as per @flaviendelangle but I'm of course open to reverting this in case it's not wanted.

This change also makes it so that the eval check won't be executed if `filterMode='server'` regardless of the disableEval prop.

### CODE REVIEW

**Comment by reihwald** [comment]
Is the argos fail expected? It seems to be failing because of something unrelated to this pr

**Comment by flaviendelangle** [comment]
The Argos diff is due to the fact that you are targeting `master` and our main branch is currently `next`
So Argos compare its screenshot to `next`

Unless this PR is a cherry-pick of a PR already applied to `next`, it should probably target `next` and we will take care of back-porting it to `master`

`next` contains the code for v7 alpha releases and `master` contains the code for v6 stable releases.

**Comment by reihwald** [comment]
Thanks @flaviendelangle. I changed the branch. Can I help with the back-porting?

**Comment by flaviendelangle** [comment]
We have a new bot that should create the PR on `master` once we merge this one :+1: 
I'll let the grid team make the review

File: packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts [hunk 1]
```diff
@@ -26,12 +26,13 @@ import {
...
-} catch (_: unknown) {
-  hasEval = false;
-}
+const getHasEval = () => {
+  try {
+    return evalCode<boolean>('true');
+  } catch (_: unknown) {
+    return false;
+  }
+};
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts:35]: Is it possible to avoid making the check everytime it's needed? Check once, store the value.

Comment (reihwald) [reply packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts]: Good idea it was indeed checked uselessly often. Thanks I changed it.

**Review by romgrk — APPROVED** [review]

**Comment by reihwald** [comment]
@romgrk I had to retrigger the pipeline because a check failed. Can you please enable auto-merge again?

**Comment by romgrk** [comment]
All good, thanks for the PR!
