### PR TITLE
[pickers] Fix `themeAugmentation` and style overriding

### LINKED ISSUE #4552: [pickers] Add classes to `DayPicker` sub-components
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The header (or row) that contains the week labels should have a className so that it could be styled.

The weekday labels (['S, M, T, W, T, F, S']) should be customizable just like weekdays are.
Now, it is possible to resize the weekdays, but then they have a different size than week labels. 

Also, the rows containing the weekdays should have a className so that these can be customized. 
Now, it contains has margin between rows which can't be removed.

### Examples 🌈

_No response_

### Motivation 🔦

File: PickersCalendar.tsx

**1. Add className to PickersCalendarDayHeader**

weekdayrow

Problem:  The header containing the week labels can not be styled. This is because the header can not be targeted.
Solution: Add `.MuiPickersCalendar-dayHeader` className to the PickersCalendarDayHeader component

**2. Add className to PickersCalendarWeekDayLabel**

weekday

Problem: The size of the weekday labels can't be changed. This is because the weekday labels can not be targeted.
Solution: Add `.MuiPickersCalendar-weekDayLabel` className to the PickersCalendarWeekDayLabel component

**3. Add className to PickersCalendarWeek**

dayrow

Problem: The margin between week rows can't be removed. This is because the week rows can not be targeted.
Solution: Add `.MuiPickersCalendar-week` className to the PickersCalendarWeek component

### LINKED ISSUE #4669: [pickers] Add style override for sub components
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

After migrating pickers to emotion (v4 to v5), I lost the ability to modify the styling of some subcomponents. I think this is due to the fact that `styled` is used without providing the `name` option as can be seen in

https://github.com/mui/mui-x/blob/ebb0e3b1a4d940b02ca20abd61ade86fce9b6e94/packages/x-date-pickers/src/DateTimePicker/DateTimePickerToolbar.tsx#L31

## Expected Behavior 🤔
I should be able to style the subcomponents of pickers. For instance, in RTL view, the `TimeContainer` component of `DateTimePickerToolbar` used in `MobileDateTimePicker` shows the time with `direction: rtl`. I want to change this behavior so that the time is always `ltr` even if the theme is `rtl`. Previously, with JSS, this worked:
```javascript
const theme = createTheme({
  direction: rtl,
  components: {
      MuiDateTimePickerToolbar: {
        styleOverrides: {
          timeContainer: {
            flip: false,
            direction: "ltr",
          },
        },
      },
    },
});
```
Now, with emotion, I would expect the following to work, but it doesn't:
```javascript
const theme = createTheme({
  direction: rtl,
  components: {
      MuiDateTimePickerToolbar: {
        styleOverrides: {
          root: {
            "& .MuiDateTimePickerToolbar-timeContainer": {
              direction: "/* @noflip */ ltr",
            },
          },
        },
      },
    },
});
```

Also, when inspecting the element, the class name is not `MuiDateTimePickerToolbar-timeContainer` or anything similar, but `muirtl-1lomthf`.

Is there currently a work around for this?

### LINKED ISSUE #5194: [TimePicker] Can't change color of selected items
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In TimePicker I am unable to set the color of the selected items in the clock, while I was able to change basically everything else:
image

I would like to make the background color of the highlighted items red instead of blue (AM/PM and selected time)

### Expected behavior 🤔

The text color of the numbers should change.

### Steps to reproduce 🕹

I tried to accomplish this using the `PaperProps`
```
    <LocalizationProvider dateAdapter={AdapterDateFns}>
      <TimePicker
        disableMaskedInput
        //   Style Props --- start
        PaperProps={{
          sx: {
            backgroundColor: "#000000",
            color: "#eeeeee",
            "& .MuiButtonBase-root": {
              color: "#ffffff",
            },
            "& .MuiPickersArrowSwitcher-button": {
              backgroundColor: "#282d36",
              color: "#ffffff",
            },
            // clocl background color
            "& .css-eziifo": {
              backgroundColor: "#282d36",
            },
            // clock numbers color
            "& .css-1flhz3h": {
              color: "#ffffff",
            },
            // clock selected items color
            "& .css-7lip4c, .css-12ha4i7, .css-118whkv, .Mui-selected, .css-a1rc6s":
              {
                backgroundColor: "#d3121a",
              },
          },
        }}
        InputProps={{
          disableUnderline: true,
          sx: {
            backgroundColor: "#282d36",
          },
        }}
        OpenPickerButtonProps={{
          sx: { color: "hsl(0, 0%, 80%)" },
        }}
        //   Style Props --- end
        inputFormat="HH:mm"
        onChange={handleChange}
        renderInput={renderCustomInput}
        value={date}
      />
    </LocalizationProvider>
```

### Context 🔦

I am just trying to customize my UI elements to match the app theme I use.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD  
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 102.0.5005.63
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.39)
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.81
    @mui/icons-material: ^5.8.0 => 5.8.0
    @mui/material: ^5.8.0 => 5.8.0
    @mui/private-theming:  5.8.0
    @mui/styled-engine:  5.8.0
    @mui/styled-engine-sc: ^5.8.0 => 5.8.0
    @mui/system:  5.8.0
    @mui/types:  7.1.3
    @mui/utils:  5.8.0
    @mui/x-date-pickers: ^5.0.0-alpha.6 => 5.0.0-alpha.6
    @types/react:  18.0.8
    react: ^18.1.0 => 18.1.0
    react-dom: ^18.1.0 => 18.1.0
```
</details>

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #4669 
Fixes #4552
Fixes #5194 

Fix community package components theme augmentation (style and prop overrides).

TL.DR.: The PR is quite big in change quantity, but the changes are more or less very similar among along the components

### CODE REVIEW

File: packages/x-date-pickers/src/ClockPicker/ClockNumber.tsx [hunk 1]
```diff
@@ -62,13 +83,7 @@ export function ClockNumber(props: ClockNumberProps) {
...
   return (
     <ClockNumberRoot
-      className={clsx(
-        {
-          [classes.selected]: selected,
-          [classes.disabled]: disabled,
-        },
-        className,
-      )}
+      className={clsx(className, classes.root)}
```
Comment (LukasTy) [inline packages/x-date-pickers/src/ClockPicker/ClockNumber.tsx:86]: L29 covers applying `selected` or `disabled` classes instead as in most other cases.

File: packages/x-date-pickers/src/CalendarPickerSkeleton/CalendarPickerSkeleton.tsx [hunk 2]
```diff
@@ -56,7 +56,7 @@ const CalendarPickerSkeletonWeek = styled('div', {
 
 const CalendarPickerSkeletonDay = styled(Skeleton, {
   name: 'MuiCalendarPickerSkeleton',
-  slot: 'Day',
+  slot: 'DaySkeleton',
```
Comment (LukasTy) [inline packages/x-date-pickers/src/CalendarPickerSkeleton/CalendarPickerSkeleton.tsx:59]: Align naming with className

File: packages/x-date-pickers/src/CalendarPickerSkeleton/CalendarPickerSkeleton.tsx [hunk 3]
```diff
@@ -103,7 +103,7 @@ function CalendarPickerSkeleton(props: CalendarPickerSkeletonProps) {
     name: 'MuiCalendarPickerSkeleton',
   });
 
-  const classes = useUtilityClasses(props);
+  const classes = useUtilityClasses(other);
```
Comment (LukasTy) [inline packages/x-date-pickers/src/CalendarPickerSkeleton/CalendarPickerSkeleton.tsx:106]: Fix to allow passing `classes` down via `defaultProps.classes`

File: packages/x-date-pickers/src/ClockPicker/ClockPointer.tsx [hunk 4]
```diff
@@ -43,59 +69,40 @@ const ClockPointerThumb = styled('div')<{
...
-      toAnimateTransform: false,
-      previousType: nextProps.type,
-    };
-  };
-
-  state = {
-    toAnimateTransform: false,
-    previousType: undefined,
-  };
+export function ClockPointer(inProps: ClockPointerProps) {
```
Comment (LukasTy) [inline packages/x-date-pickers/src/ClockPicker/ClockPointer.tsx:73]: Refactored to a function component and simplified the additional `state` stored in order to resolve when we `should animate` transition

File: packages/x-date-pickers/src/PickersDay/PickersDay.tsx [hunk 5]
```diff
@@ -90,9 +91,11 @@ const useUtilityClasses = (ownerState: PickersDayProps<any>) => {
     root: [
       'root',
       selected && 'selected',
+      disabled && 'disabled',
       !disableMargin && 'dayWithMargin',
       !disableHighlightToday && today && 'today',
       outsideCurrentMonth && showDaysOutsideCurrentMonth && 'dayOutsideMonth',
+      outsideCurrentMonth && !showDaysOutsideCurrentMonth && 'hiddenDaySpacingFiller',
```
Comment (LukasTy) [inline packages/x-date-pickers/src/PickersDay/PickersDay.tsx:98]: Was not possible overriding `hiddenDaySpacingFiller` slot as this class name was not being applied

File: packages/x-date-pickers/src/YearPicker/yearPickerClasses.ts [hunk 6]
```diff
@@ -2,7 +2,7 @@ import { generateUtilityClass, generateUtilityClasses } from '@mui/material';
 
 export interface YearPickerClasses {
   /** Styles applied to the root element. */
-  root?: string;
+  root: string;
```
Comment (LukasTy) [inline packages/x-date-pickers/src/YearPicker/yearPickerClasses.ts:5]: Align with other cases

File: packages/x-date-pickers/src/CalendarPicker/DayPicker.tsx [hunk 7]
```diff
@@ -74,17 +77,41 @@ export interface DayPickerProps<TDate>
...
+const useUtilityClasses = (
+  ownerState: DayPickerProps<any> & { classes?: Partial<DayPickerClasses> },
+) => {
+  const { classes } = ownerState;
+  const slots = {
+    header: ['header'],
+    weekDayLabel: ['weekDayLabel'],
+    loadingContainer: ['loadingContainer'],
+    slideTransition: ['slideTransition'],
+    weeksContainer: ['weeksContainer'],
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/CalendarPicker/DayPicker.tsx:88]: Not sure it's semantically the best. But, it's confusing the `week`/`weeks`

```suggestion
    monthContainer: ['monthContainer'],
```

File: packages/x-date-pickers/src/ClockPicker/ClockPointer.tsx [hunk 8]
```diff
@@ -43,59 +70,40 @@ const ClockPointerThumb = styled('div')<{
...
+  const props = useThemeProps({ props: inProps, name: 'MuiClockPointer' });
+  const previousType = React.useRef<ClockPickerView | null>(props.type);
+  React.useEffect(() => {
+    previousType.current = props.type;
+  }, [props.type]);
 
-  render() {
-    const { className, hasSelected, isInner, type, value, ...other } = this.props;
+  const { className, hasSelected, isInner, type, value, ...other } = props;
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/ClockPicker/ClockPointer.tsx:80]: Should it be put just after the `useThemeProps` to replace `props.type` by `type`?

File: packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx [hunk 9]
```diff
@@ -79,7 +85,11 @@ const TimePickerToolbarHourMinuteLabel = styled('div', {
 const TimePickerToolbarAmPmSelection = styled('div', {
   name: 'MuiTimePickerToolbar',
   slot: 'AmPmSelection',
-  overridesResolver: (props, styles) => styles.ampmSelection,
+  overridesResolver: (props, styles) => [
+    { [`.${timePickerToolbarClasses.ampmLabel}`]: styles.ampmLabel },
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx:90]: Did you forget the `&`?

File: packages/x-date-pickers/src/internals/components/PickersPopper.tsx [hunk 10]
```diff
@@ -49,13 +51,33 @@ export interface PickerPopperProps extends ExportedPickerPopperProps, ExportedPi
...
+  };
+
+  return composeClasses(slots, getPickersPopperUtilityClass, classes);
+};
+
+const PickersPopperRoot = styled(Popper, {
+  name: 'MuiPickersPopper',
+  slot: 'Root',
+  overridesResolver: (_, styles) => styles.root,
+})<{ ownerState: PickerPopperProps }>(({ theme }) => ({
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/internals/components/PickersPopper.tsx:72]: If the owner state is not used, does it bring something to specify it in typescript?
```suggestion
})(({ theme }) => ({
```

**Review by alexfauquette — APPROVED** [review]

**Comment by alexfauquette** [comment]
Maybe some of my comments are useless. It overall looks good, I think we can merge the modification, it will fix lot of style issues

File: packages/x-date-pickers/src/CalendarPickerSkeleton/CalendarPickerSkeleton.tsx (hunk 2 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/CalendarPickerSkeleton/CalendarPickerSkeleton.tsx:59]: Nope, it's just a consistency in `className` and `slot` fields.
I'm not 100% sure what does this slot name do, but the applied class name depends on how we generate them using `getCalendarPickerSkeletonUtilityClass`

File: packages/x-date-pickers/src/CalendarPickerSkeleton/CalendarPickerSkeleton.tsx (hunk 3 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/CalendarPickerSkeleton/CalendarPickerSkeleton.tsx:106]: Less changes I guess 🤷 
But good point, will update, does not seem to require those exquisite types as well. 🤔

File: packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx (hunk 9 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx:90]: In this particular case - nope. Will test if it is needed on next line. 👌

File: packages/x-date-pickers/src/CalendarPicker/DayPicker.tsx (hunk 7 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/CalendarPicker/DayPicker.tsx:88]: Very good suggestion 🙈 👍

File: packages/x-date-pickers/src/YearPicker/PickersYear.tsx [hunk 11]
```diff
@@ -100,64 +95,64 @@ const noop = () => {};
...
-    onFocus = noop,
-    onBlur = noop,
-    ...other
-  } = props;
-  const ref = React.useRef<HTMLButtonElement>(null);
-  const refHandle = useForkRef(ref, forwardedRef as React.Ref<HTMLButtonElement>);
-  const wrapperVariant = React.useContext(WrapperVariantContext);
+export const PickersYear = React.forwardRef<HTMLButtonElement, PickersYearProps>(
+  function PickersYear(props, forwardedRef) {
+    // TODO: add 'useThemeProps' once the component class names are aligned
```
[the remark this answers is not in the document]
Comment (LukasTy) [reply packages/x-date-pickers/src/YearPicker/PickersYear.tsx]: Yup, we can't easily use `useThemeProps` as it will complain about function name being different from `component` name, hence I decided to leave adding `defaultProps` support with a breaking change adjusting the component name at the same time

File: packages/x-date-pickers/src/CalendarPicker/PickersSlideTransition.tsx [hunk 12]
```diff
@@ -13,22 +18,39 @@ export interface SlideTransitionProps extends Omit<CSSTransitionProps, 'timeout'
...
+    { [`.${pickersSlideTransitionClasses['slideEnter-right']}`]: styles['slideEnter-right'] },
+    { [`.${pickersSlideTransitionClasses.slideEnterActive}`]: styles.slideEnterActive },
+    { [`.${pickersSlideTransitionClasses.slideExit}`]: styles.slideExit },
+    {
+      [`.${pickersSlideTransitionClasses['slideExitActiveLeft-left']}`]:
+        styles['slideExitActiveLeft-left'],
+    },
+    {
+      [`.${pickersSlideTransitionClasses['slideExitActiveLeft-right']}`]:
+        styles['slideExitActiveLeft-right'],
```
[the remark this answers is not in the document]
Comment (LukasTy) [reply packages/x-date-pickers/src/CalendarPicker/PickersSlideTransition.tsx:50]: Nope, `&` is only needed when we want to apply class on the same element as the root, but in this case these classes are going to the child element

File: packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx (hunk 9 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/TimePicker/TimePickerToolbar.tsx:90]: Did re-test, everything seems to be as needed to have correct overridden styles application. 🤞

File: packages/x-date-pickers/src/internals/components/PickersPopper.tsx (hunk 10 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/internals/components/PickersPopper.tsx:72]: The `ownerState` prop was already being passed to this element, hence I did probably add this type here because of that, but you are correct, we can ditch this type and prop as they are not used anyways. 👍
