### PR TITLE
[TreeView] Introduce a new `TreeItem2` component and a new `useTreeItem2` hook

### LINKED ISSUE #12284: [TreeView] TreeItem label is two levels of specificity instead of one
Some styles applied to TreeItem label are not applied (the class order is wrong).

You can check the example : https://codesandbox.io/s/gmailtreeview-material-demo-forked-s6z3q 

font size should be 45px.

Tested on alpha.29, thank you very much for doing Material-UI  ❤️

**Search keywords**:

### LINKED ISSUE #12287: [TreeView] Use new DX patterns (hooks and slots) for `TreeItem` customization
Currently, the customization of the TreeView is done mainly with the `ContentComponent` and `ContentProps` props on the `TreeItem` component.

We want to replace those props with a set of slots (`slots.label`, `slots.iconContainer`, ...) and with a `useTreeItemHook` that allows advanced customization.

This should also solve #12284 by not having the style of the label defined at the content level.

**Search keywords**:

### PR DESCRIPTION
**Pull request by flaviendelangle**
Closes #12287
Fixes #12284

Waiting for #12231 to have a coherent "RichTreeView - Customization" doc page

### CODE REVIEW

File: docs/data/tree-view/simple-tree-view/customization/IconExpansionTreeView.js [hunk 1]
```diff
@@ -1,76 +1,37 @@
 import * as React from 'react';
```
Comment (flaviendelangle) [inline docs/data/tree-view/simple-tree-view/customization/IconExpansionTreeView.js:1]: I migrated this example to the new API to give an example of what it would look like

**BUT** we should not merge it like this, we should keep the old example until the new API is public

File: docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.tsx [hunk 2]
```diff
@@ -1,93 +1,72 @@
 import * as React from 'react';
```
Comment (flaviendelangle) [inline docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.tsx:1]: I migrated this example to the new API to give an example of what it would look like

**BUT** we should not merge it like this, we should keep the old example until the new API is public

File: docs/data/tree-view/simple-tree-view/customization/CustomizedTreeView.tsx [hunk 3]
```diff
@@ -130,6 +134,9 @@ const StyledTreeItem = React.forwardRef(function StyledTreeItem(
 
   return (
     <StyledTreeItemRoot
+      slots={{
```
Comment (flaviendelangle) [inline docs/data/tree-view/simple-tree-view/customization/CustomizedTreeView.tsx:137]: One could argue that using `useTreeItem` and re-building the UI is better here instead of passing everything inside the label, but it would complexity the demo so I'm in favor of keeping it like this

File: docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js [hunk 4]
```diff
@@ -1,84 +1,70 @@
...
-          {label[0]}
-        </Avatar>
-        <Typography component="div" className={classes.label}>
-          {label}
-        </Typography>
-      </Box>
-    </CustomContentRoot>
+    <TreeItemProvider nodeId={nodeId}>
+      <TreeItemNextRoot {...getRootProps(other)}>
+        <CustomTreeItemContent {...getContentProps()} ownerState={status}>
```
Comment (flaviendelangle) [inline docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js:44]: I followed the Base UI approach, so the `ownerState` is not part of the `getContentProps`, which make sense when you use a custom component for the DOM structure because it will probably not want this `ownerState`.
But if you use the built-in component or one derived from it (like `CustomTreeItemContent` here), then you do need to pass the `ownerState` in order to have the variants.

And it gets even worse if we require the `ownerState` on all the other slots (which we probably should if we want to properly support `styleOverrides`.

@michaldudak what would be your take on this one?
I feel like our needs are not exactly the same as the one from a Base UI users, most people will do things like in this demo, i.e: use `useTreeItem` to play Tetris with the blocks of the `TreeItem`, maybe remove one, replace one but most likely not all of them.

Comment (flaviendelangle) [reply docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js:44]: By the way, the same applies with classes, in this demo, the `CustomTreeItemContent` never receives the classes like `treeItemClasses.selected` because it's apply in the `useSlotProps`.
So I moved all the styling logic to `variants` to not use those classes for our own styling, which means that this demo work and people can manually pass the classes if **they** need them.

File: docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js [hunk 5]
```diff
@@ -1,84 +1,70 @@
...
-          })}
-        >
-          {label[0]}
-        </Avatar>
-        <Typography component="div" className={classes.label}>
-          {label}
-        </Typography>
-      </Box>
-    </CustomContentRoot>
+    <TreeItemProvider nodeId={nodeId}>
```
Comment (flaviendelangle) [inline docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js:42]: This new provider is useful on `SimpleTreeView` to register the JSX items at the tree view level.
And in the future it will also contain potential drag&drop context if needed of stuff like that.

File: packages/x-tree-view/src/internals/useTreeView/useTreeView.ts [hunk 6]
```diff
@@ -88,42 +89,46 @@ export const useTreeView = <Plugins extends readonly TreeViewPlugin<TreeViewAnyP
...
-      },
+      contentRef: finalContentRef,
+      rootRef: finalRootRef,
     };
   };
 
+  const itemWrappers = plugins
+    .map((plugin) => plugin.wrapItem)
+    .filter((wrapItem): wrapItem is TreeItemWrapper => !!wrapItem);
+  contextValue.wrapItem = ({ nodeId, children }) => {
```
Comment (flaviendelangle) [inline packages/x-tree-view/src/internals/useTreeView/useTreeView.ts:123]: I moved `wrapItem` outside of `runItemPlugins` / `itemPlugin` so that the `TreeItemProvider` can wrap items without executing `runItemPlugins`.

Before, we executed `runItemPlugins` in `TreeItem` and then used the returned `wrapItem` function to wrap the JSX element.
But when doing a custom field, it's a weird DX to do:

```tsx
const node = (
  <Root>
    <Content>STUFF</Content>
  </Root>
);

return wrapItem(node);
```

So I replaced it with: 

```tsx
return (
  <TreeItemProvider nodeId={nodeId}r>
    <Root>
      <Content>STUFF</Content>
    </Root>
);
```

Which means `TreeItemProvider` is not aware of the value returned by `runItemPlugins`, thus the split.

File: packages/x-tree-view/src/internals/plugins/useTreeViewJSXNodes/useTreeViewJSXNodes.tsx [hunk 7]
```diff
@@ -116,25 +124,22 @@ const useTreeViewJSXNodesItemPlugin: TreeViewItemPlugin = ({ props, ref }) => {
...
         nodeId,
-        (contentRef.current?.textContent ?? '').substring(0, 1).toLowerCase(),
+        (pluginContentRef.current?.textContent ?? '').substring(0, 1).toLowerCase(),
       );
     }
     return undefined;
   }, [instance, nodeId, label]);
 
   return {
-    props: {
```
Comment (flaviendelangle) [inline packages/x-tree-view/src/internals/plugins/useTreeViewJSXNodes/useTreeViewJSXNodes.tsx:126]: I refactored this part so that it's not aware of the props structure of the components.
Because the old `TreeItem` has its content ref in `props.ContentProps.contentRef` and the new one has its content ref in `slotProps.content.ref` 

So now the plugin just returns the ref and the item component is responsible for merging.

It means that plugins can no longer process the other props, but I think we can re-evaluate once we have an actual need and not over engineer.

File: docs/data/tree-view/simple-tree-view/customization/GmailTreeView.tsx [hunk 8]
```diff
@@ -22,96 +32,130 @@ declare module 'react' {
...
   color?: string;
   colorForDarkMode?: string;
   labelIcon: React.ElementType<SvgIconProps>;
   labelInfo?: string;
-  labelText: string;
-};
+}
 
-const StyledTreeItemRoot = styled(TreeItem)(({ theme }) => ({
+const CustomTreeItemRoot = styled(TreeItemNextRoot)(({ theme }) => ({
```
Comment (flaviendelangle) [inline docs/data/tree-view/simple-tree-view/customization/GmailTreeView.tsx:44]: For this one we have several solutions:

1. We keep putting everything in the label, it keeps the demo short but it means that we are telling people to pass a `React.ReactNode` to the label, which only works on `SimpleTreeView`, maybe educating people to always pass a string is better

2. We use `useTreeView` and create wrappers for each element

3. We use `useTreeView` and create wrapper only for the root, we apply the styling like @noraleonte did, based on the classes. This will require to manually set classes to the slots because (unless we do differently than Base UI), the MUI X classes are not applied when using the headless API. See https://github.com/mui/mui-x/pull/11721/files#r1492769672 for context

File: docs/data/tree-view/simple-tree-view/customization/GmailTreeView.js [hunk 9]
```diff
@@ -13,85 +13,129 @@ import ArrowDropDownIcon from '@mui/icons-material/ArrowDropDown';
...
-          }}
+    <TreeItemProvider nodeId={nodeId}>
+      <CustomTreeItemRoot {...getRootProps({ ...other, style })}>
+        <CustomTreeItemContent
+          {...getContentProps({
+            className: clsx('content', {
+              expanded: status.expanded,
+              selected: status.selected,
+              focused: status.focused,
+            }),
```
Comment (alexfauquette) [inline docs/data/tree-view/simple-tree-view/customization/GmailTreeView.js:106]: Out of context: This kind of behavior will need some educational efforts.

I went to [base docs](https://mui.com/base-ui/getting-started/customization/#creating-custom-components-using-hooks) to check what `getXxxxProps` take as an argument. I assume other dev not familiar with with base might wonder what are those functions

Comment (flaviendelangle) [reply docs/data/tree-view/simple-tree-view/customization/GmailTreeView.js:106]: Yep, I don't want to rush the merging of this PR because it clearly needs to come with some good doc on the Base UI side and backlinks to it on our side.

File: docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.tsx [hunk 10]
```diff
@@ -1,95 +1,74 @@
...
-    label,
+    id,
     nodeId,
-    icon: iconProp,
-    expansionIcon,
-    displayIcon,
+    label,
+    children,
+    slots = {},
+    slotProps = {},
```
[the remark this answers is not in the document]
Comment (alexfauquette) [reply docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.tsx:32]: For me `slots` is ourtool to comunicate with dev because we lack of context about what they are doing. Devs have the product context so they should pass directly their custom icons to the component in a more semantic friendly way.

```diff
- <TreeItemIcon status={status} slots={slots} />
+ <TreeItemIcon status={status} slots={{ collapsedIcon: CustomIcon }} />
```

I they need to customize them at the `CustomTreeItem` level, I would encourage them to be semantically closer to their usecase. For example the VSCode would be

```jsx
<CustomTreeItem nodeId="1" label="DatePicker">
  <CustomTreeItem nodeId="2" label="index.ts" fileType="ts" />
  <CustomTreeItem nodeId="3" label="DatePicker.tsx"  fileType="tsx">
  <CustomTreeItem nodeId="6" label="DatePicker.test.ts" fileType="test" />
</CustomTreeItem>
```

With the `CustomTreeItem` slots `endIcon` computed according to the `fileType` (or the label extension)

image

[the remark this answers is not in the document]
Comment (alexfauquette) [reply docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.tsx:32]: perfect :+1;

File: docs/data/tree-view/rich-tree-view/customization/customization.md [hunk 11]
```diff
@@ -0,0 +1,29 @@
...
+
+Use the `label` slot to customize the Tree Item label or to replace it with an entirely custom component.
+
+The `slotProps` prop allows you to pass props to the default label component:
+
+:::warning
+TODO
+:::
+
+The `slots` prop allows you to replace the default label with your own component.
```
Comment (flaviendelangle) [inline docs/data/tree-view/rich-tree-view/customization/customization.md:26]: I added this demo here because it make no sense on the `SimpleTreeView`

I think it can be a good example for `slots.label` until we have a built-in edition

File: docs/data/tree-view/simple-tree-view/customization/GmailTreeView.js (hunk 9 above)
Comment (michaldudak) [reply docs/data/tree-view/simple-tree-view/customization/GmailTreeView.js:104]: FYI, as we're [changing the API](https://www.notion.so/mui-org/base-ui-Customization-API-3996f854a02943ca8c34ccbaac80e6dc) of the Base UI components and hooks, we're limiting the contributions to the current version of the library. Going forward, Base UI will be developed in its own repo (but we won't remove the existing sources from the Core repo, as it's used in several places).

File: docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js (hunk 4 above)
Comment (michaldudak) [reply docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js:36]: I'm wondering why do you need both a component (TreeItemNextContent) and a hook. Doesn't the component handle setting its own props?

Comment (flaviendelangle) [reply docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js:36]: `useTreeItem` is the hook to build you own `TreeItemNext`, not `TreeItemNextContent`.

We are trying to provide a good DX for people who need to create custom versions of the `TreeItemNext` component.
The idea here is that slots are often not enough, they don't allow you to easily swap two elements or to insert an element between two others ([this doc example](https://deploy-preview-11721--material-ui-x.netlify.app/x/react-tree-view/simple-tree-view/customization/#headless-api)).
So we are providing a `useTreeItem` hook that allows you to create your own component.

We are trying to make the barrier to entry low for this new hook, because IMHO it will be useful for simple customization (the demo linked above is a good example), and not just for people create a whole new design system.
So being able to easily re-use the blocks used by `TreeItemNext` (`TreeItemNextContent`, `TreeItemNextLabel`, etc...) would be quite important.

Comment (flaviendelangle) [reply docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js:36]: I'm wondering how the DX should look like for the use-cases.
I'm trying to create something consistent with Base as much as possible to avoid ending with yet another DX for customization.

Comment (flaviendelangle) [reply docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js:36]: An alternative would be that `TreeViewNextContent` gets the `status` as a prop and uses it instead of the `ownerState` for its styling, with a `shouldForwardProp` to avoid passing it to the DOM.

The main downside here is that people creating a custom component that receives `getContentProps` should make sure not to forward to the DOM.
But it would only impact advanced customizations

Comment (flaviendelangle) [reply docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js]: https://github.com/mui/mui-x/pull/11721/commits/caeeb8abe22506c283360e7a141f1cbfcfbd2a7d

@michaldudak do you think it's a good approach?

Comment (michaldudak) [reply docs/data/tree-view/simple-tree-view/customization/CustomContentTreeView.js]: > I'm trying to create something consistent with Base as much as possible to avoid ending with yet another DX for customization.

With the component-per-node approach, Base UI won't use `ownerState` as currently. It'll be only used as a callback to the render prop if you want to override the component being rendered (it won't be passed to subcomponents by their parents).

> https://github.com/mui/mui-x/commit/caeeb8abe22506c283360e7a141f1cbfcfbd2a7d
> @michaldudak do you think it's a good approach?

It does look better to me.

File: packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts [hunk 12]
```diff
@@ -0,0 +1,140 @@
...
+}
+
+export type UseTreeItem2LabelSlotProps<ExternalProps = {}> = ExternalProps &
+  UseTreeItem2LabelSlotOwnProps;
+
+export interface UseTreeItem2GroupTransitionSlotOwnProps {
+  unmountOnExit: boolean;
+  in: boolean;
+  component: 'ul';
+  role: 'GroupTransition';
```
Comment (LukasTy) [inline packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts:72]:
```suggestion
  role: 'group';
```

File: packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts [hunk 13]
```diff
@@ -0,0 +1,140 @@
...
+  expanded: boolean;
+  focused: boolean;
+  selected: boolean;
+  disabled: boolean;
+}
+
+export interface UseTreeItem2ReturnValue<TPlugins extends readonly TreeViewAnyPluginSignature[]> {
+  /**
+   * Resolver for the root slot's props.
+   * @param {ExternalProps} externalProps additional props for the root slot
```
Comment (LukasTy) [inline packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts:90]:
```suggestion
   * @param {ExternalProps} externalProps Additional props for the root slot.
```

File: packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts [hunk 14]
```diff
@@ -0,0 +1,140 @@
...
+   * @returns {UseTreeItem2RootSlotProps<ExternalProps>} props that should be spread on the root slot
```
Comment (LukasTy) [inline packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts:91]:
```suggestion
   * @returns {UseTreeItem2RootSlotProps<ExternalProps>} Props that should be spread on the root slot.
```

File: packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts [hunk 15]
```diff
@@ -0,0 +1,140 @@
...
+   */
+  getRootProps: <ExternalProps extends Record<string, any> = {}>(
+    externalProps?: ExternalProps,
+  ) => UseTreeItem2RootSlotProps<ExternalProps>;
+  /**
+   * Resolver for the content slot's props.
+   * @param {ExternalProps} externalProps additional props for the content slot
```
Comment (LukasTy) [inline packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts:98]:
```suggestion
   * @param {ExternalProps} externalProps Additional props for the content slot.
```

File: packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts [hunk 16]
```diff
@@ -0,0 +1,140 @@
...
+   * @returns {UseTreeItem2ContentSlotProps<ExternalProps>} props that should be spread on the content slot
```
Comment (LukasTy) [inline packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts:99]:
```suggestion
   * @returns {UseTreeItem2ContentSlotProps<ExternalProps>} Props that should be spread on the content slot.
```

File: packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts [hunk 17]
```diff
@@ -0,0 +1,140 @@
...
+   */
+  getContentProps: <ExternalProps extends Record<string, any> = {}>(
+    externalProps?: ExternalProps,
+  ) => UseTreeItem2ContentSlotProps<ExternalProps>;
+  /**
+   * Resolver for the label slot's props.
+   * @param {ExternalProps} externalProps additional props for the label slot
```
Comment (LukasTy) [inline packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts:106]:
```suggestion
   * @param {ExternalProps} externalProps Additional props for the label slot.
```

File: packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts [hunk 18]
```diff
@@ -0,0 +1,140 @@
...
+   * @returns {UseTreeItem2LabelSlotProps<ExternalProps>} props that should be spread on the label slot
```
Comment (LukasTy) [inline packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts:107]:
```suggestion
   * @returns {UseTreeItem2LabelSlotProps<ExternalProps>} Props that should be spread on the label slot.
```

File: packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts [hunk 19]
```diff
@@ -0,0 +1,140 @@
...
+   */
+  getLabelProps: <ExternalProps extends Record<string, any> = {}>(
+    externalProps?: ExternalProps,
+  ) => UseTreeItem2LabelSlotProps<ExternalProps>;
+  /**
+   * Resolver for the iconContainer slot's props.
+   * @param {ExternalProps} externalProps additional props for the iconContainer slot
```
Comment (LukasTy) [inline packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts:114]:
```suggestion
   * @param {ExternalProps} externalProps Additional props for the iconContainer slot.
```

File: packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts [hunk 20]
```diff
@@ -0,0 +1,140 @@
...
+   * @returns {UseTreeItemIconContainerSlotProps<ExternalProps>} props that should be spread on the iconContainer slot
```
Comment (LukasTy) [inline packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts:115]:
```suggestion
   * @returns {UseTreeItemIconContainerSlotProps<ExternalProps>} Props that should be spread on the iconContainer slot.
```

File: packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts [hunk 21]
```diff
@@ -0,0 +1,140 @@
...
+   */
+  getIconContainerProps: <ExternalProps extends Record<string, any> = {}>(
+    externalProps?: ExternalProps,
+  ) => UseTreeItemIconContainerSlotProps<ExternalProps>;
+  /**
+   * Resolver for the GroupTransition slot's props.
+   * @param {ExternalProps} externalProps additional props for the GroupTransition slot
```
Comment (LukasTy) [inline packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts:122]:
```suggestion
   * @param {ExternalProps} externalProps Additional props for the GroupTransition slot.
```

File: packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts [hunk 22]
```diff
@@ -0,0 +1,140 @@
...
+   * @returns {UseTreeItem2GroupTransitionSlotProps<ExternalProps>} props that should be spread on the GroupTransition slot
```
Comment (LukasTy) [inline packages/x-tree-view/src/useTreeItem2/useTreeItem2.types.ts:123]:
```suggestion
   * @returns {UseTreeItem2GroupTransitionSlotProps<ExternalProps>} Props that should be spread on the GroupTransition slot.
```

File: scripts/x-tree-view.exports.json [hunk 23]
```diff
@@ -23,6 +23,21 @@
...
+  { "name": "TreeItem2IconSlotProps", "kind": "Interface" },
+  { "name": "TreeItem2IconSlots", "kind": "Interface" },
+  { "name": "TreeItem2Label", "kind": "Variable" },
+  { "name": "TreeItem2Props", "kind": "Interface" },
+  { "name": "TreeItem2Provider", "kind": "Function" },
+  { "name": "TreeItem2ProviderProps", "kind": "Interface" },
+  { "name": "TreeItem2Root", "kind": "Variable" },
+  { "name": "TreeItem2SlotProps", "kind": "Interface" },
+  { "name": "TreeItem2Slots", "kind": "Interface" },
+  { "name": "TreeItem2TransitionGroup", "kind": "Variable" },
```
Comment (LukasTy) [inline scripts/x-tree-view.exports.json:40]: So, is it `GroupTransition` or `TransitionGroup`? 😄 🙈

**Review by LukasTy — COMMENTED** [review]
Great work! 👏 
Leaving a bit of mostly nitpick comments. 🙈

File: docs/data/tree-view/rich-tree-view/customization/LabelSlots.tsx [hunk 24]
```diff
@@ -0,0 +1,150 @@
+import * as React from 'react';
+import {
+  TreeItem2,
+  TreeItem2Label,
+  TreeItem2Props,
+} from '@mui/x-tree-view/TreeItem2';
+import { RichTreeView, TreeViewBaseItem } from '@mui/x-tree-view';
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply docs/data/tree-view/rich-tree-view/customization/LabelSlots.tsx:7]: :sob: If Webstorm could please stop using those root imports

[the remark this answers is not in the document]
Comment (flaviendelangle) [reply docs/data/tree-view/rich-tree-view/customization/LabelSlots.tsx:7]: Fixed

File: docs/data/tree-view/rich-tree-view/customization/LabelSlots.tsx [hunk 25]
```diff
@@ -0,0 +1,150 @@
...
+
+function CustomLabel(props: CustomLabelProps) {
+  const { children, onChange, ...other } = props;
+
+  const [isEditing, setIsEditing] = React.useState<boolean>(false);
+  const [value, setValue] = React.useState('');
+  const editingLabelRef = React.useRef<HTMLInputElement>(null);
+
+  const handleLabelDoubleClick = (event: React.MouseEvent) => {
+    event.stopPropagation();
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply docs/data/tree-view/rich-tree-view/customization/LabelSlots.tsx:23]: It was to stop the expansion when it has children, but it's a fail :laughing:

File: docs/data/tree-view/rich-tree-view/customization/LabelSlots.tsx [hunk 26]
```diff
@@ -0,0 +1,150 @@
...
+    if (event.key === 'Enter') {
+      event.stopPropagation();
+      setIsEditing(false);
+      onChange(value);
+    }
+  };
+
+  React.useEffect(() => {
+    if (isEditing) {
+      editingLabelRef.current?.focus();
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply docs/data/tree-view/rich-tree-view/customization/LabelSlots.tsx:42]: I'll wait for #12226 before spending to much time on the focus here :laughing:

File: scripts/x-tree-view.exports.json (hunk 23 above)
Comment (flaviendelangle) [reply scripts/x-tree-view.exports.json:40]: :see_no_evil:

File: packages/x-tree-view/src/TreeItem2/TreeItem2.types.ts [hunk 27]
```diff
@@ -0,0 +1,69 @@
...
+   */
+  slots?: TreeItem2Slots;
+  /**
+   * The props used for each component slot.
+   * @default {}
+   */
+  slotProps?: TreeItem2SlotProps;
+  /**
+   * This prop isn't supported.
+   * Use the `onNodeFocus` callback on the tree if you need to monitor a node's focus.
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-tree-view/src/TreeItem2/TreeItem2.types.ts:64]: It was like this on the lab
IMHO they did this so that people passing a `onFocus` to the item have a TS error but I don't really see the point tbh
I just kept it for API consistency for `TreeItem`

File: packages/x-tree-view/src/TreeItem2Icon/TreeItem2Icon.types.ts [hunk 28]
```diff
@@ -0,0 +1,44 @@
...
+   * Overridable component slots.
+   * @default {}
+   */
+  slots?: TreeItem2IconSlots;
+  /**
+   * The props used for each component slot.
+   * @default {}
+   */
+  slotProps?: TreeItem2IconSlotProps;
+  fallbackIcon?: React.ReactNode;
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-tree-view/src/TreeItem2Icon/TreeItem2Icon.types.ts:43]: Nop, it's a leftover from a previous implementation, removed

File: docs/data/tree-view/rich-tree-view/customization/LabelSlots.tsx [hunk 29]
```diff
@@ -0,0 +1,150 @@
...
+  const [value, setValue] = React.useState('');
+  const editingLabelRef = React.useRef<HTMLInputElement>(null);
+
+  const handleLabelDoubleClick = (event: React.MouseEvent) => {
+    event.stopPropagation();
+    setIsEditing(true);
+    setValue(children);
+  };
+
+  const handleEditingLabelChange = (event: React.ChangeEvent<HTMLInputElement>) => {
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply docs/data/tree-view/rich-tree-view/customization/LabelSlots.tsx:32]: I don't think this a memoization worth doing since we are directly passing the prop to a DOM element,

File: docs/data/tree-view/rich-tree-view/customization/LabelSlots.tsx (hunk 25 above)
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply docs/data/tree-view/rich-tree-view/customization/LabelSlots.tsx]: I changed the approach to only expand when clicking the icon, it's probably a lot better when using editing
And it raises a question for our future built-in edition: should we automatically switch the expansion trigger to the icon when editing?

File: packages/x-tree-view/src/TreeItem2/TreeItem2.types.ts (hunk 27 above)
[the remark this answers is not in the document]
Comment (LukasTy) [reply packages/x-tree-view/src/TreeItem2/TreeItem2.types.ts:64]: Gotcha. Makes sense. 🤔

**Review by LukasTy — APPROVED** [review]
Great improvement! 👏 💯
