### PR TITLE
[DatePicker] Add keyboard support for selecting day, month, and year

### LINKED ISSUE #20632: [pickers] DatePicker cannot select date with VoiceOver and Full Keyboard Access in Pass Through mode
### Steps to reproduce

Steps:
using iOS phone with Bluetooth keyboard
1. surf to https://mui.com/x/react-date-pickers/date-picker/ (I used safari)
2. find any date picker showing month as a matrix of days
3. in iOS accessibility settings turn on Full Keyboard Access . note Pass Through mode shortcut
4. turn on VoiceOver
5. date matrix can be navigated with arrow keys and date can be selected with space/return. Great
6. turn on Pass Through mode using the shortcut (default Ctrl Opt Cmd P)
7. navigation still works with arrow keys but space/return does NOT select a date

for some reason my Cordova Mui v5 app does not work properly with FKA On and Pass Through mode Off - for example onKeyDown events do not fire. This is a shame as I would prefer that it just worked. Its unclear why it does not work

Pass Through mode On seemed to fix everything until I discovered that I could not select a date using the BT keyboard

### Current behavior

_No response_

### Expected behavior

_No response_

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: VoiceOver Full Keyboard Access Pass Through mode

### PR DESCRIPTION
**Pull request by michelengelen**
This PR fixes an accessibility issue where users on iOS with VoiceOver and a Bluetooth keyboard were unable to select dates using the Space or Enter keys when 'Pass Through' mode was active.

While arrow key navigation worked (due to explicit onKeyDown handling), the selection logic relied on the browser's default behavior of converting Space/Enter into a click event on a focused button. In iOS 'Pass Through' mode, this default event synthesis often fails to reach the React event system, even though specific key events (like arrows) are still dispatched.

Added explicit handling for Enter and Space keys within the onKeyDown listeners of the calendar components. This ensures that the selection callback is triggered directly by the key event, mirroring how navigation is already handled.

Fixes #20632

### CODE REVIEW

File: packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx [hunk 1]
```diff
@@ -270,6 +270,11 @@ export const MonthCalendar = React.forwardRef(function MonthCalendar(
       case 'ArrowRight':
         focusMonth((monthsInYear + month + (isRtl ? -1 : 1)) % monthsInYear);
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/MonthCalendar/MonthCalendar.tsx]:
```suggestion
```
