### PR TITLE
[TimePicker] Fix time validation when current date is null

### LINKED ISSUE #4866: [TimePicker] Min/max is not respected if it doesn't have a default value
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

the time range min/max isn't respected for a  Time component that has the value = null;
it's only after first selected a time that the time range is respected.

https://stackblitz.com/edit/react-ix5es1?file=demo.tsx

### Expected behavior 🤔

should always respect the min/max

### Steps to reproduce 🕹

Steps:

1. https://stackblitz.com/edit/react-ix5es1?file=demo.tsx
2. click to add time
3. you will see you it displays all the time options and not limited to the min/max

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #4866

When we migrated the project, there was 0 validation on `ClockPicker` if the current time was null.
In #4726 I applied the value validity check (is hours "5" valid).
And in this PR I apply the full date validity (is 24th of May 2022 at 5PM valid)

## What's next ?

- Refacto `ClockPicker.test.tsx` to group the validity tests

### CODE REVIEW

File: packages/x-date-pickers/src/ClockPicker/ClockPicker.tsx [hunk 1]
```diff
@@ -258,8 +258,11 @@ export const ClockPicker = React.forwardRef(function ClockPicker<TDate extends u
 
   const now = useNow<TDate>();
   const utils = useUtils<TDate>();
-  const midnight = utils.setSeconds(utils.setMinutes(utils.setHours(now, 0), 0), 0);
-  const dateOrMidnight = date || midnight;
+
+  const dateOrMidnight = React.useMemo(
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/ClockPicker/ClockPicker.tsx:262]: Without this `useMemo`, the `useCallback` and `useMemo` below are useless when `date` is null

File: packages/x-date-pickers/src/ClockPicker/ClockPicker.tsx [hunk 2]
```diff
@@ -298,36 +301,23 @@ export const ClockPicker = React.forwardRef(function ClockPicker<TDate extends u
       switch (viewType) {
         case 'hours': {
           const value = convertValueToMeridiem(rawValue, meridiemMode, ampm);
-
-          if (date == null) {
-            return !isValidValue(value);
-          }
-
-          const dateWithNewHours = utils.setHours(date, value);
+          const dateWithNewHours = utils.setHours(dateOrMidnight, value);
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/ClockPicker/ClockPicker.tsx:304]: `dateOrMidnight` is the variable used on the `onChange` callbacks.
So using the same value should keep the validation coherent.

Even if `disableIgnoringDatePartForTimeValidation` is set to `true` (i.e: when used in `DateTimePicker` and there is a `minDateTime` or `maxDateTime` provided).

**Review by alexfauquette — APPROVED** [review]
I was looking for a way to handle minutes/seconds because tests looked strange. 

But I don't think we have a better way expect a doc page on validation

**Comment by flaviendelangle** [comment]
> I was looking for a way to handle minutes/seconds because tests looked strange.

What was looking strange in the tests ?

**Comment by alexfauquette** [comment]
That selecting minutes to 20 is impossible when `minValue=12:15` and `maxValue=15:45`

**Comment by flaviendelangle** [comment]
Indeed, maybe we will find a better behavior later
