### PR TITLE
[DataGrid] Fix undefined slot values

### LINKED ISSUE #10933: NoRowsOverlay slot throws when passed undefined but types allow it
### Search keywords

datagrid norowsoverlay

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: [(required)](https://codesandbox.io/s/data-grid-no-rows-throws-when-undefined-zklnsw?file=/src/Demo.tsx)

Steps:
1. Make a grid with no rows
2. Pass NoRowsOverlay slot with undefined

### Current behavior

MUI throws error and crashes

### Expected behavior

MUI just renders the default norows component

### Context

We are conditionally passing this slot based on some other data in the component. Previously this worked fine but now crashes in v6.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 64.44 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nodenv/versions/18.12.1/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.5.1 - ~/.nodenv/versions/18.12.1/bin/npm
    pnpm: 6.32.11 - ~/.nodenv/versions/18.12.1/bin/pnpm
  Managers:
    Cargo: 1.63.0 - ~/.cargo/bin/cargo
    Homebrew: 4.1.18 - /opt/homebrew/bin/brew
    pip3: 22.2.2 - ~/.pyenv/shims/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.40.0 - /opt/homebrew/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.1.2 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    VirtualBox: 7.0.8 - /usr/local/bin/vboxmanage
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
  IDEs:
    VSCode: 1.84.1 - /opt/homebrew/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.19.2 - /opt/homebrew/bin/go
    Perl: 5.30.3 - /usr/bin/perl
    Python: 3.9.9 - /Users/scamden/.pyenv/shims/python
    Python3: 3.9.9 - /Users/scamden/.pyenv/shims/python3
    Ruby: 2.6.10 - /usr/bin/ruby
    Rust: 1.63.0 - /Users/scamden/.cargo/bin/rustc
  Databases:
    PostgreSQL: 14.8 - /opt/homebrew/opt/postgresql@14/bin/postgres
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 119.0.6045.105
    Safari: 17.1
```
</details>

### Order ID or Support key 💳 (optional)

77647

### PR DESCRIPTION
**Pull request by romgrk**
Closes #10933

Allow passing `undefined` as a slot value.

### CODE REVIEW

File: packages/grid/x-data-grid/src/internals/utils/computeSlots.ts [hunk 1]
```diff
@@ -18,5 +18,14 @@ export function computeSlots<SlotComponents extends object>({
...
+  const result = { ...defaultSlots };
+  Object.keys(overrides).forEach((key) => {
+    const k = key as keyof typeof overrides;
+
+    if (overrides[k] !== undefined) {
+      result[k] = overrides[k] as any;
+    }
+  });
+
+  return result;
```
Comment (scamden) [inline packages/grid/x-data-grid/src/internals/utils/computeSlots.ts:30]: thanks for the fix! little bit less boilerplatey suggestion if you want:

```suggestion
  return Object.fromEntries(Object.entries(defaultSlots).filter([k] => k !== undefined))
```

Comment (romgrk) [reply packages/grid/x-data-grid/src/internals/utils/computeSlots.ts:30]: Doesn't seem equivalent. And the result needs to be set to the default slot unless an override is provided.

Comment (scamden) [reply packages/grid/x-data-grid/src/internals/utils/computeSlots.ts:30]: updated to be correct :)

Comment (scamden) [reply packages/grid/x-data-grid/src/internals/utils/computeSlots.ts:30]: `Object.fromEntries(Object.entries(overrides).filter(fn)` is basically just a `pickBy` pattern, so if you all have lodash or a similar util you could reduce this code even a little bit further

**Review by cherniavskii — APPROVED** [review]
