### PR TITLE
[DataGrid] Correct the type for single digit edited number value

### LINKED ISSUE #9281: [question] [maybe bug] single digit number wrongly typed as string even if column type is number
### Order ID or Support key 💳 (optional)

68257

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

https://codesandbox.io/s/currying-night-xpfv64?file=/demo.tsx

```
const columns = [
  {
    field: "userName",
    type: "string",
    editable: true
  },
  {
    field: "age",
    type: "number",
    editable: true
  }
];
```

even if "age" column is typed as "number",
when I type with keyboard only "1" or "2" or something single degit number.("10" or "11" is fine)
MUI X Grid takes it as "string" wrongly.

How can I get number As it it's expected.

https://github.com/mui/mui-x/assets/11783802/1768d73f-af6f-46f1-8078-dff94acc5c23

### Your environment 🌎

  System:
    OS: macOS 12.4
  Binaries:
    Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
    Yarn: Not Found
    npm: 9.6.7 - ~/develop/nitoel/tenant/supplier-frontend/node_modules/.bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @emotion/react: ^11.9.3 => 11.9.3
    @emotion/styled: ^11.10.4 => 11.10.4
    @mui/core-downloads-tracker:  5.10.13
    @mui/icons-material: ^5.10.9 => 5.10.9
    @mui/material: ^5.10.13 => 5.10.13
    @mui/styled-engine:  5.13.2
    @mui/system:  5.13.2
    @mui/utils:  5.13.1
    @mui/x-data-grid:  6.6.0
    @mui/x-data-grid-premium: ^6.6.0 => 6.6.0
    @mui/x-data-grid-pro:  6.6.0
    @mui/x-license-pro:  6.6.0
    @types/react: 18.0.14 => 18.0.14
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.7.4 => 4.7.4

### PR DESCRIPTION
**Pull request by MBilalShafi**
Fix #9281
Context: https://github.com/mui/mui-x/issues/9281#issuecomment-1584309343

Before: https://codesandbox.io/s/currying-night-xpfv64?file=/demo.tsx
After: https://codesandbox.io/s/youthful-resonance-n2ypdt?file=/demo.tsx

### CODE REVIEW

File: packages/grid/x-data-grid/src/hooks/features/editing/useGridCellEditing.ts [hunk 1]
```diff
@@ -179,7 +179,11 @@ export const useGridCellEditing = (
         }
 
         if (reason) {
-          const newParams: GridCellEditStartParams = { ...params, reason, key: event.key };
+          const newParams: GridCellEditStartParams = {
+            ...params,
+            reason,
+            key: params.colDef.type === 'number' ? Number(event.key) : event.key,
+          };
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/features/editing/useGridCellEditing.ts:186]: Shouldn't we put the logic for this later in the process? Would this be valid on backspace?

Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/hooks/features/editing/useGridCellEditing.ts:186]: The `colDef` was already available here and I didn't want to pass it along or load it using selectors down the tree. To me, backspace works fine, did you face some issue?

**Comment by mcl-laura** [comment]
Using the same ["after" sandbox](https://codesandbox.io/s/youthful-resonance-n2ypdt?file=/demo.tsx), if the value that is typed is 0, the cell doesn't immediately take in that value, it only goes into Edit Mode. It should work as it does when the value is a single digit greater than 0, the cell immediately changes to reflect the digit as contents of the cell.
