### PR TITLE
[data grid] Fix Unable to Paste Row Data in Data Grid with CAPS Lock Key Enabled

### LINKED ISSUE #11790: [data grid] Unable to Paste Row Data in Data Grid with CAPS Lock Key Enabled
### Steps to reproduce

Link to live example: https://mui.com/x/react-data-grid/clipboard/

Steps:
1. Go to the **Clipboard paste** section
2. Copy several columns of data from a spreadsheet (e.g., Excel)
3. Enable the CAPS lock key
4. Click on the first cell
5. Attempt to paste data using CTRL + V

### Current behavior

When attempting to paste a row of data with CTRL + V while the CAPS lock key is enabled, nothing will happen.  However, if you disable the CAPS lock key, the data will be pasted as expected.

### Expected behavior

Row data should be successfully pasted regardless of the status of the CAPS lock key

### Context

Trying to allow users to paste rows of data from Excel to a data grid for uploading

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Version 120.0.6099.225 (Official Build) (64-bit)
    Edge: Version 120.0.2210.144 (Official build) (64-bit)
  npmPackages:
    @emotion/react: ^11.11.0 => 11.11.1
    @emotion/styled: ^11.11.0 => 11.11.0
    @mui/base:  5.0.0-beta.9
    @mui/core-downloads-tracker:  5.14.3
    @mui/icons-material: ^5.8.4 => 5.8.4
    @mui/material: ^5.12.3 => 5.14.3
    @mui/private-theming:  5.13.7
    @mui/styled-engine:  5.13.2
    @mui/styles: ^5.9.3 => 5.9.3
    @mui/system:  5.14.3
    @mui/types:  7.2.4
    @mui/utils:  5.14.3
    @mui/x-data-grid: ^6.3.1 => 6.18.6
    @mui/x-data-grid-premium: ^6.10.2 => 6.18.6
    @mui/x-data-grid-pro:  6.18.6
    @mui/x-date-pickers: ^6.2.1 => 6.2.1
    @mui/x-license-pro:  6.10.2
    @types/react: 18.0.13 => 18.0.13
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ~4.7.2 => 4.7.4
```
</details>

**Search keywords**: caps lock, data grid, past

### PR DESCRIPTION
**Pull request by shaharyar-shamshi**
Fixes #11790

### CODE REVIEW

File: packages/grid/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts [hunk 1]
```diff
@@ -304,9 +304,9 @@ function defaultPasteResolver({
   });
 }
 
-function isPasteShortcut(event: React.KeyboardEvent) {
-  return (event.ctrlKey || event.metaKey) && event.key === 'v';
-}
+const isPasteShortcut = (event: React.KeyboardEvent) => {
+  return (event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'v';
+};
```
Comment (romgrk) [inline packages/grid/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts:309]: While we're touching this, if you want to add logic to avoid matching `ctrl-shift-v` and `ctrl-alt-v`, that would be nice.

**Review by romgrk — APPROVED** [review]

File: packages/grid/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts (hunk 1 above)
Comment (shaharyar-shamshi) [reply packages/grid/x-data-grid-premium/src/hooks/features/clipboard/useGridClipboardImport.ts]: done

**Comment by shaharyar-shamshi** [comment]
@romgrk I assume it needs to be merged only

**Comment by cherniavskii** [comment]
@shaharyar-shamshi thank you for this pull request! Your changes seem to impact the commercially licensed code. For any changes of this nature, we require contributors to sign the MUI’s Contributor License Agreement (CLA). However, I can’t find a CLA signed that could cover these changes. Please follow the steps at https://mui-org.notion.site/CLA-Contributor-License-Agreement-92ece655b1584b10b00e4de9e67eedb0 to sign the document.

**Comment by shaharyar-shamshi** [comment]
> @shaharyar-shamshi thank you for this pull request! Your changes seem to impact the commercially licensed code. For any changes of this nature, we require contributors to sign the MUI’s Contributor License Agreement (CLA). However, I can’t find a CLA signed that could cover these changes. Please follow the steps at https://mui-org.notion.site/CLA-Contributor-License-Agreement-92ece655b1584b10b00e4de9e67eedb0 to sign the document.

Sure let me sign the CLA

**Comment by shaharyar-shamshi** [comment]
> > @shaharyar-shamshi thank you for this pull request! Your changes seem to impact the commercially licensed code. For any changes of this nature, we require contributors to sign the MUI’s Contributor License Agreement (CLA). However, I can’t find a CLA signed that could cover these changes. Please follow the steps at https://mui-org.notion.site/CLA-Contributor-License-Agreement-92ece655b1584b10b00e4de9e67eedb0 to sign the document.
> 
> Sure let me sign the CLA

Done

**Comment by zannager** [comment]
@shaharyar-shamshi can you please complete the step 3 - Forward the “form submission confirmation” email (check also your spam folder) to team-legal@mui.com to confirm your identity. Also, include the link to the pull request it corresponds to. Thanks.

**Comment by oliviertassinari** [comment]
✅

We could have considered the changes CLA free, under the trivial clause as most of the changes were supervised https://mui-org.notion.site/CLA-Contributor-License-Agreement-92ece655b1584b10b00e4de9e67eedb0#ede845886e494cb4b802a67563152130
