### PR TITLE
[DataGrid] Add scroll shadows and fix scrollbar overlap

### LINKED ISSUE #10001: Improve pinning shadow design
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The existing design for pinned columns introduces an unintended visual element with a default box shadow, which contributes unnecessary visual clutter to the UI. To enhance this aspect, consider implementing a refinement where the shadow is selectively applied only in situations where a horizontal scroll is present. This not only serves to mitigate visual noise but also aids users in intuitively grasping their position within the scroll range – indicating whether they are positioned at the beginning, middle, or end of the scroll.

Captura de Pantalla 2023-08-11 a las 10 14 08

Shopify example:

https://github.com/mui/mui-x/assets/100380515/bef2d24c-e73d-4c1c-ac67-d4bce75517ac

### Examples 🌈

_No response_

### Motivation 🔦

_No response_

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by KenanYusuf**
Preview: https://deploy-preview-16476--material-ui-x.netlify.app/x/react-data-grid/column-pinning/#pinned-columns-appearance

### Conditional scroll shadows

Adds conditional scroll shadows when there are pinned columns and rows. Closes #10001

https://github.com/user-attachments/assets/1e8c61cb-9d38-41dd-a008-603c436b2e56

### Vertical scrollbar changes

Update vertical scrollbar positioning to cover pinned rows (previous discussion #16379). TLDR; this is a usability improvement, as it currently doesn't look as though you can scroll vertically over pinned rows.

Also fixes https://github.com/mui/mui-x/issues/13286

| Browser | Before | After |
| --- | --- | --- |
| Chrome, macOS | mac chrome before | mac chrome after |
| Edge, Windows 11 | windows edge before | windows edge after |
| Chrome, Windows 11 |  windows chrome before | windows chrome after |

### Changelog

- Updated vertical scrollbar to include pinned rows and aggregation sections
- Improved the appearance of [pinned columns](https://mui.com/x/react-data-grid/column-pinning/#pinned-columns-appearance) and [pinned rows](https://mui.com/x/react-data-grid/row-pinning/#pinned-rows-appearance) sections

### CODE REVIEW

File: packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx [hunk 1]
```diff
@@ -71,7 +72,15 @@ const ScrollbarHorizontal = styled(Scrollbar)({
   '& > div': {
     height: 'var(--size)',
   },
-  bottom: '0px',
+  bottom: 0,
+});
+
+export const ScrollbarCorner = styled(Scrollbar)({
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx:78]: This corner piece covers up the dead zone between the two scrollbars—works nicely on a Mac, needs to be tested on other browsers + OS.

| Without | With |
| --- | --- |
| localhost_3001_playground_ (1) | localhost_3001_playground_ (3) |

Comment (KenanYusuf) [inline packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx:78]: This corner piece covers up the dead zone between the two scrollbars.

| Without | With |
| --- | --- |
| Screenshot 2025-05-21 at 17 01 47 | Screenshot 2025-05-21 at 17 01 16 |

**Comment by KenanYusuf** [comment]
> I feel like it makes the grid with pinned rows a bit more readable as to which is the pinned vs unpinned section

@romgrk it does, but I think scroll shadows are a better indicator — I plan to add this back in at the same time https://github.com/mui/mui-x/issues/10001

File: packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts [hunk 2]
```diff
@@ -238,6 +241,10 @@ export function useGridDimensions(apiRef: RefObject<GridPrivateApiCommunity>, pr
       }
     }
 
+    if (overlayType === 'noColumnsOverlay' || loadingOverlayVariant === 'skeleton') {
+      hasScrollY = false;
```
Comment (kenanyusuf) [inline packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts]: Previously we were hiding the vertical scrollbar with CSS, but this is much more reliable. Ensures that all of the calculations that rely on `hasScrollY` are correct when the scrollbar is hidden (occurs when the "no columns overlay" and "skeleton loading overlay" are visible).

File: packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts [hunk 3]
```diff
@@ -238,6 +242,14 @@ export function useGridDimensions(apiRef: RefObject<GridPrivateApiCommunity>, pr
       }
     }
 
+    if (props.listView) {
+      hasScrollX = false;
+    }
```
Comment (kenanyusuf) [inline packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts]: We were previously hiding the scrollbar in `GridVirtualScroller` when in list view, however, this resulted in some unwanted space under the rows:
 
before

Makes sense to me to override the `hasScrollX` value so that it is accurate whilst in list view:

after

File: packages/x-data-grid/src/components/GridRow.tsx [hunk 4]
```diff
@@ -474,9 +477,6 @@ const GridRow = forwardRef<HTMLDivElement, GridRowProps>(function GridRow(props,
       {cells}
       <div role="presentation" className={clsx(gridClasses.cell, gridClasses.cellEmpty)} />
       {rightCells}
-      {scrollbarWidth !== 0 && (
-        <ScrollbarFiller pinnedRight={pinnedColumns.right.length > 0} borderTop={!isFirstVisible} />
```
Comment (cherniavskii) [inline packages/x-data-grid/src/components/GridRow.tsx:485]: So now the empty cell above fills the space `ScrollbarFiller` was filling, correct?

**Review by joserodolfofreitas — APPROVED** [review]
Nice improvement, thanks @KenanYusuf! 
It'd be great to have a follow-up with an example of how to customize the new borders.

File: packages/x-data-grid/src/components/GridScrollShadows.tsx [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+
+interface GridScrollShadowsProps {
+  position: 'vertical' | 'horizontal';
+}
+
+type OwnerState = Pick<DataGridProcessedProps, 'classes'> & {
+  position: 'vertical' | 'horizontal';
+};
+
+const ScrollShadow = styled('div')<{ ownerState: OwnerState }>(({ theme }) => ({
```
Comment (cherniavskii) [inline packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: The shadows look quite dim in dark mode:



I can't tell that there are pinned rows and columns just looking at the screenshot 😅
WDYT?

It looks great in light mode for comparison:

File: packages/x-data-grid/src/components/GridScrollShadows.tsx
Comment (cherniavskii) [inline packages/x-data-grid/src/components/GridScrollShadows.tsx:1]: Looks like scroll shadows do not consider RTL and don't work properly

File: packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx [hunk 6]
```diff
@@ -179,7 +173,10 @@ const GridVirtualScrollbar = forwardRef<HTMLDivElement, GridVirtualScrollbarProp
           event.target.blur();
         }}
       >
-        <div ref={contentRef} className={classes.content} />
+        <div
+          className={classes.content}
+          style={{ [propertyDimension]: `${scrollbarInnerSize}px` }}
```
Comment (cherniavskii) [inline packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx]: Why change the imperative `useEffect` style to inline styles?

Comment (kenanyusuf) [reply packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx]: It feels more idiomatic to use a declarative style here so I changed it, but maybe there was good reason for it to be in an effect?

Comment (cherniavskii) [reply packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx]: As far as I understand, this specific component is render-heavy, but the scrollbar width almost never changes, so evaluating inline styles on every render is an overkill.
I also noticed that we pass inline styles to the parent `Container` component, which should be extracted to a static object.

cc @romgrk in case you have an opinion on this

File: packages/x-data-grid/src/components/GridRow.tsx (hunk 4 above)
Comment (kenanyusuf) [reply packages/x-data-grid/src/components/GridRow.tsx:485]: My understanding is that scrollbar fillers on rows is currently only necessary to cover the area where the scrollbar is not present on pinned rows:
Screenshot 2025-06-26 at 14 29 16

Now that the scrollbar covers this area, I don't _think_ it is necessary 🤔

File: packages/x-data-grid/src/components/GridScrollShadows.tsx (hunk 5 above)
Comment (kenanyusuf) [reply packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: Shadows on dark mode are hard 🫠 

We need to have a lighter background on the grid for shadows to be effective. Investigated a little and found that on the Material UI Table component, it has the paper overlay making it a dark grey as opposed to the black we currently have:

Screenshot 2025-06-26 at 14 40 30

I've updated the background color on dark mode for the data grid to match and refined the shadow size/opacity:

Screenshot 2025-06-26 at 14 37 02

Feels like an improvement — WDYT?

File: packages/x-data-grid/src/components/GridScrollShadows.tsx
Comment (kenanyusuf) [reply packages/x-data-grid/src/components/GridScrollShadows.tsx:1]: Good spot. Updated https://github.com/mui/mui-x/pull/16476/commits/392d9a01803d129ce57c6cfc35a293e54727437d

File: packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx (hunk 6 above)
Comment (kenanyusuf) [reply packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx]: > As far as I understand, this specific component is render-heavy, but the scrollbar width almost never changes, so evaluating inline styles on every render is an overkill.

That makes sense — would it be equally performant to memoize the style object using `useMemo`, seeing as it would have the same dependencies as the `useEffect`?

> I also noticed that we pass inline styles to the parent Container component, which should be extracted to a static object.

Good spot. These styles don't appear necessary anymore due to this change: https://github.com/mui/mui-x/pull/16476/files/2386c9cbd5d4f28b26a26e64bc337bd043a401ab#r2166635714

File: packages/x-data-grid/src/components/GridScrollShadows.tsx (hunk 5 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: Looks better!
Do you think it's OK to change the background color in a patch/minor version?

File: packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx (hunk 6 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx]: > That makes sense — would it be equally performant to memoize the style object using useMemo, seeing as it would have the same dependencies as the useEffect?

In the context of rerenders caused by parent component rerender – yes, I think so.

File: packages/x-data-grid/src/components/GridScrollShadows.tsx (hunk 5 above)
Comment (kenanyusuf) [reply packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: I think so? Not sure. There are a few substantial design changes here, including removing borders on pinned columns by default. @joserodolfofreitas any thoughts?

**Review by cherniavskii — APPROVED** [review]

File: packages/x-data-grid/src/components/GridScrollShadows.tsx (hunk 5 above)
Comment (joserodolfofreitas) [reply packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: Good question. Since we follow SemVer, visual changes like background color or removing borders can be breaking if they affect existing layouts or theming expectations, especially for users relying on visual consistency.

So even though they might feel “minor”, ideally, we should treat these as breaking changes and target them for the next major version.

That said, if we can opt-in* to the new visuals via a prop or theme variable (and keep the old behavior as default), then we could consider shipping it in a minor instead.

*(An opt-out prop is not the ideal, because it essentilly still breaking, but it's fine as well, since it'd not break for most people)

Comment (kenanyusuf) [reply packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: Just discussed with @cherniavskii — @joserodolfofreitas we wanted to get your thoughts on this approach for getting the PR merged in a minor release:

- Treat the background color change as a bug fix, since it should likely align with the Material UI Table for consistency.
- Add a prop to hide pinned column borders. We can default it to false for now and consider flipping it in a future major release.
- Introduce scroll shadows as a design improvement in the minor. They work fine alongside the pinned column and row borders.

File: packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx (hunk 6 above)
Comment (romgrk) [reply packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx]: No strong opinion, the component is render-heavy, but otoh an inline style attribute might be evaluated sooner than a DOM update in an effect. I think either is fine.

File: packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts:1]: We need to figure out an API for this that doesn't tie the virtualizer with the grid's internals now that the virtualizer is separated. Maybe the dimensions feature of the virtualizer can accept input data for e.g. `hasScrollX`? Maybe as something like `disableHorizontalScrollbar`? I also wonder if we can translate the "listView" case into something more general that the virtualizer could handle.

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 7]
```diff
@@ -275,10 +275,10 @@ export const useGridVirtualScroller = () => {
 
     const dimensions = gridDimensionsSelector(apiRef);
     const maxScrollTop = Math.ceil(
-      dimensions.minimumSize.height - dimensions.viewportOuterSize.height,
+      dimensions.contentSize.height - dimensions.viewportInnerSize.height,
     );
     const maxScrollLeft = Math.ceil(
-      dimensions.minimumSize.width - dimensions.viewportInnerSize.width,
+      dimensions.contentSize.width - dimensions.viewportInnerSize.width,
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:217]: Iiuc, this is a bugfix for the virtualization code?

Comment (kenanyusuf) [reply packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:217]: Yes, if I'm remembering correctly it fixes a miscalculation.

File: packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts:1]: > if we can translate the "listView" case into something more general

Are there specific requirements for that feature? Scrollbar-wise, is it meant to never have a horizontal scrollbar? And is it intended just for mobile, or for small viewport size in general?

Comment (kenanyusuf) [reply packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts:1]: > Scrollbar-wise, is it meant to never have a horizontal scrollbar?

List view should never have a horizontal scrollbar.

> or for small viewport size in general?

Yes, it's intended for small viewports. Any viewport size where it's better UX to present the data not in a table.

File: packages/x-data-grid/src/components/GridScrollShadows.tsx (hunk 5 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: I have added a prop to control borders/shadows https://deploy-preview-16476--material-ui-x.netlify.app/x/react-data-grid/column-pinning/#pinned-columns-appearance

Comment (kenanyusuf) [reply packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: @cherniavskii thanks for picking this up. Would it make sense to have a similar option for pinned rows since they can have shadows now too? Or we could perhaps condense it into one prop: `pinnedSectionSeparator`.

Comment (cherniavskii) [reply packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: > Or we could perhaps condense it into one prop: pinnedSectionSeparator.

In case of pinned rows, the border is always there. Do you think we should support the same list of options for the pinned rows as for the pinned columns?

Comment (cherniavskii) [reply packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: Added a separate `pinnedRowsSectionSeparator` prop to avoid implementing `shadow` option for pinned rows, since we don't even know if anyone would want to use it. https://deploy-preview-16476--material-ui-x.netlify.app/x/react-data-grid/row-pinning/#pinned-rows-appearance

Comment (kenanyusuf) [reply packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: Yeah, I don't think a `shadow` option would make sense in the case of pinned rows. Looks good 👍

**Comment by cherniavskii** [comment]
OK, this PR is ready for review again.
@romgrk any objections on your side?

File: packages/x-data-grid/src/models/props/DataGridProps.ts [hunk 8]
```diff
@@ -903,6 +903,16 @@ export interface DataGridProSharedPropsWithDefaultValue {
...
+  /**
+   * Sets the type of separator between pinned columns and non-pinned columns.
+   * @default 'border+shadow'
+   */
+  pinnedColumnsSectionSeparator: 'border' | 'shadow' | 'border+shadow';
+  /**
+   * Sets the type of separator between pinned rows and non-pinned rows.
+   * @default 'border+shadow'
+   */
+  pinnedRowsSectionSeparator: 'border' | 'border+shadow';
```
Comment (arminmeh) [inline packages/x-data-grid/src/models/props/DataGridProps.ts]: My personal preference, since having `+` in the value feels a bit weird. You can ignore it if you want
```suggestion
  /**
   * Sets the type of separator between pinned columns and non-pinned columns.
   * @default 'border+shadow'
   */
  pinnedColumnsSectionSeparator: 'border' | 'shadow' | 'border-and-shadow';
  /**
   * Sets the type of separator between pinned rows and non-pinned rows.
   * @default 'border+shadow'
   */
  pinnedRowsSectionSeparator: 'border' | 'border-and-shadow';
```

File: packages/x-data-grid/src/components/GridScrollShadows.tsx [hunk 9]
```diff
@@ -0,0 +1,150 @@
...
```
Comment (arminmeh) [inline packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: Can this component be combined with https://github.com/mui/mui-x/blob/v8.11.3/packages/x-data-grid/src/components/GridShadowScrollArea.tsx
They are creating the same UI, right?

File: packages/x-data-grid/src/models/props/DataGridProps.ts (hunk 8 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/models/props/DataGridProps.ts]: I didn't think much about the naming here, how about `border&shadow`?

File: packages/x-data-grid/src/components/GridScrollShadows.tsx (hunk 9 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/components/GridScrollShadows.tsx:30]: I just compared them, and the implementation is completely different.
Box shadow vs Background color
Horizontal + vertical vs horizontal only
Absolute position vs before/after on the same `div`

I don't think it's worth extracting common parts because, well, there's not much in common.

File: packages/x-data-grid/src/models/props/DataGridProps.ts (hunk 8 above)
Comment (arminmeh) [reply packages/x-data-grid/src/models/props/DataGridProps.ts]: I am also fine with that

Comment (kenanyusuf) [reply packages/x-data-grid/src/models/props/DataGridProps.ts]: `border-and-shadow` is the best IMO

**Review by romgrk — APPROVED** [review]

File: packages/x-data-grid/src/material/variables.ts [hunk 10]
```diff
@@ -17,15 +17,19 @@ function transformTheme(t: Theme): GridCSSVariablesInterface {
   const borderColor = getBorderColor(t);
   const dataGridPalette = (t.vars || t).palette.DataGrid;
 
-  const backgroundBase = dataGridPalette?.bg ?? (t.vars || t).palette.background.default;
+  const backgroundBase =
+    dataGridPalette?.bg ??
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/material/variables.ts:21]: @mui/xgrid Would this change count as breaking, as the color value is being updated?

Context: https://github.com/mui/mui-x/issues/20048

Comment (kenanyusuf) [reply packages/x-data-grid/src/material/variables.ts:21]: Hey @MBilalShafi — we decided to treat the background color change as a bug fix. See this comment: https://github.com/mui/mui-x/pull/16476#discussion_r2192109932

Comment (MBilalShafi) [reply packages/x-data-grid/src/material/variables.ts:21]: Thanks @KenanYusuf for linking the discussion.
In such cases, we should probably announce such changes more prominently to set the users' expectations right.
