### PR TITLE
[pickers] Forward `data-*` and `aria-*` attributes to the root

### LINKED ISSUE #20706: [pickers] data-x attributes do not end up on the root element of the picker
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/devbox/cocky-rain-4kdvm3?from-embed=&workspaceId=ws_8Gvn86jdwuzyvAQSp15K4u
2. Notice that even though the `DatePicker` component has a `data-id='my-id'` property, there's no `data-id="my-id"` attribute  in the DOM

### Current behavior

`data-x` properties on the `DatePicker` component do not end up in the DOM, even though they pass typecheck.

### Expected behavior

`data-x` properties on the `DatePicker` component should end up on the DOM, on the `.MuiPickersTextField-root` element or the `.MuiPickersInputBase-root` element.

Alternatively, the properties should not pass type checks in TS if they are not supported.

### Context

Trying to add `data-id` elements to the `DatePicker` component, so that I can find the picker in my Cypress tests.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 15.7.2
  Binaries:
    Node: 24.0.2 - /Users/jakobmerrild/.nvm/versions/node/v24.0.2/bin/node
    npm: 11.3.0 - /Users/jakobmerrild/.nvm/versions/node/v24.0.2/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 143.0.7499.111
    Edge: Not Found
    Firefox: 138.0.4
    Safari: 26.0.1
  npmPackages:
    @emotion/react: ^11.14.0 => 11.14.0
    @emotion/styled: ^11.14.1 => 11.14.1
    @mui/base:  5.0.0-beta.42
    @mui/core-downloads-tracker:  7.3.6
    @mui/icons-material: ^7.3.6 => 7.3.6
    @mui/lab: 6.0.0-dev.240424162023-9968b4889d => 6.0.0-dev.240424162023-9968b4889d
    @mui/material: ^7.3.6 => 7.3.6
    @mui/material-nextjs: ^7.3.6 => 7.3.6
    @mui/private-theming:  6.4.9
    @mui/styled-engine:  6.4.11
    @mui/system:  6.4.11
    @mui/types:  7.4.5
    @mui/utils:  7.3.1
    @mui/x-data-grid:  8.5.2
    @mui/x-date-pickers: ^8.21.0 => 8.22.0
    @mui/x-internals:  8.22.0
    @toolpad/core: ^0.16.0 => 0.16.0
    @toolpad/utils:  0.16.0
    @types/react: ^19.2.7 => 19.2.7
    react: ^19.2.3 => 19.2.3
    react-dom: ^19.2.3 => 19.2.3
    typescript: ^5.9.3 => 5.9.3
```
</details>

**Search keywords**: [DatePicker] data attribute

### PR DESCRIPTION
**Pull request by LukasTy**
## Summary

Passing `data-*` or `aria-*` attributes to a Picker (for example `<DatePicker data-id="my-id" />`) previously passed TypeScript but never reached the DOM. The attributes were dropped in the Picker hooks, which destructured a fixed set of known props and did not thread anything else into the Field slot or layout root.

Fixes #20706.

## What changed

- New `extractRootForwardedProps` utility in `packages/x-date-pickers/src/internals/utils/utils.ts` that picks `data-*` / `aria-*` keys off the incoming props.
- Threaded through `externalForwardedProps` of the Field slot in:
  - `useDesktopPicker`
  - `useMobilePicker`
  - `useDesktopRangePicker` (preserving the existing `data-active-range-position` additional prop)
  - `useMobileRangePicker`
- For the 4 static pickers (`StaticDatePicker`, `StaticDateTimePicker`, `StaticTimePicker`, `StaticDateRangePicker`), `PickersLayout` now extends `React.HTMLAttributes<HTMLDivElement>` and spreads the remaining props onto its root `div`. `useStaticPicker` and `useStaticRangePicker` thread `extractRootForwardedProps(props)` to the `Layout`.
- From there the existing `DateField` / `SingleInputRangeField` / `MultiInputRangeField` forward chain lands the attributes on the rendered root (`MuiPickersTextField-root` for single-input pickers, the Stack root for multi-input range pickers, the layout root for static pickers).
- `propsSpread` enabled in all 21 picker conformance test suites that were previously skipping it (8 single + 9 range + 4 static). The conformance test verifies that both a random `data-*` attribute and `data-testid` land on the root element.

## Why narrow (`data-*` / `aria-*` only) for non-static pickers

The issue specifically reports the `data-*` / `aria-*` case (matching v6 behavior). A broader "forward anything not destructured" approach was considered but rejected for the desktop/mobile/range hooks:

- Picker props come from a generic union, with no single runtime list of owned keys.
- Picker-owned props (`value`, `onChange`, `views`, `openTo`, `format`, `onAccept`, `onClose`, `open`, ...) would need an explicit omit list that must be maintained on every prop addition; any miss would silently leak to the DOM and trigger React's unknown-attribute warning.
- If a specific semantic HTML attribute ever needs forwarding (`role`, `title`, `tabIndex`, ...), it is a one-line extension of the extractor.

For `PickersLayout` itself the full `HTMLAttributes<HTMLDivElement>` surface is fine because the component is a thin wrapper around a `div`, and its owned props are a small closed set destructured at the top of the component.

### CODE REVIEW

File: packages/x-date-pickers/src/PickersLayout/PickersLayout.tsx [hunk 1]
```diff
@@ -114,7 +114,7 @@ const PickersLayout = React.forwardRef(function PickersLayout<TValue extends Pic
 
   const { toolbar, content, tabs, actionBar, shortcuts, ownerState } = usePickerLayout(props);
   const { orientation, variant } = usePickerContext();
-  const { sx, className, classes: classesProp } = props;
+  const { sx, className, classes: classesProp, children, slots, slotProps, ...other } = props;
```
Comment (michelengelen) [inline packages/x-date-pickers/src/PickersLayout/PickersLayout.tsx:117]: Is the destructuring of children intentional? Feels like this would break custom implementations, no?

**Review by michelengelen — COMMENTED** [review]
Would it make sense to add some tests for this?

File: packages/x-date-pickers/src/PickersLayout/PickersLayout.tsx (hunk 1 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/PickersLayout/PickersLayout.tsx:117]: `children`, `slots`, and `slotProps` are handled inside the `usePickerLayout` hook.
This shouldn't have any impact.
If it had broken anything, then the [demos here](https://deploy-preview-22147--material-ui-x.netlify.app/x/react-date-pickers/custom-layout/) would have been impacted. 🤔

**Review by michelengelen — APPROVED** [review]
