### PR TITLE
[DataGrid] Add `checkboxColDef` prop to customize the selection column

### LINKED ISSUE #18642: [data grid] Row grouping and `checkboxSelection` with custom Checkbox rendered moves checkbox to later column
### Steps to reproduce

Steps:
1. Open this link to live example: [Link](https://stackblitz.com/edit/wjsqqjfo?file=src%2FDemo.tsx)

### Current behavior

Note that the checkbox column is now second, instead of first. Preceded by the "group" column. This only happens when I pass a `GRID_CHECKBOX_SELECTION_COL_DEF` explicitly in the grid's columns, no matter if its the direct import from @mui or a customized version with its own `renderCell`.

Weirder still, Im somewhat able to explicitly force the checkbox to be first, by using `initialState.columns.orderedFields = [GRID_CHECKBOX_SELECTION_COL_DEF.field]`, but it ONLY works if I disable column pinning (which I also need) and ONLY the second time the DataGrid is rendered, meaning it still shows the checkbox in the second column at first.

Image

### Expected behavior

The checkbox column's position should coincide with its position in the `columns` array passed to the `DataGrid`. This used to be the case in MUIX 7 before we upgraded

### Context

I want a customized checkbox cell even with row grouping is active, without changing its column placement

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 15.5
  Binaries:
    Node: 22.17.0 - ~/.nvm/versions/node/v22.17.0/bin/node
    npm: 10.9.2 - ~/.nvm/versions/node/v22.17.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 138.0.7204.49 < This one
    Edge: Not Found
    Safari: 18.5
  npmPackages:
    @emotion/react: ^11.14.0 => 11.14.0 
    @emotion/styled: ^11.14.0 => 11.14.0 
    @mui/core-downloads-tracker:  7.1.2 
    @mui/material: ^7.1.2 => 7.1.2 
    @mui/private-theming:  7.1.1 
    @mui/styled-engine:  7.1.1 
    @mui/system: ^7.1.1 => 7.1.1 
    @mui/types:  7.4.3 
    @mui/utils: ^7.1.1 => 7.1.1 
    @mui/x-charts:  8.6.0 
    @mui/x-charts-pro: ^8.6.0 => 8.6.0 
    @mui/x-charts-vendor:  8.5.3 
    @mui/x-data-grid:  8.6.0 
    @mui/x-data-grid-premium: ^8.6.0 => 8.6.0 
    @mui/x-data-grid-pro:  8.6.0 
    @mui/x-date-pickers:  8.6.0 
    @mui/x-date-pickers-pro: ^8.6.0 => 8.6.0 
    @mui/x-internals:  8.6.0 
    @mui/x-license: ^8.6.0 => 8.6.0 
    @mui/x-telemetry:  8.5.3 
    @types/react: ^19.1.8 => 19.1.8 
    react: ^19.1.0 => 19.1.0 
    react-dom: ^19.1.0 => 19.1.0 
    typescript: ^5.8.3 => 5.8.3 
```
</details>

**Search keywords**: row grouping, checkbox selection

### PR DESCRIPTION
**Pull request by michelengelen**
This PR introduces the `checkboxColDef` prop to `DataGrid`, `DataGridPro`, and `DataGridPremium`. This prop allows developers to customize the checkbox selection column (e.g., changing its width, pinning it, or adding custom class names) in a way consistent with existing props like `listViewColumn` and `groupingColDef`.

Fixes #18642

### CODE REVIEW

File: packages/x-data-grid/src/models/colDef/gridColDef.ts [hunk 1]
```diff
@@ -382,6 +382,16 @@ export type GridListViewColDef<R extends GridValidRowModel = any, V = any, F = V
   'field' | 'renderCell' | 'align' | 'cellClassName' | 'display'
 >;
 
+/**
+ * Column Definition interface used for the checkbox selection column.
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/models/colDef/gridColDef.ts:386]: Should we omit the usage of, or atleast document the risk of using `renderCell` and `renderHeader` from the type? Users overriding these could break select-all / row-select behavior entirely.

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelectionPreProcessors.ts [hunk 2]
```diff
@@ -37,6 +37,7 @@ export const useGridRowSelectionPreProcessors = (
         cellClassName: classes.cellCheckbox,
         headerClassName: classes.columnHeaderCheckbox,
         headerName: apiRef.current.getLocaleText('checkboxSelectionHeaderName'),
+        ...props.checkboxColDef,
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelectionPreProcessors.ts:40]: To avoid someone accidentally removing them?
```suggestion
        ...props.checkboxColDef,
        GRID_CHECKBOX_SELECTION_COL_DEF.field,
        GRID_CHECKBOX_SELECTION_COL_DEF.type,
```

**Review by MBilalShafi — APPROVED** [review]

File: packages/x-data-grid/src/models/colDef/gridColDef.ts (hunk 1 above)
Comment (michelengelen) [reply packages/x-data-grid/src/models/colDef/gridColDef.ts:386]: I did add a warning to the docs and the type. I don't think we should exclude this from customization in general, just a warning should suffice

**Comment by michelengelen** [comment]
@MBilalShafi if you are fine with the callout and warning in types I can merge. Agree?

**Comment by MBilalShafi** [comment]
> @MBilalShafi if you are fine with the callout and warning in types I can merge. Agree?

Looks enough for now. 👍

**Comment by MBilalShafi** [comment]
@michelengelen This should probably be backported to v8 too. Wdyt?
