### PR TITLE
[TreeView] Support reordering of items in `SimpleTreeView`

### LINKED ISSUE #10235: [TreeView] After reordering TreeItem in TreeView, multiple selection broken
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

As title describe, the `index` (internal state of `TreeView`) not update after reorder items, that will cause multiple selection (hold shift) broken. (see Steps to reproduce for example)

### Expected behavior 🤔

 (see Steps to reproduce for example)

### Steps to reproduce 🕹

Steps:

[sandbox](https://codesandbox.io/s/infallible-night-tdqkx)

1. click `move 3rd item to last`
2. select `item 4`
3. hold shift and select `item 5`
4. only `item 4` and `item 5` selected (should be `item 5/2/3/4`)

### Context 🔦

I'm creating a app which will let the user reorder the tree item

Workaround: (not tested, just trace the source)

If remove and add it in new place, the multiple selection may work, but my tree may be deep and frequently change its content and order, if I use this workaround may cause some performance issue.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.0 - ~\AppData\Local\Temp\xfs-cd02493b\node.CMD
    Yarn: 3.1.0 - ~\AppData\Local\Temp\xfs-cd02493b\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.57)
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.60
    @mui/icons-material: ^5.2.4 => 5.2.4
    @mui/lab: ^5.0.0-alpha.60 => 5.0.0-alpha.60
    @mui/material: ^5.2.4 => 5.2.4
    @mui/private-theming:  5.2.3
    @mui/styled-engine:  5.2.4
    @mui/system:  5.2.4
    @mui/types:  7.1.0
    @mui/utils:  5.2.3
    @types/react: ^17.0.37 => 17.0.37
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.5.4 => 4.5.4
    and my app is running in electron 16
```
</details>

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fix #10235

## Problem

The registration is done by the children when some of their props changes.
But if you just swap to items, nothing is called and the indexes in the state becomes outdated, causing multi-selection to break.

### For both `RichTreeView` and `SimpleTreeView`

- [x] For each item with children, store its children ids in an order array in `state.items.itemOrderedChildrenIds`
- [x] Remove the index from `state.items.nodeMap` 

#### Benefis

- `instance.getItemOrderedChildrenIds` (which replaces `instance.getChildrenIds`) has now a complexity of `O(1)` instead of `O(n)`. It is used for most keyboard navigation and range selection.

#### Costs

- The complexity to get the index of a given item is now `O(n)` instead of `O(1)`. We need to explore the optimal data structure for the indexes depending on which access is the most frequent (getting an item index, changing an item index, getting the next item after some item, getting an ordered list of the items, ...). For now the new structure is super simple so at least we can easily modify it.

### For `SimpleTreeView`

- [x] On every render, each item generates the new list of its children ids using `querySelector`, if the list has changed it updates `state.items.itemOrderedChildrenIds`

#### Benefis

- Can now re-order items on `SimpleTreeView`
- We no longer have any binary position search based on the DOM position

#### Costs

- We have some cost on every render to check if the children have changed (should not be noticeable at all since `SimpleTreeView` is not meant for big dataset, IMHO the data structure optimization for `state.items.itemOrderedChildrenIds` are a lot more important to help the `RichTreeView` scale on big datasets).

## Follow up

- `state.items.itemOrderedChildrenIds` could be a ref since it's only used in even callbacks. We need to check if this can avoid a re-render (not sure since it's always updated when children changes, which should cause a re-render of its own unless it's an index swap. So the optimization might be pointless).

### CODE REVIEW

File: packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.ts [hunk 1]
```diff
@@ -154,7 +168,16 @@ export const useTreeViewNodes: TreeViewPlugin<UseTreeViewNodesSignature> = ({
     return childrenIds;
   };
 
+  const isItemUpdatedPreventedRef = React.useRef(false);
+  const preventItemUpdate = useEventCallback(() => {
```
Comment (flaviendelangle) [inline packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.ts:172]: This PR makes the item register earlier in `SimpleTreeView`, which is great but causes the empty `props.items` array to wipe the state after the initialization.
The simplest solution I found is just to have `useTreeViewJSXNodes` prevents any state update based on `props.items` with this method.

File: packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.ts [hunk 2]
```diff
@@ -138,12 +148,16 @@ export const useTreeViewNodes: TreeViewPlugin<UseTreeViewNodesSignature> = ({
     [instance],
   );
 
-  const getChildrenIds = useEventCallback((nodeId: string | null) =>
-    Object.values(state.nodes.nodeMap)
-      .filter((node) => node.parentId === nodeId)
-      .sort((a, b) => a.index - b.index)
-      .map((child) => child.id),
-  );
+  const getChildrenIds = useEventCallback((nodeId: string | null) => {
```
Comment (flaviendelangle) [inline packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.ts:151]: Nice side effect of storing the indexes in this new structure, we no longer have to loop on **all** the items to find the one that belong to a certain parent.

File: packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+    } else if (id && parentContext) {
+      // The DescendantProvider is not aware of the ref of its own item,
+      // but its parent can give him this information.
+      element = parentContext.getChild(id);
+    }
+
+    // Weak but quick way to check if the descendants have changed and avoid the expensive DOM operations.
+    // This is not sufficient to get the new order because this includes grand-children, not only direct children.
+    if (element) {
+      const newDescendantIds = Array.from(element.querySelectorAll('[role="treeitem"]'))
```
Comment (LukasTy) [inline packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx:65]: A couple of possibly nitpick topics:
1. Have you considered treating the DOM as the source of truth and adjusting event handling to interact with DOM rather than a tree item indexed representation that we try to keep in sync?
2. I noticed that in our implementation only `treeitem`s of an `expanded` `group` are rendered. Was this intentional for some reason? 🤔 
I think it is somewhat of an a11y problem because screen readers can not give context about what is inside of a collapsed group. 🙈

File: packages/x-tree-view/src/internals/models/plugin.ts [hunk 4]
```diff
@@ -159,8 +164,14 @@ export type TreeViewPlugin<TSignature extends TreeViewAnyPluginSignature> = {
...
    * Render function used to add React wrappers around the TreeItem.
-   * @param {TreeItemWrapperParams} params The params of the item.
-   * @returns {React.ReactNode} The wrapped items.
+   * @param {{ nodeId: TreeViewItemId; children: React.ReactNode; }} params The params of the item.
+   * @returns {React.ReactNode} The wrapped item.
    */
   wrapItem?: TreeItemWrapper;
+  /**
+   * Render function used to add React wrappers around the TreeView.
+   * @param {{ nodeId: TreeViewItemId; children: React.ReactNode; }} params The params of the root
```
Comment (LukasTy) [inline packages/x-tree-view/src/internals/models/plugin.ts:173]: Nitpick 🙈 
```suggestion
   * @param {{ nodeId: TreeViewItemId; children: React.ReactNode; }} params The params of the root.
```

File: packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.types.ts [hunk 5]
```diff
@@ -15,6 +15,11 @@ export interface UseTreeViewNodesInstance<R extends {}> {
   getChildrenIds: (nodeId: string | null) => string[];
   getNavigableChildrenIds: (nodeId: string | null) => string[];
   isNodeDisabled: (nodeId: string | null) => nodeId is string;
+  /**
+   * Freeze any future update to the state based on the `items` prop.
+   * This is useful when `useTreeViewJSXNodes` is used to avoid having conflicting sources if truth.
```
Comment (LukasTy) [inline packages/x-tree-view/src/internals/plugins/useTreeViewNodes/useTreeViewNodes.types.ts:20]:
```suggestion
   * This is useful when `useTreeViewJSXNodes` is used to avoid having conflicting sources of truth.
```

File: packages/x-tree-view/src/internals/plugins/useTreeViewJSXNodes/useTreeViewJSXNodes.tsx [hunk 6]
```diff
@@ -34,20 +38,41 @@ export const useTreeViewJSXNodes: TreeViewPlugin<UseTreeViewJSXNodesSignature> =
...
+    parentId: string | null,
+    indexes: { [id: string]: number },
+  ) => {
+    setState((prevState) => ({
+      ...prevState,
+      nodes: {
+        ...prevState.nodes,
+        itemIndexes: {
+          ...prevState.nodes.itemIndexes,
+          [parentId ?? TREE_VIEW_ROOT_PARENT_ID]: indexes,
```
Comment (LukasTy) [inline packages/x-tree-view/src/internals/plugins/useTreeViewJSXNodes/useTreeViewJSXNodes.tsx:59]: Nitpick: Have you considered prefixing the constant with `DEFAULT_` as it looks like it is its purpose? 🤔

**Review by LukasTy — APPROVED** [review]
Looks great, nice work! 👍 👏 

The solution doesn't look the "cleanest", but if you think that it is best option—I'm not complaining. 😃

**Comment by flaviendelangle** [comment]
>  if you think that it is best option—I'm not complaining.

If we had a way to create a selector that targets the direct children without also getting the other descendants, we would no longer need all the binary search which is the heaviest part of the new code.
But I'm not sure it's doable without polluting the HTML with something like `data-parentId`.
The problem being that with custom items, people might have several nested divs / spans before actually rendering the items.

File: packages/x-tree-view/src/internals/plugins/useTreeViewJSXNodes/useTreeViewJSXNodes.tsx (hunk 6 above)
Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/plugins/useTreeViewJSXNodes/useTreeViewJSXNodes.tsx:59]: I don't see it as a default but more an ID for the root items when it's needed.
It's not "I don't have parent, let's use this ID", but more "I am a root element, so my parent ID is the root ID".

It's the equivalent to `GRID_ROOT_GROUP_ID` on the grid.

File: packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx (hunk 3 above)
Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx:65]: > Have you considered treating the DOM as the source of truth and adjusting event handling to interact with DOM rather than a tree item indexed representation that we try to keep in sync?

Yes
And the challenge is to have `RichTreeView` working with it since it has the index without looking on the DOM.
Should we have 2 ways of getting the index (`RichTreeView` uses state and `SimpleTreeView` looks on the DOM), or should we always look on the DOM even though `RichTreeView` has the information in state?
Always looking on the DOM will probably not work well with virtualization (which is only planned for `RichTreeView`).

>  noticed that in our implementation only treeitems of an expanded group are rendered. Was this intentional for some reason?

Do we agree that it was already the case before this PR?
I think it's a performance topic mostly, it was like this when I migrated but your point about a11y is interesting...

Comment (LukasTy) [reply packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx:65]: > And the challenge is to have RichTreeView working with it since it has the index without looking on the DOM.
Should we have 2 ways of getting the index (RichTreeView uses state and SimpleTreeView looks on the DOM), or should we always look on the DOM even though RichTreeView has the information in state?
Always looking on the DOM will probably not work well with virtualization (which is only planned for RichTreeView).

Yes, I do understand that `RichTreeView` couldn't work with DOM event management, specifically because of virtualization and it does not need, because we already have one source of truth in that case.
I was indeed referring to the consideration of going with a simpler approach for the `SimpleTreeView`, albeit, it would be different between the components. 🤔 

In any case, it can probably be tackled without a BC if we see that as the better option, because it's mostly internal logic. 🤷 

> Do we agree that it was already the case before this PR?
I think it's a performance topic mostly, it was like this when I migrated but your point about a11y is interesting...

Oh yes, I just mentioned it here, that's not related to this PR.
I just double-checked the a11y behavior and it seems that I might have "dreamt" a behavioral difference initially.
Even the [tree view with all items rendered](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-1a/) does not announce anything about children until the group/parent is expanded. 👌 
So, there does not seem to be any direct a11y consequence because of this. 👌

**Comment by LukasTy** [comment]
> If we had a way to create a selector that targets the direct children without also getting the other descendants, we would no longer need all the binary search which is the heaviest part of the new code.
> But I'm not sure it's doable without polluting the HTML with something like `data-parentId`.
> The problem being that with custom items, people might have several nested divs / spans before actually rendering the items.

IMHO, polluting the DOM with `data` attributes to improve performance or just have a cleaner solution is a viable compromise.
We already have a few examples in Pickers and Data Grid seems to use its fair share of `data-` attributes... 🤷 
The part about nested components in userland is just a matter of adding mention to put this prop on an appropriate element. 🤔

**Comment by flaviendelangle** [comment]
> The part about nested components in userland is just a matter of adding mention to put this prop on an appropriate element

Sure, the problem of custom DOM structure occurs if we do not have any custom attribute, but if we add `data-parentId` then we can do something like `Array.from(element.querySelectorAll('[role="treeitem"][data-parentId=${parentId ?? ""}'))` (we would need to decide if for root elements we use the internal default ID (which is quite long) or if we just use an empty string.

File: packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx (hunk 3 above)
Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx:65]: > I just double-checked the a11y behavior and it seems that I might have "dreamt" a behavioral difference initially.
Even the [tree view with all items rendered](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/examples/treeview-1a/) does not announce anything about children until the group/parent is expanded. 👌

:ok_hand: That's reassuring

**Comment by LukasTy** [comment]
> About not storing the ID in state, since we would need this custom data-attr to find the next element (unless I'm missing someway of doing it), I propose to explore it in a follow up, the change should be purely internal.

Sounds fair. No other nitpicks from me. 👌

File: CHANGELOG.md
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply CHANGELOG.md:1]: Which diff seems unrelated to you?
There are small internal changes required for the new behavior (to stop storing the index with the other attributes)

[the remark this answers is not in the document]
Comment (michelengelen) [reply CHANGELOG.md:1]: its gone now ... When clicking the notification i got send to this diff: 592f27b5c98f595e0f9e35ba5a676d698bff96fd

Sry for the misinformation! 🙇🏼

[the remark this answers is not in the document]
Comment (flaviendelangle) [reply CHANGELOG.md:1]: No problem!
No idea why you got it :laughing:

File: packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx [hunk 7]
```diff
@@ -0,0 +1,91 @@
...
+      }
+    }
+
+    if (idAttr == null) {
+      return;
+    }
+
+    const previousChildrenIds = instance.getItemOrderedChildrenIds(itemId ?? null) ?? [];
+    const childrenElements = rootRef.current.querySelectorAll(
+      `${itemId == null ? '' : `*[id="${idAttr}"] `}[role="treeitem"]:not(*[id="${idAttr}"] [role="treeitem"] [role="treeitem"])`,
```
Comment (LukasTy) [inline packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx:51]: Nitpick: Does the truthy ternary case make sense here? 🤔 
Wouldn't simply returning an empty array be the same?
P.S. Running `document.querySelectorAll('')` seems to throw and exception. 🙈

**Review by LukasTy — APPROVED** [review]
The updated approach looks great! 🎉 👍

File: packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx (hunk 7 above)
Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx:51]: The ternay does not create an empty selector, it only removes `*[id="${idAttr}"]`.

Selector with the root: `[role="treeitem"]:not(*[id="${idAttr}"] [role="treeitem"] [role="treeitem"])`
Selector with nested item: `*[id="${idAttr}"] [role="treeitem"]:not(*[id="${idAttr}"] [role="treeitem"] [role="treeitem"])`

Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx:51]: I can do the ternary outside of the selector if this is more readable:

`itemId == null ? rootRef.querySelector() : rootRef.querySelector()`

I did not do it because if I move `[role="treeitem"]:not(*[id="${idAttr}"] [role="treeitem"] [role="treeitem"])` to a string, I loose the IDE selector analysis which makes it harder to read, so we would have to duplicate this string in both selector.
Both approaches are good to me :+1:

Comment (LukasTy) [reply packages/x-tree-view/src/internals/TreeViewProvider/TreeViewChildrenItemProvider.tsx:51]: Whoops, sorry. 🙈 
Well, the readability isn't the best, as we can clearly see. 😆 
But if it's the cleanest overall solution, I retract my comment. 👌
