### PR TITLE
[charts] Fix zoom discard inconsistency

### LINKED ISSUE #17561: [charts] `createAxisFilterMapper` does not respect domain limit
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/sandbox/x-charts-pro-domain-limit-zoom-k6ztx7

### Current behavior

https://github.com/mui/mui-x/pull/15294 introduced a new domainLimit option to axis config. This allows the configuration of the axis scale domain, as described in the docs https://mui.com/x/api/charts/axis-config/#axis-config-prop-domainLimit

This is used by `computeAxisValue`

https://github.com/mui/mui-x/blob/dbfc3fea456bd5d73ea8712d9f43368857cdc102/packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts#L189-L207

However, `createAxisFilterMapper` does not take into account this domain limit

https://github.com/mui/mui-x/blob/dbfc3fea456bd5d73ea8712d9f43368857cdc102/packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.ts#L75

The zoom and pan feature depends on the `createAxisFilterMapper` function. This results in a desync between what the zoom feature thinks the current domain is vs what the actual domain is, as it assumes it's set to `nice`. 

The code sandbox has the zoom set to 90%-100%, to show the cases where scaling is a factor. 

### Expected behavior

_No response_

### Context

_No response_

### Your environment

**Search keywords**: charts domain limit zoom

**Order ID**: 96664

### PR DESCRIPTION
**Pull request by bernardobelchior**
Fixes #17561. 

Alternative to #19332.

### CODE REVIEW

File: packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts [hunk 1]
```diff
@@ -106,138 +102,118 @@ export function computeAxisValue<T extends ChartSeriesType>({
...
+            scaleType as ContinuousScaleName,
             range.map((v) => scale.invert(v)),
             range,
           ),
         ) as <TScaleName extends ScaleName>(
           value: any,
           context: AxisValueFormatterContext<TScaleName>,
         ) => string),
-    };
+    } as ComputedAxis<ContinuousScaleName, any, ChartsAxisProps>;
```
Comment (bernardobelchior) [inline packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts:240]: Couldn't make this work without casting, unfortunately. `satisfies` didn't work either.

File: packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts [hunk 2]
```diff
@@ -106,138 +102,118 @@ export function computeAxisValue<T extends ChartSeriesType>({
...
+    if (filter) {
+      const [minData, maxData] = getAxisExtremum(
+        axis,
+        axisDirection,
+        seriesConfig as ChartSeriesConfig<CartesianChartSeriesType>,
+        axisIndex,
+        formattedSeries,
+        filter,
+      );
+      scale = scale.copy();
```
Comment (alexfauquette) [inline packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts:194]: Are you sure this effectively cut the refernce with the `scales`?

File: packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts [hunk 3]
```diff
@@ -106,138 +102,118 @@ export function computeAxisValue<T extends ChartSeriesType>({
...
-
-    const [minData, maxData] = getAxisExtremum(
-      axis,
-      axisDirection,
-      seriesConfig as ChartSeriesConfig<CartesianChartSeriesType>,
-      axisIndex,
-      formattedSeries,
-      zoom === undefined && !zoomOption ? getFilters : undefined, // Do not apply filtering if zoom is already defined.
-    );
+    const filter = zoom === undefined && !zoomOption ? getFilters : undefined; // Do not apply filtering if zoom is already defined.
```
Comment (alexfauquette) [inline packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts]: Nitpick: you could move this line next to only place were you're using it (the `if(filter) { ... }`)

File: packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts (hunk 1 above)
Comment (alexfauquette) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts:240]: Yes, I assume it's because the scale type comes from a distinct object. So it TS cannot do the relation between the `scaleType` and the `scale`.

I don't think their is an easy workaround except the one you did previously by having some line of codes enforcing the scale and scaleType to be coherent like `isBandScale(scale) && isBandScaleConfig(axis)`

File: packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts [hunk 4]
```diff
@@ -106,138 +102,118 @@ export function computeAxisValue<T extends ChartSeriesType>({
...
+      const [minData, maxData] = getAxisExtremum(
+        axis,
+        axisDirection,
+        seriesConfig as ChartSeriesConfig<CartesianChartSeriesType>,
+        axisIndex,
+        formattedSeries,
+        filter,
+      );
+      scale = scale.copy();
+      scale.domain([minData, maxData]);
```
Comment (alexfauquette) [inline packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts:195]: This should be slightly more complex. The filters is here to remove some data points.

But it should still apply domainLimit strategies: `nice(tickNumber)` or the `domainLimit(min, max)` if defined.


We could add a test with a BarChart with series data set to `[1, 4.5, 5]` and x-axis zoom set to `[0, 50]` (ditch the last item)

- `domainLimit='nice'`: y-axis should go from 0 to 5
- `domainLimit='strict'`: y-axis should go from 0 to 4.5

Dark mode is the actual docs demo, light mode is this PR preview


https://github.com/user-attachments/assets/ef2fa7e7-38ae-4e4c-85de-a38797384b03

This will have a side effect impact: The `domainLimit` as a function could be called twice:
- one when creating scales
- one when applying the filter

Not a big deal for me

File: packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts (hunk 2 above)
Comment (bernardobelchior) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts:194]: It should, according to [the docs](https://d3js.org/d3-scale/band#band_copy):

> Changes to this scale will not affect the returned scale, and vice versa.

Comment (alexfauquette) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts:194]: > It should, according to [the docs](https://d3js.org/d3-scale/band#band_copy):

Yes they do something simple
```js
const x1 = d3.scaleBand(["a", "b", "c"], [0, 960]);
const x2 = x1.copy();
```

You do something slightly trickier

```js
const scales = { scaleId: d3.scaleBand(["a", "b", "c"], [0, 960]); }
let x1 = scales['scaleId'];
x1 = x1.copy();
```

But it looks good :+1:

File: packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts (hunk 4 above)
Comment (bernardobelchior) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/computeAxisValue.ts:195]: Should be fixed with the most recent commit 👍

File: packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.test.ts [hunk 5]
```diff
@@ -60,8 +62,10 @@ describe('createDiscreteScaleGetAxisFilter', () => {
 
 describe('createContinuousScaleGetAxisFilter', () => {
   describe('linear scale', () => {
+    const scale = getScale('linear', [0, 100], [0, 100]).nice();
```
Comment (JCQuintas) [inline packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.test.ts:65]: All tests for `createContinuousScaleGetAxisFilter` use `nice` now. 

We should also test the strict behaviour.

Comment (bernardobelchior) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.test.ts:65]: > We should also test the strict behaviour.

What issues do you think testing the strict behavior will catch? As far as I can see, `createContinuousScaleGetAxisFilter` isn't affected by whether the domain is nice or not.

Comment (JCQuintas) [reply packages/x-charts/src/internals/plugins/featurePlugins/useChartCartesianAxis/createAxisFilterMapper.test.ts:65]: Ah true, I was still thinking of the previous behaviour 🤔

**Review by alexfauquette — CHANGES_REQUESTED** [review]
You have an issue with preview

https://github.com/user-attachments/assets/03d8a9d4-47f1-44af-8a86-a488b612965f

**Comment by bernardobelchior** [comment]
> You have an issue with preview
> 
>  Capture.video.du.2025-09-15.18-20-50.mp4

Fixed and added a visual regression test 👍

**Comment by alexfauquette** [comment]
@bernardobelchior I fixed scritp issues, and added `filterMode: 'discard',` to your visual regression test such that it now test the two regression I spotted during the review

- preview scalling like main chart
- discard no applying the `nice()` method to scale
