### PR TITLE
[fields] Fix section clearing behavior on Android

### LINKED ISSUE #13620: [fields] on Android: deleting the date template is possible and breaks the component
### Steps to reproduce

Link to live example: (required)

Steps:
1. Implement the DateField component 
2. Open the page in mobile - android only 
3. focus on the MM for example, and the use the backspace and delete the "MM" successfully 

### Current behavior

When trying to delete the "MM/DD/YYYY" template of the dateField component from an android mobile, it deletes the template

### Expected behavior

There is no way to delete the template "MM/DD/YYYY" of the component 

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 11.3.1
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 126.0.6478.114
    Edge: Not Found
    Safari: 14.1

```
</details>

**Search keywords**: DateField Mobile

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #13620 

Related to #10399.

The present behavior and test for section clearing on Android seemed incorrect.
It doesn't work like that on Desktop.
The change aligns the section clearing behavior between Desktop and Android.

~There is still an issue on Chrome on Android with syncing the focus on a section, which has a different length placeholder than the value (i.e. full length month).~

https://github.com/mui/mui-x/assets/4941090/72bcfc89-83d7-4c64-936d-f226e1ad65fd

~Maybe because it requires an extra repaint/resize cycle. 🤷 
If you have ideas on how to solve it—I'm all ears.
P.S. Wrapping the `syncSelectionToDOM` call in a `setTimeout` fixes the issue, but introduces a delay and causes the caret to be momentarily visible.
P.P.S. The situation with the MS Swiftkey keyboard is even worse... All the section selections are no syncked after section removal. 🙈~
This fix seems to avoid the problem and works stable: https://github.com/mui/mui-x/pull/13652/commits/73ed8e9e9e3455eab8e5cd7d8ccae8fd5739393c (albeit with a slight chance of endless recursion in an unforeseen case).

In any case, I'd be happy to ship this fix as is, because the current state of Chrome on Android with Gboard is pretty bad-unusable when deleting. 🙈

### CODE REVIEW

**Review by flaviendelangle — APPROVED** [review]
If it's improves the current behavior, I think we can ship it

Is the behavior better / worse in v7 approach?

File: packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts [hunk 1]
```diff
@@ -162,6 +162,18 @@ export const useFieldV6TextField: UseFieldTextField<false> = (params) => {
...
+          setTimeout(() => {
+            // handle case when the selection is not updated correctly
+            // could happen on Android
+            if (
+              inputRef.current &&
+              inputRef.current === getActiveElement(document) &&
+              (inputRef.current.selectionStart !== selectionStart ||
+                inputRef.current.selectionEnd !== selectionEnd)
+            ) {
+              interactions.syncSelectionToDOM();
```
Comment (LukasTy) [inline packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts:174]: I'm afraid of a possible endless recursion here. 🤔 
WDYT, do we need an additional safeguard against it here?

**Comment by LukasTy** [comment]
> Is the behavior better / worse in v7 approach?

It's better on `enableAccessibleDOMStructure`.
It needs additional testing on various keyboards, but overall works great.

File: packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts (hunk 1 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/useField/useFieldV6TextField.ts:174]: Do you have a clearer idea of a scenario when this recursion might happen?
Tbh I don't really know how to add safeguards here :grimacing:
