### PR TITLE
[charts] Add a localization provider

### LINKED ISSUE #16963: [charts] Pie chart loading text not localizable
### Steps to reproduce

https://github.com/mui/mui-x/blob/fd688626ec58f714590cfbb6f52261e1c4b135f6/docs/data/charts/styling/CustomOverlay.tsx#L47-L49

### Current behavior

Loading data.. is not localisable. hard coded in

### Expected behavior

should be localisable

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Linux 6.11 Ubuntu 24.10 24.10 (Oracular Oriole)
  Binaries:
    Node: 20.16.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
    pnpm: 9.15.5 - /usr/local/bin/pnpm
  Browsers:
    Chrome: Not Found

~$ 

```
</details>

**Search keywords**: Loading Data...

### PR DESCRIPTION
**Pull request by alexfauquette**
Close #16963

This introduces the localisation for charts. It will be more useful when we introduce the toolbar since buttons and helpers will need some text.

For info, the data grid put its locales in its `apiRef` and the pickers in a dedicated context.

I went with the picker approach because we have a similar issue: defining the locale once and using it in multiple components and their subcomponent.

Having a dedicated provider allows targeting it in the MUI theme's defaultProps.

Preview: https://deploy-preview-17325--material-ui-x.netlify.app/x/react-charts/localization/

### CODE REVIEW

File: packages/x-charts-pro/src/BarChartPro/BarChartPro.tsx [hunk 1]
```diff
@@ -192,6 +192,10 @@ BarChartPro.propTypes = {
    * @default false
    */
   loading: PropTypes.bool,
+  /**
+   * Locale for charts components texts
```
Comment (bernardobelchior) [inline packages/x-charts-pro/src/BarChartPro/BarChartPro.tsx:196]:
```suggestion
   * Locale text for charts components
```

File: packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.test.tsx [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+    const localeText: ChartsLocaleText = handleContextChange.lastCall.args[0].localeText;
+    expect(localeText.noData).to.equal('Priotized');
+  });
+
+  it('should prioritize deepest LocalizationProvider when using nested ones', () => {
+    const handleContextChange = spy();
+
+    render(
+      <ChartsLocalizationProvider localeText={{ noData: 'Not Priotized' }}>
+        <ChartsLocalizationProvider localeText={{ noData: 'Priotized' }}>
```
Comment (bernardobelchior) [inline packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.test.tsx:83]:
```suggestion
      <ChartsLocalizationProvider localeText={{ noData: 'Not Prioritized' }}>
        <ChartsLocalizationProvider localeText={{ noData: 'Prioritized' }}>
```

File: packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.test.tsx [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+          <ContextListener onContextChange={handleContextChange} />
+        </ChartsLocalizationProvider>
+      </ChartsLocalizationProvider>,
+    );
+
+    const localeText: ChartsLocaleText = handleContextChange.lastCall.args[0].localeText;
+    expect(localeText.noData).to.equal('Priotized');
```
Comment (bernardobelchior) [inline packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.test.tsx:90]:
```suggestion
    expect(localeText.noData).to.equal('Prioritized');
```

File: packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.test.tsx [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+    render(
+      <ChartsLocalizationProvider localeText={{ noData: 'Priotized' }}>
+        <ChartsLocalizationProvider localeText={{ loading: 'Other Locale' }}>
+          <ContextListener onContextChange={handleContextChange} />
+        </ChartsLocalizationProvider>
+      </ChartsLocalizationProvider>,
+    );
+
+    const localeText: ChartsLocaleText = handleContextChange.lastCall.args[0].localeText;
+    expect(localeText.noData).to.equal('Priotized');
```
Comment (bernardobelchior) [inline packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.test.tsx:105]:
```suggestion
    expect(localeText.noData).to.equal('Prioritized');
```

File: packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.test.tsx [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
+  });
+
+  it("should not loose locales from higher LocalizationProvider when deepest one don't have the translation key", () => {
```
Comment (bernardobelchior) [inline packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.test.tsx:93]:
```suggestion
  it("should not lose locales from higher LocalizationProvider when deepest one don't have the translation key", () => {
```

File: packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.tsx [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+ * Demos:
+ *
+ * - [Date format and localization](https://mui.com/x/react-date-pickers/adapters-locale/)
+ * - [Calendar systems](https://mui.com/x/react-date-pickers/calendar-systems/)
+ * - [Translated components](https://mui.com/x/react-date-pickers/localization/)
+ * - [UTC and timezones](https://mui.com/x/react-date-pickers/timezone/)
+ *
+ * API:
+ *
+ * - [LocalizationProvider API](https://mui.com/x/api/date-pickers/localization-provider/)
```
Comment (bernardobelchior) [inline packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.tsx:38]: Should we update these links?

File: packages/x-charts/src/hooks/useChartsLocalization.ts [hunk 7]
```diff
@@ -0,0 +1,17 @@
+import * as React from 'react';
+import { ChartsLocalizationContext } from '../ChartsLocalizationProvider/ChartsLocalizationProvider';
+
+export const useChartsLocalization = () => {
+  const localization = React.useContext(ChartsLocalizationContext);
+  if (localization === null) {
+    throw new Error(
+      [
+        'MUI X: Can not find the charts pickers localization context.',
```
Comment (bernardobelchior) [inline packages/x-charts/src/hooks/useChartsLocalization.ts:9]:
```suggestion
        'MUI X: Can not find the charts localization context.',
```

File: packages/x-charts/src/locales/frFR.ts [hunk 8]
```diff
@@ -0,0 +1,10 @@
+import { ChartsLocaleText } from './utils/chartsLocaleTextApi';
+import { getChartsLocalization } from './utils/getChartsLocalization';
+
+const frFRCharts: Partial<ChartsLocaleText> = {
+  // No group
```
Comment (bernardobelchior) [inline packages/x-charts/src/locales/frFR.ts:5]: What do you mean by "no group"?

File: packages/x-charts/src/locales/utils/chartsLocaleTextApi.ts [hunk 9]
```diff
@@ -0,0 +1,12 @@
+export interface ChartsLocaleText {
+  /**
+   * Title displayed in the overlay if `loading` is `true`.
+   */
+  loading: string;
+  /**
+   * Title displayed in the overlay if their is no data to display.
```
Comment (bernardobelchior) [inline packages/x-charts/src/locales/utils/chartsLocaleTextApi.ts:7]:
```suggestion
   * Title displayed in the overlay if there is no data to display.
```

File: packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.tsx (hunk 6 above)
Comment (alexfauquette) [reply packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.tsx:38]: Thanks, I forgot it

File: packages/x-charts/src/locales/frFR.ts (hunk 8 above)
Comment (alexfauquette) [reply packages/x-charts/src/locales/frFR.ts:5]: I added one to remove this default comment

File: docs/data/charts/localization/ChartsLocalizationTableNoSnap.js [hunk 10]
```diff
@@ -0,0 +1,7 @@
+import * as React from 'react';
+import LocalisationTable from 'docsx/src/modules/components/LocalizationTable';
+import data from './data.json';
+
+export default function ChartsLocalizationTableNoSnap() {
+  return <LocalisationTable data={data} />;
```
Comment (bernardobelchior) [inline docs/data/charts/localization/ChartsLocalizationTableNoSnap.js:6]:
```suggestion
import LocalizationTable from 'docsx/src/modules/components/LocalizationTable';
import data from './data.json';

export default function ChartsLocalizationTableNoSnap() {
  return <LocalizationTable data={data} />;
```

File: packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.tsx [hunk 11]
```diff
@@ -0,0 +1,88 @@
...
+);
+
+if (process.env.NODE_ENV !== 'production') {
+  ChartsLocalizationContext.displayName = 'ChartsLocalizationContext';
+}
+
+export interface ChartsLocalizationProviderProps {
+  children?: React.ReactNode;
+  /**
+   * Locale for charts components texts.
```
Comment (bernardobelchior) [inline packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.tsx:23]:
```suggestion
   * Localized text for chart components.
```

**Review by bernardobelchior — APPROVED** [review]

**Comment by oliviertassinari** [comment]
How does starting to follow the docs structure for l10n in #17475 feel?

File: scripts/l10n.ts [hunk 12]
```diff
@@ -39,6 +39,13 @@ const packagesWithL10n = [
     localesRelativePath: 'packages/x-date-pickers/src/locales',
     documentationReportPath: 'docs/data/date-pickers/localization/data.json',
   },
+  {
+    key: 'charts',
+    reportName: '📊 Charts',
+    constantsRelativePath: 'packages/x-charts/src/constants/defaultLocale.ts',
```
Comment (oliviertassinari) [inline scripts/l10n.ts:45]: How does aligning all of those to the `pickers` feel? Propose in #17475

```suggestion
    constantsRelativePath: 'packages/x-charts/src/locales/enUS.ts',
```

File: packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.tsx [hunk 13]
```diff
@@ -0,0 +1,88 @@
...
+/**
+ * Demos:
+ *
+ * - [localization](https://mui.com/x/react-charts/localization/)
+ *
+ * API:
+ *
+ * - [ChartsLocalizationProvider API](https://mui.com/x/api/charts/charts-localization-provider/)
+ */
+function ChartsLocalizationProvider(inProps: ChartsLocalizationProviderProps) {
```
Comment (oliviertassinari) [inline packages/x-charts/src/ChartsLocalizationProvider/ChartsLocalizationProvider.tsx:37]: What's the point of having a `ChartsLocalizationProvider`? I mean, why do we need this when we have the `ThemeProvider`?

I guess this is the unstyled version. But then, why don't we have a `LocalizationProvider` component that is shared between all components?

File: docs/data/charts/localization/localization.md [hunk 14]
```diff
@@ -0,0 +1,115 @@
...
+```
+
+Note that `createTheme()` accepts any number of arguments.
+If you are already using the [translations of the core components](/material-ui/guides/localization/#locale-text), you can add `frFR` as a new argument.
+The same import works for Charts Pro as it's an extension of Charts.
+
+```jsx
+import { createTheme, ThemeProvider } from '@mui/material/styles';
+import { BarChart } from '@mui/x-charts/BarChart';
+import { frFR } from '@mui/x-charts/locales';
```
Comment (oliviertassinari) [inline docs/data/charts/localization/localization.md:53]: Might be clearer

```suggestion
import { chartsfrFR } from '@mui/x-charts/locales';
```

Comment (alexfauquette) [reply docs/data/charts/localization/localization.md:53]: That would break the logic  we use on all packages and their related example.

For now, all packages export locales as follow:

```jsx
import { xxYY } from '@mui/[packageName]/locales';
```

And for multiple packages, we encourage them to do
```jsx
import { xxYY as [packageName]XxYY } from '@mui/[packageName]/locales';
```

Comment (alexfauquette) [reply docs/data/charts/localization/localization.md:107]: While doing the update, I understood your point. Exporting an object that contained only the `localeText` content.

I propose to export `frFR` and `frFRLocaleText` to be more explicit that `chartsfrFR` that does not says if the content is made for `localText` prop of the `createTheme()`

**Comment by alexfauquette** [comment]
I tried the structure proposed in #17475

I moved the `### Built-in locales` higher in the order because I felt the need to introduce the information "We have some translation" before explaining how to use them.

I moved the table of available locales completely at the end of the page because it can grow a lot (like the [data grid one](https://mui.com/x/react-data-grid/localization/#supported-locales) ) and then cut the reading experience
