### PR TITLE
[DataGrid] Fix `checkboxSelectionVisibleOnly` behavior with server-side pagination

### LINKED ISSUE #14070: [data grid] `checkboxSelectionVisibleOnly` with server-side pagination doesn't select all items on the second page
### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-f1gyh1?file=Demo.tsx

```
<DataGridPro
  columns={columns}
  unstable_dataSource={dataSource}
  pagination
  initialState={initialStateWithPagination}
  pageSizeOptions={[10, 20, 50]}
  checkboxSelection
  checkboxSelectionVisibleOnly
/>
```

Steps:
1. Select all items by clicking on the main (Select All) checkbox in the header
2. Navigate to page 2 and click the same Select All checkbox

### Current behavior

Only 1 item is selected on the second page.

### Expected behavior

All items are selected on the second page.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: checkboxSelectionVisibleOnly, pagination, checkboxSelection
**Order ID**: 87418

### PR DESCRIPTION
**Pull request by MBilalShafi**
Fixes #14070

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts [hunk 1]
```diff
@@ -446,14 +446,15 @@ export const useGridRowSelection = (
       const shouldLimitSelectionToCurrentPage =
         props.checkboxSelectionVisibleOnly && props.pagination;
 
-      const rowsToBeSelected = shouldLimitSelectionToCurrentPage
-        ? gridPaginatedVisibleSortedGridRowIdsSelector(apiRef)
-        : gridExpandedSortedRowIdsSelector(apiRef);
+      const rowsToBeSelected =
+        shouldLimitSelectionToCurrentPage && props.paginationMode === 'client'
```
Comment (arminmeh) [inline packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:450]: should `props.paginationMode === 'client'` be part of the `shouldLimitSelectionToCurrentPage` evaluation?

Comment (MBilalShafi) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:450]: Sure we could. Although it's a very trivial thing it seemed to me more logical to keep them separate.

`shouldLimitSelectionToCurrentPage` relates to the status `checkboxSelectionVisibleOnly`, two conditions much be satisfied in order for the `gridPaginatedVisibleSortedGridRowIdsSelector` to be used in this use case.
1. `shouldLimitSelectionToCurrentPage` is true.
2. Pagination is not "server-side"

We could even remove the variable `shouldLimitSelectionToCurrentPage` and combine the condition though.

**Review by arminmeh — APPROVED** [review]
