### PR TITLE
[fields] Make the ArrowUp / ArrowDown edition only impact the active section

### LINKED ISSUE #7934: [fields] Editing a section value using `ArrowDown` / `ArrowUp` should not impact other section's value
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/krz4s0?file=/demo.tsx

Steps:
1. Click on AM/PM, minutes, or Hour
2. Press and hold the up arrow (or down arrow)

### Current behavior 😯

Notice the date changes when cycling through AM/PM or Hours and the hour changes when cycling over the minutes from 59 -> 00 or 00 -> 59

### Expected behavior 🤔

The date and hours should stay the same when rolling over those fields. 

### Context 🔦

For non-sighted users, changing the value in a field they have already completed is a terrible experience. Even sighted users may have yet to notice that date/time changes, which can cause invalid or unwanted times/dates to be entered.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
Run via codesandbox from the Beta Site
Chrome Version 109.0.5414.120 (Official Build) (64-bit)
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
Closes #7934

### CODE REVIEW

File: packages/x-date-pickers/src/AdapterLuxon/index.ts [hunk 1]
```diff
@@ -33,12 +33,10 @@ const formatTokenMap: MuiFormatTokenMap = {
   LL: 'month',
   LLL: { sectionName: 'month', contentType: 'letter' },
   LLLL: { sectionName: 'month', contentType: 'letter' },
-  LLLLL: { sectionName: 'month', contentType: 'letter' },
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/AdapterLuxon/index.ts:36]: We can't correctly support those single letter month since they can represent several months (and are by definition impossible to parse).

File: packages/x-date-pickers/src/AdapterMoment/index.ts [hunk 2]
```diff
@@ -7,7 +7,6 @@ import { MuiFormatTokenMap, MuiPickersAdapter } from '../internals/models';
 const formatTokenMap: MuiFormatTokenMap = {
   // Month
   M: 'month',
-  Mo: 'month',
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/AdapterMoment/index.ts:10]: We don't support `2nd` type format, only `2`.

File: packages/x-date-pickers/src/AdapterMomentJalaali/index.ts [hunk 3]
```diff
@@ -106,6 +105,10 @@ export class AdapterMomentJalaali
       : date.clone().add(count, 'jMonth');
   };
 
+  public setMonth = (date: Moment, month: number) => {
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/AdapterMomentJalaali/index.ts:108]: The date-io adapter is setting the `month` instead of `jMonth`

File: packages/x-date-pickers/src/tests/fieldKeyboardInteraction.test.tsx [hunk 4]
```diff
@@ -39,8 +43,8 @@ const adapterToTest = [
   'dayjs',
   'moment',
   'date-fns-jalali',
-  'moment-hijri',
-  'moment-jalaali',
+  // 'moment-hijri',
+  // 'moment-jalaali',
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/tests/fieldKeyboardInteraction.test.tsx:47]: In my browser, if I render an `AdapterMomentJalaali` date, the year is a number but in the test it's some character (from the persian alphabet I suppose) which don't work at all with our editing (since we are doing `Number(section.value)`).

I tried to understand why and failed...
If you want to have a look, for me everything works well on my browser but the tests behavior make no sense...

**Review by flaviendelangle — COMMENTED** [review]
Moving the format token tests to a section-based editing instead of a date-based editing highlighted a few small bugs

File: packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts [hunk 5]
```diff
@@ -832,38 +670,86 @@ export const validateSections = <TSection extends FieldSection>(
   }
 };
 
-export const mergeDateIntoReferenceDate = <
-  TDate,
-  TSection extends Omit<FieldSection, 'start' | 'end' | 'startInInput' | 'endInInput'>,
->(
+const transferDateSectionValue = <TDate>(
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts:673]: I tried to make this function simpler to understand now that it is the only one doing transformation directly on a date.
No more lookup with complex typing, I just have one dumb `switch`

File: packages/x-date-pickers/src/AdapterMoment/index.ts [hunk 6]
```diff
@@ -29,7 +27,6 @@ const formatTokenMap: MuiFormatTokenMap = {
   Y: 'year',
   YY: 'year',
   YYYY: 'year',
-  YYYYYY: 'year',
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/AdapterMoment/index.ts:32]: This format looks like `-001970 -001971 ... +001907 +001971`

It's not a valid format for us, we don't handle `-` and `+` signes

File: packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts [hunk 7]
```diff
@@ -68,226 +68,133 @@ export const getDaysInWeekStr = <TDate>(utils: MuiPickersAdapter<TDate>, format:
...
+
     default: {
-      return date;
+      return [];
     }
   }
 };
 
-export const adjustInvalidDateSectionValue = <TDate, TSection extends FieldSection>(
+export const adjustSectionValue = <TDate, TSection extends FieldSection>(
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts:119]: This function changes a lot.
It now uses a similar approach to the character editing.
We never try to parse a date (except to get today's year).

Instead for digit editing we rely on the boundaries and for letter editing on the option list.

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/useField/useField.utils.ts:119]: The old approach had problems with days of the month for example, because by parsing today's date, we had a "max" of "28" when using the field in February.

The new version should be more robust since it uses the boundaries which have a smarter behavior.

File: packages/x-date-pickers/src/tests/fieldKeyboardInteraction.test.tsx (hunk 4 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/tests/fieldKeyboardInteraction.test.tsx]: I've pushed [a fix for `moment-jalaali`](https://github.com/mui/mui-x/pull/7993/commits/7fd66494ca1d9ab913c700146d471d3edfad3050). Let me know if you think that it's an inappropriate one. 🙈 
As for `moment-hijri`, we are well aware that it is broken and have listed it in our doc. 🤔

**Review by LukasTy — APPROVED** [review]
This is an insane improvement towards having sanity maintaining fields. 🙌 🚀 ❤️ 
Pushed a few minor fixes as well as leaving a couple of nit-pick comments. 😉

File: packages/x-date-pickers/src/TimeField/tests/editing.TimeField.test.tsx [hunk 8]
```diff
@@ -109,26 +109,6 @@ describe('<TimeField /> - Editing', () => {
           valueToSelect: adapterName === 'date-fns' ? 'pm' : 'PM',
         });
       });
-
-      it('should go from AM to PM when the current value is 00:00 AM', () => {
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-date-pickers/src/TimeField/tests/editing.TimeField.test.tsx:113]: Pressing `ArrowDown` on the hour no longer impact the meridiem since they are independent right ?

File: packages/x-date-pickers/src/tests/fieldKeyboardInteraction.test.tsx (hunk 4 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/tests/fieldKeyboardInteraction.test.tsx]: :partying_face: 

We just have a small issue where `moment` keeps using the persian on the rest of its test

Comment (flaviendelangle) [reply packages/x-date-pickers/src/tests/fieldKeyboardInteraction.test.tsx]: I'll reset it in an `after`

File: packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx [hunk 9]
```diff
@@ -134,12 +134,12 @@ describe('<DateField /> - Editing', () => {
       });
     });
 
-    it('should decrement go to the first month of the next year when when a value in December is provided', () => {
+    it('should go to the first month of the current year when when a value in December is provided', () => {
```
Comment (LukasTy) [inline packages/x-date-pickers/src/DateField/tests/editing.DateField.test.tsx:137]: 🙈 
```suggestion
    it('should go to the first month of the current year when a value in December is provided', () => {
```

File: packages/x-date-pickers/src/TimeField/tests/editing.TimeField.test.tsx (hunk 8 above)
[the remark this answers is not in the document]
Comment (LukasTy) [reply packages/x-date-pickers/src/TimeField/tests/editing.TimeField.test.tsx:113]: Ah, yes, sorry, I've missed the value of `valueToSelect`. 🙈 🤦
