### PR TITLE
[tree view] Fix unwanted behaviors on the item re-ordering

### LINKED ISSUE #20130: [tree view] Ordering Drag&Drop Behaviour
### Steps to reproduce

Open https://mui.com/x/react-tree-view/rich-tree-view/ordering/#limit-the-re-ordering

### Current behavior

1 . **isItemReorderable** is not working as name suggests
When limiting reodering using the `isItemReorderable` prop, the item is not only disabled for dragging, but is also no longer a valid drop target.

Dragging into a folder where `apiRef.current!.getItemOrderedChildrenIds(itemId).length === 0` is `false` does not work anymore.

https://github.com/user-attachments/assets/71252ed7-cf61-443a-a5c2-398958c4002d

2. **Cancel Dragging** 
When dragging an item, you cannot cancel the drag event when staying on the item you started dragging.
The DragPreview for the latest valid target stays active.

https://github.com/user-attachments/assets/db0c9411-4bd9-4a56-9c5b-cf9d03e8c969

### Expected behavior

1.  when using `isItemReorderable` the item should still be a valid drop target.

2. you should be able to cancel dragging without any action, when staying or returning to the original dragged item.

This Bug is kinda critical for us, if the User cannot stop dragging without modifying the tree.

### Context

The current behaviour seems unintended and buggy.

### Your environment

Browser: Chrome

**Search keywords**: treeview drag drop ordering

**Order ID**: 116138

### PR DESCRIPTION
**Pull request by flaviendelangle**
Part of #20301
Fixes #20130 

- [x] Cancel the drag sequence when droping an item on itself
- [x] Use the `contentRef` to determine the current coordinate of the mouse within the target item
- [x] Allow to drop an item onto a non-reorderable item

### CODE REVIEW

**Comment by flaviendelangle** [comment]
I can try to fix the other half of #20130 if it's a small fix :eyes: 
EDIT: Done

File: packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts [hunk 1]
```diff
@@ -20,22 +20,6 @@ export const useTreeViewItemsReordering: TreeViewPlugin<UseTreeViewItemsReorderi
   params,
   store,
 }) => {
-  const canItemBeDragged = React.useCallback(
```
Comment (flaviendelangle) [inline packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts:23]: Was never used
