### PR TITLE
[DataGrid] Replace `forwardRef` with a shim for forward compatibility

### LINKED ISSUE #15770: [data grid] React 19 - everything that depends on `GridRootPropsContext` re-renders on every state change (or root re-render) if the ref prop is present
### Search keywords

N/A

### Latest version

- [X] I have tested the latest version

### Affected products

Data Grid

### Steps to reproduce

Steps:
1. Generic – https://github.com/facebook/react/issues/31613
2. Datagrid specific – https://github.com/mui/mui-x/pull/15549#issuecomment-2493523350

### Current behavior

Read more about on the links above.

Found in the midst of another PR, so opening an issue so it doesn't go overlooked, especially now that there's official React 19 support and React 19 is stable. 

Worth noting that it can also affect instances where developers don't actually provide a ref, but have created an abstracted component over the Datagrid which passes forward the ref prop by explicitly naming it as `ref={ref}` even if `ref={undefined}`. This was the case for us. Which means that the potential share of users affected is much wider.

Not sure if the problem affects any other areas of the DataGrid as well, but probably not as critical as this.

cc @arminmeh, since you worked on the React 19 support

### PR DESCRIPTION
**Pull request by lauri865**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #15770

The shim asserts that Ref is always part of the render function props (even if that is not the case in older versions), this is to force typescript to warn us in case we're accidentally spreading over the ref. Refactored everything to have ref as the last prop as a result:
Screenshot 2024-12-20 at 10 47 52

Ref warning doesn't work with `slotProps` though currently, as they take a slice of the props without the ref. But that can be improved as well I suppose to avoid any footguns.

### CODE REVIEW

File: packages/x-internals/src/forwardRefShim/forwardRefShim.tsx [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+// Compatibility shim that ensures stable props object for forwardRef components
+// Fixes https://github.com/facebook/react/issues/31613
+// We ensure that the ref is always present in the props object (even if that's not the case for older versions of React) to avoid the footgun of spreading props over the ref in the newer versions of React.
+// Footgun: <Component ref={ref} {...props} /> will break past React 19, but the types will now warn us that we should use <Component {...props} ref={ref} /> instead.
+export const forwardRefShim = <T, P = {}>(
+  render: React.ForwardRefRenderFunction<T, P & { ref: React.Ref<T> }>,
+) => {
+  if (reactMajor >= 19) {
+    const Component = (props: any) => render(props, props.ref ?? null);
+    return Component as React.ForwardRefExoticComponent<P>;
```
Comment (romgrk) [inline packages/x-internals/src/forwardRefShim/forwardRefShim.tsx:13]: Might be nice to carry the `render.name` or `render.displayName`, it's useful when profiling performance.

File: packages/x-internals/src/forwardRefShim/forwardRefShim.tsx
Comment (romgrk) [inline packages/x-internals/src/forwardRefShim/forwardRefShim.tsx:1]: I'd call it just `forwardRef`.

**Review by romgrk — APPROVED** [review]

File: packages/x-internals/src/forwardRefShim/forwardRefShim.tsx
Comment (lauri865) [reply packages/x-internals/src/forwardRefShim/forwardRefShim.tsx:1]: fair, renamed

File: packages/x-internals/src/forwardRefShim/forwardRefShim.tsx (hunk 1 above)
Comment (lauri865) [reply packages/x-internals/src/forwardRefShim/forwardRefShim.tsx]: Agree, I think displayName only should be enough – added.

**Comment by arminmeh** [comment]
FYI @mui/x 
You can use this in other components as well

**Comment by oliviertassinari** [comment]
Oh, I love to see this! Can we do the same in http://github.com/mui/material-ui and https://github.com/mui/base-ui?

File: packages/x-data-grid/src/components/virtualization/GridVirtualScrollerRenderZone.tsx [hunk 2]
```diff
@@ -48,13 +49,13 @@ const GridVirtualScrollerRenderZone = React.forwardRef<
...
   return (
     <VirtualScrollerRenderZoneRoot
-      ref={ref}
       className={clsx(classes.root, className)}
       ownerState={rootProps}
       style={{
         transform: `translate3d(0, ${offsetTop}px, 0)`,
       }}
       {...other}
+      ref={ref}
```
Comment (oliviertassinari) [inline packages/x-data-grid/src/components/virtualization/GridVirtualScrollerRenderZone.tsx:58]: This change is wrong no? The ref needs to arrive before `{...other}`: otherwise, it goes into the slow branch

SCR-20241229-cgoo

[Source](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=DwNQlgTgLgrghgGwMoGMIHsEIKYQErYB2AJrgFrqHZ7rpQBQABIygnAM7sBycAttgF4A3q3YAPABSsO7bOwB0GOgBoWbTj34BKAL5NG6AO5UISKHCiChSqAAUMAB3Z7m7KAE8cwofuZQIcITsAGboELwAXIwABv6B7GyWAMzEEgAMqgAkQujBwbJQACroDjoOYqppWtHK-joujELyzXQAFrgNENjBwl3BegD0AHxAA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Ctypescript&prettier=true&targets=Node-14&version=7.26.4&externalPlugins=%40babel%2Fplugin-transform-class-properties%407.24.6%2C%40babel%2Fplugin-transform-class-static-block%407.24.6%2C%40babel%2Fplugin-transform-runtime%407.25.7&assumptions=%7B%7D)

See https://github.com/facebook/react/blob/50f00fd876b0b92b243cd8b54a222f9577446392/packages/react/src/jsx/ReactJSXElement.js#L302C7-L302C15

Comment (oliviertassinari) [reply packages/x-data-grid/src/components/virtualization/GridVirtualScrollerRenderZone.tsx:58]: Na, nevermind. I'm confusing ref and key.

**Comment by cherniavskii** [comment]
> Should we do the same in [http://github.com/mui/material-ui](https://github.com/mui/material-ui?rgh-link-date=2024-12-29T00%3A26%3A37Z) and [mui/base-ui](https://github.com/mui/base-ui?rgh-link-date=2024-12-29T00%3A26%3A37Z) to improve performance?

Yes, I think so 👍🏻

**Comment by oliviertassinari** [comment]
So today, forwardRef in React 19 looks like this: https://github.com/facebook/react/blob/7aa5dda3b3e4c2baa905a59b922ae7ec14734b24/packages/react/src/ReactForwardRef.js#L51. Almost the same as in React 18.
It seems to create a custom element type. Looking at how React resolves those, I couldn't find obvious source of slowness.

So if this is accurate, we should revert this PR once https://github.com/facebook/react/issues/31613 is fixed.

**Comment by cherniavskii** [comment]
>So if this is accurate, we should revert this PR once https://github.com/facebook/react/issues/31613 is fixed.

Chances are it won't be fixed – see https://github.com/mui/mui-x/issues/15770#issuecomment-2523670430
