### PR TITLE
[TreeView]: allow reordering item to bottom

### LINKED ISSUE #16171: [tree view] Cannot reorder elements to the bottom of the tree view if the last item has children
### Steps to reproduce

Steps:
1. Open this link to live example: https://mui.com/x/react-tree-view/rich-tree-view/ordering/
2. In the top "Enable drag-and-drop reordering" example, attempt to drag any element below the last element in the tree

### Current behavior

In the example, the final item in the list is highlighted and the item is dropped within.

### Expected behavior

A line should be displayed under the final item in the list, and on drop the dragged item should appear at the top-level of the tree.

### Context

I'm trying to display items that can be reordered within a tree view, but they can't be reordered freely.

### Your environment

I was able to replicate this in the sample/demo environment, but here's my local configuration:

```  
  System:
    OS: macOS 15.2
  Binaries:
    Node: 18.8.0 - ~/.config/nvm/versions/node/v18.8.0/bin/node
    Yarn: Not Found
    npm: 8.18.0 - ~/.config/nvm/versions/node/v18.8.0/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Safari: 18.2
  npmPackages:
    @emotion/react: ^11.10.5 => 11.11.1
    @emotion/styled: ^11.9.3 => 11.11.0
    @mui/base:  5.0.0-beta.67
    @mui/core-downloads-tracker:  6.2.1
    @mui/lab: ^6.0.0-beta.20 => 6.0.0-beta.20
    @mui/material: ^6.2.1 => 6.2.1
    @mui/private-theming:  6.2.1
    @mui/styled-engine:  6.2.1
    @mui/system:  6.2.1
    @mui/types:  7.2.20
    @mui/utils:  5.15.7
    @mui/x-charts: ^6.19.3 => 6.19.3
    @mui/x-data-grid:  6.15.0
    @mui/x-data-grid-pro: ^6.9.1 => 6.15.0
    @mui/x-date-pickers: ^5.0.15 => 5.0.20
    @mui/x-internals:  7.23.0
    @mui/x-license:  7.23.2
    @mui/x-license-pro: ^6.0.4 => 6.10.2
    @mui/x-tree-view:  7.23.2
    @mui/x-tree-view-pro: ^7.23.2 => 7.23.2
    @types/react: 18.0.33 => 18.0.33
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.3.1 => 18.3.1
    typescript: ^5.2.2 => 5.2.2
```

**Search keywords**: tree view, reordering, bottom

**Order ID**: 87493

### PR DESCRIPTION
**Pull request by jyash97**
Closes #16171 

Currently, we weren't allowing the items to be reordered to the bottom of the list, I added a condition to `reorder-below` in case we reach the end of the list. Attaching a video in order to show the working of the current fix.

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

https://github.com/user-attachments/assets/3279a4e8-0906-428e-9580-e907f49de0bb

### CODE REVIEW

File: packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts [hunk 1]
```diff
@@ -97,16 +99,18 @@ export const useTreeViewItemsReordering: TreeViewPlugin<UseTreeViewItemsReorderi
...
-              parentId: targetItemMeta.parentId,
-              index:
-                targetItemMeta.parentId === draggedItemMeta.parentId &&
-                targetItemIndex > draggedItemIndex
-                  ? targetItemIndex
-                  : targetItemIndex + 1,
-            },
+        // For the last element allow reordering to the bottom
+        'reorder-below':
+          !targetItemMeta.expandable || targetItemIndex + 1 === totalItems
```
Comment (jyash97) [inline packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts:104]: As I am looking into the diff, I feel the condition should be only applicable when `parentId` is `null`

Comment (flaviendelangle) [reply packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts]: For me the same applies with nested elements.
In the video below, I can't move my item below `@mui/x-data-grid-premium` because it is expandable.

https://github.com/user-attachments/assets/82dc47f4-13e9-4be0-a6f9-6ed484383887

**Comment by flaviendelangle** [comment]
Sorry for the delay,
I took a look at the diff and made some changes to correctly support nested items.
Thanks a lot for the contribution, I'll merge it and apply it to the next v8 beta and the v7 stable releases.

**Review by flaviendelangle — APPROVED** [review]

File: packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts (hunk 1 above)
Comment (jyash97) [reply packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts]: yeah make sense, saw your changes, totally make sense. Sorry for the trouble you had to go through for the same. Will try to do better next time

Comment (flaviendelangle) [reply packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts]: It was really not a critisism, I have the small advantage of knowing the codebase.
Community help is always greatly appreciated!
