### PR TITLE
[DataGrid] `printOptions` should respect `hideFooter` root prop

### LINKED ISSUE #14861: [data grid] Cannot print without footer
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/github-kbnsbh?file=src%2Fdemo.tsx

Steps:
1. Use the `DataGrid` component with property `hideFooter={true}`
2. Add a toolbar containing `GridToolbarExport` component without `printOptions={{ hideFooter: true}}`
3. Print the data grid

### Current behavior

Print window does not open, error about missing footer element instead

### Expected behavior

Print window opens

### Context

When the print window is opened, properties are assigned to a missing footer element. I guess there should be a check if the footer actually exists before the following lines 189-191:

https://github.com/mui/mui-x/blob/7bd05d2a516a4569955e8f8cb4d9f578365d71e8/packages/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx#L181-L192

Compare to where the `hideFooter` option is applied and the footer is only removed if it exists:

https://github.com/mui/mui-x/blob/7bd05d2a516a4569955e8f8cb4d9f578365d71e8/packages/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx#L166-L169 

### Your environment

**Search keywords**: DataGrid Print

### PR DESCRIPTION
**Pull request by k-rajat19**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #14861 
Currently, we are enforcing `hideFooter` in `printOptions` to false by default but it should also consider the `hideFooter` root prop value to avoid issues like this.

Before: https://stackblitz.com/edit/github-kbnsbh?file=src%2Fdemo.tsx
After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-9wx4pw

### CODE REVIEW

**Comment by timonla** [comment]
With regards to:
https://github.com/mui/material-ui/blob/488bdd9c7c24aacafb4f6b00fe28dce18ada5828/CONTRIBUTING.md?plain=1#L166

I would suggest to change the PR title to: [DataGrid] Respect hideFooter root prop in printOptions

**Comment by k-rajat19** [comment]
Hi @cherniavskii, are there any blockers to merge this?

File: packages/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx [hunk 1]
```diff
@@ -128,9 +131,9 @@ export const useGridPrintExport = (
       const normalizeOptions = {
         copyStyles: true,
         hideToolbar: false,
-        hideFooter: false,
         includeCheckboxes: false,
         ...options,
+        hideFooter: props.hideFooter || options?.hideFooter,
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx:136]: Shouldn't it be something like `options.hideFooter ?? props.hideFooter`?

Comment (k-rajat19) [reply packages/x-data-grid/src/hooks/features/export/useGridPrintExport.tsx]: I think we can do it without depending on `props.hideFooter` value ? see [27e94d7](https://github.com/mui/mui-x/pull/14863/commits/27e94d70435073b3b6c170e8d7a41453542ee0f7)

**Comment by timonla** [comment]
@k-rajat19 you should really check out this post: https://chris.beams.io/posts/git-commit/ :pray:

**Comment by k-rajat19** [comment]
Thank you!

**Review by romgrk — APPROVED** [review]
