### PR TITLE
[TreeView] Fix the parameters passed for the `canMoveItemToNewPosition` prop

### LINKED ISSUE #14175: [TreeView] `canMoveItemToNewPosition` params not providing correct `itemId` to function
### Steps to reproduce

Steps:
1. Have a page with a RichTreeViewPro component and a tree with multiple items
2. Configure item reordering according to docs
3. Add an implementation of canMoveItemToNewPosition prop
4. Drag and drop a tree item
5. See that params.itemId passed to canMoveItemToNewPosition is the ID of the item at the new position and not the ID of the item being dropped

### Current behavior

Happy to be told i'm wrong on this but  it seems the ID of the item at the new position is passed into canMoveItemToNewPosition (params.itemId) instead of the ID of the item being dropped.

### Expected behavior

The ID of the item being dropped is passed into canMoveItemToNewPosition (params.itemId).

### Context

Trying to implement a drag and drop tree view for displaying a users and groups org structure. Because of this there is no way to know which item is being dropped in canMoveItemToNewPosition.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.5
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 127.0.6533.100
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.10 
    @mui/core-downloads-tracker:  5.14.4 
    @mui/icons-material: ^5.14.1 => 5.14.3 
    @mui/lab: ^5.0.0-alpha.137 => 5.0.0-alpha.139 
    @mui/material: ^5.14.1 => 5.14.4 
    @mui/material-nextjs: ^5.15.5 => 5.15.5 
    @mui/private-theming:  5.16.6 
    @mui/styled-engine:  5.16.6 
    @mui/styles: ^5.14.1 => 5.14.4 
    @mui/system:  5.16.7 
    @mui/types:  7.2.15 
    @mui/utils:  5.16.6 
    @mui/x-data-grid:  6.11.0 
    @mui/x-data-grid-pro: ^6.10.0 => 6.11.0 
    @mui/x-date-pickers:  6.11.0 
    @mui/x-date-pickers-pro: ^6.10.0 => 6.11.0 
    @mui/x-internals:  7.12.0 
    @mui/x-license:  7.12.0 
    @mui/x-license-pro: ^6.10.0 => 6.10.2 
    @mui/x-tree-view: ^7.6.2 => 7.12.1 
    @mui/x-tree-view-pro: ^7.12.1 => 7.12.1 
    @types/react: 18.2.14 => 18.2.14 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ~5.1.3 => 5.1.6 
```
</details>

**Search keywords**: tree-view pro
**Order ID**: 90357

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #14175

### CODE REVIEW

File: packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts [hunk 1]
```diff
@@ -84,7 +84,7 @@ export const useTreeViewItemsReordering: TreeViewPlugin<UseTreeViewItemsReorderi
           isValid = false;
         } else if (canMoveItemToNewPosition) {
           isValid = canMoveItemToNewPosition({
-            itemId,
+            itemId: state.itemsReordering!.draggedItemId,
```
Comment (michelengelen) [inline packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts:87]: shouldn't this be picked up by TS automatically? I mean there is an `if` condition that would essentially discriminate the possibility of it being `undefined`/`null`

Comment (flaviendelangle) [reply packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts:87]: It is not picked up by TS automatically because we are inside a function `checkIfPositionIsValid`, so TS considers that we might have mutated this object between the `if` line 62 and the line your commented :cry:

Comment (michelengelen) [reply packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts:87]: yeah ... i thought so ... weird shortcoming of TS in this case 👍🏼

Comment (JCQuintas) [reply packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts:87]: `state.itemsReordering` is perceived as "mutable", so `typescript` can't ensure it is the same between the two usages. To overcome that you can move the related var into a `const`

```tsx
const itemsReordering = state.itemsReordering
...
if (itemsReordering)
  myFuncWithRequiredProp(itemsReordering)
```

Comment (JCQuintas) [reply packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts:87]: You can also define the type that defines the object as `readonly` 😅

Comment (flaviendelangle) [reply packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts]: I tried the `reaonly` on both `state` and `state.itemsReordering` an TS still complains :cry:

Comment (JCQuintas) [reply packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts]: Probably because the param os the function is not readonly, then `state` itself can be another instance of `state`? I'm unsure 🤔  

Anyways, I wouldn't dive into this rabbit hole just for this, as there are a lot of conditions for that to work correctly. The other alternative (using a `const`) should work properly

Comment (flaviendelangle) [reply packages/x-tree-view-pro/src/internals/plugins/useTreeViewItemsReordering/useTreeViewItemsReordering.ts]: Done

**Review by JCQuintas — APPROVED** [review]
