### PR TITLE
[DataGrid] Merge `page` and `pageSize` props into `paginationModel`

### LINKED ISSUE #3516: [data-grid] Controlled pagination issue
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have a controlled pagination with `onPageChange` and `onPageSizeChange` functions applied on datagrid and pagination mode sets to "server", But sometimes when changing `pageSize` the `onPageSizeChange` is called but `onPageChange` also gets called automatically.

### Expected behavior 🤔

I am expecting that both the  `onPageChange` and `onPageSizeChange` functions should work independently.

### Steps to reproduce 🕹

https://codesandbox.io/s/quirky-tu-i0nox?file=/src/Demo.tsx

Steps:

1. Open console window and observe the output
2. Click pagination next button 3 times and then clear console
3. Now change the page size to 10 

You will probably see the output something like this

Output:
--------
Current Page Size:  10
Current Page:  2

### Context 🔦

I have ajax calls in both functions and currently same ajax calls are being sent multiple times and page state also gets reverted to old state. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```

  Browser: 
    Chrome Version 96.0.4664.110
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.60
    @mui/icons-material: ^5.2.1 => 5.2.4
    @mui/material: ^5.2.4 => 5.2.4
    @mui/private-theming:  5.2.3
    @mui/styled-engine:  5.2.4
    @mui/system:  5.2.4
    @mui/types:  7.1.0
    @mui/utils:  5.2.3
    @mui/x-data-grid-pro: ^5.2.0 => 5.2.0
    @mui/x-license-pro:  5.2.0
    @types/react: ^16.9.41 => 16.14.21
    react: ^16.13.1 => 16.14.0
    react-dom: ^16.8.3 => 16.14.0
    typescript: ^3.9.6 => 3.9.10
```
</details>

### LINKED ISSUE #5624: [data grid] Merge the `pageSize` and `page` into a single `pagination` prop
# Summary 

Merge the `pageSize` and `page` into a single `pagination` prop, they are too entangled to be correctly managed independently.

# Challenge
How to describe the new API?

# Motivation
Improved DX

### PR DESCRIPTION
**Pull request by MBilalShafi**
Closes #5624
Fixes #3516

Before: https://codesandbox.io/s/serverpaginationgrid-material-demo-forked-rts4d?file=/demo.tsx
After: https://codesandbox.io/s/serverpaginationgrid-material-demo-with-paginationmodel-0yhefr?file=/demo.tsx

Docs Preview: https://deploy-preview-7147--material-ui-x.netlify.app/x/react-data-grid/pagination/#pagination-model

### Breaking changes

- The `page` and `pageSize` props and their respective event handlers `onPageChange` and `onPageSizeChange` were removed. Use `paginationModel` and `onPaginationModelChange` instead.

  ```diff
  -<DataGrid page={page} pageSize={pageSize} onPageChange={handlePageChange} onPageSizeChange={handlePageSizeChange} />
  +<DataGrid paginationModel={{ page, pageSize }} onPaginationModelChange={handlePaginationModelChange} />
  ```

- The property `initialState.pagination.page` and `initialState.pagination.pageSize` were also removed. Use `initialState.pagination.paginationModel` instead.

  ```diff
  -initialState={{ pagination: { page: 1, pageSize: 10 } }}
  +initialState={{ pagination: { paginationModel: { page: 1, pageSize: 10 } } }}
  ```

- The `rowsPerPageOptions` prop was renamed to `pageSizeOptions`.

  ```diff
  -<DataGrid rowsPerPageOptions={[10, 20, 50]} />
  +<DataGrid pageSizeOptions={[10, 20, 50]} />
  ```

### CODE REVIEW

File: docs/data/data-grid/api-object/UseGridApiRef.tsx [hunk 1]
```diff
@@ -20,7 +25,13 @@ export default function UseGridApiRef() {
     <Stack spacing={1} sx={{ width: '100%' }} alignItems="flex-start">
       <Button onClick={handleGoToPage1}>Go to page 1</Button>
       <Box sx={{ height: 400, width: '100%' }}>
-        <DataGrid {...data} apiRef={apiRef} pagination pageSize={10} />
+        <DataGrid
+          {...data}
+          apiRef={apiRef}
+          pagination
```
Comment (alexfauquette) [inline docs/data/data-grid/api-object/UseGridApiRef.tsx:31]: Out of scop: `pagination` is forced to `true` in the MIT version. I assume it's a legacy from a demo with pro component
```suggestion
```

File: docs/data/data-grid/pagination/CursorPaginationGrid.tsx [hunk 2]
```diff
@@ -13,30 +13,36 @@ const { useQuery, ...data } = createFakeServer({}, SERVER_OPTIONS);
...
   };
 
   React.useEffect(() => {
     if (!isLoading && pageInfo?.nextCursor) {
       // We add nextCursor when available
-      mapPageToNextCursor.current[page] = pageInfo?.nextCursor;
+      mapPageToNextCursor.current[paginationModel.page] = pageInfo?.nextCursor;
     }
-  }, [page, isLoading, pageInfo?.nextCursor]);
+  }, [paginationModel, isLoading, pageInfo?.nextCursor]);
```
Comment (alexfauquette) [inline docs/data/data-grid/pagination/CursorPaginationGrid.tsx:45]: Not sure

```suggestion
  }, [paginationModel.page, isLoading, pageInfo?.nextCursor]);
```

File: docs/data/data-grid/pagination/PageSizeInitialState.tsx [hunk 3]
```diff
@@ -17,7 +17,7 @@ export default function PageSizeInitialState() {
           ...data.initialState,
           pagination: {
             ...data.initialState?.pagination,
-            pageSize: 25,
+            paginationModel: { pageSize: 25, page: 0 },
```
Comment (alexfauquette) [inline docs/data/data-grid/pagination/PageSizeInitialState.tsx:20]: It should be the default value
```suggestion
            paginationModel: { pageSize: 25 },
```

File: docs/data/data-grid/pagination/pagination.md [hunk 4]
```diff
@@ -33,15 +33,15 @@ You can't use both the `autoPageSize` and `autoHeight` props at the same time be
 
 {{"demo": "PageSizeAuto.js", "bg": "inline"}}
 
-### Initialize the page size
+### Initialize the pagination model
 
-To initialize the page size without controlling it, provide the page size to the `initialState` prop.
+To initialize the pagination model without controlling it, provide the `paginationModel` to the `initialState` prop.
```
Comment (alexfauquette) [inline docs/data/data-grid/pagination/pagination.md:38]:
```suggestion
To initialize the pagination model without controlling it, provide the `paginationModel` to the `initialState` prop.
It allows to specify the `pageSize` and the current `page`.
```

File: docs/data/data-grid/pagination/pagination.md [hunk 5]
```diff
@@ -51,23 +51,23 @@ To initialize the page size without controlling it, provide the page size to the
 
 ### Controlled page size
```
Comment (alexfauquette) [inline docs/data/data-grid/pagination/pagination.md:52]: I think you can merge `page` and `pageSize` sections

```suggestion
### Controlled pagination model
```

File: docs/data/data-grid/state/DirectSelector.tsx [hunk 6]
```diff
@@ -35,7 +40,13 @@ export default function DirectSelector() {
         Toggle the selection of the 1st row of the page
       </Button>
       <Box sx={{ height: 400, mt: 1 }}>
-        <DataGrid apiRef={apiRef} pagination pageSize={10} {...data} />
+        <DataGrid
+          apiRef={apiRef}
+          pagination
```
Comment (alexfauquette) [inline docs/data/data-grid/state/DirectSelector.tsx:45]:
```suggestion
```

File: docs/data/data-grid/state/UseGridSelector.tsx [hunk 7]
```diff
@@ -1,26 +1,30 @@
...
 } from '@mui/x-data-grid';
 import { useDemoData } from '@mui/x-data-grid-generator';
 import Pagination from '@mui/material/Pagination';
 
+const PAGE_SIZE = 10;
+
 function Toolbar() {
   const apiRef = useGridApiContext();
-  const page = useGridSelector(apiRef, gridPageSelector);
+  const paginationModel = useGridSelector(apiRef, gridPaginationModelSelector);
```
Comment (alexfauquette) [inline docs/data/data-grid/state/UseGridSelector.tsx:16]: Not sure about that

```suggestion
  const { page } = useGridSelector(apiRef, gridPaginationModelSelector);
```

File: packages/grid/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx [hunk 8]
```diff
@@ -39,6 +40,22 @@ describe('<DataGridPro /> - Detail panel', () => {
     );
   }
 
+  function PaginationTestCase({
```
Comment (alexfauquette) [inline packages/grid/x-data-grid-pro/src/tests/detailPanel.DataGridPro.test.tsx:43]: DOn't sure to get why introducing a `PaginationTestCase` in test file for detailPanel

File: packages/grid/x-data-grid/src/components/GridPagination.tsx [hunk 9]
```diff
@@ -31,38 +31,41 @@ export const GridPagination = React.forwardRef<HTMLDivElement, Partial<TablePagi
     const paginationState = useGridSelector(apiRef, gridPaginationSelector);
 
     const lastPage = React.useMemo(
-      () => Math.floor(paginationState.rowCount / (paginationState.pageSize || 1)),
-      [paginationState.rowCount, paginationState.pageSize],
+      () => Math.floor(paginationState.rowCount / (paginationState.paginationModel.pageSize || 1)),
+      [paginationState.rowCount, paginationState.paginationModel],
```
Comment (alexfauquette) [inline packages/grid/x-data-grid/src/components/GridPagination.tsx:35]: Do  not change when `page` is modified
```suggestion
      [paginationState.rowCount, paginationState.paginationModel.pageSize],
```

File: packages/grid/x-data-grid/src/components/GridPagination.tsx [hunk 10]
```diff
@@ -31,38 +31,41 @@ export const GridPagination = React.forwardRef<HTMLDivElement, Partial<TablePagi
...
     );
 
     const handlePageSizeChange = React.useCallback(
       (event: React.ChangeEvent<HTMLTextAreaElement | HTMLInputElement>) => {
-        const newPageSize = Number(event.target.value);
-        apiRef.current.setPageSize(newPageSize);
+        const pageSize = Number(event.target.value);
+        apiRef.current.setPaginationModel({ pageSize, page: paginationState.paginationModel.page });
```
Comment (alexfauquette) [inline packages/grid/x-data-grid/src/components/GridPagination.tsx:41]: Would be nice to be able to do the following: specifying only the elements you want to update
```suggestion
        apiRef.current.setPaginationModel({ pageSize });
```

Same idea for `handlePageChange`

File: packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts [hunk 11]
```diff
@@ -1,38 +1,32 @@
...
-  page: number;
+  paginationModel: GridPaginationModel;
   pageCount: number;
   rowCount: number;
 }
 
 export interface GridPaginationInitialState {
-  pageSize?: number;
-  page?: number;
+  paginationModel?: GridPaginationModel;
```
Comment (alexfauquette) [inline packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts:10]:
```suggestion
  paginationModel?: Partial<GridPaginationModel>;
```

File: docs/data/data-grid/state/UseGridSelector.tsx (hunk 7 above)
Comment (alexfauquette) [reply docs/data/data-grid/state/UseGridSelector.tsx:16]: By the way, you kept `gridPageSelector` for this purpose

File: packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts [hunk 12]
```diff
@@ -1,41 +1,78 @@
...
-    pageSize = props.pageSize;
-  } else if (props.initialState?.pagination?.pageSize != null) {
-    pageSize = props.initialState.pagination.pageSize;
-    throwIfPageSizeExceedsTheLimit(pageSize, props.signature);
-  } else {
-    pageSize = defaultPageSize(props.autoPageSize);
-  }
+  const paginationModel =
+    (props.paginationModel ?? props.initialState?.pagination?.paginationModel) ||
+    getDefaultGridPaginationModel(props.autoPageSize);
```
Comment (alexfauquette) [inline packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts:36]: To allows partial specification in `initialState`
```suggestion
  const paginationModel = {
    ...getDefaultGridPaginationModel(props.autoPageSize),
    ...(props.paginationModel ?? props.initialState?.pagination?.paginationModel)
  };
```

File: packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts [hunk 13]
```diff
@@ -44,17 +81,212 @@ export const useGridPagination = (
...
+      logger.debug(`Setting page size to ${pageSize}`);
+      apiRef.current.setPaginationModel({ pageSize, page: currentModel.page });
+    },
+    [apiRef, logger],
+  );
+
+  const setPaginationModel = React.useCallback<GridPaginationApi['setPaginationModel']>(
+    (paginationModel) => {
+      const currentModel = gridPaginationModelSelector(apiRef);
+      if (paginationModel === currentModel) {
```
Comment (alexfauquette) [inline packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts:139]: Since you're comparing object, I doubt the equality will be `true`. Maybe better to test the values, but it woull expose to bug if we add other properties latter

```suggestion
      if (paginationModel.page === currentModel.page && paginationModel.pageSize === currentModel.pageSize) {
```

File: packages/grid/x-data-grid/src/components/GridPagination.tsx (hunk 10 above)
Comment (alexfauquette) [reply packages/grid/x-data-grid/src/components/GridPagination.tsx:41]: You've created `setPage` and `setPageSize` for those purpose ?

File: packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts [hunk 14]
```diff
@@ -44,17 +81,212 @@ export const useGridPagination = (
...
+  /**
+   * PRE-PROCESSING
+   */
+  const stateExportPreProcessing = React.useCallback<GridPipeProcessor<'exportState'>>(
+    (prevState, context) => {
+      const paginationModel = gridPaginationModelSelector(apiRef);
+
+      const shouldExportPaginationModel =
+        // Always export if the `exportOnlyDirtyModels` property is activated
+        !context.exportOnlyDirtyModels ||
```
Comment (alexfauquette) [inline packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts:176]: @flaviendelangle should the comment be

```suggestion
        // Always export if the `exportOnlyDirtyModels` property is not activated
        !context.exportOnlyDirtyModels ||
```

File: packages/grid/x-data-grid/src/components/GridPagination.tsx (hunk 10 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/components/GridPagination.tsx:41]: Yes, I kept them for easing up the migration pain a bit. It's opinionated but I was thinking to deprecate them and remove them in the next major release basically to keep the API simple.

File: packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts (hunk 13 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts:139]: Usually, I'm doing a simple equality check in the model updater and doing the smarter checks in each function.
See the filter plugin.

For the pagination, the state is simple enough so that the detailed check is doable.
But as you said, I think it's risky for the future.

I would prefer to keep exposing `setPage` / `setPageSize` / `setPaginationModel` and have each method check what is relevant.
Updating only one of the two is probably the most common scenario for users, so it should not be more complicated to do it than before

File: packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts (hunk 14 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts:176]: :see_no_evil: yes
And the comment error is probably present in all plugin

File: packages/grid/x-data-grid/src/components/GridPagination.tsx (hunk 10 above)
Comment (alexfauquette) [reply packages/grid/x-data-grid/src/components/GridPagination.tsx]: I don't have a strong opinion about keeping/removing those methods

File: packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx [hunk 15]
```diff
@@ -595,6 +578,13 @@ DataGridRaw.propTypes = {
    * @default "client"
    */
   paginationMode: PropTypes.oneOf(['client', 'server']),
+  /**
+   * The pagination model of type [[GridPaginationModel]] which refers to current `page` and `pageSize`.
+   */
+  paginationModel: PropTypes.shape({
+    page: PropTypes.number.isRequired,
+    pageSize: PropTypes.number.isRequired,
```
Comment (DanailH) [inline packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx:586]: I'm wondering if it makes sense to simplify the name to just `size` given the context is set for pagination. 🤔
```suggestion
    size: PropTypes.number.isRequired,
```

File: packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts [hunk 16]
```diff
@@ -1,38 +1,32 @@
...
-  page: number;
+  paginationModel: GridPaginationModel;
   pageCount: number;
   rowCount: number;
 }
 
 export interface GridPaginationInitialState {
-  pageSize?: number;
-  page?: number;
+  paginationModel?: Partial<GridPaginationModel>;
```
Comment (DanailH) [inline packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts:10]: Do we need a state structure like:
```
{
  paginationModel: {
    page:
    pageSize:
  }
}

Can't we make the internal state a single level?

```suggestion
  export interface GridPaginationInitialState extends Partial<GridPaginationModel> {};
```

File: packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx (hunk 15 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx:586]: Yeah may be we can consider doing that.

Another thing, I was also thinking to rename `rowsPerPageOptions` to `pageSizeOptions` as I have to sometimes think twice to reach the conclusion that `pageSize` and `rowPerPageOptions` are related.
`pageSize` and `pageSizeOptions` look more logical.

If we go with paginationModel.size it could be
```tsx
paginationModel: {
  page: number;
  size: number
}
```

And the `rowsPerPageOptions` could be `paginationOptions` or `pageSizeOptions`

Comment (alexfauquette) [reply packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx:586]: @DanailH I'm not sure saving 4 characters worth decreasing clarity. 

`paginationModel.pageSize` is obviously, it's the number of items per page
`paginationModel.size` could be either the number of items per page or the number of pages

File: packages/grid/x-data-grid/src/models/events/gridEventLookup.ts [hunk 17]
```diff
@@ -317,6 +314,7 @@ export interface GridControlledStateReasonLookup {
     | 'deleteFilterItem'
     | 'changeLogicOperator'
     | 'restoreState';
+  pagination: 'setPaginationModel' | 'setPage' | 'setPageSize' | 'stateRestorePreProcessing';
```
[the remark this answers is not in the document]
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/models/events/gridEventLookup.ts:317]: Removing this key totally throws ts error while using `apiRef.current.updateControlState` as it's typed to accept keys defined in `GridControlledStateReasonLookup`.
How about keeping the valid ones?

```tsx
pagination: 'setPaginationModel' | 'stateRestorePreProcessing';
```

File: packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts (hunk 16 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts:10]: > Can't we make the internal state a single level?

You mean `InitialState` or state itself. I observed a bit the patterns for all other controlled states. I feel if we make it single level it will make things a bit inconsistent.

Initial State:

For instance in row grouping:
https://github.com/mui/mui-x/blob/00d4569c716fcda032a550b5ab15ea22d0a17c37/packages/grid/x-data-grid-premium/src/hooks/features/rowGrouping/gridRowGroupingInterfaces.ts#L9-L11

For aggregation:
https://github.com/mui/mui-x/blob/00d4569c716fcda032a550b5ab15ea22d0a17c37/packages/grid/x-data-grid-premium/src/hooks/features/aggregation/gridAggregationInterfaces.ts#L13-L15

Same is the case with sorting and filtering, although a small inconsistency I can find is different keywords used for them i.e `filterModel` and `sortModel` instead of `model` as in aggregation and rowGrouping. May be we can think about making it consistent everywhere?

By the way, does making single level you mean to make the prop interface like the following or only refactoring internally?

```diff
<DataGrid
  initialState={
    pagination: {
-     paginationModel: {
      page: initialPage,
      pageSize: initialPageSize
-     }
    }
  }
/>
```

File: packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts [hunk 18]
```diff
@@ -1,41 +1,81 @@
...
+    rowCount: number,
+    signature: DataGridProcessedProps['signature'],
+    paginationModelProp?: GridPaginationModel,
+  ) =>
+  (paginationState: GridPaginationState) => {
+    let paginationModel = paginationState.paginationModel;
+    const pageSize = paginationModelProp?.pageSize ?? paginationModel.pageSize;
+    const pageCount = getPageCount(rowCount, pageSize);
+
+    if (paginationModelProp && paginationModelProp !== paginationModel) {
```
[the remark this answers is not in the document]
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts:62]: The possibility of users storing values on their side in separate state variables etc could surely be a use-case. 👍 

I wanted to go with shallow equality for the scalability purpose, but since I can't foresee too many new props being added to `paginationModel` soon, I'll refactor it.

File: packages/grid/x-data-grid/src/models/gridStateCommunity.ts [hunk 19]
```diff
@@ -45,7 +45,7 @@ export interface GridStateCommunity {
  * The initial state of `DataGrid`.
  */
 export interface GridInitialStateCommunity {
-  pagination?: GridPaginationInitialState;
+  paginationModel?: GridPaginationInitialState;
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/models/gridStateCommunity.ts:48]: Named it `paginationModel` to be aligned with `props.paginationModel`.

If we still want to name it `pagination`, then maybe we should rename the `pagination` boolean prop to be `disablePagination` and use `pagination` everywhere instead of `paginationModel`. But it seems to cause more problems than it solves.

Let me know if `paginationModel` looks off.

File: packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationSelector.ts [hunk 20]
```diff
@@ -4,60 +4,73 @@ import {
...
+import { getPageCount } from './gridPaginationUtils';
 
 /**
+ * Get the pagination model
  * @category Pagination
- * @ignore - do not document.
  */
-export const gridPaginationSelector = (state: GridStateCommunity) => state.pagination;
+export const gridPaginationModelSelector = createSelector(
+  (state: GridStateCommunity) => state,
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationSelector.ts:17]: A workaround for providing [direct access selector](https://mui.com/x/react-data-grid/state/#direct-selector-access), as this selector is likely to be used more often by end users.

We can also think about refactoring `createSelector` to support single selector use-case like this maybe?

File: packages/grid/x-data-grid/src/models/gridStateCommunity.ts (hunk 19 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/models/gridStateCommunity.ts:48]: > I would prefer the sub-state to be named like the plugin.
`state.detailPanel` but `props.detailPanelExpandedRowIds`

That's what I wanted to do too, but then the idea of calling it in `initialState` as `pagination` and in props as `paginationModel` (example no. 1 below) didn't look great to me. 😄

```tsx
// 1. With `state.pagination` and `initialState.pagination`
<DataGrid
  initialState={{ pagination: { page: 0, pageSize: 10 } }}
  paginationModel={{ page: 0, pageSize: 10 }}
/>

// 2. With `state.paginationModel` and `initialState.paginationModel`
<DataGrid
  initialState={{ paginationModel: { page: 0, pageSize: 10 } }}
  paginationModel={{ page: 0, pageSize: 10 }}
/>

// 3. With `state.pagination` and `initialState.paginationModel`
<DataGrid
  initialState={{ paginationModel: { page: 0, pageSize: 10 } }}
  paginationModel={{ page: 0, pageSize: 10 }}
/>
```

I wanted to go with no. 2 as it logically aligned better to me as an end user with single level state but we can go with no. 1 too if it looks ok to team?

Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/models/gridStateCommunity.ts:48]: For me `3.` is the worse`, when I introduced `initialState` I built it to be a sub-set of `state`.

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/models/gridStateCommunity.ts:48]: It would be great if we make it consistent with other initialState properties, like `sorting` and `filter`:

```tsx
<DataGrid
  initialState={{
    sorting: {
      sortModel: [{ field: 'plan', sort: 'asc' }]
    },
    filter: {
      filterModel: { items: [{ field: 'title', operator: 'equals', value: 'Titanic' }] }
    },
    pagination: {
      paginationModel: { page: 0, pageSize: 10 }
    }
  }}
  paginationModel={{ page: 0, pageSize: 10 }}
/>
```

What do you think?

File: packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationSelector.ts (hunk 20 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationSelector.ts:17]: It's somewhat related to https://github.com/mui/mui-x/pull/7147#discussion_r1069682438

File: packages/grid/x-data-grid/src/models/gridStateCommunity.ts (hunk 19 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/models/gridStateCommunity.ts:48]: It was suggested to make pagination state single level in [this](https://github.com/mui/mui-x/pull/7147#discussion_r1062371217) thread.

Do you mean just keeping initialState interface like this while keeping state single level?

```tsx
interface GridPaginationModel {
  page: number;
  pageSize: number;
}

interface GridPaginationState extends GridPaginationModel {}

interface GridPaginationInitialState {
  paginationModel?: Partial<GridPaginationModel>;
}

const initialState = {
  pagination: {
    paginationModel: { page: 0, pageSize: 10 }
  }
}
```

File: packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts (hunk 16 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts]: `sorting` and `filter` are other examples of nested states. Both contain only the model.
I think we should keep the pagination state consistent with those states - see https://github.com/mui/mui-x/pull/7147#discussion_r1069682438

File: packages/grid/x-data-grid/src/models/gridStateCommunity.ts (hunk 19 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/models/gridStateCommunity.ts]: As discussed with the team, we'll be going with Andrew's [suggestion](https://github.com/mui/mui-x/pull/7147#discussion_r1069682438) on this topic

File: docs/data/data-grid/row-selection/MultipleRowSelectionGrid.js [hunk 21]
```diff
@@ -9,9 +9,19 @@ export default function MultipleRowSelectionGrid() {
     maxColumns: 6,
   });
 
+  const [paginationModel, setPaginationModel] = React.useState({
+    page: 0,
+    pageSize: 10,
```
Comment (cherniavskii) [inline docs/data/data-grid/row-selection/MultipleRowSelectionGrid.js:14]: Maybe use the `initialState` here as well?

File: docs/data/data-grid/state/UseGridSelector.tsx [hunk 22]
```diff
@@ -9,6 +9,8 @@ import {
 import { useDemoData } from '@mui/x-data-grid-generator';
 import Pagination from '@mui/material/Pagination';
 
+const PAGE_SIZE = 10;
```
Comment (cherniavskii) [inline docs/data/data-grid/state/UseGridSelector.tsx:12]: Is the const useful here?

File: packages/grid/x-data-grid-pro/src/tests/pagination.DataGridPro.test.tsx [hunk 23]
```diff
@@ -74,18 +74,18 @@ describe('<DataGridPro /> - Pagination', () => {
...
 
         return (
           <div style={{ width: 300, height: 300 }}>
             <DataGridPro
               {...basicData}
               apiRef={apiRef}
-              pageSize={pageSize}
-              rowsPerPageOptions={[pageSize]}
-              onPageSizeChange={(newPageSize) => setPageSize(newPageSize)}
+              initialState={{ pagination: { paginationModel: { pageSize: 5 } } }}
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/tests/pagination.DataGridPro.test.tsx:86]: Shouldn't `paginationModel` be used here?

File: packages/grid/x-data-grid/src/components/GridPagination.tsx [hunk 24]
```diff
@@ -29,60 +31,70 @@ export const GridPagination = React.forwardRef<HTMLDivElement, Partial<TablePagi
...
       },
       [apiRef],
     );
 
     if (process.env.NODE_ENV !== 'production') {
       // eslint-disable-next-line react-hooks/rules-of-hooks
-      const warnedOnceMissingPageSizeInRowsPerPageOptions = React.useRef(false);
+      const warnedOnceMissingInPageSizeOptions = React.useRef(false);
+      const pageSize =
+        rootProps.paginationModel?.pageSize ?? paginationState.paginationModel.pageSize;
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/GridPagination.tsx:65]: Isn't `rootProps.paginationModel?.pageSize` synchronized with `paginationState.paginationModel.pageSize`?

File: packages/grid/x-data-grid/src/components/GridPagination.tsx [hunk 25]
```diff
@@ -29,60 +31,70 @@ export const GridPagination = React.forwardRef<HTMLDivElement, Partial<TablePagi
...
 
     return (
       <GridPaginationRoot
         ref={ref}
         component="div"
-        count={paginationState.rowCount}
-        page={paginationState.page <= lastPage ? paginationState.page : lastPage}
+        count={rowCount}
+        page={
+          paginationState.paginationModel.page <= lastPage
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/GridPagination.tsx:88]: Maybe extract `paginationState.paginationModel` to a variable to reduce the chaining a bit and make the code look more compact?

File: packages/grid/x-data-grid/src/hooks/features/columns/useGridColumns.tsx [hunk 26]
```diff
@@ -276,7 +276,7 @@ export function useGridColumns(
 
       const columnVisibilityModelToExport = gridColumnVisibilityModelSelector(apiRef);
       const shouldExportColumnVisibilityModel =
-        // Always export if the `exportOnlyDirtyModels` property is activated
+        // Always export if the `exportOnlyDirtyModels` property not is activated
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/columns/useGridColumns.tsx:279]:
```suggestion
        // Always export if the `exportOnlyDirtyModels` property is not activated
```

File: packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts [hunk 27]
```diff
@@ -1,38 +1,30 @@
...
- * The apiRef methods handled by `useGridPageSize`
+ * The pagination API interface that is available in the grid `apiRef`.
  */
-export interface GridPageSizeApi {
+export interface GridPaginationApi {
+  /**
+   * Sets the displayed page to the value given by `page`.
+   * @param {number} page The new page number.
+   */
+  setPage: (page: number) => void;
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts:19]: Mark as `@deprecated`?

File: packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationSelector.ts [hunk 28]
```diff
@@ -1,25 +1,36 @@
...
+);
+
 /**
  * Get the index of the page to render if the pagination is enabled
  * @category Pagination
  */
 export const gridPageSelector = createSelector(
   gridPaginationSelector,
-  (pagination) => pagination.page,
+  (pagination) => pagination.paginationModel.page,
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationSelector.ts:33]: Shouldn't it use `gridPaginationModelSelector` selector?

File: packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts [hunk 29]
```diff
@@ -44,17 +83,214 @@ export const useGridPagination = (
...
+  useGridRegisterPipeProcessor(apiRef, 'exportState', stateExportPreProcessing);
+  useGridRegisterPipeProcessor(apiRef, 'restoreState', stateRestorePreProcessing);
+
+  /**
+   * EVENTS
+   */
+  const handlePaginationModelChange: GridEventListener<'paginationModelChange'> = () => {
+    const paginationModel = gridPaginationModelSelector(apiRef);
+    if (apiRef.current.virtualScrollerRef?.current) {
+      apiRef.current.scrollToIndexes({
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts:237]: This changes the behavior a bit - previously the page was scrolled to the top only on page change. Currently, it would scroll to the top even if the page size changes

File: packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts [hunk 30]
```diff
@@ -44,17 +83,214 @@ export const useGridPagination = (
...
+        rowIndex: paginationModel.page * paginationModel.pageSize,
+      });
+    }
+
+    apiRef.current.forceUpdate();
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts:242]: Is it necessary?

File: packages/grid/x-data-grid/src/tests/columnSpanning.DataGrid.test.tsx [hunk 31]
```diff
@@ -698,18 +698,25 @@ describe('<DataGrid /> - Column Spanning', () => {
...
-          rows={rows}
-          pagination
-          pageSize={pageSize}
-          rowsPerPageOptions={[pageSize]}
-          disableVirtualization={isJSDOM}
-        />
-      </div>,
-    );
+    function TestCase() {
+      const [paginationModel, setPaginationModel] = React.useState({ pageSize, page: 0 });
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/tests/columnSpanning.DataGrid.test.tsx:702]: Use `initialState` instead?

File: packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx [hunk 32]
```diff
@@ -46,120 +46,158 @@ describe('<DataGrid /> - Pagination', () => {
...
       );
       expect(getColumnValues(0)).to.deep.equal(['0']);
-      setProps({ page: 1 });
+      setProps({ paginationModel: { page: 1, pageSize: 1 } });
       expect(getColumnValues(0)).to.deep.equal(['1']);
     });
 
-    it('should apply new page when clicking on next / previous button and onPageChange is not defined and page is not controlled', () => {
-      render(<BaselineTestCase pageSize={1} rowsPerPageOptions={[1]} />);
+    it('should not apply new page when clicking on next / previous button and onPaginationModelChange is not defined and page is not controlled', () => {
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx:76]: Should we mention this behavior change in the migration guide?

File: docs/data/data-grid/pagination/PaginationModelInitialState.tsx.preview [hunk 33]
```diff
@@ -4,10 +4,10 @@
...
     pagination: {
       ...data.initialState?.pagination,
-      page: 1,
+      paginationModel: {
+        pageSize: 25,
+        /* page: 0 // default value will be used if not passed */
+      },
     },
   }}
-  pageSize={5}
```
[the remark this answers is not in the document]
Comment (MBilalShafi) [reply docs/data/data-grid/pagination/PaginationModelInitialState.tsx.preview:10]: I guess those were the use-cases where `pageSize` was not likely to change and it was OK to make it controlled.

File: packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx (hunk 32 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx:76]: I think the title is confusing, this should be the text and then it should be the default behaviour.
```suggestion
    it('should not apply new page when clicking on next / previous button and onPaginationModelChange is not defined and paginationModel is controlled', () => {
```

File: packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts (hunk 27 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts:19]: Yes that would be more logical to do and I wanted to do that too but this [concern](https://github.com/mui/mui-x/pull/7147#discussion_r1061251536) (second part of the comment) also makes sense that most frequent use-case for the users would be updating either of the `page` or `pageSize`, so keeping these helpers kind of makes the API easy to use. What do you think?

File: packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts (hunk 29 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts:237]: Yes and it seems to make sense to me too. I mean after `pageSize` change, the visible rows are computed again and the same row isn't necessarily shown on the viewport. Is there a catch you can observe here?

File: packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx (hunk 15 above)
Comment (DanailH) [reply packages/grid/x-data-grid/src/DataGrid/DataGrid.tsx:565]: Fair enough, assuming there can be more numbers that represent different things.

File: packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts (hunk 16 above)
Comment (DanailH) [reply packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationInterfaces.ts:8]: If we start exploring in this direction then another option is to do something like this:
```diff
<DataGrid
  initialState={
-    pagination: {
+     paginationModel: {
      page: initialPage,
      pageSize: initialPageSize
     }
-   }
  }
/>
```

That is leaning on @m4theushw comment about the pagination being a 2-year-old feature and we never needed more than a model in the state. I guess we are short on time for this discussion so we can have this in mind for the future but for now, we can keep it as is.

**Review by DanailH — APPROVED** [review]

**Comment by DanailH** [comment]
Looks great!

File: packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts (hunk 30 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts:242]: In theory it shouldn't be needed, but removing this causes ~10 tests to fail. We may investigate a bit on this later on, what do you think?

File: docs/data/data-grid/pagination/PaginationModelInitialState.tsx.preview (hunk 33 above)
[the remark this answers is not in the document]
Comment (cherniavskii) [reply docs/data/data-grid/pagination/PaginationModelInitialState.tsx.preview:10]: Never mind, I misunderstood the demo :)

File: packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts (hunk 30 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/features/pagination/useGridPagination.ts:242]: I checked the `setPage` and `setPageSize` and both of those methods were calling `.forceUpdate`, so I think we are good here 👍

File: packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx (hunk 32 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx]: So the behavior hasn't changed, right?

**Review by cherniavskii — APPROVED** [review]

File: packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx (hunk 32 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx]: Yes, the same behavior that was previously for page or pageSize now works for paginationModel

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx]: Great!
