### PR TITLE
[DataGrid] Store the outlined cell in the state

### LINKED ISSUE #3844: [DataGrid] Cell consistency broken when keyboard event blur
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When a keyboard event moves the focus outside of the grid with <kbd>Tab</kbd> for example, the focus of the internal state is not cleaned.

For mouse event, we clean it by listening `mouseDown` and `click`

See [this comment for more details](https://github.com/mui-org/material-ui-x/pull/3718#issuecomment-1023783748)

### Expected behavior 🤔

_No response_

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by m4theushw**
Part of https://github.com/mui/mui-x/pull/6567#issuecomment-1322791819

Fixes #3844

Here I'm moving to the state the information of which cell has the outline. Previously, the outline style was added by CSS using `:focus-within`, but for cell selection a cell might focused but not have the outline. During normal usage, e.g. keyboard navigation, the outline is synced with the focus inside `apiRef.current.setCellFocus`. This means that if the focus is not correctly updated, the cell won't have the outline. A way to review this PR is to battle test the focus logic ensuring that the focus is always updated.

To implement the correct behavior for cell selection I'll open another PR allowing `apiRef.current.setCellFocus` to skip the outline update. Then we can add a `apiRef.current.setOutlinedCell` to update only the outline state.

### Breaking changes

- To update the outline style of a focused cell, use the `.MuiDataGrid-cell--outlined` CSS class instead of the `:focus-within` selector.

  ```diff
  -'.MuiDataGrid-cell:focus-within': {
  +'.MuiDataGrid-cell--outlined': {
  ```

### CODE REVIEW

**Review by DanailH — COMMENTED** [review]
Nice work! I just have a couple of notes/questions but other than those it's good from my side

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 1]
```diff
@@ -353,10 +353,6 @@ export const GridRootStyles = styled('div', {
       display: 'flex',
       boxShadow: theme.shadows[2],
       backgroundColor: (theme.vars || theme).palette.background.paper,
-      '&:focus-within': {
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:356]: Cell focus seems broken on nested grids in https://deploy-preview-7111--material-ui-x.netlify.app/x/react-data-grid/demo/
Should we update the demo to use the new class name?

```diff
diff --git a/docs/data/data-grid/demo/PopularFeaturesDemo.tsx b/docs/data/data-grid/demo/PopularFeaturesDemo.tsx
index f439522..49b04c3 100644
--- a/docs/data/data-grid/demo/PopularFeaturesDemo.tsx
+++ b/docs/data/data-grid/demo/PopularFeaturesDemo.tsx
@@ -393,7 +393,7 @@ export default function PopularFeaturesDemo() {
           [`& .${gridClasses.detailPanel}`]: {
             background: 'transparent',
           },
-          [`& .${gridClasses.cell}:focus, & .${gridClasses.cell}:focus-within`]: {
+          [`& .${gridClasses['cell--outlined']}`]: {
             outline: 'none',
           },
           [`& .${gridClasses.columnHeader}:focus, & .${gridClasses.columnHeader}:focus-within`]:
```

**Comment by cherniavskii** [comment]
> In a range selection created by clicking two cells, the outlined cell is the last one, however, I need to keep the outline in the first clicked cell.

Sorry, I thought you were solving a different issue.
Could you provide more details on the issue you're solving? I don't understand why the outline has to stay in the first-clicked cell.

**Review by DanailH — APPROVED** [review]
