### PR TITLE
[pickers] fix to trigger `onChange` when clearing not empty value

### LINKED ISSUE #5690: onChange is not triggered when clearing an invalid date
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When you enter an invalid date (such as 13/02/2022 for MM/DD/YYYY) and then press the clear button, no callback is triggered.

### Expected behavior 🤔

A callback should be triggered in such a way that a controlled input would have the error state and value cleared.

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/objective-water-g8s2ln?file=/src/App.js
Steps:
1. Type 13/02/2022 into the DateInput
2. Open the calendar
3. Press the clear button in the calendar

### Context 🔦

I'm trying to control a date input in a form, and users of the form find the current behavior counterintuitive.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #5690 

Force trigger an `onChange` call when clicking `clear` button with not empty `value`.
Covers case, when date picker has `Invalid date` due to manual entry, but internally the state is saved as `null` already.

Simply adding a check in `setDate` function causes inconsistent behaviour, where simply closing the picker would also reset an invalid value.

### CODE REVIEW

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 1]
```diff
@@ -257,7 +264,16 @@ export const usePickerState = <TInputValue, TValue, TDate>(
...
-        setDate({ value: valueManager.emptyValue, action: 'acceptAndClose' });
+        setDate({
+          value: valueManager.emptyValue,
+          action: 'acceptAndClose',
+          // force `onChange` in cases like input (value) === `Invalid date`
+          forceOnChangeCall: !valueManager.areValuesEqual(
+            utils,
+            value as any,
+            valueManager.emptyValue,
+          ),
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/internals/hooks/usePickerState.ts:275]: Should we do the same with `onAccept`?

https://codesandbox.io/s/summer-sound-rn9osw?file=/src/App.js

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts [hunk 2]
```diff
@@ -278,7 +294,16 @@ export const usePickerState = <TInputValue, TValue, TDate>(
...
+    [
+      isOpen,
+      setDate,
+      valueManager,
+      value,
+      dateState.draft,
+      dateState.committed,
+      dateState.resetFallback,
+      utils,
+    ],
```
[the remark this answers is not in the document]
Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:306]: There should be difference, especially in this case.
I've changed it to this style only because it was the change that the IDE has done as auto suggestion.
WiIl add `value` manually for cleanliness.

File: packages/x-date-pickers/src/internals/hooks/usePickerState.ts (hunk 1 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:275]: Do you mean that clicking `ok` (accept) should also revert date to empty/null if it is invalid?

Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:275]: Thanks for noting this case. 🙏 
Updated.
Although, I'm no longer happy with this `memo`ized `wrapperProps` as it is changing on every input value change, this forces the component to re-render even though it essentially **has** to re-render only on static picker open (to update the selected value).

Comment (alexfauquette) [reply packages/x-date-pickers/src/internals/hooks/usePickerState.ts:275]: it there is not value selected, I assume that accepting no value means cleaning the field.

But I'm thinking a bit too much about what is logical instead of what user want. I assume nobody click on accept if they do not have selected a date

**Review by alexfauquette — APPROVED** [review]
Sounds like a nice tradeoff 👍
