### PR TITLE
[DataGridPremium] Fix loading issue + add skeleton overlay

### LINKED ISSUE #16220: [data grid] loading does not work with dataSource in DataGridPremium
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/p/sandbox/intelligent-leavitt-q4h68n?from-embed=&workspaceId=ws_96AUJAP4MpFUq5gdSxRein
2. Click reload

https://github.com/user-attachments/assets/924d0368-5afe-4729-8042-c4667d23a64b

### Current behavior

"no rows" text displayed

### Expected behavior

show loading spinner or skeleton

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 15.3
  Binaries:
    Node: 20.11.0 - ~/Library/Caches/fnm_multishells/97945_1737063734686/bin/node
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/97945_1737063734686/bin/npm
    pnpm: 9.15.4 - ~/Library/Caches/fnm_multishells/97945_1737063734686/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.265
    Edge: Not Found
    Safari: 18.3
  npmPackages:
    @emotion/react: 11.14.0 => 11.14.0 
    @emotion/styled: 11.14.0 => 11.14.0 
    @mui/icons-material: 6.0.2 => 6.0.2 
    @mui/material: 6.4.0 => 6.4.0 
    @mui/utils: 6.4.0 => 6.4.0 
    @mui/x-data-grid-generator: 7.23.6 => 7.23.6 
    @mui/x-data-grid-premium: 8.0.0-alpha.8 => 8.0.0-alpha.8 
    @mui/x-date-pickers-pro: 8.0.0-alpha.8 => 8.0.0-alpha.8 
    @types/react: 19.0.7 => 19.0.7 
    react: 19.0.0 => 19.0.0 
    react-dom: 19.0.0 => 19.0.0 ```
</details>



**Search keywords**: dataSource

### PR DESCRIPTION
**Pull request by MBilalShafi**
## Changelog

- Fixes #16220
	- Before: https://codesandbox.io/p/sandbox/intelligent-leavitt-q4h68n?from-embed=&workspaceId=ws_96AUJAP4MpFUq5gdSxRein
	- After: https://codesandbox.io/p/sandbox/stupefied-scott-qnqpx5
	
- Add a skeleton loading overlay on the aggregation row while it's loading

  https://github.com/user-attachments/assets/310f57fe-2809-45c7-9930-22f5df413e04

### CODE REVIEW

File: packages/x-data-grid-premium/src/hooks/features/aggregation/createAggregationLookup.ts [hunk 1]
```diff
@@ -109,7 +109,7 @@ const getGroupAggregatedValueDataSource = (
 
     groupAggregationLookup[aggregatedField] = {
       position,
-      value: apiRef.current.resolveGroupAggregation(groupId, aggregatedField),
+      value: apiRef.current.resolveGroupAggregation?.(groupId, aggregatedField) ?? '-',
```
Comment (arminmeh) [inline packages/x-data-grid-premium/src/hooks/features/aggregation/createAggregationLookup.ts:112]: As discussed in the issue, this should be skeleton row cell

Comment (MBilalShafi) [reply packages/x-data-grid-premium/src/hooks/features/aggregation/createAggregationLookup.ts]: Added a skeleton row, let me know how it feels.
Could be tested here: https://deploy-preview-16282--material-ui-x.netlify.app/x/react-data-grid/server-side-data/aggregation/#usage-with-lazy-loading
(Try increasing the server delay `minDelay` and `maxDelay` properties to visualize better.)

**Review by arminmeh — APPROVED** [review]
Looks great 💯

File: packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+
+  const slots = {
+    root: ['aggregationRowOverlayWrapper'],
+  };
+
+  return composeClasses(slots, getDataGridUtilityClass, classes);
+};
+
+const GridAggregationRowOverlay = forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
+  function GridSkeletonLoadingOverlay(props, forwardedRef) {
```
Comment (KenanYusuf) [inline packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx:39]:
```suggestion
  function GridAggregationRowOverlay(props, forwardedRef) {
```

File: packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+} from '@mui/x-data-grid-pro';
+import { GridSkeletonLoadingOverlayInner, useGridSelector } from '@mui/x-data-grid-pro/internals';
+import { useGridApiContext } from '../hooks/utils/useGridApiContext';
+import { gridAggregationLookupSelector } from '../hooks/features/aggregation/gridAggregationSelectors';
+import { DataGridPremiumProcessedProps } from '../models/dataGridPremiumProps';
+
+const GridAggregationRowOverlayWrapper = styled('div', {
+  name: 'MuiDataGrid',
+  slot: 'AggregationRowOverlayWrapper',
+  overridesResolver: (_, styles) => styles.aggregationRowOverlayWrapper,
```
Comment (KenanYusuf) [inline packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx:20]:
```suggestion
```

File: packages/x-data-grid-premium/src/components/GridPinnedRows.tsx [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+  const pinnedRows = virtualScroller.getRows({
+    position,
+    rows,
+    renderContext: pinnedRenderContext,
+  });
+
+  return (
+    <div className={clsx(classes.root, gridClasses[`pinnedRows--${position}`])} role="presentation">
+      {pinnedRows}
+      {position === 'bottom' && <GridAggregationRowOverlay />}
```
Comment (KenanYusuf) [inline packages/x-data-grid-premium/src/components/GridPinnedRows.tsx:51]: There's a missing border with pinned row cells when also in a pinned column:
Screenshot 2025-01-30 at 10 36 21

Should look like:
Screenshot 2025-01-30 at 10 41 22

File: packages/x-data-grid-premium/src/constants/dataGridPremiumDefaultSlotsComponents.ts [hunk 5]
```diff
@@ -2,9 +2,11 @@ import { DATA_GRID_PRO_DEFAULT_SLOTS_COMPONENTS } from '@mui/x-data-grid-pro/int
 import type { GridPremiumSlotsComponent } from '../models';
 import { GridPremiumColumnMenu } from '../components/GridPremiumColumnMenu';
 import materialSlots from '../material';
+import { GridPinnedRows } from '../components/GridPinnedRows';
 
 export const DATA_GRID_PREMIUM_DEFAULT_SLOTS_COMPONENTS: GridPremiumSlotsComponent = {
   ...DATA_GRID_PRO_DEFAULT_SLOTS_COMPONENTS,
   ...materialSlots,
   columnMenu: GridPremiumColumnMenu,
+  pinnedRows: GridPinnedRows,
```
Comment (KenanYusuf) [inline packages/x-data-grid-premium/src/constants/dataGridPremiumDefaultSlotsComponents.ts:11]: Out of interest, what's the benefit to this being a slot?

**Review by KenanYusuf — COMMENTED** [review]
Spotted a couple of minor things but it looks great 👍

File: packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+    }
+    const rootLookup = aggregationLookup[GRID_ROOT_GROUP_ID];
+    const initialDataFetched = Object.values(rootLookup).some(({ value }) => value !== '');
+    if (initialDataFetched) {
+      return null;
+    }
+
+    const visibleColumns = new Set(Object.keys(rootLookup));
+    const viewportHeight = dimensions.bottomContainerHeight ?? 0;
+    const skeletonRowsCount = Math.ceil(viewportHeight / dimensions.rowHeight);
```
[the remark this answers is not in the document]
Comment (MBilalShafi) [reply packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx:57]: Initially, I wanted to use this for all the pinned rows in the container, but turned out the pinned rows don't support lazy loading by default, so I made it specific to the aggregation row. We could certainly try limiting it to `1`.

File: packages/x-data-grid-premium/src/constants/dataGridPremiumDefaultSlotsComponents.ts (hunk 5 above)
Comment (MBilalShafi) [reply packages/x-data-grid-premium/src/constants/dataGridPremiumDefaultSlotsComponents.ts:11]: Just not to spill the logic related to the Premium package in Pro or Community.

File: packages/x-data-grid/src/components/GridSkeletonLoadingOverlay.tsx [hunk 7]
```diff
@@ -52,220 +52,244 @@ const useUtilityClasses = (ownerState: OwnerState) => {
...
-      [allVisibleColumns, inViewportCount],
-    );
-    const pinnedColumns = useGridSelector(apiRef, gridVisiblePinnedColumnDefinitionsSelector);
+export const GridSkeletonLoadingOverlayInner = forwardRef<
+  HTMLDivElement,
+  React.HTMLAttributes<HTMLDivElement> & {
+    skeletonRowsCount: number;
+    showFirstRowBorder?: boolean;
+    visibleColumns?: Set<GridColDef['field']>;
+  }
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/components/GridSkeletonLoadingOverlay.tsx:61]: Nit: should we pull this out into a type/interface?

**Review by KenanYusuf — APPROVED** [review]

**Review by KenanYusuf — APPROVED** [review]

File: packages/x-data-grid/src/components/GridSkeletonLoadingOverlay.tsx [hunk 8]
```diff
@@ -52,220 +52,244 @@ const useUtilityClasses = (ownerState: OwnerState) => {
...
-      () => positions.filter((value) => value <= totalWidth).length,
-      [totalWidth, positions],
-    );
-    const allVisibleColumns = useGridSelector(apiRef, gridVisibleColumnDefinitionsSelector);
-    const columns = React.useMemo(
-      () => allVisibleColumns.slice(0, inViewportCount),
-      [allVisibleColumns, inViewportCount],
-    );
-    const pinnedColumns = useGridSelector(apiRef, gridVisiblePinnedColumnDefinitionsSelector);
+export const GridSkeletonLoadingOverlayInner = forwardRef<
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/components/GridSkeletonLoadingOverlay.tsx:55]: There's an issue with scrolling not being in sync:

https://github.com/user-attachments/assets/e1ab930b-90f0-4451-9196-813bdad163c5

Works ok on the [skeleton overlay demo](https://deploy-preview-16282--material-ui-x.netlify.app/x/react-data-grid/overlays/#skeleton):

https://github.com/user-attachments/assets/87504ebe-75a8-4a4d-adbc-27d88fa73268

**Review by KenanYusuf — CHANGES_REQUESTED** [review]

File: packages/x-data-grid/src/components/GridSkeletonLoadingOverlay.tsx (hunk 8 above)
Comment (MBilalShafi) [reply packages/x-data-grid/src/components/GridSkeletonLoadingOverlay.tsx:55]: Looks like a broader issue, seems like we need to explicitly pass the `slotProps.loadingOverlay.noRowsVariant` for the scroll to be in sync.

Reported a separate [issue](https://github.com/mui/mui-x/issues/16436) and a potential fix. Thanks for reporting.

File: packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx [hunk 9]
```diff
@@ -0,0 +1,68 @@
+import * as React from 'react';
```
[the remark this answers is not in the document]
Comment (MBilalShafi) [reply packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx:1]: Yes, I was also looking at it, it seems the skeleton row isn't needed anymore since we don't show the aggregation row with no values. 🙂

[the remark this answers is not in the document]
Comment (MBilalShafi) [reply packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx:1]: We don't show the skeleton row on the initial load, but we could still have a case for the subsequent loads, to show a nice feedback to the users around the fields being loaded.

https://github.com/user-attachments/assets/310f57fe-2809-45c7-9930-22f5df413e04

How does this sound?

[the remark this answers is not in the document]
Comment (KenanYusuf) [reply packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx:1]: > it seems the skeleton row isn't needed anymore since we don't show the aggregation row with no values.

I think it is still a useful indicator on the skeleton loader. My intention with that PR was to hide it from the "no rows" overlay only.

[the remark this answers is not in the document]
Comment (MBilalShafi) [reply packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx:1]: > I think it is still a useful indicator on the skeleton loader. My intention with that PR was to hide it from the "no rows" overlay only.

We could show it back for sure. To me this change felt intentional. For the initial load, hiding the aggregation pinned row and showing the skeleton on all the rows seems fine, since there's no actual data loaded yet, the central skeleton serves as an indicator of the "first load".

Not showing the row on the first load also solves a problem of error UI, i.e. what to show if the first call fails? empty row? hide the row again?

No strong preference though. I'd like to take your preference here.

File: packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx [hunk 10]
```diff
@@ -0,0 +1,53 @@
...
+
+    return (
+      <GridAggregationRowOverlayWrapper className={classes.root}>
+        <GridSkeletonLoadingOverlayInner
+          {...props}
+          skeletonRowsCount={1}
+          visibleColumns={visibleColumns}
+          showFirstRowBorder
+          ref={forwardedRef}
+        />
```
Comment (KenanYusuf) [inline packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx:47]: For the skeleton aggregation row, we also need to apply `backgroundColor: 'var(--DataGrid-pinnedBackground)'` so that the pinned row isn't transparent:

Screenshot 2025-02-10 at 13 51 08

Comment (MBilalShafi) [reply packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx:47]: I thought it's already [applied](https://github.com/MBilalShafi/mui-x/blob/863115a76152eb41f410ea7c121f0edbdda3de63/packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx#L15) 🤔 

Could you share which demo you can reproduce the issue on?

Comment (KenanYusuf) [reply packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx:47]: Ah, I think you want to apply the style to `${gridClasses.row}` so that the background color takes up the width of all of the cells, similar to how we do here: https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/components/containers/GridRootStyles.ts#L600-L601

I found it by resizing a column on [this demo](https://deploy-preview-16282--material-ui-x.netlify.app/x/react-data-grid/server-side-data/aggregation/#usage-with-lazy-loading) to create an overflow.

Comment (MBilalShafi) [reply packages/x-data-grid-premium/src/components/GridAggregationRowOverlay.tsx:47]: Nvm, I'm able to reproduce it, the issue is on the far right side of the row when there's a horizontal scroll. On it.

**Review by KenanYusuf — APPROVED** [review]
