### PR TITLE
[DataGridPremium] Fix type import

### LINKED ISSUE #21021: No matching export in "../../node_modules/@mui/x-data-grid-pro/esm/index.js" for import "GridEventLookup"
### Steps to reproduce

Steps:
1. import x-data-grid-premium

### Current behavior

using x-data-grid-premium is importing a component from x-data-grid-pro, causing an error in versione 8.26.0

X [ERROR] No matching export in "../../node_modules/@mui/x-data-grid-pro/esm/index.js" for import "GridEventLookup"
    ../../node_modules/@mui/x-data-grid-premium/esm/typeOverloads/modules.js:1:9:
      1 │ import { GridEventLookup } from '@mui/x-data-grid-pro';

### Expected behavior

GridEventLookup should be imported from premium grid

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 26.2
  Binaries:
    Node: 22.20.0 - /Users/alessiobrunello/.nvm/versions/node/v22.20.0/bin/node
    npm: 10.9.3 - /Users/alessiobrunello/.nvm/versions/node/v22.20.0/bin/npm
    pnpm: 10.25.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 144.0.7559.59
    Edge: Not Found
    Firefox: 145.0.2
    Safari: 26.2
  npmPackages:
    @base-ui/utils:  0.2.4 
    @emotion/react: ^11.10.5 => 11.14.0 
    @emotion/styled: ^11.10.5 => 11.14.1 
    @mui/core-downloads-tracker:  7.3.7 
    @mui/icons-material: ^7.1.0 => 7.3.7 
    @mui/material: ^7.1.0 => 7.3.7 
    @mui/private-theming:  7.3.7 
    @mui/styled-engine:  7.3.7 
    @mui/system:  7.3.7 
    @mui/types:  7.4.10 
    @mui/utils:  7.3.7 
    @mui/x-data-grid:  8.25.0 
    @mui/x-data-grid-premium: 8.25.0 => 8.25.0 
    @mui/x-data-grid-pro:  8.25.0 
    @mui/x-date-pickers:  8.25.0 
    @mui/x-date-pickers-pro: 8.25.0 => 8.25.0 
    @mui/x-internal-exceljs-fork:  4.4.3 
    @mui/x-internals:  8.25.0 
    @mui/x-license:  8.25.0 
    @mui/x-telemetry:  8.20.0 
    @mui/x-tree-view: 8.25.0 => 8.25.0 
    @mui/x-virtualizer:  0.3.2 
    @types/react: 18.3.1 => 18.3.1 
    react: 18.3.1 => 18.3.1 
    react-dom: 18.3.1 => 18.3.1 
    styled-components:  6.3.8 
    typescript: ^5.9.3 => 5.9.3 
```
</details>

**Search keywords**: No matching export in "../../node_modules/@mui/x-data-grid-pro/esm/index.js" for import "GridEventLookup"

### PR DESCRIPTION
**Pull request by arminmeh**
Fixes https://github.com/mui/mui-x/issues/21021

I will make a hotfix release with the fix

### CODE REVIEW

**Comment by arminmeh** [comment]
@Janpot is there a way to catch this without opening Stackblitz?

File: packages/x-data-grid-premium/src/typeOverloads/modules.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import {
+import type {
```
Comment (cherniavskii) [inline packages/x-data-grid-premium/src/typeOverloads/modules.ts:1]: Hmm, any idea why this didn't come up in CI?

**Review by cherniavskii — APPROVED** [review]

File: packages/x-data-grid-premium/src/typeOverloads/modules.ts (hunk 1 above)
Comment (arminmeh) [reply packages/x-data-grid-premium/src/typeOverloads/modules.ts:1]: I guess because
> It only happens when i start in dev mode, not when i run a prod build.

**Comment by ahr-cw-de** [comment]
@arminmeh do you have information when this hotfix will be available?

**Comment by arminmeh** [comment]
> @arminmeh do you have information when this hotfix will be available?

I am working on the release now. I think that it will be there in an hour or two.

**Comment by ahr-cw-de** [comment]
@arminmeh Perfect, thank you for the quick fix! 🙂

**Comment by Janpot** [comment]
> is there a way to catch this without opening Stackblitz?

If you want to enforce type only imports with a `type` directive => https://typescript-eslint.io/rules/consistent-type-imports/
