### PR TITLE
[pickers] Fix `componentsProps.dialog` propagation

### LINKED ISSUE #8506: [pickers] `componentsProps.dialog` not being applied
Hi!

Recently migrated from v4 to v6 and my custom styling for the Dialog part is broken, can't figure out how to solve it.

I used it like this before:
```
<MobileDatePicker
    value={productDate}
    onChange={(newValue) => dateChanged(newValue, index)}
    renderInput={(params) => <TextField {...params} />}
    DialogProps={customcss}
    components={{ActionBar: MyActionBar}}
											/>
```

where the customcss is:
   customcss= {
```
	sx: {
		'& .MuiPaper-root': {
			width: '95%',
			margin: '0',
			height: '880px',
			maxWidth: '95%',
			'& .MuiDialogContent-root': {

				'& > div': {
					flexDirection: 'column',

					'& > div:nth-of-type(2)': {
						width: 'calc(100% - 48px)',
						maxHeight: 'calc(1000px - 32px)'
					},
				},
				'& .MuiPickersToolbar-root.MuiDatePickerToolbar-root': {
					padding: '16px 50px',
					maxWidth: '100%',
					width: 'calc(100% - 100px)',

					'& .MuiGrid-root.MuiGrid-container': {
						flexDirection: 'row',
						display: 'flex',
						alignItems: 'flex-start',
						width: 'auto',

						'& .MuiGrid-root.MuiPickersToolbar-content': {

						}
					}
				} ,......
```

Now I tried like these: 

```
<MobileDatePicker
  value={productDate}
  onChange={(newValue) => {dateChanged(newValue);}}
  textField={(params) => <TextField {...params} />}
  slotProps={{
	  Dialog: {
		  backgroundColor: 'red',
		  sx: {
			  backgroundColor: 'red',
			  '.MuiDialog-root': {
				  backgroundColor: 'red'
			  }
		  }
	  }
  }}
  components={{ActionBar: MyActionBar}}
  />
```

But none has any effect. Thanks!

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #8506 

Fix to correctly apply:
```tsx
componentsProps={{
  dialog: {
    sx: {
      backgroundColor: 'red',
    },
  },
}}
```

Also removed `components` and `componentsProps` from all internal components:
- PickersCalendarHeader
- PickersArrowSwitcher
- PickersModalDialog
- PickersPopper

### CODE REVIEW

File: packages/x-date-pickers/src/internals/components/PickersModalDialog.tsx [hunk 1]
```diff
@@ -94,6 +94,7 @@ export function PickersModalDialog(props: React.PropsWithChildren<PickersModalDi
     <Dialog
       open={open}
       onClose={onDismiss}
+      {...slotProps?.dialog}
       {...componentsProps?.dialog}
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/components/PickersModalDialog.tsx:98]: We can just replace `componentsProps` by `slotProps`
All the pickers are doing the fallback, so the internal components don't have to handle both.

And I think it's the same for the lines after (cc @alexfauquette)

If you use

```
export default function BasicDatePicker() {
    return (
        <LocalizationProvider dateAdapter={AdapterDayjs}>
            <DemoContainer components={['DatePicker']}>
                <MobileDatePicker label="Date Picker" componentsProps={{ dialog: { fullScreen: true } }} />
            </DemoContainer>
        </LocalizationProvider>
    );
}
```

You can see that it still receives `slotProps` inside `PickersModalDialog`

**Review by flaviendelangle — CHANGES_REQUESTED** [review]

File: packages/x-date-pickers/src/internals/components/PickersModalDialog.tsx (hunk 1 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/components/PickersModalDialog.tsx:98]: In summary:

1. The picker (e.g: `DesktopDatePicker`) does the fallback the is `useXXXDefaultizedProps`

```tsx
  const slots = themeProps.slots ?? uncapitalizeObjectKeys(themeProps.components);
  return {
    // ... other props
    slots: { toolbar: DatePickerToolbar, ...slots },
    slotProps: themeProps.slotProps ?? themeProps.componentsProps,
  }
```

2. The headless responsive picker (e.g: `useDesktopPicker`) only receives the new `slots` / `slotProps` API and passes it to the layout, dialog, tooltip, etc...

```tsx
```

3. The internal components only consumes the new API

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/components/PickersModalDialog.tsx:98]: As long as it's not exported from a public endpoint of the library, for me it's not a breaking change on the public API.

Comment (alexfauquette) [reply packages/x-date-pickers/src/internals/components/PickersModalDialog.tsx:98]: I confirm, the 3 components (Date, Time, and DateTime) do the merging in [`shared.ts`](https://github.com/mui/mui-x/blob/master/packages/x-date-pickers/src/DatePicker/shared.tsx) so Dialog should get `slots`, and `componentsProps` is not provided anymore.


If at the same time you can remove it in props typing, it would be a plus 👍

Comment (LukasTy) [reply packages/x-date-pickers/src/internals/components/PickersModalDialog.tsx]: I've gone through all the internal components and [removed `components` and `componentsProps`](https://github.com/mui/mui-x/pull/8509/commits/a8e017f025b2034c5e4ad27f3686af67092e9041).
The `TimeClock` component needed some adjustment as it is public and needs to work with both `components` and `slots` API. 😉

**Review by alexfauquette — APPROVED** [review]
Thanks for the refinement of slots propagation in internals 👍

**Review by flaviendelangle — APPROVED** [review]
Great job cleaning all of this :partying_face:
