### PR TITLE
[DateRangePicker] Fix input focused style and mobile behaviour

### LINKED ISSUE #6627: [DateRangePicker] on mobile opens keyboard after selecting date
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Selecting the date range from the calendar and pressing "OK" automatically focuses to the input and opens keyboard on my Android mobile device. 

### Expected behavior 🤔

Keyboard should not automatically open up. This is the behavior with DatePicker component for example. 

### Steps to reproduce 🕹

Link to live example:
Any example from the documentation: https://mui.com/x/react-date-pickers/date-range-picker/

Steps:
1. Open date selection from the input
2. Select dates and press OK

### Context 🔦

Automatically opening the keyboard after selecting date range is bad UX. 

### Your environment 🌎

_No response_

### Order ID 💳 (optional)

51665

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #6627 

- fix `focused` prop declaration to allow for `focused` styles application both on tab-focus and when picker is open
- add `readonly` prop to `inputProps`  in mobile date range picker to align the behaviour with regular Date Picker and avoiding opening keyboard on mobile when value is selected

### CODE REVIEW

**Review by alexfauquette — COMMENTED** [review]
I don't know why, but it seems to bring a regression. On mobile when clicking on the label, the view does not open (The bug you fixed  in #5651)

I appears in the preview but not in the doc

**Comment by LukasTy** [comment]
> I don't know why, but it seems to bring a regression. On mobile when clicking on the label, the view does not open (The bug you fixed in #5651)

Actually, the correct fix is in https://github.com/mui/mui-x/pull/6074. Will need to replicate something similar. 🤔

File: packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerInput.tsx [hunk 1]
```diff
@@ -144,7 +144,10 @@ export const DateRangePickerInput = React.forwardRef(function DateRangePickerInp
     lazyHandleChangeCallback([start, date], inputString);
   };
 
-  const openRangeStartSelection = () => {
+  const openRangeStartSelection = (
+    event: React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLElement>,
```
Comment (flaviendelangle) [inline packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerInput.tsx:148]: The following is enough if you just want to stop the propagation.
But if you think in the future we might use the event for other things, the more detailed typing can make sense

```suggestion
    event: React.UIEvent
```

Comment (LukasTy) [reply packages/x-date-pickers-pro/src/DateRangePicker/DateRangePickerInput.tsx:148]: Yeah, I was debating about using a more common type, but IMHO—it seems a bit more logical to be explicit. Especially when we know what kind of events might be passed in. 🤔

**Review by flaviendelangle — APPROVED** [review]

**Comment by flaviendelangle** [comment]
I'll make sure that the new range pickers also have this behavior :+1:
