### PR TITLE
[DataGrid] Use `slotProps` to forward props to `.main` and `.root` elements

### LINKED ISSUE #13522: [data grid] The provided aria label prop is attached on the wrong grid element, causing issues with accessibility
### The problem in depth

I am a MUI Pro license user and customers are experiencing accessibility issues with the data grid. The problem is that the aria label that MUI provides is attached to the "wrong" element. It should be attached to the div with the `role="grid"`, so screen readers can pick it up.

Currently, for example, the NVDA screen reader does not correctly read the aria label, in the grid, failing our accessibility requirements. In the below image, the red circle is where the aria label is currently attached, and the green is where it should be (or vise versa). The overall requirement is that the role must be on the same div as the aria label, or else there will be issues with screen readers reading the correct back to the user.

aria-label

**Search keywords**: aria, label
**Order ID**: 79357

### PR DESCRIPTION
**Pull request by MBilalShafi**
Closes #13522
Closes https://github.com/mui/mui-x/pull/14197

Continuation of #14197, thank you @samwato for the original PR.

Motivation for the approach followed: https://github.com/mui/mui-x/pull/14197#issuecomment-2528939781

- [ ] Port the fix to v7 as discussed in https://github.com/mui/mui-x/pull/15870#discussion_r1883514038

### Breaking changes

- Passing additional props (like `data-*`, `aria-*`) directly on the Data Grid component is no longer supported. To pass the props, use `slotProps`.
  - For `.root` element, use `slotProps.root`
  - For `.main` element (the one with `role="grid"`), use `slotProps.main`

### CODE REVIEW

File: packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
Comment (MBilalShafi) [inline packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx:1]: ### Open Question

How to port this to v7? If we treat #13522 as bug, we could port it as it is, as a bug fix.

However, since the discussion [here](https://github.com/mui/mui-x/pull/14197#issuecomment-2304022206) emphasizes it to be a breaking change. To avoid it, we could only introduce `slotProps.main` and keep the current behavior of passing the props to the `.root` element, to at least have a workaround for the v7 users wanting to target (`role="grid"`) element.

We could then make it part of the v8 migration guide to connect the dots.

Any objections @mui/xgrid ?

File: docs/data/migration/migration-data-grid-v7/migration-data-grid-v7.md [hunk 1]
```diff
@@ -34,6 +34,12 @@ Since v8 is a major release, it contains some changes that affect the public API
 These changes were done for consistency, improve stability and make room for new features.
 Below are described the steps you need to make to migrate from v7 to v8.
 
+### Props
+
+- Passing additional props (like `data-*`, `aria-*`) directly on the Data Grid component is no longer supported. To pass the props, use `slotProps`.
+  - For `.root` element, use `slotProps.root`
+  - For `.main` or `role="grid"` element, use `slotProps.main`
```
Comment (cherniavskii) [inline docs/data/migration/migration-data-grid-v7/migration-data-grid-v7.md:41]:
```suggestion
  - For the `.root` element, use `slotProps.root`
  - For the `.main` element (the one with `role="grid"`), use `slotProps.main`
```

File: packages/x-data-grid/src/models/gridSlotsComponentsProps.ts [hunk 2]
```diff
@@ -35,6 +35,8 @@ import type { GridRowCountProps } from '../components/GridRowCount';
 import type { GridColumnHeaderSortIconProps } from '../components/columnHeaders/GridColumnHeaderSortIcon';
 
 type DividerProps = {};
+type RootProps = Record<string, unknown>;
+type MainProps = Record<string, unknown>;
```
Comment (cherniavskii) [inline packages/x-data-grid/src/models/gridSlotsComponentsProps.ts:39]: It should rather be:

```suggestion
type RootProps = React.HTMLAttributes<HTMLDivElement>;
type MainProps = React.HTMLAttributes<HTMLDivElement>;
```

File: packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx
Comment (cherniavskii) [reply packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx:1]: I agree with keeping props forwarding for v7 👍🏻
However, I would also add `slotProps.root`, and if it is provided – skip the forwarding logic in `useProps`.

Comment (MBilalShafi) [reply packages/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx:1]: That sounds even better. 👍

File: packages/x-data-grid/src/models/gridSlotsComponentsProps.ts (hunk 2 above)
Comment (MBilalShafi) [reply packages/x-data-grid/src/models/gridSlotsComponentsProps.ts]: It caused this issue:
image

I assume the same was the reason we didn't use `React.HTMLAttributes<HTMLDivElement>` in the initial [PR](https://github.com/mui/mui-x/pull/8845) when supporting forwarded props.

@romgrk Could you recall by any chance if it was the same reason?

Comment (cherniavskii) [reply packages/x-data-grid/src/models/gridSlotsComponentsProps.ts]: Yeah, `React.HTMLAttributes` does not cover data attributes: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/69864

We can do this instead:
```ts
React.HTMLAttributes<HTMLDivElement> & Record<`data-${string}`, string>
```

File: packages/x-data-grid/src/models/gridSlotsComponentsProps.ts [hunk 3]
```diff
@@ -34,6 +34,8 @@ import type { GridRowCountProps } from '../components/GridRowCount';
 import type { GridColumnHeaderSortIconProps } from '../components/columnHeaders/GridColumnHeaderSortIcon';
 
 type DividerProps = {};
+type RootProps = React.HTMLAttributes<HTMLDivElement> & Record<`data-${string}`, unknown>;
+type MainProps = React.HTMLAttributes<HTMLDivElement> & Record<`data-${string}`, unknown>;
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/models/gridSlotsComponentsProps.ts:38]:
```suggestion
type RootProps = React.HTMLAttributes<HTMLDivElement> & Record<`data-${string}`, string>;
type MainProps = React.HTMLAttributes<HTMLDivElement> & Record<`data-${string}`, string>;
```
