### PR TITLE
[pickers] Unify `PickersMonth` and `PickersYear` behaviors

### LINKED ISSUE #4459: [MonthPicker] Improve the design (could look like YearPicker)
Currently from https://mui.com/components/date-picker/ v5.0.6:
image

Expected to render like YearPicker from https://mui.com/components/date-picker/ v5.0.6:
image

### LINKED ISSUE #5465: [pickers] Incorrect font size in DatePicker with responsiveFontSizes
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When wrapping my Theme with `responsiveFontSizes()` (default config), the `DatePicker` selected month appears bigger.

```
// Augment mui Theme type with DatePicker
import type {} from '@mui/x-date-pickers/themeAugmentation'

import { createTheme, responsiveFontSizes } from '@mui/material/styles'
import { cyan } from '@mui/material/colors'

const theme = responsiveFontSizes(createTheme({
  palette: {
    primary: {
      main: cyan.A700
    }
  }
}))

export default theme
```

Capture d’écran 2022-07-11 à 23 39 27

### Expected behavior 🤔

I'd expect to behave the same desktop size as without the responsive util :

Capture d’écran 2022-07-11 à 23 39 12

### Steps to reproduce 🕹

Steps:

1. Wrap `createTheme` with `responsiveFontSizes`
2. Use `DatePicker` with at least `'month'` view

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.2.1
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Not Found
    Firefox: 93.0
    Safari: 15.3
  npmPackages:
    @emotion/react: ^11.9.3 => 11.9.3 
    @emotion/styled: ^11.9.3 => 11.9.3 
    @mui/base:  5.0.0-alpha.88 
    @mui/icons-material: ^5.8.4 => 5.8.4 
    @mui/material: ^5.8.7 => 5.8.7 
    @mui/private-theming:  5.8.6 
    @mui/styled-engine:  5.8.7 
    @mui/system:  5.8.7 
    @mui/types:  7.1.4 
    @mui/utils:  5.8.6 
    @mui/x-date-pickers: ^5.0.0-beta.0 => 5.0.0-beta.0 
    @types/react: ^18.0.15 => 18.0.15 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: 4.7.4 => 4.7.4 
```
</details>

(used Chrome)

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #5465
Fixes #4459

- [x] Have the same exact behavior between `PickersMonth` and `PickersYear`
- [x] Have the same exact behavior between `MonthPicker` and `YearPicker`
- [x] Spread props to the root on `MonthPicker` and `YearPicker` (requires removing the `...other` props to `YearPicker` in `CalendarPicker`)

@alexfauquette I hope I did not introduce any regression in your recent improvements.

### CODE REVIEW

File: packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx [hunk 1]
```diff
@@ -1,106 +1,161 @@
...
-      onFocus={(event: React.FocusEvent) => onFocus(event, value)}
-      onBlur={(event: React.FocusEvent) => onBlur(event, value)}
-      {...other}
-    />
+    <PickersYearRoot data-mui-test="month" className={classes.root} ownerState={ownerState}>
+      <PickersYearButton
+        ref={ref}
+        disabled={disabled}
+        type="button"
+        data-mui-test={`month-${value}`}
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx:142]: I don't see why adding it. aria label should allow to find the correct month. And if not, it means we have a11y problem
```suggestion
```

File: packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx [hunk 2]
```diff
@@ -1,106 +1,161 @@
...
+        tabIndex={disabled ? -1 : tabIndex}
+        onClick={(event) => onClick(event, value)}
+        onKeyDown={(event) => onKeyDown(event, value)}
+        onFocus={(event) => onFocus(event, value)}
+        onBlur={(event) => onBlur(event, value)}
+        className={classes.yearButton}
+        ownerState={ownerState}
+        {...other}
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx:150]: Should the `...other` be in the root component?

File: packages/x-date-pickers/src/YearPicker/PickersYear.tsx [hunk 3]
```diff
@@ -96,29 +104,25 @@ const PickersYearButton = styled('button')<{
...
-    onFocus = noop,
-    onBlur = noop,
+    onClick,
+    onKeyDown,
+    onFocus,
+    onBlur,
     ...other
   } = props;
   const ref = React.useRef<HTMLButtonElement>(null);
-  const refHandle = useForkRef(ref, forwardedRef as React.Ref<HTMLButtonElement>);
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/YearPicker/PickersYear.tsx:121]: I never really get the point of using  `useForkRef` or not

File: packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx [hunk 4]
```diff
@@ -1,106 +1,161 @@
...
-      disabled={disabled}
-      onFocus={(event: React.FocusEvent) => onFocus(event, value)}
-      onBlur={(event: React.FocusEvent) => onBlur(event, value)}
-      {...other}
-    />
+    <PickersYearRoot data-mui-test="month" className={classes.root} ownerState={ownerState}>
+      <PickersYearButton
+        ref={ref}
+        disabled={disabled}
+        type="button"
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx:141]: It is, otherwise when place in a `form` it behaves as a `submit` and submits the form.

https://github.com/mui/mui-x/pull/4402

File: packages/x-date-pickers/src/YearPicker/PickersYear.tsx (hunk 3 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/YearPicker/PickersYear.tsx:121]: From what I understand, it allows to merge a ref received on the component and a ref created internally and pass the merged version to the DOM.

`useForkRef` then makes sure that both the received ref and the internal ref are kept up to date

File: packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx (hunk 2 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx]: I followed the behavior of `PickersYear` but I agree that it's not following our guidelines.

Switched for both

File: packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx [hunk 5]
```diff
@@ -1,106 +1,161 @@
...
+const PickersYearRoot = styled('div')<{
+  ownerState: PickersMonthOwnerState;
+}>(({ ownerState }) => ({
+  flexBasis: '33.3%',
   display: 'flex',
   alignItems: 'center',
   justifyContent: 'center',
+  ...(ownerState?.wrapperVariant === 'desktop' && {
+    flexBasis: '25%',
+  }),
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx:74]: Small mistake here, I removed the switch to 4 months on desktop that we currently don't have.

As for the grid, we can play with it in a follow up.

File: packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx (hunk 1 above)
Comment (alexfauquette) [reply packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx]: If it does not break tests yes

Comment (flaviendelangle) [reply packages/x-date-pickers/src/MonthPicker/PickersMonth.tsx]: I removed it and all the test are passing :+1:

File: packages/x-date-pickers/src/MonthPicker/MonthPicker.tsx [hunk 6]
```diff
@@ -143,76 +148,65 @@ export const MonthPicker = React.forwardRef(function MonthPicker<TDate>(
...
-    state: 'hasFocus',
-    controlled: hasFocus,
-    default: autoFocus,
+    return shouldDisableMonth(month);
   });
 
-  const changeHasFocus = React.useCallback(
-    (newHasFocus: boolean) => {
-      setInternalHasFocus(newHasFocus);
+  const handleMonthSelection = useEventCallback((event: React.MouseEvent, year: number) => {
```
Comment (LukasTy) [inline packages/x-date-pickers/src/MonthPicker/MonthPicker.tsx:192]: Shouldn't it be `month` as previously? 🤔 
```suggestion
  const handleMonthSelection = useEventCallback((event: React.MouseEvent, month: number) => {
```

Comment (flaviendelangle) [reply packages/x-date-pickers/src/MonthPicker/MonthPicker.tsx]: :see_no_evil:

File: packages/x-date-pickers/src/YearPicker/PickersYear.tsx [hunk 7]
```diff
@@ -141,23 +145,27 @@ export const PickersYear = React.forwardRef<HTMLButtonElement, YearProps>(functi
       data-mui-test="year"
       className={clsx(classes.root, className)}
       ownerState={ownerState}
+      {...other}
```
Comment (LukasTy) [inline packages/x-date-pickers/src/YearPicker/PickersYear.tsx:148]: Similar issue is also happening here because of the change where `other` is spread.
Screenshot 2022-09-06 at 16 59 26
`aria-current` should be on the `button` instead of the wrapping `div`.

Comment (flaviendelangle) [reply packages/x-date-pickers/src/YearPicker/PickersYear.tsx:148]: Indeed, I may have been a bit quick on my change.
Typescript was not complaining that `aria-current` was not present in the props.

I checked and unless I missed one, all the other props passed to `PickersYear` and `PickersMonth` are correctly handled.

Comment (LukasTy) [reply packages/x-date-pickers/src/YearPicker/PickersYear.tsx:150]: Yes, as far as I've tested other places with generic examples, it seemed to work fine. 👌

**Review by LukasTy — APPROVED** [review]

**Review by alexfauquette — APPROVED** [review]
Does no seems to introduce any regression 👌

**Comment by flaviendelangle** [comment]
I think the diff makes sense
