### PR TITLE
[charts] Fix area order when overlapping

### LINKED ISSUE #13067: [charts] Transparent fills in area line charts overlap causing color mixing issues
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/blazing-hill-sxq2zg

### Current Behavior
In the current implementation of the line chart, I have adjusted the area fill color to include a transparent fill. This can be seen in the screenshot below. The issue arises where the areas corresponding to two different lines intersect. The transparency of these fills results in the colors mixing together, making it difficult to distinguish between the two lines in certain sections of the chart.

**Current behavior screenshot:**

Current Behavior

### Expected Behavior
Ideally, the areas should remain visually distinct even when overlapping. The screenshot below illustrates the desired outcome where each area's color does not blend into the other, which was temporarily achieved by stacking the areas. However, stacking is not a viable solution in this case, as the data series do not cumulatively represent a total value.

**Expected behavior screenshot:**

Expected Behavior

### Suggested Fix
One potential solution could involve the use of SVG clip paths, which have been effectively utilized in other parts of the chart to manage overlapping visual elements. Implementing clip paths could help maintain the visual integrity of each area without the colors merging.

### Context
This issue is important as the chart is intended to display several arbitrary values that do not collectively contribute to a total but still need to support transparent area fills. Achieving clear visual differentiation between overlapping areas is crucial for accurate data representation.

**Context screenshot:**

Chart Context

### Environment
N/A

### Search Keywords
- Transparent area chart
- Chart color overlap
- SVG clip path in charts

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #13067

I would still discourage the use of overlapping areas except for very specific edge case (such the one in the issue) 🙈

With no structure

image

With guarantee some series are always smaller than others

image

I introduced this `reverse` when creating the animation, otherwise you get a weird state with the line and the area not in sync, just because the area on top of you is overlapping  (the time it finishes its animation too)

This fix applies the reverse on staking groups instead of all series.
- For staked series, they do not overflow so we can reverse the series order
- For non-stacked series, we do not apply the reverse and so they overlap correctly

### CODE REVIEW

File: packages/x-charts/src/LineChart/AreaPlot.tsx [hunk 1]
```diff
@@ -47,62 +47,66 @@ const useAggregatedData = () => {
...
-        if (xData === undefined) {
-          throw new Error(
-            `MUI X Charts: ${
-              xAxisKey === DEFAULT_X_AXIS_KEY
-                ? 'The first `xAxis`'
-                : `The x-axis with id "${xAxisKey}"`
-            } should have data property to be able to display a line plot.`,
-          );
+    return [...groupIds]
+      .reverse() // Revert staked area for a more pleasant animation
```
Comment (JCQuintas) [inline packages/x-charts/src/LineChart/AreaPlot.tsx:51]: minnor typo on comment
```suggestion
      .reverse() // Revert stacked area for a more pleasant animation
```

**Review by JCQuintas — APPROVED** [review]
