### PR TITLE
[fields] Support format without separator

### LINKED ISSUE #12487: [pickers] Cannot display time with format without spaces like "HHmm" correctly
### Steps to reproduce

Link to live example: (required)
https://stackblitz.com/edit/react-jjpkxw?file=Demo.tsx

Steps:

1. Set format="HHmm" in TimeField
2. Give it a defaultValue (15:30)

Version: 6.19.7

`dayjs` and `TimeField` are used in the example

`moment` and `DateTimePicker` also have this problem.

In [#10007](https://github.com/mui/mui-x/issues/10007) and [#10185](https://github.com/mui/mui-x/pull/10185) said it was fixed, but same problem on `dayjs` and `moment`

### Current behavior

It displays `15m30` 

### Expected behavior

It should display `1530`

### Context

Showing time with format `HHmm` in `DateTimePicker` with `Moment`

### Your environment

_No response_

**Search keywords**: DateTimePicker TimeField HHmm format moment dayjs

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fix #12487

### CODE REVIEW

File: packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts [hunk 1]
```diff
@@ -214,6 +214,10 @@ export class AdapterLuxon implements MuiPickersAdapter<DateTime, string> {
     // Extract escaped section to avoid extending them
     const catchEscapedSectionsRegexp = /''|'(''|[^'])+('|$)|[^']*/g;
 
+    // This RegExp tests if a string is only mad of supported tokens
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts:217]: This method was escaping tokens when they were not separated by any character.

File: packages/x-date-pickers/src/internals/hooks/useField/buildSectionsFromFormat.ts [hunk 2]
```diff
@@ -202,56 +202,48 @@ const buildSections = <TDate extends PickerValidDate>(
...
   let startSeparator: string = '';
 
-  // This RegExp test if the beginning of a string corresponds to a supported token
-  const isTokenStartRegExp = new RegExp(
-    `^(${Object.keys(utils.formatTokenMap)
-      .sort((a, b) => b.length - a.length) // Sort to put longest word first
-      .join('|')})`,
-    'g', // used to get access to lastIndex state
-  );
+  // This RegExp tests if the beginning of a string corresponds to a supported token
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useField/buildSectionsFromFormat.ts:205]: I reworked this method because it was duplicating the 1st character of the 2nd token (once inside the token and once as a separator).

Since we catch the whole token in one passage in the loop, we can replace the `for` with a `while` and stop populating `currentTokenValue` incrementaly. This makes the whole behavior simple IMHO.

File: packages/x-date-pickers/src/internals/hooks/useField/buildSectionsFromFormat.ts [hunk 3]
```diff
@@ -202,56 +202,53 @@ const buildSections = <TDate extends PickerValidDate>(
...
+  const isTokenStartRegExpStr = `^(${Object.keys(utils.formatTokenMap)
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useField/buildSectionsFromFormat.ts:206]: Not sure why but my code does not work if I re-use the same `RegExp` object
So I just created the string outside of the loop and the `RegExp` object inside it.

File: packages/x-date-pickers/src/internals/hooks/useField/buildSectionsFromFormat.ts [hunk 4]
```diff
@@ -202,56 +202,60 @@ const buildSections = <TDate extends PickerValidDate>(
...
 
-    if (!isEscapedChar && char.match(/([A-Za-z]+)/) && regExpMatch) {
-      currentTokenValue = potentialToken.slice(0, isTokenStartRegExp.lastIndex);
-      i += isTokenStartRegExp.lastIndex - 1;
-    } else {
       // If we are on the opening or closing character of an escaped part of the format,
       // Then we ignore this character.
       const isEscapeBoundary =
         (isEscapedChar && escapedPartOfCurrentChar?.start === i) ||
         escapedPartOfCurrentChar?.end === i;
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/internals/hooks/useField/buildSectionsFromFormat.ts:247]: What about moving the pointer directly to the end of the escaped section instead of adding character one by one to `startSeparator`?

Does not really matter

**Review by alexfauquette — APPROVED** [review]
:+1:

File: packages/x-date-pickers/src/internals/hooks/useField/buildSectionsFromFormat.ts (hunk 4 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/useField/buildSectionsFromFormat.ts:247]: I'll have a look on how to do that
