### PR TITLE
[DataGridPremium] Fallback to the regular reorder method for plain data

### LINKED ISSUE #19454: [data grid] Drag and drop events appear to have changed again 8.11.0 causing tests to fail.
### The problem in depth

MUI introduced a change to the drag & drop events in version 8.9.1 that required us to update our drag & drop tests. MUI helpfully provided an example of how to write our tests given the changes made in version 8.9.1. See this [issue](https://github.com/mui/mui-x/issues/18938).

Now the drag & drop tests are broken again in version 8.11.0. The same test that was passing in version 8.9.1 now fails in version 8.11.0 with this error:

` Cannot set properties of undefined (setting 'effectAllowed')`

Please advise on how to make the test pass given your new changes.

You can use the same repo provided in issue 18938 to reproduce. 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
   System:
    OS: macOS 15.6.1
  Binaries:
    Node: 22.17.0 - ~/.nvm/versions/node/v22.17.0/bin/node
    npm: 10.9.2 - ~/.nvm/versions/node/v22.17.0/bin/npm
    pnpm: 9.12.2 - ~/.nvm/versions/node/v22.17.0/bin/pnpm
  Browsers:
    Chrome: Not Found
    Edge: 139.0.3405.125
    Safari: 18.6
  npmPackages:
    @emotion/react: latest => 11.14.0 
    @emotion/styled: latest => 11.14.1 
    @mui/core-downloads-tracker:  7.2.0 
    @mui/icons-material: latest => 7.2.0 
    @mui/material: 7.2.0 => 7.2.0 
    @mui/private-theming:  7.2.0 
    @mui/styled-engine:  7.2.0 
    @mui/system: 7.2.0 => 7.2.0 
    @mui/types:  7.4.4 
    @mui/utils:  7.3.2 
    @mui/x-data-grid:  8.11.0 
    @mui/x-data-grid-premium: 8.11.0 => 8.11.0 
    @mui/x-data-grid-pro:  8.11.0 
    @mui/x-internals:  8.11.0 
    @mui/x-license:  8.11.0 
    @mui/x-telemetry:  8.11.0 
    @mui/x-virtualizer:  0.1.4 
    @types/react: ^18.3.3 => 18.3.4 
    react: 19.1.0 => 19.1.0 
    react-dom: 19.1.0 => 19.1.0 
    typescript: ^5.5.3 => 5.5.4 
```
</details>

**Search keywords**: Drag & Drop

**Order ID**: 45466

### PR DESCRIPTION
**Pull request by MBilalShafi**
Fixes #19454

Will standardize it in #19401

### CODE REVIEW

File: packages/x-data-grid-premium/src/hooks/features/rows/useGridRowsOverridableMethods.ts [hunk 1]
```diff
@@ -17,9 +21,13 @@ export const useGridRowsOverridableMethods = (
   props: Pick<DataGridPremiumProcessedProps, 'processRowUpdate' | 'onProcessRowUpdateError'>,
 ) => {
   const { processRowUpdate, onProcessRowUpdateError } = props;
+  const { setRowIndex: setRowIndexPlain } = useGridRowsOverridableMethodsCommunity(apiRef, props);
```
Comment (MBilalShafi) [inline packages/x-data-grid-premium/src/hooks/features/rows/useGridRowsOverridableMethods.ts]:
```suggestion
  const { setRowIndex: setRowIndexPlain } = useGridRowsOverridableMethodsCommunity(apiRef);
```

File: packages/x-data-grid-premium/src/hooks/features/rows/useGridRowsOverridableMethods.ts [hunk 2]
```diff
@@ -17,9 +21,14 @@ export const useGridRowsOverridableMethods = (
   props: Pick<DataGridPremiumProcessedProps, 'processRowUpdate' | 'onProcessRowUpdateError'>,
 ) => {
   const { processRowUpdate, onProcessRowUpdateError } = props;
+  const { setRowIndex: setRowIndexPlain } = useGridRowsOverridableMethodsCommunity(apiRef);
 
   const setRowIndex = React.useCallback(
     async (sourceRowId: GridRowId, targetOriginalIndex: number) => {
+      if (gridRowMaximumTreeDepthSelector(apiRef) === 1) {
```
Comment (arminmeh) [inline packages/x-data-grid-premium/src/hooks/features/rows/useGridRowsOverridableMethods.ts]: instead of this, you can
```tsx
return {
  setRowIndex: gridRowMaximumTreeDepthSelector(apiRef) === 1 ? setRowIndexPlain : setRowIndex,
}
```
at the end of the file.
This way, you will not call the premium version of the method, which will call the community version inside of it.

Additionally, you can extract `gridRowMaximumTreeDepthSelector(apiRef) === 1` into a variable and rename row index methods, to end up with something like

```tsx
return {
  setRowIndex: flatTree ? setFlatRowIndex : setTreeRowIndex,
}
```

**Review by arminmeh — APPROVED** [review]
