### PR TITLE
[pickers] Add date-fns@3.x adapter

### LINKED ISSUE #11454: [pickers] Add support for date-fns 3.0
### Steps to reproduce

Install `date-fns` 3.0.0 or higher when using `@mui/x-date-pickers`.

### Current behavior

Currently, when using @mui/x-date-pickers together with date-fns version 3.0.0, npm will return the following error:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: --
npm WARN Found: date-fns@2.30.0
npm WARN node_modules/date-fns
npm WARN   date-fns@"3.0.0" from the root project
npm WARN   1 more (@mui/x-date-pickers)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional date-fns@"^2.25.0" from @mui/x-date-pickers@6.18.5
npm WARN node_modules/@mui/x-date-pickers
npm WARN   @mui/x-date-pickers@"6.18.5" from the root project
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '--',
npm WARN EBADENGINE   required: { node: '18.x', npm: '8.x' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.2.4' }
npm WARN EBADENGINE }
```

The application won't run.

### Expected behavior

The application does run and installing date-fns version 3.0 works without errors.

### Context

_No response_

### Your environment

_No response_

**Search keywords**: date time picker

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #11454 

> [!NOTE]
> The adapter for `date-fns@v3` is available using `@mui/x-date-pickers/AdapterDateFnsV3`.
> The minimum supported `date-fns` package version for this adapter is `3.2.0`.

~~It does not seem doable without breaking changes, due to changes in export (move to ESM).
I'm not sure that going with date-fns v3 for v7 would be a good plan. 🤔~~

The current approach is to explore the possibility of introducing an `AdapterDateFnsV3` that would work with v3 date-fns and keep the original adapter intact as suggested here: https://github.com/mui/mui-x/pull/11462#issuecomment-1864301399.

The question could be—do we want to inverse this logic before stable v7 and have a breaking change:
v6:
- `AdapterDateFns` works with date-fns v2
- `AdapterDateFnsV3` works with date-fns v3
v7:
- `AdapterDateFns` works with date-fns v3
- `AdapterDateFnsV2` works with date-fns v2

If date-fns v3 turns out to be the new standard, then having the v6 approach might be a bit strange during v7. 🤔 

### My proposal
1. Introduce it as `v6` on both v7 prerelease and v6
2. Switch to `v7` approach before stable release
3. Consider adding a codemod to fix adapter imports
4. (Optional) Deprecate date-fns v2 adapter on v7

~### ⚠️ The main problem with the approach:
Either v2 or v3 adapter is not tested. 🤷 
Do you think that it's worth investing time to configure tests to run on both major versions of `date-fns`?~
A hacky solution to test both adapters is introduced with: https://github.com/mui/mui-x/pull/11462/commits/a2aa1247156a22af742ce573aae610fa17fe734e

### CODE REVIEW

**Comment by flaviendelangle** [comment]
Did you consider exporting a `AdapterDateFnsV3` adapter for v7 and keep the current one ?
We could even avoid duplicating the adapter code with something like:



````tsx
import { format } from 'date-fns/format'
// ... all other imports

export const AdapterDateFnsV3 = createDateFnsAdapter({ format, ... });
````

And same for the v2.

It adds complexity but I think it's worth considering.

And btw it could allow us to not override ALL the adapter for `AdapterDateFnsJalali`

**Comment by LukasTy** [comment]
> Did you consider exporting a `AdapterDateFnsV3` adapter for v7 and keeping the current one, at least for v7 ?

That seems like a super nice approach! 👍 
Thanks for the suggestion.
Will look into it.
In this case, it might even be possible to add the support for v6. 🤔 

> And btw it could allow us to not override ALL the adapter for AdapterDateFnsJalali

I'm not sure if we need to touch those. They do not seem to rely on date-fns at all. 🤔

**Comment by flaviendelangle** [comment]
> In this case, it might even be possible to add the support for v6. 🤔

You will not be able to copy-paste it because the adapters have changes since the start of the alpha.
And one could say that it's a good reason to make people migrate to v7.
But we can discuss in our next meeting if we want to back-port it

**Review by michelengelen — APPROVED** [review]
nice improvement!

**Comment by flaviendelangle** [comment]
Did you run in some issue trying to not duplicate the logic?

**Comment by flaviendelangle** [comment]
> Do you think that it makes sense to create a typed constructor with a bunch of required functions that we would have to type explicitly just to avoid the duplication of methods?

I'm not sure
I'm always worried when we duplicate that we end up with unwanted divergence
But maybe the requirements to avoid this duplication are just too problematic

**Review by michelengelen — APPROVED** [review]

**Comment by michelengelen** [comment]
> > Do you think that it makes sense to create a typed constructor with a bunch of required functions that we would have to type explicitly just to avoid the duplication of methods?
> 
> I'm not sure I'm always worried when we duplicate that we end up with unwanted divergence But maybe the requirements to avoid this duplication are just too problematic

I was wondering the same during the review ... IMO the extraction into a base adapter that gets extended is the way to go to prevent said divergence. 

Especially with the background that this is probably only an intermittent step to provide a solution to use date-fns v3

**Comment by flaviendelangle** [comment]
By the way @LukasTy it would be awesome to have a clean error thrown when using `AdapterDateFns` with date-fns v3 saying to use the new adapter.
I guess that by default we would have some "xxx is not a function"

**Comment by LukasTy** [comment]
Thanks for another great suggestion @flaviendelangle! 👍

File: packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts [hunk 1]
```diff
@@ -79,6 +80,14 @@ export class AdapterDateFns
   implements MuiPickersAdapter<Date, DateFnsLocale>
 {
   constructor({ locale, formats }: AdapterOptions<DateFnsLocale, never> = {}) {
+    if (!version.startsWith('2.')) {
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts:83]: I guess we would bundle the whole `package.json` which is not ideal.
It would be great to be able to import the version from the package, but if they don't make this information available, maybe it's better to infer the major version from some API that changed rather than importing the `package.json`.

Comment (LukasTy) [reply packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts]: Thanks for the tip.
I've used the imported function to identify the major: https://github.com/mui/mui-x/pull/11462/commits/22528bcfd6e8ba28bce24836ee8c021802c47c10
Seems to do the trick based on my testing. 💯 
WDYT? 🤔

Comment (flaviendelangle) [reply packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts]: I think it's the easiest and best trick we can do :ok_hand:

**Comment by flaviendelangle** [comment]
> Either v2 or v3 adapter is not tested. 🤷
> Do you think that it's worth investing time to configure tests to run on both major versions of date-fns?

I think that, if it's not a technical nightmare, running `describeGregorianAdapter` would be awesome, the rest is useless IMHO.

**Comment by LukasTy** [comment]
> I think that, if it's not a technical nightmare, running `describeGregorianAdapter` on both versions would be awesome, the rest is useless IMHO.

WDYT about this approach: https://github.com/mui/mui-x/pull/11462/commits/a2aa1247156a22af742ce573aae610fa17fe734e? 🤔 
Looks pretty hacky, but it works™. 😆 

I've also decided to make the adapter stable: https://github.com/mui/mui-x/pull/11462/commits/5c6d33152f6c46910e754f362732f5da91269200
WDYT about that? 🤔 

P.S. Requesting a re-review. 😉

File: docs/data/date-pickers/adapters-locale/adapters-locale.md [hunk 2]
```diff
@@ -40,9 +40,23 @@ import 'dayjs/locale/de';
 
 For `date-fns`, import the locale and pass it to `LocalizationProvider`:
 
+:::info
+We support both `date-fns` major versions (v2.x and v3.x).
```
Comment (LukasTy) [inline docs/data/date-pickers/adapters-locale/adapters-locale.md:44]:
```suggestion
Both `date-fns` major versions (v2.x and v3.x) are supported.
```

File: packages/x-date-pickers/src/internals/models/helpers.ts [hunk 3]
```diff
@@ -10,6 +10,8 @@ export type ExtendMui<C, Removals extends keyof C = never> = Omit<
 
 export type MakeOptional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;
 
+export type MakeRequired<T, K extends keyof T> = T & Required<Pick<T, K>>;
```
Comment (michelengelen) [inline packages/x-date-pickers/src/internals/models/helpers.ts:13]: nit: not sure if we need to `Omit` `K` first before making it required. It will work like this, but it is more consistent that way.

```suggestion
export type MakeRequired<T, K extends keyof T> = Omit<T, K> & Required<Pick<T, K>>;
```

Comment (LukasTy) [reply packages/x-date-pickers/src/internals/models/helpers.ts:13]: Sure, will apply it for consistency with `MakeOptional`.
They both work and do the same. 👌

Comment (michelengelen) [reply packages/x-date-pickers/src/internals/models/helpers.ts]: Yep ... that's why i marked it as nit! Thanks! 🙇🏼

**Review by flaviendelangle — APPROVED** [review]
I''m fine with the somehow hacky testing approach

And no problem making the adapter stable, it's not less stable than the v2 version IMHO
