### PR TITLE
[DataGrid] Add generic typing to GridColDef and derived interfaces

### LINKED ISSUE #545: Generic TypeScript Types
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

It would be great if the `XGrid`, `DataGrid` and other components utilized TS generics for the type system.  For instance, in [DataGrid](https://material-ui.com/api/data-grid/#datagrid-api), the type for `onRowSelected` is `(param: RowSelectedParams) => void`.  `RowSelectedParams` contains a `data` prop that has a type as follows:

```
interface RowData extends ObjectWithId {
    [key: string]: any;
}
```

A developer should really be able to pass in a type parameter to either `RowSelectedParams` like `RowSelectedParams<MyRowDataShape>` so that the `data` prop comes back with a proper type in TS.  There are other instances of the type system for MUI-X that could greatly benefit from generics.

It would be super useful for TS users!  Right now, I am just using type assertions to coerce the type of things (like `data` above) into the proper shape.

## Examples 🌈

Examples above.

## Motivation 🔦

Motivation above.  A better type system is just overall an improvement for TS users.

Thanks!

### LINKED ISSUE #3741: [DataGrid] Improve `sortComparator` typing
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently for TypeScript to stop complaining users have to use type assertion, e.g.:
```tsx
sortComparator: (v1, v2) =>
  (v1 as { label: string }).label.localeCompare(
    (v2 as { label: string }).label,
  ),
```

### Examples 🌈

_No response_

### Motivation 🔦

_No response_

### Order ID 💳 (optional)

_No response_

### LINKED ISSUE #4109: [data-grid] Remove prop-types warning when passing an array to a cell
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

[DataGrid] it looks like Datagrid dropped support for rendering arrays as grid cells, I could not find this change on the changelog
is it a bug?
in the previous versions (before 5.6.0), this wasn't a problem, but after updating to 5.6.0 it shows a warning

### Expected behavior 🤔

_No response_

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
Part of #1329
Fixes #3741
Fixes #4109
Fixes #545 (I will keep #1329 as the only long running issue for future improvements)

## Goal

Allow users to strongly type all the objects related to the row and the cell values

Note that I did not try to type anything based on the `GridColDef["type"]` property because it makes the typing very complex and my experience on React Table was that trying to be too smart often lead to problems.

## Steps

- [x] Type the interfaces
- [x] Fix the demo and `@mui/x-data-grid-generator`
- [x] Add spec tests
- [ ] Add a TypeScript standalone page on the doc (maybe later ?)

### Explicit column type declaration

```tsx
const decadeColumn:  GridColDef<Movie, number, string> = {
    field: 'decade',

    // typeof params.row => Movie (R)
    // return type => number (V)
    valueGetter: (params) => Math.floor(params.row.year / 10) * 10,

    // typeof params.row => Movie (R)
    groupingValueGetter: (params) => Math.floor(params.row.year / 10) * 10,

    // typeof params.value => number | undefined (V | undefined)
    valueFormatter: (params) => `${params.value?.toString().slice(-2) ?? ''}'s`,

    // typeof value => string (F)
    valueParser: (value) => Number(value?.slice(0, -2)),

    // typeof params.row => Movie (R)
    // typeof params.value => number (V) (should it be F ?)
    valueSetter: (params) => ({ ...params.row, year: params.value * 10 }),

    // typeof params.formattedValue => string (F)
    renderCell: (params) => <strong>{params.formattedValue}</strong>,

    // typeof v1 => number (V)
    // typeof v2 => number (V)
    // typeof cellParams1.value => number (V)
    // typeof cellParams1.value => number (V)
    // Side note, why do we have both v1 and cellParams1.value ? Isn't it redundant ?
    sortComparator: (v1, v2, cellParams1, cellParams2) => gridNumberComparator(v1, v2, cellParams1, cellParams2),

    filterOperators: [  {
        // typeof column => GridColDef<Movie, number, string> (GridColDef<R, V, F>)
        getApplyFilterFn: (filterItem, column) => {
            // typeof params.value => number | undefined (V | undefined)
            // typeof params.row => Movie (R)
            // typeof params.formattedValue => string (F)
            return params => true;
        },
        // ... other properties
    }]
}
```

### Forced column type

This syntax allows to type without declaring a variable per column and still works for most of the mis-usages

```ts
const columns: GridColDef<Movie>[] = [
    {
        // All the properties are typed like on the 1st example
        field: 'decade',
        // typeof params.row => Movie (R)
        // return type => number (V)
        valueGetter: (params) => Math.floor(params.row.year / 10) * 10,
    } as GridColDef<Movie, number, string>,
    {
        // All the properties are typed like on the 1st example
        field: 'isNineties',
        // typeof params.row => Movie (R)
        // return type => boolean (V)
        valueGetter: (params) => params.row.year >= 1990 && params.row.year <= 1999,
    } as GridColDef<Movie, boolean>,
]
```

### Property explicit type

It is still possible to type each property, even if not recommended.

```ts
const columns: GridColDef[] = [
    {
        // The row is typed on all the properties the 1st example
        // The value and formattedValue is not typed 
        field: 'decade',
        // typeof params.row => Movie (R)
        // return type => number (V)
        valueGetter: (params: GridValueGetterParams<number, Movie>) => Math.floor(params.row.year / 10) * 10,
    },
]
```

### Explicit generic on `DataGrid`

```tsx
<DataGrid<Movie> 
  rows={[]}
  columns={[{ 
    // The row is typed on all the properties the 1st example
    // The value and formattedValue is not typed 
    field: 'year',
    // typeof params.row => Movie (R)
    valueGetter: params => params.row.year, 
  }]}
/>
```

### Implicit generic on `DataGrid`

```tsx
const rows: Movie[] = []

return (
  <DataGrid 
    rows={rows}
    columns={[{ 
      // typeof params.row => Movie (R)
      valueGetter: params => params.row.year, 
    }]}
  />
)
```

### Explicit prop typing

`DataGridProps` and `DataGridProProps` now take a generic.
It can be useful to declare a prop without importing all its params / return type

```tsx
const props: DataGridProps<Movie> = {
  columns
  rows,
  // typeof row => Movie (R)
  getRowId: (row) => row.id
}
```

### CODE REVIEW

**Comment by nghieptiki** [comment]
Looking forward to the completion of the PR 💯

File: packages/grid/x-data-grid/src/models/colDef/gridColDef.ts [hunk 1]
```diff
@@ -236,13 +241,21 @@ export interface GridActionsColDef extends GridColDef {
...
-export type GridColumns = GridEnrichedColDef[];
+export type GridColumns<R extends GridValidRowModel = any> = GridEnrichedColDef<R>[];
 
-export type GridColTypeDef = Omit<GridColDef, 'field'> & { extendType?: GridNativeColTypes };
+export type GridColTypeDef<V = any, F = V> = Omit<GridColDef<V, any, F>, 'field'> & {
+  extendType?: GridNativeColTypes;
+};
 
-export type GridStateColDef = GridEnrichedColDef & {
+export type GridStateColDef<R extends GridValidRowModel = any, V = any, F = V> = GridEnrichedColDef<
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/models/colDef/gridColDef.ts:254]: What do you think about using more descriptive naming for generic types?
For example `TRow/TRowModel` instead of `R` etc?

File: packages/grid/x-data-grid-generator/src/renderer/renderEditRateType.tsx [hunk 2]
```diff
@@ -1,65 +0,0 @@
-import * as React from 'react';
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-generator/src/renderer/renderEditRateType.tsx:1]: I assume it wasn't used?

**Review by cherniavskii — APPROVED** [review]
This looks great, good job! 🎉

File: packages/grid/x-data-grid/src/models/colDef/gridColDef.ts (hunk 1 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/models/colDef/gridColDef.ts:254]: @m4theushw was in favor of one letter generics.
One thing to consider is that on the doc, the generics already make the api lists heavier, it would probably become very heavy visually with longer names (see the `getCellParams` line [here](https://deploy-preview-4064--material-ui-x.netlify.app/api/data-grid/grid-api/)

File: packages/grid/x-data-grid-generator/src/renderer/renderEditRateType.tsx (hunk 2 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid-generator/src/renderer/renderEditRateType.tsx:1]: Yes, I was to lazy to migrate unused packages :D

File: packages/grid/x-data-grid/src/models/colDef/gridColDef.ts (hunk 1 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/models/colDef/gridColDef.ts:254]: For me personally, if longer name is more descriptive (i.e. I don't have to guess what it means) - it's much better DX.
But if one letter generics is a convention we adopted and agreed on - it's fine with me.
I'm curious to hear @m4theushw thoughts for this specific case.

BTW, is it possible to use JSDoc to have description for generic types?

Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/models/colDef/gridColDef.ts:254]: > BTW, is it possible to use JSDoc to have description for generic types?

Yes
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#template

I used it on this PR, but probably not everywhere.

**Comment by flaviendelangle** [comment]
I am merging this one
We will be able to rename the generic later on without any breaking change (even for typing)
