### PR TITLE
[DataGridPro] checkboxSelection & treeData/grouping bug

### LINKED ISSUE #9402: [DataGridPro] Removing a row with treeData and checkboxSelection enabled crashes the DataGrid
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-datagrid-tree-issue-4pvxjv?file=/demo.tsx

Steps:
1. Open the live example
2. Click on on the button "Remove 1 row"
3. An error appears

If you remove the **checkboxSelection** (or set it to false), the error does not occur. So it seems related to **treeData** and **checkboxSelection** enabled at the same time.

### Current behavior 😯

An error occurs:

image

### Expected behavior 🤔

The datagrid should simply re re-render with the new rows.

### Context 🔦

Altering rows displaying by the DataGrid.

### Your environment 🌎

Browser: Chrome Version 114.0.5735.133 (Official Build) (arm64) 
<details>
  <summary><code>npx @mui/envinfo</code></summary>
```
 System:
    OS: macOS 13.4
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.5
  npmPackages:
    @mui/icons-material: 5.11.16 => 5.11.16 
    @mui/lab: 5.0.0-alpha.134 => 5.0.0-alpha.134 
    @mui/material: 5.13.5 => 5.13.5 
    @mui/styled-engine-sc:  5.12.0 
    @mui/system: 5.13.5 => 5.13.5 
    @mui/x-data-grid-premium: 6.8.0 => 6.8.0 
    @mui/x-date-pickers: 6.8.0 => 6.8.0 
    @types/react: 18.2.13 => 18.2.13 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    styled-components: 5.3.11 => 5.3.11 
    typescript: 5.1.3 => 5.1.3 
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by romgrk**
Closes #9402

The selector tries to index a rowTree that refers to new values with an old value.

### CODE REVIEW

File: packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationSelector.ts [hunk 1]
```diff
@@ -103,14 +103,18 @@ export const gridPaginationRowRangeSelector = createSelectorMemoized(
...
-      if (depth === 0) {
-        topLevelRowAdded += 1;
+      } else {
+        if (topLevelRowAdded < topLevelRowsInCurrentPageCount || depth > 0) {
+          lastRowIndex += 1;
+        }
+
+        if (depth === 0) {
+          topLevelRowAdded += 1;
+        }
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/features/pagination/gridPaginationSelector.ts:117]: imho a `continue` would be more clear than nested `if/else` clauses but our linter rules don't allow `continue`.

File: packages/grid/x-data-grid-pro/src/tests/treeData.DataGridPro.test.tsx [hunk 2]
```diff
@@ -702,4 +702,17 @@ describe('<DataGridPro /> - Tree Data', () => {
       ]);
     });
   });
+
+  describe('regressions', () => {
+    it('should not fail with checkboxSelection', () => {
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/tests/treeData.DataGridPro.test.tsx:707]:
```suggestion
    // See https://github.com/mui/mui-x/issues/9402
    it('should not fail with checkboxSelection', () => {
```

For additional context

**Review by cherniavskii — APPROVED** [review]
