### PR TITLE
[pickers] Use device motion reduction preference

### LINKED ISSUE #9740: [pickers] Integral support for for reduced motion
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://mui.com/x/react-date-pickers/getting-started/

Steps:
1. Make sure reduced motion is enabled on your OS or browser.
2. Open the date picker and move the month around

### Current behavior 😯

I see animation, and become disoriented. People with more severe motion sensitivity may experience headaches and/or nausia.

### Expected behavior 🤔

No animation when `prefers-reduced-motion` is set.

### Context 🔦

I think this is basic accessibility, and our project needs to meet certain accessibility standards.

We could workaround it, but I feel if a library provides animations pretty much hardcoded, it's on them to deal with disabling them when the browser/OS requests to do so.

### Your environment 🌎

Not applicable

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #9740

- Add media query detection for reduced motion when resolving the default `reduceAnimations` prop value
- Fix `DateCalendar` props defaulting order

### CODE REVIEW

File: packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx [hunk 1]
```diff
@@ -44,20 +44,22 @@ function useDateCalendarDefaultizedProps<TDate>(
...
-    views: ['year', 'day'],
-    reduceAnimations: defaultReduceAnimations,
-    renderLoading: () => <span data-mui-test="loading-progress">...</span>,
     ...themeProps,
+    loading: themeProps.loading ?? false,
+    disablePast: themeProps.disablePast ?? false,
+    disableFuture: themeProps.disableFuture ?? false,
+    openTo: themeProps.openTo ?? 'day',
+    views: themeProps.views ?? ['year', 'day'],
+    reduceAnimations: themeProps.reduceAnimations ?? defaultReduceAnimations,
```
Comment (LukasTy) [inline packages/x-date-pickers/src/DateCalendar/DateCalendar.tsx:60]: When implementing this I noticed that the location of `...themeProps` is incorrect.
It's the first item on `DateRangeCalendar` and causes issues, when used with pickers, where a view renderer passes all the props as undefined. 🙈

**Review by flaviendelangle — APPROVED** [review]
Nice improvement!

File: packages/x-date-pickers/src/internals/hooks/useDefaultReduceAnimations.ts [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+
+const PREFERS_REDUCED_MOTION = '@media (prefers-reduced-motion: reduce)';
+
+export const defaultReduceAnimations =
+  typeof navigator !== 'undefined' && /(android)/i.test(navigator.userAgent);
+
+export const useDefaultReduceAnimations = () => {
+  const prefersReduced = useMediaQuery(PREFERS_REDUCED_MOTION, { defaultMatches: false });
+  return prefersReduced || defaultReduceAnimations;
+};
```
Comment (oliviertassinari) [inline packages/x-date-pickers/src/internals/hooks/useDefaultReduceAnimations.ts:11]: There are two different concepts here:

1. `defaultReduceAnimations` is to disable animations that are too slow on low-end devices, it's performance related
2.  `@media (prefers-reduced-motion: reduce)` is user preference related, it's motion sickness related.

I would expect 1. and 2. to not apply at the same time, since not all the animations are too slow for performance, e.g. not enough hardware acceleration, while different animations create motion sickness.

So, this logic looks strange.

Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/useDefaultReduceAnimations.ts:11]: Good observation, but I'm not sure if they are that much different. Any animation has a performance impact, regardless if it's heavy or not. If we are talking about low-end devices, then it could make sense to disable all animations as well. 🤔 
But if we are on this topic, why do we consider all Android devices as low-end and disable animations on them? 🤔

Comment (oliviertassinari) [reply packages/x-date-pickers/src/internals/hooks/useDefaultReduceAnimations.ts:11]: > then it could make sense to disable all animations as well.

Note that "reduced motion" doesn't mean no animations but no movement.

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/useDefaultReduceAnimations.ts:11]: https://a11y-101.com/development/reduced-motion

> On Win10 go to "Settings > Ease of Access > Display > Simplify and personalise Windows". Set "Show animation in Windows" to off.

Looks like this behavior is called "animation" on Windows

Comment (oliviertassinari) [reply packages/x-date-pickers/src/internals/hooks/useDefaultReduceAnimations.ts:11]: Oh yeah, it's inconsistent https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
Screenshot 2023-07-31 at 16 10 54
