### PR TITLE
[DataGrid] Remove `GridCell` `borderBottom` when last row

### LINKED ISSUE #2315: [DataGrid] `autoHeight` + `hideFooter` results in double bottom border
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Enabling both `autoHeight` and `hideFooter` in the data grid renders a double border on the bottom of data grid:
Screenshot 2021-08-10 at 00 28 45

This is very minor, but it looks like the bottom border of the last grid row shouldn't be rendered in this case to avoid this.

## Expected Behavior 🤔

No double border should appear on the bottom of the grid.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-3ndjy?file=/demo.tsx

Steps:

1. Zoom in and look at the bottom of the data grid

## Context 🔦

This is a small, but noticeable layout bug. This is especially noticeable if the border size of the columns doesn't match the root border color of the grid.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 11.5.1
  Binaries:
    Node: 16.6.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.20.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0
    @emotion/styled: ^11.3.0 => 11.3.0
    @material-ui/core: ^5.0.0-beta.2 => 5.0.0-beta.2
    @material-ui/data-grid: ^4.0.0-alpha.35 => 4.0.0-alpha.35
    @material-ui/icons: ^5.0.0-beta.1 => 5.0.0-beta.1
    @material-ui/private-theming:  5.0.0-beta.2
    @material-ui/styled-engine:  5.0.0-beta.1
    @material-ui/styles: ^5.0.0-beta.2 => 5.0.0-beta.2
    @material-ui/system:  5.0.0-beta.2
    @material-ui/types:  6.0.1
    @material-ui/unstyled:  5.0.0-alpha.41
    @material-ui/utils:  5.0.0-beta.1
    @types/react: 17.0.15 => 17.0.15
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    typescript: 4.3.5 => 4.3.5
```
</details>

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #2315 

I've done a potential fix for the issue. The drawback is that now that you have fewer rows than what the grid can load (a black space is visible) and you have a footer enabled then the footer also has a `borderTop`. I think this is how it should have been from the beginning but still, it is technically a breaking change so we need to review it before proceeding.

You can check what the change is here: ...

https://deploy-preview-3519--material-ui-x.netlify.app/components/data-grid/

### CODE REVIEW

**Comment by oliviertassinari** [comment]
It reminds me of #271. IMHO the right solution is a tricker. I see a couple of KO cases in the live preview.

File: packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 1]
```diff
@@ -269,9 +270,11 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
 
     const rows: JSX.Element[] = [];
 
+    const isEmptySpace = nextRenderContext.lastRowIndex >= currentPage.rows.length;
+
     for (let i = 0; i < renderedRows.length; i += 1) {
       const { id, model } = renderedRows[i];
-
+      const isLastRow = i === renderedRows.length - 1;
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx:277]: This will be `true` when on the last row of the **current render context**, which is different from the index relative to all visible rows. Is this what you want? The `index` prop gives the "real" index.

Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx:277]: Hmm, the `index` might also work. The thing is that I need to know if there are fewer rows than the height of the viewport so I can add the border to the last row.

**Comment by DanailH** [comment]
> It reminds me of this attempt that I did in #271 at the problem but on which I failed by lack of time. IMHO the right solution is trickier. I see a couple of KO cases in the live preview.

Yes, I saw the `autoHeight` problem. Besides that  and the fact that now if there are fewer rows than what the viewport can take (you have an empty space between the footer and the last row) then both the last row and the footer have a border.

File: packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx (hunk 1 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx]: I think what you need to do is something that's already being done for the columns. Instead of `columnsMeta.totalWidth`, use `currentPage.rows.length * rowHeight`. To get the height you can try using `apiRef.current.getRootDimensions`.

https://github.com/mui-org/material-ui-x/blob/6208886dbb143f7365f8387ef9d91a6261a3a9d3/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx#L299-L303

Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx]: But the current way also works. I don't need to calculate the height, I can know if there is space just by checking the indexes.

File: packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 2]
```diff
@@ -269,8 +270,12 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
 
     const rows: JSX.Element[] = [];
 
+    const isEmptySpace = nextRenderContext.lastRowIndex >= currentPage.rows.length;
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx:273]: When `nextRenderContext.lastRowIndex` is greater than `currentPage.rows.length`? It's clamped to the number of rows.

https://github.com/mui-org/material-ui-x/blob/9e4c04f1b6d5a2ef8504c81c1cfe295c2f392ee4/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx#L162-L166

https://github.com/mui-org/material-ui-x/blob/9e4c04f1b6d5a2ef8504c81c1cfe295c2f392ee4/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx#L153-L156

File: packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 3]
```diff
@@ -288,6 +293,12 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
           selected={selectionLookup[id] !== undefined}
           index={currentPage.range.firstRowIndex + nextRenderContext.firstRowIndex! + i}
           containerWidth={availableSpace}
+          className={
+            isEmptySpace &&
+            isLastRow &&
+            !rootProps.autoHeight &&
+            gridClasses['row--lastBeforeEmpty']
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx:300]: Could we keep the calculation of the class name inside the `useUtilityClasses` of the `GridRow`? You can pass the input values you need as props. This allows the users to opt-out from this feature by providing a custom row through the slots.

File: packages/grid/_modules_/grid/components/containers/GridRootStyles.ts [hunk 4]
```diff
@@ -212,6 +212,9 @@ export const GridRootStyles = styled('div', {
           },
         },
       },
+      [`&:last-child:not(.${gridClasses['row--lastBeforeEmpty']}) .${gridClasses.cell}`]: {
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/components/containers/GridRootStyles.ts:215]: This selector targets the last visible row that the virtualization decided to render. `:last-child` doesn't mean the last row of the dataset. Also, could we simplify it? Maybe target a row which has a `.MuiDataGrid-row--last` (being the true last row)?

Scrolling https://deploy-preview-3519--material-ui-x.netlify.app/components/data-grid/#commercial-version slowly I can see that sometimes some cells don't have the border bottom.

image

This is much more prominent depending on the value of `rowThreshold`: https://codesandbox.io/s/datagridprodemo-material-demo-forked-jsnbs?file=/demo.js

File: packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx (hunk 2 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx:287]: This is just to catch if the total number of rows is less than the number of rows that can fit in the viewport (user-visible rows). If there is a better way I'm up for it.

Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx]: Updated - I used the `scrollY` in the `GridRow`.

File: packages/grid/_modules_/grid/components/containers/GridRootStyles.ts (hunk 4 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/containers/GridRootStyles.ts]: Updated. I added the `row-last` class.

File: packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 5]
```diff
@@ -282,6 +282,7 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
 
     for (let i = 0; i < renderedRows.length; i += 1) {
       const { id, model } = renderedRows[i];
+      const isLastRow = currentPage.range.firstRowIndex + i === currentPage.rows.length - 1;
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx:285]: I don't think this formula is giving the correct value. In https://deploy-preview-3519--material-ui-x.netlify.app/components/data-grid/rows/#row-height there're 100 rows and the last row has `data-rowindex=102` when it should end at 99.

image

In #3838 I have a situation where I also need to know if one row is the last one. I solved by using `currentPage.range.firstRowIndex + firstRowToRender + i`: https://github.com/mui-org/material-ui-x/pull/3848/files#diff-7fb7dbb1d7fe2c699d9fc5cfc5c6a56b2489af3b46dc1a2a8eaa3404575cacbdR313

The rationale is:

- `firstRowToRender` gives the first row to render in the current render context
- `i` gives which row we're rendering inside the current render context
- `currentPage.range.firstRowIndex` gives the first row to base with when pagination is on, because in the 2nd page `firstRowToRender` is 0.

**Comment by siriwatknp** [comment]
👋 The [migration PR](https://github.com/mui/mui-x/pull/3730) has been merged.

Please follow these steps to make sure that the contents are all updated. (Sorry for the inconvenience)

1. pull latest master from upstream to your branch
2. if your PR has changes on the `*.md` or demo files, you are likely to encounter conflict because all of them have been moved to the new folder.
   2.1 revert the change on those markdown files you did
   2.2 pull latest master from upstream (you should not see conflict)
   2.3 make the changes again at `docs/data/material/*`
3. run `yarn docs:api`
    - you might see the changes in `docs/pages/material/api/*` if your PR touches some of the components
    - it is okay if there is no changes

If you are struggle with the steps above, feel free to tag @siriwatknp

File: packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx (hunk 5 above)
Comment (m4theushw) [reply packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx]: Yes, makes sense. I'm using `firstRowToRender + i` to pass ´isLastVisible` in https://github.com/mui/mui-x/pull/3848/files#diff-d686bc46bbd2d70d8fe115f2d0f87743bf452fddf658b5dbe8c79d3bd0bb52cbR151

File: packages/grid/_modules_/grid/components/containers/GridRootStyles.ts [hunk 6]
```diff
@@ -222,6 +222,10 @@ export const GridRootStyles = styled('div', {
           },
         },
       },
+      [`&.${gridClasses['row--last']}:not(.${gridClasses['row--lastBeforeEmpty']}) .${gridClasses.cell}`]:
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/components/containers/GridRootStyles.ts:225]: I found the purpose of `row--lastBeforeEmpty` hard to understand. How about adding a class to `MuiDataGrid-virtualScrollerContent` to signal that its content doesn't extend to the full height of the grid. You'll need to wait for #3821 to able to do it. In DataGridPro the calculation is already being done, we only need to add the class name. 

https://github.com/mui/mui-x/blob/996f727467311f20e999b8db3d1331e3526594fd/packages/grid/x-data-grid-pro/src/DataGridProVirtualScroller.tsx#L249-L250

Once you have the class name added you can create a selector like `.MuiDataGrid-root:not(.MuiDataGrid-autoHeight) .MuiDataGrid-virtualScroller:not(.MuiDataGrid-virtualScrollerContent--newClassAdded) .MuiDataGrid-row--last`.

File: packages/grid/_modules_/grid/gridClasses.ts [hunk 7]
```diff
@@ -407,6 +407,8 @@ export const gridClasses = generateUtilityClasses('MuiDataGrid', [
   'row--editable',
   'row--editing',
   'row',
+  'row--lastBeforeEmpty',
+  'row--last',
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/gridClasses.ts:411]: You also need to add these classes to the interface in this same file.

File: packages/grid/_modules_/grid/components/containers/GridRootStyles.ts (hunk 6 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/containers/GridRootStyles.ts:225]: That will work as well. I can put the on hold for now for the PR until the other one is merged.

File: packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 8]
```diff
@@ -312,6 +313,7 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
           selected={isSelected}
           index={currentPage.range.firstRowIndex + nextRenderContext.firstRowIndex! + i}
           containerWidth={availableSpace}
+          isCurrentPageLastRow={currentPageLastRow}
```
[the remark this answers is not in the document]
Comment (DanailH) [reply packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx]: Yes, sorry I missed that - updated.

File: packages/grid/_modules_/grid/components/containers/GridRootStyles.ts (hunk 6 above)
Comment (DanailH) [reply packages/grid/_modules_/grid/components/containers/GridRootStyles.ts]: Updated

File: packages/grid/x-data-grid/src/internals/components/virtualization/GridVirtualScrollerContent.tsx [hunk 9]
```diff
@@ -30,13 +30,18 @@ const GridVirtualScrollerContent = React.forwardRef<
   HTMLDivElement,
   React.HTMLAttributes<HTMLDivElement>
 >(function GridVirtualScrollerContent(props, ref) {
-  const { className, ...other } = props;
+  const { className, style, ...other } = props;
   const rootProps = useGridRootProps();
-  const ownerState = { classes: rootProps.classes };
+  const ownerState = { classes: rootProps.classes, overflowedContent: style?.minHeight === 'auto' };
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/internals/components/virtualization/GridVirtualScrollerContent.tsx:35]: I noticed that `minHeight` is not reliable when `autoHeight` is on. Removing a row and re-adding it in https://deploy-preview-3519--material-ui-x.netlify.app/components/data-grid/layout/#auto-height, adds the overflow class. I propose to use:

```suggestion
  const ownerState = { classes: rootProps.classes, overflowedContent: !rootProps.autoHeight && style?.minHeight === 'auto' };
```

The content never overflows when `autoHeight` is on.

image

File: packages/grid/x-data-grid/src/internals/components/containers/GridRootStyles.ts [hunk 10]
```diff
@@ -73,6 +73,10 @@ export const GridRootStyles = styled('div', {
     [`&.${gridClasses.autoHeight}`]: {
       height: 'auto',
     },
+    [`& .${gridClasses['virtualScrollerContent--overflowed']} .${gridClasses['row--lastVisible']} .${gridClasses.cell}`]:
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/internals/components/containers/GridRootStyles.ts:76]: The content is not supposed to overflow when `autoHeight` is on. We need to also remove the border in this condition. In https://deploy-preview-3519--material-ui-x.netlify.app/components/data-grid/layout/#auto-height sometimes I still see the double border.

image

Comment (DanailH) [reply packages/grid/x-data-grid/src/internals/components/containers/GridRootStyles.ts]: Ah yes thanks for the catch!

**Review by m4theushw — APPROVED** [review]
Good job!
