### PR TITLE
[charts] Improve the management of the text (legend only)

### LINKED ISSUE #9743: [charts] Wrap `Legend` labels to avoid overlapping when displaying multiple categories
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/legend-labels-4kh7r8

Steps:
1. Check live demo to see labels overlapping

### Current behavior 😯

The Legend components try to display all categories in the same row with equally-divided widths.
image

### Expected behavior 🤔

Ideally, the `Legend` component could deal with this issue by:
- Automatically breaking lines on the text categories to match legend width.
- (and/or) Setting custom Item width for single legends, and automatically breaking to the next row if the legends don't fit the current one.
- (or) Dynamically auto-size legends based on the label width and consider row width to use multiple rows.

Other open-source libraries don't provide this feature out-of-the-box, so you have to build your own CustomLegend component, but some commercial libraries do.

### Benchmark
[Highcharts](https://jsfiddle.net/t7ep0weq/1/) have a property called `itemWidth` and it's used as a kind of `flexBasis`

```
legend: {
    enabled: true,
    itemWidth: 200, //Essentially sets two columns for legends in this case
    width:400,
    align: 'center'
  },
```

Recharts does it automatically, and have a property on Legend called wrapperStyle where you can define further styling.

```
<Legend verticalAlign="bottom" wrapperStyle={{ lineHeight: "40px" }} />
```

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #9743

The target is to get access to the text size (height and width) to be able to place them nicely.

For now, the new `<Text />` component allows to get its size and to support multiline texts.

It's used for
- axes ticks and labels, but it does not allow customization and does not use the size computation for now
- legend to allow it to wrap. Here it uses size computation and allows style customization

### Style

The placement of the legend has changed unintentionally. It now sticks to the border of the SVG instead of the border of the drawing area. Not a big deal, but I don't see one being better than the other

I changed a bit the default styling of legend text. I'm open to suggestions on this topic.

### DevExp

For me the legend is much better now, but it opens the question about how to pass style the its labels. I went with `labelStyle` props. So you can do the following.

```jsx
slotProps={{
  legend: {
    labelStyle: { fill: 'red',  fontSize: 50 }
  }
}}
```

image

But it could be done with other options to be able to manage states. But it feels overengineered. I don't know if you have ideas

```jsx
slotProps={{
  legend: {
    styles: { 
      label: {fill: 'red',  fontSize: 50},
      outlinedLabel: {fill: 'red',  fontSize: 50},
      hiddenLabel: {fill: 'red',  fontSize: 50},
      mark: { ... },
    }
  }
}}
```

## Todo

- [x] In the legend let texts pick the width they need without having to provide a fixed width
- [ ] ~In the axis adapt the number of ticks to label size~
- [x] Support characters `\n`
- [x] Fix docs spacing
- [x] Make sure no more CSS is applied to text in the docs

## Todo next PRs

- [ ] Allow to override legend marks
- [ ] Allow to customize texts for axes
- [ ] Avoid axes ticks overflow

## Trade-offs

There are a lot of styled components in axes, and most of their style will be useless with this `<Text/>` component. I removed all of them and only kept the root one. The default styling is done by CSS classes

Preview is available in the demo of [Legend docs page](https://deploy-preview-10138--material-ui-x.netlify.app/x/react-charts/legend/)

#### Breaking changes

The charts have a new text display mechanism. 
It adds line break support and avoids overlapping text in the legend.
This comes with some breaking changes.

- The DOM structure is modified. An intermediary `<tspan />` element has been added. This can impact how your style is applied.
  ```diff
  - <text>The label</text>
  + <text><tspan>The label</tspan></text>
  ```

- The top margin has been reduced from 100 to 50 to benefit form the denser legend.

- To accurately compute the text size and then place it, styling should be provided as a JS object. For example, to set the legend font size, you should do:
  ```jsx
  <PieChart
    {/** ... */}
    slotProps={{
      legend: {
        labelStyle: {
          fontSize: 16,
        },
      },
    }}
  />
  ```
  Support for other text elements (axis labels and tick labels) will be implemented in follow-up PR.

### CODE REVIEW

File: packages/x-charts/src/internals/components/AxisSharedComponents.tsx [hunk 1]
```diff
@@ -5,64 +5,23 @@ export const AxisRoot = styled('g', {
   name: 'MuiChartsAxis',
   slot: 'Root',
   overridesResolver: (props, styles) => styles.root,
-})({
```
Comment (alexfauquette) [inline packages/x-charts/src/internals/components/AxisSharedComponents.tsx:8]: All the text alignments are moved from this CSS to the `<Text/>` props

File: packages/x-charts/src/internals/components/Text.tsx [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+      break;
+    case 'central':
+      startDy = ((wordsByLines.length - 1) / 2) * -wordsByLines[0].height;
+      break;
+    default:
+      startDy = (wordsByLines.length - 1) * -wordsByLines[0].height;
+      break;
+  }
+
+  // const transforms = [];
```
Comment (alexfauquette) [inline packages/x-charts/src/internals/components/Text.tsx:67]: It is not implemented yet. It will mostly be helpful for axes tiks

**Review by LukasTy — COMMENTED** [review]
It's a really nice improvement!
The updated legend behavior is much more DX friendly. 💯 
I leave the space for @noraleonte to comment on the reduced font size of the legend labels.
IMHO, they seem a bit too small - even pixelated on a lower PPI (probably majority of desktop users) screen. 🙈

**Comment by LukasTy** [comment]
This looks like a demo "regression" that we might need to mend. 🙈 
Screenshot 2023-10-05 at 17 55 51

File: docs/data/charts/legend/legend.md [hunk 3]
```diff
@@ -12,28 +12,35 @@ In chart components, the legend links series with `label` properties and their c
...
+To break line in legend labels, use the special character `\n`.
 
-- `--ChartsLegend-itemWidth`: The width of one series (including the mark and the label).
-- `--ChartsLegend-itemMarkSize`: The size of the mark square.
-- `--ChartsLegend-labelSpacing`: The space between the mark and the label.
-- `--ChartsLegend-rootSpacing`: The space between two series.
+To customize its style, you should not use CSS. Instead pass a styling object to the `labelStyle` property.
 
-{{"demo": "DimensionsNoSnap.js", "hideToolbar": true, "bg": "inline"}}
+The `labelStyle` property is needed to measure text size, and then place legend items at the correct position.
```
[the remark this answers is not in the document]
Comment (alexfauquette) [reply docs/data/charts/legend/legend.md:46]: I was hesitating to put it into an `info` section. It's not mandatory information, but it's good to know why this object is here and what you might break if you don't use it

File: packages/x-charts/src/ChartsLegend/utils.ts [hunk 4]
```diff
@@ -12,9 +12,6 @@ export type AnchorPosition = { horizontal: AnchorX; vertical: AnchorY };
 
 export type SizingParams = {
```
[the remark this answers is not in the document]
Comment (alexfauquette) [reply packages/x-charts/src/ChartsLegend/utils.ts:13]: I will fix that :+1:

**Comment by LukasTy** [comment]
> You mean adding more space between the axis label and ticks label?

Yup, I've observed this change in the Argos diff.

File: docs/data/charts/legend/legend.md [hunk 5]
```diff
@@ -12,28 +12,35 @@ In chart components, the legend links series with `label` properties and their c
...
+
+### Dimensions
+
+Inside the legend, the mark can be customized with `itemMarkWidth` and `itemMarkHeight` which are the width/height in pixels.
+
+You also have access to the `markGap` which is the gap between the mark and its label given in pixels.
+And `itemGap` which is the gap between two legend items.
 
-## Dimensions
+### Label styling
```
Comment (joserodolfofreitas) [inline docs/data/charts/legend/legend.md:40]: Would it make sense to have this on the [styling page](https://deploy-preview-10138--material-ui-x.netlify.app/x/react-charts/styling/) since it doesn't apply only to legends?

**Review by joserodolfofreitas — COMMENTED** [review]
Very welcome improvements! Thanks for tackling this!

I experimented with a few scenarios, and it works well by default on horizontal bars. But with legends, it feels we need to have style control over the legend itself and maybe in relation to the legend.
For example, is there a way to position the text vertically centralized in relation to the legend's symbol?

I tried playing with the `dominant-baseline` based on the current style in place, but it doesn't centralize well when the label is not consistently in multiline.
image

https://codesandbox.io/s/cool-joliot-2zjhs3?file=/Demo.tsx

File: docs/data/charts/legend/legend.md (hunk 5 above)
Comment (alexfauquette) [reply docs/data/charts/legend/legend.md:40]: What about keeping a "Label styling" section on all pages that use text. 

For example in axis page it will have similar content explaining how to customize axis labels and ticks label. Saying what's the name of the styling property and how to access it.

In the styling page, we could have an explanation about which properties are supported. For example, the text baseline, the alignement, or the rotation might be slightly different than standard CSS.

**Comment by alexfauquette** [comment]
> I tried playing with the `dominant-baseline` based on the current style in place, but it doesn't centralize well when the label is not consistently in multiline.

The text alignment and transformation should be reimplemented (It's the drawback of the solution) It applies the `dominant-baseline` to all the line independently. To get it work we should pass it as a props if the `<Text/>` component

File: docs/data/charts/legend/legend.md [hunk 6]
```diff
@@ -12,28 +12,35 @@ In chart components, the legend links series with `label` properties and their c
...
-It can also be moved by a combination of `position: { vertical, horizontal }` properties and the legend offset values.
-The `position` places the legend just next to the drawing area, and offset values move it relative to this base position.
+It can also be moved with the `position: { vertical, horizontal }` property which defines how the legend aligns within the SVG.
 
 - `vertical` can be `'top'`, `'middle'`, or `'bottom'`.
 - `horizontal` can be `'left'`, `'middle'`, or `'right'`.
-- offsets are set with CSS variables `--ChartsLegend-rootOffsetX` and `--ChartsLegend-rootOffsetY`.
+
+You can add some space to a given `position` with a `padding` property which can be either a number or an object `{ top, bottom, left, right }`.
+This `padding` will add space between the SVG borders and the legend.
```
Comment (noraleonte) [inline docs/data/charts/legend/legend.md:27]: I am not entirely sure about the phrasing of 'a given position'. It makes sense to me, but I'm not sure it is intelligible at a first glance. I don't have a better suggestion for this though 🙈 🤔 
```suggestion
You can add spacing to a given `position` with the `padding` property, which can be either a number or an object `{ top, bottom, left, right }`.
This `padding` will add space between the SVG borders and the legend.
```

File: docs/data/charts/legend/legend.md [hunk 7]
```diff
@@ -12,28 +12,35 @@ In chart components, the legend links series with `label` properties and their c
...
 
 Defaults are such that the legend is placed on top of the charts.
 
-{{"demo": "LegendCustomizationNoSnap.js", "hideToolbar": true, "bg": "inline"}}
+{{"demo": "LegendPositionNoSnap.js", "hideToolbar": true, "bg": "inline"}}
+
+### Dimensions
+
+Inside the legend, the mark can be customized with `itemMarkWidth` and `itemMarkHeight` which are the width/height in pixels.
```
Comment (noraleonte) [inline docs/data/charts/legend/legend.md:35]:
```suggestion
Inside the legend, you can customize the pixel value of the width and height of the mark with the `itemMarkWidth` and `itemMarkHeight` props.
```

File: docs/data/charts/legend/legend.md [hunk 8]
```diff
@@ -12,28 +12,35 @@ In chart components, the legend links series with `label` properties and their c
...
+
+You also have access to the `markGap` which is the gap between the mark and its label given in pixels.
+And `itemGap` which is the gap between two legend items.
```
Comment (noraleonte) [inline docs/data/charts/legend/legend.md:38]:
```suggestion
You can also access the `markGap` prop to change the gap between the mark and its label, or the  `itemGap` to change the gap between two legend items. Both props impact the values defined in pixels.
```

File: docs/data/charts/legend/legend.md [hunk 9]
```diff
@@ -12,28 +12,35 @@ In chart components, the legend links series with `label` properties and their c
...
+It can also be moved with the `position: { vertical, horizontal }` property which defines how the legend aligns within the SVG.
 
 - `vertical` can be `'top'`, `'middle'`, or `'bottom'`.
 - `horizontal` can be `'left'`, `'middle'`, or `'right'`.
-- offsets are set with CSS variables `--ChartsLegend-rootOffsetX` and `--ChartsLegend-rootOffsetY`.
+
+You can add some space to a given `position` with a `padding` property which can be either a number or an object `{ top, bottom, left, right }`.
+This `padding` will add space between the SVG borders and the legend.
 
 Defaults are such that the legend is placed on top of the charts.
```
Comment (noraleonte) [inline docs/data/charts/legend/legend.md:29]:
```suggestion
By default, the legend is placed above the charts.
```

**Review by noraleonte — COMMENTED** [review]
Great improvement! 🎉 Much better DX, 💙 the docs improvements
I left a few suggestions for the phrasing in the docs 🙈 
About the reduced label font size, I agree that they are a bit too small. I would personally go with a middle ground of `14px`. WDYT?

File: docs/data/charts/legend/legend.md [hunk 10]
```diff
@@ -12,28 +12,35 @@ In chart components, the legend links series with `label` properties and their c
...
 
-{{"demo": "LegendCustomizationNoSnap.js", "hideToolbar": true, "bg": "inline"}}
+{{"demo": "LegendPositionNoSnap.js", "hideToolbar": true, "bg": "inline"}}
+
+### Dimensions
+
+Inside the legend, the mark can be customized with `itemMarkWidth` and `itemMarkHeight` which are the width/height in pixels.
+
+You also have access to the `markGap` which is the gap between the mark and its label given in pixels.
+And `itemGap` which is the gap between two legend items.
```
[the remark this answers is not in the document]
Comment (alexfauquette) [reply docs/data/charts/legend/legend.md]: Adding the demo allowed me to spot on mark/label placement. Rows were overlapping when `itemGap` was small.

Now it's fixed `itemGap=0` means every think touch its neighbors
[legendbug.mp4.webm](https://github.com/mui/mui-x/assets/45398769/2f399d38-d987-442c-b898-abfee0c5f135)

File: packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx [hunk 11]
```diff
@@ -76,10 +72,37 @@ function ChartsYAxis(inProps: ChartsYAxisProps) {
...
+    elementType: Label,
+    externalSlotProps: slotProps?.axisTickLabel,
+    additionalProps: {
+      textAnchor: 'middle',
+      dominantBaseline: 'central',
+      style: {
+        fontSize: labelFontSize,
+        transform: `rotate(${positionSigne * 90}deg)`,
+        transformOrigin: `${labelRefPoint.x}px ${labelRefPoint.y}px`,
+      },
```
[the remark this answers is not in the document]
Comment (alexfauquette) [reply packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx:102]: Yes, I was in the middle of a thinking about
- drop `className` since the style should be passe to the `<ChartsText/>` props
- keep it for colors, and other stuff that do not impact size

File: packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx [hunk 12]
```diff
@@ -76,10 +72,38 @@ function ChartsYAxis(inProps: ChartsYAxisProps) {
...
+
+  const axisLabelProps = useSlotProps({
+    elementType: Label,
+    externalSlotProps: slotProps?.axisLabel,
+    additionalProps: {
+      textAnchor: 'middle',
+      dominantBaseline: 'auto',
+      style: {
+        fontSize: labelFontSize,
+        transform: `rotate(${positionSigne * 90}deg)`,
```
Comment (LukasTy) [inline packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx:100]: Is `Signe` a typo? 🤔

**Review by LukasTy — COMMENTED** [review]
Looks great! 💯 
Leaving some comments. 😉 
The label vertical alignment is the culprit for not approving the PR yet as it seems like it would be a regression as compared to the current version. 🙈

File: packages/x-charts/src/internals/components/ChartsText.tsx [hunk 13]
```diff
@@ -0,0 +1,102 @@
...
+    GetWordsByLinesParams {
+  /**
+   * Height of a text line (in `em`).
+   */
+  lineHeight?: number;
+  /**
+   * The text baseline
+   * @default 'central'
+   */
+  dominantBaseline?: ChartsTextBaseline;
```
[the remark this answers is not in the document]
Comment (alexfauquette) [reply packages/x-charts/src/internals/components/ChartsText.tsx:33]: I don't understand. Previously the text was with `central`. Does `middle` have a specific advantage?

image

I took a screenshot of the preview and production, and I struggle to find the breaking change

image

[the remark this answers is not in the document]
Comment (LukasTy) [reply packages/x-charts/src/internals/components/ChartsText.tsx:33]: Fair point. 🙈 
My bad, it's more of a general issue that we can leave for a separate PR if need be. 👌 

If I understand it correctly, the problem seems to stem from the fact that the legend label appears misaligned vertically, event though it is aligned, but based on the tallest letter.
WDYT about changing all the demo legend labels to start with a capital letter in order to avoid this strange visual anomaly? 🙈 🤷 🤔 
Screenshot 2023-10-10 at 20 04 43

**Review by LukasTy — APPROVED** [review]
Looks great! 💯 
Approving based on: https://github.com/mui/mui-x/pull/10138#discussion_r1352898200
The few left nitpicks are just that - minor improvements.

File: packages/x-charts/src/internals/components/ChartsText.tsx (hunk 13 above)
[the remark this answers is not in the document]
Comment (alexfauquette) [reply packages/x-charts/src/internals/components/ChartsText.tsx:33]: Ok, now I remember why we moved from `middle` to `central`. It was for the tick alignment. Digits looked better aligned with `central`

Good idea to add first captial letter

File: packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx (hunk 12 above)
Comment (alexfauquette) [reply packages/x-charts/src/ChartsYAxis/ChartsYAxis.tsx:100]: It's an english/french mix :)
