### PR TITLE
[DataGrid] Fix group header resize

### LINKED ISSUE #12290: [data grid] Flex columns causes column grouping headers to become un-aligned from their columns for some column resizes
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-cecf1r?file=Demo.tsx
Steps:
1. Create a DataGrid with the following column definitions:
   ```
   { field: 'field1', flex: 1 },
   { field: 'field2', flex: 1 },
   { field: 'field3', flex: 0 },
   ```
2. Create a grouping model as follows:
   ```
   [
          {
            groupId: 'Group1',
            children: [{ field: 'field1' }, { field: 'field2' }],
          },
          {
            groupId: 'Group2',
            children: [{ field: 'field3' }],
          },
   ]
   ```
3. Enable column grouping and provide the grouping model from above.
4. Take the right edge of the `field2` column and shrink it.

### Current behavior

Following the steps above will leave you with group headers that are mis-aligned. The header for the `Group1` group does not grow in size to reflect the growth of the `field1` column to fill the space left when `field2` was shrunk. Instead the header for `Group1` is the width of the `field1` and `field2` columns when the `field2` column was shrunk.

This leaves the header for `Group2` too far left and misaligned with the header for `field3`.

image

### Expected behavior

I would expect the header for `Group1` to resize to match the size of the `field1` and `field2` columns after the flex has resized them, so that all group headers remain aligned with their columns.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
MUI Data Grid Version: 6.19.5
MUI Material Version: 5.15.11
React Version: 18.2
Chrome Version 120.0.6099.225

</details>

**Search keywords**: column grouping, resize, alignment, flex, data grid

### PR DESCRIPTION
**Pull request by arminmeh**
Fix #12290 

Recalculate group header widths after column widths were adjusted based on the flex values

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Before: https://stackblitz.com/edit/react-cecf1r-nfqkhk
After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-td62tk

### CODE REVIEW

File: packages/x-data-grid/src/utils/domUtils.ts [hunk 1]
```diff
@@ -71,6 +71,11 @@ export function findHeaderElementFromField(elem: Element, field: string): HTMLDi
   return elem.querySelector(`[data-field="${field}"]`)!;
 }
 
+export function getFieldsFromGroupHeaderElem(colCellEl: Element): string[] {
+  const found = colCellEl.getAttribute('data-fields')!.match(/^\|-(.+)-\|$/);
+  return found ? found[1].split('-|-') : [];
```
Comment (cherniavskii) [inline packages/x-data-grid/src/utils/domUtils.ts:76]: I'd rather avoid regexp for better readability:
```suggestion
  const fieldsString = colCellEl.getAttribute('data-fields');
  return fieldsString?.startsWith('|-') ? fieldsString!.slice(2, -2).split('-|-') : [];
```

**Review by cherniavskii — APPROVED** [review]
Thank you!

File: packages/x-data-grid/src/utils/domUtils.ts (hunk 1 above)
Comment (arminmeh) [reply packages/x-data-grid/src/utils/domUtils.ts]: Agree. Thanks 🙂
