### PR TITLE
[DataGrid] Fix inconsistent overlay when changing the `loading` prop

### LINKED ISSUE #4309: [data grid] `DataGrid` briefly flashes "No rows" after loading
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Datagrid briefly flashes the "No Rows" overlay when you transition from `loading=true rows=[]` to `loading=false rows=[loaded rows]`

Depending on the code and other things, if multiple (unnecessary) rerenders happen this flash may not be visible.

### Expected behavior 🤔

It should not flash "No rows"

### Steps to reproduce 🕹

Codesandbox: https://codesandbox.io/s/datagriddemo-material-demo-forked-dmwwi3?file=/demo.tsx

Code (mirrored)
```
import * as React from 'react';
import { DataGrid, GridColDef, GridValueGetterParams } from '@mui/x-data-grid';
import { useEffect, useState } from 'react';

const columns: GridColDef[] = [
  { field: 'id', headerName: 'ID', width: 90 },
  {
    field: 'firstName',
    headerName: 'First name',
    width: 150,
    editable: true,
  },
  {
    field: 'lastName',
    headerName: 'Last name',
    width: 150,
    editable: true,
  },
  {
    field: 'age',
    headerName: 'Age',
    type: 'number',
    width: 110,
    editable: true,
  },
  {
    field: 'fullName',
    headerName: 'Full name',
    description: 'This column has a value getter and is not sortable.',
    sortable: false,
    width: 160,
    valueGetter: (params: GridValueGetterParams) =>
      `${params.row.firstName || ''} ${params.row.lastName || ''}`,
  },
];

const baseRows = [
  { id: 1, lastName: 'Snow', firstName: 'Jon', age: 35 },
  { id: 2, lastName: 'Lannister', firstName: 'Cersei', age: 42 },
  { id: 3, lastName: 'Lannister', firstName: 'Jaime', age: 45 },
  { id: 4, lastName: 'Stark', firstName: 'Arya', age: 16 },
  { id: 5, lastName: 'Targaryen', firstName: 'Daenerys', age: null },
  { id: 6, lastName: 'Melisandre', firstName: null, age: 150 },
  { id: 7, lastName: 'Clifford', firstName: 'Ferrara', age: 44 },
  { id: 8, lastName: 'Frances', firstName: 'Rossini', age: 36 },
  { id: 9, lastName: 'Roxie', firstName: 'Harvey', age: 65 },
];

export default function DataGridDemo() {
  const [data, setData] = useState({
    loading: true,
    rows: []
  })

  useEffect(() => {
    setTimeout(() => {
      setData({
        loading: false,
        rows: baseRows,
      })
    }, 1000)
  }, []);

  return (
    <div style={{ height: 400, width: '100%' }}>
      <DataGrid
        rows={data.rows}
        columns={columns}
        loading={data.loading}
        pageSize={5}
        rowsPerPageOptions={[5]}
        checkboxSelection
        disableSelectionOnClick
      />
    </div>
  );
}
```

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
See codesandbox
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #4309 

Solution: move the `loading` prop to the state so we kill the inconsistency when the `rows` state has not been updated yet.

Before: https://codesandbox.io/s/datagridprodemo-material-demo-forked-1xejrr?file=/demo.tsx
After: https://codesandbox.io/s/datagridprodemo-material-demo-forked-ed2heq?file=/demo.tsx

When running the examples locally with React 18 the bug is very preeminent, that's why I gave priority to it.

### CODE REVIEW

File: packages/grid/x-data-grid/src/hooks/features/rows/gridRowsSelector.ts [hunk 1]
```diff
@@ -8,6 +8,8 @@ export const gridRowCountSelector = createSelector(
   (rows) => rows.totalRowCount,
 );
 
+export const gridLoadingSelector = createSelector(gridRowsStateSelector, (rows) => rows.loading);
```
Comment (flaviendelangle) [inline packages/grid/x-data-grid/src/hooks/features/rows/gridRowsSelector.ts:11]: If it is in the row state, should it be `gridRowsLoadingSelector` ?

**Review by cherniavskii — APPROVED** [review]

File: packages/grid/x-data-grid/src/hooks/features/rows/gridRowsSelector.ts (hunk 1 above)
Comment (m4theushw) [reply packages/grid/x-data-grid/src/hooks/features/rows/gridRowsSelector.ts]: Renamed.

**Comment by yanfaingoldCell** [comment]
still blinking :'(
