### PR TITLE
[charts-premium] Add series `valueFormatter` to candlestick chart

### LINKED ISSUE #21804: [charts-premium] Add a value formater to the candelstick charts
### Summary

Add the `valueFormatter` to the candlestick series. It should

- have similar API as other charts
- document it's usage
- add test to prevent regression

### Examples

_No response_

### Motivation

_No response_

**Search keywords**: candelstick, formatter

### PR DESCRIPTION
**Pull request by JCQuintas**
## Summary

- Adds per-field `valueFormatter` support to the candlestick (OHLC) series, following the Heatmap pattern of overriding the base `CommonSeriesType` formatter
- The formatter receives individual number values with a `{ dataIndex, field }` context where `field` is `'open' | 'high' | 'low' | 'close'`
- Tooltip `value` and `formattedValue` are now structured objects (`{ open, high, low, close }`) instead of raw tuples/strings
- Updates `OHLCTooltipContent`, `descriptionGetter`, locale text types, and `useAxesTooltip` to support the new format
- Adds documentation with a demo showing per-field formatting

Fixes #21804

### CODE REVIEW

File: packages/x-charts/src/ChartsTooltip/useAxesTooltip.tsx [hunk 1]
```diff
@@ -60,8 +60,12 @@ export interface UseAxesTooltipParams {
 export interface SeriesItem<T extends CartesianChartSeriesType | PolarChartSeriesType> {
   seriesId: SeriesId;
   color: string;
-  value: ChartsSeriesConfig[T]['valueType'];
-  formattedValue: string;
+  value: T extends 'ohlc'
+    ? { open: number; high: number; low: number; close: number } | null
+    : ChartsSeriesConfig[T]['valueType'];
```
Comment (alexfauquette) [inline packages/x-charts/src/ChartsTooltip/useAxesTooltip.tsx:65]: To be sure this is not a breaking change, you could modify the default agrs of  `UseAxesTooltipReturnValue` as follow to avoid type breaking chanage

```diff
- CartesianChartSeriesType
+ Exclude<CartesianChartSeriesType, 'ohlc'>
```

File: docs/data/charts/candlestick/CandlestickValueFormatter.tsx.preview [hunk 2]
```diff
@@ -0,0 +1,16 @@
+<CandlestickChart
+  {...chartSettings}
+  series={[
+    {
+      data,
+      valueFormatter: (value, { field }) => {
+        if (value === null) { return ''; }
+        if (field === 'open') { return `⇒ ${dollarFormatter.format(value)}`; }
+        if (field === 'close') { return `⇍ ${dollarFormatter.format(value)}`; }
```
Comment (alexfauquette) [inline docs/data/charts/candlestick/CandlestickValueFormatter.tsx.preview]: I don't know if it was intended to have a slash on the arrow or not
```suggestion
        if (field === 'close') { return `⇐ ${dollarFormatter.format(value)}`; }
```
