### PR TITLE
[DataGridPro] Fix header filters rendering issue for `isEmpty` and `isNotEmpty` filter operators

### LINKED ISSUE #14490: [data grid] Header Filters empty / no UI once isEmpty or isNotEmpty is selected
### Steps to reproduce

[Link to live example (Documentation site)](https://mui.com/x/react-data-grid/filtering/header-filters/)

Steps:
1. Find the first DataGrid on the example page, in which you can change the header filter to `Is Empty`
2. For any column, select either `Is Empty` or `Is Not Empty`

### Current behavior

The header filter is blank. There is no UI element.

### Expected behavior

A UI element is rendered to allow the user to switch to another filter or no filter at all.

### Context

We disabled the main filter panel as our users in particular found it a bit complicated and solely using header filters worked better with our UX. This means that when they select `Is Empty` or `Is Not Empty`, they now cannot remove or change that filter unless they refresh the page.

### Your environment

Using Firefox 130.0

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 14.6.1
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 128.0.6613.114
    Edge: Not Found
    Safari: 17.6
  npmPackages:
    @emotion/react: ^11.10.0 => 11.13.0 
    @emotion/styled: ^11.10.0 => 11.13.0 
    @mui/base: ^5.0.0-beta.23 => 5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.16.6 
    @mui/icons-material: ^5.8.4 => 5.16.6 
    @mui/lab: ^5.0.0-alpha.114 => 5.0.0-alpha.173 
    @mui/material: ^5.9.2 => 5.16.6 
    @mui/private-theming:  5.16.6 
    @mui/styled-engine:  5.16.6 
    @mui/system:  5.16.6 
    @mui/types:  7.2.15 
    @mui/utils:  5.16.6 
    @mui/x-data-grid:  7.12.0 
    @mui/x-data-grid-pro: ^7.1.1 => 7.12.0 
    @mui/x-date-pickers:  7.12.0 
    @mui/x-date-pickers-pro: ^7.1.1 => 7.12.0 
    @mui/x-internals:  7.12.0 
    @mui/x-license:  7.12.0 
    @types/react: ^18.2.45 => 18.3.3 
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1 
    styled-components:  6.1.12 
    typescript: ^5.3.3 => 5.5.4 
```
</details>

**Search keywords**: header filter isEmpty
**Order ID**: 75000

### PR DESCRIPTION
**Pull request by k-rajat19**
Fixes #14490 
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

File: packages/x-data-grid/src/colDef/gridDateOperators.ts
Comment (MBilalShafi) [inline packages/x-data-grid/src/colDef/gridDateOperators.ts:1]: Instead of having to update the behavior in the filter panel:

**Before**
image

**After**
image

I'd rather keep the disabled input components in the header filter cell.

How about something like:
```diff
diff --git a/packages/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterCell.tsx b/packages/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterCell.tsx
index 1d22e8793..80ff6dfa2 100644
--- a/packages/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterCell.tsx
+++ b/packages/x-data-grid-pro/src/components/headerFiltering/GridHeaderFilterCell.tsx
@@ -18,6 +18,11 @@ import {
   gridFilterModelSelector,
   gridFilterableColumnLookupSelector,
   GridPinnedColumnPosition,
+  GridFilterInputValue,
+  GridFilterInputDate,
+  GridFilterInputBoolean,
+  GridColType,
+  GridFilterInputSingleSelect,
 } from '@mui/x-data-grid';
 import {
   GridStateColDef,
@@ -32,7 +37,6 @@ import { useGridRootProps } from '../../hooks/utils/useGridRootProps';
 import { DataGridProProcessedProps } from '../../models/dataGridProProps';
 import { GridHeaderFilterMenuContainer } from './GridHeaderFilterMenuContainer';
 import { GridHeaderFilterClearButton } from './GridHeaderFilterClearButton';
-
 export interface GridRenderHeaderFilterProps extends GridHeaderFilterCellProps {
   inputRef: React.RefObject<unknown>;
 }
@@ -87,6 +91,19 @@ const dateSx = {
   [`& input[value=""]:not(:focus)`]: { color: 'transparent' },
 };
 
+const defaultInputComponents: {
+  [key in GridColType]: React.JSXElementConstructor<any> | null;
+} = {
+  string: GridFilterInputValue,
+  number: GridFilterInputValue,
+  date: GridFilterInputDate,
+  dateTime: GridFilterInputDate,
+  boolean: GridFilterInputBoolean,
+  singleSelect: GridFilterInputSingleSelect,
+  actions: null,
+  custom: null,
+};
+
 const GridHeaderFilterCell = React.forwardRef<HTMLDivElement, GridHeaderFilterCellProps>(
   (props, ref) => {
     const {
@@ -147,7 +164,9 @@ const GridHeaderFilterCell = React.forwardRef<HTMLDivElement, GridHeaderFilterCe
     );
 
     const InputComponent =
-      colDef.filterable || isFilterReadOnly ? currentOperator!.InputComponent : null;
+      colDef.filterable || isFilterReadOnly
+        ? (currentOperator.InputComponent ?? defaultInputComponents[colDef.type as GridColType])
+        : null;
 
     const applyFilterChanges = React.useCallback(
       (updatedItem: GridFilterItem) => {
```

**Review by MBilalShafi — COMMENTED** [review]
Thank you for picking this up. 🙏

File: packages/x-data-grid/src/colDef/gridDateOperators.ts
Comment (k-rajat19) [reply packages/x-data-grid/src/colDef/gridDateOperators.ts:1]: Shukriya for the review
this solution is much better than that I have proposed earlier 
I missed checking that it is already working in v6 
thanks again :)

**Comment by MBilalShafi** [comment]
Hey @k-rajat19 
Thank you again for this pull request!

Your changes seem to impact the commercially licensed code. For any changes of this nature, we require contributors to sign the MUI’s Contributor License Agreement (CLA). However, I can’t find a CLA signed that could cover these changes. Please follow the steps at https://mui-org.notion.site/CLA-Contributor-License-Agreement-92ece655b1584b10b00e4de9e67eedb0 to sign the document.

**Comment by k-rajat19** [comment]
I've sent the email to team-legal@mui.com

**Comment by zannager** [comment]
@MBilalShafi, CLA signed, thanks.

**Review by MBilalShafi — APPROVED** [review]
LGTM
