### PR TITLE
[DataGridPro] Rework `onRowsScrollEnd` to use `IntersectionObserver`

### LINKED ISSUE #4371: [data grid] `onRowsScrollEnd` fired without scrolling
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

- initial 3 rows are rendered
- `onRowsScrollEnd` is called (even though there was no scroll event)
- newly-added 3 rows are rendered as well
- scroll doesn't trigger `onRowsScrollEnd` anymore

https://user-images.githubusercontent.com/13808724/161784597-0479a931-b345-4e7f-bf3a-87e47491b35b.mov

### Expected behavior 🤔

- initial 3 rows are rendered
- `onRowsScrollEnd` is not called, since there's no scroll event

### Steps to reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/infiniteloadinggrid-material-demo-forked-4uve2q?file=/demo.tsx

### Context 🔦

I've noticed it while investigating #4184

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #4371
Fixes https://github.com/mui/mui-x/issues/9022

Preview: https://deploy-preview-8672--material-ui-x.netlify.app/x/react-data-grid/row-updates/#infinite-loading

TODO:
- [x] How should it behave with sorting applied?
      Server-side sorting should be used.
- [x] How should it behave with a filter applied? https://github.com/mui/mui-x/issues/11402

### CODE REVIEW

File: packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts [hunk 1]
```diff
@@ -22,62 +20,48 @@ export const useGridInfiniteLoader = (
...
+    const rowScrollEndParam: GridRowScrollEndParams = {
+      visibleColumns,
+      viewportPageSize,
+      visibleRowsCount: currentPage.rows.length,
+    };
 
-  const handleRowsScrollEnd = React.useCallback(
-    (scrollPosition: GridScrollParams) => {
-      const dimensions = apiRef.current.getRootDimensions();
+    apiRef.current.publishEvent('rowsScrollEnd', rowScrollEndParam);
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:43]: I played with it a bit and it seems to me that it's being fired to often: https://codesandbox.io/s/infiniteloadinggrid-material-demo-forked-xfdu80?file=/demo.tsx

https://user-images.githubusercontent.com/13808724/236502751-5fcaf797-a698-482d-a76c-f1b484b2596f.mov

1. `onRowsScrollEnd` is called on mount, even though there's no need to fetch additional rows yet
2. `onRowsScrollEnd` is called multiple times on scroll

Is this expected behavior?

Comment (DanailH) [reply packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:43]: Ah yes, it seems that there is an initial call that is not needed.
Regarding being called multiple times per scroll - probably debouncing will help here.

I didn't notice it being called when scrolling up?

File: packages/grid/x-data-grid/src/components/GridRow.tsx [hunk 2]
```diff
@@ -498,23 +498,49 @@ const GridRow = React.forwardRef<HTMLDivElement, GridRowProps>(function GridRow(
...
-      {cells}
-      {emptyCellWidth > 0 && <EmptyCell width={emptyCellWidth} />}
-    </div>
-  );
+  const renderCell = () => {
+    if (isLastVisible && (rootProps as any).onRowsScrollEnd) {
+      return (
+        <div ref={(apiRef as any).current.unstable_lastVisibleRowRef}>
+          <div
+            ref={handleRef}
```
[the remark this answers is not in the document]
Comment (DanailH) [reply packages/grid/x-data-grid/src/components/GridRow.tsx]: Should be ok now

File: packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts (hunk 1 above)
Comment (DanailH) [reply packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts]: > It's also being called when scrolling up.

Added a check to call the callback only when scrolling down.

Tweaked the solution a but to eliminate unnecessary calls.

File: packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx [hunk 3]
```diff
@@ -888,8 +888,8 @@ DataGridPremiumRaw.propTypes = {
    */
   scrollbarSize: PropTypes.number,
   /**
-   * Set the area in `px` at the bottom of the grid viewport where onRowsScrollEnd is called.
-   * @default 80
+   * Set the percentage of the element that needs to be visible in order to invoke the rowsScrollEnd callback. A threshold of 1.0 means that when 100% of the target needs to be visible.
```
Comment (DanailH) [inline packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx:891]: This is a potential breaking change.

File: packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts [hunk 4]
```diff
@@ -27,57 +25,63 @@ export const useGridInfiniteLoader = (
...
   const visibleColumns = useGridSelector(apiRef, gridVisibleColumnDefinitionsSelector);
   const currentPage = useGridVisibleRows(apiRef, props);
-  const rowsMeta = useGridSelector(apiRef, gridRowsMetaSelector);
-  const contentHeight = Math.max(rowsMeta.currentPageTotalHeight, 1);
+  const observer = React.useRef<IntersectionObserver>();
+  let previousY = 0;
+  let previousRatio = 0;
 
-  const isInScrollBottomArea = React.useRef<boolean>(false);
+  const handleLoadMoreRows = React.useCallback(
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:32]: In some cases the callback is fired twice, see this demo: https://codesandbox.io/s/sweet-wing-y3h4zt?file=/demo.tsx

Expected behavior: on scroll, additional 3 rows are fetched which results in total of 9 rows
Current behavior: on scroll, 2x 3 rows are fetched which results in total of 12 rows

https://github.com/mui/mui-x/assets/13808724/4d91bab0-a3c9-4932-906a-9086ec14df16

File: packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts [hunk 5]
```diff
@@ -27,57 +25,63 @@ export const useGridInfiniteLoader = (
...
+            visibleRowsCount: currentPage.rows.length,
+          };
+          apiRef.current.publishEvent('rowsScrollEnd', rowScrollEndParam);
+        }
+      }
+
+      // eslint-disable-next-line react-hooks/exhaustive-deps
+      previousY = currentY;
+      // eslint-disable-next-line react-hooks/exhaustive-deps
+      previousRatio = currentRatio;
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:54]: These values should be stored in refs instead

File: packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx (hunk 3 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx]: Yes, it is also less flexible compared to the pixel value, because it doesn't allow to start fetching the next rows earlier - e.g. when 3rd row from the bottom is visible.
How do you feel about attaching a DOM node to the bottom of the content and using it for intersection? That should allow avoiding breaking changes

File: packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts [hunk 6]
```diff
@@ -27,57 +25,63 @@ export const useGridInfiniteLoader = (
...
   const currentPage = useGridVisibleRows(apiRef, props);
-  const rowsMeta = useGridSelector(apiRef, gridRowsMetaSelector);
-  const contentHeight = Math.max(rowsMeta.currentPageTotalHeight, 1);
+  const observer = React.useRef<IntersectionObserver>();
+  let previousY = 0;
+  let previousRatio = 0;
 
-  const isInScrollBottomArea = React.useRef<boolean>(false);
+  const handleLoadMoreRows = React.useCallback(
+    ([entry]: any) => {
```
Comment (romgrk) [inline packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:33]: `[entry]: IntersectionObserverEntry[]`

File: packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx (hunk 3 above)
Comment (DanailH) [reply packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx]: I've updated it - deprecated the existing prop and added a new one. Upon further research, I couldn't replicate the behavior using the new `InterectionObserver` API.

File: packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts (hunk 4 above)
Comment (DanailH) [reply packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:36]: I tried to debug it but as far as I can see this happens either because of the accelerated scroll on IOS or another option is because you are trying to load fewer rows that the screen can fit, essentially hitting the intersection again. The callback passes the `viewportPageSize` to indicate how many rows the user can load.

Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:36]: I think I can reproduce the double fetching with our demo in https://deploy-preview-8672--material-ui-x.netlify.app/x/react-data-grid/row-updates/#infinite-loading
You can see this if you add logging: https://codesandbox.io/s/compassionate-panka-flyq4j?file=/demo.tsx

https://github.com/mui/mui-x/assets/13808724/2f5fb8a8-ec05-4801-995b-d03c82b51057

You don't see a visual reproduction of the issue, because the demo has a hidden bug where the second response overrides data fetched in the first one:
https://github.com/mui/mui-x/blob/be7174996bc1157dd1d39343c819b6a9af7581bb/docs/data/data-grid/row-updates/InfiniteLoadingGrid.tsx#L38

I think this demo is generally buggy and needs a rewrite (I'll try to create a better one).
But the double fetching issue is consistent and needs a solution.

Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:36]: @DanailH

File: packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx (hunk 3 above)
Comment (DanailH) [reply packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx]: We can postpone it to v7. The problem is that the threshold has a different value that is not measured in pixels.

File: packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts [hunk 7]
```diff
@@ -22,62 +20,72 @@ export const useGridInfiniteLoader = (
...
-          viewportPageSize,
-          visibleRowsCount: currentPage.rows.length,
-        };
-        apiRef.current.publishEvent('rowsScrollEnd', rowScrollEndParam);
-        isInScrollBottomArea.current = true;
+      observer.current = new IntersectionObserver(handleLoadMoreRows, {
+        threshold: props.lastVisibleRowThreshold,
+      });
+
+      if (node && node !== previousNode.current) {
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:77]: It looks like the original issue is now reproducible again https://github.com/mui/mui-x/issues/4371
See this demo: https://codesandbox.io/s/infiniteloadinggrid-material-demo-forked-3nf8wf

Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:77]: Would be great to have a unit test for this issue specifically

File: packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx (hunk 3 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx]: I was thinking about this briefly, would it make sense to add an element that would always stick to the bottom of the grid and observe it with an intersection observer instead of observing the last row?
It will be possible to change this element's height and keep the same `scrollEndThreshold` API.
What do you think?

Comment (DanailH) [reply packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx]: One of the first implementations used this approach but then the feedback was to observe the last loaded row instead 😅.
This would make sense tho if we want to be backward compatible but will have to change once we do v7. At this point, we might want to park the PR for when we start the alfa and just introduce the new approach

File: packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts (hunk 7 above)
Comment (DanailH) [reply packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:77]: Actually, it should work like this. If you have fewer rows than what the viewport can hold the callback is invoked. If this doesn't happen, the callback will never be called because there is no ability to scroll.

Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:77]: > Actually, it should work like this. If you have fewer rows than what the viewport can hold the callback is invoked.

Yes, the issue is that you're stuck with 6 rows unable to load more rows

Comment (DanailH) [reply packages/grid/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:77]: yup this calls for a test indeed.

File: packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx (hunk 3 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid-premium/src/DataGridPremium/DataGridPremium.tsx]: Yeah, backward compatibility is one of the aspects of this change. We can put it on hold until v7.

Another aspect is flexibility - in some cases, you might want to trigger row fetching way before the last row is visible. This is possible with the current `scrollEndThreshold` API, but with the new API the earliest you can fetch the next rows is when the last row enters the grid viewport.

**Comment by cherniavskii** [comment]
This is ready for review.

File: packages/x-data-grid-pro/src/hooks/features/infiniteLoader/gridInfniteLoaderInterface.ts [hunk 8]
```diff
@@ -0,0 +1,7 @@
+export interface GridInfiniteLoaderApi {
+  /**
+   * Stores the ref of the element at the bottom of the virtual scroller content that triggers the infinite loading.
+   * @ignore - do not document.
+   */
+  unstable_infiniteLoadingTriggerRef: (node: HTMLElement | null) => void;
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/hooks/features/infiniteLoader/gridInfniteLoaderInterface.ts:6]: Keep in private API?

File: packages/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts [hunk 9]
```diff
@@ -1,17 +1,17 @@
...
-  GridScrollParams,
-  useGridApiEventHandler,
   useGridApiOptionHandler,
   gridVisibleColumnDefinitionsSelector,
-  gridRowsMetaSelector,
+  useGridApiMethod,
+  gridDimensionsSelector,
 } from '@mui/x-data-grid';
 import { useGridVisibleRows } from '@mui/x-data-grid/internals';
+import { unstable_useEventCallback } from '@mui/utils';
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:10]: We usually import it as `useEventCallback`.

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 10]
```diff
@@ -41,6 +42,13 @@ export const EMPTY_DETAIL_PANELS = Object.freeze(new Map<GridRowId, React.ReactN
 
 export type VirtualScroller = ReturnType<typeof useGridVirtualScroller>;
 
+const InfiniteLoadingTriggerElement = styled('div')({
+  position: 'sticky',
+  left: 0,
+  width: 0,
+  height: 0,
+});
+
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:51]: I don't love how the infinite loading logic is spilling in this file. Is there any other way we can separate the logic?

Instead of exposing `unstable_infiniteLoadingTriggerRef` on the API, maybe we could expose (a) function(s) to add the trigger element?

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 11]
```diff
@@ -376,8 +387,17 @@ export const useGridVirtualScroller = () => {
...
+      if (isInfiniteLoadingEnabled && isLastVisible) {
+        rows.push(
+          <InfiniteLoadingTriggerElement
+            ref={(apiRef as any).current.unstable_infiniteLoadingTriggerRef}
+            // Force rerender on last row change to start observing the new trigger
+            key={`trigger-${id}`}
+            role="presentation"
+          />,
+        );
+      }
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:399]: I think I meant the `isLastVisible` flag to mean the last logical row in the page, not the last displayed row on screen. Maybe we could move this outside of the loop and just add the element at the end of `rows` when needed?

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx (hunk 10 above)
Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:51]: The function could take as input the props, so the `props.rowsLoadingMode === 'client'` (below) would not need the `(rootProps as any)` cast that's required here.

File: packages/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts (hunk 9 above)
Comment (romgrk) [reply packages/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.ts:10]: I think this should be the way to use it:

```js
import useEventCallback from '@mui/utils/useEventCallback
```

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx (hunk 11 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:399]: > I think I meant the isLastVisible flag to mean the last logical row in the page, not the last displayed row on screen.

Correct, and for infinite loading, I need to put the trigger element after the last logical row in the page, not the last row rendered due to virtualization.

File: packages/x-data-grid-pro/src/hooks/features/infiniteLoader/gridInfniteLoaderInterface.ts (hunk 8 above)
Comment (cherniavskii) [reply packages/x-data-grid-pro/src/hooks/features/infiniteLoader/gridInfniteLoaderInterface.ts]: I've replaced it with a `getInfiniteLoadingTriggerElement` method in the private API and moved the interface to the MIT package for the sake of type safety (`getInfiniteLoadingTriggerElement` is being called in the MIT package's `useGridVirtualScroller`)

File: packages/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.tsx [hunk 12]
```diff
@@ -0,0 +1,144 @@
...
+  React.useEffect(() => {
+    if (!isEnabled) {
+      return;
+    }
+    if (!virtualScroller) {
+      return;
+    }
+    if (triggerElement.current) {
+      observer.current?.unobserve(triggerElement.current);
+    }
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.tsx:77]: Not sure if it applies but there is also `observer.current?.disconnect()`, which can help avoid storing the observed element ref sometimes.

**Review by romgrk — APPROVED** [review]

File: packages/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.tsx (hunk 12 above)
Comment (cherniavskii) [reply packages/x-data-grid-pro/src/hooks/features/infiniteLoader/useGridInfiniteLoader.tsx]: Good point! I used `disconnect` instead of unobserve.

I still need to keep track of the trigger element to observe it after recreating `IntersectionObserver` (e.g. when `marginBottom` changes): https://github.com/mui/mui-x/pull/8672/files#diff-626d69f7d7c9aebfab3fdc6388cd0f88a38b6d9e51c567e76f63a25d63895b10R81-R83

File: docs/data/data-grid/row-updates/row-updates.md [hunk 13]
```diff
@@ -40,6 +40,11 @@ In addition, the area in which `onRowsScrollEnd` is called can be changed using
 
 {{"demo": "InfiniteLoadingGrid.js", "bg": "inline", "disableAd": true}}
 
+:::info
+Note that for infinite loading to work properly, sorting and filtering should be done on the server side.
+Otherwise, the sorting and filtering will be applied to loaded rows only.
```
Comment (MBilalShafi) [inline docs/data/data-grid/row-updates/row-updates.md:45]:
```suggestion
For sorting and filtering to work properly with the infinite loading, they should be applied on the server side.
Otherwise, the sorting and filtering will be applied to the partially loaded rows only.
```

**Review by MBilalShafi — APPROVED** [review]
