### PR TITLE
[data grid] Fix focused column header scroll jump

### LINKED ISSUE #19320: [data grid] Scroll jumps if column header is focused and columns flicker when scrolling
### Steps to reproduce

Steps 1/2:
1. Open this link to live example: https://mui.com/x/react-data-grid/#pro-version
2. Focus e.g. Sub Total column header
3. Scroll left until sub total is out of the viewport, scroll slowly back, all columns flicker

Steps 2/2:
1. Open this link to live example: https://mui.com/x/react-data-grid/#premium-version
2. Focus the Sub Total column header
3. Scroll fully to the left
4. Witness the scroll jump back

### Current behavior

_No response_

### Expected behavior

_No response_

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: flicker scroll jump

### PR DESCRIPTION
**Pull request by lauri865**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #19320.

Albeit the focused element jumping in and out of render context part probably is not ideal (also doesn't support keyboard), it fixes the biggest issue for now.

### CODE REVIEW

File: packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx [hunk 1]
```diff
@@ -269,10 +269,7 @@ function GridColumnHeaderItem(props: GridColumnHeaderItemProps) {
     if (hasFocus && !columnMenuState.open) {
       const focusableElement = headerCellRef.current!.querySelector<HTMLElement>('[tabindex="0"]');
       const elementToFocus = focusableElement || headerCellRef.current;
-      elementToFocus?.focus();
-      if (apiRef.current.columnHeadersContainerRef?.current) {
-        apiRef.current.columnHeadersContainerRef.current.scrollLeft = 0;
-      }
```
Comment (romgrk) [inline packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx]: For the context, this was added here: https://github.com/mui/mui-x/pull/4280

File: packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx [hunk 2]
```diff
@@ -84,19 +82,6 @@ const GridGenericColumnHeaderItem = forwardRef<HTMLDivElement, GridGenericColumn
...
-        const focusableElement =
-          headerCellRef.current!.querySelector<HTMLElement>('[tabindex="0"]');
-        const elementToFocus = focusableElement || headerCellRef.current;
-        elementToFocus?.focus();
-        if (apiRef.current.columnHeadersContainerRef?.current) {
-          apiRef.current.columnHeadersContainerRef.current.scrollLeft = 0;
-        }
-      }
-    }, [apiRef, hasFocus]);
-
```
Comment (romgrk) [inline packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx:99]: This isn't used/useful?

Comment (lauri865) [reply packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx:99]: Seemed like a duplicated logic that was already present in the parent components.

File: packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx (hunk 1 above)
Comment (lauri865) [reply packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx]: Whatever it fixed should be irrelevant since `position: sticky`? `columnHeadersContainer` is not scrollable anyways (anymore).

**Comment by lauri865** [comment]
Need to add a fallback for  Chrome on Android it seems, similar to GridCell:

https://caniuse.com/mdn-api_htmlelement_focus_options_preventscroll_parameter

**Comment by lauri865** [comment]
Should be ready to merge now.

File: packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx (hunk 2 above)
Comment (romgrk) [reply packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx:99]: Indeed, I've tested and the functionality seems to work even without this.

File: packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx (hunk 1 above)
Comment (romgrk) [reply packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderItem.tsx]: Yes, it should be irrelevant.

**Review by romgrk — APPROVED** [review]
