### PR TITLE
[docs] Fix Data Grid advanced list view demo

### LINKED ISSUE #17056: [docs] Data Grid advanced list view demo is broken
### Related page

https://next.mui.com/x/react-data-grid/list-view/#advanced-usage

### Kind of issue

Broken demo

### Issue description

Try clicking any of the buttons in the toolbar and see the whole page be overtaken by icons.

https://github.com/user-attachments/assets/3eb9a113-15a7-4633-9e22-92dd1197e4fc

### Context

_No response_

**Search keywords**: n/a

### PR DESCRIPTION
**Pull request by KenanYusuf**
Use the `window` prop that gets passed to iframe demos instead of a ref on the container element.

Fixes #17056 

**Before**

https://next.mui.com/x/react-data-grid/list-view/#advanced-usage

https://github.com/user-attachments/assets/3eb9a113-15a7-4633-9e22-92dd1197e4fc

**After**

https://deploy-preview-17064--material-ui-x.netlify.app/x/react-data-grid/list-view/#advanced-usage

https://github.com/user-attachments/assets/69951e66-84bf-4ff3-bdea-a8a7dec3887d

### CODE REVIEW

File: docs/data/data-grid/list-view/ListViewAdvanced.js [hunk 1]
```diff
@@ -25,15 +25,14 @@ import { formatDate, formatSize, stringAvatar } from './utils';
 import { ActionDrawer } from './components/ActionDrawer';
 import { RenameDialog } from './components/RenameDialog';
 
-export default function ListViewAdvanced(props) {
+export default function ListViewAdvanced({ window }) {
   // This is used only for the example - renders the drawer inside the container
-  const containerRef = React.useRef(null);
-  const container = () => containerRef.current;
```
Comment (KenanYusuf) [inline docs/data/data-grid/list-view/ListViewAdvanced.js:31]: This was returning `null` when the drawer opened, meaning it did not have a container to render to.

**Review by arminmeh — APPROVED** [review]
