### PR TITLE
[DataGrid] Fix first row flickering with autoHeight enabled

### LINKED ISSUE #13270: [data grid] adding a new row with the autoHeight prop causes first row flicker
### The problem in depth

I have a DataGrid component that lets you add a new row and auto-adds a new row after being saved. 
The issue is a re-render on the first row is triggered when adding a row and it causes a flicker. Ths only occurs when the `autoHeight` prop is added. 

See this [demo](https://codesandbox.io/p/sandbox/tender-meninsky-k8gv87?file=%2Fsrc%2FDemo.js). Simply add a row and notice the flicker on the first row. 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  Binaries:
    Node: 18.19.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 124.0.6367.60
  npmPackages:
    @emotion/react: ^11.10.6 => 11.10.6 
    @emotion/styled: ^11.10.6 => 11.10.6 
    @mui/base: ^5.0.0-beta.34 => 5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.18 
    @mui/icons-material: ^5.11.11 => 5.11.11 
    @mui/joy: ^5.0.0-beta.11 => 5.0.0-beta.11 
    @mui/lab: ^5.0.0-alpha.126 => 5.0.0-alpha.126 
    @mui/material: ^5.11.12 => 5.15.18 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-charts: ^6.0.0-alpha.15 => 6.0.0-alpha.15 
    @mui/x-data-grid:  6.6.0 
    @mui/x-data-grid-generator: ^6.6.0 => 6.6.0 
    @mui/x-data-grid-premium:  6.6.0 
    @mui/x-data-grid-pro: ^7.4.0 => 7.4.0 
    @mui/x-date-pickers:  6.16.2 
    @mui/x-date-pickers-pro: ^6.16.2 => 6.16.2 
    @mui/x-license:  7.2.0 
    @mui/x-license-pro: ^6.6.0 => 6.6.0 
    @types/react:  18.0.28 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript:  4.9.5 
```
</details>

**Search keywords**: autoHeight, DataGrid, flicker
**Order ID**: 67382

### PR DESCRIPTION
**Pull request by KenanYusuf**
Fixes the first row flickering when a new, editable row is added to a grid with autoHeight enabled.

Fixes #13270
- Before: https://codesandbox.io/p/sandbox/tender-meninsky-k8gv87
- After: https://codesandbox.io/p/sandbox/misty-bird-kxzdrz

### 1. User adds a new row

Screenshot 2024-08-16 at 14 06 21

### 2. The new row gets rendered in the correct position, but the original row is hidden

This happens because the newly added editable cell calls `.focus()` when it mounts. The virtual scroller has a `scroll` event listener that listens to scroll events in order to recalculate which rows are in view to render. The browser tries to scroll the editable cell into view, and triggers the scroll event callback.

The scroll event handler receives an `event.scrollTop` position of `52px`, and decides that the first row does not need rendering because based on this value, it is out of view. This is what leads to the temporary state of a hidden first row.

**Why is this only a problem with autoHeight enabled?**

When `autoHeight` is not enabled, the scroll event listener only fires when the virtual scroller content actually becomes scrollable. This means the editable cell moves into focus and there is no visible flicker.

With `autoHeight` enabled, the virtual scroller content temporarily overflows when a new row is added whilst it recalculates the virtual scroller content height.

Screenshot 2024-08-16 at 14 06 30

### 3. The virtual scroller recalculates and re-renders both rows in the correct position

Screenshot 2024-08-16 at 14 06 38

## The solution

Disable row virtualization when `autoHeight` is enabled. Row virtualization has no performance gains when `autoHeight` is enabled as the list of rows never becomes scrollable. This in turn fixes the issue of the virtual scroller miscalculating which elements are in view.

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx [hunk 1]
```diff
@@ -22,7 +22,7 @@ export const EMPTY_RENDER_CONTEXT = {
 
 export const virtualizationStateInitializer: GridStateInitializer<RootProps> = (state, props) => {
   const virtualization = {
-    enabled: !props.disableVirtualization,
+    enabled: !props.disableVirtualization && !props.autoHeight,
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx:25]: This disables row & column virtualization, is this the desired behavior?

Comment (KenanYusuf) [reply packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx:25]: No it's not, I misunderstood because there is a separate `enabledForColumns` property. Will fix.

Comment (KenanYusuf) [reply packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx:25]: I'm confused by the default state of `enabledForColumns` here. Why is it `true` regardless of the value of `props.disableVirtualization` if that prop disables virtualization for columns and rows?

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 2]
```diff
@@ -551,15 +551,21 @@ export const useGridVirtualScroller = () => {
...
   useEnhancedEffect(() => {
-    if (enabled) {
-      // TODO a scroll reset should not be necessary
+    // TODO a scroll reset should not be necessary
+    if (enabledForColumns) {
       scrollerRef.current!.scrollLeft = 0;
+    }
+  }, [enabledForColumns, gridRootRef, scrollerRef]);
+
+  useEnhancedEffect(() => {
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:560]: Could we combine these two effects into one?

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx [hunk 3]
```diff
@@ -61,9 +67,20 @@ export function useGridVirtualization(
     }));
   };
 
+  const setRowVirtualization = (enabled: boolean) => {
+    apiRef.current.setState((state) => ({
+      ...state,
+      virtualization: {
+        ...state.virtualization,
+        enabledForRows: enabled,
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx:75]: To be aligned with the constraint applied in initializer and other setter?
```suggestion
        enabledForRows: enabled && !props.autoHeight,
```

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx [hunk 4]
```diff
@@ -61,9 +67,20 @@ export function useGridVirtualization(
...
+      },
+    }));
+  };
+
   const api = {
     unstable_setVirtualization: setVirtualization,
     unstable_setColumnVirtualization: setColumnVirtualization,
+    unstable_setRowVirtualization: setRowVirtualization,
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx:83]: Do we have a use case for it in the userland? If not, could we keep it private for now?

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx (hunk 2 above)
Comment (KenanYusuf) [reply packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx]: Fixed https://github.com/mui/mui-x/pull/14235/commits/9b14b515320e7ca75a14afaefb9479f2cd02b77c

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx (hunk 4 above)
Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx:83]: I wouldn't add it then, and I would keep the selector private. I'm already unhappy about having needed to add `unstable_setColumnVirtualization`, felt hacky.

Comment (KenanYusuf) [reply packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx]: Makes sense - removed it https://github.com/mui/mui-x/pull/14235/commits/9b61d4258bb44bba09624323e83f480bad4ee9f2

File: packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx [hunk 5]
```diff
@@ -168,7 +168,7 @@ export const useGridColumnHeaders = (props: UseGridColumnHeadersProps) => {
       maxLastColumn = visibleColumns.length,
     } = params || {};
 
-    const firstColumnToRender = !hasVirtualization ? 0 : currentContext.firstColumnIndex;
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx:171]: There was a bug here. `hasVirtualization` is using `gridVirtualizationColumnEnabledSelector` to get the column virtualization state. This was previously always `true`, even when the `disableVirtualization` prop was passed to DataGrid. The `0` here meant that pinned columns headers were duplicated were not being removed from the middle section of columns.

**Review by MBilalShafi — APPROVED** [review]

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx [hunk 6]
```diff
@@ -47,6 +51,8 @@ export function useGridVirtualization(
       virtualization: {
         ...state.virtualization,
         enabled,
+        enabledForColumns: enabled,
+        enabledForRows: enabled && !props.autoHeight,
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx:55]: Could we move the `!autoheight` somewhere it doesn't need to be repeated?

[the remark this answers is not in the document]
Comment (KenanYusuf) [reply packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx:55]: Any suggestions where/how @romgrk?

[the remark this answers is not in the document]
Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualization.tsx:55]: No, feel free to ignore if there's no other good place.

**Comment by Luis-Ramirez21x** [comment]
Thank you guys for bashing this bug !

Our users will be happy to have this fixed :pray: !!
