### PR TITLE
[pickers] Clean component interfaces and remove non-implemented props

### LINKED ISSUE #4557: [DateRangePicker] ToolbarComponent prop documented but not implemented
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

`DateRangePicker` does not render a custom `ToolbarComponent` when it's supplied via `props`.

## Expected Behavior 🤔

Expect `DateRangePicker` to support this as `DatePicker` does.

## Steps to Reproduce 🕹

Code Sandbox Demo
https://codesandbox.io/s/blissful-cdn-zus0r?file=/src/Demo.tsx

Steps:

1. Supply a custom `ToolbarComponent` to a `DateRangePicker`.
2. Observe that this is not rendered, and the component shows the default toolbar.

## Context 🔦

Attempting to customise the appearance of the toolbar for a `DateRangePicker` on a mobile device.

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```
System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) m5-6Y54 CPU @ 1.10GHz
    Memory: 20.18 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.5 - /Users/finn/.rvm/rubies/ruby-2.4.1/bin/pod
    Homebrew: 3.2.6 - /usr/local/bin/brew
    Maven: 3.3.9 - /usr/local/bin/mvn
    pip3: 21.1.3 - /usr/local/bin/pip3
    RubyGems: 3.1.4 - /Users/finn/.rvm/rubies/ruby-2.4.1/bin/gem
  Utilities:
    CMake: 3.15.5 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.30.1 - /usr/bin/git
    Clang: 12.0.5 - /usr/bin/clang
  Servers:
    Apache: 2.4.46 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.2 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 25
      Build Tools: 25.0.3
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Atom: 1.54.0
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_131 - /usr/bin/javac
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.24 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.6 - /usr/local/bin/python3
    Ruby: 2.4.1 - /Users/finn/.rvm/rubies/ruby-2.4.1/bin/ruby
  Databases:
    PostgreSQL: 13.2 - /usr/local/bin/postgres
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 93.0.4577.63
    Safari: 14.1.2
```
</details>

### PR DESCRIPTION
**Pull request by flaviendelangle**
Closes #4557

## In this PR

- [x] Remove `onClose` / `onOpen` and `close` props from the static pickers
- [x] Use the interfaces from `usePickerState` whenever possible rather than redefining its props
- [x] Remove `ToolbarComponent` prop from `BaseDateRangePickerProps` (not implemented, see #4557)
- [x] Remove `toolbarPlaceholder` prop from `BaseDateRangePickerProps` and `BaseTimePickerProps` (not implemented)
- [x] Remove `toolbarFormat` prop from `BaseTimePickerProps` (not implemented)

## What's next ?

- Move all the toolbar props in `componentsProps.toolbar` to avoid all this prop drilling
- Try to simplify the component interface cascade (that one will be hard)

### CODE REVIEW

File: packages/x-date-pickers/src/internals/models/props/baseToolbarProps.ts [hunk 1]
```diff
@@ -3,22 +3,21 @@ import { CalendarOrClockPickerView } from '../views';
 import type { PickerOnChangeFn } from '../../hooks/useViews';
 import type { ExportedCalendarPickerProps } from '../../../CalendarPicker/CalendarPicker';
 import type { ExportedClockPickerProps } from '../../../ClockPicker/ClockPicker';
+import { PickerStatePickerProps } from '../../hooks/usePickerState';
 
-export interface BaseToolbarProps<TDate>
+export interface BaseToolbarProps<TDate, TValue>
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/models/props/baseToolbarProps.ts:8]: I added a generic so that the `date` prop of BaseToolbarProps` can be correctly typed with `TValue` (the prop will be renamed `parsedValue` in #4736)

File: docs/pages/x/api/date-pickers/date-range-picker.json [hunk 2]
```diff
@@ -2,6 +2,7 @@
   "props": {
     "onChange": { "type": { "name": "func" }, "required": true },
     "renderInput": { "type": { "name": "func" }, "required": true },
+    "value": { "type": { "name": "arrayOf", "description": "Array&lt;any&gt;" }, "required": true },
```
Comment (flaviendelangle) [inline docs/pages/x/api/date-pickers/date-range-picker.json:5]: I don't understand why `value` was not in the proptypes

**Review by cherniavskii — COMMENTED** [review]
Great job reducing type confusions!

File: packages/x-date-pickers-pro/src/DateRangePicker/DateRangePicker.tsx [hunk 3]
```diff
@@ -157,7 +157,6 @@ DateRangePicker.propTypes = {
   disableAutoMonthSwitching: PropTypes.bool,
   /**
    * If `true`, the picker and text field are disabled.
-   * @default false
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-date-pickers-pro/src/DateRangePicker/DateRangePicker.tsx]: I added it back on `disabled` and `readOnly`

**Review by cherniavskii — APPROVED** [review]
