### PR TITLE
[DataGrid] Improve grouping performance for large datasets

### LINKED ISSUE #9197: Performance issues when grouping rows in large datasets
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
https://codesandbox.io/s/nifty-jennings-20q62b?file=/src/App.js:1223-1234

Example built on top of:
https://mui.com/x/react-data-grid/performance/

Steps:
1. Load 100.000 rows of demo data 'Commodities'
2. Click on the column menu "Commodity" and select "Group by Commodity"
3. Click on the column menu "Trader name" and select "Group by Trader name"

### Current behavior 😯

When working with large datasets (>100.000 rows) the row grouping becomes very slow, especially when applying multiple grouping criterias.

In the example provided the second grouping takes above 5 seconds(3. step).

### Expected behavior 🤔

I expect the grouping to be as instant and performant as the filtering and sorting.

### Context 🔦

I am testing various datagrids for use in data heavy applications, where there can be more than 500.000 transaction datasets. To allow the user to narrow down specific rows, the grouping feature would be of great help. But the performance is a must at the same time.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Version 113.0.5672.127 (Official Build) (64-bit)
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.57)
  npmPackages:
    @emotion/react: ^11.10.6 => 11.11.0
    @emotion/styled: ^11.10.6 => 11.11.0
    @mui/base:  5.0.0-beta.0
    @mui/core-downloads-tracker:  5.13.0
    @mui/icons-material: ^5.11.11 => 5.11.16
    @mui/material: ^5.11.13 => 5.13.0
    @mui/private-theming:  5.12.3
    @mui/styled-engine:  5.12.3
    @mui/styles: ^5.11.16 => 5.12.3
    @mui/system: ^5.4.1 => 5.12.3
    @mui/types:  7.2.4
    @mui/utils:  5.12.3
    @mui/x-data-grid:  6.3.1
    @mui/x-data-grid-generator: ^6.0.1 => 6.3.1
    @mui/x-data-grid-premium: ^6.3.1 => 6.3.1
    @mui/x-data-grid-pro:  6.3.1
    @mui/x-date-pickers: ^6.0.2 => 6.3.1
    @mui/x-license-pro:  6.0.4
    @types/react:  18.2.6
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^4.9.5 => 4.9.5
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by romgrk**
Closes #9197 

We should be using a double-linked list for this use-case, we care only about insertion time here. The memory pressure of constantly re-allocating the `sortedRows` array is turning this into an `O(n^something)` runtime. There probably is a more elegant way to solve this as I haven't used dlinked list in a while but this will do for now.

_edit: or maybe just a single-linked list is enough? I'll update tomorrow_

Before: https://codesandbox.io/s/cranky-pike-i1xy45
Screenshot from 2023-06-02 11-51-33

After: https://codesandbox.io/s/nervous-grothendieck-n1bwgf
image

### CODE REVIEW

**Comment by romgrk** [comment]
Is it normal that it only says 944 total rows (with a 100,000 rows dataset) when grouping is on? I've never worked with the grouping code yet, not sure if my PR is wrong or this is how it displays.

image

File: packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts [hunk 1]
```diff
@@ -68,24 +151,22 @@ export const sortRowTree = (params: SortRowTreeParams) => {
...
-    rowList.forEach((rowId) => {
-      treeSize += 1;
-      const children = sortedGroupedByParentRows.get(rowId);
       if (children?.length) {
-        const subTreeSize = insertRowListIntoSortedRows(startIndex + treeSize, children);
-        treeSize += subTreeSize;
+        const sublist = List.from(children);
+        const subnodes = sublist.nodes();
+        node.insertAfter(sublist);
+        fillList(subnodes);
```
Comment (romgrk) [inline packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts:164]: I think that if I was iterating the list in the reverse order, then it would be possible to fill it without storing the list into a temporary `nodes` array.

**Review by MBilalShafi — COMMENTED** [review]
Impressive how massive a performance jump we can get just by changing the data structure 🎉 

> Is it normal that it only says 944 total rows (with a 100,000 rows dataset) when grouping is on? I've never worked with the grouping code yet, not sure if my PR is wrong or this is how it displays.

Yes, this count shows the root level nodes. The children of the node with `GRID_ROOT_GROUP_ID` id.

File: packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts (hunk 1 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts:164]: Not 100% sure, but if we use `List.forEach()` instead of `List.nodes().forEach()`, we  don't even need recursion here:

```ts
const rootList = List.from<GridRowId>(sortedGroupedByParentRows.get(GRID_ROOT_GROUP_ID)!);

rootList.forEach((node) => {
  const children = sortedGroupedByParentRows.get(node.data);

  if (children?.length) {
    const sublist = List.from(children);
    node.insertAfter(sublist);
  }
});
```

File: packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts [hunk 2]
```diff
@@ -13,9 +13,92 @@ interface SortRowTreeParams {
...
+// Double-linked list node
+class Node<T> {
+  previous: null | Node<T>;
+
+  next: null | Node<T>;
+
+  data: T;
+
+  constructor(data: T, previous: null | Node<T>, next: null | Node<T>) {
+    this.previous = previous;
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts:25]: > edit: or maybe just a single-linked list is enough? I'll update tomorrow

👍

**Review by cherniavskii — APPROVED** [review]
Wow, this is amazing! 🤯 🚀
Thank you, @romgrk! 🎉

File: packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts (hunk 1 above)
Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts]: Done

File: packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts (hunk 2 above)
Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts]: Done

File: packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts (hunk 1 above)
Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts]: No recursion single-linked list, 100,000 rows:

image

**Comment by romgrk** [comment]
> Impressive how massive a performance jump we can get just by changing the data structure

Yeah, memory IO is usually the bottleneck for the majority of software. I highly recommend [this PDF](https://people.freebsd.org/~lstewart/articles/cpumemory.pdf) on the subject.

File: packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts (hunk 1 above)
Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/utils/tree/sortRowTree.ts]: There was indeed no need for recursion nor inversion. I was just very tired when I wrote this.

File: packages/grid/x-data-grid-pro/src/hooks/features/lazyLoader/useGridLazyLoaderPreProcessors.tsx [hunk 3]
```diff
@@ -19,8 +19,7 @@ export const useGridLazyLoaderPreProcessors = (
 
   const addSkeletonRows = React.useCallback<GridPipeProcessor<'hydrateRows'>>(
     (groupingParams) => {
-      const tree = { ...groupingParams.tree };
-      const rootGroup = tree[GRID_ROOT_GROUP_ID] as GridGroupNode;
```
Comment (romgrk) [inline packages/grid/x-data-grid-pro/src/hooks/features/lazyLoader/useGridLazyLoaderPreProcessors.tsx:23]: On the example for the linked issue, this was costing 45ms for nothing.

**Comment by romgrk** [comment]
I've cleaned up the linked list implementation & turned it into a single-linked one.

I've also added a few other small changes, mainly avoiding an object spread that wasn't used, and unwrapping object params into just raw params.

| Before | After |
| --- | --- |
| total-before | total-after |

We can still do more gains but it will need changing the data model and I need some stuff from #9120 in first.

**Review by cherniavskii — APPROVED** [review]
