### PR TITLE
[l10n] Improve French (fr-FR) locale

### LINKED ISSUE #18901: [data grid] "Clear filter" in header filters menu is not translated in french
### Steps to reproduce

Enable header filters, enter any value in any input and use the menu to clear the filter. In french "Clear filter" is displayed.

### Current behavior

See above

### Expected behavior

"Effacer le filtre" or something similar is shown instead.

### Context

See https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/locales/frFR.ts#L113

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.8 Linux Mint 22.1 (Xia)
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 10.13.1 - ~/.nvm/versions/node/v22.11.0/bin/pnpm
  Browsers:
    Chrome: 138.0.7204.168
```
</details>

**Search keywords**: header filters translation clear

**Order ID**: 78178

### PR DESCRIPTION
**Pull request by ddolcimascolo**
Closes #18901

## Changelog

Improved fr-FR locale

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

File: packages/x-data-grid/src/locales/frFR.ts [hunk 1]
```diff
@@ -119,7 +119,7 @@ const frFRGrid: Partial<GridLocaleText> = {
 
   // Column menu text
   columnMenuLabel: 'Menu',
-  // columnMenuAriaLabel: (columnName: string) => `${columnName} column menu`,
+  columnMenuAriaLabel: (columnName: string) => `Menu de colonne pour ${columnName}`,
```
Comment (flaviendelangle) [inline packages/x-data-grid/src/locales/frFR.ts]: Might be more natural

```suggestion
  columnMenuAriaLabel: (columnName: string) => `Menu pour la colonne ${columnName}`,
```

**Review by flaviendelangle — COMMENTED** [review]
Thanks for your contribution!
I just have one nitpick

File: packages/x-data-grid/src/locales/frFR.ts (hunk 1 above)
Comment (ddolcimascolo) [reply packages/x-data-grid/src/locales/frFR.ts]: Fixed

**Comment by ddolcimascolo** [comment]
Thx for the review!
