### PR TITLE
[DataGridPro] Refresh detail panel caches when props change

### LINKED ISSUE #4784: DataGridPro getDetailPanelHeight changes not consistently applied to grid with autoHeight
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When changing the return value of `getDetailHeight` of an `autoHeight` `DataGridPro`, the total height of the data grid does not change.

### Expected behavior 🤔

The height of the autoHeight DataGridPro should adapt when a different value is returned from `getDetailPanelHeight`.

### Steps to reproduce 🕹

Run the example code below and expand / collapse the detail panel of one of the rows.

```typescript
import React from "react";
import {DataGridPro, GridColumns} from "@mui/x-data-grid-pro";
import {Box, Typography} from "@mui/material";

export interface RowModel {
  id: string
  label: string
  text: string
}

const DetailView = React.forwardRef((props: {text: string}, ref) => <Box ref={ref} sx={{backgroundColor: 'red', width: '100%'}}>
  <Typography>{props.text}</Typography>
</Box>)

function useClientRect(): [DOMRect | undefined, (node: HTMLElement | null) => void] {
  const [rect, setRect] = React.useState<DOMRect | undefined>(undefined);
  const ref = React.useCallback((node: HTMLElement | null): void => {
    if (node) {
      setRect(node.getBoundingClientRect())
    } else {
      setRect(undefined)
    }
  }, []);
  return [rect, ref];
}

export default function Table() {
  const [detailRect, detailRef] = useClientRect()

  const columns: GridColumns<RowModel> = React.useMemo(() => [
    {
      flex: 1,
      editable: false,
      field: 'label',
      headerName: 'Label'
    }
  ], [])

  const rows: RowModel[] = React.useMemo(() => [
    {
      id: 'foo',
      label: 'Foo',
      text: 'I am a small piece of text.'
    },
    {
      id: 'bar',
      label: 'Bar',
      text: 'I am a small piece of text.'
    }
  ], []);

  return <DataGridPro
    autoHeight
    sx={{
      width: '100%',
      backgroundColor: 'green',
    }}
    columns={columns}
    rows={rows}
    getDetailPanelContent={params => <DetailView ref={detailRef} text={params.row.text}/>}
    getDetailPanelHeight={() => detailRect?.height ?? 300}
  />
}
```

### Context 🔦

I am working with the Master/Detail feature of a DataGridPro with autoHeight. I would like to have the detail view to have a dynamic height.
As this is currently unsupported, my workaround is to show the detail view (with an over-estimated default height returned from `getDetailPanelHeight`), measure it and then adapt the `getDetailPanelHeight` function to return the correct height for the detail view.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 17.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.79 
    @mui/icons-material: ^5.6.2 => 5.6.2 
    @mui/material: ^5.6.4 => 5.6.4 
    @mui/private-theming:  5.6.2 
    @mui/styled-engine:  5.6.1 
    @mui/system: ^5.6.4 => 5.6.4 
    @mui/types:  7.1.3 
    @mui/utils:  5.6.1 
    @mui/x-data-grid:  5.10.0 
    @mui/x-data-grid-pro: ^5.10.0 => 5.10.0 
    @mui/x-license-pro:  5.10.0 
    @types/react: ^18.0.0 => 18.0.8 
    react: ^18.0.0 => 18.1.0 
    react-dom: ^18.0.0 => 18.1.0 
    typescript: ^4.6.3 => 4.6.4
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #4784

Before: https://codesandbox.io/s/basicdetailpanels-material-demo-forked-t604oh?file=/demo.tsx (CodeSandbox from Andrew)
After: https://codesandbox.io/s/basicdetailpanels-material-demo-forked-7b5ujk?file=/demo.tsx

Previously, the cache for the content and height of the detail panels was always calculated when `getDetailPanelContent` or `getDetailPanelHeight` is changed, but the recalculation didn't trigger a new rows hydration. As consequence, the cache was updated but the height of the panel was the same, unless the panel is closed and reopened. This PR changes to trigger a rows hydration, and also a cache recalculation, when any the props is changed.

### CODE REVIEW

File: packages/grid/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts [hunk 1]
```diff
@@ -57,90 +57,88 @@ export const useGridRowsMeta = (
...
-          (acc2, value) => acc2 + value,
-          0,
-        );
-        return acc + finalRowHeight;
-      }, 0);
+      const finalRowHeight = Object.values(processedSizes).reduce((acc2, value) => acc2 + value, 0);
+      return acc + finalRowHeight;
+    }, 0);
 
+    apiRef.current.setState((state) => {
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts:141]: I had to remove the `apiRef.current.setState`-wrapping-everything to allow a pre-processor to update the state before that the rows hydration is finished. Without this change, the pre-processor will update the state but the changes will be lost because `state` is outdated.
