### PR TITLE
[DataGrid] Add `keepNonExistentRowsSelected` prop

### LINKED ISSUE #4676: [DataGrid] Changing pages causes onSelectionModelChange prop to be invoked
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The current behavior makes it so that a controlled selection is getting "blown away" when the page changes thus making retaining the `selectionModel` difficult / impossible. I am following the example in the [documentation](https://mui.com/x/react-data-grid/selection/#usage-with-server-side-pagination) and am on version `5.10.0`

Demo taken from the documentation with a `console.log` added to show state is not being retained when changing pages:
https://codesandbox.io/s/controlledselectionserverpaginationgrid-material-demo-forked-6whmr8?file=/demo.tsx

Seems like it may be a regression or related to https://github.com/mui/mui-x/issues/2136

### Expected behavior 🤔

When the page changes, the selection model callback should either:

1. Be invoked with the provided selection model
2. Not invoked at all (but I do understand why it's being invoked)

### Steps to reproduce 🕹

https://codesandbox.io/s/controlledselectionserverpaginationgrid-material-demo-forked-6whmr8?file=/demo.tsx

Follow the steps / code described in the documented example to see that it no longer works when opened separately (although it is unclear to me why it seems to be working on the documentation itself)

1. Make a selection on page 1
Screen Shot 2022-04-27 at 4 09 55 PM

2. Go to page 2 and notice that the bottom does not show any rows being selected. Selecting all rows on page will show 5 rows selected (the demo shows the total selected across all pages)
Screen Shot 2022-04-27 at 4 10 02 PM

3. Go back to page 1 and notice no selection have persisted.
Screen Shot 2022-04-27 at 4 10 06 PM

I have added `console.log` statements so you can see the `onSelectionModelChange` calls

### Context 🔦

I am trying to retain selections when changing pages using server side pagination.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 16.13.2 - ~/.volta/tools/image/node/16.13.2/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 7.24.2 - ~/code/project/node_modules/.bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Edge: Not Found
    Firefox: 99.0.1
    Safari: 15.4
  npmPackages:
    @emotion/react: ~11.8.1 => 11.8.1
    @emotion/styled: ~11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.78
    @mui/icons-material: ~5.6.2 => 5.6.2
    @mui/lab: ~5.0.0-alpha.79 => 5.0.0-alpha.79
    @mui/material: ~5.6.3 => 5.6.3
    @mui/private-theming:  5.6.2
    @mui/styled-engine:  5.6.1
    @mui/styles: ~5.6.2 => 5.6.2
    @mui/system:  5.6.3
    @mui/types:  7.1.3
    @mui/utils:  5.6.1
    @mui/x-data-grid: ~5.10.0 => 5.10.0
    @mui/x-date-pickers:  5.0.0-alpha.0
    @types/react: ~17.0.39 => 17.0.39
    react: ~17.0.2 => 17.0.2
    react-dom: ~17.0.2 => 17.0.2
    typescript: ~4.5.5 => 4.5.5
```

Using Firefox: 99.0.1
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by willsoto**
Preview: https://deploy-preview-4786--material-ui-x.netlify.app/x/react-data-grid/selection/#usage-with-server-side-pagination

_Implementation based on [this comment](https://github.com/mui/mui-x/issues/4676#issuecomment-1119867144)_

By setting this prop to `true`, onSelectionModelChange will be called with
the selectionModel even when the selectionModel is no longer visible in the table.

Closes #4676

### CODE REVIEW

File: packages/grid/x-data-grid/src/hooks/features/selection/useGridSelection.ts [hunk 1]
```diff
@@ -265,6 +266,12 @@ export const useGridSelection = (
    * EVENTS
    */
   const removeOutdatedSelection = React.useCallback(() => {
+    if (props.keepNonExistentRowsSelected) {
+      // Trigger the selection model callback again but with whatever values are currently selected
+      // This will help consumers keep the selectionModel in sync
+      apiRef.current.setSelectionModel(Object.values({ ...selectedIdsLookupSelector(apiRef) }));
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/hooks/features/selection/useGridSelection.ts:272]: Why you added this call? Was it added to help testing? Since `Object.values` always returns a new object, `setSelectionModel` will be called even if the model didn't change. Eventually, you'll need to pass `selectionModel` to clean the selection, so this call might not be necessary.

File: packages/grid/x-data-grid/src/models/props/DataGridProps.ts [hunk 2]
```diff
@@ -247,6 +247,13 @@ export interface DataGridPropsWithDefaultValues {
    * @default false
    */
   hideFooterSelectedRowCount: boolean;
+  /**
+   * If `true`, the selectedRow model will retain selected rows that do not exist.
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/models/props/DataGridProps.ts:251]:
```suggestion
   * If `true`, the selection model will retain selected rows that do not exist.
```

File: packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx [hunk 3]
```diff
@@ -571,6 +571,30 @@ describe('<DataGrid /> - Selection', () => {
...
+          keepNonExistentRowsSelected
+          onSelectionModelChange={onSelectionModelChange}
+          {...data}
+        />,
+      );
+      expect(getSelectedRowIds()).to.deep.equal([0, 1, 2]);
+
+      setProps({
+        rows: data.rows.slice(0, 1),
+      });
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx:592]: To save 2 lines.

```suggestion
      setProps({ rows: data.rows.slice(0, 1) });
```

File: packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx [hunk 4]
```diff
@@ -571,6 +571,30 @@ describe('<DataGrid /> - Selection', () => {
...
+      // This expectation is around visible rows
+      expect(getSelectedRowIds()).to.deep.equal([0]);
+      // The callback should be called with the true selectionModel
+      expect(onSelectionModelChange.lastCall.args[0]).to.deep.equal([0, 1, 2]);
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx:596]: An alternative is to check the number of selected rows in the footer.

**Review by m4theushw — COMMENTED** [review]
Thanks for the contribution. Do you mind updating the demo in https://deploy-preview-4786--material-ui-x.netlify.app/x/react-data-grid/selection/#usage-with-server-side-pagination to use the new prop, in place of the ref?

File: packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx (hunk 4 above)
Comment (willsoto) [reply packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx:594]: This is partially why I added that call. I'll update the test and I should be able to remove all of it.

**Review by m4theushw — APPROVED** [review]
LGTM! I pushed one commit updating the description in the docs.

**Review by DanailH — APPROVED** [review]

File: packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx [hunk 5]
```diff
@@ -1,5 +1,5 @@
 import * as React from 'react';
-// @ts-ignore Remove once the test utils are typed
+// @ts-expect-error Remove once the test utils are typed
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx:2]: Why?

Comment (willsoto) [reply packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx:2]: Once the test utils are typed, the type checker will automatically throw an error here. This way people know what to TODOs to remove once the issue is fixed. Some more info [here](https://github.com/microsoft/TypeScript/issues/37458)

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx:2]: Nice!

**Review by cherniavskii — APPROVED** [review]
