### PR TITLE
[pickers] Fix week day label localization

### LINKED ISSUE #10790: [pickers] `DateCalendar` week day label are not understandable with the hebrew locale
### Steps to reproduce

Link to live example:  https://codesandbox.io/s/date-picker-material-ui-forked-5q52m6?file=/src/App.js

1. Use     "@mui/x-date-pickers": "^6.16.3"
2. Use     <LocalizationProvider dateAdapter={AdapterDateFns} adapterLocale={he}> , all from the correct imports.
3. Doesn't work properly.

### Current behavior

image

### Expected behavior

it should be - 
image

Not sure why it is like that. I could not for the life of me find a way to 'customize' the days of week either, so I ended going back version until worked (    "@mui/x-date-pickers": "^5.0.0-beta.1" )

### Context

_No response_

### Your environment

chrome.

**Search keywords**: Date Picker

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #10790 

Change `weekdayShort` formats to be more in line with what `adapter.getWeekdays` used to do.

Doing so fixes the localization problem on `date-fns` and `luxon` adapters on certain locales (e.g. Hebrew).
It also reverts the previous `dayOfWeekFormatter` behavior.

### Before https://github.com/mui/mui-x/pull/10345 (v6.15.0) 🔣 
https://codesandbox.io/s/unruffled-kilby-7ssyfz?file=/src/Demo.tsx

#### With custom formatter
6_15_0-with-custom-formatter

#### Hebrew locale
6_15_0-hebrew

### Current release (v6.16.3)
https://codesandbox.io/s/blissful-johnson-s2n5cl?file=/src/Demo.tsx

#### With custom formatter
6_16_3-with-custom-formatter

#### Hebrew locale
6_16_3-hebrew

### After 🔠 
https://codesandbox.io/s/old-wildflower-6ljv9l?file=/src/Demo.tsx

#### With custom formatter
fix-with-custom-formatter

#### Hebrew locale
fix-hebrew

### CODE REVIEW

File: packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx [hunk 1]
```diff
@@ -565,9 +565,7 @@ export function DayCalendar<TDate>(inProps: DayCalendarProps<TDate>) {
           </PickersCalendarWeekNumberLabel>
         )}
         {getWeekdays(utils, now).map((weekday, i) => {
-          // regression-prevention:
-          // since 'weekdayShort' now always returns an abbreviated form we slice the first 2 letters from it.
-          const day = utils.format(weekday, 'weekdayShort').slice(0, 2);
```
Comment (LukasTy) [inline packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx:570]: The `slice` was causing the discrepancy between behavior before v6.16.0. 🤔

Comment (michelengelen) [reply packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx:570]: oh, yeah ... that's a blunder I made 😮‍💨 ... Sry! We do this in the default `dayOfWeekFormatter` in a similar way. I guess I just wanted to pass the first 2 chars since that was the previous behaviour

File: packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.ts [hunk 2]
```diff
@@ -138,7 +138,7 @@ const defaultFormats: AdapterFormats = {
   monthShort: 'MMM',
   dayOfMonth: 'd',
   weekday: 'EEEE',
-  weekdayShort: 'EEE',
+  weekdayShort: 'EEEEE',
```
Comment (michelengelen) [inline packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.ts]: shouldn't this also be `EEEEEE` 🤔 
```suggestion
  weekdayShort: 'EEEEEE',
```

File: packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx (hunk 1 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx:570]: > oh, yeah ... that's a blunder I made 😮‍💨 ... Sry! We do this in the default `dayOfWeekFormatter` in a similar way. I guess I just wanted to pass the first 2 chars since that was the previous behaviour

Was it? 🤔 
I believe that we were not doing any preformatting of the resulting item from the `adapter.getWeekdays` before. 🤷

File: packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.ts (hunk 2 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.ts]: You were probably checking the first commit changeset. 🙈

File: packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx (hunk 1 above)
Comment (michelengelen) [reply packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx:570]: well, previously we just returned a formatted string from the adapter method `getWeekDays`. But the format Token was hard coded. Maybe thats why I thought it's always the same

**Review by michelengelen — APPROVED** [review]
