### PR TITLE
[DataGrid] Remove the deprecated `hide` property of `GridColDef`

### LINKED ISSUE #5970: [DataGrid] Columns not updating with `apiRef.current.updateColumns`
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Using `apiRef.current.updateColumns` doesn't seem to update the existing columns.

### Expected behavior 🤔

It should update the columns

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/brave-breeze-quutgg?file=/demo.tsx

Steps:
1. click the "update columns" button
2. one grid will update (because it remounts when columns change). The other won't, which uses `updateColumns` to trigger an update.

### Context 🔦

Toolpad needs to update the columns of a grid in the canvas when a user makes changes in the editor. (currently we remount by regenerating a `key` when `columns` or `getRowId` changes)

### Your environment 🌎

https://codesandbox.io/s/brave-breeze-quutgg?file=/demo.tsx

### Order ID 💳 (optional)

_No response_

### LINKED ISSUE #6001: [data grid] Remove the `hide` property of `GridColDef`
# Summary

Breaking change for v6. 
For more context: #3287 

Remove the deprecated `hide` property of `GridColDef`.

# Motivation

In `v5.3.0`, we introduced a new model (`columnVisibilityModel`) that allows a better visibility management (with state import / export, controlling, callback when hiding all and showing all at once, etc...)

The legacy `hide` property has been deprecated since this release and is intended to be removed in v6

### PR DESCRIPTION
**Pull request by flaviendelangle**
To fix #5970 I will first remove the deprecated behavior to make the logic easier to play with.

Closes #6001

- [x] Remove all the logic around the `hide` property and its synchronization with the new model
- [x] Remove the doc section
- [x] Remove the deprecated tests
- [x] Remove the `columnVisibilityChange` event and the `onColumnVisibilityChange` callback
- [x] Fix all the stories to pass the `initialState` to the grid to have the `columnVisibilityModel`

@m4theushw @DanailH can we please kill the Storybook ?
I feel like the only time I hear about it is when I need to spend 2 hours doing a migration on every story to have it still works.
Its content is super outdated and nobody keeps it up to date with the new features and apis.

### CODE REVIEW

File: docs/data/data-grid/filtering/ServerFilterGrid.tsx [hunk 1]
```diff
@@ -12,13 +12,13 @@ export default function ServerFilterGrid() {
...
-  const { isLoading, data } = useQuery(queryOptions);
+  const { isLoading, rows } = useQuery(queryOptions);
 
   return (
     <div style={{ height: 400, width: '100%' }}>
       <DataGrid
-        rows={data}
-        columns={columns}
+        rows={rows}
+        {...data}
```
Comment (alexfauquette) [inline docs/data/data-grid/filtering/ServerFilterGrid.tsx:21]:
```suggestion
        {...data}
        rows={rows}
```
I thaught it would be the opposite. Maybe it's the same

File: packages/grid/x-data-grid/src/tests/columnsVisibility.DataGrid.test.tsx [hunk 2]
```diff
@@ -78,7 +75,6 @@ describe('<DataGridPro /> - Columns Visibility', () => {
       expect(onColumnVisibilityModelChange.callCount).to.equal(1);
       expect(onColumnVisibilityModelChange.lastCall.firstArg).to.deep.equal({
         id: false,
-        idBis: true,
```
Comment (alexfauquette) [inline packages/grid/x-data-grid/src/tests/columnsVisibility.DataGrid.test.tsx:81]: Should we warn dev about the fact that ?

```js
// Good
isVisible = columnVisibilityModel[field] !== false
// Good
isVisible = columnVisibilityModel[field] ?? true
// Wrong
isVisible = columnVisibilityModel[field]
```

**Review by alexfauquette — APPROVED** [review]

File: packages/grid/x-data-grid/src/tests/columnsVisibility.DataGrid.test.tsx (hunk 2 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/tests/columnsVisibility.DataGrid.test.tsx:81]: I think once we had done #6037 we can add a small note in the doc :+1:

File: docs/data/data-grid/filtering/ServerFilterGrid.tsx (hunk 1 above)
Comment (flaviendelangle) [reply docs/data/data-grid/filtering/ServerFilterGrid.tsx:21]: I don't know if it's the same, but it's clearly a bad habit, fixed :+1:

**Review by m4theushw — APPROVED** [review]
Do we still need the warning in https://deploy-preview-5999--material-ui-x.netlify.app/x/react-data-grid/column-visibility/#controlled-visible-columns? I tested and it appears we already support changing from uncontrolled to controlled.

**Comment by flaviendelangle** [comment]
@m4theushw indeed, removed :+1:
