### PR TITLE
[charts] Fix bar border radius on Firefox

### LINKED ISSUE #14690: [charts] Bar chart borderRadius not applied on Firefox
### Search keywords

barchart, borderRadius, firefox

### Latest version

- [X] I have tested the latest version

### Affected products

Charts

### Steps to reproduce

Link to live example: https://mui.com/x/react-charts/bars/#border-radius

`borderRadius` property of  `<BarPlot />` is not working in Firefox.
SVG `clip-path` looks correct but is ignored by FF.

### Current behavior

**Firefox Developer Edition 131.0b8 (64-bit)**
image

**Firefox ESR 115.15.0esr**
image

### Expected behavior

**Using Chrome Version 129.0.6668.58 (64 bits)**
image

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by bernardobelchior**
Fixes #14690.

Fix bar border radius on Firefox.

#### Visual Test

image

#### Animation (10x slowdown)

Chrome:

https://github.com/user-attachments/assets/56b08080-1110-44b0-ac06-99d10b3cfac0

Firefox:

https://github.com/user-attachments/assets/abed2455-33d3-4aa6-813c-136f0e5fab18

Safari:

https://github.com/user-attachments/assets/921da1b2-1fdb-472d-ba08-5c2aed077555

### CODE REVIEW

File: packages/x-charts/src/BarChart/BarClipPath.tsx [hunk 1]
```diff
@@ -135,24 +108,77 @@ export interface BarClipPathProps {
...
-        width={width}
-        height={height}
-        skipAnimation={skipAnimation}
-      />
+      <path ref={ref} d={d} />
     </clipPath>
   );
 }
 
+function generateClipPath(
```
Comment (bernardobelchior) [inline packages/x-charts/src/BarChart/BarClipPath.tsx:137]: The main logic is here:

**Review by JCQuintas — APPROVED** [review]
Nice, the animation looks better too 👍 

I just want to point out that this is "technically" a breaking change if users were previously targeting the clip rect somehow to customise it (eg: uneven border radius), though it is very very unlikely, so I'm ok with going forward with this 😆
