### PR TITLE
[fields] Use `onChange` instead of `onKeyPress` for Backspace editing

### LINKED ISSUE #10399: [DateField] LL format allows for removing MMMM placeholder resulting in issues when filling in a date.
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:
_Issue also exists on docs page_ https://mui.com/x/react-date-pickers/date-field/#customize-the-date-format in the LL format.  

Steps:
1. Open https://mui.com/x/react-date-pickers/date-field/#customize-the-date-format on a mobile android device 
2. Focus on input with labelled with 'full letter month'
3. Hit backspace to remove 'April' from the input
4. Hit backspace again.
5. Click elsewhere on the page
6. Put focus back in input labelled with 'full letter month'
7. Fill the input value with a month

### Current behavior 😯

In the current behaviour (on mobile) the pre-filed MMMM value gets removed when hitting the hitting the backspace key on the keyboard when there is no value. 

### Expected behavior 🤔

The initial value of MMMM should stay in place when hitting the delete or backspace key when there is no other value.

### Context 🔦

In our application we are using the DateField component as part of a registration form. We switched away from the browser native DatePicker as this was confusing to use and required a lot of scrolling for elderly users. 

We are using the DateField in combination with the LocalizationProvider (using AdapterDayjs). We went for the LL format to stay as close to the date format our foreign users are familiar with. We opted for a full letter month as this reduces more confusion about date format.

When we were testing the DateField in our application we noticed in date formats where month is in the middle (nl, de, fr, es, etc.) removing the Month part completely results in a problem where you cannot fill it back in. This would require a page refresh the state for the rest of the form.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.5.1/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
  Browsers:
    Chrome on Android: v117.0.5938.60 (Android 13)
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.16 
    @mui/core-downloads-tracker:  5.14.10 
    @mui/material: ^5.14.10 => 5.14.10 
    @mui/private-theming:  5.14.10 
    @mui/styled-engine:  5.14.10 
    @mui/system:  5.14.10 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.10 
    @mui/x-date-pickers: ^6.14.0 => 6.14.0 
    @types/react: ^18.0.33 => 18.0.33 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^4.9.5 => 4.9.5 
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #10399

After some more investigation, the problem is that the `Backspace` key is always treated as `Unidentified` on Android, so it was edited using `onChange`.
I updated the `onChange` to work with Backspace editing, removed the Backspace editing from `onKeyPress` and updated all the tests.

### CODE REVIEW

File: packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts [hunk 1]
```diff
@@ -213,6 +213,10 @@ export const useFieldState = <
       tempValueStrAndroid: null,
     }));
 
+    if (valueManager.areValuesEqual(utils, state.value, value)) {
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts:216]: Before, we were not even calling `publishValue`.
But it's problematic with `Backspace` because the state was not updated when pressing `Backspace` on an already empty section, causing the selection to be removed by the browser.
So now we always update the state but we don't publish `onChange` if not needed

File: packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts [hunk 2]
```diff
@@ -254,20 +254,16 @@ export const useFieldState = <
...
-      return;
-    }
-
     const activeDateManager = fieldValueManager.getActiveDateManager(utils, state, activeSection);
 
     const nonEmptySectionCountBefore = activeDateManager
       .getSections(state.sections)
       .filter((section) => section.value !== '').length;
-    const isTheOnlyNonEmptySection = nonEmptySectionCountBefore === 1;
+    const hasNoOtherNonEmptySections =
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/useField/useFieldState.ts:262]: Small fix when the active section is already empty
If could never happen before

**Review by LukasTy — COMMENTED** [review]
Great work! 💯 
This has the added benefit of now allowing the full date clearing.
Previously clicking `Backspace` on Android while having the whole field selected would not correctly clear the field 🙈 

I noticed that after these changes there is some sort of flickering happening when deleting a section value on Android, it also happens when trying to delete already empty section.
It seems that visually the section value gets removed and then added back in.
Is there any way we could avoid this, because the UX is not the best now. 🙈

**Review by LukasTy — APPROVED** [review]
Sorry for missing the mentioned comment. 🙈 
Yeah, it's definitely not a big problem, it's not that you constantly need to delete already empty sections. 😆

**Comment by flaviendelangle** [comment]
The mentionned comment is in the middle of thousands of lines of code, not easy to spot :ok_hand:
