### PR TITLE
[DataGrid] Fix resizing right pinned column

### LINKED ISSUE #12852: [data grid] The right pinned column shrinks from the opposite side when resizing
### Search keywords

resizing pinned right

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/flamboyant-davinci-2ch3pp?file=%2Fsrc%2FDemo.tsx%3A50%2C1

Steps:
1. Resize the last pinned column

https://github.com/mui/mui-x/assets/18424848/13da3c9c-a640-4a6b-8f95-ccfde9e73365

### Current behavior

The right pinned column shrinks from the opposite side when resizing

### Expected behavior

The right pinned column doesn't shrink from the opposite side when resizing

### Context

_No response_

### Your environment

_No response_

### Order ID or Support key 💳 (optional)

74777

### PR DESCRIPTION
**Pull request by KenanYusuf**
Fixes #12852 and #13548

There is already [a PR open](https://github.com/mui/mui-x/pull/12979) that fixes the same issue, but takes a different approach. Curious to see what others think of this way which relies on always rendering the empty cell (rather than conditionally) to grow/shrink in the space as the column resizes.

Before: https://mui.com/x/react-data-grid/column-pinning/
After: https://deploy-preview-15107--material-ui-x.netlify.app/x/react-data-grid/column-pinning/

### CODE REVIEW

File: packages/x-data-grid/src/components/GridRow.tsx [hunk 1]
```diff
@@ -477,8 +451,7 @@ const GridRow = React.forwardRef<HTMLDivElement, GridRowProps>(function GridRow(
         style={{ width: offsetLeft }}
       />
       {cells}
-      {emptyCellWidth > 0 && <EmptyCell width={emptyCellWidth} />}
-      {rightCells.length > 0 && <div role="presentation" className={gridClasses.filler} />}
+      <div role="presentation" className={clsx(gridClasses.cell, gridClasses.cellEmpty)} />
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/components/GridRow.tsx:454]: Rendering the empty cell all the time improves resizing of the right-pinned cells

**Before**

https://github.com/user-attachments/assets/779b759b-4cd7-4948-9d4c-2fc74a8f7b41

**After**

https://github.com/user-attachments/assets/7546bd15-9830-4217-973d-395a31c0220c

File: packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx [hunk 2]
```diff
@@ -300,12 +300,14 @@ export const useGridColumnResize = (
     const prevWidth = refs.columnHeaderElement!.offsetWidth;
     const widthDiff = newWidth - prevWidth;
     const columnWidthDiff = newWidth - refs.initialColWidth;
-    const newTotalWidth = refs.initialTotalWidth + columnWidthDiff;
 
-    apiRef.current.rootElementRef?.current?.style.setProperty(
-      '--DataGrid-rowWidth',
-      `${newTotalWidth}px`,
-    );
+    if (columnWidthDiff > 0) {
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx:304]: **Before**

https://github.com/user-attachments/assets/dce6f970-8c5e-43e6-9041-b32271c2c6a4

**After**

https://github.com/user-attachments/assets/b3539398-5c78-4cba-9f91-772d9f584cea

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 3]
```diff
@@ -564,6 +564,7 @@ export const GridRootStyles = styled('div', {
       lineHeight: 'inherit',
     },
     [`& .${c.cellEmpty}`]: {
+      flex: 1,
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/components/containers/GridRootStyles.ts:567]: This way the empty cell always takes up the right amount of space in a row. Shrinks when the row is full of cells, grows when there aren't enough to fill a row.

File: packages/x-data-grid/src/components/GridRow.tsx [hunk 4]
```diff
@@ -477,8 +451,7 @@ const GridRow = React.forwardRef<HTMLDivElement, GridRowProps>(function GridRow(
         style={{ width: offsetLeft }}
       />
       {cells}
-      {emptyCellWidth > 0 && <EmptyCell width={emptyCellWidth} />}
-      {rightCells.length > 0 && <div role="presentation" className={gridClasses.filler} />}
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/components/GridRow.tsx:481]: Not sure why we need this + the empty cell. Perhaps I'm missing something for this.

File: packages/x-data-grid/src/components/GridRow.tsx (hunk 1 above)
Comment (KenanYusuf) [reply packages/x-data-grid/src/components/GridRow.tsx:454]: Ideally the actions column would also move with the right pinned column in the after...

File: packages/x-data-grid/src/components/GridRow.tsx (hunk 4 above)
Comment (romgrk) [reply packages/x-data-grid/src/components/GridRow.tsx:481]: I don't remember :| You should build a test case with all the variations of:
 - pinned or no pinned columns
 - scrollbar or no scrollbar
 - empty space or no empty space (when columns don't fill the width)

And then check if all the cases behave correctly. Make sure to enable vertical borders on all cells, it will help you spot issues.

We should probably create a visual regression test based on that.

**Review by romgrk — COMMENTED** [review]
LGTM, if it behaves the same and fixes all issues that would be amazing.

File: packages/x-data-grid/src/tests/rows.DataGrid.test.tsx [hunk 5]
```diff
@@ -750,7 +750,7 @@ describe('<DataGrid /> - Rows', () => {
             width={100}
           />,
         );
-        expect(document.querySelectorAll('.MuiDataGrid-cell')).to.have.length(2);
+        expect(document.querySelectorAll('.MuiDataGrid-cell')).to.have.length(3);
```
Comment (cherniavskii) [inline packages/x-data-grid/src/tests/rows.DataGrid.test.tsx:753]:
```suggestion
        expect($$(`.${gridClasses.cell}:not(.${gridClasses.cellEmpty})`)).to.have.length(2);
```
To make it more clear

**Review by cherniavskii — APPROVED** [review]
Great job!
