### PR TITLE
[DataGrid] Fix column cell and row cell focus style

### LINKED ISSUE #1291: [DataGrid] Roving tabindex is wrong
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Misalignment with the guidelines WAI-ARIA guidelines.

## Expected Behavior 🤔

Alignment with the guidelines.

## Steps to Reproduce 🕹

1. Open: https://codesandbox.io/s/material-demo-forked-c6kb1?file=/demo.js
2. Set the focus on the "start" button
3. Use <kbd>Tab</kbd> to move the focus forward until reaching the "end" button

I see 3 things wrongs:

1. No focus-visible feedback on when the focus is on the root container
2. The root container shouldn't be focusable. See "Because focus is managed using roving tabindex , the grid element is **not focusable**." https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html
3. Per the [roving focus index](https://www.w3.org/TR/wai-aria-practices/#kbd_roving_tabindex) management in a composite widget, setting `tabIndex="0"` on the first item would make more sense. This is the most IMPORTANT part of this bug report. Without it, end-users, can't navigate the cells with the keyboard only.

## Context 🔦

First reported in #1289 by @DanailH.

> as far as I could work out there is no way to navigate to focus a cell in the grid, meaning that when changing focus using tab the focus will move through what is in the toolbar and then be lost - IMO it should focus the first cell or column header (needs to be decided)

Also, looking at the example in https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html. They set tabIndex={-1} on the inner button in the cells. I wonder if we shouldn't do the same with our checkboxes. No idea.

## Your Environment 🌎

v4.0.0-alpha.23

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #1291 

In response to that comment https://github.com/mui-org/material-ui-x/issues/1291#issuecomment-832588416

Preview: https://deploy-preview-1575--material-ui-x.netlify.app/components/data-grid

### CODE REVIEW

**Comment by dtassone** [comment]
Nice 👍 

FYI there are some refactoring around this area in #1513 
Not the styling so great :)

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
See the report from argos, the diff doesn't work

**Comment by DanailH** [comment]
> See the report from argos, the diff doesn't work

I think that is expected right? Because the way the checkbox behaves when it is in the column is that it focuses the input directly. Another solution would be to keep it as it was but make the column header checkbox also have an outline that matches the cell one.

**Comment by oliviertassinari** [comment]
I think that the expected outcome that would work the best from a UX perspective is to have a single focus-visible indicator when in view mode, and always the outline when in edit mode, so only removing the outline in this state:

Screenshot 2021-05-06 at 12 16 17

cc @m4theushw for thoughts has he was the last to improve the UI on this aspect.

**Comment by DanailH** [comment]
I've updated the PR, now if the cell is a checkbox cell there won't be a outline.

File: packages/grid/_modules_/grid/components/containers/GridRootStyles.ts [hunk 1]
```diff
@@ -229,7 +229,7 @@ export const useStyles = makeStyles(
           textOverflow: 'ellipsis',
           whiteSpace: 'nowrap',
           borderBottom: `1px solid ${borderColor}`,
-          '&:focus-within': {
+          '&:focus-within:not(.MuiDataGrid-cellCheckbox)': {
```
Comment (oliviertassinari) [inline packages/grid/_modules_/grid/components/containers/GridRootStyles.ts:232]: Developers can move the focus inside their cell too: #1465. Could we use the editable CSS class name instead?

Comment (DanailH) [reply packages/grid/_modules_/grid/components/containers/GridRootStyles.ts:232]: I'm sorry it seems that I'm struggling to understand the end goal. I thought I'm only removing the outline for the cell that has a checkbox in it and keep it as it is for all the others, no?

Comment (DanailH) [reply packages/grid/_modules_/grid/components/containers/GridRootStyles.ts:232]: I'm sorry it seems that I'm struggling to understand the end goal. I thought I'm only removing the outline for the cell that has a checkbox in it and keep it as it is for all the others, no? If I use `.MuiDataGrid-cellEditable` it would remove all editable cells, also the checkbox cell doesn't currently have that class.

Comment (oliviertassinari) [reply packages/grid/_modules_/grid/components/containers/GridRootStyles.ts:232]: My assumption are the following:

> a single focus-visible indicator when in view mode (**to** not be confused about where the real focus is), and always have the outline when in edit mode (this style works in a combination of the box-shadow, **to** make it clear what's in edit mode)

Comment (m4theushw) [reply packages/grid/_modules_/grid/components/containers/GridRootStyles.ts:232]: > a single focus-visible indicator when in view mode (to not be confused about where the real focus is, only one element can have it, not two), and always have the outline when in edit mode (this style works in a combination of the box-shadow, to make it clear what's in edit mode)

@oliviertassinari  I'm missing something here. When you say focus-visible I think about the `:focus-visible` pseudo-class. It's only applied to one element and where the real focus is. I agree with showing the dotted outline in view mode and the solid outline in edit mode.

File: packages/grid/_modules_/grid/components/containers/GridRootStyles.ts [hunk 2]
```diff
@@ -88,7 +88,7 @@ export const useStyles = makeStyles(
           padding: theme.spacing(0, 2),
         },
         '& .MuiDataGrid-colCell:focus, & .MuiDataGrid-cell:focus': {
-          outline: 'dotted',
+          outline: `solid ${theme.palette.primary.main} 1px`,
```
Comment (m4theushw) [inline packages/grid/_modules_/grid/components/containers/GridRootStyles.ts:91]: You should use the same `:not(.MuiDataGrid-cellCheckbox)` here to not show the outline in the checkbox column. If I click in the corner it won't match the `:focus-within`.

focus

**Review by dtassone — APPROVED** [review]

**Comment by DanailH** [comment]
Thanks, @oliviertassinari. The only thing is that this https://github.com/mui-org/material-ui-x/pull/1575#discussion_r627423838 now reappears, but if I think about it again it is better that way because otherwise the focus changes and there is no visible indication.

**Comment by oliviertassinari** [comment]
> The only thing is that this #1575 (comment) now reappears

Interesting. The other issue is that when using the click modality, there are no focus indicators. It feels inconsistent. In this case, maybe we should `:focus -> :focus-within`?

**Comment by dtassone** [comment]
> Interesting. The other issue is that when using the click modality, there are no focus indicators. It feels inconsistent. In this case, maybe we should `:focus -> :focus-within`?
> 
> Or even better: have **two** different colors intensity based on either the root of the cell is focused or only its children. It would still be 1-level of specificity so easy to override.

Seems like low priority to me. Should we create a separate issue, or can it be a quick fix?

**Comment by oliviertassinari** [comment]
>  Should we create a separate issue, or can it be a quick fix?

10 minutes fix

**Comment by oliviertassinari** [comment]
I have pushed a new proposal. I'm not really happy with it, I don't like how the background color intensity doesn't tell if the arrow navigation is available or not but it's the least worth option I have seen so far. Alternative ideas are welcome.

**Comment by DanailH** [comment]
Ok  @oliviertassinari now I understand what you meant by the comment before the last one 😅

To be this looks better than the initial solution. The visual indication that the cell is focused is better.

**Comment by oliviertassinari** [comment]
OK, no preferences between the two options.
