### PR TITLE
[charts] Fix missing configuration types

### LINKED ISSUE #9852: [charts] re-export AxisConfig on top level, like SeriesTypes are exported
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

```diff
import type { BarSeriesType } from "@mui/x-charts";
-import type { AxisConfig } from "@mui/x-charts/models/axis";
+import type { AxisConfig } from "@mui/x-charts";
```

### Examples 🌈

_No response_

### Motivation 🔦

Docs [state](https://mui.com/material-ui/guides/minimizing-bundle-size/#option-one-use-path-imports) that 
> we only support first and second-level imports. Anything deeper is considered private and can cause issues

So I've added the recommended no-restricted-imports rule from there, and it errors on current import of AxisConfig.

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #9852

### CODE REVIEW

File: packages/x-charts/src/models/index.ts [hunk 1]
```diff
@@ -1 +1,9 @@
 export * from './seriesType';
+export * from './layout';
+export {
```
Comment (flaviendelangle) [inline packages/x-charts/src/models/index.ts:3]:
```suggestion
export type {
```
