### PR TITLE
[pickers] Pass the date object to `dayOfWeekFormatter` and deprecate the string parameter

### LINKED ISSUE #9984: Just got the first letter of the days ussing Luxon Adapter on Date Calendar
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Just a simple case of the Date Calendar

``` tsx
      <LocalizationProvider dateAdapter={AdapterLuxon}>
        <DateCalendar
          dayOfWeekFormatter={(day) => {
            console.log(day);
            return day.charAt(0).toUpperCase() + day.slice(1, 3);
          }}
        />
      </LocalizationProvider>
```

### Current behavior 😯

In my console.log, i got `M, T, W, T, F, S, S`

### Expected behavior 🤔

I would like to get the complete day (as i think it is describe in the doc) `Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday`

### Context 🔦

I want to render the 3 first letter avec the day, like `Mon, Tue, Wed` ....

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: macOS 13.5
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: Not Found
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Edge: Not Found
    Safari: 16.6
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.8 
    @mui/core-downloads-tracker:  5.14.2 
    @mui/icons-material: ^5.14.0 => 5.14.1 
    @mui/lab:  5.0.0-alpha.137 
    @mui/material: ^5.14.0 => 5.14.2 
    @mui/private-theming:  5.13.7 
    @mui/styled-engine:  5.13.2 
    @mui/system:  5.14.1 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.1 
    @mui/x-date-pickers: ^6.11.0 => 6.11.0 
    @types/react: ^18.0.14 => 18.2.16 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.1.6 => 5.1.6 
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by michelengelen**
## Description

The `dayOfWeekFormatter` received only a string as parameter and to handle this the user had to manually detect which day of the week he received before handling its formatting (if he intended to change something on that).
Now the formatting function receives the date object (according to the used adapter), so the flexibility is increased by a fair margin here.

As a way of fixing this the `getWeekdays` method will be deprecated and replaced by the new `getWeek` method in the adapters. This now returns an array of date objects for the week of the given date. The signature looks like this:

```ts
getWeek(value: TDate): TDate[];
```

The new signature for the `dayOfWeekFormatter` is now:

```ts
dayOfWeekFormatter?: (weekday: TDate) => string;
```

the default behaviour is kept the same (returning the initial of the weekday):

```ts
(weekday: TDate) => utils.format(weekday, 'weekdayShort').charAt(0).toUpperCase()
```

This introduces a minor breaking change.

Fixes #9984 

---

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

File: packages/x-date-pickers/src/models/adapters.ts [hunk 1]
```diff
@@ -721,9 +721,16 @@ export interface MuiPickersAdapter<TDate, TLocale = any> {
...
+   * @deprecated Will be removed in v7. Use `adapter.getWeek` and format the Dates.
    * @returns {string[]} The label of each day of a week.
    */
   getWeekdays(): string[];
+  /**
+   * Get an array with all the weekdays dates in the week of the given date.
+   * @param {TDate} value The given date.
+   * @returns {TDate[]} The date of each day of a week.
+   */
+  getWeek(value: TDate): TDate[];
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/models/adapters.ts:733]: Did you encountered anything preventing you from not putting this logic inside the adapter?

See https://github.com/mui/mui-x/issues/9984#issuecomment-1717602090

File: packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx [hunk 2]
```diff
@@ -62,11 +62,11 @@ export interface ExportedDayCalendarProps extends ExportedPickersDayProps {
...
   /**
    * Formats the day of week displayed in the calendar header.
-   * @param {string} day The day of week provided by the adapter's method `getWeekdays`.
+   * @param {TDate} weekday The day of week provided by the adapter's method `getWeek`.
    * @returns {string} The name to display.
-   * @default (day) => day.charAt(0).toUpperCase()
+   * @default (weekday: TDate) => adapter.format(weekday, 'weekdayShort').charAt(0).toUpperCase()
    */
-  dayOfWeekFormatter?: (day: string) => string;
+  dayOfWeekFormatter?: (weekday: TDate) => string;
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx:69]: For me we can't do this breaking change during a minor
Sorry if I was not clear, in https://github.com/mui/mui-x/issues/9984#issuecomment-1717634957 I was talking purely about stopping using `adapter.getWeekdays` not being breaking.

If we want to improve `dayOfWeekFormatter`, we have two options:

1. Create a new prop `dayOfWeekFormatterV7` that takes a date, deprecated `dayOfWeekFormatter` and swap in v7
2. Add the date as a 2nd param on `dayOfWeekFormatter` and remove the 1st param in v7.

Comment (michelengelen) [reply packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx:69]: see https://github.com/mui/mui-x/pull/10345#discussion_r1327238451

File: packages/x-date-pickers/src/models/adapters.ts (hunk 1 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/models/adapters.ts:733]: Initially, I was talking about deprecating `getWeekDays` and add a new adapter method that does the same but returning dates.

BUT, I saw that if the new `getWeekDays` returns dates, then it can be created outside of the adapter (see my comment linked above).
So we can just deprecate `adapters.getWeekDays` and create a new utility method in the picker package that returns dates and use it internally.

____

For `dayOfWeekFormatter`, we clearly have a breaking change and for me we need to do it in a non-breaking way :+1:

**Comment by michelengelen** [comment]
@flaviendelangle could re-review? I have added the requested changes

File: docs/data/date-pickers/adapters-locale/CustomDayOfWeekFormat.tsx [hunk 3]
```diff
@@ -12,7 +12,7 @@ export default function CustomDayOfWeekFormat() {
       <DateCalendar
         value={value}
         onChange={(newValue) => setValue(newValue)}
-        dayOfWeekFormatter={(day) => `${day}.`}
+        dayOfWeekFormatter={(_day, weekday) => `${dayjs(weekday).format('dd')}.`}
```
Comment (flaviendelangle) [inline docs/data/date-pickers/adapters-locale/CustomDayOfWeekFormat.tsx:15]: For me `weekday` is already a `dayjs` object so we don't need to re-parse it.
Do you have issues when removing it?

```suggestion
        dayOfWeekFormatter={(_day, weekday) => `${weekday.format('dd')}.`}
```

File: docs/data/date-pickers/adapters-locale/adapters-locale.md [hunk 4]
```diff
@@ -240,8 +240,8 @@ This prop is available on all pickers.
 ### Custom day of week format
 
 Use `dayOfWeekFormatter` to customize day names in the calendar header.
-This prop takes the short name of the day provided by the date library as an input, and returns it's formatted version.
-The default formatter only keeps the first letter and capitalises it.
+This prop takes the date of the day provided by the date library as an input, and returns a formatted string.
+The default formatter only keeps the first letter of the name and capitalises it.
```
Comment (flaviendelangle) [inline docs/data/date-pickers/adapters-locale/adapters-locale.md:244]: Maybe add a small warning card saying that it also takes the string as it's 1st param but that this one will be removed in v7?

**Comment by michelengelen** [comment]
@alexfauquette could you also take a look here, since @flaviendelangle is on PTO? Thanks! 🙇🏼‍♂️

File: packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.test.tsx [hunk 5]
```diff
@@ -26,6 +26,7 @@ describe('<AdapterDateFns />', () => {
       const adapter = new AdapterDateFns({ locale: enUS });
       const date = adapter.date(TEST_DATE_ISO_STRING)!;
 
+      // TODO@v7: can be removed after v7 release
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.test.tsx:29]: I'm using `TODO v7`
We can reconsider the best comment later, but I think we need to stick to one for this major to be able to get all of them with a single search :+1:

File: packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx [hunk 6]
```diff
@@ -62,11 +63,12 @@ export interface ExportedDayCalendarProps extends ExportedPickersDayProps {
   renderLoading?: () => React.ReactNode;
   /**
    * Formats the day of week displayed in the calendar header.
-   * @param {string} day The day of week provided by the adapter's method `getWeekdays`.
+   * @param {string} day The day of week provided by the adapter.  Deprecated in v7: Use `date` instead.
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/DateCalendar/DayCalendar.tsx:66]:
```suggestion
   * @param {string} day The day of week provided by the adapter.  Deprecated, will be removed in v7: Use `date` instead.
```

**Review by flaviendelangle — COMMENTED** [review]
Looks great :ok_hand:

**Review by flaviendelangle — APPROVED** [review]
Just living a small suggestion for the doc

**Comment by flaviendelangle** [comment]
The build error is weird, I'll have a look if you do not find its root cause

**Review by flaviendelangle — APPROVED** [review]
Great work!

**Comment by michelengelen** [comment]
@flaviendelangle argos seems flaky on this test :/
