### PR TITLE
[DataGrid] Sticky headers

### LINKED ISSUE #4506: [DataGrid] Header scroll lag (especially on mobile devices)
### Current behavior 😯

The DataGrid Header part seems to lag behind user input on touch devices when the Grid is horizontally scrollable. If user input is too 'vigorous'  can cause the header part to be completely misaligned and stuck. I tested it on tablets and phones. It seems a consistent issue, tet seems that smaller devices have more issues. (Phones, 7" tablets). 

https://github.com/mui/mui-x/assets/13808724/7e3c784a-1094-47b6-9236-61fa330c4167

The desktop version is fine.

### Expected behavior 🤔

Should be the same speed.

### Steps to reproduce 🕹

Steps:

1. DataGrid with a horizontal scroll
2. Touch Device input 

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### LINKED ISSUE #5416: [DataGrid] horizontal scrolling doesn't work over column headers
### Current behavior 😯

You can't use horizontal scrolling over column headers via Shift key + scroll wheel or directly with the Mac's trackpad.

[screen recording](https://youtu.be/te9dox2cpHs)

### Expected behavior 🤔

You can use horizontal scrolling over column headers.

image

### Steps to reproduce 🕹

Steps:

1. navigate with your mouse over column headers
2. try horizontal scrolling

### Context 🔦

We have a use case where we want to create a table with columns first and then the data. In this case, we cannot scroll to the part of the table that does not fit into the page.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Used Chrome.

@mui/envinfo doesn't work so here is manually gathered info:

System:
  OS: Windows 10 Pro 21H2 (19044.1415) / Mac OS Monterey (tested both of them)
  Binaries:
    Node: 16.3.0
    Yarn: 1.22.18
    npm: 7.8.0
  Browsers:
    Chrome: 103.0.5060.114
```
</details>

### Order ID 💳 (optional)

48059

### LINKED ISSUE #9646: [DataGrid] Remove the wrapper & `cellV6` and use `cellV7` exclusively
Address the TODO left in `GridCell.tsx` ([context](https://github.com/mui/mui-x/pull/9037#discussion_r1223812088)).

Scope:
- Remove the v6 compatibility layer
- Migration instructions

This issue is included in the scope of https://github.com/mui/mui-x/pull/10059

### LINKED ISSUE #10339: [data grid] VoiceOver (JAWS) reads wrong column / row when using column pinning feature
### Steps to reproduce 🕹

Link to live example:

Steps:
1. navigate to https://mui.com/x/react-data-grid/column-pinning
2. turn on JAWS voiceover
3. turn off virtual PC cursor (insert + z)
4. Navigate to unpinned column

### Current behavior 😯

When navigating the data grid when there is a pinned column, the voiceover utility reads the incorrect row/column number for unpinned columns. For example, when there is one pinned column, navigating to the first  data cell in the second column (first unpinned column), voiceover will read column 1 row 12 (should be column 2 row 2).

### Expected behavior 🤔

Voiceover should read correct row/column number when navigating the grid

### Context 🔦

The context of this issue involves working to bring our implementation of the data grid to meet WCAG AA compliance standards, and to pass VPAT accessibility testing. Current implementation requires a lot of hacking

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

48138

### LINKED ISSUE #10616: [data grid] Decreasing the width of the last column in DataGridPro with pinned columns results in weird behaviour
### Steps to reproduce

Link to live example: https://codesandbox.io/s/dank-darkness-599h6y?file=/Demo.tsx

Steps:
1. Scroll all the way to the right
2. Decrease the width of any column

### Current behavior

When the column size is decreased, while dragging the mouse to adjust the width, the last unpinned column's width stays fixed and a gap appears between the last unpinned column and the first pinned column. After the `mouseup` event, everything gets back into its place and the gap disappears.

### Expected behavior

The last unpinned column's width should be fluid while dragging the mouse and take all the available space, or the pinned columns should move together with the other columns.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.5.2
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    Yarn: 3.5.1 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Edge: Not Found
    Safari: 16.6
  npmPackages:
    @emotion/react: ^11.9.3 => 11.11.1
    @emotion/styled: ^11.9.3 => 11.11.0
    @mui/base:  5.0.0-beta.8
    @mui/core-downloads-tracker:  5.14.1
    @mui/icons-material: ^5.14.1 => 5.14.1
    @mui/lab: ^5.0.0-alpha.137 => 5.0.0-alpha.137
    @mui/material: ^5.14.1 => 5.14.1
    @mui/private-theming:  5.13.7
    @mui/styled-engine:  5.13.2
    @mui/system: ^5.14.1 => 5.14.1
    @mui/types:  7.2.4
    @mui/utils:  5.14.1
    @mui/x-data-grid:  6.13.0
    @mui/x-data-grid-pro: ^6.10.1 => 6.13.0
    @mui/x-license-pro:  6.10.2
    @types/react: ~17.0.2 => 17.0.62
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    typescript: ~4.9.4 => 4.9.5
```
</details>

**Search keywords**: resizing width pinned
**Order ID**: 53911

### LINKED ISSUE #11691: [question] Problems with Pinned columns hover delay
### The problem in depth

https://github.com/mui/mui-x/assets/100214450/0297af2d-78a7-41d0-8339-22e84755fa5d

As we can see on the pinning columns official demos, after reproduce the video in 0.25x. Demo url: https://mui.com/x/react-data-grid/column-pinning/#blocking-column-unpinning

When the user makes hover over the rows, the pinned columns have some delay to change the background color. This happens in the official demos, and when we are using more complex data-grids this bugs are more evident.

https://github.com/mui/mui-x/assets/100214450/b189f9c3-873c-4fc1-9e16-cffc54b11daf

Is this a known bug? 

Its there any workaround to avoid this behavior? 

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 14.2.1
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 120.0.6099.109
    Edge: Not Found
    Safari: 17.2.1
  npmPackages:
    @emotion/react:  11.11.1 
    @emotion/styled:  11.11.0 
    @mui/base:  5.0.0-beta.16 
    @mui/core-downloads-tracker:  5.14.10 
    @mui/icons-material:  5.14.9 
    @mui/lab:  5.0.0-alpha.145 
    @mui/material:  5.14.10 
    @mui/private-theming:  5.14.10 
    @mui/styled-engine:  5.14.10 
    @mui/styled-engine-sc:  5.14.10 
    @mui/system:  5.14.10 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.10 
    @mui/x-data-grid:  6.18.4 
    @mui/x-data-grid-generator:  6.18.4 
    @mui/x-data-grid-premium:  6.18.4 
    @mui/x-data-grid-pro:  6.18.4 
    @mui/x-date-pickers:  5.0.20 
    @mui/x-date-pickers-pro:  5.0.20 
    @mui/x-license-pro:  6.10.2 
    @mui/x-tree-view:  6.0.0-alpha.1 
    @types/react:  18.2.22 
    react:  18.2.0 
    react-dom:  18.2.0 
    typescript:  4.9.5 
```
</details>

**Search keywords**: pinned columns hover delay
**Order ID**: 74611

### PR DESCRIPTION
**Pull request by romgrk**
Closes #4506
Closes #9646
Closes #5416
Closes #10616
Closes #10339
Closes #11214
Closes #11215
Closes #9502
Closes #11691 

Implement `position: sticky` grid headers. It's based on the work in #9589.

Preview: https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/#commercial-versions

### Before

header tearing, header not responding to scroll intent, white screen areas

https://github.com/mui/mui-x/assets/3165635/766a578e-cd8e-4f85-af78-ddfd0a4fd469

### After 

no header tearing, header responding to scroll intent, trade no white screen areas for scrollbar tearing

https://github.com/mui/mui-x/assets/3165635/ca51d45d-c4cb-46ba-afe4-1d42237d86b4

---

Stuff that needs to change:
 - [x] DOM structure
 - [x] Fake scrollbars
 - [x] Header scrolling logic

Remaining tasks:
 - [x] Remove transparency in colors (was set for development purposes)
 - [x] Styles for pinned+hover, pinned+selected and pinned+hover+selected
 - [x] The skipped test with a `XXX:` note
 - [x] Discuss & agree on how to expose colors publicly (pinned background, header background)
     => We use the colors from the theme.
 - [x] Do a performance check again (memoization is easy to disrupt)
 - [x] Resizing is not working properly

### CODE REVIEW

**Comment by romgrk** [comment]
> At least, as a developer, I don't mind the pain to customize this, in exchange of the smoother UX.

Fair point, I agree it's a very minor change. The DOM change is the one that might require a major release though, we've been considering the DOM as a public API in the other discussions I've seen.

File: packages/grid/x-data-grid/src/components/DataGridVirtualScroller.tsx [hunk 1]
```diff
@@ -4,24 +4,30 @@ import { GridVirtualScrollerContent } from './virtualization/GridVirtualScroller
...
     const { getRootProps, getContentProps, getRenderZoneProps, getRows } = useGridVirtualScroller({
       ref,
       disableVirtualization,
     });
 
+    const contentProps = getContentProps();
+
     return (
       <GridVirtualScroller className={className} {...getRootProps(other)}>
+        <GridHeaders contentProps={contentProps} ColumnHeadersProps={ColumnHeadersProps} />
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/DataGridVirtualScroller.tsx:28]: The cell keyboard navigation will need to take the header height into account. Currently, the focused cell hides below the fold:

https://github.com/mui/mui-x/assets/13808724/dfe6bbba-4dda-474b-80f0-3a2103bc758e

File: packages/grid/x-data-grid/src/components/columnHeaders/GridBaseColumnHeaders.tsx [hunk 2]
```diff
@@ -23,8 +23,9 @@ const GridColumnHeadersRoot = styled('div', {
   slot: 'ColumnHeaders',
   overridesResolver: (props, styles) => styles.columnHeaders,
 })<{ ownerState: OwnerState }>({
-  position: 'relative',
-  overflow: 'hidden',
+  position: 'sticky',
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/columnHeaders/GridBaseColumnHeaders.tsx:26]: This is conflicting with row pinning, which also uses `position: sticky` 🤔
https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/row-pinning/

https://github.com/mui/mui-x/assets/13808724/6cfa8a94-66f0-44ec-8e9d-13cfae81dcf5

File: packages/grid/x-data-grid/src/components/columnHeaders/GridBaseColumnHeaders.tsx [hunk 3]
```diff
@@ -23,8 +23,9 @@ const GridColumnHeadersRoot = styled('div', {
...
+  top: 0,
+  zIndex: 2,
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/columnHeaders/GridBaseColumnHeaders.tsx:28]: Should be at least 3 to stay above the detail panel content:
https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/master-detail/

https://github.com/mui/mui-x/assets/13808724/d6e6e2b5-7ee2-48c2-b9c8-763183283082

File: packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx [hunk 4]
```diff
@@ -387,6 +387,7 @@ const DataGridProVirtualScroller = React.forwardRef<
 
   return (
     <GridVirtualScroller {...getRootProps(other)}>
+      <GridHeaders contentProps={contentProps} ColumnHeadersProps={ColumnHeadersProps} />
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/components/DataGridProVirtualScroller.tsx:390]: Column resizing regressed a bit because of the DOM structure change:
https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/column-dimensions/#resizing

https://github.com/mui/mui-x/assets/13808724/a78ca03d-0c58-45d4-9bb2-c2f62b9f8884

**Review by cherniavskii — COMMENTED** [review]
Feels much better on mobile 👍


https://github.com/mui/mui-x/assets/13808724/47594599-2cc3-418f-a34e-f5f09c135f11

**Comment by cherniavskii** [comment]
Regarding the DOM structure breaking change - fair point, it was a breaking change even for us internally 😅 - see https://github.com/mui/mui-x/pull/10059#discussion_r1297343965
We should release it in v7, although we can keep working on it to make sure it's ready for v7

**Comment by romgrk** [comment]
@cherniavskii Don't review now, not ready yet. I opened the PR so we can discuss how/when to release, considering the changes that need to happen.

**Comment by cherniavskii** [comment]
> When is v7 release? March? I'd probably start work on this around December then. Otherwise we might lose time on conflicts that might happen by then.

Do you think the sticky column header is still feasible given https://github.com/mui/mui-x/pull/10059#discussion_r1297330446 ?

**Comment by romgrk** [comment]
> Do you think the sticky column header is still feasible given https://github.com/mui/mui-x/pull/10059#discussion_r1297330446 ?

Yes, we can sticky those after the header programatically, or place them inside the same container as the header.

File: packages/grid/x-data-grid/src/components/base/GridBody.tsx [hunk 5]
```diff
@@ -147,25 +85,6 @@ function GridBody(props: GridBodyProps) {
 
   return (
     <GridMainContainer ref={rootRef}>
-      <rootProps.slots.columnHeaders
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/base/GridBody.tsx:150]: With column headers moved to the virtual scroller, it will be possible to make individual header cells sticky during horizontal scroll 👍🏻

https://github.com/mui/mui-x/assets/13808724/24c43a03-a090-42a5-ba33-a8da9e5426f9

This might be especially helpful with multi-column pivoting to make the column group structure clearer (see demo without sticky headers https://codesandbox.io/s/trusting-shtern-6tg36d

```diff
diff --git a/docs/data/data-grid/column-groups/BasicGroupingDemo.tsx b/docs/data/data-grid/column-groups/BasicGroupingDemo.tsx
index ea48cee7d..35b58e13e 100644
--- a/docs/data/data-grid/column-groups/BasicGroupingDemo.tsx
+++ b/docs/data/data-grid/column-groups/BasicGroupingDemo.tsx
@@ -6,18 +6,18 @@ const columns: GridColDef[] = [
   {
     field: 'firstName',
     headerName: 'First name',
-    width: 150,
+    width: 550,
   },
   {
     field: 'lastName',
     headerName: 'Last name',
-    width: 150,
+    width: 550,
   },
   {
     field: 'age',
     headerName: 'Age',
     type: 'number',
-    width: 110,
+    width: 550,
   },
 ];
 
@@ -61,6 +61,15 @@ export default function BasicGroupingDemo() {
         checkboxSelection
         disableRowSelectionOnClick
         columnGroupingModel={columnGroupingModel}
+        sx={{
+          '& .MuiDataGrid-columnHeaderTitleContainer': {
+            overflow: 'visible',
+          },
+          '& .MuiDataGrid-columnHeaderTitleContainerContent': {
+            position: 'sticky',
+            left: 8,
+          },
+        }}
       />
     </div>
   );

```

**Comment by romgrk** [comment]
Alright, so the initial implementation of the change is complete. The diff is huge but there is no way to split this into multiple PRs, the changes are too fundamental to split it cleanly like it was possible for e.g. the filter PRs. I've also left out some more refactoring & simplification that could be done to avoid increasing the size of this PR.

Here is a summary of the changes.

## API state changes

These are changes to the `apiRef.current.state`.

1. Elements refs like `rootElementRef` and `virtualScrollerElementRef` are non-nullable and defined in `useGridRefs`.
2. `dimensions: GridDimensions` has been added and expanded. It's now meant to contain all layout & dimensions calculations, no one else should be mathing layout stuff except `useGridDimensions`.
3. To match pinned rows, the state for pinned columns now exists in the community package. The logic still lives in pro. This is done so we can use pinned columns' state in layout calculations.
4. Previously, the visible pinned columns were re-derived at multiple locations with the `filterColumns` function. Now, the function is private and the visible pinned columns are derived once.
5. Previously, the virtual scroller was returning the raw render context with `apiRef.current.getRenderContext` and exporting the `getRenderableIndexes` function, and multiple locations were re-deriving the real render context. Now, it exposes the real render context directly. That function is not private yet but will be when I refactor the headers code in a subsequent PR.

## DOM & CSS changes:

1. GridBody == GridVirtualScroller, “main” element is now the scroller container, which looks like this:

```html
<Scroller>
   <Content>
      <Headers />
      <Row />
      <Row />
      <DetailPanel />
      <Row />
      <!-- ... -->
   </Content>
   <Scrollbar horizontal />
   <Scrollbar vertical />
</Scroller>
```

2. A row is now a single element which contains all its rendered columns. Pinned ones are `sticky`:
```html
<Row>
   <!-- Left pinned columns -->
   <Cell pinned="left" />
   <Cell pinned="left" />
   <!-- Non-pinned columns -->
   <Cell />
   <Cell />
   <Cell />
   <!-- Right pinned columns -->
   <Cell pinned="right" />
   <Cell pinned="right" />
</Row>
```

3. I have added quite a few CSS variables on the root element. Those are used by the various elements (rows, fake scrollbars, columns) to place themselves where they should be. See `GridRootStyles.ts` for more details.

**Review by cherniavskii — COMMENTED** [review]
Great work! Excited to see these changes coming to the data grid! 🎉

Leaving some early feedback below 🙂

File: docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx [hunk 6]
```diff
@@ -26,12 +26,12 @@ function DetailPanelContent({ row: rowProp }: { row: Customer }) {
   const apiRef = useGridApiContext();
   const [width, setWidth] = React.useState(() => {
```
[the remark this answers is not in the document]
Comment (romgrk) [reply docs/data/data-grid/master-detail/FullWidthDetailPanel.tsx:27]: Lol this behavior isn't even intentional. It's just behaving that way without me having done anything in particular to make it so :sweat_smile:

**Comment by oliviertassinari** [comment]
> Fake scrollbars

Thoughts on this. Once the laptop you have doesn't have enough processing power to respond to each JavaScript event within 8ms (120Hz screen), you will feel a scrollbar lag:

https://github.com/mui/mui-x/assets/3165635/7ac5d7ee-5785-462f-92d2-3579232682d5

So for people who are using the scrollbar to navigate the list (and not the trackpad or the mouse scroll wheel), this effectively means that we trade header tearing for scrollbar tearing (by tearing I mean similar to https://steemit.com/screen/@cryptobur/how-to-prevent-annoying-screen-tearing-in-chrome).

To be fair: 1. on AG Grid, they get both, scrollbar and header tearing 🙈, 2. scrollbar tearing is better than header tearing, for example, on mobile there is no scrollbar, so it feels much smoother 👌.

Now, I'm curious, what's the advantage of having a fake scrollbar? I mean, why is position sticky with a regular scroll container not possible? (taking advantage of hardware acceleration, no JS runtime involved)

**Comment by romgrk** [comment]
Yeah no idea why ag-grid doesn't use sticky, they'd get a better experience.

The reason for fake scrollbars is that real scrollbars + sticky means the vertical scrollbar goes up all the way to the top of the headers, instead of being limited to the cells area, and this changes the design and is uglier:



The other point in favor of fake scrollbars is that when scrolling with the scrollbar, we can delay updating the actual viewport position until after rendering, so there is no more white areas. The vertical scroll with fake scrollbar feels a bit nicer this way.

One thing that we could do is use a real scrollbar for horizontal, and a fake one for vertical. In general, vertical scroll tearing isn't as apparent as horizontal because the scrollbar thumb is much smaller. Please comment on this idea.

**Comment by oliviertassinari** [comment]
On https://github.com/okonet/react-scroll-sync, there is no scrollbar tearing even at x6 CPU slowdown. They use a continue request animation frame to update the scrollbars. Maybe there is something there that we could use to improve the performance (we use onScroll right now)

**Comment by wieseljonas** [comment]
I think you need to lock horizontal or vertical scrolling depending on the direction on mobile. Just like google maps. This and performance is the only thing stopping us from migrating fully to the grid.

https://github.com/mui/mui-x/assets/1095469/a90d4b90-96df-4c41-a3eb-139a2936716a

**Comment by lauri865** [comment]
> > The reason for fake scrollbars is that real scrollbars + sticky means the vertical scrollbar goes up all the way to the top of the headers, instead of being limited to the cells area, and this changes the design and is uglier:
> 
> @romgrk Ah right, fake scrollbar much needed 👍. In this case, the question is how to make the scroll sync feel more fluid.
> 
> On https://github.com/okonet/react-scroll-sync, there is no scrollbar tearing even at x6 CPU slowdown. They use a continuous request animation frame to update the scrollbars.
> 
> So maybe there is something that we could do to improve the tearing (maybe onScroll isn't the best, etc.)

Can't wait for this release, amazing work! 💪👊

What if instead of having a single scrollable container, making the headers and body independently scrollable (while hiding the scrollbar for the headers), and using the techniques in `react-scroll-sync` to sync the scroll between the two? Then you end up with native scrollbars that are positioned nicely, and don't have to go through the hassle of creating fake scrollbars.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 7]
```diff
@@ -128,7 +128,28 @@ export const GridRootStyles = styled('div', {
     '--unstable_DataGrid-overlayBackground': theme.vars
       ? `rgba(${theme.vars.palette.background.defaultChannel} / ${theme.vars.palette.action.disabledOpacity})`
       : alpha(theme.palette.background.default, theme.palette.action.disabledOpacity),
+    '--unstable_DataGrid-containerBackground': theme.vars
+      ? `rgba(${theme.vars.palette.background.defaultChannel} / 0.8)`
+      : alpha(theme.palette.background.default, 0.8),
```
Comment (oliviertassinari) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:133]: I think that this is clearly too transparent, preventing to read the header's content with enough contrast. 

This feels better:
```suggestion
      : alpha(theme.palette.background.default, 0.95),
```

Before
Screenshot 2023-11-27 at 21 27 55

After
Screenshot 2023-11-27 at 21 27 45

But I'm not sure, no transparency at all might be for the best. I have tried to play with `backdrop-filter: blur(xpx);` as well but I can't find anything that feel better than having no transparency.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 8]
```diff
@@ -128,7 +128,28 @@ export const GridRootStyles = styled('div', {
     '--unstable_DataGrid-overlayBackground': theme.vars
       ? `rgba(${theme.vars.palette.background.defaultChannel} / ${theme.vars.palette.action.disabledOpacity})`
       : alpha(theme.palette.background.default, theme.palette.action.disabledOpacity),
+    '--unstable_DataGrid-containerBackground': theme.vars
+      ? `rgba(${theme.vars.palette.background.defaultChannel} / 0.8)`
```
Comment (oliviertassinari) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:132]: if we use the space notation, then?

```suggestion
      ? `rgb(${theme.vars.palette.background.defaultChannel} / 0.8)`
```

**Comment by oliviertassinari** [comment]
> I think you need to lock horizontal or vertical scrolling depending on the direction on mobile. Just like google sheets. 

@wieseljonas Google Sheet's app on Android allows you to scroll both horizontally and vertically at the same time. However, Notion, Airtable, AG Grid indeed only let you scroll in one direction at the time on mobile. 

on iOS this is configured with https://developer.apple.com/documentation/uikit/uiscrollview/1619390-directionallockenabled. I could find https://stackoverflow.com/questions/58190439/dont-allow-horizontal-scroll-when-scrolling-vertically-and-vice-versa on the matter.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 7 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:133]: Yeah this is just testing values so I can better see what's going on. I haven't finalized the colors, I was planning on making it opaque to preserve the design as it is, but some transparency can make it look a bit more modern.

**Comment by romgrk** [comment]
I think properly implemented single direction scroll lock has UX & performance advantages but it's indeed a different feature, the scope of this PR is big enough already.

**Comment by oliviertassinari** [comment]
Discussion on scroll moved to #11230.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 9]
```diff
@@ -356,15 +378,29 @@ export const GridRootStyles = styled('div', {
...
+    },
     [`& .${gridClasses.cell}`]: {
       display: 'flex',
       alignItems: 'center',
+      '--width': '0px',
+      '--height': '0px',
+      minWidth: 'var(--width)',
+      maxWidth: 'var(--width)',
+      minHeight: 'var(--height)',
+      maxHeight: 'var(--height)',
```
Comment (oliviertassinari) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:397]: I never understood why Damien didn't simply do

```suggestion
      width: 'var(--width)',
      height: 'var(--height)',
```

**Comment by MBilalShafi** [comment]
Probably related to the already under discussion problem of adding background-color to the headers, the difference in grid background and headers one more visible in the dark mode (more noticeable with more header rows)
side-sticky

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 7 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:133]: Argument against transparency: we need to display more rows on screen and it will affect performance a bit.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 9 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts]: Done

**Comment by romgrk** [comment]
This is ready for review. Some notes:
- We make use of CSS variables much more extensively now. The root-level ones are named `--DataGrid-xxxx`. The ones in the format `--xxxx` are usually local to a specific component, e.g. `--width` on cells.
- All root-level variables are initialized in `GridRootStyles`.
- I've added testing helpers `$` and `$$`, which are straightforward.
- I've added testing helper `grid()`: replace `document.querySelector<HTMLElement>(`.${gridClasses['cell--pinnedLeft']}`)` with `grid('cell--pinnedLeft')`. It's typed so it autocompletes nicely. I've only replaced it in some tests I modified. We can continue replacing gradually.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 10]
```diff
@@ -356,15 +389,33 @@ export const GridRootStyles = styled('div', {
         },
       },
     },
+    [`& .${gridClasses['container--top']}, & .${gridClasses['container--bottom']}`]: {
+      '[role=row]': {
+        background: 'var(--unstable_DataGrid-containerBackground)',
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:394]: Rows in the column header should have `minWidth: 100%`:

File: packages/grid/x-data-grid-pro/src/components/GridDetailPanel.tsx [hunk 11]
```diff
@@ -13,30 +13,25 @@ const DetailPanel = styled(Box, {
   slot: 'DetailPanel',
   overridesResolver: (props, styles) => styles.detailPanel,
 })<{ ownerState: OwnerState }>(({ theme }) => ({
-  zIndex: 2,
   width: '100%',
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/components/GridDetailPanel.tsx:16]: 100% now means "as wide as the virtual scroller content" instead of "as wide as the grid".
The detail panel should have the same width as `MuiDataGrid-virtualScrollerContent`, and if its content exceeds that width - the detail panel should be scrollable horizontally:

https://codesandbox.io/p/sandbox/loving-ramanujan-2qnn87

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 12]
```diff
@@ -490,6 +564,15 @@ export const GridRootStyles = styled('div', {
...
       },
     },
+    [`& .${gridClasses['row--lastVisible']}`]: {
+      minHeight: 'unset !important',
+      maxHeight: 'unset !important',
+    },
+    [`& .${gridClasses['row--lastVisible']} .${gridClasses.cell}`]: {
+      width: 'var(--width)',
+      height: 'calc(var(--height) + var(--DataGrid-hasScrollX) * var(--DataGrid-scrollbarSize))',
+      paddingBottom: 'calc(var(--DataGrid-hasScrollX) * var(--DataGrid-scrollbarSize))',
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:574]: Why should the last row have different bottom padding?
https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/demo/

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 13]
```diff
@@ -1,7 +1,6 @@
 import * as React from 'react';
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:1]: It looks like there's no column virtualization anymore, you can see the performance taking a hit in https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/virtualization/#column-virtualization

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 12 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:574]: Initially, there was the logic to add padding to the last column so it stretched to occupy the space of the vertical scrollbar:

image

So when I added the fake vertical scrollbars, the cells got the same padding to fill the space they now need to fill, because the scrollbar floats in front of the whole grid. Then when I added the horizontal scrollbar, I used the same logic to space thing.

I could look for other options to fill the space if there are unsolvable problems with that approach.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 10 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:394]: Where is this example?

File: packages/grid/x-data-grid-pro/src/components/GridDetailPanel.tsx (hunk 11 above)
Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/components/GridDetailPanel.tsx]: I've implemented the behavior you describe here, but there's one test that seems to be different than what I understand this needs to be. Can you validate if the behavior is ok? There's a `@cherniavskii` tag in the test in question.

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx (hunk 13 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:1]: Forgot to reenable it after making changes :| It's back in.

File: packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts [hunk 14]
```diff
@@ -16,179 +17,118 @@ import { useGridApiMethod } from '../../utils/useGridApiMethod';
...
-  const fullDimensionsRef = React.useRef<GridDimensions | null>(null);
+  const rootDimensionsRef = React.useRef(EMPTY_SIZE);
   const rowsMeta = useGridSelector(apiRef, gridRowsMetaSelector);
+  const pinnedColumns = useGridSelector(apiRef, gridVisiblePinnedColumnDefinitionsSelector);
   const densityFactor = useGridSelector(apiRef, gridDensityFactorSelector);
   const rowHeight = Math.floor(props.rowHeight * densityFactor);
-  const totalHeaderHeight = getTotalHeaderHeight(apiRef, props.columnHeaderHeight);
+  const headerHeight = Math.floor(props.columnHeaderHeight * densityFactor);
+  const columnsTotalWidth = roundToDecimalPlaces(gridColumnsTotalWidthSelector(apiRef), 6);
+  const hasHeaderFilters = Boolean((props as any).unstable_headerFilters); // XXX: this is kinda unsafe
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts:90]: This will break with the PR to stabilize these.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 15]
```diff
@@ -272,245 +340,310 @@ export const GridRootStyles = styled('div', {
...
+    f(backgroundColor.values[0], overlayColor.values[0]),
+    f(backgroundColor.values[1], overlayColor.values[1]),
+    f(backgroundColor.values[2], overlayColor.values[2]),
+  ] as const;
+
+  return recomposeColor({
+    type: 'rgb',
+    values: rgb as any,
+  });
+}
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:649]: This should probably go in the core's `colorManipulator.js`, but it would delay this PR to wait for it so I'll move it there after we merge this.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 10 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts]: This one: https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/filtering/

But it's reproducible in any demo that has vertical scroll and the column total width smaller than the grid width

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx (hunk 13 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:1]: Now we're talking! 🚀

File: packages/grid/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx [hunk 16]
```diff
@@ -117,117 +123,6 @@ describe('<DataGridPro /> - Column pinning', () => {
...
-
-    const checkbox = cell.querySelector('input[type="checkbox"]')!;
-    fireEvent.click(checkbox);
-    fireEvent.click(checkbox);
-    expect(leftColumns!.querySelector('[data-rowindex="0"]')).to.have.class('Mui-hovered');
-    expect(rightColumns!.querySelector('[data-rowindex="0"]')).to.have.class('Mui-hovered');
-    expect(renderZone!.querySelector('[data-rowindex="0"]')).to.have.class('Mui-hovered');
-  });
-
-  it('should update the render zone offset after resize', function test() {
```
Comment (romgrk) [inline packages/grid/x-data-grid-pro/src/tests/columnPinning.DataGridPro.test.tsx:179]: Restore

File: packages/grid/x-data-grid-pro/src/components/GridDetailPanel.tsx (hunk 11 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/components/GridDetailPanel.tsx]: My previous content was wrong.
The detail panel should actually be "as wide as the virtual scroller content", not "as wide as the grid".
But it should not exceed the total column width (which was the case when I added this comment).
Sorry for the confusion!

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 12 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:599]: > So when I added the fake vertical scrollbars, the cells got the same padding to fill the space they now need to fill, because the scrollbar floats in front of the whole grid.

Does this mean, that the last row should always have the bottom padding?

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 17]
```diff
@@ -100,117 +101,80 @@ export const areRenderContextsEqual = (
...
+
+export const EMPTY_DETAIL_PANELS = Object.freeze(new Map<GridRowId, React.ReactNode>());
 
-// The `maxSize` is 3 so that reselect caches the `renderedColumns` values for the pinned left,
-// unpinned, and pinned right sections.
-const MEMOIZE_OPTIONS = { maxSize: 3 };
+export type VirtualScroller = ReturnType<typeof useGridVirtualScroller>;
 
-export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
+export const useGridVirtualScroller = () => {
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:120]: I've noticed column headers jump and misalignment that seem to be caused by column virtualization:
https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/performance/#visualization


https://github.com/mui/mui-x/assets/13808724/c706def2-1e8c-4690-aa67-1ab31b197d3b

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:120]: In this demo, the column headers offset persists (the number in the column header should match the second number in the cell): https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/virtualization/#column-virtualization

Screenshot 2023-12-05 at 17 39 44

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 12 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:599]: Yeah right now it needs bottom padding.

One alternative could be that the bottom scrollbar space is filled with a filler div instead. But I'd keep the right scrollbar space filled with padding, because it's not possible to fill it cleanly with a single div (there would need to be one div inside each row that needs padding).

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx (hunk 17 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:120]: The header border is also not stretching and goes away when scrolling horizontally.

File: packages/grid/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx
Comment (romgrk) [inline packages/grid/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx:1]: There is a gap at the intersection of the scrollbars:

image

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 18]
```diff
@@ -37,174 +45,238 @@ export const GridRootStyles = styled('div', {
...
+  const pinnedBackground =
+    t.palette.mode === 'dark'
+      ? lighten(
+          t.vars ? t.vars.palette.background.defaultChannel : t.palette.background.default,
+          0.1,
+        )
+      : darken(
+          t.vars ? t.vars.palette.background.defaultChannel : t.palette.background.default,
+          0.05,
+        );
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:143]: The header background, which now needs a solid background color, is from the palette's background color. The pinned cells' background is derived from the same value, but lightened or darkened.

I'm not sure what's the best way to make the pinned background customizable with this setup, suggestions welcome.

**Comment by MBilalShafi** [comment]
It's an amazing feeling to experiment with the new version. Looks like a massive improvement.

A couple of possible improvements I spotted.

1. The scrollbar no longer appears (MacOS) unless the scroll bar is set to show _Always_ in system settings.

**Before & after:**
before after

2. Separator feels a bit less reachable:

Before and after:
before-separator after-separator

File: packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts [hunk 19]
```diff
@@ -379,6 +410,8 @@ export const createColumnsState = ({
     });
   }
 
+  columnsState = updatePinnedColumns(columnsState as GridColumnsState, theme);
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts:413]: Pinning the checkbox selection column acts weird:



Here's a minimal repro (couldn't link the codesandbox because CSCI has failed):

```tsx
import * as React from 'react';
import { DataGridPro, GRID_CHECKBOX_SELECTION_FIELD } from '@mui/x-data-grid-pro';
import { useDemoData } from '@mui/x-data-grid-generator';

export default function Demo() {
  const { data } = useDemoData({
    dataSet: 'Commodity',
    rowLength: 100,
    maxColumns: 20,
  });

  return (
    <div style={{ height: 600 }}>
      <DataGridPro
        {...data}
        checkboxSelection
        initialState={{
          pinnedColumns: { left: [GRID_CHECKBOX_SELECTION_FIELD, 'desk'] },
        }}
      />
    </div>
  );
}
```

I looked into it and this diff solves the issue:

```diff
diff --git a/packages/grid/x-data-grid-pro/src/hooks/features/columnPinning/useGridColumnPinningPreProcessors.ts b/packages/grid/x-data-grid-pro/src/hooks/features/columnPinning/useGridColumnPinningPreProcessors.ts
index 7c92b7890..1ab69aaea 100644
--- a/packages/grid/x-data-grid-pro/src/hooks/features/columnPinning/useGridColumnPinningPreProcessors.ts
+++ b/packages/grid/x-data-grid-pro/src/hooks/features/columnPinning/useGridColumnPinningPreProcessors.ts
@@ -5,7 +5,11 @@ import {
   gridPinnedColumnsSelector,
   useGridRegisterPipeProcessor,
   eslintUseValue,
+  updatePinnedColumns,
+  gridVisibleColumnFieldsSelector,
 } from '@mui/x-data-grid/internals';
+import { useTheme } from '@mui/material/styles';
+import { GridColumnsState } from '@mui/x-data-grid';
 import { DataGridProProcessedProps } from '../../../models/dataGridProProps';
 import { GridPrivateApiPro } from '../../../models/gridApiPro';
 
@@ -24,10 +28,14 @@ export const useGridColumnPinningPreProcessors = (
 
   const prevAllPinnedColumns = React.useRef<string[]>([]);
 
+  const theme = useTheme();
+
   const reorderPinnedColumns = React.useCallback<GridPipeProcessor<'hydrateColumns'>>(
     (columnsState) => {
       eslintUseValue(pinnedColumns);
 
+      columnsState = updatePinnedColumns(columnsState as GridColumnsState, theme);
+
       if (columnsState.orderedFields.length === 0 || disableColumnPinning) {
         return columnsState;
       }
diff --git a/packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts b/packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts
index f5491e730..505e5e2a8 100644
--- a/packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts
+++ b/packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts
@@ -410,8 +410,6 @@ export const createColumnsState = ({
     });
   }
 
-  columnsState = updatePinnedColumns(columnsState as GridColumnsState, theme);
-
   const columnsStateWithPreProcessing = apiRef.current.unstable_applyPipeProcessors(
     'hydrateColumns',
     columnsState,

```

The difference is that the `columnsState` in `hydrateColumns` includes the `__check__` column in the visible columns lookup.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 18 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:143]: What are the reasons for a different bgcolor for pinned columns?
I would favor using the same bgcolor for pinned and non-pinned columns. The shadow that indicates the pinned columns should be enough.

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx (hunk 17 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:120]: Yes, I tried to show this on the video, but didn't mention it as it seemed like a minor issue in this context 😀

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 12 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:599]: A filler div for the horizontal scroll bar sounds like a better option to me!
This would also make the bottom cell outline in the last row visible:



It's a minor thing, but still 🙂

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 18 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:143]: I've used the docs as my reference to restore the design after I do changes:
image

But I just noticed that light theme doesn't differentiate. I never use light theme.

File: packages/grid/x-data-grid-pro/src/components/GridDetailPanel.tsx (hunk 11 above)
Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/components/GridDetailPanel.tsx]: Makes sense, it's possible to implement the viewport-width behavior if we leave it as it is. But it wouldn't be possible to have row-width panels if we do viewport-width. It's restored.

File: packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx:1]: It's an amazing feeling to experiment with the new version. Looks like a massive improvement.

A couple of possible improvements I spotted.

1. The scrollbar no longer appears (MacOS) unless the scroll bar is set to show _Always_ in system settings.

**Before & after:**
before after

2. Separator feels a bit less reachable:

**Before and after:**
before-separator after-separator

3. Header filter keyboard navigation seems to have a small regression

**Before and after:**
before-hf after-hf

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 18 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:143]: This is out of the scope of this PR, but this reminds me of the discussion we had in https://github.com/mui/mui-x/issues/5979#issuecomment-1235812999
I feel like using the same bg color for pinned columns (in both light and dark modes) looks better, as long as we use a thicker border or a shadow to mark the boundaries between pinned/unpinned columns - see https://www.figma.com/proto/W6TItYkiGJZjL5zLnfeSjy/Data-grid?node-id=511-25798&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=501%3A31128

File: packages/grid/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx:1]: It's not the case on MacOS:

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx [hunk 20]
```diff
@@ -681,13 +322,21 @@ const GridCellV7 = React.forwardRef<HTMLDivElement, GridCellV7Props>((props, ref
       };
     }
     const cellStyle = {
-      minWidth: width,
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/cell/GridCell.tsx:684]: I think I just discovered the reason for `minWidth` here - it's for column resizing:


https://github.com/mui/mui-x/assets/13808724/00a03754-d33d-4898-a473-d9443dfb35ee

File: packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx:1]: Yes sure, thanks

File: packages/grid/x-data-grid-pro/src/components/GridColumnHeaders.tsx [hunk 21]
```diff
@@ -49,61 +47,51 @@ const useUtilityClasses = (ownerState: OwnerState) => {
...
-              '#fff',
-              getOverlayAlpha(2),
-            )})`,
-          }),
+    backgroundColor: 'var(--DataGrid-pinnedBackground)',
+    ...(ownerState.side === GridPinnedColumnPosition.LEFT && { left: 0 }),
+    ...(ownerState.side === GridPinnedColumnPosition.RIGHT && { right: 0 }),
+    [`&.${gridClasses['pinnedColumnHeaders--left']}`]: {
+      left: 0,
+      width: 'var(--DataGrid-leftPinnedWidth)',
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/components/GridColumnHeaders.tsx:76]: Is the width necessary here?

https://github.com/mui/mui-x/assets/13808724/51470117-6551-4d4d-92ee-e20659e479c4

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 18 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:143]: Sounds good for using the same color for pinned rows. The shadow styles are broken right now anyway, I need to work on that. Do we have a preference?

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 12 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts]: Ok this is fixed with the spacers, which is indeed better, but wow this took all day and I have a renewed hate for our styling solution and for CSS in general.

File: packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts (hunk 19 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts]: I found other underlying issues with pinning, I implemented a fix but I'm horrified by it :| Left a comment about `renderContext` & pinning.

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:1]: There is a kinda big change here, due to an architectural issue with `renderContext` and other parts of the state (pinning among others).

To make it simple, the `renderContext` is in essence a value derived from some of the grid's state (viewport size, pinned columns, buffer props, ...). But it was stored in a `useState` hook, unlike the rest of the grid state. So if we updated it with a `useEffect` on a value from `useGridSelector`, there could be one render cycle before the `renderContext` would be in sync with the rest of the state.

The solution was to lift up `renderContext` in the grid state, but this was super messy to do inside a hook, because there were lots of deps to each function needed to compute the context. So I extracted everything into a pure function outside the hook. Looks weird, works great.

**Comment by romgrk** [comment]
Status: not getting merged this week :|

Remaining points:
 - pinned stuff styling (background, box-shadows)
 - make resizing work
 - keyboard navigation regression
 - finish `renderContext` refactor

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:1]: > To make it simple, the renderContext is in essence a value derived from some of the grid's state (viewport size, pinned columns, buffer props, ...). But it was stored in a useState hook, unlike the rest of the grid state. So if we updated it with a useEffect on a value from useGridSelector, there could be one render cycle before the renderContext would be in sync with the rest of the state.

If it's derived from the grid's state, could it be removed from the state and derived during the rendering?

Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:1]: I know react's advice is to derive during rendering in general, but for a state slice that is complex to derive it's more messy to derive it multiple times than to just derive it once and store it. There's also the fact that a lot of our reactivity model is now based around `useGridSelector`, which re-renders when the selected slice of the state has changed. With `renderContext` in there, updating in response to a change is now as simple as using:
```js
const renderContext = useGridSelector(apiRef, gridRenderContextSelector)
// and that's always going to stay in sync with the 
const pinnedColumns = useGridSelector(...)
// in the next line. 
```
And it's easier for our mental model to do things always the same way. I've also added a selector that only selects the render context columns, so the headers can change only when that part changes.

There is a similar change to that for `dimensions`, where we do the layout computations once in `.updateDimensions` and then everyone is free of doing any layout math—and it's also good because the dimensions/layout doesn't change while the user uses the grid. Here again we can `useGridSelector(apiRef, gridDimensionsSelector)` to get reactivity easily instead of using a combination of `apiRef.current.getRootDimensions()` and events/callbacks.

There is also a similar change for `visiblePinnedColumns`. Because we didn't have that state derived in the grid-state, we needed to derive everything verbosely everytime:
```js
      const [leftPinnedColumns, rightPinnedColumns] = filterColumns(
        pinnedColumns,
        visibleColumnFields,
        theme.direction === 'rtl',
      );
```
This above also introduced a dependency on `theme` everywhere that needed the pinned columns. Now, we can just depend on the `visiblePinnedColumns` selector.

### Reactivity & useGridSelector

One thing I'll admit is that event-based reactivity (e.g. `.publishEvent('rowsIntervalChange', renderContext)`) is more efficient than selector-based reactivity, because events can be subscribed to separately, whereas `useGridSelector` needs to re-derive every selector to know if a reaction is needed. I've benchmarked a bit, right now an `api.setState()` call costs around 0.8ms with a medium sized grid on my laptop. The large majority of the cost is each cell calling `.getCellParams()`, which is a known bad (costly) function. So it's not "free", but it's very very far from being an optimization target.

Interestingly I've been trying to figure out if there is a way to get fine-grained reactivity while keeping our selector model. I thought about turning our selectors into functional lenses (which describe both get & set operation), so that if we `set` the state with a lense, we can know who is `get`ing that same state with the same lens. Another option could be to wrap the `useGridSelector` state passed to selectors in proxies that observe which part of the state is accessed during the selector; then we that same slice is modified in `setState`, we know who needs updating—this is similar to how solidjs does reactivity, but their signal getter/setters are more explicit than proxies. But this is all in theory, and not a priority anytime soon.

Anyway sorry for the wall of text, hope it helps understand my design choices better.

Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:1]: Last note I promise but another alternative for reactivity would be to gradually move to event-based reactivity, which woud look something like this:
```js
// Emitter:
apiRef.current.publishEvent('rowsIntervalChange', renderContext)

// Consumer:
const renderContext = useGridEvent(apiRef, 'rowsIntervalChange')
```
But the amount of events might become unwieldy.

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:1]: > There's also the fact that a lot of our reactivity model is now based around useGridSelector, which re-renders when the selected slice of the state has changed. With renderContext in there, updating in response to a change is now as simple as using:
const renderContext = useGridSelector(apiRef, gridRenderContextSelector)
// and that's always going to stay in sync with the 
const pinnedColumns = useGridSelector(...)
// in the next line. 

Hmm, good point. Although, deriving the `renderContext` in `useMemo` would give the same result.
The only downside is prop-drilling, but I'm not sure if it's an actual problem for `renderContext`.

Generally, I don't mind keeping `renderContext` in the grid state, and your choice makes sense to me (thanks for the detailed explanation!).
My only concern is that it will be even harder to review this PR as a whole with more and more architectural changes 😅 Maybe we can extract some of them to separate PRs?

Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:1]: Splitting this PR would be a lot (big emphasis) of work. The renderContext change is not really out of scope, the main changes that this PR needed to do are the dimensions logic and the virtualization logic (renderContext is part of the virtualization code), both of which directly touch the layout. Let's discuss this in the meeting.

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:1]: > Last note I promise but another alternative for reactivity would be to gradually move to event-based reactivity, which woud look something like this:
>
> // Emitter:
>apiRef.current.publishEvent('rowsIntervalChange', renderContext)
>
> // Consumer:
>const renderContext = useGridEvent(apiRef, 'rowsIntervalChange')

This looks interesting, we can discuss this separately along with some estimations for potential performance gains 🙂

> But the amount of events might become unwieldy.

I'm not very concerned with this, it would probably be around the number of selectors we currently have 😅

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 22]
```diff
@@ -37,174 +45,238 @@ export const GridRootStyles = styled('div', {
...
+    '--DataGrid-pinnedBackground': pinnedBackground,
+    '--DataGrid-rowBorderColor': borderColor,
+
     '--DataGrid-cellOffsetMultiplier': 2,
+    '--DataGrid-width': '0px',
+    '--DataGrid-hasScrollX': '0',
+    '--DataGrid-hasScrollY': '0',
+    '--DataGrid-offsetTop': '0px',
+    '--DataGrid-offsetLeft': '0px',
+    '--DataGrid-scrollbarSize': '10px',
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:201]: I looked into the point (1) from https://github.com/mui/mui-x/pull/10059#discussion_r1417075038 and managed to fix the automatic scrollbar on MacOS with the following diff:

```diff
diff --git a/packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts b/packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts
index 836dd6392..11fd2e6e9 100644
--- a/packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts
+++ b/packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts
@@ -198,7 +198,6 @@ export const GridRootStyles = styled('div', {
     '--DataGrid-hasScrollY': '0',
     '--DataGrid-offsetTop': '0px',
     '--DataGrid-offsetLeft': '0px',
-    '--DataGrid-scrollbarSize': '10px',
     '--DataGrid-rowWidth': '0px',
     '--DataGrid-columnsTotalWidth': '0px',
     '--DataGrid-leftPinnedWidth': '0px',
diff --git a/packages/grid/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx b/packages/grid/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx
index 87a2b7779..af94c326c 100644
--- a/packages/grid/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx
+++ b/packages/grid/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx
@@ -37,13 +37,13 @@ const Scrollbar = styled('div')({
 });
 
 const ScrollbarVertical = styled(Scrollbar)({
-  width: 'var(--DataGrid-scrollbarSize)',
+  width: 'var(--DataGrid-scrollbarSize, 16px)',
   height:
-    'calc(var(--DataGrid-hasScrollY) * (100% - var(--DataGrid-topContainerHeight) - var(--DataGrid-bottomContainerHeight) - var(--DataGrid-hasScrollX) * var(--DataGrid-scrollbarSize)))',
+    'calc(var(--DataGrid-hasScrollY) * (100% - var(--DataGrid-topContainerHeight) - var(--DataGrid-bottomContainerHeight) - var(--DataGrid-hasScrollX) * var(--DataGrid-scrollbarSize, 16px)))',
   overflowY: 'auto',
   overflowX: 'hidden',
   '& > div': {
-    width: 'var(--DataGrid-scrollbarSize)',
+    width: 'var(--DataGrid-scrollbarSize, 16px)',
   },
   top: 'var(--DataGrid-topContainerHeight)',
   right: '0px',
@@ -51,11 +51,11 @@ const ScrollbarVertical = styled(Scrollbar)({
 
 const ScrollbarHorizontal = styled(Scrollbar)({
   width: '100%',
-  height: 'var(--DataGrid-scrollbarSize)',
+  height: 'var(--DataGrid-scrollbarSize, 16px)',
   overflowY: 'hidden',
   overflowX: 'auto',
   '& > div': {
-    height: 'var(--DataGrid-scrollbarSize)',
+    height: 'var(--DataGrid-scrollbarSize, 16px)',
   },
   bottom: '0px',
 });
diff --git a/packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts b/packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
index a16662db6..395f4b5db 100644
--- a/packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
+++ b/packages/grid/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts
@@ -307,7 +307,9 @@ export function useGridDimensions(
     set('--DataGrid-width', `${dimensions.viewportOuterSize.width}px`);
     set('--DataGrid-hasScrollX', `${Number(dimensions.hasScrollX)}`);
     set('--DataGrid-hasScrollY', `${Number(dimensions.hasScrollY)}`);
-    set('--DataGrid-scrollbarSize', `${dimensions.scrollbarSize}px`);
+    if (dimensions.scrollbarSize !== 0) {
+      set('--DataGrid-scrollbarSize', `${dimensions.scrollbarSize}px`);
+    }
     set('--DataGrid-rowWidth', `${dimensions.rowWidth}px`);
     set('--DataGrid-columnsTotalWidth', `${dimensions.columnsTotalWidth}px`);
     set('--DataGrid-leftPinnedWidth', `${dimensions.leftPinnedWidth}px`);
```

Chromium:

https://github.com/mui/mui-x/assets/13808724/9a2f5794-fa3e-46e5-b611-b46e36ca0c30

Safari:

https://github.com/mui/mui-x/assets/13808724/0632de40-c8fc-4ea8-bdd8-43f8493e4b36

Scrollbars do not show up on iOS though - I will investigate this too.

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:1]: > I'm not very concerned with this, it would probably be around the number of selectors we currently have

That's exactly what I thought.

It does look interesting, but again if we focus this we'd be optimizing a cost of less than a millisecond (0.8ms on my laptop) on each `.setState` call, and those don't happen often during usage of the grid, only when something changes (e.g. renderContext change, filters, pins, etc). They dont happen during scrolling<sup>1, </sup><sup>2</sup>. We have bigger costs that we can focus before working on that. The big reason for going for selectors was that we'd get reactivity<sup>3</sup> with a medium-low complexity change, due to `useGridSelector` being used everywhere already.


<sup>1</sup> <em>Except when renderContext needs to change to render more rows/cols.</em>
<sup>2</sup> <em>Except right now because [this](https://github.com/mui/mui-x/blob/next/packages/grid/x-data-grid/src/hooks/features/columnMenu/useGridColumnMenu.ts#L82-L93) runs on every wheel event, but this PR fixes it.</em>

<sup>3</sup> <em>Reactivity that isn't "rerender everything anytime something changes".</em>

**Comment by cherniavskii** [comment]
Current dependencies on/for this PR:
* `next`
  * **PR #10059** <a href="https://app.graphite.dev/github/pr/mui/mui-x/10059?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/mui/mui-x/10059?utm_source=stack-comment).

File: packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx:1]: Point no 3 was a reactivity issue, solved it in https://github.com/mui/mui-x/pull/10059/commits/8697661fd31b1c0dbdc4c30739f3f41a27a09e7f

File: packages/grid/x-data-grid/src/hooks/core/useGridInitialization.ts [hunk 23]
```diff
@@ -19,6 +21,9 @@ export const useGridInitialization = <
   props: DataGridProcessedProps,
 ) => {
   const privateApiRef = useGridApiInitialization<PrivateApi, Api>(inputApiRef, props);
+
+  useGridRefs(privateApiRef);
+  useGridTheme(privateApiRef);
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/core/useGridInitialization.ts:26]: I have also lifted the `theme` in the grid state. This is done so that functions that select & operate on the state can be truly pure (in the real FP sense, not react "pure"). We should use a single mechanism for reactivity instead of storing part of the inputs in the `state` and other parts in react hooks (theme in `useContext`, etc).

This also allowed me to turn the visible pinned columns logic into a grid selector, which makes it way more resilient to change than the approach I used before, and simplifies the mental load required to understand that logic.

File: packages/grid/x-data-grid/src/models/gridSlotsComponent.ts [hunk 24]
```diff
@@ -82,7 +87,7 @@ export interface GridSlotsComponent extends GridBaseSlots, GridIconSlotsComponen
    * Component rendered for each cell.
    * @default GridCell
    */
-  cell: React.JSXElementConstructor<any>;
+  cell: React.JSXElementConstructor<GridCellProps>;
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/models/gridSlotsComponent.ts:90]: Not sure why these are all `any`, but adding types here makes it easier to refactor and not miss issues or create bugs.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 22 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:201]: Solved, but this needed to go on the scrollbar container directly. For the rest of the grid, the scrollbar size needs to be `0px` otherwise stuff isn't positionned properly.

I've set it to an absolute value of 14px but I don't like that solution, but there's no way to figure out the scrollbar size for platforms where the scrollbar doesn't affect layout like macOS or gnome. In particular if the user is zoomed to a different level than 100%, the scrollbar "pixel" size could be much smaller or larger.

Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:201]: Did you have time to test on iOS by any chance? I don't have any apple device, so I can't test it easily.

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:201]: Unfortunately, the scrollbars aren't visible on iOS:


https://github.com/mui/mui-x/assets/13808724/267bfab9-3b7d-444f-b4b6-daf9954e8175

We can fix this later though

File: packages/grid/x-data-grid/src/models/gridSlotsComponent.ts (hunk 24 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/models/gridSlotsComponent.ts:90]: Yes, I came across this issue as well in https://github.com/mui/mui-x/pull/8067#discussion_r1122007786
At that time, we decided to not go with this change, but I'm all in for doing this, at least for some slots 👍🏻

Minor sidenote: `GridCellProps` does not include [custom props from props overrides](https://mui.com/x/react-data-grid/components/#custom-slot-props-with-typescript). I think this was the reason I tried using `GridSlotsComponentsProps` in the PR linked above.



> I commented out the following line in the `GridCellProps` to demonstrate the issue above:
> https://github.com/romgrk/mui-x/blob/da77da1037e6256651a84a32060073b776dddcdb/packages/grid/x-data-grid/src/components/cell/GridCell.tsx#L65

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 25]
```diff
@@ -37,174 +45,238 @@ export const GridRootStyles = styled('div', {
...
+  const radius = t.shape.borderRadius;
+
+  const containerBackground = t.vars
+    ? t.vars.palette.background.defaultChannel
+    : t.palette.background.default;
+
+  const pinnedBackground =
+    t.palette.mode === 'dark'
+      ? lighten(
+          t.vars ? t.vars.palette.background.defaultChannel : t.palette.background.default,
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:137]: JS color manipulations won't work with `t.vars` as `t.vars.palette.background.defaultChannel` contains a CSS variable.
This is the reason https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/experiments/joy-ui/ throws an error

Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:137]: I don't understand theme much yet, would you have a proposition to solve this issue? Should I pick a different field from the theme object?

File: packages/grid/x-data-grid/src/components/GridRow.tsx [hunk 26]
```diff
@@ -454,21 +502,30 @@ const GridRow = React.forwardRef<HTMLDivElement, GridRowProps>(function GridRow(
       }
     : null;
 
+  const scrollbarWidth = dimensions.hasScrollY ? dimensions.scrollbarSize : 0;
+  const expandedWidth =
+    dimensions.viewportOuterSize.width - dimensions.columnsTotalWidth - scrollbarWidth;
+  const emptyCellWidth = Math.max(scrollbarWidth, expandedWidth);
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/GridRow.tsx:508]: This causes an issue with pinned columns: https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/column-pinning/

<div class='graphite__hidden'>
          <div>🎥 Video uploaded on Graphite:</div>
            <a href="https://app.graphite.dev/media/video/HUAcyHFPUPbbXFJX5Kwj/9b991c14-e316-4ed6-a15e-ce99c4d56fdc.mov">
              
            </a>
          </div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/HUAcyHFPUPbbXFJX5Kwj/9b991c14-e316-4ed6-a15e-ce99c4d56fdc.mov">Screen Recording 2023-12-20 at 10.53.19.mov</video>


Why is `scrollbarWidth` used here? Shouldn't it be `Math.max(0, expandedWidth);`?

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 27]
```diff
@@ -1,449 +1,209 @@
...
-  const [renderContext, setRenderContextState] = React.useState<GridRenderContext | null>(null);
-  const prevRenderContext = React.useRef<GridRenderContext | null>(renderContext);
-  const scrollPosition = React.useRef({ top: 0, left: 0 });
-  const [containerDimensions, setContainerDimensions] = React.useState<ContainerDimensions>({
-    width: null,
-    height: null,
-  });
+  const scrollbarVerticalRef = React.useRef<HTMLDivElement>(null);
+  const scrollbarHorizontalRef = React.useRef<HTMLDivElement>(null);
+  const contentHeight = dimensions.contentSize.height;
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:72]: There is a bit of extra space at the bottom in some cases, like here: https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/column-pinning/


https://github.com/mui/mui-x/assets/13808724/c1a85096-dcde-4557-8956-bd6d3a102acd

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 25 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:137]: I'll take a look

File: packages/grid/x-data-grid/src/models/gridSlotsComponent.ts (hunk 24 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/models/gridSlotsComponent.ts:90]: It'll be a nice dx improvement if we could replace these any occurrences with proper types.
Could possibly be done separately though?

File: packages/grid/x-data-grid/src/components/GridColumnHeaders.tsx [hunk 28]
```diff
@@ -9,26 +9,25 @@ import {
 import { GridBaseColumnHeaders } from './columnHeaders/GridBaseColumnHeaders';
 import { GridColumnHeadersInner } from './columnHeaders/GridColumnHeadersInner';
```
[the remark this answers is not in the document]
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/components/GridColumnHeaders.tsx:10]: A related UI behavior (header `border-bottom` jump on fast scrolling) which I believe is also due to this one pixel gap as it's only reproducible on Firefox too. 🤔 

jump

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 25 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts]: I've pushed a commit with a fix, but there's no support for darken/lighten when using CSS variables.
So when the data grid is used inside `CSSVarProvider` (instead of regular `ThemeProvider`), `pinnedBackground === containerBackground`.
I think it's fine since we might remove different background color for pinned columns/rows anyway as discussed in https://github.com/mui/mui-x/pull/10059#discussion_r1417215551

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 29]
```diff
@@ -272,245 +338,299 @@ export const GridRootStyles = styled('div', {
...
       '& svg': {
         pointerEvents: 'none',
       },
     },
-    [`& .${gridClasses.iconSeparator}`]: {
+    [`& .${c.iconSeparator}`]: {
       color: 'inherit',
     },
-    [`& .${gridClasses.menuIcon}`]: {
-      width: 0,
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:314]: The removal of `width: 0` here causes diffs like this:


https://github.com/mui/mui-x/assets/13808724/8fdcab6a-34ec-47e4-b0a1-572844174824

File: packages/grid/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:1]: Noticed an issue: column autosizing doesn't work well after manual column resize: https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/column-dimensions/#autosizing


https://github.com/mui/mui-x/assets/13808724/7269319d-334b-4056-96f8-3389ba1a0d8a

File: packages/grid/x-data-grid/src/components/columnHeaders/GridBaseColumnHeaders.tsx
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/columnHeaders/GridBaseColumnHeaders.tsx:1]: Column autosizing sizes column headers differently than before:


https://github.com/mui/mui-x/assets/13808724/32659ade-2acb-42d8-abcf-6f5354ac270a

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 25 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts]: It's not too bad though - most of the changes are expected.
I've added comments in the PR for those that seem to be out of place

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 30]
```diff
@@ -37,174 +45,236 @@ export const GridRootStyles = styled('div', {
...
-    '--unstable_DataGrid-headWeight': theme.typography.fontWeightMedium,
-    '--unstable_DataGrid-overlayBackground': theme.vars
-      ? `rgba(${theme.vars.palette.background.defaultChannel} / ${theme.vars.palette.action.disabledOpacity})`
-      : alpha(theme.palette.background.default, theme.palette.action.disabledOpacity),
+    '--unstable_DataGrid-headWeight': t.typography.fontWeightMedium,
+    '--unstable_DataGrid-overlayBackground': overlayBackground,
+
+    '--DataGrid-containerBackground': containerBackground,
+    '--DataGrid-pinnedBackground': pinnedBackground,
+    '--DataGrid-rowBorderColor': borderColor,
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:191]: One side border for [spanned columns](https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/column-spanning/) seems to not have picked the right color.
image

File: packages/grid/x-data-grid/src/components/GridPinnedRows.tsx
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/components/GridPinnedRows.tsx:1]: https://github.com/mui/mui-x/assets/12609561/cf388430-65fc-45d7-9e37-a2eaa38725e4

Is this resizing behavior issue for pinned columns known?

Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/components/GridPinnedRows.tsx:1]: Oh I see, there's a resizing is not working action item 👍

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 25 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts]: One thing with your change though, the hover & selected styles aren't blended with the background color, it's just the color raw. Is there a way we can fix those? We haven't really discussed, but what would be the recommended way to customize that sort of color for the grid?

File: packages/grid/x-data-grid/src/components/GridRow.tsx (hunk 26 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/GridRow.tsx:508]: Fixed. Not sure why it was written that way (past me had intentions forgotten to me), but the filler cell needs to act differently depending if there's pinned-right columns or not.

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx (hunk 27 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:72]: Logic issue with the render context, the final row wasn't rendered. It's fixed.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 25 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts]: > One thing with your change though, the hover & selected styles aren't blended with the background color, it's just the color raw. Is there a way we can fix those?

Well, I won't be able to recreate the same blend, but I can use [`color-mix`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix). Browser support isn't great though (version-wise).

> We haven't really discussed, but what would be the recommended way to customize that sort of color for the grid?

What is the current approach? Users have to override colors for hover, selected, and selected on hover?

File: packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsSelector.ts [hunk 31]
```diff
@@ -66,6 +71,69 @@ export const gridVisibleColumnFieldsSelector = createSelectorMemoized(
...
+export const gridVisiblePinnedColumnDefinitionsSelector = createSelectorMemoized(
+  gridColumnsStateSelector,
+  gridPinnedColumnsSelector,
+  gridVisibleColumnFieldsSelector,
+  gridThemeSelector,
+  (columnsState, model, visibleColumnFields, theme) => {
+    const visiblePinnedFields = filterVisibleColumns(
+      model,
+      visibleColumnFields,
+      theme.direction === 'rtl',
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsSelector.ts:93]: Should we go a step further here and create a `gridThemeDirectionSelector` to preserve caching when the theme changes, but the direction is the same?

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 25 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts]: The current approach would be to use the MUI themes. I think it's ok to leave it as it is and adjust later though.

File: packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsSelector.ts (hunk 31 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsSelector.ts:93]: I don't expect the theme object to change often enough to be worth it.

File: packages/grid/x-data-grid/src/components/GridColumnHeaders.tsx (hunk 28 above)
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/GridColumnHeaders.tsx:10]: Can't reproduce, can you give me the exact example you're seeing this on? You're on macOS right? What's the firefox version?

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 29 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:314]: It was causing a layout issue that I can't reproduce, so I've restored the `width: 0`.

File: packages/grid/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx
Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx:1]: Fixed. Our resizing code manipulates the DOM directly, which wasn't accounted for.

File: packages/grid/x-data-grid/src/components/columnHeaders/GridBaseColumnHeaders.tsx
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/columnHeaders/GridBaseColumnHeaders.tsx:1]: Seems to be fixed in the latest argos build.

File: packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts (hunk 19 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsUtils.ts]: This has been fixed.

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx (hunk 20 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx:684]: I've kept the CSS var but restored the min/max width.

File: packages/grid/x-data-grid-pro/src/components/GridColumnHeaders.tsx (hunk 21 above)
Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/components/GridColumnHeaders.tsx]: Removed.

File: packages/grid/x-data-grid/src/components/GridRow.tsx [hunk 32]
```diff
@@ -387,14 +338,128 @@ const GridRow = React.forwardRef<HTMLDivElement, GridRowProps>(function GridRow(
...
+    // eslint-disable-next-line default-case
+    switch (pinnedPosition) {
+      case PinnedPosition.LEFT:
+        pinnedOffset = columnPositions[indexRelativeToAllColumns];
+        break;
+      case PinnedPosition.RIGHT:
+        pinnedOffset =
+          dimensions.columnsTotalWidth -
+          columnPositions[indexRelativeToAllColumns] -
+          column.computedWidth;
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/GridRow.tsx:373]: Fixed.

File: packages/grid/x-data-grid/src/components/GridPinnedRows.tsx
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/GridPinnedRows.tsx:1]: This issue still remains and it's going to be messy to fix it.

**Comment by romgrk** [comment]
Remaining tasks:
 - [ ] [Bug when resizing and there are more than one right-pinned columns](https://github.com/mui/mui-x/pull/10059#discussion_r1433652562)
 - [ ] [Firefox 1px gap/jitter](https://github.com/mui/mui-x/pull/10059#discussion_r1432751054)
 - [ ] Fake browser tests failing
 - [ ] Migration guide/breaking changes

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 33]
```diff
@@ -262,9 +262,9 @@ export const useGridVirtualScroller = () => {
         break;
     }
 
-    if (innerSize.width === 0) {
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx]: This condition makes sense, but it's always 0 in JSDOM.
I assume we didn't have a check like this before, do we really need it?

Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx]: Let's see if the tests pass without it. The state dimensions are now always defined but initialized with `0`, so this condition might have been added to avoid the uninitialized case, which may have other implications. If it works without it, amazing. Otherwise, we could compare `innerSize !== EMPTY_SIZE`, which is the initiali value for all dimensions.

File: packages/grid/x-data-grid/src/components/GridColumnHeaders.tsx (hunk 28 above)
[the remark this answers is not in the document]
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/components/GridColumnHeaders.tsx:10]: Yep. I have MacOS Firefox (regular) version 120.0.1 (64-bit) and Firefox developer edition version 114.0b9 (64-bit).
The first issue (1px gap on top) seems to have been fixed now. But the border-bottom jump I can still observe. But I think it's not that noticeable to block merging this PR.

[the remark this answers is not in the document]
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/components/GridColumnHeaders.tsx:10]: On observing a bit closer, it seems like the border is increasing and decreasing during the scroll.
border

This property seems to have a connection with the first issue, I was able to reproduce the first issue on commenting this line:
https://github.com/mui/mui-x/blob/48619cd79fe988bb1accb2b89ddf84b4a959f851/packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts#L252

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 34]
```diff
@@ -37,174 +45,237 @@ export const GridRootStyles = styled('div', {
...
       outline: `solid ${
-        theme.vars
-          ? `rgba(${theme.vars.palette.primary.mainChannel} / 0.5)`
-          : alpha(theme.palette.primary.main, 0.5)
+        t.vars
+          ? `rgba(${t.vars.palette.primary.mainChannel} / 0.5)`
+          : alpha(t.palette.primary.main, 0.5)
       } 1px`,
       outlineWidth: 1,
       outlineOffset: -1,
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:251]: I spotted a possible improvement (unrelated to this PR) during debugging for https://github.com/mui/mui-x/pull/10059#discussion_r1440656297
```suggestion
      outlineOffset: -2,
```

This will remove the outline clipping traded with one pixel white space which looks better to me tbh.

Before:
image

After:
image

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx (hunk 33 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx]: All tests pass now - see [`1a925a6` (#10059)](https://github.com/mui/mui-x/pull/10059/commits/1a925a6b3af42c16677f31c2bab72b537b002ab4) and [`af2f722` (#10059)](https://github.com/mui/mui-x/pull/10059/commits/af2f722262041aef9b8cff4d531da4473a241665)

File: packages/grid/x-data-grid/src/components/GridPinnedRows.tsx
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/GridPinnedRows.tsx:1]: Fixed. I hate it but I fixed it the easy way which is for sure the best compromise. But I hate it.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 34 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:251]: LGTM also.

File: packages/grid/x-data-grid/src/components/panel/GridPanel.tsx [hunk 35]
```diff
@@ -98,12 +97,12 @@ const GridPanel = React.forwardRef<HTMLDivElement, GridPanelProps>((props, ref)
   const [anchorEl, setAnchorEl] = React.useState<Element | null>(null);
 
   React.useEffect(() => {
-    const columnHeadersElement = apiRef.current.rootElementRef?.current?.querySelector(
-      `.${gridClasses.columnHeaders}`,
+    const panelAnchor = apiRef.current.rootElementRef?.current?.querySelector(
+      '[data-id="gridPanelAnchor"]',
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/panel/GridPanel.tsx:101]: Fixes this:

https://github.com/mui/mui-x/assets/13808724/62b36b90-7199-4090-b60e-d403a72b1430

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 36]
```diff
@@ -389,6 +389,7 @@ export const GridRootStyles = styled('div', {
     },
     [`.${c.menuOpen}`]: {
       visibility: 'visible',
+      width: 'auto',
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:392]: This line was removed, do you remember the reason?
It caused this issue:

https://github.com/mui/mui-x/assets/13808724/4f9a2db7-a2c6-4300-89ae-4a1a6a75a80b

Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:392]: Not sure. The menu icons were messing with the flex+sticky layout because in their hidden state their were sticking outside at the end of the row, so they were adding width and widening the scroll container more than it needed to be. I modified them until it didn't happen, don't remember about this specific line.

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:392]: I've added it back, let me know if it's causing other issues.

**Review by cherniavskii — COMMENTED** [review]
Adding a few comments I added while reviewing the code.
I'll finish the review tomorrow!

File: packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx [hunk 37]
```diff
@@ -442,23 +444,23 @@ describe('<DataGridPro /> - Rows', () => {
...
         Math.floor((height - 1) / rowHeight) + rowBuffer,
       ); // Subtracting 1 is needed because of the column header borders
+      const scrollbarSize = apiRef.current.state.dimensions.scrollbarSize;
       const distanceToFirstRow = (nbRows - renderingZone.children.length) * rowHeight;
-      expect(renderingZone.style.transform).to.equal(
-        `translate3d(0px, ${distanceToFirstRow}px, 0px)`,
-      );
-      expect(virtualScroller.scrollHeight).to.equal(nbRows * rowHeight);
+      const styles = getComputedStyle(root);
+      const offsetTop = parseInt(styles.getPropertyValue('--DataGrid-offsetTop'), 10);
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx:461]: Tbh a lot of these tests were too implementation-specific and they still are, it's just that finding a way to test what we really want to test (that the content is rendered where it needs to be) is kinda hard without falling into this trap. Something like argos tests but that can take snapshots at different moments of an action/test would be more reliable. This would be the best option to test resizing also.

File: packages/grid/x-data-grid-pro/src/hooks/features/columnPinning/useGridColumnPinningPreProcessors.ts [hunk 38]
```diff
@@ -1,43 +1,53 @@
...
+    pinnedColumns = gridPinnedColumnsSelector(apiRef.current.state);
+  } else {
+    pinnedColumns = null;
   }
 
   const prevAllPinnedColumns = React.useRef<string[]>([]);
 
   const reorderPinnedColumns = React.useCallback<GridPipeProcessor<'hydrateColumns'>>(
     (columnsState) => {
+      eslintUseValue(pinnedColumns);
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/hooks/features/columnPinning/useGridColumnPinningPreProcessors.ts:30]: I'm terribly annoyed with the `react-hooks` rules. They haven't received work in the last years, they don't make use of typescript to avoid useless code (e.g. skip values whose type extends `React.MutableRefObject<any>` from the deps list...), and they don't allow to be turned off for specific symbols rather than just turn off for the whole effect.

File: packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx (hunk 37 above)
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx:461]: Or a video-based argos instead of image-based.

[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx:461]: Fair enough

File: packages/grid/x-data-grid/src/components/GridRow.tsx [hunk 39]
```diff
@@ -454,21 +504,29 @@ const GridRow = React.forwardRef<HTMLDivElement, GridRowProps>(function GridRow(
...
       style={style}
       {...eventHandlers}
       {...other}
     >
+      {leftCells}
       {cells}
       {emptyCellWidth > 0 && <EmptyCell width={emptyCellWidth} />}
+      {rightCells.length > 0 && <div role="presentation" style={{ flex: '1' }} />}
+      {rightCells}
+      <ScrollbarFiller pinnedRight={pinnedColumns.right.length > 0} />
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/GridRow.tsx:529]:
```suggestion
      {scrollbarWidth !== 0 && <ScrollbarFiller pinnedRight={pinnedColumns.right.length > 0} />}
```

No need for fillers when `scrollbarWidth === 0` - this is often the case on MacOS

File: packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx [hunk 40]
```diff
@@ -77,10 +77,11 @@ function GridVirtualScroller(props: GridVirtualScrollerProps) {
       <Scroller className={classes.scroller} {...getScrollerProps()} ownerState={rootProps}>
         <TopContainer>
           <GridHeaders />
-          <GridOverlays />
           <rootProps.slots.pinnedRows position="top" virtualScroller={virtualScroller} />
         </TopContainer>
 
+        <GridOverlays />
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx:83]: @romgrk 

Along with `top: 'var(--DataGrid-headersTotalHeight)',` fixes this issue:


https://github.com/mui/mui-x/assets/13808724/1e95e102-acb9-444d-87bd-322d3a68d449

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx [hunk 41]
```diff
@@ -249,7 +250,7 @@ const GridCell = React.forwardRef<HTMLDivElement, GridCellProps>((props, ref) =>
     sectionIndex === 0;
   const showRightBorder =
     rootProps.showCellVerticalBorder &&
-    !(isSectionLastCell && pinnedPosition !== PinnedPosition.LEFT);
+    (isSectionLastCell ? pinnedPosition === PinnedPosition.LEFT || !gridHasScrollX : true);
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/cell/GridCell.tsx:253]: @romgrk 
This fixes the `ColumnSpanningNumber` demo: https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/column-spanning/#number-signature

File: scripts/x-data-grid-premium.exports.json [hunk 42]
```diff
@@ -33,8 +33,11 @@
   { "name": "deDE", "kind": "Variable" },
   { "name": "DEFAULT_GRID_AUTOSIZE_OPTIONS", "kind": "Variable" },
   { "name": "DEFAULT_GRID_COL_TYPE_KEY", "kind": "Variable" },
+  { "name": "dimensionsStateInitializer", "kind": "Variable" },
```
Comment (cherniavskii) [inline scripts/x-data-grid-premium.exports.json:36]: No need to export it

File: scripts/x-data-grid-premium.exports.json [hunk 43]
```diff
@@ -639,12 +651,16 @@
   { "name": "useGridApiMethod", "kind": "Function" },
   { "name": "useGridApiOptionHandler", "kind": "Function" },
   { "name": "useGridApiRef", "kind": "Variable" },
+  { "name": "useGridDimensions", "kind": "Function" },
```
Comment (cherniavskii) [inline scripts/x-data-grid-premium.exports.json:654]: No need to export it

**Review by cherniavskii — APPROVED** [review]

File: docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md [hunk 44]
```diff
@@ -69,6 +69,27 @@ Since v7 is a major release, it contains some changes that affect the public API
...
+ - slot `GridRow`, props removed: containerWidth, position
+ - api `mainElementRef` non-null
+ - api `rootElementRef` non-null
+ - api `virtualScrollerRef` non-null
+ - event `renderedRowsIntervalChange`: params changed `GridRenderedRowsIntervalChangeParams` to `GridRenderContext`
+ - type `GridRenderedRowsIntervalChangeParams` removed
+ - type `GridRootContainerRef` removed
+ - slot `GridRow` has typed props now
+ - slot `headerFilterCell`, props removed: filterOperators
+ - DOM changes
```
Comment (romgrk) [inline docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md:90]: I've gone through the PR, this is the list of breaking changes I found.

In theory no change to the slot props is breaking because they're all typed as `any`, but in practice any change there is a breaking change, it's just that people won't be able to know because there are no types. This is one reason why I think we should absolutely type the slot props.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 34 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:254]: Let's do this after merging this PR though

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 18 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts]: For me, the ideal behavior is:
- same bg color for pinned and non-pinned columns
- conditional shadow on pinned columns: see the demo in https://github.com/mui/mui-x/issues/7152#issuecomment-1344981248

Would you like to work on this after merging this PR?
There's an issue for this enhancement already: https://github.com/mui/mui-x/issues/10001

File: docs/data/data-grid/column-pinning/ControlPinnedColumns.tsx
Comment (MBilalShafi) [inline docs/data/data-grid/column-pinning/ControlPinnedColumns.tsx:1]: I thought we decided to remove this pinned background. Isn't it?
image

File: docs/data/data-grid/events/events.json
Comment (MBilalShafi) [inline docs/data/data-grid/events/events.json:1]: Another variant of https://github.com/mui/mui-x/pull/10059#discussion_r1433652562 I think?


https://github.com/mui/mui-x/assets/12609561/09e59d31-09d8-426c-ad0a-74d15c7f7999

Comment (MBilalShafi) [reply docs/data/data-grid/events/events.json:1]: Same seems to be the case with the filler row in [this demo](https://deploy-preview-10059--material-ui-x.netlify.app/x/react-data-grid/column-pinning/#controlling-the-pinned-columns)

https://github.com/mui/mui-x/assets/12609561/3ffe1edc-8831-423d-9479-ac1c2d06987c

**Review by MBilalShafi — APPROVED** [review]
I can't spot anything notable blocking the PR apart from a few minor things already known/being worked on.
Once again, great work with a gigantic impact, thank you so much 👍 
Differing Argos' changes seem fine too.

File: docs/data/data-grid/events/events.json
Comment (romgrk) [reply docs/data/data-grid/events/events.json:1]: Yeah the resizing code isn't very resilient to change. I'll fix this before merging.

File: docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md [hunk 45]
```diff
@@ -281,17 +292,28 @@ Below are described the steps you need to make to migrate from v6 to v7.
...
+- The field `rootElementRef` is now always non-null.
+- The field `virtualScrollerRef` is now always non-null.
+- The event `renderedRowsIntervalChange` params changed from `GridRenderedRowsIntervalChangeParams` to `GridRenderContext`, and the former has been removed.
+
+### Changes to slots
+
+- The slot `columnHeaders` has had these props removed: columnPositions, densityFactor, minColumnIndex.
+- The slot `row` has had these props removed: containerWidth, position.
+- The slot `row` has typed props now.
+- The slot `headerFilterCell` has had these props removed: filterOperators.
```
Comment (cherniavskii) [inline docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md:317]:
```suggestion
- The slot `columnHeaders` has had these props removed: `columnPositions`, `densityFactor`, `minColumnIndex`.
- The slot `row` has had these props removed: `containerWidth`, `position`.
- The slot `row` has typed props now.
- The slot `headerFilterCell` has had these props removed: `filterOperators`.
```

File: packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx [hunk 46]
```diff
@@ -1,53 +1,105 @@
 import * as React from 'react';
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx:1]: @romgrk Do you have an idea why the vertical scroll thumb size has changed in some cases?

https://app.argos-ci.com/mui/mui-x/builds/16813/70843502
https://app.argos-ci.com/mui/mui-x/builds/16813/70843559

Comment (romgrk) [reply packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx:1]: I think it's supposed to have changed in all cases, because the headers are now inside the virtual scroller's scroll-container, so they count towards the scroll content's height despite being fixed at the top.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 22 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:194]: > Unfortunately, the scrollbars aren't visible on iOS:

I confirm this to be an issue, there's also another interesting observation on iOS.

When I scroll fast on this demo, there appears to be a lot of white space, but only when checkbox column is in view, if I scroll to the right, it appears to be quite smooth. Checkbox rendering seems to be expensive.

https://github.com/mui/mui-x/assets/12609561/21186c12-6ead-44a6-97ee-b68e8753acea

We could probably create a followup issue for these iOS related issues. 
CC @romgrk

File: packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx (hunk 46 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx:1]: Yes, this makes sense to me.
Any idea why it didn't change in the second demo?

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx:1]: Oh, I think it didn't change because there are 100 rows in the second demo, and the impact of one additional row (header) wasn't enough to increase the scroll thumb height even by 1px. Does this make sense?

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx [hunk 47]
```diff
@@ -245,12 +245,12 @@ const GridCell = React.forwardRef<HTMLDivElement, GridCellProps>((props, ref) =>
   const isSectionLastCell = sectionIndex === sectionLength - 1;
 
   const showLeftBorder =
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/cell/GridCell.tsx:247]: @romgrk I think this change results in a double vertical border when `showCellVerticalBorder={true}`:

https://app.argos-ci.com/mui/mui-x/builds/16834/70974455
https://app.argos-ci.com/mui/mui-x/builds/16834/70974454

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 48]
```diff
@@ -214,56 +288,52 @@ export const GridRootStyles = styled('div', {
...
         borderBottom: `none`,
       },
-    [`& .${gridClasses['columnHeader--filledGroup']}.${gridClasses['columnHeader--showColumnBorder']}`]:
-      {
-        borderBottomWidth: '1px',
-        borderBottomStyle: 'solid',
-        boxSizing: 'border-box',
-      },
-    [`& .${gridClasses.headerFilterRow}`]: {
-      borderTop: `1px solid ${borderColor}`,
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:238]: The border is missing between the headers and header filters:
https://app.argos-ci.com/mui/mui-x/builds/16834/70974514

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:238]: Ah, it's applied to the cells now, this is why it's not there when custom cells are used.

Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:238]: Should we fix this demo separately then?

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:238]: Yes, it's not a blocker

File: packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx (hunk 46 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx:1]: Yes 100 rows and more demos don't seem to change.

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 48 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:238]: [Fixed](https://github.com/mui/mui-x/pull/10059/commits/11c84c5b80b2890caa5f6c27bf66fa0575dea88f)

**Comment by Janpot** [comment]
This is an awesome job. I've spent so much time in a rabbit hole fixing similar issues for my own [grid](https://mui-plus.vercel.app/components/DataGrid/virtualization) back in the day. I can only imagine the effort on a full featured implementation like the X grid.

**Comment by oliviertassinari** [comment]
Isn't this much better?

Before:
https://github.com/mui/mui-x/assets/3165635/d7f43370-d8a0-4496-8b87-43206492feac

After:
https://github.com/mui/mui-x/assets/3165635/8e944fa4-bd0a-48a7-95b2-f1b3a49ab5e5

**Comment by lauri865** [comment]
@oliviertassinari, try disabling overscroll-behavior, and will look and feel even more performant on iOS (as I pointed out here: https://github.com/mui/mui-x/issues/11230#issuecomment-1848022297). You wont have the all the rows disappearing for a brief moment when you accidentally overscroll on the X-axis while actually just trying to scroll down ;)

**Comment by oliviertassinari** [comment]
@romgrk I found a regression, this PR broke this demo: https://next.mui.com/x/react-data-grid/row-updates/#lazy-loading

**Comment by romgrk** [comment]
Opened the issue linked above.

**Comment by oliviertassinari** [comment]
@romgrk In terms of scrolling performance, I have noticed a few things on this PR.

First, the baseline, ranked by how much time it takes to render the next rows, the difference is clear on my laptop:

- 🥇 a. AG Grid: no white screens
- 🥈 b. Before: a little bit of white screen, about 8% of the viewport
- 🥉 c. After: more white screen, about 20% of the viewport

Now, when we look at the actual profile for 1,000 ms of scroll, we see a much different story:

- AG Grid: no white screens, overscan of 10 rows



- Before: a little bit of white screen, about 8% of the viewport, overscan of 3 rows



- After: more white screen, about 20% of the viewport, overscan of 3 rows



We were 1st Before in terms of idle time, the most important metric to judge performance IMHO, but because we were not using a high enough overscan, end-users would feel a white area. It seems clear to me that 3 is not enough https://mui.com/x/api/data-grid/data-grid/#DataGrid-prop-rowBuffer. Increasing it would be a perfect quick win.

There is a x2.0 increase in rendering time in After compared to Before. We are no longer so much ahead of AG Grid. This seems to come from two things:

- We spend a lot more time in the Layerize phase (https://developer.chrome.com/docs/chromium/renderingng-architecture). 



As I can see it, it's because of this style:

https://github.com/mui/mui-x/assets/3165635/a02c3fd8-91e9-4726-81ee-e0b88320a183

Once this style removed, the computation bottleneck seems to then move to recalculateStyles, this is very odd to me:



More in context:



I don't know why.

---

Another opportunity I see is how we re-render emotion components at each render, e.g. ScrollbarFiller. How about we memoize or move the style outside of the re-render flow during scroll?

**Comment by romgrk** [comment]
Yes I've noticed the performance changes, I merged anyway because I wanted to get the breaking changes in. I kinda expected the layout to be more expensive for the browser due to that `transform` style as it's on each cell now instead of on a wrapping container, but I think it will be fairly easy to add a wrapping container for the cells and apply the style once. That in conjunction with the CSS `contain: strict` style should make it much more easy for the browser to layout stuff. The CSS containment styles are fairly easy to use for us because we know our dimensions ahead of time with single pixel precision thanks to the changes in the dimensions logic. We compute dimensions once and those dimensions usually don't change much, even during scrolling.

I also initially used CSS variables a lot in this PR, often in dynamic ways (e.g. `calc(10px + var(--xxxx))`, but ended removing them in a few places and might end up removing a lot more of them, because they also increase the layout time.

Regarding emotion, that library is absolutely atrocious for runtime performance and the sooner we can get rid of it the happier I will be. I have been trying to find a way to get emotion to do something like this:

```js
const className = css` color: red `
```

instead of having to use their styled-components, but I don't know the library and our system style wrappers much so I also wasn't able to complete this during this PR. Discussing how we do styling internally on the datagrid is on my roadmap.

Lastly regarding the row overscan, I've already opened #11344 to discuss that aspect, read there for more details.

**Comment by oliviertassinari** [comment]
Alright, let's continue to explore this then. Overall, it's not yet clear that we should sell it as a performance improvement in the v7 release blog post, but it feels like we are close 😁

> I have been trying to find a way to get emotion to do something like this:

A nested CSS selector from the parent does something close, as long as that parent doesn't rerender. We moved many styles up to the grid root in the past because of this.

> CSS variables

I don't know if they increase layout time, I wouldn't expect them to. 
However, updating a CSS variable 120 times per second is slow as the browser needs to make the value propagate down all the children, not just the element itself (unless maybe if we use a custom property with inheritance disabled).

**Comment by romgrk** [comment]
> A nested CSS selector from the parent does something close, as long as that parent doesn't rerender. We moved many styles up to the grid root in the past because of this.

That's terrible. We don't get the CSS-in-JS advantage of colocation of styles & logic, and we don't get the CSS advantage of native (clean) CSS syntax. I've been observing `GridRootStyles`, I also don't like that the massive styles object is recomputed, and it's recomputed quite often during normal usage of the grid despite being near the root :|

I've been watching the zero-runtime solution in the hopes that it solves all our style issues, in the meantime if there's any solution that would help with injecting CSS simply & directly, I'd definitely adopt that.

**Comment by cherniavskii** [comment]
Extracted vertical scrolling performance to a separate issue: https://github.com/mui/mui-x/issues/11866

**Comment by romgrk** [comment]
I've opened #11924 for the performance issues.

**Comment by romgrk** [comment]
Last fix for the issues above opened in #12019. CSS variables were the culprit.

File: packages/grid/x-data-grid/src/components/panel/GridPanel.tsx (hunk 35 above)
Comment (oliviertassinari) [reply packages/grid/x-data-grid/src/components/panel/GridPanel.tsx:101]: Discussion continued a bit in https://github.com/mui/mui-x/pull/15022#issuecomment-2424213768.
