### PR TITLE
[DataGrid] Improve custom overlay slots positioning

### LINKED ISSUE #3795: [DataGrid] Horizontal Scrollbar disappears when NoResultsOverlay is used and no results in filter
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When NoResultsOverlay is set, and no results are given due to preset filter criteria, grid does not show Horizontal Scroll bar.

### Expected behavior 🤔

DataGrid should always show Horizontal Scroll bar. Even when no result/rows, but number of columns exceeds to grid width.

### Steps to reproduce 🕹

Steps:

1. Preset the `filter` value in initialState of grid attribute
2. Load the grid with rows such that no result get rendered, and have numbers of columns with width more than available grid width.
3. No Horizontal bar is shown

https://codesandbox.io/s/fullfeatureddemo-material-demo-forked-0w92k?file=/demo.tsx:288-294

### Context 🔦

As an enterprise application, we have 18 columns to display. our users do use large monitors, but still our grid is wider and needs horizontal bar shown when necessary. 
Right now, if set filter column is around the end, user is not able to unset that filter and stuck with no result.
We use Chrome Browser.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.88 GB / 15.28 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/apra/apra-amcos-apps-distribution-frontend/node_modules/.bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Managers:
    Apt: 2.3.9 - /usr/bin/apt
    Cargo: 1.57.0 - ~/.cargo/bin/cargo
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 11.2.0 - /usr/bin/gcc
    Git: 2.32.0 - /usr/bin/git
  Virtualization:
    Docker: 20.10.12 - /usr/bin/docker
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
  IDEs:
    Nano: 5.6.1 - /usr/bin/nano
    VSCode: 1.63.2 - /snap/bin/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 5.1.8 - /usr/bin/bash
    Java: 1.8.0_312 - /usr/bin/javac
    Perl: 5.32.1 - /usr/bin/perl
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.9.7 - /usr/bin/python3
    Rust: 1.57.0 - /home/anand/.cargo/bin/rustc
  Databases:
    SQLite: 3.32.2 - /home/anand/Android/Sdk/platform-tools/sqlite3
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 96.0

</details>

### Order ID 💳 (optional)

28914

### PR DESCRIPTION
**Pull request by cherniavskii**
Closes #3795

Preview: https://codesandbox.io/s/fullfeatureddemo-material-demo-forked-efmqf

Our layout requires overlays to have position absolute. Otherwise things like horizontal scrolling won't work (overlay might push render zone down below the grid footer).
At the same time, we allow to override overlays using slots.
So in order to make custom overlays work as good as default ones, we have to make sure custom slots are positioned in the way as default ones.
I've solved it by wrapping overlays with a component that has all position-related styles applied, so that they stay there when using custom overlays.

UPDATE: I just noticed, that in our demos we use `GridOverlay` component.
https://mui.com/components/data-grid/components/#loading-overlay
I think this PR makes it unnecessary. Also, it's not obvious `GridOverlay` is required - as seen in #3795
I'll update the demos.

### CODE REVIEW

File: packages/grid/_modules_/grid/components/base/GridOverlaysRoot.tsx [hunk 1]
```diff
@@ -0,0 +1,52 @@
+import * as React from 'react';
+import { unstable_useEnhancedEffect as useEnhancedEffect } from '@mui/material/utils';
+import { useGridSelector } from '../../hooks/utils/useGridSelector';
+import { gridDensityHeaderHeightSelector } from '../../hooks/features/density/densitySelector';
+import { GridEvents } from '../../models/events';
+import { useGridApiContext } from '../../hooks/utils/useGridApiContext';
+import { useGridRootProps } from '../../hooks/utils/useGridRootProps';
+
+export function GridOverlaysRoot(props: React.PropsWithChildren<{}>) {
```
Comment (cherniavskii) [inline packages/grid/_modules_/grid/components/base/GridOverlaysRoot.tsx:9]: It's basically extracted from `GridOverlay.tsx`

File: docs/src/pages/components/data-grid/components/CustomLoadingOverlayGrid.js [hunk 2]
```diff
@@ -24,7 +14,7 @@ export default function CustomLoadingOverlayGrid() {
     <div style={{ height: 400, width: '100%' }}>
       <DataGrid
         components={{
-          LoadingOverlay: CustomLoadingOverlay,
+          LoadingOverlay: LinearProgress,
```
Comment (cherniavskii) [inline docs/src/pages/components/data-grid/components/CustomLoadingOverlayGrid.js:17]: I love this change!

**Comment by siriwatknp** [comment]
👋 The [migration PR](https://github.com/mui/mui-x/pull/3730) has been merged.

Please follow these steps to make sure that the contents are all updated. (Sorry for the inconvenience)

1. pull latest master from upstream to your branch
2. if your PR has changes on the `*.md` or demo files, you are likely to encounter conflict because all of them have been moved to the new folder.
   2.1 revert the change on those markdown files you did
   2.2 pull latest master from upstream (you should not see conflict)
   2.3 make the changes again at `docs/data/material/*`
3. run `yarn docs:api`
    - you might see the changes in `docs/pages/material/api/*` if your PR touches some of the components
    - it is okay if there is no changes

If you are struggle with the steps above, feel free to tag @siriwatknp

File: packages/grid/x-data-grid/src/internals/components/base/GridBody.tsx [hunk 3]
```diff
@@ -72,7 +73,9 @@ function GridBody(props: GridBodyProps) {
 
   return (
     <GridMainContainer>
-      <GridOverlays />
+      <GridOverlaysRoot>
+        <GridOverlays />
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/internals/components/base/GridBody.tsx:77]: Could `GridOverlaysRoot` be the root element of `GridOverlays`? This approach kinda breaks the internal convention for styled components:

```tsx
<GridOverlays>
  <GridOverlaysRoot>
    {currentOverlay}
  </GridOverlaysRoot>
</GridOverlays>
```

For the error overlay we can make an exception and export `GridOverlaysRoot`.

**Review by m4theushw — COMMENTED** [review]
It was a bit complicate to understand how these overlay components work together. That's a signal that we should simplify the tree. What do you think about removing `GridOverlay` from the default overlays (e.g. no result overlay) and integrate the styles into `GridOverlays`? `GridOverlay` would still be exported but it wouldn't have styles, only kept for backwards compatibility.

File: packages/grid/x-data-grid/src/internals/components/base/GridBody.tsx (hunk 3 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/internals/components/base/GridBody.tsx:77]: Agree!

File: packages/grid/x-data-grid/src/internals/components/base/GridOverlaysRoot.tsx [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+  return (
+    <div
+      style={{
+        height,
+        width: viewportInnerSize?.width ?? 0,
+        position: 'absolute',
+        top: headerHeight,
+        left: 0,
+        right: 0,
+        bottom: 0,
```
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/internals/components/base/GridOverlaysRoot.tsx]: turns out `bottom: 0` is needed here when `height: auto`, otherwise overlay won't take the whole height

File: packages/grid/x-data-grid/src/internals/components/base/GridBody.tsx (hunk 3 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/internals/components/base/GridBody.tsx]: I've kept `GridOverlayWrapper` in separate file though to avoid exporting it in the package

File: packages/grid/x-data-grid/src/internals/components/base/GridOverlayWrapper.tsx [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+
+  return (
+    <div
+      style={{
+        height,
+        width: viewportInnerSize?.width ?? 0,
+        position: 'absolute',
+        top: headerHeight,
+        bottom: 0,
+        left: 0,
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/internals/components/base/GridOverlayWrapper.tsx:46]: Not needed.

```suggestion
```

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/internals/components/base/GridOverlayWrapper.tsx:46]: `bottom` is needed when `height` is `auto`, because otherwise overlay won't take the full height and some tests will fail

Comment (m4theushw) [reply packages/grid/x-data-grid/src/internals/components/base/GridOverlayWrapper.tsx:46]: True, I forgot https://github.com/mui/mui-x/pull/3832#discussion_r811991220. Then, maybe keep `bottom=0` only when `height=auto`, otherwise it's `undefined`. That way we don't have two properties competing.

File: packages/grid/x-data-grid/src/internals/components/base/GridOverlays.tsx [hunk 6]
```diff
@@ -15,19 +16,23 @@ export function GridOverlays() {
...
 
   if (rootProps.loading) {
-    return <rootProps.components.LoadingOverlay {...rootProps.componentsProps?.loadingOverlay} />;
+    overlay = (
+      <rootProps.components.LoadingOverlay {...rootProps.componentsProps?.loadingOverlay} />
+    );
   }
 
-  return null;
+  return <GridOverlayWrapper>{overlay}</GridOverlayWrapper>;
```
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/internals/components/base/GridOverlays.tsx:37]: Nice catch!

File: packages/grid/x-data-grid/src/internals/components/base/GridOverlayWrapper.tsx (hunk 5 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/internals/components/base/GridOverlayWrapper.tsx]: Sure, done

File: packages/grid/x-data-grid/src/internals/components/base/GridOverlayWrapper.tsx [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+    return null;
+  }
+
+  return (
+    <div
+      style={{
+        height,
+        width: viewportInnerSize?.width ?? 0,
+        position: 'absolute',
+        top: headerHeight,
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/internals/components/base/GridOverlayWrapper.tsx:44]: Looking at #4026, I think we should set `top: 0` and full height (including footer) for `ErrorOverlay`, since neither grid column header nor footer are rendered.
At this point, I don't think we need `GridOverlayWrapper` for `ErrorOverlay` at all, since scrolling is not an issue if there's an error.

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/internals/components/base/GridOverlayWrapper.tsx:44]: cc @m4theushw

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/internals/components/base/GridOverlayWrapper.tsx:44]: And since `GridOverlayWrapper` is used only in `GridOverlays`, I've moved it to `GridOverlays`

**Review by m4theushw — APPROVED** [review]
Much better. 👍
