### PR TITLE
[fields] Fix Safari input selection resetting regression

### LINKED ISSUE #8283: [pickers] Picker forces focus in MacOS Safari
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

https://codesandbox.io/s/hardcore-wing-tupxmr?fontsize=14&hidenavigation=1&theme=dark

Just click different date inputs. To see problem faster click many times different inputs.

### Current behavior 😯

It's flickering and sometimes you need 5 clicks to change a focus.
Also, if you click outside of input focus will be forced to some of them.

Important!
IOS Safari, and MacOS chrome works well. Reproduce it only with MacOS Safari.

### Expected behavior 🤔

There should be no "infinity focus prison"

### Context 🔦

_No response_

### Your environment 🌎

Safari MacOS browser.
<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 19.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/WebstormProjects/ladyboom_static/node_modules/.bin/yarn
    npm: 9.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.3
  npmPackages:
    @emotion/react:  11.10.6 
    @emotion/styled:  11.10.6 
    @mui/base:  5.0.0-alpha.121 
    @mui/core-downloads-tracker:  5.11.13 
    @mui/icons-material:  5.11.11 
    @mui/lab:  5.0.0-alpha.123 
    @mui/material:  5.11.13 
    @mui/private-theming:  5.11.13 
    @mui/styled-engine:  5.11.11 
    @mui/system:  5.11.13 
    @mui/types:  7.2.3 
    @mui/utils:  5.11.13 
    @mui/x-date-pickers:  6.0.2 
    @types/react:  18.0.28 
    react:  18.2.0 
    react-dom:  18.2.0 
    typescript:  5.0.2 

```
</details>

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #8283 

The previous (initial) implementation was causing a regression due to the fact that in Safari calling `setSelectionRange` causes the input to receive focus.
Source: https://bugs.webkit.org/show_bug.cgi?id=224425

P.S. The state of pickers in Safari is not ideal, there are other, less severe issues that I observed, but they would need a separate investigation on how to solve them.

### CODE REVIEW

**Review by flaviendelangle — APPROVED** [review]
It's not easy for me to test, but I could not find any regression on Chrome

Nice work ! :partying_face:

**Comment by oliviertassinari** [comment]
I have tried a bit on BrowserStack, but it's not as smooth as reproducing locally.

1. Open https://live.browserstack.com/dashboard#os=OS+X&os_version=Ventura&browser=Safari&browser_version=16.3&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fmui.com%2Fmaterial-ui%2Fexperimental-api%2Fcss-theme-variables%2Foverview%2F&speed=1&host_ports=google.com%2C80%2C0
2. Open https://mui.com/x/react-date-pickers/date-picker/#basic-usage
3. Add

```jsx
import * as React from "react";
import {
  DatePicker,
} from "@mui/x-date-pickers";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import dayjs from "dayjs";

/**
 * how you used the components
 */
export default function App() {
  const [value] = React.useState<Dayjs>(dayjs());
  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DatePicker value={value} />
      <DatePicker value={value} />
    </LocalizationProvider>
  );
}
```

to a live demo

4. 💥

Screenshot 2023-03-21 at 20 34 46

File: packages/x-date-pickers/src/internals/hooks/useField/useField.ts [hunk 1]
```diff
@@ -334,9 +334,11 @@ export const useField = <
...
   useEnhancedEffect(() => {
     if (selectedSectionIndexes == null) {
-      if (inputRef.current!.selectionStart !== 0 || inputRef.current!.selectionEnd !== 0) {
-        // Ensure input selection range is in sync with component selection indexes
-        inputRef.current!.setSelectionRange(0, 0);
+      if (inputRef.current!.scrollLeft) {
+        // Ensure that input content is not marked as selected.
+        // setting selection range to 0 causes issues in Safari.
+        // https://bugs.webkit.org/show_bug.cgi?id=224425
+        inputRef.current!.scrollLeft = 0;
```
Comment (oliviertassinari) [inline packages/x-date-pickers/src/internals/hooks/useField/useField.ts:341]: **Off-topic**

This makes me wonder about overflows 😁

https://user-images.githubusercontent.com/3165635/226722056-795c74a2-3eda-4a31-8c9d-ace276aaf50b.mov

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

vs. 

https://user-images.githubusercontent.com/3165635/226722396-f8cc0bab-c44f-44e9-a352-a62d0bda9b40.mov

http://mui.com/x/react-date-pickers/date-time-range-field/#uncontrolled-vs-controlled

**Review by oliviertassinari — COMMENTED** [review]
Nice 👍
