### PR TITLE
[pickers] Do not loose the value of date sections not present in the format in the new field components

### LINKED ISSUE #6208: [pickers] The keyboard editing loses the timezone (tested with `dayjs`)
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Use DateTimePicker or DatePicker and dayjs-date with timezone applied
2. Change the datetime-value with the UI-selectors and see that the timezone works properly
3. Now change the datetime-value with keyboard and see that the timezone is dropped from the datetime-value
4. [Here is a codesandbox](https://codesandbox.io/s/fancy-smoke-otsmh9?file=/demo.tsx) to reproduce the issue

### Current behavior 😯

When user changes the date with keyboard and there is a dayjs-date object with timezone in the picker, then the timezone is dropped out of the value

### Expected behavior 🤔

The timezone should stay in the value.
It should work like when changing the value with the graphical user interface by clicking. (it works)

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Browser: 
    Chrome Version 105.0.5195.125 (Official Build) (arm64)
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/NordSafety.Portal/NordSafety.Portal/quentic-app-ui/node_modules/.bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Edge: Not Found
    Firefox: 104.0.2
    Safari: 16.0
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4
    @emotion/styled: ^11.10.4 => 11.10.4
    @mui/base: ^5.0.0-alpha.95 => 5.0.0-alpha.95
    @mui/core-downloads-tracker:  5.10.3
    @mui/icons-material: ^5.8.4 => 5.10.2
    @mui/lab: ^5.0.0-alpha.97 => 5.0.0-alpha.97
    @mui/material: ^5.10.3 => 5.10.3
    @mui/private-theming:  5.10.3
    @mui/styled-engine:  5.10.3
    @mui/system:  5.10.3
    @mui/types:  7.2.0
    @mui/utils:  5.10.3
    @mui/x-data-grid:  5.17.1
    @mui/x-data-grid-pro:  5.17.1
    @mui/x-date-pickers: ^5.0.2 => 5.0.2
    @mui/x-date-pickers-pro: ^5.0.2 => 5.0.2
    @mui/x-license-pro:  5.17.0
    @types/react: 18.0.17 => 18.0.17
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    styled-components: ^5.3.5 => 5.3.5
    typescript: ^4.7.4 => 4.7.4

```
</details>

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #6208

This PR makes sure that if we have a date provided in `props.value` or `props.defaultValue`:

- [x] Don't loose the timezone from `props.value` / `props.defaultValue` writing a new date 
- [x] Don't loose the parts of `props.value` / `props.defaultValue` not present in the format when writing a new date
- [x] Start writing edition tests to avoid regressions since this PR rewrites most of the editing methods

## Date parts not present in the format

[Demo before](https://codesandbox.io/s/wandering-cdn-uiyuvf)
[Demo after](https://codesandbox.io/s/peaceful-napier-z2b9op)

## Timezone

[Demo before](https://codesandbox.io/s/jovial-lovelace-ybxsm6?file=/package.json)
[Demo after](https://codesandbox.io/s/boring-bas-phrjlw?file=/demo.tsx)

### CODE REVIEW

File: packages/x-date-pickers-pro/src/MultiInputDateRangeField/useMultiInputDateRangeField.ts [hunk 1]
```diff
@@ -54,28 +53,25 @@ export const useMultiInputDateRangeField = <
...
     defaultValue: defaultValue === undefined ? undefined : defaultValue[1],
     onChange: handleEndDateChange,
   };
 
-  const rawStartDateResponse = useDateField<TInputDate, TDate, {}>(startInputProps);
-  const rawEndDateResponse = useDateField<TInputDate, TDate, {}>(endInputProps);
+  const rawStartDateResponse = useDateField<TDate, {}>(startInputProps);
+  const rawEndDateResponse = useDateField<TDate, {}>(endInputProps);
 
   // TODO: Avoid the type casting.
```
Comment (alexfauquette) [inline packages/x-date-pickers-pro/src/MultiInputDateRangeField/useMultiInputDateRangeField.ts:73]:
```suggestion
```

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/SingleInputDateRangeField.interfaces.ts [hunk 2]
```diff
@@ -7,24 +7,25 @@ import {
   DateRangeValidationProps,
 } from '../internal/hooks/validation/useDateRangeValidation';
 
-export interface UseSingleInputDateRangeFieldProps<TInputDate, TDate>
-  extends UseFieldInternalProps<DateRange<TInputDate>, DateRange<TDate>, DateRangeValidationError>,
-    Partial<Omit<DateRangeValidationProps<TInputDate, TDate>, 'value'>> {}
+export interface UseSingleInputDateRangeFieldProps<TDate>
+  extends UseFieldInternalProps<DateRange<TDate>, DateRangeValidationError>,
+    Partial<Omit<DateRangeValidationProps<TDate, TDate>, 'value'>> {}
```
Comment (alexfauquette) [inline packages/x-date-pickers-pro/src/SingleInputDateRangeField/SingleInputDateRangeField.interfaces.ts:12]: Or it's waiting from another PR to remove it in `DateRangeValidationProps`?
```suggestion
    Partial<Omit<DateRangeValidationProps<TDate>, 'value'>> {}
```

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/useSingleInputDateRangeField.ts [hunk 3]
```diff
@@ -78,67 +79,53 @@ export const dateRangeFieldValueManager: FieldValueManager<
...
-      shouldPublish,
-    };
+    return [startDate, endDate] as DateRange<any>;
   },
-  getActiveDateFromActiveSection: (value, activeSection) => {
-    const updateActiveDate = (dateName: 'start' | 'end') => (newActiveDate: any) => {
-      if (dateName === 'start') {
-        return [newActiveDate, value[1]] as DateRange<any>;
-      }
+  getActiveDateFromActiveSection: ({ state, publishValue, activeSection }) => {
```
Comment (alexfauquette) [inline packages/x-date-pickers-pro/src/SingleInputDateRangeField/useSingleInputDateRangeField.ts:98]: That function is far from simple to understand. maybe commenting the returned object could help do understand its purpose

File: packages/x-date-pickers/src/internals/hooks/useField/useField.ts [hunk 4]
```diff
@@ -12,95 +13,242 @@ import {
...
-    valueManager,
-    fieldValueManager,
-    validator,
-  } = params;
 
   const firstDefaultValue = React.useRef(defaultValue);
-  const focusTimeoutRef = React.useRef<NodeJS.Timeout | undefined>(undefined);
-
   const valueParsed = React.useMemo(() => {
     // TODO: Avoid this type casting, the emptyValues are both valid TDate and TInputDate
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/internals/hooks/useField/useField.ts:49]:
```suggestion
```

File: packages/x-date-pickers/src/internals/hooks/useField/useField.ts [hunk 5]
```diff
@@ -12,95 +13,242 @@ import {
...
-    const value =
-      firstDefaultValue.current ?? valueProp ?? (valueManager.emptyValue as unknown as TInputValue);
+    const value = firstDefaultValue.current ?? valueProp ?? valueManager.emptyValue;
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/internals/hooks/useField/useField.ts:50]: Why does the default value in `firstDefaultValue.current` has priority on `valueProp`?

**Comment by flaviendelangle** [comment]
@alexfauquette Sorry I did not ping you
I had to rework entirely this PR to handle timezone.
It is in draft for now.

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/SingleInputDateRangeField.interfaces.ts (hunk 2 above)
Comment (flaviendelangle) [reply packages/x-date-pickers-pro/src/SingleInputDateRangeField/SingleInputDateRangeField.interfaces.ts:12]: Yes, I removed `TInputDate` from the field codebase in this PR as well to simplify my work.
But I'm waiting for the main PR before touching the rest of the codebase.

File: packages/x-date-pickers/src/internals/hooks/useField/useField.ts (hunk 5 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/useField/useField.ts:49]: Because it's a mistake :laughing:

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/useField/useField.ts:49]: Fixed

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/useSingleInputDateRangeField.ts (hunk 3 above)
Comment (flaviendelangle) [reply packages/x-date-pickers-pro/src/SingleInputDateRangeField/useSingleInputDateRangeField.ts]: I need to comment the whole `FieldValueManager` interface in depth

**Comment by flaviendelangle** [comment]
@alexfauquette the edition is not perfect yet but this PR becomes too big...

File: packages/x-date-pickers-pro/src/SingleInputDateRangeField/useSingleInputDateRangeField.ts [hunk 6]
```diff
@@ -74,58 +92,37 @@ export const dateRangeFieldValueManager: FieldValueManager<
...
-      return [value[0], newActiveDate] as DateRange<any>;
-    };
-
-    if (activeSection.dateName === 'start') {
-      return {
-        value: value[0],
-        update: updateActiveDate('start'),
-      };
-    }
+    const updateDateInRange = (date: any, dateRange: DateRange<any>) =>
```
Comment (alexfauquette) [inline packages/x-date-pickers-pro/src/SingleInputDateRangeField/useSingleInputDateRangeField.ts:106]: To be more specific

```suggestion
    const updateDateInRange = (newDate: any, prevDateRange: DateRange<any>) =>
```

File: packages/x-date-pickers/src/internals/hooks/useField/useField.interfaces.ts [hunk 7]
```diff
@@ -84,7 +84,37 @@ export interface FieldSection {
...
+  edited: boolean;
+}
+
+/**
+ * Object used to access and update the active value.
+ * Mainly useful in the range fields where we need to update the date containing the active section without impacting the other one.
+ */
+interface FieldActiveDateManager<TValue, TDate> {
+  /**
+   * Date containing the current active section.
```
Comment (alexfauquette) [inline packages/x-date-pickers/src/internals/hooks/useField/useField.interfaces.ts:96]: Out of the scop of this PR:
It let me think that this will be problematic for copying a full date range, because the selection will be contained in both dates

**Review by alexfauquette — APPROVED** [review]

File: packages/x-date-pickers/src/internals/hooks/useField/useField.interfaces.ts (hunk 7 above)
Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/useField/useField.interfaces.ts:96]: Right now Ctrl A would select both dates
But not sure how to support single date copy / paste

As a user, I could expect Shift + Arrow Right to work to select several sections
Or maybe the double click (work on a text input but not on a date input in the html spec)
