### PR TITLE
[pickers] Fix `disableOpenPicker` prop behavior

### LINKED ISSUE #11618: [pickers] using `disableOpenPicker` prop with responsive DatePicker shows no dates in mobile calendar dialog
### Steps to reproduce

Link to live example: https://codesandbox.io/s/amazing-silence-ks3gq6?file=/src/Demo.tsx

Steps:
1. Use device toolbar to simulate mobile device (or alternately, look at the link on a device)
2. Click the input field to trigger the picker dialog
3. The dialog contains no days to select, only action buttons

Screenshot 2023-11-22 at 11 24 09 am

### Current behavior

When using `<DatePicker disableOpenPicker />` on a device, I want to select a date from the calendar picker but there are no dates in the dialog to choose. The dialog only contains action buttons.

### Expected behavior

When using `<DatePicker disableOpenPicker />` on a device I want to select a date from the calendar picker. There should always be a list of days/months/years to select, as well as action buttons.

### Context

We want to be able to use the `disableOpenPicker` prop which should only effect the desktop version. Happy with the different behaviour on mobile, and know that disableOpenPicker won't do anything in that context. But it would be good if there were still some dates to pick 😄   

We are now using the DesktopDatePicker only instead, but would be good to be able to use the responsive version and the `disableOpenPicker` prop.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
Issue is replicated in MUI codesandbox link using DatePicker, and simply adding disableOpenPicker

System:
    OS: macOS 13.3.1
Browser
   Chrome: 119.0.6045.159
```
</details>

**Search keywords**: pickers disableOpenPicker

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #11618.

- Avoid correlation between the `disableOpenPicker` prop intent and the fact that it forced the UI not to be rendered.
- Add a test asserting that:
  - a button is hidden (if it even should be present) when `disableOpenPicker="true"`
  - the `MuiPickersLayout-contentWrapper` element has children - is not empty

### CODE REVIEW

File: packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePickerLayout.tsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ function DesktopDateTimePickerLayout<
       {isLandscape ? shortcuts : toolbar}
       {isLandscape ? toolbar : shortcuts}
       <PickersLayoutContentWrapper
-        className={pickersLayoutClasses.contentWrapper}
+        className={clsx(pickersLayoutClasses.contentWrapper, classes?.contentWrapper)}
```
Comment (LukasTy) [inline packages/x-date-pickers/src/DesktopDateTimePicker/DesktopDateTimePickerLayout.tsx:43]: The addition of the test allowed me to discover this "bug"—the `slotProps.layout.classes` were not used in the case of `DesktopDateTimePicker` and `DesktopDateTimeRangePicker`. 🙈

**Review by flaviendelangle — APPROVED** [review]
This makes a lot of sense!

File: packages/x-date-pickers/src/internals/hooks/usePicker/usePickerViews.ts [hunk 2]
```diff
@@ -185,7 +184,7 @@ export const usePickerViews = <
   TAdditionalProps
 >): UsePickerViewsResponse<TView> => {
   const { onChange, open, onClose } = propsFromPickerValue;
-  const { views, openTo, onViewChange, disableOpenPicker, viewRenderers, timezone } = props;
+  const { views, openTo, onViewChange, viewRenderers, timezone } = props;
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/internals/hooks/usePicker/usePickerViews.ts:187]: You may be able to simplify the typing and get rid of `UsePickerViewsNonStaticProps` if `disableOpenPicker` is no longer used in this file

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePicker/usePickerViews.ts:186]: Not exactly
From what I see, `disableOpenPicker` is defined in `UsePickerViewsNonStaticProps`
Which is weird now that this prop is never used in the `usePickerViews` hook.
If you move it to `UseDesktopPickerProps`, it would be removed from the mobile pickers (which make sense since it does nothing on them).

Or maybe I'm missing something, I did not dive deeper tbh

Comment (LukasTy) [reply packages/x-date-pickers/src/internals/hooks/usePicker/usePickerViews.ts:186]: On Mobile, it currently doesn't change anything, but on range pickers, it prevents the picker from opening on click. 🤔 
That's why I didn't move anything more than needed now.

Comment (flaviendelangle) [reply packages/x-date-pickers/src/internals/hooks/usePicker/usePickerViews.ts:186]: OK
The current position of this prop's definition seems odd to me but we can move it later if we find a better interface to put it in.
