### PR TITLE
[DataGrid] Sync `date` column value when entering edit mode by pressing a digit

### LINKED ISSUE #8302: [docs] Demo BasicRowEditingGrid crashes

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #8302 

Preview: https://deploy-preview-8364--material-ui-x.netlify.app/x/react-data-grid/editing/#making-a-column-editable

The solution I implemented here was not what I intended to do in https://github.com/mui/mui-x/issues/8302#issuecomment-1477768055. When a digit key is pressed, we update the input value to be equal to the key pressed. In a `type=date` input, this updates the first date component, which could be the day or month, depending on the locale. Calling the value parser won't work because we don't know the date format (it's defined by the browser) to replace the right date component. The solution used here is a workaround involving calling `setEditCellValue` as soon as the input is rendered and a digit key press was the reason for the cell to enter edit mode.

### CODE REVIEW

File: packages/grid/x-data-grid/src/components/cell/GridEditDateCell.tsx [hunk 1]
```diff
@@ -98,24 +98,32 @@ function GridEditDateCell(props: GridEditDateCellProps) {
   const ownerState = { classes: rootProps.classes };
   const classes = useUtilityClasses(ownerState);
 
+  const hasUpdatedValueOnRender = React.useRef(false);
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/cell/GridEditDateCell.tsx:101]:
```suggestion
  const hasUpdatedEditValueOnMount = React.useRef(false);
```
Would this name better reflect what it's used for?

File: packages/grid/x-data-grid/src/components/cell/GridEditDateCell.tsx [hunk 2]
```diff
@@ -145,9 +153,23 @@ function GridEditDateCell(props: GridEditDateCellProps) {
     }
   }, [hasFocus]);
 
+  const meta = apiRef.current.unstable_getEditCellMeta(id, field);
+
+  const handleInputRef = async (el: HTMLInputElement) => {
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/cell/GridEditDateCell.tsx:158]:
```suggestion
  const handleInputRef = (el: HTMLInputElement) => {
```

**Review by cherniavskii — APPROVED** [review]
