### PR TITLE
[DataGrid] Fix row with ids matching Object prototype

### LINKED ISSUE #9264: DataGrid does throws error when row id is something on the Object prototype
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/nostalgic-albattani-84czb7

Steps:
This will happen if a row has an id of `constructor`, `toString`, `hasOwnProperty` etc

### Current behavior 😯

Error is thrown: 
```
Cannot read properties of undefined (reading 'baseCenter')
    at calculateRowProcessedSizes (https://84czb7.csb.app/node_modules/
mui/x-data-grid/hooks/features/rows/useGridRowsMeta.js:70:43
```

### Expected behavior 🤔

Everything works as intended

### Context 🔦

We have a grid that lists all of the "tags" in a users system.  The grid is selectable and we use the selected values for filtering another part of the screen so we use the tag as the id.  

User made a tag named `constructor` and things broke 

Workaround is to prepend `id: "id:" + tag` going in and remove the prefix coming out.  

### Your environment 🌎

_No response_

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by romgrk**
Closes #9264 

Avoid failing if the rows have ids like `constructor`.

### CODE REVIEW

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 1]
```diff
@@ -140,7 +140,7 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
   });
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:140]: Would reassigning it to `{}` bring back the Object prototype?
```diff
diff --git a/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx b/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
index f01c15850..a78170e61 100644
--- a/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
+++ b/packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx
@@ -536,7 +536,7 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
       prevGetRowProps.current !== getRowProps || prevRootRowStyle.current !== rootRowStyle;
 
     if (invalidatesCachedRowStyle) {
-      rowStyleCache.current = {};
+      rowStyleCache.current = Object.create(null);
     }
 
     const rows: JSX.Element[] = [];
```

**Review by MBilalShafi — APPROVED** [review]
I think it also reduces memory usage a bit, should we use it as a default pattern of object instantiation for cases like defining lookups, etc, where prototype methods are not likely to be accessed?

**Review by cherniavskii — APPROVED** [review]
