### PR TITLE
[charts] Use voronoi cells to trigger interaction with scatter items

### LINKED ISSUE #9358: [charts] Improve tooltip trigger in scatter charts
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

For now, the tooltip is triggered only when hover the scatter item. Which is working, but not perfect since scatter item can be quite small.

Most of the other libraries are using a proximity trigger based on the computation of Voronoi diagram (a graph that for each position indicates which element is the closest) Maybe adding also a threshold, such that if the closes item is at a distance larger than x don't display the tooltip

### Current behavior 😯

_No response_

### Expected behavior 🤔

_No response_

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #9358

### Changelog

- 🚀 The scatter charts now use voronoi to trigger items

Users needed to hover the item to highlight the scatter item or show the tooltip.
Now they can interact with data by triggering the closest element. See the [docs page](https://next.mui.com/x/react-charts/scatter/#interaction) for more info.

### CODE REVIEW

File: packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+import useEnhancedEffect from '@mui/utils/useEnhancedEffect';
+import { InteractionContext } from '../context/InteractionProvider';
+import { CartesianContext } from '../context/CartesianContextProvider';
+import { SVGContext, DrawingContext } from '../context/DrawingProvider';
+import { SeriesContext } from '../context/SeriesContextProvider';
+import { getValueToPositionMapper } from '../hooks/useScale';
+
+export type ChartsVoronoiHandlerProps = {
+  /**
+   * Defines the maximal distance between scatter point and mouse that triggers the interaction.
```
Comment (alexfauquette) [inline packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx:13]:
```suggestion
   * Defines the maximal distance between a scatter point and the pointer that triggers the interaction.
```

File: packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+   * If undefined, the radius is assume to be infinit.
```
Comment (alexfauquette) [inline packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx:14]:
```suggestion
   * If `undefined`, the radius is assumed to be infinite.
```

File: packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+   * @default undefined
+   */
+  voronoiMaxRadius?: number;
```
Comment (alexfauquette) [inline packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx:17]:
```suggestion
  voronoiMaxRadius?: number | undefined;
```

File: packages/x-charts/src/ScatterChart/Scatter.tsx [hunk 4]
```diff
@@ -94,7 +95,7 @@ function Scatter(props: ScatterProps) {
           key={dataPoint.id}
           cx={0}
           cy={0}
-          r={markerSize}
+          r={(dataPoint.isHighlighted ? 1.2 : 1) * markerSize}
```
Comment (alexfauquette) [inline packages/x-charts/src/ScatterChart/Scatter.tsx:98]:
```suggestion
          r={markerSize}
```

File: packages/x-charts/src/context/InteractionProvider.tsx [hunk 5]
```diff
@@ -71,6 +93,9 @@ const dataReducer: React.Reducer<Omit<InteractionState, 'dispatch'>, Interaction
       return { ...prevState, item: null };
 
     case 'updateAxis':
+      if (action.data.x === prevState.axis.x && action.data.y === prevState.axis.y) {
```
Comment (alexfauquette) [inline packages/x-charts/src/context/InteractionProvider.tsx:96]: This update is not directly for voronoi. It's a way to "improve perf" If axis do not change, we do not create a new object to avoid triggering rerender at each mouse movement

File: packages/x-charts/src/hooks/useAxisEvents.ts [hunk 6]
```diff
@@ -5,6 +5,9 @@ import { SVGContext, DrawingContext } from '../context/DrawingProvider';
 import { isBandScale } from '../internals/isBandScale';
 import { AxisDefaultized } from '../models/axis';
 
+function getAsANumber(value: number | Date) {
```
Comment (alexfauquette) [inline packages/x-charts/src/hooks/useAxisEvents.ts:8]: Fix TS errors

File: packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx [hunk 7]
```diff
@@ -0,0 +1,154 @@
...
+    }
+
+    const handleMouseOut = () => {
+      dispatch({ type: 'exitChart' });
+    };
+
+    // TODO: A perf optimisation of voronoi could be to use the last point as the intial point for the next search.
+    const handleMouseMove = (event: MouseEvent) => {
+      // Get mouse coordinate in global SVG space
+      const pt = svgRef.current!.createSVGPoint();
```
Comment (LukasTy) [inline packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx:83]: Nit: Have you considered using a full word (i.e.: `point`, `svgPoint`) for this variable?
Or do you have an argument as to why the shorthand form is better? 🤔

File: packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx [hunk 8]
```diff
@@ -0,0 +1,154 @@
...
+        }
+
+        const dataIndex = (2 * closestPointIndex - voronoiRef.current[seriesId].startIndex) / 2;
+
+        if (voronoiMaxRadius !== undefined) {
+          const pointX = voronoiRef.current.delauney.points[2 * closestPointIndex];
+          const pointY = voronoiRef.current.delauney.points[2 * closestPointIndex + 1];
+          const dist2 = (pointX - svgPt.x) ** 2 + (pointY - svgPt.y) ** 2;
+          if (dist2 > voronoiMaxRadius ** 2) {
+            // The closest point is to far to be considered.
```
Comment (LukasTy) [inline packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx:121]:
```suggestion
            // The closest point is too far to be considered.
```

File: packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx [hunk 9]
```diff
@@ -0,0 +1,154 @@
...
+import { CartesianContext } from '../context/CartesianContextProvider';
+import { SVGContext, DrawingContext } from '../context/DrawingProvider';
+import { SeriesContext } from '../context/SeriesContextProvider';
+import { getValueToPositionMapper } from '../hooks/useScale';
+
+export type ChartsVoronoiHandlerProps = {
+  /**
+   * Defines the maximal distance between a scatter point and the pointer that triggers the interaction.
+   * If `undefined`, the radius is assumed to be infinite.
+   * @default undefined
```
Comment (LukasTy) [inline packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx:15]: Have you considered going with a specific default? 🤔 
I checked that Highcharts also have the same behavior, but when exploring the demo, I felt that 25 seemed the most natural to me. 🤔 🤷 
What do others think? @flaviendelangle @joserodolfofreitas?

File: packages/x-charts/src/ScatterChart/Scatter.tsx (hunk 4 above)
Comment (LukasTy) [reply packages/x-charts/src/ScatterChart/Scatter.tsx:98]: Note: Highcharts also do increase the point radius, when highlighted, but that is probably a separate story/functionality and would need to be controllable. 🤷 🙈

File: packages/x-charts/src/ScatterChart/ScatterChart.tsx [hunk 10]
```diff
@@ -36,10 +40,16 @@ export interface ScatterChartSlotProps
...
 export interface ScatterChartProps
   extends Omit<ResponsiveChartContainerProps, 'series'>,
-    Omit<ChartsAxisProps, 'slots' | 'slotProps'> {
+    Omit<ChartsAxisProps, 'slots' | 'slotProps'>,
+    ChartsVoronoiHandlerProps {
   series: MakeOptional<ScatterSeriesType, 'type'>[];
   tooltip?: ChartsTooltipProps;
   axisHighlight?: ChartsAxisHighlightProps;
+  /**
+   * If true, the interaction will not use voronoi cell and fall back on hover events.
```
Comment (LukasTy) [inline packages/x-charts/src/ScatterChart/ScatterChart.tsx:49]:
```suggestion
   * If true, the interaction will not use the Voronoi cell and fall back to hover events.
```

File: packages/x-charts/src/context/InteractionProvider.tsx [hunk 11]
```diff
@@ -41,12 +48,18 @@ type InteractionState = {
    * The x- and y-axes currently interacting.
    */
   axis: AxisInteractionData;
+  /**
+   * Set to `true` when `VoronoiHandler is active.
```
Comment (LukasTy) [inline packages/x-charts/src/context/InteractionProvider.tsx:52]:
```suggestion
   * Set to `true` when `VoronoiHandler` is active.
```

**Review by LukasTy — APPROVED** [review]
This is a major improvement, great work! 💯 💙 
Leaving some nitpicks. 😉

File: packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx (hunk 7 above)
Comment (alexfauquette) [reply packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx:83]: It's mostly because it's a trash variable. I create it to access the `matrixTransform` method and then it's over, So I avoid to pick a meaining full variable name

An option could be to create a helper `getSVGPoint`

```js
const svgPoint = getSVGPoint(svgRef, event)
```

Comment (LukasTy) [reply packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx:83]: Gotcha. 👌 
Yup, the suggested helper does sound nice. 👍

File: packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx (hunk 9 above)
Comment (LukasTy) [reply packages/x-charts/src/ChartsVoronoiHandler/ChartsVoronoiHandler.tsx:15]: Okay, if it's only my opinion, we can disregard it. There is nothing wrong with this default. 👌 
In that case, WDYT about aligning the demo with defaults?
It's what initially tripped me a bit because after seeing the demo I expected the default radius to be `50`. 🙈
