### PR TITLE
[DataGrid] Fix `MenuProps.onClose` being overriden for single select edit component

### LINKED ISSUE #8166: [DataGrid] Edit select input does not close when MenuProps are given through slotProps
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. The table should have column with type singleSelect and should be editable.
2. Pass slotProps where baseSelect's MenuProps is overridden. Example -
```
slotProps = {{
    baseSelect: {
        MenuProps: {
          className: 'custom-class-name',  
        },
      },
    ....
```
3. Try to edit the cell and click outside the select.

### Current behavior 😯

When the cell is in edit mode and the select component is rendered, the select menu does not close on click away or on clicking escape.

### Expected behavior 🤔

The edit select should close when clicked outside the select or when escape key is pressed.

### Context 🔦

I was able to debug the error cause back to GridEditSingleSelectCell component.

- When a custom MenuProps object is passed, the default one is overridden.
- As the default one had the onClose handler, the close functionality is broken.

 https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx#L152

I was thinking of a solution like this,
```
const { MenuProps, ...otherSlotProps} = rootProps.slotProps?.baseSelect || {};
....

// In the JSX
<rootProps.slots.baseSelect
      ....
      MenuProps={{
        onClose: handleClose,
        ...MenuProps
      }}
      error={error}
      native={isSelectNative}
      fullWidth
      {...other}
      {...otherSlotProps}
    >
....
```

Can raise a PR if this solution is okay.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  MUI Version = 6.0.0
  Browser = Chrome
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by rohitnatesh**
Fixes #8166

Before: https://codesandbox.io/s/bug-reproduction-h06vvj?file=/src/App.tsx
After: https://codesandbox.io/s/bug-reproduction-forked-z0f82v?file=/src/App.tsx

### CODE REVIEW

**Review by MBilalShafi — APPROVED** [review]
Thank you for the contribution 🙏

File: packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx [hunk 1]
```diff
@@ -67,6 +67,7 @@ function GridEditSingleSelectCell(props: GridEditSingleSelectCellProps) {
 
   const baseSelectProps = rootProps.slotProps?.baseSelect || {};
   const isSelectNative = baseSelectProps.native ?? false;
+  const { MenuProps, ...baseSelectProps } = rootProps.slotProps?.baseSelect || {};
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx:70]:
```suggestion
  const { MenuProps, ...otherBaseSelectProps } = rootProps.slotProps?.baseSelect || {};
```

File: packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx [hunk 2]
```diff
@@ -144,12 +145,13 @@ function GridEditSingleSelectCell(props: GridEditSingleSelectCellProps) {
...
       MenuProps={{
         onClose: handleClose,
+        ...MenuProps,
       }}
       error={error}
       native={isSelectNative}
       fullWidth
       {...other}
-      {...rootProps.slotProps?.baseSelect}
+      {...baseSelectProps}
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/components/cell/GridEditSingleSelectCell.tsx:154]:
```suggestion
      {...otherBaseSelectProps}
```
