### PR TITLE
[DataGrid] Fix scroll restoration

### LINKED ISSUE #19180: [data grid] Scroll restoration stopped working
### Search keywords

scroll restoration

### Latest version

- [x] I have tested the latest version

### Affected products

Data Grid

### Steps to reproduce

Steps:
1. Open this link to live example: (required)
2.
3.

### Current behavior

_No response_

### Expected behavior

_No response_

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by romgrk**
Closes #19180

### CODE REVIEW

File: packages/x-virtualizer/src/features/virtualization.ts [hunk 1]
```diff
@@ -558,38 +552,35 @@ function useVirtualization(store: Store<BaseState>, params: VirtualizerParams, a
       const scroller = refs.scroller.current;
       const { top, left } = initialState.scroll;
 
-      // On initial mount, if we have columns available, we can restore the horizontal scroll immediately, but we need to skip the resulting scroll event, otherwise we would recalculate the render context at position top=0, left=restoredValue, but the initial render context is already calculated based on the initial value of scrollPosition ref.
```
Comment (romgrk) [inline packages/x-virtualizer/src/features/virtualization.ts:560]: @lauri865 I feel like we can remove this logic ([added here](https://github.com/mui/mui-x/pull/15623)), even if the render context is recalculated it shouldn't trigger an update (as long as it's equal to the previous render context).

Comment (lauri865) [reply packages/x-virtualizer/src/features/virtualization.ts:560]: But if the rows are still loading, the render context cannot be equal. There's no vertical scroll height yet at this point, so the initial render context will shift up.

Comment (lauri865) [reply packages/x-virtualizer/src/features/virtualization.ts:560]: plus it acts as a guard for performance regressions to some extent. It's incredibly easy to introduce reflows for scroll restoration. It should ideally work without the `onScrollChange` event (in testing), as scroll restoration triggers it by itself, but the render context should ideally be calculated ahead of time.

Comment (romgrk) [reply packages/x-virtualizer/src/features/virtualization.ts:560]: Does [the reproduction case you provided](https://stackblitz.com/edit/o6mumixa?file=src%2Findex.tsx,src%2FDemo.tsx) exhibits the behavior you're worried about? If so I'll check to optimize it and avoid re-renders for that case.

Comment (romgrk) [reply packages/x-virtualizer/src/features/virtualization.ts:560]: I'll restore that logic for now to try to get this fix in this week's release. I've added a visual regression test to ensure we don't break it again, and I'll investigate adding a performance regression test next week.
