### PR TITLE
[codemod] Fix `experimentalFeatures` codemod for typescript parser

### LINKED ISSUE #12874: [codemod] mui-x 7.0 migration script
### The problem in depth

Hi, 
I'm trying to upgrade an application using mui-x 6 to mui-x version 7. 
I followed the guide at https://mui.com/x/migration/migration-data-grid-v6/ but when I run the script to migrate the @mui/x-data-grid-premium no changes are applied to my code.

I installed new versions of packages @mui/x-data-grid-premium, @mui/x-date-pickers-pro, @mui/x-tree-view, 
I installed and imported the license from @mui/x-license
I ran the codemods for data grid

Here is the output of the command:

```

❯ npx @mui/x-codemod@latest v7.0.0/data-grid/preset-safe src/ 
Executing command: jscodeshift /PATH/TO/HOME/.npm/_npx/51d343d56bb93e62/node_modules/@mui/x-codemod/node_modules/jscodeshift/bin/jscodeshift.js --transform /PATH/TO/HOME/.npm/_npx/51d343d56bb93e62/node_modules/@mui/x-codemod/v7.0.0/data-grid/preset-safe --extensions js,ts,jsx,tsx --parser tsx --ignore-pattern **/node_modules/** /PATH/TO/PROJECT/src

====================================
IMPORTANT NOTICE ABOUT CODEMOD USAGE
====================================
Not all use cases are covered by codemods. In some scenarios, like props spreading, cross-file dependencies and etc., the changes are not properly identified and therefore must be handled manually.

For example, if a codemod tries to rename a prop, but this prop is hidden with the spread operator, it won't be transformed as expected.
<DatePicker {...pickerProps} />
  
After running the codemods, make sure to test your application and that you don't have any console errors.

Processing 606 files... 
Spawning 9 workers...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 6 files to free worker...
All done. 
Results: 
0 errors
606 unmodified
0 skipped
0 ok
Time elapsed: 2.187seconds

```

I also tried to run codemods for all mui-x packages and only stuff related to @mui/x-tree-view have been updated.

```
❯ npx @mui/x-codemod@latest v7.0.0/preset-safe src/           
Executing command: jscodeshift /PATH/TO/HOME/.npm/_npx/51d343d56bb93e62/node_modules/@mui/x-codemod/node_modules/jscodeshift/bin/jscodeshift.js --transform /PATH/TO/HOME/.npm/_npx/51d343d56bb93e62/node_modules/@mui/x-codemod/v7.0.0/preset-safe --extensions js,ts,jsx,tsx --parser tsx --ignore-pattern **/node_modules/** /PATH/TO/PROJECT/src

====================================
IMPORTANT NOTICE ABOUT CODEMOD USAGE
====================================
Not all use cases are covered by codemods. In some scenarios, like props spreading, cross-file dependencies and etc., the changes are not properly identified and therefore must be handled manually.

For example, if a codemod tries to rename a prop, but this prop is hidden with the spread operator, it won't be transformed as expected.
<DatePicker {...pickerProps} />
  
After running the codemods, make sure to test your application and that you don't have any console errors.

Processing 606 files... 
Spawning 9 workers...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 6 files to free worker...
All done. 
Results: 
0 errors
605 unmodified
0 skipped
1 ok
Time elapsed: 5.426seconds
```

Many thanks in advance for your help.
Mauro

### Your environment

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 14.4.1
  Binaries:
    Node: 21.7.3 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 123.0.6312.124
    Edge: Not Found
    Safari: 17.4.1
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.5 => 11.11.5 
    @mui/base: 5.0.0-beta.42 => 5.0.0-beta.42 
    @mui/core-downloads-tracker:  5.15.15 
    @mui/icons-material: 5.15.15 => 5.15.15 
    @mui/lab: ^5.0.0-alpha.170 => 5.0.0-alpha.170 
    @mui/material: ^5.15.15 => 5.15.15 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system: ^5.15.15 => 5.15.15 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-data-grid:  7.3.0 
    @mui/x-data-grid-premium: ^7.3.0 => 7.3.0 
    @mui/x-data-grid-pro:  7.3.0 
    @mui/x-date-pickers:  7.2.0 
    @mui/x-date-pickers-pro: ^7.2.0 => 7.2.0 
    @mui/x-license: ^7.2.0 => 7.2.0 
    @mui/x-tree-view: ^7.3.0 => 7.3.0 
    @types/react:  18.0.14 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript:  5.1.6 
```
</details>

**Search keywords**: upgrade migrate 7 7.0
**Order ID**: 47709

### PR DESCRIPTION
**Pull request by MBilalShafi**
Fix #12874 

Weirdly so, the **tsx** parser vs **js** parser sometimes behaves differently. It was the case with the `removeObjectProperty` utility being used in the `experimentalFeatures` codemod.

This can be visualized [here](https://astexplorer.net/#/gist/f85f47fedfe25b5b8acfad9bcbbafe60/92673ced65be16c0e5a98bc4e52df2cb83d48f9e). Try commenting the line 3 of the codemod script `export const parser = "tsx";` to have the codemod remove the `experimentalFeatures` prop properly.

The typescript parser parses the node as `ObjectProperty` while the js parser parses as `Property`.

I was not aware of this and I think we should be mindful of testing with both compilers before shipping new codemods.

### CODE REVIEW

File: packages/x-codemod/src/util/removeObjectProperty.ts [hunk 1]
```diff
@@ -48,11 +48,19 @@ export default function removeObjectProperty({
...
-      const objectProperties = j(targetAttribute).find(j.Property);
-      objectProperties.forEach((path) => {
-        const objectKey = (path.value.key as any).name as any;
-        definedKeys.push(objectKey);
-      });
+      const properties = j(targetAttribute).find(j.Property);
+      const objectProperties = j(targetAttribute).find(j.ObjectProperty);
+
+      const propertiesToProcess = properties.length > 0 ? properties : objectProperties;
+      if (propertiesToProcess.length > 0) {
```
Comment (arminmeh) [inline packages/x-codemod/src/util/removeObjectProperty.ts:55]: if the length is 0, enclosed code will not do anything anyway

File: packages/x-codemod/src/v7.0.0/data-grid/remove-stabilized-experimentalFeatures/remove-stabilized-experimentalFeatures.test.ts [hunk 2]
```diff
@@ -24,4 +24,27 @@ describe('v7.0.0/data-grid', () => {
       expect(actual).to.equal(expected, 'The transformed version should be correct');
     });
   });
+
+  describe('remove-stabilized-experimentalFeatures - with typescript', () => {
```
Comment (arminmeh) [inline packages/x-codemod/src/v7.0.0/data-grid/remove-stabilized-experimentalFeatures/remove-stabilized-experimentalFeatures.test.ts:28]: maybe this be merged with the previous `describe` and just include additional tests there

File: packages/x-codemod/src/util/removeObjectProperty.ts (hunk 1 above)
Comment (MBilalShafi) [reply packages/x-codemod/src/util/removeObjectProperty.ts]: Correct, I actually wanted to do https://github.com/mui/mui-x/pull/14150/commits/2befa5a1feea45fe80eb5cc24e6cf0cc8672df73 here. Updated!

**Review by arminmeh — APPROVED** [review]
