### PR TITLE
[DataGridPro] Make Row reordering work with pagination

### LINKED ISSUE #15351: [data grid] Row reordering does not work with pagination
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/row-reorder-v5r5q9

Steps:
1. Go to the second page in the DataGrid
2. Attempt to reorder a row on the second page
3. The row will instead disappear and cannot be reordered

### Current behavior

Rows on pages 2+ cannot be reordered.

### Expected behavior

Allow reordering rows on pages other than the first page.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 14.4.1
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v20.18.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 130.0.6723.117
    Edge: Not Found
    Safari: 17.4.1
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3
    @emotion/styled: ^11.13.0 => 11.13.0
    @mui/base: ^5.0.0-beta.61 => 5.0.0-beta.61
    @mui/core-downloads-tracker:  6.1.6
    @mui/icons-material: ^6.1.6 => 6.1.6
    @mui/lab: ^6.0.0-beta.14 => 6.0.0-beta.14
    @mui/material: ^6.0.1 => 6.1.6
    @mui/material-nextjs: ^6.1.6 => 6.1.6
    @mui/private-theming:  5.16.6
    @mui/styled-engine:  5.16.6
    @mui/system:  5.16.7
    @mui/types:  7.2.19
    @mui/utils:  5.16.6
    @mui/x-charts: ^7.22.1 => 7.22.1
    @mui/x-charts-vendor:  7.20.0
    @mui/x-data-grid:  7.22.2
    @mui/x-data-grid-pro: ^7.22.2 => 7.22.2
    @mui/x-date-pickers: ^7.22.1 => 7.22.1
    @mui/x-internals:  7.21.0
    @mui/x-license:  7.21.0
    @types/react: ^18.3.12 => 18.3.12
    react: ^18.2.0 => 18.3.1
    react-dom: ^18.2.0 => 18.3.1
    typescript: ^5.4.5 => 5.5.4
```

Used Browser: Firefox 132.0.1 (aarch64)
</details>

**Search keywords**: row,reorder,pagination
**Order ID**: 101523

### PR DESCRIPTION
**Pull request by k-rajat19**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #15351

`getRowIndexRelativeToVisibleRows` method gives index relative to the current page causing the row-reordering to not work with pages > first page. This PR adds a new lookup to fix it.

Before: https://codesandbox.io/p/sandbox/row-reorder-v5r5q9
After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-4m7hkp

### CODE REVIEW

File: packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx [hunk 1]
```diff
@@ -63,6 +64,16 @@ export const useGridRowReorder = (
...
+  const rows = gridExpandedSortedRowEntriesSelector(apiRef);
+  const lookup = React.useMemo(
+    () =>
+      rows.reduce<Record<GridRowId, number>>((acc, { id }, index) => {
+        acc[id] = index;
+        return acc;
+      }, {}),
+    [rows],
+  );
+  const getRowIndex = React.useCallback((id: GridRowId) => lookup[id], [lookup]);
```
Comment (k-rajat19) [inline packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx:76]: should we add this method to the `GridRowApi` ?

File: packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx
Comment (MBilalShafi) [inline packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx:1]: I noticed it doesn't work as expected with filtered data.

https://github.com/user-attachments/assets/9036276a-153b-4f49-a817-72b1eee73bb2

Could we make it work properly?

File: packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx [hunk 2]
```diff
@@ -63,6 +64,16 @@ export const useGridRowReorder = (
   const ownerState = { classes: props.classes };
   const classes = useUtilityClasses(ownerState);
   const [dragRowId, setDragRowId] = React.useState<GridRowId>('');
+  const rows = gridExpandedSortedRowEntriesSelector(apiRef);
```
Comment (MBilalShafi) [inline packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx:67]: Using a selector directly in the React component might yield bugs since it'll not ensure proper reactivity.
Wrapping the selector with `useGridSelector` is preferred as it ensures to re-render the component when the state value updates.

File: packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx [hunk 3]
```diff
@@ -63,6 +64,16 @@ export const useGridRowReorder = (
...
+  const lookup = React.useMemo(
```
Comment (MBilalShafi) [inline packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx:68]: I'd prefer to off-load this to a selector as it'll remove the need for a method as well as ensure proper reactivity.
Wdyt?

**Review by MBilalShafi — COMMENTED** [review]
Thank you @k-rajat19 for your contribution.
I added a few comments.
Also, Is it possible to add some test coverage for the bugfix?

File: packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx
Comment (k-rajat19) [reply packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx:1]: this seems like a separate problem of row reordering with filtered data, also not working in v7 and in v6
 v7- https://mui.com/x/react-data-grid/row-ordering/ 
 v6- https://v6.mui.com/x/react-data-grid/row-ordering/ 

but it is working at the time when row reordering is implemented in https://github.com/mui/mui-x/pull/4034
v5- https://deploy-preview-4034--material-ui-x.netlify.app/x/react-data-grid/rows/#row-reorder (working)

File: packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx (hunk 3 above)
Comment (k-rajat19) [reply packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx]: I created a new selector for it and wrapped it in `useGridSelector` while using it to ensure proper reactivity.

File: packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx
Comment (k-rajat19) [reply packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx:1]: Hi @MBilalShafi ,
I've fixed both issues and added test, let me know if you see any problem with this approach.
I've also added test for row reordering with filtered data in a follow-up PR https://github.com/mui/mui-x/pull/15455

Comment (MBilalShafi) [reply packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx:1]: Thank you for updating the PR.
I'm thinking if the new API method `getRowIndex` is really needed?

Could we use the selector in `useGridRowReorder` instead?

```diff
diff --git a/packages/x-data-grid-pro/src/hooks/features/rowReorde
diff --git a/packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx b/packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx
index ff3a1a3b57..103080b41c 100644
--- a/packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx
+++ b/packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx
@@ -10,6 +10,7 @@ import {
   gridRowMaximumTreeDepthSelector,
   useGridApiOptionHandler,
   GridRowId,
+  gridSortedRowIndexLookupSelector,
 } from '@mui/x-data-grid';
 import { gridEditRowsStateSelector } from '@mui/x-data-grid/internals';
 import { GridRowOrderChangeParams } from '../../../models/gridRowOrderChangeParams';
@@ -63,6 +64,7 @@ export const useGridRowReorder = (
   const ownerState = { classes: props.classes };
   const classes = useUtilityClasses(ownerState);
   const [dragRowId, setDragRowId] = React.useState<GridRowId>('');
+  const sortedRowIndexLookup = useGridSelector(apiRef, gridSortedRowIndexLookupSelector);
 
   React.useEffect(() => {
     return () => {
@@ -97,10 +99,10 @@ export const useGridRowReorder = (
         dragRowNode.current!.classList.remove(classes.rowDragging);
       });
 
-      originRowIndex.current = apiRef.current.getRowIndex(params.id);
+      originRowIndex.current = sortedRowIndexLookup[params.id];
       apiRef.current.setCellFocus(params.id, GRID_REORDER_COL_DEF.field);
     },
-    [apiRef, isRowReorderDisabled, logger, classes.rowDragging],
+    [apiRef, isRowReorderDisabled, logger, classes.rowDragging, sortedRowIndexLookup],
   );
 
   const handleDragOver = React.useCallback<GridEventListener<'cel
lDragOver' | 'rowDragOver'>>(
@@ -126,7 +128,7 @@ export const useGridRowReorder = (
         : event.clientY;
 
       if (params.id !== dragRowId) {
-        const targetRowIndex = apiRef.current.getRowIndex(params.
id);
+        const targetRowIndex = sortedRowIndexLookup[params.id];
 
         const dragDirection = mouseMovementDiff > 0 ? Direction.D
OWN : Direction.UP;
         const currentReorderState: ReorderStateProps = {
@@ -148,7 +150,7 @@ export const useGridRowReorder = (
 
       previousMousePosition = { x: event.clientX, y: event.client
Y };
     },
-    [dragRowId, apiRef, logger],
+    [dragRowId, apiRef, logger, sortedRowIndexLookup],
   );
 
   const handleDragEnd = React.useCallback<GridEventListener<'rowD
ragEnd'>>(
@@ -178,7 +180,7 @@ export const useGridRowReorder = (
         // Emit the rowOrderChange event only once when the reord
ering stops.
         const rowOrderChangeParams: GridRowOrderChangeParams = {
           row: apiRef.current.getRow(dragRowId)!,
-          targetIndex: apiRef.current.getRowIndex(params.id),
+          targetIndex: sortedRowIndexLookup[params.id],
           oldIndex: originRowIndex.current!,
         };
 
@@ -187,7 +189,7 @@ export const useGridRowReorder = (
 
       setDragRowId('');
     },
-    [apiRef, dragRowId, isRowReorderDisabled, logger],
+    [apiRef, dragRowId, isRowReorderDisabled, logger, sortedRowIn
dexLookup],
   );
 
   useGridApiEventHandler(apiRef, 'rowDragStart', handleDragStart)
;
```

File: packages/x-data-grid/src/hooks/features/sorting/gridSortingSelector.ts [hunk 4]
```diff
@@ -73,3 +73,17 @@ export const gridSortColumnLookupSelector = createSelectorMemoized(
     return result;
   },
 );
+
+/**
+ * @category Sorting
+ * @ignore - do not document.
+ */
+export const gridSortedRowIndexLookupSelector = createSelectorMemoized(
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/sorting/gridSortingSelector.ts:81]: Do we have a use-case for it in the userland? If not, how about exporting it from `@mui/x-data-grid/internals` instead?

**Review by MBilalShafi — COMMENTED** [review]
Thank you for fixing the case with the filtered data, is it possible to add some test coverage avoid it being introduced again?
Or would it make sense to extract this specific fix in another PR and add the test along with that?

File: packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx
Comment (k-rajat19) [reply packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorder.tsx:1]: we can directly use the selector as well 👍

**Comment by k-rajat19** [comment]
> Thank you for fixing the case with the filtered data, is it possible to add some test coverage to avoid it being introduced again? Or would it make sense to extract this specific fix in another PR and add the test along with that?

A PR has already opened https://github.com/mui/mui-x/pull/15455 for that , if you want I can add those changes here otherwise we can do this in that PR after this one lands.

File: packages/x-data-grid/src/hooks/features/sorting/gridSortingSelector.ts (hunk 4 above)
Comment (MBilalShafi) [reply packages/x-data-grid/src/hooks/features/sorting/gridSortingSelector.ts:81]: I pushed a commit to further support this: https://github.com/mui/mui-x/pull/15355/commits/1fa97339560b85b40b1c6461758de5ef0a9ec6a4

File: packages/x-data-grid/src/hooks/features/sorting/gridSortingSelector.ts [hunk 5]
```diff
@@ -73,3 +73,17 @@ export const gridSortColumnLookupSelector = createSelectorMemoized(
...
+  gridSortedRowIdsSelector,
+  (sortedIds) => {
+    return sortedIds.reduce<Record<GridRowId, number>>((acc, id, index) => {
+      acc[id] = index;
+      return acc;
+    }, {});
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/sorting/gridSortingSelector.ts:87]: Nit: I think we could live without Object prototype with the selector to strip down some bytes of memory.
```suggestion
    }, Object.create(null));
```

**Review by MBilalShafi — APPROVED** [review]
Thank you. LGTM. 🎉
