### PR TITLE
[charts] Fix `minBarSize` when y-axis is reversed

### LINKED ISSUE #19901: Have minBarSize with reverse Y axis is getting the bar below the desired line.
### Steps to reproduce

Steps:
1. Open this link to live example: https://stackblitz.com/edit/yjvfu3af?file=src%2FDemo.tsx

### Current behavior

When having minBarSize with reverse Y axis position of bar is incorrect
Image

### Expected behavior

_No response_

### Context

Not sure if its related to this https://github.com/mui/mui-x/issues/19893

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>
System:
OS: Linux 5.0 undefined
Binaries:
Node: 20.19.1 - /usr/local/bin/node
npm: 10.8.2 - /usr/local/bin/npm
pnpm: 8.15.6 - /usr/local/bin/pnpm
Browsers:
Chrome: Not Found
Firefox: Not Found
npmPackages:
@emotion/react: latest => 11.14.0
@emotion/styled: latest => 11.14.1
@mui/core-downloads-tracker: 7.3.4
@mui/material: latest => 7.3.4
@mui/private-theming: 7.3.3
@mui/styled-engine: 7.3.3
@mui/system: 7.3.3
@mui/types: 7.4.7
@mui/utils: 7.3.3
@mui/x-charts: latest => 8.14.0
@mui/x-charts-vendor: 8.14.0
@mui/x-internal-gestures: 0.3.3
@mui/x-internals: 8.14.0
@types/react: latest => 19.2.2
react: latest => 19.2.0
react-dom: latest => 19.2.0
typescript: latest => 5.9.3

**Search keywords**: minBarSize, reverse

### PR DESCRIPTION
**Pull request by bernardobelchior**
Fixes #19901.

Fix `minBarSize` not working properly when axis is reversed.

[Before](https://app.argos-ci.com/mui/mui-x/builds/42243/208017650):

image

[After](https://app.argos-ci.com/mui/mui-x/builds/42262/208094591):

image

### CODE REVIEW

File: packages/x-charts/src/BarChart/useBarPlotData.ts [hunk 1]
```diff
@@ -185,32 +183,14 @@ function getBandSize({
...
-  const isVerticalAndPositive = isVertical && baseValue >= 0;
-  const isHorizontalAndNegative = !isVertical && baseValue < 0;
-
-  if (isSizeLessThanMin && (isVerticalAndPositive || isHorizontalAndNegative)) {
-    return {
-      barSize,
-      startCoordinate: maxValueCoord - barSize,
-    };
+  if (reverse) {
+    invertStartCoordinate = !invertStartCoordinate;
```
Comment (alexfauquette) [inline packages/x-charts/src/BarChart/useBarPlotData.ts]:
```suggestion
  if (reverse) {
    return !invertStartCoordinate;
```

File: packages/x-charts/src/BarChart/useBarPlotData.ts [hunk 2]
```diff
@@ -185,32 +183,14 @@ function getBandSize({
...
-      startCoordinate: minValueCoord,
-    };
-  }
-
-  const isSizeLessThanMin = maxValueCoord - minValueCoord < minBarSize;
-  const barSize = isSizeLessThanMin ? minBarSize : maxValueCoord - minValueCoord;
+function shouldInvertStartCoordinate(verticalLayout: boolean, baseValue: number, reverse: boolean) {
+  const isVerticalAndPositive = verticalLayout && baseValue > 0;
+  const isHorizontalAndNegative = !verticalLayout && baseValue < 0;
+  let invertStartCoordinate = isVerticalAndPositive || isHorizontalAndNegative;
```
Comment (alexfauquette) [inline packages/x-charts/src/BarChart/useBarPlotData.ts]:
```suggestion
  const invertStartCoordinate = isVerticalAndPositive || isHorizontalAndNegative;
```
