### PR TITLE
[DataGrid] Fix scroll to cell logic for keyboard navigating cells and drag selection with pinned columns

### LINKED ISSUE #14545: MUI DataGrid (premium v7) automatically scrolls horizontally if we have pinned columns that exceed or take the half-view screen
### Search keywords

Horizontal scroll with pinned columns

### Latest version

- [X] I have tested the latest version

### Affected products

Data Grid

### Steps to reproduce

1. Create a DataGrid component.
2. Pin the first 7-8 columns (or however many columns take up at least half of the screen width).
3. Ensure there are enough unpinned columns so that horizontal scrolling is enabled.
4. Select an unpinned cell, and use the arrow keys to move across the grid. The selected cell will move beneath the pinned columns.
5. Select an unpinned cell, then drag to multi-select cells. This will also trigger automatic horizontal scrolling.

### Current behavior

When we pin the columns so that they take up half of your screen (like 5/6 columns with respective widths), the Datagrid automatically scrolls horizontally in two scenarios
Scenario 1. Select an un-pinned cell and move the selection in any direction (top, bottom, right) using the up, down, right arrow keys
Scenario 2. Select an un-pinned cell and try to multi-select cells using either mouse drag or shift + arrow keys

### Expected behavior

It shouldn't scroll horizontally and cell selection should behave as default.

### Context

Findings: In Datagrid v7, the data grid is built such that the selected cell stays in the middle till we reach the extreme right, but with more pinned columns this logic automatically scrolls the whole grid horizontally and selected cell moves under pinned columns.
Code Snippet:
```
import Box from "@mui/material/Box";
import { DataGridPremium, GridColDef, GridValueGetter } from "@mui/x-data-grid-premium";

const rows = Array.from({ length: 30 }, (_, id) => ({
  id: id + 1,
  firstName: `First${id + 1}`,
  lastName: `Last${id + 1}`,
  age: Math.floor(Math.random() * 100),
  occupation: `Occupation${id + 1}`,
  city: `City${id + 1}`,
  country: `Country${id + 1}`,
  email: `email${id + 1}@example.com`,
  phone: `+1-555-000${id + 1}`,
  company: `Company${id + 1}`,
  department: `Department${id + 1}`,
  salary: Math.floor(Math.random() * 100000),
  hireDate: new Date(`2023-0${(id % 9) + 1}-01`),
  performanceRating: (Math.random() * 5).toFixed(2),
  isActive: id % 2 === 0,
  status: id % 3 === 0 ? "Active" : "Inactive",
  role: `Role${id + 1}`,
  team: `Team${id + 1}`,
  manager: `Manager${id + 1}`,
  region: `Region${id + 1}`,
}));

const getFullName: GridValueGetter<(typeof rows)[number], unknown> = (value, row) => {
  return `${row.firstName || ""} ${row.lastName || ""}`;
};

const columns: GridColDef[] = [
  { field: "firstName", headerName: "First name", width: 130 },
  { field: "lastName", headerName: "Last name", width: 130 },
  {
    field: "fullName",
    headerName: "Full name",
    width: 160,
    valueGetter: getFullName,
  },
  { field: "age", headerName: "Age", width: 90, type: "number" },
  { field: "occupation", headerName: "Occupation", width: 160 },
  { field: "city", headerName: "City", width: 130 },
  { field: "country", headerName: "Country", width: 130 },
  { field: "email", headerName: "Email", width: 200 },
  { field: "phone", headerName: "Phone", width: 150 },
  { field: "company", headerName: "Company", width: 160 },
  { field: "department", headerName: "Department", width: 150 },
  { field: "salary", headerName: "Salary", width: 120, type: "number" },
  { field: "hireDate", headerName: "Hire Date", width: 130, type: "date" },
  { field: "performanceRating", headerName: "Rating", width: 110, type: "number" },
  { field: "isActive", headerName: "Active", width: 100, type: "boolean" },
  { field: "status", headerName: "Status", width: 120 },
  { field: "role", headerName: "Role", width: 130 },
  { field: "team", headerName: "Team", width: 130 },
  { field: "manager", headerName: "Manager", width: 130 },
  { field: "region", headerName: "Region", width: 130 },
];

export default function Test() {
  return (
    <Box sx={{ height: 400, width: "100%" }}>
      <DataGridPremium
        rows={rows}
        columns={columns}
        cellSelection
        initialState={{
          pinnedColumns: {
            left: ["firstName", "lastName", "fullName", "age", "occupation", "city"],
          },
        }}
      />
    </Box>
  );
}
```

### Your environment

  System:
    OS: macOS 14.2
  Binaries:
    Node: 20.14.0 - ~/.volta/tools/image/node/20.14.0/bin/node
    npm: 10.7.0 - ~/.volta/tools/image/node/20.14.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 128.0.6613.120
    Edge: Not Found
    Safari: 17.2
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.16.7 
    @mui/icons-material: ^5.16.7 => 5.16.7 
    @mui/lab: ^5.0.0-alpha.173 => 5.0.0-alpha.173 
    @mui/material: ^5.16.7 => 5.16.7 
    @mui/private-theming:  5.16.6 
    @mui/styled-engine:  5.16.6 
    @mui/system:  5.16.7 
    @mui/types:  7.2.16 
    @mui/utils:  5.16.6 
    @mui/x-data-grid:  7.14.0 
    @mui/x-data-grid-premium: ^7.13.0 => 7.14.0 
    @mui/x-data-grid-pro:  7.14.0 
    @mui/x-date-pickers:  7.14.0 
    @mui/x-date-pickers-pro: ^7.13.0 => 7.14.0 
    @mui/x-internals:  7.14.0 
    @mui/x-license: ^7.13.0 => 7.14.0 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react: ^18.0.6 => 18.3.3 
    react: ^18.1.0 => 18.3.1 
    react-dom: ^18.1.0 => 18.3.1 
    styled-components:  5.3.11 
    typescript: ^5.1.6 => 5.5.2 

### Order ID or Support key 💳 (optional)

85118

### PR DESCRIPTION
**Pull request by KenanYusuf**
Fixes two issues related to navigating the data grid via scroll + keyboard with pinned columns. For specific testing conditions, see the issue below.

Fixes #14545

We are using the `viewportInnerSize` to calculate the new scroll position, but this value does not include the width of pinned columns https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/dimensions/useGridDimensions.ts#L201-L204. The fix was to use `viewportOuterSize` instead, which does account for pinned columns.

**Preview URL**: https://codesandbox.io/p/sandbox/laughing-roentgen-q5l87d

## Issue 1

Navigating via arrow keys moves focused items under pinned columns.

**Before**

https://github.com/user-attachments/assets/259598f8-0d82-4c94-8faf-d52757ea7f59

**After**

https://github.com/user-attachments/assets/5238a9f7-e7f8-47ba-af62-008e56e7fb06

## Issue 2

Selecting item via drag causes the grid to scroll automatically.

**Before**

https://github.com/user-attachments/assets/6d1cbfa6-07f3-46e2-aaab-eb9c4e4eb055

**After**

https://github.com/user-attachments/assets/72706ac3-0f06-4742-84bb-dda2a3e7d84e

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Review by arminmeh — APPROVED** [review]

**Review by arminmeh — CHANGES_REQUESTED** [review]
I found an issue with the cell selection.

Selecting away from pinned columns works fine, but selection towards them does not trigger scroll

https://github.com/user-attachments/assets/51fbf168-2fe5-4e30-aa9f-b0a6b8045825

**Comment by KenanYusuf** [comment]
@arminmeh I observed this too. You have to move the cursor to the edge of the outer viewport, not just passed the pinned columns.

This behaviour is consistent with v6:

https://github.com/user-attachments/assets/e2692b70-8422-43ec-aba0-6a0da3f1ab6f

**Comment by arminmeh** [comment]
I think that the problem I have pointed out is actually another issue with the cell selection and pinned columns.
In my video you can see the selected cells together with the cells in the pinned columns.

In v6 the prop was called `unstable_cellSelection`
After updating your last example, I can see that the selection behavior is the same. Once you go over the pinned column, all cells in between are selected.
But in v6 they are not visible.

**Comment by KenanYusuf** [comment]
@arminmeh I see what you mean.

There seems to be a glitch with showing selected cells underneath pinned cells too.

This is a frame from your video:

image

**Review by arminmeh — APPROVED** [review]

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts
Comment (cherniavskii) [inline packages/x-data-grid/src/components/containers/GridRootStyles.ts:1]: Is this refactor only to reduce duplications? Or were there other changes here as well?

Comment (KenanYusuf) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:1]: There were changes. Previously, we were creating 3 unique colors for pinned cells in 3 different states:
- Row hovered
- Row selected
- Row selected and hovered

To re-create the various background colors that regular cells can have, due to stacked transparent background colors, we also need to create unique colors for these states for pinned cells:
- Row hovered + cell selected
- Row hovered + cell selected and hovered
- Row selected + cell selected
- Row selected + cell selected and hovered
- Row selected and hovered + cell selected and hovered

I created this [Figma file](https://www.figma.com/design/cRRgSZ2pT666F0miQqbOkL/Cell-%26-Row-Selection?node-id=0-1&t=Lger6fmfGDTLJqUI-1) to help visualize the various states a selectable cell can be in.

State color matrix

I created the `getPinnedBackgroundStyles` function to help generate the various background colors consistently across the various states.

Comment (cherniavskii) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:1]: Thanks for the explanation!

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 1]
```diff
@@ -171,15 +203,35 @@ export const GridRootStyles = styled('div', {
...
     ? selectedBackground
     : blend(pinnedBackground, selectedBackground, selectedOpacity);
-  const pinnedSelectedHoverBackground = t.vars
-    ? hoverColor
-    : blend(pinnedSelectedBackground, hoverColor, hoverOpacity);
+  const pinnedSelectedStyles = getPinnedBackgroundStyles({
+    hoverOpacity,
+    selectedOpacity,
+    selectedBackground,
+    backgroundColor: pinnedSelectedBackgroundColor,
```
Comment (cherniavskii) [inline packages/x-data-grid/src/components/containers/GridRootStyles.ts:223]: `pinnedSelectedBackgroundColor` here can be either a CSS color value or a CSS variable.
`getPinnedBackgroundStyles` assumes it's a CSS color value and uses the `blend` function, which won't work with CSS variables.
This made me realize that we missed a test for the DataGrid using inside of the `CssVarsProvider`, so I opened https://github.com/mui/mui-x/pull/14662 to add one.

We have to make sure we don't try to `blend` CSS variables.
This also reminds me about this PR: https://github.com/mui/mui-x/pull/12901.

Comment (KenanYusuf) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:223]: @cherniavskii I am not sure of the best way to handle this. 

`color-mix` would work well besides the versions of Safari that do not support it. It doesn't look like there is another way to blend colors with CSS variables otherwise.

I don't know if we can add an exception to our browser support specifically for cases where `CssVarsProvider` is used? 😅 

The only other way I can think to achieve this effect with CSS variables is by having an inner element in pinned cells to apply the transparent hover/selected background-color to. Not sure this is viable though, considering the performance implications of having an extra element for every pinned cell. https://codepen.io/KenanYusuf/pen/WNqVXqM

Comment (goldst) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:223]: @KenanYusuf, not sure it helps, but we ran into similar problems when migrating to DataGrid v7 due to our custom styles. Some of our pinned cells had backgrounds with alpha values. Therefore, the non-pinned cells were visible behind them.

We attempted to solve this using `color-mix`. The result worked but was very hard to read and extend in our case.

We opted for the two-element approach you described, but instead of adding one additional element per cell, we added one sticky background element with the width of the pinned cells.

<details><summary>Details</summary>
<p>

grafik

We added the sticky background to the row using DataGrid `slots`. We had to place it between row and pinned cells using `z-index`, but you could probably just make it a container element of the pinned cells.

The additional sticky background always has the same background color as the row. If the row is selected using row selection, the color of the additional sticky background changes too. If only a pinned cell is selected using cell selection, only the background color of the pinned cell changes.

</p>
</details>

We didn't run into noticeable performance problems. If you consider pinned left and pinned right, it's only two more divs in each row.

**Review by cherniavskii — APPROVED** [review]
🎉
