### PR TITLE
[DataGrid] Fix Voice Over reading the column name twice

### LINKED ISSUE #9954: mui data grid column name has been read out twice by mac voice over
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

1 open link with Chrome or Safari
2. open mac built-in voice over
3. use tab to tab into grid and then use left and right navigate to grid column name
4. column name has been read out twice

### Current behavior 😯

_No response_

### Expected behavior 🤔

_No response_

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### PR DESCRIPTION
**Pull request by arminmeh**
Fixes #9954 

`aria-label` was only added if the default header component was used (`GridColumnHeaderTitle`).
That component adds label as its content which is read by the voice over, so the `aria-label` is not needed at all.

### CODE REVIEW

**Review by KenanYusuf — APPROVED** [review]
Tested with VoiceOver and it is working as expected.

File: packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx [hunk 1]
```diff
@@ -111,7 +111,6 @@ const GridGenericColumnHeaderItem = React.forwardRef(function GridGenericColumnH
       tabIndex={tabIndex}
       aria-colindex={colIndex + 1}
       aria-sort={ariaSort}
-      aria-label={headerComponent == null ? label : undefined}
```
Comment (cherniavskii) [inline packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx:114]: I looked into this issue some time ago, but couldn't make it work properly.
Even with this change, it doesn't seem to work as expected – see the recording:


https://github.com/user-attachments/assets/14388fa9-5255-4a82-84b6-c52770f8bbf9

Any idea why it starts reading the column name twice?

Comment (KenanYusuf) [reply packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx:114]: Which keys are you using to navigate the header items? 🤔

Comment (cherniavskii) [reply packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx:114]: `Control` + `Option` + arrow keys

Comment (arminmeh) [reply packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx:112]: I have made another PR for that
https://github.com/mui/mui-x/pull/14484

Since it is out of the scope of the linked issue, I have split it to cover the bug faster

File: packages/x-data-grid-pro/src/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx [hunk 2]
```diff
@@ -29,5 +29,5 @@ export const GRID_DETAIL_PANEL_TOGGLE_COL_DEF: GridColDef = {
     return expandedRowIds.includes(rowId);
   },
   renderCell: (params) => <GridDetailPanelToggleCell {...params} />,
-  renderHeader: () => null,
+  renderHeader: (params) => <div aria-label={params.colDef.headerName} />,
```
Comment (arminmeh) [inline packages/x-data-grid-pro/src/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx:32]: Before, the condition `headerComponent == null ? label : undefined` in `GridGenericColumnHeaderItem` was ensuring that the aria label is added to this column without actually rendering anything.
Now the column definition holds that logic in itself

File: packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx (hunk 1 above)
Comment (arminmeh) [reply packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx:112]: I found the reason
it looks like the `Tooltip` component is adding another `aria-label` on the wrapped component

https://github.com/mui/mui-x/blob/cf441ece0f6c2e07acf49438ee14473bc4278b39/packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderTitle.tsx#L77-L85

we don't pass it here, but consoling `other` in

https://github.com/mui/mui-x/blob/cf441ece0f6c2e07acf49438ee14473bc4278b39/packages/x-data-grid/src/components/columnHeaders/GridColumnHeaderTitle.tsx#L34-L50

shows `aria-label` prop

For string content, `aria-label` should not be attached to the element. For now, I will filter it out in our component, but I will make a PR to the component to fix it there as well

Comment (KenanYusuf) [reply packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx:112]: > Control + Option + arrow keys

Ah makes sense, I tested with the arrow keys only, not the virtual cursor.

> I think that the voice over wants to connect header name with the cell when you use Control + Option + arrow keys. If you navigate through content you will notice that it reads out the data plus the column name which is great in that scenario.

Strange bug.

> Anyway, I think that we can ignore that issue and have at least regular arrow key navigation fixed

I tested again with the latest changes and it's working as expected with arrow keys at least 👍

File: packages/x-data-grid-pro/src/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx (hunk 2 above)
Comment (cherniavskii) [reply packages/x-data-grid-pro/src/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx:32]: How about we do this internally instead?

```diff
diff --git a/packages/x-data-grid-pro/src/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx b/packages/x-data-grid-pro/src/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx
index 0fc2a55a78..ce3a18b882 100644
--- a/packages/x-data-grid-pro/src/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx
+++ b/packages/x-data-grid-pro/src/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx
@@ -29,5 +29,5 @@ export const GRID_DETAIL_PANEL_TOGGLE_COL_DEF: GridColDef = {
     return expandedRowIds.includes(rowId);
   },
   renderCell: (params) => <GridDetailPanelToggleCell {...params} />,
-  renderHeader: (params) => <div aria-label={params.colDef.headerName} />,
+  renderHeader: () => null,
 };
diff --git a/packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx b/packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx
index 412bb46be9..91ecd13dc5 100644
--- a/packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx
+++ b/packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx
@@ -120,7 +120,7 @@ const GridGenericColumnHeaderItem = React.forwardRef(function GridGenericColumnH
         <div className={classes.titleContainer} role="presentation">
           <div className={classes.titleContainerContent}>
             {headerComponent !== undefined ? (
-              headerComponent
+              headerComponent || <div aria-label={label} />
             ) : (
               <GridColumnHeaderTitle label={label} description={description} columnWidth={width} />
             )}

```

Comment (arminmeh) [reply packages/x-data-grid-pro/src/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx:32]: I would rather keep it with the definition that actually needs it and keep the generic component clean from it.
Otherwise we have this (for me) weird algorithm where we say:
- If you don't provide a component a fallback will be rendered
- Else If your component is `null` another fallback will be rendered
- Else your component is rendered

Searching the code, I didn't find any other place where `null` is returned (there is another definition with `' '`, but that will not end up as this special condition)

Do you think that someone relies on the current logic and that the things will break?

Comment (cherniavskii) [reply packages/x-data-grid-pro/src/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx:32]: I was mostly considering compatibility here, but also a better default – no need to know this trick to make the column header accessible.
The empty column header is a rare case though.
I don't have a strong opinion on this one, I'm OK with your approach 👍🏻

Comment (MBilalShafi) [inline packages/x-data-grid-pro/src/hooks/features/detailPanel/gridDetailPanelToggleColDef.tsx:32]: Nitpick:
```suggestion
  renderHeader: ({ colDef }) => <div aria-label={colDef.headerName} />,
```

File: packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx
Comment (MBilalShafi) [inline packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx:1]: Might be unrelated to this PR but Safari reads normal cells twice too (used to do for header cells too but fixed with this PR)

https://github.com/user-attachments/assets/f533c774-9338-4e88-b280-996475e1d9f5

**Review by MBilalShafi — APPROVED** [review]
Looks great on Firefox and Chrome with Arrow keys. 🎉 
Found a small issue on Safari, feel free to handle it separately if it's unrelated.

File: packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx
Comment (arminmeh) [reply packages/x-data-grid/src/components/columnHeaders/GridGenericColumnHeaderItem.tsx:1]: yes, this is what I saw as well
since it is not mentioned in the original issue, I have opened a [separate PR](https://github.com/mui/mui-x/pull/14484) to address this
