### PR TITLE
[DateTimeRangePicker] Fix validation behavior

### LINKED ISSUE #12048: [pickers] DateTimeRangePicker `disableFuture` disables Time in the Past
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/quizzical-mclaren-2jd2gp

Steps:
1. Select date in the past.
2. Try to Select Time in the future.

### Current behavior

Not being able to select Time.

### Expected behavior

Being able to select all times for days that are in the past.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DateTimeRangePicker, disableFuture

**Order ID**: 85157

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #12048

Follow-up on #9528

Closes #12101

- initialize `disableIgnoringDatePartForTimeValidation` accordingly (the main issue fix) - same as in `DateTimePicker`
- Initialize `minDate` and `maxDate` based on `minDateTime` and `maxDateTime` respectively
- Add `describes` tests to `DesktopDateTimeRangePicker`, `MobileDateTimeRangePicker`, and `DateTimeRangePicker` 
- Add a few specific (validation) `DateTimeRangePicker` tests
- Fix to not render `DateTimeRangePickerToolbar` (root element) when it is `hidden`
- Fix `DateTimeRangePickerToolbar` `titleId` (aria-labelledby on dialog) behavior (for mobile)
- Set `aria-disabled` on a disabled `MultiDigitalClockSection` item

### CODE REVIEW

File: packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx [hunk 1]
```diff
@@ -187,7 +187,9 @@ export const MultiSectionDigitalClockSection = React.forwardRef(
         {...other}
       >
         {items.map((option, index) => {
-          if (skipDisabled && option.isDisabled?.(option.value)) {
+          const isItemDisabled = option.isDisabled?.(option.value);
+          const isDisabled = disabled || isItemDisabled;
+          if (skipDisabled && isItemDisabled) {
```
Comment (michelengelen) [inline packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx:192]: shouldn't this be `isDisabled`? 🤔 

```suggestion
          if (skipDisabled && isDisabled) {
```

File: test/utils/pickers/describeRangeValidation/testDayViewRangeValidation.tsx [hunk 2]
```diff
@@ -5,15 +5,10 @@ import { adapterToUse } from 'test/utils/pickers';
 
 const isDisable = (el: HTMLElement) => el.getAttribute('disabled') !== null;
```
Comment (michelengelen) [inline test/utils/pickers/describeRangeValidation/testDayViewRangeValidation.tsx:6]: unrelated, but shouldn't this be called `isDisabled`?

File: test/utils/pickers/describeValue/testControlledUnControlled.tsx [hunk 3]
```diff
@@ -259,7 +257,10 @@ export const testControlledUnControlled: DescribeValueTestSuite<any, any> = (
         expect(fieldRoot).to.have.class(inputBaseClasses.error);
         expect(fieldRoot).to.have.attribute('aria-invalid', 'true');
 
-        if (params.type === 'date-range' && !params.isSingleInput) {
+        if (
+          (params.type === 'date-range' || params.type === 'date-time-range') &&
+          !params.isSingleInput
+        ) {
```
Comment (michelengelen) [inline test/utils/pickers/describeValue/testControlledUnControlled.tsx:263]:
```suggestion
        if (isRangeType && !params.isSingleInput) {
```

File: test/utils/pickers/openPicker.ts [hunk 4]
```diff
@@ -18,11 +18,12 @@ export type OpenPickerParams =
     };
 
 export const openPicker = (params: OpenPickerParams) => {
+  const isRangePicker = params.type === 'date-range' || params.type === 'date-time-range';
```
Comment (michelengelen) [inline test/utils/pickers/openPicker.ts:21]: nit, but to be consistent:

```suggestion
  const isRangeType = params.type === 'date-range' || params.type === 'date-time-range';
```

**Review by michelengelen — CHANGES_REQUESTED** [review]
just a few details! looks good otherwise! 💪🏼

File: test/utils/pickers/describeValue/testControlledUnControlled.tsx (hunk 3 above)
Comment (LukasTy) [reply test/utils/pickers/describeValue/testControlledUnControlled.tsx:263]: Sadly, can't do it.
TS does not resolve the `params` type correctly in that case. 🙈 
Screenshot 2024-02-28 at 16 25 52

Comment (michelengelen) [reply test/utils/pickers/describeValue/testControlledUnControlled.tsx:263]: eh ... but that wasn't my proposed change! 
`params.type === 'date-range' || params.type === 'date-time-range'` is the same as `isRangeType`, which gets defined in line 31

File: packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx (hunk 1 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx:192]: Not that such combination even makes sense—we would end up with empty list of items 😆 
That is already the case anyways, because `option.isDisabled` already does this check anyways.
But making sure and having the redundancy can't hurt. 👌

File: test/utils/pickers/describeValue/testControlledUnControlled.tsx (hunk 3 above)
Comment (LukasTy) [reply test/utils/pickers/describeValue/testControlledUnControlled.tsx:263]: How is it not the same proposed change? 🤔 
The problem is that TS can't infer that `isSingleInput` exists on `params` with that kind of check 🙈 
I've looked into it an will replace the `[].includes` check for `=== || ===` to make it work. 👌

Comment (michelengelen) [reply test/utils/pickers/describeValue/testControlledUnControlled.tsx]: oh, you meant your change? I was referring to my suggestion! :D

File: test/utils/pickers/openPicker.ts (hunk 4 above)
Comment (LukasTy) [reply test/utils/pickers/openPicker.ts]: Kind of made sense - updated. 👌

**Review by michelengelen — APPROVED** [review]

File: packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx (hunk 1 above)
Comment (LukasTy) [reply packages/x-date-pickers/src/MultiSectionDigitalClock/MultiSectionDigitalClockSection.tsx]: Updated to check for `disabled` only here, removed the check on the `option` level. 👌
