### PR TITLE
[DataGrid] Add generics to `GridActionsColDef` to match `GridColDef`

### LINKED ISSUE #4660: [data grid] getActions generic not working
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

`getActions` is not working with generic like `valueGetter`

### Expected behavior 🤔

It should provide correct type

### Steps to reproduce 🕹

```
import {
  GridColumns
} from '@mui/x-data-grid'

interface User {
  name: string;
  age: number
}

const columns: GridColumns<User> = [
  {
    field: "name",
    valueGetter: (params) => params.row.name,
  }, 
  {
    field: "actions",
    type: 'actions',
    getActions: (params) => params.row.age && []
  },
]
```

Bildschirmfoto 2022-04-26 um 12 52 00
Bildschirmfoto 2022-04-26 um 12 52 10

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by subvertallchris**
Closes #4660 

This adds generic arguments to the `GridActionsColDef` interface. They match those provided to `GridValidRowModel` and feed into it in the definition as well as in the params given to the `getActions` callback.

The immediate benefit here is that it provides an added layer of type safety to `getActions` and anywhere else in the base `GridColDef` that those arguments are used. It should be fully backwards compatible with all existing uses of this interface since the generics are optional and default to `any`. 

I added a simple test that puts the compiler through some very basic paces and also tests a `getActions` callback that makes use of those arguments. I see there is another test that also checks the `getActions` callback params, so maybe this second portion isn't necessary, but I figured I might as well demonstrate the connection between the interface and the implementation.

### CODE REVIEW

File: packages/grid/x-data-grid/src/models/colDef/gridColDef.ts [hunk 1]
```diff
@@ -260,7 +261,7 @@ export interface GridActionsColDef extends GridColDef {
    * @param {GridRowParams} params The params for each row.
    * @returns {React.ReactElement<GridActionsCellItemProps>[]} An array of [[GridActionsCell]] elements.
    */
-  getActions: (params: GridRowParams) => React.ReactElement<GridActionsCellItemProps>[];
+  getActions: (params: GridRowParams<R>) => React.ReactElement<GridActionsCellItemProps>[];
 }
 
 export type GridEnrichedColDef<R extends GridValidRowModel = any, V = any, F = V> =
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/models/colDef/gridColDef.ts:267]: You also need to pass the generics to `GridActionsColDef` to make the typings work below:

```ts
const columns: GridColumns<TestRowModel> = [
  {
    field: 'actions',
    type: 'actions',
    getActions: ({ id, row }) => {},
  },
];
```

The diff in https://github.com/mui/mui-x/issues/4660#issuecomment-1109929700 shows how to do.

File: packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx [hunk 2]
```diff
@@ -145,6 +146,77 @@ describe('<DataGrid /> - Rows', () => {
...
+                icon={<span />}
+              />,
+            ];
+          },
+        };
+      }, []);
+
+      return (
+        <div>
+          <div data-testid="id">{id || 'none'}</div>
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx:190]: We usually don't use DOM elements to test if a function received a specific argument. Instead, we use spy functions.

Example:

https://github.com/mui/mui-x/blob/23a57c3665ff00675c976cc89f8aaeee54cefe69/packages/grid/x-data-grid-pro/src/tests/cellEditing.DataGridPro.new.test.tsx#L83-L89

Could you use this same approach here? It reduces the boilerplate.

**Review by m4theushw — COMMENTED** [review]
Thanks for the contribution. I linked #4660 in the description.

> I added a simple test that puts the compiler through some very basic paces and also tests a getActions callback that makes use of those arguments.

Usually we put these kind of tests in https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/tests/columns.spec.tsx

We type the generic so it throws a TS error if we use an invalid prop. There're some examples in this file. If you could add one there it would be awesome.

File: packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx (hunk 2 above)
Comment (subvertallchris) [reply packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx:190]: I think I can go ahead and pull the tests out of this file since the behavior is already tested and the compiler tests are covered elsewhere.

**Comment by subvertallchris** [comment]
> Usually we put these kind of tests in https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/tests/columns.spec.tsx

Sounds good! I looked for something like this but didn't find it, it's how I'm used to testing type defs for definitely-typed. I'll make the changes. I hadn't come across `GridEnrichedColDef` before. That behavior is really cool, I'm glad I did this exercise.

File: packages/grid/x-data-grid/src/tests/columns.spec.tsx [hunk 3]
```diff
@@ -40,6 +41,29 @@ const RenderCellParamsExplicitTyping = () => {
             return params.formattedValue.toUpperCase();
           },
         },
+        {
+          field: 'price6',
+          type: 'actions',
+          getActions: (params: GridRowParams) => {
+            return params.row.foo.bar.toExponential();
+          },
+        },
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/tests/columns.spec.tsx:50]: I don't think we need this test. The `row` in `GridRowParams` already has `any` so it accepts everything. Instead, you could create a different function using `GridColumns<{ ... }>`, then check if `getActions` receives the same row. Something like:


```ts
const columns: GridColumns<{ price: number }> = [{
  getActions: (params) => {
    return params.row.price.toUpperCase(); // fails
  }
}];
```

**Review by m4theushw — APPROVED** [review]
Thanks for going the extra mile.
