### PR TITLE
[charts] Fix horizontal layout and tooltip

### LINKED ISSUE #19613: [charts] Some example on the Overview page are distorted
### Steps to reproduce

1.  Legends should horizontal and on the top:

Image

2. Same as above:

Image

3.  Same as above:

Image

4. Uneven spacing

Image

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #19613

### CODE REVIEW

**Review by bernardobelchior — COMMENTED** [review]
Should we add a demo or a visual test to ensure this works as expected? How do we know we won't cause any regression with this change?

**Comment by alexfauquette** [comment]
> We can probably use the toolbar + the legend positions to test the variations.

Yes, I spoted much more bad scenario thanks to it 🙃

File: packages/x-charts/src/ChartsWrapper/ChartsWrapper.tsx [hunk 1]
```diff
@@ -102,66 +97,85 @@ const getTemplateColumns = (
     return `${width ? 'auto' : '1fr'} auto`;
   }
 
-  return '100%';
+  return 'auto';
```
Comment (alexfauquette) [inline packages/x-charts/src/ChartsWrapper/ChartsWrapper.tsx]:
```suggestion
  return '100%';
```

File: packages/x-charts/src/ChartsWrapper/ChartsWrapper.tsx [hunk 2]
```diff
@@ -87,81 +82,95 @@ const getGridTemplateAreas = (
...
+          style: {
+            height: '100%',
+          },
+        },
+      ],
+      flex: 1,
+      display: 'grid',
+      gridTemplateColumns,
+      gridTemplateRows,
+      [`&:has(.${chartsToolbarClasses.root})`]: {
```
Comment (bernardobelchior) [inline packages/x-charts/src/ChartsWrapper/ChartsWrapper.tsx]: Should we mention somewhere that custom toolbars should have this class to ensure they're properly placed?

File: packages/x-charts/src/ChartsWrapper/ChartsWrapper.tsx [hunk 3]
```diff
@@ -87,81 +82,95 @@ const getGridTemplateAreas = (
...
+        // Add a row for toolbar if there is one.
+        gridTemplateRows: `auto ${gridTemplateRows}`,
+        gridTemplateAreas: `"${gridTemplateColumns
+          .split(' ')
+          .map(() => 'toolbar')
+          .join(' ')}"
+        ${gridTemplateAreas}`,
+      },
+      [`&:not(:has(.${chartsToolbarClasses.root}))`]: {
```
Comment (bernardobelchior) [inline packages/x-charts/src/ChartsWrapper/ChartsWrapper.tsx]: Do we need this? Can't we define the properties without a selector? Then if a toolbar exists, the `gridTemplateAreas` defined in there will have priority.

**Review by bernardobelchior — APPROVED** [review]
Looks good 👍 just need to fix the visual regression test so that it fits inside the image 😅

File: packages/x-charts/src/ChartsWrapper/ChartsWrapper.tsx (hunk 3 above)
Comment (alexfauquette) [reply packages/x-charts/src/ChartsWrapper/ChartsWrapper.tsx]: Yes, this also make me realise the next lines are now useless since the `display` is now `'grid'` and not `'flex'`

```js
 justifyContent: 'center',
      justifyItems: getJustifyItems(ownerState.legendPosition),
      alignItems: getAlignItems(ownerState.legendPosition),
      [`& > .${chartsToolbarClasses.root}`]: {
        justifySelf: 'center',
      },
```
