### PR TITLE
[DataGrid] Fix scroll jumping

### LINKED ISSUE #14802: [data grid] Scrolling with scrollbar jumps back to a previous position when `getRowHeight={() => 'auto'}` is used
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-sux3md?file=Demo.tsx

Steps:
1. Scroll down on the Data Grid using the scrollbar
2. Make note of which row id you're looking at when you're about to stop scrolling
3. Note that the row id after you've stopped scrolling, they are different

### Current behavior

The row you're viewing when you release the scrollbar aren't the rows you see when you release the scrollbar. We don't see this behavior for a smaller number of rows where virtualization of rows doesn't come into play.

### Expected behavior

The row you're viewing when you release the scrollbar are the rows you see when you release the scrollbar.

### Context

We had a customer report this jumping behavior when they scroll using the scrollbar. The seems like this might be related to virtualization on the grid rows then those rows adjusting their size due to rowHeight auto. This was seen in version 6 and version 7 of mui-x. We're really looking for a way that we can make this virtualization/rowHeight behavior seem less clunky. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 13.6.2
  Binaries:
    Node: 20.8.1 - ~/.asdf/installs/nodejs/20.8.1/bin/node
    npm: 10.1.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 129.0.6668.71
```
</details>

**Search keywords**: scrollbar data grid jumping pro premium rowHeight
**Order ID**: 82849

### PR DESCRIPTION
**Pull request by romgrk**
Closes #14802

Before: https://codesandbox.io/p/sandbox/thirsty-sun-qcstlj

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts:1]: As I'm fixing/refactoring the `'auto'` height code, I'm seeing stuff that could be removed. I see that there is a `.resized` flag that is never used, except in `unstable_setRowHeight` which is itself not used afaict. It was added in https://github.com/mui/mui-x/pull/3751. @cherniavskii, can we remove this method and its associated data?

Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts:1]: It's a programmatic API that developers can use. I'm not sure if it's actually being used though, it could be useful for implementing row resizing.
I prefer keeping it if it's not causing issues.

Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts:1]: I don't like much keeping code that's unused, it makes reading & understanding the rest of the file more tedious. But should we consider removing the `unstable_` prefix from those methods, if we're going to keep them?

Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts:1]: Also note that the `unstable_setRowHeight` method is marked as `@ignore - do not document` in addition to `unstable_`, thus why I suggested removing it.

Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts:1]: > unstable_setRowHeight method is marked as @ignore - do not document

Fair enough, then I'm OK with removing it 👍🏻

Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts:1]: I think deleting code is my favourite part of programming.

File: packages/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts [hunk 1]
```diff
@@ -73,55 +70,55 @@ export const useGridRowsMeta = (
...
+  };
 
-      const { isResized, needsFirstMeasurement, sizes } = rowsHeightLookup.current[row.id];
-      let baseRowHeight = typeof rowHeight === 'number' && rowHeight > 0 ? rowHeight : 52;
-      const existingBaseRowHeight = sizes.baseCenter;
+  const processHeightEntry = React.useCallback(
+    (row: GridRowEntry) => {
+      // HACK: rowHeight trails behind the most up-to-date value just enough to
+      // mess the initial rowsMeta hydration :/
+      const baseRowHeight = gridDimensionsSelector(apiRef.current.state).rowHeight;
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts:93]: @cherniavskii The recent change you made to pull `rowHeight` from `useGridSelector` coupled with the changes of this PR created this issue :| It's a symptom of [this](https://www.notion.so/mui-org/mui-x-Data-Grid-refactoring-120cbfe7b6608044bedad0bbc8e87a48?pvs=4#121cbfe7b6608089ba62c43dfd69f4c3).

File: packages/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts [hunk 2]
```diff
@@ -183,113 +182,93 @@ export const useGridRowsMeta = (
...
     if (hasRowWithAutoHeight.current && index > lastMeasuredRowIndex.current) {
       lastMeasuredRowIndex.current = index;
     }
-  }, []);
+  };
 
-  const resetRowHeights = React.useCallback(() => {
-    rowsHeightLookup.current = {};
+  const resetRowHeights: GridRowsMetaApi['resetRowHeights'] = () => {
+    heightCache.clear();
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/rows/useGridRowsMeta.ts:221]: We used `Object.create(null)` when creating the lookup but not when resetting it here. Using `Map` for lookups avoids the issues with `{}` (prototype injection, and presence of Object methods), and is also more performant.

File: packages/x-data-grid/src/hooks/utils/useGridApiMethod.ts [hunk 3]
```diff
@@ -14,7 +15,7 @@ export function useGridApiMethod<
 >(privateApiRef: React.MutableRefObject<PrivateApi>, apiMethods: T, visibility: V) {
   const isFirstRender = React.useRef(true);
 
-  React.useEffect(() => {
+  useEnhancedEffect(() => {
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/utils/useGridApiMethod.ts:18]: This was causing subtle bugs, because some of our hook effects use `useEnhancedEffect` (aka `React.useLayoutEffect`), so they were running before the API methods were updated, so they were calling outdated `useCallback` instances.

**Comment by romgrk** [comment]
The argos changes all look positive to me, they show the grid reacting to `'auto'` height faster.

File: packages/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts
Comment (romgrk) [inline packages/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts:1]: Sidenote but the detail panels code is terribly unefficient. IIUC, they call `getDetailPanel(Height|Content)` for *all* the rows of the grid, regardless if they're displayed or not. For large datasets, the performance must be horrible.

**Review by KenanYusuf — APPROVED** [review]
Nice refactors 👍  

Tested the scrolling issue with `getRowHeight: () => 'auto'` and I could no longer reproduce it.
