### PR TITLE
[DataGrid] Re-use previous `rowNode` when building tree and the new `rowNode` is equal to the previous one

### LINKED ISSUE #3924: [DataGridPro] `renderCell` is called on each keystroke during cell editing
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm using custom InputBase on two columns with renderCell and renderEditCell props. And I'm using custom input component for this InputBase with inputComponent prop (imask library).
But when I clicked anywhere , being render every time for every cell that using renderCell prop.  Actually, I solved it partially, for example , I'm using useMemo hook with JSX expression for renderCell , didn't render.
```
        renderCell: (params: GridRenderCellParams<number>) => (
            <>
                {
                    useMemo(() => {
                        return <InputBase
                            name="old_price"/**/
                            readOnly
                            value={!params.value ? "" : params.value.toString()}
                            inputComponent={VMaskNumber as any}
                            style={{
                                color: '#262626',
                            }}
                        />
                    }, [params.value])
                }
            </>
        )
```

It's perfect , but there's a problem, this column wasn't editable. And this solution was useful. In the same way, I'm trying for editable column , I'm getting error : 
**_"Rendered fewer hooks than expected. This may be caused by an accidental early return statement."_**

But I have to use  useMemo, beacause of it's trouble even for 35 data.

https://user-images.githubusercontent.com/6121871/153591066-7a7d028d-a31c-45ce-9dab-c9f2a189838c.mp4

You can see difference with renderCell prop and without renderCell prop. I'm sharing code and if you can watch console , you will show performance problem.

https://codesandbox.io/s/p0t4z
 

### Expected behavior 🤔

_No response_

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

37219

### PR DESCRIPTION
**Pull request by flaviendelangle**
FIxes #3924

### CODE REVIEW

File: packages/grid/x-data-grid-pro/src/internals/utils/tree/buildRowTree.ts [hunk 1]
```diff
@@ -170,13 +170,32 @@ export const buildRowTree = (params: BuildRowTreeParams): GridRowGroupingResult
...
+    const shouldReUsePreviousNode =
+      previousNode &&
+      previousNode.isAutoGenerated === node.isAutoGenerated &&
+      previousNode.parent === node.parent &&
+      previousNode.groupingKey === node.groupingKey &&
+      previousNode.groupingField === node.groupingField &&
+      previousNode.depth === node.depth &&
+      previousNode.childrenExpanded === node.childrenExpanded &&
+      previousNode.children?.length === node.children?.length &&
+      previousNode.children?.every((childId, index) => node.children?.[index] === childId);
```
Comment (m4theushw) [inline packages/grid/x-data-grid-pro/src/internals/utils/tree/buildRowTree.ts:192]: I wonder if checking all children again is not more painful than a new rerender.

**Review by m4theushw — APPROVED** [review]
What about removing in v6 the `rowNode` prop from the props passed to the cell? From what I found it's mostly used to know if the row is auto-generated or not. As alternative we could provide an `isRowAutoGenerated` prop or force developers to use the API method. That way we don't have to do complex deep checks to avoid a rerender.

File: packages/grid/x-data-grid-pro/src/internals/utils/tree/buildRowTree.ts (hunk 1 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid-pro/src/internals/utils/tree/buildRowTree.ts:192]: It is also used in the tree data cell to know the amount of children.
Users can always use the `apiRef` to get the rowNode if we remove it from the prop.
I don't know what would be the best behavior here.
