### PR TITLE
[TimePicker] Add `Mui-selected` class to `TimeClock` meridiem buttons

### LINKED ISSUE #12493: [TimePicker] AM/PM button does not have selected class for font style customization
### Steps to reproduce

Link to live example: (required)

Steps:
1. Use timepicker component to show time picker clock.
2. Now after opening the timepicker pop up. Try to inspect it.
3. Now inspect the selected button from AM or PM whichever is shown selected.
4. The selected button does not contain any selected class which i can use to cusotmize the selected state of AM or PM button.

### Current behavior

As per current behaviour the timepicker am/pm button doesnot show any selected class on it because of which it is not possible to customize the selected state of these button.
image
As per the above screenshot we are not able to update the font styles of AM button if we want to show different font color or font weight for selected state.
Same case happens with the PM button as well when it is in selected state. 

### Expected behavior

Expected behavior should be like, we should have a selected class for example like **Mui-selected** on the selected button, so that we can overwrite the styles by catching that class. 

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: AM PM css customization

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #12493.

Additional changes:
- ~Refactor active/selected styles to depend on the `Mui-selected` class rather than using a `variant`~. Can't do it now, because it's a possible BC: https://github.com/mui/mui-x/pull/13848#discussion_r1678801329
- Extract common meridiem button styles into a reusable function

P.S. I picked this up after I saw an old stash with partially complete work. 🙈

### CODE REVIEW

File: packages/x-date-pickers/src/TimeClock/Clock.tsx [hunk 1]
```diff
@@ -145,56 +145,41 @@ const ClockPin = styled('div', {
   transform: 'translate(-50%, -50%)',
 }));
 
+const meridiemButtonCommonStyles = (theme: Theme) => ({
+  zIndex: 1,
+  bottom: 8,
+  paddingLeft: 4,
+  paddingRight: 4,
+  width: CLOCK_HOUR_WIDTH,
+  [`&.${clockClasses.selected}`]: {
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/TimeClock/Clock.tsx:154]: Does this introduce any specificity change?

Comment (LukasTy) [reply packages/x-date-pickers/src/TimeClock/Clock.tsx:154]: Great point.
This could be a BC for someone currently overriding selected styles via theme.
I'll check.
As for the class specificity, I don't think we can run into it, because there was no way to identify the selected button based on DOM/Classes for now. 🙈

Comment (flaviendelangle) [reply packages/x-date-pickers/src/TimeClock/Clock.tsx:154]: If people are using the variants / the `ownerState` in their theme, would they see their CSS change because of specificity change on our side?
I think so but I'm not very good at CSS specificity :laughing:

Comment (LukasTy) [reply packages/x-date-pickers/src/TimeClock/Clock.tsx]: I've double-checked and indeed, we can't go this route, at least now, because for someone it would be a BC. 🙈 
The following styles would no longer apply to a selected meridiem button:
```ts
MuiClock: {
  styleOverrides: {
    amButton: {
      color: 'red',
    },
    pmButton: {
      color: 'green',
    },
  },
},
```

Comment (flaviendelangle) [reply packages/x-date-pickers/src/TimeClock/Clock.tsx]: If you think we should do the change in the next major, feel free to open an issue so that we can keep track of it :+1:

**Review by flaviendelangle — APPROVED** [review]
