### PR TITLE
[data grid] Fix `renderContext` calculation with scroll bounce / over-scroll

### LINKED ISSUE #14930: [data grid] Stop rendering when overscrolling on iOS
### Steps to reproduce

Link to live example: (required)

Steps:
1. Go to https://mui.com/x/react-data-grid/#pro-plan in iPad
2. Scroll the Data grid which have rowHeight
3. You can see empty space in rendering, it looks like flickering 

### Current behavior

https://github.com/user-attachments/assets/c6dfe2bd-3b54-489e-b925-8b32c6d6d75f

Flickering when scrolling vertically in iPad

### Expected behavior

Mui Data Grid Pro render without flickering. 

### Context

We are facing flickering issue in iPad when scroll on Mui DataGrid. 
We can see empty screen for few milliseconds, so it makes the page flickering. 

https://mui.com/x/react-data-grid/#pro-plan - We can see same issue in this page in iPad. 

We are using DataGridPro from mui/x-data-grid-pro. 
iPadOS 17.7 (21H16) 
iPad (10th generation)

We have tested some other tables in iPad, all are rendering fine. 
Help us to resolve this issue.

Support key -> 77584 - Licenses (QT 23092601)

### Your environment

_No response_

**Search keywords**: Flickering issue when rendering MUI Data Grid Pro in iPad
**Order ID**: 77584

### PR DESCRIPTION
**Pull request by lauri865**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes an age old bug that has made the Datagrid look really broken on iOS devices.

Turns out there's a faulty logic that prevents renderContext from being recalculated when overscrolling – it skips calculating a new render context if the scroller is out of bounds, which results in blank rows intermittently. Fixed it by clamping within the known scroll area instead to avoid any unnecessary recalculations when bouncing, while still updating the render context when needed.

Steps to reproduce:
1. On iOS (not sure about Android) scroll down on any datagrid with sufficient rows (e.g. https://mui.com/x/), but also pull your finger to the right to pull the scroll area away from edges
2. Notice how new rows don't get rendered, and you end up with blank screen for a while

It's very annoying, since there's no directional scroll locks, so natural motion can easily trigger even the tiniest of overscrolls and this bug looks like this (no rows displayed while actively scrolling):
https://github.com/user-attachments/assets/d431e8f3-60c0-4914-b098-ed901195e38c

I also added in a small performance optimisation to reduce the number of calls to `scrollTop/scrollLeft` properties (centralised to `triggerUpdateRenderContext`), which can cause re-measurements when called in different times (depends on browser implementation).

Fixes #14930 (was never solved)

Preview: https://deploy-preview-16297--material-ui-x.netlify.app/x/react-data-grid/#pro-version

### CODE REVIEW

**Comment by oliviertassinari** [comment]
Before

https://github.com/user-attachments/assets/da993b59-391f-4646-a5c8-219215a00cd7

After:

https://github.com/user-attachments/assets/5d33125d-7ad4-46af-bd6b-1b4330e2f2d9

File: packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx [hunk 1]
```diff
@@ -139,12 +148,12 @@ const GridVirtualScrollbar = forwardRef<HTMLDivElement, GridVirtualScrollbarProp
     useOnMount(() => {
       const scroller = apiRef.current.virtualScrollerRef.current!;
       const scrollbar = scrollbarRef.current!;
-      const options = { capture: true, passive: true };
+      const options = { passive: true };
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx:151]:
```suggestion
      const options: AddEventListenerOptions = { passive: true };
```

File: packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx [hunk 2]
```diff
@@ -139,12 +148,12 @@ const GridVirtualScrollbar = forwardRef<HTMLDivElement, GridVirtualScrollbarProp
...
       scroller.addEventListener('scroll', onScrollerScroll, options);
       scrollbar.addEventListener('scroll', onScrollbarScroll, options);
       return () => {
-        scroller.removeEventListener('scroll', onScrollerScroll, options);
-        scrollbar.removeEventListener('scroll', onScrollbarScroll, options);
+        scroller.removeEventListener('scroll', onScrollerScroll, options as any);
+        scrollbar.removeEventListener('scroll', onScrollbarScroll, options as any);
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx:156]:
```suggestion
        scroller.removeEventListener('scroll', onScrollerScroll, options);
        scrollbar.removeEventListener('scroll', onScrollbarScroll, options);
```

**Review by KenanYusuf — COMMENTED** [review]
Thanks a lot for the PR @lauri865

File: packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 3]
```diff
@@ -264,9 +263,24 @@ export const useGridVirtualScroller = () => {
...
+      dimensions.minimumSize.height - dimensions.viewportOuterSize.height,
+    );
+    const maxScrollLeft = Math.ceil(
+      dimensions.minimumSize.width -
+        // TODO: remove remove pinned columns once the below gets merged:
+        // https://github.com/mui/mui-x/pull/15627
+        (dimensions.viewportInnerSize.width +
+          dimensions.leftPinnedWidth +
+          dimensions.rightPinnedWidth),
+    );
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:276]:
```suggestion
    const maxScrollLeft = Math.ceil(
      dimensions.minimumSize.width - dimensions.viewportInnerSize.width,
    );
```

**Review by KenanYusuf — APPROVED** [review]

**Comment by KenanYusuf** [comment]
**LTR**

https://github.com/user-attachments/assets/ec61332f-a841-4511-81b9-96963813c0c2

**RTL**

https://github.com/user-attachments/assets/ee5621e6-91ce-46aa-b468-5f0a63c122c0

**Pinned columns**

https://github.com/user-attachments/assets/cfdaabdc-13a8-4d50-8b60-7e549acf315d

File: packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx (hunk 1 above)
Comment (oliviertassinari) [reply packages/x-data-grid/src/components/virtualization/GridVirtualScrollbar.tsx]: `capture: true` was suspicious, happy we could remove this.
