### PR TITLE
[docs] Fix remaining charts demos on mobile

### LINKED ISSUE #16554: [charts] Docs page for v8 have an horizontal overflow
### Steps to reproduce

https://github.com/user-attachments/assets/dd5b81dc-b617-4a95-ab21-c4a1dc2fb194

Steps:
1. Open [this link](https://next.mui.com/x/react-charts/bars/)
2. Scroll horizontally

### Current behavior

The page scrolls horizontally

### Expected behavior

The page shouldn't scroll horizontally and charts should occupy at most 100vw.

### Context

This only happens in the `next.mui.com` website. The current version's docs are fine. 

### Your environment

Safari iOS

**Search keywords**: docs, charts, horizontal, overflow, scroll,

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #16554

### CODE REVIEW

File: docs/data/charts/composition/BasicComposition.tsx [hunk 1]
```diff
@@ -23,8 +23,7 @@ export default function BasicComposition() {
         labelPlacement="end"
       />
 
-      <Paper sx={{ width: '100%', height: 300 }} elevation={3}>
-        {/* @ts-ignore */}
+      <Paper sx={{ width: '95%', height: 300 }} elevation={3}>
```
Comment (bernardobelchior) [inline docs/data/charts/composition/BasicComposition.tsx:26]: Don't we want to use something like flex in the parent and do `flex: 1` here? 

Otherwise on smaller screens the `FormControlLabel` might occupy more than 5% of the width, can't it not?

**Review by bernardobelchior — APPROVED** [review]

File: docs/data/charts/composition/BasicComposition.tsx (hunk 1 above)
Comment (alexfauquette) [reply docs/data/charts/composition/BasicComposition.tsx:26]: I moved from 100% to 95% to let the shadow fo the Paper be visible. But it seems the 100% is not necessary at all, and a `margin: 1` does the job :+1:

image
