### PR TITLE
[DataGrid] Fix incorrect computation of `lastPage` in `GridPagination`

### LINKED ISSUE #11247: [Data Grid] Warning: Failed prop type: MUI: The page prop of a TablePagination is out of range (0 to 0, but page is 1).
### Steps to reproduce

https://codesandbox.io/p/sandbox/interesting-currying-fvqljg?file=%2Fsrc%2FDemo.tsx%3A261%2C9

### Current behavior

Show

`Warning: Failed prop type: MUI: The page prop of a TablePagination is out of range (0 to 0, but page is 1).`

### Expected behavior

Not show warning

### Context

Go to page 2 and delete all items on that page

https://github.com/mui/mui-x/assets/13531993/2ef3c375-d80a-46dd-a3f9-991c9fb6de82

### Your environment

_No response_

**Search keywords**: Data Grid warning TablePagination when remove rows

### PR DESCRIPTION
**Pull request by MBilalShafi**
Fix #11247

### CODE REVIEW

File: packages/x-data-grid/src/components/GridPagination.tsx [hunk 1]
```diff
@@ -38,10 +38,10 @@ export const GridPagination = React.forwardRef<unknown, Partial<TablePaginationP
       [rootProps.rowCount, visibleTopLevelRowCount],
     );
 
-    const lastPage = React.useMemo(
-      () => Math.floor(rowCount / (paginationModel.pageSize || 1)),
-      [rowCount, paginationModel.pageSize],
-    );
+    const lastPage = React.useMemo(() => {
+      const calculatedValue = Math.ceil(rowCount / (paginationModel.pageSize || 1)) - 1;
+      return calculatedValue < 0 ? 0 : calculatedValue;
```
Comment (romgrk) [inline packages/x-data-grid/src/components/GridPagination.tsx:43]: `Math.max(0, ...)`?

**Review by romgrk — APPROVED** [review]

**Review by michelengelen — APPROVED** [review]

**Comment by michelengelen** [comment]
@MBilalShafi Could you check if this is also fixing #11724? Thanks! 🙇🏼

**Comment by MBilalShafi** [comment]
> @MBilalShafi Could you check if this is also fixing https://github.com/mui/mui-x/issues/11724? Thanks! 🙇🏼

That is a separate problem I think.
