### PR TITLE
[data grid] Check focus validity whenever the rows in state changes

### LINKED ISSUE #4678: [data grid] Focus is not reset when the rows changes due to a change in row grouping model
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When we configure a grouping model and expand the generated row and then delete this grouping model, clicking on the column header results in an error:

`Uncaught Error: No row with id #auto-generated-row-company/20th Century Fox-director/James Cameron found`

In the local environment it also throws warnings like this:

`MUI: You are calling getValue("__row_group_by_columns_group__") but the column "__row_group_by_columns_group__" is not defined.
Instead, you can access the data from "params.row.__row_group_by_columns_group__".`

### Expected behavior 🤔

We should be able to freely change the grouping model and use the table without errors

### Steps to reproduce 🕹

I will not publish my example because the problem appears also in the documentation.

Steps:

1. Go to the example in docs: [Row Grouping example](https://mui.com/x/react-data-grid/row-grouping/#RowGroupingCustomGroupingColDefCallback) 
2. Select `Group by company and director` tab
3. Expand auto-generated row `by James Cameron`
4. Select `Group by company` tab
5. Click on any column header
6. Then `Uncaught Error: No row with id #auto-generated-row...` error appear.

### Context 🔦

I have a custom row grouping component where I drag and drop the column header name to input which generates a new grouping model, so when I'm changing the grouping model and expanding an auto-generated row and then trying to set a new model then an error appears. 

### Your environment 🌎

System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.2 
    Yarn: 1.22.17 
    npm: 8.1.2 
  Browsers:
    Chrome
  npmPackages:
    @emotion/react: ^11.8.2 => 11.9.0
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/base:  5.0.0-alpha.75
    @mui/icons-material: ^5.5.1 => 5.6.0
    @mui/lab: ^5.0.0-alpha.75 => 5.0.0-alpha.76
    @mui/material: ^5.5.2 => 5.6.0
    @mui/private-theming:  5.6.0
    @mui/styled-engine:  5.6.0
    @mui/system:  5.6.0
    @mui/types:  7.1.3
    @mui/utils:  5.6.0
    @mui/x-data-grid: ^5.8.0 => 5.8.0
    @mui/x-data-grid-generator: ^5.8.0 => 5.8.0
    @mui/x-data-grid-pro:  5.8.0
    @mui/x-date-pickers:  5.0.0-alpha.0
    @mui/x-license-pro:  5.7.0
    @types/react:  17.0.43
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    typescript:  4.6.3

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #4678

Before this PR, we where listening to `props.rows` changes to check the focus validity.
Now I listen to `GridEvents.rowsChange` to also track changes with `apiRef.current.updateRows` or grouping changes.

I don't think we need to listen to `sortedRowChange` and pagination change. If the focus is on a non-visible row, it does not causes any crash.

____

I also removed unused unused `props.rows` from `useGridDimensions` typing
That way only `useGridRows` accesses directly `props.rows`, all other hooks should use the state.

### CODE REVIEW

File: packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts [hunk 1]
```diff
@@ -236,6 +236,18 @@ export const useGridFocus = (
     [apiRef],
   );
 
+  const handleCleanFocus = React.useCallback<GridEventListener<'rowsSet'>>(() => {
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts:239]:
```suggestion
  const handleRowsSet = React.useCallback<GridEventListener<'rowsSet'>>(() => {
```

File: packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts [hunk 2]
```diff
@@ -236,6 +236,18 @@ export const useGridFocus = (
...
+    const cell = gridFocusCellSelector(apiRef);
+
+    // If the focused cell is in a row which does not exist anymore, then remove the focus
+    if (cell && !apiRef.current.getRow(cell.id)) {
+      apiRef.current.setState((state) => ({
+        ...state,
+        focus: { cell: null, columnHeader: null },
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts:246]: In theory, every time a cell loses focus it should publish `cellFocusOut`, but to publish it we call `getCellParams` which will crash because the row doesn't exist. It will be a bug if the removed row was also being edited. If we want to implement the option 3 from https://github.com/mui/mui-x/issues/4516#issuecomment-1102916209 we will likely have to revisit this part. Maybe we change the params passed to `cellFocusOut` to not include the row object. Anyway, until someone complains about `cellFocusOut` not published we can keep the listener to `rowsSet`.

**Review by m4theushw — APPROVED** [review]

File: packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts (hunk 2 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts:246]: Yes, in v6 we could pass the id instead of the params to allow to publish the focus out event on a destroyed cell.
