### PR TITLE
[TreeView] Do not mutate `props.items` in the `getItemTree` method

### LINKED ISSUE #19482: [tre view] The `apiRef.current.getItemTree` mutates `props.items`
### Search keywords

tree view mutation props

### Latest version

- [x] I have tested the latest version

### Affected products

Tree View

### Steps to reproduce

See https://github.com/mui/mui-x/pull/19284#issuecomment-3254066654

### Current behavior

_No response_

### Expected behavior

_No response_

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #19482

### CODE REVIEW

**Review by noraleonte — APPROVED** [review]
🙏

File: packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.tsx [hunk 1]
```diff
@@ -181,14 +181,15 @@ export const useTreeViewItems: TreeViewPlugin<UseTreeViewItemsSignature> = ({
   const getItemTree = React.useCallback(() => {
     const getItemFromItemId = (itemId: TreeViewItemId): TreeViewBaseItem => {
       const item = itemsSelectors.itemModel(store.state, itemId);
+      const itemToMutate = { ...item };
```
Comment (caillou) [inline packages/x-tree-view/src/internals/plugins/useTreeViewItems/useTreeViewItems.tsx:184]: <details>
  <summary>@flaviendelangle <s>This only makes a clone of the outer-most item.</s></summary>
E.g:

```ts
const x = {a: {b: []}};
const copy = {...x};
copy.a.b = ['new'];
console.log(x)
// { a: { b: [ 'new' ] } }
```

Don't you need to use `structuredClone` instead?

```ts
const x = {a: {b: []}};
const copy = structuredClone(x);
copy.a.b = ['new'];
console.log(x)
// { a: { b: [ 'new' ] } }
```
</details>

Edit: Sorry, my bad. This is a recursive function. Please ignore this comment.
