### PR TITLE
[DataGridPro] Fix header filters not displaying restored values

### LINKED ISSUE #16826: Datagrid Header Filters don't display restored values (Only Text Type)
### Steps to reproduce

Steps:
1. Open this link to live example: https://codesandbox.io/embed/xrpvsl?module=/src/Demo.tsx&fontsize=12
2. Add the `headerFilters` prop to enable them
3. Create a text filter under "Trader Name" & another boolean filter
4. Save the current view
5. Clear the current filters
6. Restore the view by clicking on the "Custom View" option

7. Observe that the "Trader Name" field is still empty
8. Observe that the boolean field has been populated correctly
9. Observe that after clicking the filter icon to open the filter box, the text field has been applied to the modal okay, just is not replicated in the header filters.

### Current behavior

Header filters are not kept in sync with filterModel on restore

### Expected behavior

Header filters should be kept in sync with filter model

### Context

_No response_

### Your environment

N/A - Was able to replicate on the sandbox linked from the docs as above

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: header filters state restore

**Order ID**: 87194

### PR DESCRIPTION
**Pull request by MBilalShafi**
Fixes #16826

`fromInput` being part of the `filterModel` made the UI component think it's the same rendered input as the previous one, thus the restored value was not being shown.

### CODE REVIEW

**Comment by arminmeh** [comment]
I can't reproduce the issue on the sandbox linked in the issue and by following all the steps 🤔
Both filters get populated correctly

**Comment by MBilalShafi** [comment]
@arminmeh It wasn't reproducing for me earlier too, but then it consistently started to reproduce. Try forking the demo or run in the playground.

**Review by cherniavskii — APPROVED** [review]
I can't reproduce the issue either, but the solution makes sense to me

File: packages/x-data-grid/src/hooks/features/filter/useGridFilter.tsx [hunk 1]
```diff
@@ -355,6 +356,13 @@ export const useGridFilter = (
     (prevState, context) => {
       const filterModelToExport = gridFilterModelSelector(apiRef);
 
+      // Remove the additional `fromInput` property from the filter model
+      filterModelToExport.items.forEach((item) => {
+        if ((item as ItemPlusTag).fromInput) {
```
Comment (arminmeh) [inline packages/x-data-grid/src/hooks/features/filter/useGridFilter.tsx:361]: you could also just do `delete item['fromInput']` without any check

**Review by arminmeh — APPROVED** [review]
