### PR TITLE
[charts] Fix sparkline scale and rendering

### LINKED ISSUE #10349: [charts] Different sparkline width depending on `plotType`
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/cranky-grass-h3w4hp?file=/Demo.tsx

### Current behavior 😯

The chart width is not the same:

### Expected behavior 🤔

The chart width should be the same in both cases

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #10349 and fix the https://github.com/mui/mui-x/pull/9228#issuecomment-1724994536

[before](https://codesandbox.io/s/cranky-grass-h3w4hp?file=/Demo.tsx)
image

[after](https://codesandbox.io/s/admiring-bogdan-vh66m2?file=/package.json)
image

### CODE REVIEW

**Review by LukasTy — APPROVED** [review]
LGTM. 🙌

File: packages/x-charts/src/SparkLineChart/SparkLineChart.tsx [hunk 1]
```diff
@@ -159,7 +159,10 @@ const SparkLineChart = React.forwardRef(function SparkLineChart(props: SparkLine
         axisHighlight?.y === 'none'
       }
     >
-      {plotType === 'bar' && <BarPlot slots={slots} slotProps={slotProps} />}
+      {plotType === 'bar' && (
+        <BarPlot slots={slots} slotProps={slotProps} sx={{ shapeRendering: 'auto' }} />
```
Comment (cherniavskii) [inline packages/x-charts/src/SparkLineChart/SparkLineChart.tsx:163]: Would it make sense to change the `shapeRendering` for all bar elements?

https://github.com/mui/mui-x/blob/404c2bb2f268d4e1713ebebe78bb37a48f48a163/packages/x-charts/src/BarChart/BarElement.tsx#L55

**Review by cherniavskii — APPROVED** [review]
Thanks!

File: packages/x-charts/src/SparkLineChart/SparkLineChart.tsx (hunk 1 above)
Comment (alexfauquette) [reply packages/x-charts/src/SparkLineChart/SparkLineChart.tsx:163]: It has been introduced for when bar are close to each other or stack. Without it border between two rects can be a bit messy due to (I assume) anti-aliasing.

So I remote it in sparkline because this should never get multiple series/stacked bars (I hope). But for main bar chart I prefer to keep it

https://github.com/mui/mui-x/assets/45398769/686a5dec-97d8-48e9-a70a-8f350a1340a0

Comment (cherniavskii) [reply packages/x-charts/src/SparkLineChart/SparkLineChart.tsx:163]: Gotcha!
