### PR TITLE
[DataGrid] Fix error logged during skeleton loading with nested data grid

### LINKED ISSUE #14061: [data grid] Skeleton Loading Overlay Triggers Error with Master Detail Panel Containing Another DataGrid
### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-kpvefc?file=Demo.tsx

Steps:
1. Open a row's Detail Panel.
2. Click "Toggle Loading" to show the Skeleton Loading Overlay.
3. Open the console to observe the error that is logged from the DataGrid.

### Current behavior

When the Skeleton Loading Overlay renders over a DataGrid with an open detail panel, and the detail panel contains a DataGrid component, an error is logged from the DataGrid within the row detail panel that it has no intrinsic size.

### Expected behavior

No errors should be logged. I would think either the overlay should be a true overlay on top of the existing content, or detail panels should be removed or hidden before the overlay is applied. I've tried switching the `getDetailPanelContent` prop to `undefined` when `loading` is true, but that doesn't seem to fix the issue.

### Context

Allowing the DataGrid to show the Skeleton Loading Overlay while a master detail panel is opened and not log any errors.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.5
  Binaries:
    Node: 20.11.1 - ~/Library/Caches/fnm_multishells/173_1722440156564/bin/node
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/173_1722440156564/bin/npm
    pnpm: 9.6.0 - ~/Library/Caches/fnm_multishells/173_1722440156564/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.73
    Edge: Not Found
    Safari: 17.5
```
</details>

I see this bug in Chrome. I have not tested Safari.

**Search keywords**: skeleton loading overlay, master detail

### PR DESCRIPTION
**Pull request by KenanYusuf**
When the skeleton loader is active, we hide the data grid scroller contents and vertical scrollbar with CSS. This works well for most cases, however, causes an issue when a data grid is nested within master details. A short summary of what happens:
1. A master detail is expanded with a data grid rendered inside
2. The main data grid `loading` prop gets set to `true`
3. The nested data grid logs the following error:
  `MUI X: useResizeContainer - The parent DOM element of the data grid has an empty height.
Please make sure that this element has an intrinsic height.
The grid displays with a height of 0px.`

Fixes #14061

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 1]
```diff
@@ -689,13 +689,6 @@ export const GridRootStyles = styled('div', {
     [`& .${c['filler--borderTop']}`]: {
       borderTop: '1px solid var(--DataGrid-rowBorderColor)',
     },
-
-    /* Hide grid rows and vertical scrollbar when skeleton overlay is visible */
-    [`& .${c['main--hasSkeletonLoadingOverlay']}`]: {
-      [`& .${c.virtualScrollerContent}, & .${c['scrollbar--vertical']}, & .${c.pinnedRows}`]: {
-        display: 'none',
```
Comment (cherniavskii) [inline packages/x-data-grid/src/components/containers/GridRootStyles.ts:696]: I tried doing this instead:
```
visibility: 'hidden',
position: 'fixed',
```
It seems to work, but I'm unsure if this would work in every scenario.
What do you think?

Comment (KenanYusuf) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:696]: It does seem to work - I thought we tried this the other day 😅. I will do some more thorough testing to double check different scenarios.

Comment (KenanYusuf) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:696]: This seems to be the ideal combination here. The virtual scroller content retains it's height with `visibility: hidden`, fixing the issue with nested data grid. And `position: fixed` takes the element out of the flow. Will make the change, thanks @cherniavskii for taking a look.

Comment (cherniavskii) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:696]: Great! 🎉

**Review by cherniavskii — APPROVED** [review]
