### PR TITLE
[DataGrid] Allow to control the grid density

### LINKED ISSUE #5647: [data grid] Add event callback on density change
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

i am unable to find event related to the density change in premium data grid.there is a onStatechange but it is called on every state change

### Expected behavior 🤔

so can i get an event related to density change in data grid

### Steps to reproduce 🕹

Link to live example:

Steps:
1.
2.
3.
4.

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by MBilalShafi**
Resolves #5647

### Breaking changes

- The `density` is a [controlled prop](https://mui.com/x/react-data-grid/accessibility/#set-the-density-programmatically) now, if you were previously passing the `density` prop to the Data Grid, you will need to do one of the following:

1. Move it to the `initialState.density` to initialize it.

   ```diff
   <DataGrid
   -  density="compact"
   +  initialState={{ density: "compact" }}
   />
   ```

2. Move it to the state and use `onDensityChange` callback to update the `density` prop accordingly for it to work as expected.

   ```diff
   + const [density, setDensity] = React.useState<GridDensity>('compact');
   <DataGrid
   -  density="compact"
   +  density={density}
   +  onDensityChange={(newDensity) => setDensity(newDensity)}
   />
   ```

- The selector `gridDensityValueSelector` was removed, use the `gridDensitySelector` instead.

### CODE REVIEW

File: packages/x-data-grid/src/models/props/DataGridProps.ts [hunk 1]
```diff
@@ -551,6 +551,11 @@ export interface DataGridPropsWithoutDefaultValue<R extends GridValidRowModel =
    * @param {GridCallbackDetails} details Additional details for this callback.
    */
   onColumnOrderChange?: GridEventListener<'columnOrderChange'>;
+  /**
+   * Fired when the density is updated.
```
Comment (flaviendelangle) [inline packages/x-data-grid/src/models/props/DataGridProps.ts:555]:
```suggestion
   * Callback fired when the density changes.
```

If we want to be consistent by props like `onFilterModelChange` or `onColumnVisibilityModelChange`

Maybe some props are using the wording "Fired when", it would be nice to unify at some point :ok_hand:

File: packages/x-data-grid/src/hooks/features/density/useGridDensity.tsx [hunk 2]
```diff
@@ -42,14 +42,18 @@ export const useGridDensity = (
...
+
         return {
           ...state,
           density: newDensityState,
         };
       });
       apiRef.current.forceUpdate();
     },
-    [logger, apiRef],
+    [logger, apiRef, props],
```
Comment (flaviendelangle) [inline packages/x-data-grid/src/hooks/features/density/useGridDensity.tsx:56]: Could it be `useEventCallback` to avoid risking errors like putting `props` here?

**Comment by MBilalShafi** [comment]
I may want to rework this to make it a proper controlled model

File: docs/data/data-grid/accessibility/DensitySelectorSmallGrid.js [hunk 3]
```diff
@@ -26,6 +26,9 @@ export default function DensitySelectorSmallGrid() {
       <DataGrid
         {...data}
         density="compact"
+        onDensityChange={(newDensity) => {
+          console.info(`Density updated to: ${newDensity}`);
```
Comment (cherniavskii) [inline docs/data/data-grid/accessibility/DensitySelectorSmallGrid.js:30]: Should we use the controlled pattern here for consistency?
It might not be obvious that `density` is only used as an initial value and there's no way to control the density from the external state.

Comment (MBilalShafi) [reply docs/data/data-grid/accessibility/DensitySelectorSmallGrid.js:30]: Yes, that sounds better, we could even simplify the density state and move the `density.factor` computation to the selector, I did it locally (just [pushed](https://github.com/mui/mui-x/pull/12332/commits/6dd1f08e283cea60a5fa3d39ee7e26cfe2811cb0) it too), but I was not sure due to the density having a default value:
https://github.com/mui/mui-x/blob/bae7c103ecfee7b183503c77961236f841370ca4/packages/x-data-grid/src/models/props/DataGridProps.ts#L157

To follow the controlled pattern, we'd break another one 😄:
https://github.com/mui/mui-x/pull/12332/commits/6dd1f08e283cea60a5fa3d39ee7e26cfe2811cb0#diff-18991c189d0e0b75b030b0889cfbee75905b8b4c19361d0a4b975a1a3ac26945R406-R410
Note that we have to move the density prop to the `DataGridPropsWithoutDefaultValue` interface, although it technically _has_ a default value.

Plus, without making it fully controlled (i.e. wrapping it with registerControlState), the density could be updated from an external state, it's just it does not work like all other controlled models. (only works on change of prop, which could be fine since it's a primitive type and re-rending should not be an issue)
https://github.com/mui/mui-x/blob/bae7c103ecfee7b183503c77961236f841370ca4/packages/x-data-grid/src/hooks/features/density/useGridDensity.tsx#L55-L57

Wdyt?

Comment (cherniavskii) [reply docs/data/data-grid/accessibility/DensitySelectorSmallGrid.js:30]: > To follow the controlled pattern, we'd break another one 😄:
https://github.com/mui/mui-x/commit/6dd1f08e283cea60a5fa3d39ee7e26cfe2811cb0#diff-18991c189d0e0b75b030b0889cfbee75905b8b4c19361d0a4b975a1a3ac26945R406-R410

Not sure I follow what we're breaking here.

> Note that we have to move the density prop to the DataGridPropsWithoutDefaultValue interface, although it technically has a default value.

Why?

Making the `density` a controlled state is a breaking change though (if you were passing `density="standard"`, the density selector won't work unless you handle the `onDensityChange` callback).
This also means that we need `initialState.density` to be able to initialize the density without controlling it 😅

Comment (MBilalShafi) [reply docs/data/data-grid/accessibility/DensitySelectorSmallGrid.js:30]: > Not sure I follow what we're breaking here.
Why?

Exactly why you mentioned

> This also means that we need `initialState.density`

So we can't keep initializing it here for the users to be able to pass it in `initalState.density`:
https://github.com/mui/mui-x/blob/f5dcc9d5119ba738cd2f72eb8cc1d331ceccb94a/packages/x-data-grid/src/DataGrid/useDataGridProps.ts#L29-L40

This would basically mean that we can't keep it anymore in `DataGridPropsWithDefaultValues` as all the types in it should have their default values in `const DATA_GRID_PROPS_DEFAULT_VALUES`, so we move it to `DataGridPropsWithoutDefaultValue` (unless we add an `Omit<>` to `DataGridPropsWithDefaultValues`). But we still need a fallback initial value for the Grid to keep working as expected, so we do that in the state initializer like [this](https://github.com/mui/mui-x/pull/12332/files#diff-ad2c1ad8bd2e059931470a567172fe1c91b0472508bbff7296f2572d973e08afR15).

> Making the density a controlled state is a breaking change though (if you were passing density="standard", the density selector won't work unless you handle the onDensityChange callback).

Exactly, do you think we should go in that direction though?

File: docs/data/data-grid/accessibility/accessibility.md [hunk 4]
```diff
@@ -22,22 +22,56 @@ The [WAI-ARIA Authoring Practices](https://www.w3.org/WAI/ARIA/apg/patterns/grid
...
+
+### Set the density programmatically
+
+The Data Grid exposes the `density` prop which supports the following values:
+
+- `standard` (default)
+- `compact`
+- `comfortable`
+
+The `density` prop supports controlled mode, which means you can set it programmatically in one of the following ways:
```
Comment (cherniavskii) [inline docs/data/data-grid/accessibility/accessibility.md:46]:
```suggestion
You can set the density programmatically in one of the following ways:
```

File: docs/data/data-grid/accessibility/accessibility.md [hunk 5]
```diff
@@ -22,22 +22,56 @@ The [WAI-ARIA Authoring Practices](https://www.w3.org/WAI/ARIA/apg/patterns/grid
...
+
+1. Initialize the density with the `initialState.density` prop.
```
Comment (cherniavskii) [inline docs/data/data-grid/accessibility/accessibility.md:48]:
```suggestion
1. Uncontrolled – initialize the density with the `initialState.density` prop.
```

File: docs/data/data-grid/accessibility/accessibility.md [hunk 6]
```diff
@@ -22,22 +22,56 @@ The [WAI-ARIA Authoring Practices](https://www.w3.org/WAI/ARIA/apg/patterns/grid
...
+
+   ```tsx
+   <DataGrid
+     initialState={{
+       density: 'compact',
+     }}
+   />
+   ```
+
+2. Control the density with the `density` prop. In order for the Data Grid to reflect the changes, you need to update the `density` prop when the user changes the density by listening to the `onDensityChange` callback. For more advanced use cases, you can also subscribe to the `densityChange` grid event.
```
Comment (cherniavskii) [inline docs/data/data-grid/accessibility/accessibility.md:58]:
```suggestion
2. Controlled – pass the `density` and `onDensityChange` props. For more advanced use cases, you can also subscribe to the `densityChange` grid event.
```

File: docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md [hunk 7]
```diff
@@ -303,6 +303,32 @@ See the [Direct state access](/x/react-data-grid/state/#direct-selector-access)
...
+```diff
+ const [density, setDensity] = React.useState<GridDensity>('compact');
+ <DataGrid
+-  density="compact"
++  density={density}
++  onDensityChange={(newDensity) => setDensity(newDensity)}
+ />
+```
+
+- The selector `gridDensityValueSelector` is removed, use the `gridDensitySelector` instead.
```
Comment (cherniavskii) [inline docs/data/migration/migration-data-grid-v6/migration-data-grid-v6.md:330]:
```suggestion
- The selector `gridDensityValueSelector` was removed, use the `gridDensitySelector` instead.
```

**Review by cherniavskii — APPROVED** [review]
