### PR TITLE
[DataGrid] Reshape row selection model

### LINKED ISSUE #15962: [data grid] Select all checkbox crashes the browser in a large grid
### Steps to reproduce

Steps:
1. [Open this link to live example](https://next.mui.com/x/react-data-grid/#commercial-licenses)
2. Click on the header checkbox

Probably related to #15523 (cc @MBilalShafi)

### Current behavior

_No response_

### Expected behavior

_No response_

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: checkbox, selection

### PR DESCRIPTION
**Pull request by cherniavskii**
Closes https://github.com/mui/mui-x/issues/15481
Fixes #15962

### Breaking changes

- The row selection model has been changed from `GridRowId[]` to `{ type: 'include' | 'exclude'; ids: Set<GridRowId> }`.
  Using `Set` allows for a more efficient row selection management.
  The `exclude` selection type allows to select all rows except the ones in the `ids` set.

  This change impacts the following props:

  - `rowSelectionModel`
  - `onRowSelectionModelChange`
  - `initialState.rowSelectionModel`

  ```diff
  -const [rowSelectionModel, setRowSelectionModel] = React.useState<GridRowSelectionModel>([]);
  +const [rowSelectionModel, setRowSelectionModel] = React.useState<GridRowSelectionModel>({ type: 'include', ids: new Set() });
  ```

  This change also impacts the `gridRowSelectionStateSelector` selector.
  For convenience, use the `gridRowSelectionManagerSelector` selector to handle both selection types:

  ```diff
  -const rowSelection = gridRowSelectionStateSelector(apiRef);
  -const isRowSelected = rowSelection.includes(rowId);
  +const rowSelectionManager = gridRowSelectionManagerSelector(apiRef);
  +const isRowSelected = rowSelectionManager.has(rowId);
  ```

  There is also a `createRowSelectionManager` utility function that can be used to manage the row selection:

  ```ts
  const rowSelectionManager = createRowSelectionManager({
    type: 'include',
    ids: new Set(),
  });
  rowSelectionManager.select(rowId);
  rowSelectionManager.unselect(rowId);
  rowSelectionManager.has(rowId);
  ```

- The `selectedIdsLookupSelector` selector has been removed. Use the `gridRowSelectionManagerSelector` or `gridRowSelectionStateSelector` selectors instead.
- The `selectedGridRowsSelector` has been renamed to `gridRowSelectionIdsSelector`.
- The `selectedGridRowsCountSelector` has been renamed to `gridRowSelectionCountSelector`.

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts [hunk 1]
```diff
@@ -620,14 +638,33 @@ export const useGridRowSelection = (
...
-      const rowsToBeSelected =
-        props.pagination && props.checkboxSelectionVisibleOnly && props.paginationMode === 'client'
-          ? gridPaginatedVisibleSortedGridRowIdsSelector(apiRef)
-          : gridExpandedSortedRowIdsSelector(apiRef);
-
-      apiRef.current.selectRows(rowsToBeSelected, params.value);
+      if (params.value) {
+        if (!props.isRowSelectable && !props.checkboxSelectionVisibleOnly && applyAutoSelection) {
+          apiRef.current.selectRows({ type: 'exclude', ids: new Set() }, params.value, true);
+        } else {
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:644]: The more corner cases I fix, the fewer opportunities for the `exclude` selection model 😅

Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:644]: AFAIU it would only be for "select all", but for large datasets it would improve that interaction substantially.

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts [hunk 2]
```diff
@@ -310,20 +302,36 @@ export const useGridRowSelection = (
   );
 
   const selectRows = React.useCallback<GridRowMultiSelectionApi['selectRows']>(
-    (ids: GridRowId[], isSelected = true, resetSelection = false) => {
+    (selectionModel: GridRowSelectionModel, isSelected = true, resetSelection = false) => {
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:305]: I wonder if leaving this as `selectRows(array)` would be better for DX than `selectRows(selectionModel)`.

File: packages/x-data-grid/src/models/gridRowSelectionModel.ts [hunk 3]
```diff
@@ -5,6 +5,61 @@ export type GridRowSelectionPropagation = {
...
+  size(): number;
+}
+class IncludeManager implements SelectionManager {
+  data: SelectionManager['data'];
+
+  constructor(model: GridRowSelectionModel) {
+    this.data = model.ids;
+  }
+
+  has: SelectionManager['has'] = (id) => this.data.has(id);
```
Comment (romgrk) [inline packages/x-data-grid/src/models/gridRowSelectionModel.ts:24]: Are the inline type annotations useful here? Can't TS infer that based on `implements`? It would also avoid allocating one new function for each method of each instance (which the arrow syntax class method does, unlike regular class methods).

File: packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx [hunk 4]
```diff
@@ -44,18 +48,29 @@ const GridHeaderCheckbox = React.forwardRef<HTMLButtonElement, GridColumnHeaderP
...
         // The row might have been deleted
         if (!apiRef.current.getRow(id)) {
-          return false;
+          continue;
         }
 
-        return rootProps.isRowSelectable!(apiRef.current.getRowParams(id));
-      });
+        const isSelectable = isRowSelectable(apiRef.current.getRowParams(id));
+        if (isSelectable) {
```
Comment (arminmeh) [inline packages/x-data-grid/src/components/columnSelection/GridHeaderCheckbox.tsx:69]:
```suggestion
        if (isRowSelectable(apiRef.current.getRowParams(id))) {
```

File: packages/x-data-grid/src/hooks/features/rowSelection/gridRowSelectionSelector.ts [hunk 5]
```diff
@@ -1,27 +1,42 @@
...
 
 export const selectedGridRowsCountSelector = createSelector(
   gridRowSelectionStateSelector,
-  (selection) => selection.length,
+  gridFilteredRowCountSelector,
+  (selection, filteredRowCount) => {
+    if (selection.type === 'include') {
+      return selection.ids.size;
+    }
+    // TODO: is this correct?
```
Comment (arminmeh) [inline packages/x-data-grid/src/hooks/features/rowSelection/gridRowSelectionSelector.ts:16]: as far as I can see, it will count in rows that are not selectable but are not in the exclusion list

**Comment by arminmeh** [comment]
performance wise this still doesn't improve anything on automatic child selection, right?

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts (hunk 1 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: Correct, but there is a number of conditions for the exclude model to be used:

```ts
if (
  !props.isRowSelectable &&
  !props.checkboxSelectionVisibleOnly &&
  applyAutoSelection &&
  !hasFilters
) {
  apiRef.current.selectRows({ type: 'exclude', ids: new Set() }, params.value, true);
} else {
  const rowsToBeSelected = getRowsToBeSelected();
  apiRef.current.selectRows(
    { type: 'include', ids: new Set(rowsToBeSelected) },
    params.value,
  );
}
```

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts (hunk 2 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: Yeah, I changed it back. Having both include/exclude model **and** `isSelected` param turned out to be too confusing.

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts (hunk 1 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: Ok, so `{ type: 'exclude', ids: new Set() }` could be interpreted differently:
1. All rows are selected (current approach)
2. All selectable and visible rows are selected (this is what you meant, right?)

Do you see benefits in (2) compared to (1)?

File: packages/x-data-grid/src/models/gridRowSelectionModel.ts (hunk 3 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/models/gridRowSelectionModel.ts:24]: I left this for later, but with `implements` I had to redeclare each method's arguments: [playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBA4gTgSwCYCUD2B3AkkqBeKAZ2EQDsBzAbgChqFTgI4AzAQwGNoBlCAGwnbAEaUgFlWpVuSZQA3tShQAFq0IAKZAC5YiVJhwBKbQCM0afhJoBfWu16rCULKTsBXJBHGTpcKAgC2YPz+EAyOPPyCwmISUjLyiooq6sgGcgqJmXAQwK5wpFAAhIXINJk2NtRAA)
Unless there's another way to avoid that, I'll just go ahead and redeclare argument types.

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts (hunk 1 above)
Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: Yes, I guess 2 would remove all those exceptions. From what I can see, we don't currently support keeping non-visible rows selected, from what I can test [on this example](https://stackblitz.com/edit/react-b717a7?file=Demo.tsx).

https://github.com/user-attachments/assets/7ecc482a-9aca-45e6-a429-b276937a07cb

Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: > From what I can see, we don't currently support keeping non-visible rows selected

We do support that with the `keepNonExistentRowsSelected` flag: https://mui.com/x/react-data-grid/row-selection/#row-selection-with-filtering

Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: On another thought, there's a difference between (1) and (2) when interpreting this model by the developers to perform operations on selected rows.
In (1), an empty exclude model means literally all rows.
In (2), an empty exclude model could mean different things depending on the data grid state. So developers would need to convert empty exclude into include (?) model to be able to perform actions on the dataset.

With the above, I think we should proceed with (1).
What do you think?

**Comment by cherniavskii** [comment]
> performance wise this still doesn't improve anything on automatic child selection, right?

It does, in 2 ways:

1. When the exclude model is used, if the conditions for it are met:
	```ts
	if (
	  !props.isRowSelectable &&
	  !props.checkboxSelectionVisibleOnly &&
	  applyAutoSelection &&
	  !hasFilters
	) {
	  apiRef.current.setRowSelectionModel({
	    type: value ? 'exclude' : 'include',
	    ids: new Set(),
	  });
	}
	```
2. When the include model is used, we now use `Set` instead of an array. So the search operation is now O(1) instead of O(n):
	- some code paths will be faster, like this one: https://github.com/mui/mui-x/pull/15651/files?diff=unified#diff-a19f11b67475233e2ba66fbc5593fe39986edeca33e5e09f350dd4efe3726997R187-R192
	- in some places, this removes the need for creating and maintaining row selection lookups – like https://github.com/mui/mui-x/pull/15651/files?diff=unified#diff-e466e798f7c971c0b2e19b4b506222388ef1b0925a05d0e262bbb9c3f3891fa2L68-R91, https://github.com/mui/mui-x/pull/15651/files#diff-a19f11b67475233e2ba66fbc5593fe39986edeca33e5e09f350dd4efe3726997L459-L460, https://github.com/mui/mui-x/pull/15651/files#diff-a19f11b67475233e2ba66fbc5593fe39986edeca33e5e09f350dd4efe3726997L504

File: packages/x-data-grid/src/hooks/features/rowSelection/gridRowSelectionSelector.ts (hunk 5 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/rowSelection/gridRowSelectionSelector.ts:16]: The exclude selection model is only used when all rows are selectable.
Added a comment to mention this.

Anything else you can think of that won't be covered here?

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts (hunk 1 above)
Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: Yes, I think (1) is the way to go. Both shapes of the model should be equivalent, which isn't the case for (2).

Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: > The more corner cases I fix, the fewer opportunities for the exclude selection model 

It's not that it's not usable for the conditions that you've guarded for, it's that some of them might require building a non-empty exclude model. You'd need an equivalent `getRowsToBeSelectedAsExclude()` function. And there are some cases in which it could make sense to do that work. For example, if there are filters applied that show 10 out of 1,000,000 total rows, using an exclude model would be much faster than building an include one.

File: packages/x-data-grid/src/hooks/features/rowSelection/gridRowSelectionSelector.ts (hunk 5 above)
Comment (arminmeh) [reply packages/x-data-grid/src/hooks/features/rowSelection/gridRowSelectionSelector.ts]: In that case, I think that it should be fine

File: test/utils/helperFn.ts [hunk 6]
```diff
@@ -191,3 +191,7 @@ export const getSelectInput = (combobox: Element) => {
 export function getSelectByName(name: string) {
   return getSelectInput(screen.getByRole('combobox', { name }))!;
 }
+
+export const includeRowSelection = (ids: GridRowId[]) => {
```
Comment (MBilalShafi) [inline test/utils/helperFn.ts:195]: Could this be useful as a public export too?
For example, it could be used as a solution in migration guide diff (and also in the codemod probably).

```diff
-const [rowSelectionModel, setRSM] = React.useState([1, 2, 3]);
+const [rowSelectionModel, setRSM] = React.useState(includeRowSelection([1, 2, 3]));
```

File: packages/x-data-grid-pro/src/tests/rowSelection.DataGridPro.test.tsx [hunk 7]
```diff
@@ -731,7 +731,7 @@ describe('<DataGridPro /> - Row selection', () => {
         />,
       );
 
-      expect(onRowSelectionModelChange.callCount).to.equal(2); // Dev mode calls twice
+      expect(onRowSelectionModelChange.callCount).to.equal(reactMajor < 19 ? 2 : 1); // Dev mode calls twice on React 18
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/tests/rowSelection.DataGridPro.test.tsx:734]: We should probably disable dev mode (aka strict mode) in testing, as it's not present in production.

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts (hunk 1 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: @MBilalShafi Yes, this is the current behavior:

https://github.com/user-attachments/assets/94f95395-72b1-4aa7-9b31-bd4328d19c06

File: packages/x-data-grid/src/models/gridRowSelectionModel.ts [hunk 8]
```diff
@@ -5,6 +5,65 @@ export type GridRowSelectionPropagation = {
...
+  select(id: GridRowId) {
+    this.data.delete(id);
+  }
+
+  unselect(id: GridRowId) {
+    this.data.add(id);
+  }
+
+  size() {
+    return this.data.size;
```
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/x-data-grid/src/models/gridRowSelectionModel.ts:60]: Turns out I'm not using this method anywhere. I'll delete it for now.

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts [hunk 9]
```diff
@@ -1,5 +1,6 @@
 import * as React from 'react';
 import { RefObject } from '@mui/x-internals/types';
+import { unstable_useEventCallback as useEventCallback } from '@mui/utils';
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:3]: IIUC, direct imports are better.

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts [hunk 10]
```diff
@@ -195,7 +185,11 @@ export const useGridRowSelection = (
   );
 
   const isRowSelected = React.useCallback<GridRowSelectionApi['isRowSelected']>(
-    (id) => gridRowSelectionStateSelector(apiRef.current.state).includes(id),
+    (id) => {
+      const model = gridRowSelectionStateSelector(apiRef.current.state);
+      const selectionManager = createRowSelectionManager(model);
+      return selectionManager.has(id);
```
Comment (romgrk) [inline packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:191]: It would be convenient to be able to put the selection manager directly in the state rather than to have to re-create it everytime we need it :/

Comment (romgrk) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:191]: Alternatively, put it in a memoized selector.

File: packages/x-data-grid-pro/src/tests/rowSelection.DataGridPro.test.tsx (hunk 7 above)
Comment (cherniavskii) [reply packages/x-data-grid-pro/src/tests/rowSelection.DataGridPro.test.tsx]: On the other hand, we want to catch issues that devs might experience in dev mode.

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts (hunk 10 above)
Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: Good point, I added `gridRowSelectionManagerSelector` and used it where applicable

File: packages/x-data-grid/src/models/gridRowSelectionModel.ts [hunk 11]
```diff
@@ -5,6 +5,65 @@ export type GridRowSelectionPropagation = {
   parents?: boolean;
 };
 
-export type GridInputRowSelectionModel = readonly GridRowId[] | GridRowId;
+export type GridRowSelectionModel = { type: 'include' | 'exclude'; ids: Set<GridRowId> };
 
-export type GridRowSelectionModel = readonly GridRowId[];
+interface SelectionManager {
```
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/x-data-grid/src/models/gridRowSelectionModel.ts]: Yeah, eventually we should do that.

File: test/utils/helperFn.ts (hunk 6 above)
Comment (cherniavskii) [reply test/utils/helperFn.ts:193]: Not sure, I would rather prefer an explicit usage of `Set`.
I only created this for tests because I had to update this in so many places 😅

Comment (MBilalShafi) [reply test/utils/helperFn.ts:193]: Makes sense to be more explicit, let's not export it.

**Review by romgrk — APPROVED** [review]

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts [hunk 12]
```diff
@@ -760,11 +826,20 @@ export const useGridRowSelection = (
     // props.isRowSelectable changed
     const currentSelection = gridRowSelectionStateSelector(apiRef);
 
-    if (isRowSelectable) {
-      const newSelection = currentSelection.filter((id) => isRowSelectable(id));
+    if (typeof isRowSelectable === 'function') {
+      let selectableIds = new Set<GridRowId>();
+      if (currentSelection.type === 'include') {
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:831]: Should we early-return if `currentSelection.type` is "exclude" as it's not been used?
