### PR TITLE
[TreeView] Automatic parents and children selection

### LINKED ISSUE #12883: [TreeView] Support parent / children selection relationship
# Related issues 

- #12802

# Current behavior

In the current implementation of the Tree View component (both `SimpleTreeView` and `RichTreeView`), selecting an item does not select its children and selecting all children of an item does not select its parent.

The behavior is exactly the same with checkbox selection.

**Selecting a parent (single select)**

image

Model value: `"A"`

**Selecting a leaf (single select)**

image

Model value: `"A1"`

**Selecting a parent (multi select)**

Here is what the result is when you click on `"A"`:

image

Model value: `["A"]`

**Selecting a leaf (multi select)**

Here is what the result is when you click on `"A1"`:

image

Model value: `["A1"]`

**Selecting all leaves of an item**

Here is what the result is when you click on `"A1"` then click on `"A3"` while pressing <kbd>Shift</kbd>:

image

Model value: `["A1", "A2", "A3"]`

# Alternatives model

## Model contains the selected leaves and the parent selection is deduced from their descendants

Based on https://github.com/mui/mui-x/pull/11452#issuecomment-2009687309

The following model can only work in multi selection.
The idea here is to only apply the selection on the leaves and then deduce the visual selection of the parents based on the selection status of their descendants:

- every descendant selected: selected
- some descendant selected: partially selected
- no descendant selected: not selected

**Selecting a parent (multi select)**

Here is what the result is when you click on `"A"`:

image

Model value: `["A1", "A2", "A3"]`

**Selecting a leaf (multi select)**

Here is what the result is when you click on `"A1"`:

image

Model value: `["A1"]`

**Selecting all leaves of an item**

Here is what the result is when you click on `"A1"` then click on `"A3"` while pressing <kbd>Shift</kbd>:

Model value: `["A1", "A2", "A3"]`

image

## Keep the model as is but visually select a children if one of its ancestors is selected

Based on https://github.com/mui/mui-x/pull/11452#issuecomment-2071989301

The following model can work in both single and multi selection.
The idea here is to visually select an item if it is selected in the model or if one of its ancestor is selected.

It might not work well with the checkbox where people probably expect the parent checkbox to change its status when selecting the children.

**Selecting a parent (single select)**

image

Model value: `"A"`

**Selecting a leaf (single select)**

image

Model value: `"A1"`

**Selecting a parent (multi select)**

Here is what the result is when you click on `"A"`:

image

Model value: `["A"]`

**Selecting a leaf (multi select)**

Here is what the result is when you click on `"A1"`:

image

Model value: `["A1"]`

**Selecting all leaves of an item**

Here is what the result is when you click on `"A1"` then click on `"A3"` while pressing <kbd>Shift</kbd>:

image

Model value: `["A1", "A2", "A3"]`

# Benchmarks

- https://johnnyreilly.com/mui-react-tree-view-check-children-uncheck-parents

**Search keywords**:

### PR DESCRIPTION
**Pull request by flaviendelangle**
No rush to review this PR since it's not for v7, breaking change preparations on the pickers are more pressing :pray: 

Apply #13757 for the Tree View
Closes #12883
[Doc preview](https://deploy-preview-14899--material-ui-x.netlify.app/x/react-tree-view/rich-tree-view/selection/#automatic-parents-and-children-selection)

Thanks to @MBilalShafi for all the work on the Data Grid feature, porting it to the Tree View is a piece of cake now :pray: 

There is a super small BC on the legacy `TreeItem`, I propose to keep the feature for the alpha, it will be the main new feature for the Tree View in the stablefor people without big datasets.

- [x] Build feature
- [x] Add doc
- [x] Add tests
- [x] Move the checkbox logic from `useTreeItem2` to `useTreeViewSelection.itemPlugin` (it's becoming quite large with the indeterminate support)
- [x] Support indeterminate checkbox state (same behavior as the grid)

### CODE REVIEW

File: packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.itemPlugin.ts [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+import { TreeViewItemId, TreeViewSelectionPropagation } from '../../../models';
+import { useTreeViewContext } from '../../TreeViewProvider';
+import { MuiCancellableEvent, TreeViewInstance, TreeViewItemPlugin } from '../../models';
+import {
+  UseTreeItem2CheckboxSlotPropsFromSelection,
+  UseTreeViewSelectionSignature,
+} from './useTreeViewSelection.types';
+import { UseTreeViewItemsSignature } from '../useTreeViewItems';
+
+function getCheckboxStatus({
```
Comment (flaviendelangle) [inline packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.itemPlugin.ts:13]: This would benefit from a selector when available

File: docs/data/tree-view/rich-tree-view/selection/selection.md [hunk 2]
```diff
@@ -75,25 +75,36 @@ Use the `onItemSelectionToggle` prop if you want to react to an item selection c
 
 {{"demo": "TrackItemSelectionToggle.js"}}
 
-## Parent / children selection relationship
+## Automatic parents and children selection
```
Comment (flaviendelangle) [inline docs/data/tree-view/rich-tree-view/selection/selection.md:78]: Basically a copy paste of the grid doc
If we modify this one, I'd be in favor of having Sam check the changes and apply the same to the grid one.

File: packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts [hunk 3]
```diff
@@ -94,6 +99,23 @@ export interface UseTreeViewSelectionParameters<Multiple extends boolean | undef
...
+   *
+   * - Selecting all the filtered descendants of a parent selects the parent automatically.
+   * - Deselecting a descendant of a selected parent deselects the parent automatically.
+   *
+   * Only works when `multiSelect` is `true`.
+   * On the SimpleTreeView, only the expanded items are considered (since the collapsed item are not passed to the Tree View component at all)
+   *
+   * @default { parents: false, descendants: false }
+   */
+  selectionPropagation?: TreeViewSelectionPropagation;
```
Comment (flaviendelangle) [inline packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts:118]: Same as the doc, it's a copy paste of the grid JSDoc

File: docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+          label="Auto select descendants"
+        />
+        <FormControlLabel
+          control={
+            <Checkbox
+              checked={selectionPropagation.parents}
+              onChange={(event) =>
+                setSelectionPropagation((prev) => ({
+                  ...prev,
+                  parents: event.target.checked,
```
Comment (MBilalShafi) [inline docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx:73]: Clicking on an indeterminate checkbox when `selectionPropagation.parents='true'` does nothing. Is it intended?

https://github.com/user-attachments/assets/6ccfeb27-933f-4b54-9418-272ae6802057

Comment (flaviendelangle) [reply docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx:73]: Probably not :laughing: 
I'll have a look

File: docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+  TreeViewBaseItem,
+  TreeViewSelectionPropagation,
+} from '@mui/x-tree-view/models';
+
+const MUI_X_PRODUCTS: TreeViewBaseItem[] = [
+  {
+    id: 'grid',
+    label: 'Data Grid',
+    children: [
+      { id: 'grid-community', label: '@mui/x-data-grid' },
```
Comment (MBilalShafi) [inline docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx:17]: It'd be great to have a demo with more than two nested level to let the users test propagation better.

File: docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx (hunk 4 above)
Comment (flaviendelangle) [reply docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx:73]: The grid has the exact same behavior
It come from this line: https://github.com/mui/mui-x/blob/4bc5acc101590bf64eef33270ef803647e249dde/packages/x-data-grid/src/hooks/features/rowSelection/utils.ts#L94

https://github.com/user-attachments/assets/eefab1b3-073b-43a0-9caf-4e35d626be2d

Not sure if removing this condition has unplaned consequences

File: docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx (hunk 5 above)
Comment (flaviendelangle) [reply docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx:17]: We don't have a deeper data set yet
I'll take the opportunity to create one :+1:

File: docs/data/tree-view/datasets/employees.ts [hunk 6]
```diff
@@ -0,0 +1,40 @@
+import { TreeViewBaseItem } from '@mui/x-tree-view/models';
+
+export const EMPLOYEES_DATASET: TreeViewBaseItem[] = [
```
Comment (flaviendelangle) [inline docs/data/tree-view/datasets/employees.ts:3]: I recreated the exact same dataset as the one I did for the Tree Data feature of the grid :+1:

File: docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx (hunk 5 above)
Comment (flaviendelangle) [reply docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx]: Done :ok_hand:

File: docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx (hunk 4 above)
Comment (MBilalShafi) [reply docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx:41]: Correct, the issue exists on the Data Grid side too, but there's a slight difference. It's only reproducable only when the `descendants` checkbox is not checked.

I'll try to make fix the behavior on the Data Grid side. 👍 

P.S The attached video doesn't work for me, maybe it wasn't fully uploaded?

File: docs/data/tree-view/rich-tree-view/selection/selection.md [hunk 7]
```diff
@@ -75,25 +75,36 @@ Use the `onItemSelectionToggle` prop if you want to react to an item selection c
...
+  descendants?: boolean; // default: false
+  parents?: boolean; // default: false
+};
+```
 
-Don't hesitate to leave a comment on the same issue to influence what gets built.
-Especially if you already have a use case for this component,
-or if you are facing a pain point with your current solution.
-:::
+When `rowSelectionPropagation.descendants` is set to `true`.
```
Comment (noraleonte) [inline docs/data/tree-view/rich-tree-view/selection/selection.md:91]:
```suggestion
When `selectionPropagation.descendants` is set to `true`.
```

File: docs/data/tree-view/rich-tree-view/selection/selection.md [hunk 8]
```diff
@@ -75,25 +75,36 @@ Use the `onItemSelectionToggle` prop if you want to react to an item selection c
...
+
+- Selecting a parent selects all its filtered descendants automatically.
+- Deselecting a parent row deselects all its filtered descendants automatically.
 
-If you cannot wait for the official implementation,
-you can create your own custom solution using the `selectedItems`,
-`onSelectedItemsChange` and `onItemSelectionToggle` props:
+When `rowSelectionPropagation.parents` is set to `true`.
```
Comment (noraleonte) [inline docs/data/tree-view/rich-tree-view/selection/selection.md:96]:
```suggestion
When `selectionPropagation.parents` is set to `true`.
```

File: docs/data/tree-view/rich-tree-view/selection/selection.md [hunk 9]
```diff
@@ -75,25 +75,36 @@ Use the `onItemSelectionToggle` prop if you want to react to an item selection c
...
+```
 
-Don't hesitate to leave a comment on the same issue to influence what gets built.
-Especially if you already have a use case for this component,
-or if you are facing a pain point with your current solution.
-:::
+When `rowSelectionPropagation.descendants` is set to `true`.
+
+- Selecting a parent selects all its filtered descendants automatically.
+- Deselecting a parent row deselects all its filtered descendants automatically.
```
Comment (noraleonte) [inline docs/data/tree-view/rich-tree-view/selection/selection.md:94]:
```suggestion
- Selecting a parent selects all its descendants automatically.
- Deselecting a parent deselects all its descendants automatically.
```

File: docs/data/tree-view/rich-tree-view/selection/selection.md [hunk 10]
```diff
@@ -75,25 +75,36 @@ Use the `onItemSelectionToggle` prop if you want to react to an item selection c
...
 
-If you cannot wait for the official implementation,
-you can create your own custom solution using the `selectedItems`,
-`onSelectedItemsChange` and `onItemSelectionToggle` props:
+When `rowSelectionPropagation.parents` is set to `true`.
 
-{{"demo": "ParentChildrenSelectionRelationship.js"}}
+- Selecting all the filtered descendants of a parent selects the parent automatically.
```
Comment (noraleonte) [inline docs/data/tree-view/rich-tree-view/selection/selection.md:98]:
```suggestion
- Selecting all the descendants of a parent selects the parent automatically.
```

File: packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts [hunk 11]
```diff
@@ -94,6 +99,23 @@ export interface UseTreeViewSelectionParameters<Multiple extends boolean | undef
    * @default false
    */
   checkboxSelection?: boolean;
+  /**
+   * When `rowSelectionPropagation.descendants` is set to `true`.
+   *
+   * - Selecting a parent selects all its filtered descendants automatically.
+   * - Deselecting a parent row deselects all its filtered descendants automatically.
```
Comment (noraleonte) [inline packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts:106]:
```suggestion
   * - Selecting a parent selects all its descendants automatically.
   * - Deselecting a parent row deselects all its descendants automatically.
```

File: packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts [hunk 12]
```diff
@@ -94,6 +99,23 @@ export interface UseTreeViewSelectionParameters<Multiple extends boolean | undef
...
+   *
+   * When `rowSelectionPropagation.parents` is set to `true`.
+   *
+   * - Selecting all the filtered descendants of a parent selects the parent automatically.
+   * - Deselecting a descendant of a selected parent deselects the parent automatically.
```
Comment (noraleonte) [inline packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts:111]:
```suggestion
   * - Selecting all the descendants of a parent selects the parent automatically.
   * - Deselecting a descendant of a selected parent deselects the parent automatically.
```

**Review by noraleonte — APPROVED** [review]
Amazing addition 🎉 That was super fast 🤭

File: packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts [hunk 13]
```diff
@@ -94,6 +99,23 @@ export interface UseTreeViewSelectionParameters<Multiple extends boolean | undef
    * @default false
    */
   checkboxSelection?: boolean;
+  /**
+   * When `rowSelectionPropagation.descendants` is set to `true`.
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts:103]: Oh I forgot to modify it after modifying the grid ones :laughing:

File: docs/data/tree-view/rich-tree-view/selection/selection.md [hunk 14]
```diff
@@ -75,25 +75,36 @@ Use the `onItemSelectionToggle` prop if you want to react to an item selection c
...
+- Deselecting a descendant of a selected parent deselects the parent automatically.
+
+The example below demonstrates the usage of the `selectionPropagation` prop.
+
+{{"demo": "SelectionPropagation.js", "bg": "inline", "defaultCodeOpen": false}}
```
Comment (noraleonte) [inline docs/data/tree-view/rich-tree-view/selection/selection.md:103]:
```suggestion
{{"demo": "SelectionPropagation.js", "defaultCodeOpen": false}}
```
I think the demo looks a bit weird without the border because of the inconsistent borderRadius of the toolbar here 🙈 
image

File: docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx (hunk 4 above)
Comment (MBilalShafi) [reply docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx:41]: **Update:** I think the Data Grid's behavior is correct and intended.

It fulfills this constraint: _"When `rowSelectionPropagation.parents='true'`, a parent will (only) be selected if all it's descendants are selected."_

So, if any of the descendants of a particular parent is not selected and the parent itself is allowed to be selected it'd violate the above constraint.

But in combined with `rowSelectionPropagation.descendants='true'`, it should work fine (i.e. select the parents + all the descendants)

Does it make sense?

File: packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts (hunk 12 above)
Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/plugins/useTreeViewSelection/useTreeViewSelection.types.ts:111]: You are right, it was taking on the grid, but the tree view do not use inline background on other demos

File: docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx (hunk 4 above)
Comment (flaviendelangle) [reply docs/data/tree-view/rich-tree-view/selection/SelectionPropagation.tsx:41]: Fixed
The Tree View was not handling correctly the scenario where the checkbox is checked but the item is not in the model (scenario introduced in this PR with the `indeterminate` state).

I do agree with you, it's not a great UX but I suppose it highlights that most people should enable both parents and descendants selection.

**Comment by Kavan72** [comment]
@flaviendelangle Thank you for the amazing work. I have one question: If the parent checkbox is in an indeterminate state and the user checks it, shouldn’t the first click select all the children, and the second click uncheck all of them along with the parent?

**Comment by flaviendelangle** [comment]
Hey @Kavan72, thanks for the feedback

The action when clicking on an indeterminate parent was the source of a lot of debate over on the Data Grid.
The current behavior their is to unselect all by default but have it configurable using the `indeterminateCheckboxAction` prop which has the following type:

```ts
  /**
   * If `select`, a group header checkbox in indeterminate state (like "Select All" checkbox)
   * will select all the rows under it.
   * If `deselect`, it will deselect all the rows under it.
   * Works only if `checkboxSelection` is enabled.
   * @default "deselect"
   */
indeterminateCheckboxAction?: 'select' | 'deselect'
```

On the Tree View, I followed the default behavior of the grid.
We can introduce the same `indeterminateCheckboxAction` prop in a follow up, it should be almost trivial to do it :+1:

**Comment by Kavan72** [comment]
> Hey @Kavan72, thanks for the feedback
> 
> The action when clicking on an indeterminate parent was the source of a lot of debate over on the Data Grid. The current behavior their is to unselect all by default but have it configurable using the `indeterminateCheckboxAction` prop which has the following type:
> 
> ```ts
>   /**
>    * If `select`, a group header checkbox in indeterminate state (like "Select All" checkbox)
>    * will select all the rows under it.
>    * If `deselect`, it will deselect all the rows under it.
>    * Works only if `checkboxSelection` is enabled.
>    * @default "deselect"
>    */
> indeterminateCheckboxAction?: 'select' | 'deselect'
> ```
> 
> On the Tree View, I followed the default behavior of the grid. We can introduce the same `indeterminateCheckboxAction` prop in a follow up, it should be almost trivial to do it 👍

That would be great feature 🙂

**Comment by MBilalShafi** [comment]
For v8, on the Data Grid side, it is also one of the considerations to make `select` the default behavior and remove `indeterminateCheckboxAction` prop, mainly aiming simplicity. I'd love decide on it together with the tree view for more consistency.

Context: [1](https://github.com/mui/mui-x/pull/14247#discussion_r1720773990), [2](https://github.com/mui/mui-x/issues/14300#issuecomment-2313923763)

**Comment by ArmandRedgate** [comment]
Hi.

I noticed that in the preview docs the bot linked, [this feature works](https://deploy-preview-14899--material-ui-x.netlify.app/x/react-tree-view/rich-tree-view/selection/#checkbox-selection), but it [does not in the live docs](https://mui.com/x/react-tree-view/rich-tree-view/selection/#checkbox-selection).

Was there a regression? Has this simply not been released yet?

(Our support key is 65425)

**Comment by flaviendelangle** [comment]
Hi,

This feature is part of the v8 alpha (which is deployed [here](https://next.mui.com/x/react-tree-view/rich-tree-view/selection/#automatic-parents-and-children-selection)).
