### PR TITLE
[data grid] Disable drag event handlers when row or column reorder are disabled

### LINKED ISSUE #4841: [DataGridPro] Unable to use 3rd party drag and drop over the grid
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When drag any elements with draggable={true} over the grid then rows flicker. 
It happens even if rowReordering={false}

### Expected behavior 🤔

if rowReordering is disabled, grid should not react on dragging any elements over it.

### Steps to reproduce 🕹

Steps:

1. I prepared an example: https://codesandbox.io/s/restless-forest-1f35e1?file=/src/App.tsx
2. Drag a grid row or green box over grid. 

### Context 🔦

We implemented drag and drop from one grid to another using [react-dnd](https://react-dnd.github.io/react-dnd/about). In version 5.10.0 it is broken. It is working in 5.8.0

### Your environment 🌎

<details>
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    @mui/material: ^5.4.4 => 5.4.4
    @mui/private-theming:  5.5.3
    @mui/styled-engine:  5.5.2
    @mui/system:  5.5.3
    @mui/types:  7.1.3
    @mui/utils:  5.5.3
    @mui/x-data-grid-generator: ^5.8.0 => 5.8.0
    @mui/x-data-grid-pro: ^5.10.0 => 5.10.0
    @mui/x-license-pro:  5.7.0
    @types/react: ^17.0.39 => 17.0.39
    react:  17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.4.4 => 4.4.4

Browser: Edge
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #4841 

Codesandbox: https://codesandbox.io/s/billowing-moon-4dw6h8

### CODE REVIEW

File: packages/grid/x-data-grid-pro/src/components/GridRowReorderCell.tsx [hunk 1]
```diff
@@ -85,7 +89,11 @@ const GridRowReorderCell = (params: GridRenderCellParams) => {
   };
 
   return (
-    <div className={classes.root} draggable={isDraggable} {...draggableEventHandlers}>
+    <div
+      className={classes.root}
+      draggable={isDraggable}
+      {...(isDraggable && draggableEventHandlers)}
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/components/GridRowReorderCell.tsx:95]: Maybe move `isDraggable` check to the `draggableEventHandlers` declaration to avoid creating event handlers on every render if they won't be used anyway?

```js
const draggableEventHandlers = isDraggable ? {
  onDragStart: publish('rowDragStart'),
  onDragOver: publish('rowDragOver'),
  onDragEnd: publish('rowDragEnd'),
} : null;
```

File: packages/grid/x-data-grid-pro/src/components/GridRowReorderCell.tsx [hunk 2]
```diff
@@ -39,11 +39,15 @@ const GridRowReorderCell = (params: GridRenderCellParams) => {
...
-    treeDepth === 1 &&
-    Object.keys(editRowsState).length === 0;
+  const isDraggable = React.useMemo(
+    () =>
+      !!(rootProps as DataGridProProcessedProps).rowReordering &&
+      !sortModel.length &&
+      treeDepth === 1 &&
+      Object.keys(editRowsState).length === 0,
+    // eslint-disable-next-line
+    [rootProps.rowReordering, sortModel, treeDepth, editRowsState],
```
[the remark this answers is not in the document]
Comment (flaviendelangle) [reply packages/grid/x-data-grid-pro/src/components/GridRowReorderCell.tsx:49]: Yes, as long as you import from the `useGridRootProps` of your current package, you should have the interface of the props of the current package.
But if you import it from `@mui/x-data-grid` (which you should not), it will fail.

So probably a legacy thing we forgot to remove during the introduction of the row reorder.

**Review by m4theushw — COMMENTED** [review]
Since the issue in #4841 was already fixed in the latest release according to https://github.com/mui/mui-x/issues/4841#issuecomment-1123837534, is there another CodeSandbox we can see the bug here, or a test case?

Based on the title of this PR, if we want to disable all event handlers, then we must disable them in the cell too:

https://github.com/mui/mui-x/blob/f90a0124a4e3fa0b8f53b662fb27de27a3103ac0/packages/grid/x-data-grid/src/components/cell/GridCell.tsx#L249

These event handlers are used to allow to drop the column header inside any cell of the column.

**Comment by DanailH** [comment]
> Since the issue in #4841 was already fixed in the latest release according to [#4841 (comment)](https://github.com/mui/mui-x/issues/4841#issuecomment-1123837534), is there another CodeSandbox we can see the bug here, or a test case?
> 
> Based on the title of this PR, if we want to disable all event handlers, then we must disable them in the cell too:
> 
> https://github.com/mui/mui-x/blob/f90a0124a4e3fa0b8f53b662fb27de27a3103ac0/packages/grid/x-data-grid/src/components/cell/GridCell.tsx#L249
> 
> These event handlers are used to allow to drop the column header inside any cell of the column.

@m4theushw I agree that it's a good idea to remove those as well - I forgot about them. The check should be in the `GridRow` component probably to avoid checks on each cell.
Regarding the bug - this is just an optimisation.

**Review by cherniavskii — APPROVED** [review]

File: packages/grid/x-data-grid/src/components/GridRow.tsx [hunk 3]
```diff
@@ -329,6 +340,7 @@ function GridRow(props: React.HTMLAttributes<HTMLDivElement> & GridRowProps) {
           tabIndex={tabIndex}
           className={clsx(classNames)}
           colSpan={colSpan}
+          enableDragEvents={enableDragEvents}
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/components/GridRow.tsx:343]: The prop name can be discussed since we never used "enableSomething", but we already have "disableSomething" so I don't have a strong opinion of which path to take.

**Review by m4theushw — APPROVED** [review]

File: packages/grid/x-data-grid/src/components/GridRow.tsx (hunk 3 above)
Comment (DanailH) [reply packages/grid/x-data-grid/src/components/GridRow.tsx]: Done
