### PR TITLE
[charts] Remove outdated prop-types

### LINKED ISSUE #10989: Prop type validation fail on PieChart
### Steps to reproduce

Link to live example: [(required)](https://codesandbox.io/p/sandbox/upbeat-gauss-2q9dz7)

Steps:
1. Add `innerRadius` and/or `outerRadius` to `series`
2. Set `legend.hidden` in `slotProps` to `true`

### Current behavior

* Warning: Failed prop type: The prop `dataIndex` is marked as required in `PieArcLabel`, but its value is `undefined`.
* Warning: Failed prop type: Invalid prop `innerRadius` of type `object` supplied to `PieArcLabel`, expected `number`.
* Warning: Failed prop type: Invalid prop `outerRadius` of type `object` supplied to `PieArcLabel`, expected `number`.
* Warning: Failed prop type: Invalid prop `cornerRadius` of type `object` supplied to `PieArcLabel`, expected `number`.

### Expected behavior

No warnings.

### Context

Specifying inner and outer radius and also hiding the labels.

This occurs after upgrading from 6.0.0-alpha.15 to latest stable.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: 11.11.1 => 11.11.1 
    @emotion/styled: 11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.23 
    @mui/core-downloads-tracker:  5.14.17 
    @mui/material: 5.14.17 => 5.14.17 
    @mui/private-theming:  5.14.17 
    @mui/styled-engine:  5.14.17 
    @mui/system:  5.14.17 
    @mui/types:  7.2.8 
    @mui/utils:  5.14.17 
    @mui/x-charts: 6.18.1 => 6.18.1 
    @types/react: ^18.2.33 => 18.2.33 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.2.2 
```
</details>

**Search keywords**: x-charts piechart

### PR DESCRIPTION
**Pull request by alexfauquette**
Fixes #10989

The current fix ignores proptypes generated by react-spring. Maybe we could find a better solution. Did not went to far into props generation scripts

### CODE REVIEW

**Comment by akamfoad** [comment]
@alexfauquette 

The default exports aren't the only exports in the changed files, there are named and type exports as well, here is the diff patch you could apply that fixes the issues:

```diff
diff --git a/packages/x-charts/src/PieChart/PieArcLabelPlot.tsx b/packages/x-charts/src/PieChart/PieArcLabelPlot.tsx
index af9460b98..2e5b903ab 100644
--- a/packages/x-charts/src/PieChart/PieArcLabelPlot.tsx
+++ b/packages/x-charts/src/PieChart/PieArcLabelPlot.tsx
@@ -11,7 +11,7 @@ import {
   ValueWithHighlight,
   useTransformData,
 } from './dataTransform/useTransformData';
-import PieArcLabel, { PieArcLabelProps } from './PieArcLabel';
+import { PieArcLabel, PieArcLabelProps } from './PieArcLabel';
 import { DefaultizedProps } from '../models/helpers';
 
 const RATIO = 180 / Math.PI;
diff --git a/packages/x-charts/src/PieChart/PieArcPlot.tsx b/packages/x-charts/src/PieChart/PieArcPlot.tsx
index d4565ef4d..b74d4efed 100644
--- a/packages/x-charts/src/PieChart/PieArcPlot.tsx
+++ b/packages/x-charts/src/PieChart/PieArcPlot.tsx
@@ -1,6 +1,6 @@
 import * as React from 'react';
 import { useTransition } from '@react-spring/web';
-import PieArc, { PieArcProps } from './PieArc';
+import { PieArc, PieArcProps } from './PieArc';
 import {
   DefaultizedPieSeriesType,
   DefaultizedPieValueType,
diff --git a/packages/x-charts/src/PieChart/index.tsx b/packages/x-charts/src/PieChart/index.tsx
index 9c0799db3..2eb39ce13 100644
--- a/packages/x-charts/src/PieChart/index.tsx
+++ b/packages/x-charts/src/PieChart/index.tsx
@@ -1,4 +1,18 @@
 export { PiePlot } from './PiePlot';
 export { PieChart } from './PieChart';
-export { PieArcLabel } from './PieArcLabel';
-export { PieArc } from './PieArc';
+export {
+  PieArcLabel,
+  type PieArcLabelClassKey,
+  type PieArcLabelClasses,
+  type PieArcLabelProps,
+  getPieArcLabelUtilityClass,
+  pieArcLabelClasses,
+} from './PieArcLabel';
+export {
+  PieArc,
+  type PieArcClassKey,
+  type PieArcClasses,
+  type PieArcProps,
+  getPieArcUtilityClass,
+  pieArcClasses,
+} from './PieArc';
```

Confirmed by running `yarn typescript:ci`, all tests are green locally on my side

File: packages/x-charts/src/PieChart/index.tsx [hunk 1]
```diff
@@ -1,5 +1,6 @@
 export { PiePlot } from './PiePlot';
 export { PieChart } from './PieChart';
-
-export * from './PieArc';
-export * from './PieArcLabel';
+export { PieArcLabel, getPieArcLabelUtilityClass, pieArcLabelClasses } from './PieArcLabel';
+export type { PieArcLabelClassKey, PieArcLabelClasses, PieArcLabelProps } from './PieArcLabel';
+export { PieArc, getPieArcUtilityClass, pieArcClasses } from './PieArc';
+export type { PieArcClassKey, PieArcClasses, PieArcProps } from './PieArc';
```
Comment (alexfauquette) [inline packages/x-charts/src/PieChart/index.tsx:6]: Doing that to avoid breaking change, but not sure it's worth exporting them. For example, BarElements are not exported.

When doing cherry pick I would just remove the export

**Review by flaviendelangle — APPROVED** [review]
