### PR TITLE
[data grid] Fix tree data selection bug

### LINKED ISSUE #20525: [data grid] Unselectable children in Grouped Rows prevents parent row from being fully selected
### Steps to reproduce

Steps:
1. Open this link to live example: https://stackblitz.com/edit/mflmkyvp?file=src/Demo.tsx
2. Check the "Select All" box (either at the top level or by 20th Century Fox)
3. Uncheck "Avatar" or "Skyfall" (under 20th Century Fox), putting Fox in an indeterminate state
4. Recheck the item from 3

### Current behavior

The group parent (20th Century Fox) remains in an Indeterminate state

https://github.com/user-attachments/assets/a183bd3b-ee1a-49aa-a254-40719ff08c1c

### Expected behavior

Based on the example [Disable selection on certain rows](https://mui.com/x/react-data-grid/row-selection/#disable-selection-on-certain-rows) in the docs, where the table's "select all" becomes Selected (not indeterminate) when re-checking an item:

We expected that when all items that can be selected are checked, the parent would become checked (not indeterminate)

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.0 undefined
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: latest => 11.14.0 
    @emotion/styled: latest => 11.14.1 
    @mui/core-downloads-tracker:  7.3.5 
    @mui/icons-material: latest => 7.3.5 
    @mui/material: latest => 7.3.5 
    @mui/private-theming:  7.3.5 
    @mui/styled-engine:  7.3.5 
    @mui/system:  7.3.5 
    @mui/types:  7.4.8 
    @mui/utils:  7.3.5 
    @mui/x-data-grid:  8.20.0 
    @mui/x-data-grid-generator: latest => 8.20.0 
    @mui/x-data-grid-premium: latest => 8.20.0 
    @mui/x-data-grid-pro:  8.20.0 
    @mui/x-internal-exceljs-fork:  4.4.3 
    @mui/x-internals:  8.19.0 
    @mui/x-license:  8.19.0 
    @mui/x-telemetry:  8.19.0 
    @mui/x-virtualizer:  0.2.10 
    @types/react: latest => 19.2.7 
    react: latest => 19.2.0 
    react-dom: latest => 19.2.0 
    typescript: latest => 5.9.3 
```
</details>

**Search keywords**: isRowSelectable group parent children

**Order ID**: 115285

### PR DESCRIPTION
**Pull request by michelengelen**
When a row is not selectable within a parent row it was not performing the parent selection propagation correctly (only showing indeterminate state).

This now selects the parent when all selectable rows are selected, reflecting the correct state.

Fixes #20525 

https://stackblitz.com/edit/mflmkyvp-1apuxwoo

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/rowSelection/utils.ts [hunk 1]
```diff
@@ -110,10 +110,22 @@ export const checkboxPropsSelector = createSelector(
...
-      } else {
-        hasUnSelectedDescendant = true;
+      // Check if row is selectable before considering it for parent selection state
+      const params: GridRowParams = {
+        id: itemToTraverseId,
+        row: rowsLookup[itemToTraverseId],
+        columns,
+      };
+      const rowIsSelectable =
+        typeof isRowSelectable === 'function' ? isRowSelectable(params) : true;
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/rowSelection/utils.ts]:
```suggestion
      const rowIsSelectable = apiRef.current.isRowSelectable(itemToTraverseId);
```

This should work

**Comment by michelengelen** [comment]
Done @cherniavskii ... do you want to check again?
