### PR TITLE
[DataGridPro] Preserve parent selection for non-selectable children

### LINKED ISSUE #19074: [data grid] keepNonExistentRowsSelected does not work with pagination (mode = 'server') + treeData
.

### PR DESCRIPTION
**Pull request by MBilalShafi**
## 🎯 Summary

Fix an issue where selected tree data parent rows would lose their selection when rows are paged out and back in, if their children are restricted from selection via the `isRowSelectable` prop.

## 🐛 Problem

When using tree data with server-side pagination and `keepNonExistentRowsSelected=true`, selecting a parent row and then navigating to a different page would cause the parent to be deselected upon return, even though it should have been preserved.

The root cause was that the deselection logic only checked if children were filtered out (`filteredRowsLookup`), but didn't account for children that exist but are not selectable according to `isRowSelectable`.

## ✨ Solution

Introduce a `hasVisibleSelectableDescendant()` helper function that recursively checks if a node has any descendants that are both:
- ✓ Present in the grid (not filtered out)
- ✓ Selectable according to the `isRowSelectable` callback

The parent deselection logic now only removes the parent if at least one of its children has a visible, selectable descendant. This preserves the parent selection when all children are non-selectable.

## 📝 Changes

- **useGridRowSelection.ts**: Add `hasVisibleSelectableDescendant()` helper and update the parent deselection condition to account for `isRowSelectable`
- **rowSelection.DataGridPro.test.tsx**: Add test case `'should preserve selected tree data parents when rows are paged out and back'` to verify the fix

### Before (Broken):
https://stackblitz.com/edit/qzuyxzcr-6wkac43z

**Steps:**
- Parent row is selected
- User navigates to a different page
- User navigates back to the original page
- ❌ Parent row is now deselected (incorrect behavior)

### After (Fixed):
https://stackblitz.com/edit/qzuyxzcr-e7jw1zid

**Steps:**
- Parent row is selected
- User navigates to a different page
- User navigates back to the original page
- ✅ Parent row remains selected (correct behavior)

## ✅ Test Coverage

New test case simulates the scenario by:
1. Restricting selection to root-level nodes only via `isRowSelectable()`
2. Selecting a parent node
3. Toggling between two pages of data
4. Verifying the parent remains selected after returning to the original page

---

Fixes #19074

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts [hunk 1]
```diff
@@ -555,6 +555,29 @@ You need to upgrade to DataGridPro or DataGridPremium component to unlock multip
       ids: new Set(currentSelection.ids),
     };
     const selectionManager = createRowSelectionManager(newSelectionModel);
+    const hasVisibleSelectableDescendant = (nodeId: GridRowId): boolean => {
```
Comment (arminmeh) [inline packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: Did you consider building a lookup for this instead of having to loop through all descendants?
I think that there are more places where we need to go through all descendants in the selection logic.

Maybe calculating this once, while the tree is being created, would help with the performance?

**Comment by nathan-lampi-ag** [comment]
@MBilalShafi Chasing on this issue. It is the final thing blocking our adoption of MUI X v8.

**Review by siriwatknp — COMMENTED** [review]
Thanks for the fix! The core logic looks correct. A few suggestions:

1. **Function naming**: `hasVisibleSelectableDescendant` is misleading for leaf nodes — it checks the node itself, not its descendants. Consider `isOrHasSelectableDescendant` or similar.

2. **Test coverage**: The test only covers root-level selectability. Would be good to add a case with mixed selectability (some children selectable, some not) to verify partial unselection works correctly.

3. Minor: the `for` loop in the helper could use `node.children.some()` for consistency with the call site, though the perf difference is negligible.

Overall the fix is solid — see inline comments for specifics.

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts [hunk 2]
```diff
@@ -555,6 +555,29 @@ You need to upgrade to DataGridPro or DataGridPremium component to unlock multip
...
+      const node = rowTree[nodeId];
+      if (!node) {
```
Comment (siriwatknp) [inline packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:560]: Nit: This function checks if the node *itself* is visible+selectable (leaf case) or if any descendant is (group case). The name `hasVisibleSelectableDescendant` is misleading for the leaf path — something like `isOrHasSelectableDescendant` would be more accurate.

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts (hunk 1 above)
Comment (siriwatknp) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: I think the current approach is fine. Can be optimized later to focus on the bug fix.

**Review by siriwatknp — APPROVED** [review]
Looks good to me, unless @arminmeh has strong opinion or insight about the performance downside.

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts (hunk 1 above)
Comment (MBilalShafi) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: The suggestion is nice, but I think the performance impact would be more visible with deeply nested trees with multiple levels and large numbers of rows. One small trade-off would be the re-computation of the lookup when dependencies change, which if happens more often then expected could become a bit expensive.
I also think to work on this optimization in a separate PR focusing on different possible outcomes.
Wdyt @arminmeh ?

Comment (arminmeh) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts]: We can focus on this in a separate PR.
Should not be a blocker for merging this now.
