### PR TITLE
[data grid] Avoid subscribing to `renderContext` state in grid root for better scroll performance

### LINKED ISSUE #15168: Scroll performance regression since v7.18.0 (probably)
### Search keywords

scroll, performance, safari

### Latest version

- [X] I have tested the latest version

### Affected products

_No response_

### Steps to reproduce

Difficult to provide a reproduction right now. It's especially pronounced in one of hour heaviest datagrids where we draw a sparkline in a cell (on a canvas). In Chrome there are occasional dropped frames, but at least it's usable still, however, on Safari, CPU is completely clogged (=maxed out) and there's severe banding and delays in rendering, which completely breaks the UX.

Performance in v7.15.0 (but seeing similar performance in v7.17.0 as well)
https://github.com/user-attachments/assets/9f06d8f8-f0cc-4213-9f8d-97152fc032b7

Performance on v7.18.0:
https://github.com/user-attachments/assets/cf3f3163-0413-4e57-a36e-0742ce0d2f22

Especially bad frame from the last video:
Screenshot 2024-10-29 at 16 07 44

Same browser (Safari v18.1), same datagrid, only difference is the `mui/x-data-grid` version.

If I would go crazy with scrolling on v7.18.0, my screen would go blank. The overall picture looks even worse than the single column, but I cannot share that view due to the nature of the data displayed.

There might be small differences in performance between v7.15.0 and v.7.17.0 as well, but that would require more measurements, as I'm so far just eyeballing it. But completely usable still.

We decided to downgrade to v7.15.0 for now just to be safe, as anything later than v17.8.0 is unusable for us.

### Current behavior

Janky scroll, dropped frames.

### Expected behavior

Smooth scroll, no dropped frames.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by lauri865**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Probably fixes #15168

@MBilalShafi, started thinking about it, and I can see now why this selector hook is problematic:
https://github.com/mui/mui-x/blob/26b1463a76fe5c48ecf87b5eca1a4d5dbdab5f48/packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts#L228

We're forcing the root of the grid to re-render every time `renderContext` changes (which can happen quite a lot when scrolling fast), which adds extra overhead, since all the root hooks need to re-evaluate as well. Regardless of whether `rowSpanning` is enabled or not. Saw that the same issue is also present in `useGridDataSourceLazyLoader`. We should rely on events instead of creating new state there.

Removed the top-level `renderContext` selector hooks for both, and slightly improved `rowSpanning` feature isolation.

### CODE REVIEW

**Comment by lauri865** [comment]
Seed for thought for future refactoring:
I wonder if some of these features/plugins would be better to be loaded as separate components instead for even better isolation 🤔. E.g. core hooks should be loaded inline as it is, and features that need to be manually toggled should be loaded as empty components that are optionally mounted.

It seems very easy to introduce additional performance overhead with unused features currently.

**Comment by lauri865** [comment]
In the latest commits I'm also proposing a slightly easier to follow logic around resetting `rowSpanning` state. By default every `renderContext` change uses existing cache, and then specific events will explicitly reset that (row updates, filtering, column changes, etc.). Currently, I was having troubles following what exactly triggers resets and how it works. Removes the need to derive logic based on refs as it's currently done – both difficult to read, but more crucially, difficult to extend (e.g. the case of adding resets based on colDef changes below).

It also fixes a few issues:
* Currently updating columns breaks rowSpanning – state updates are reactive only to renderContext/range, but not colDef changes
* `backwardsHiddenCells` only scans one row up, which can also lead to odd spanning

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts [hunk 1]
```diff
@@ -179,7 +178,8 @@ export const rowSpanningStateInitializer: GridStateInitializer = (state, props,
       !orderedFields.length ||
       !dataRowIdToModelLookup ||
       !columnsLookup ||
-      isFilteringPending
+      isFilteringPending ||
+      !props.rowSpanning
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts:182]: The `if` condition above handles it already, right?
```suggestion
      isFilteringPending
```

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts [hunk 2]
```diff
@@ -322,35 +310,41 @@ export const useGridRowSpanning = (
...
-    if (tree !== previousTree.current) {
-      previousTree.current = tree;
-      updateRowSpanningState(true);
+  // Reset events trigger a full re-computation of the row spanning state:
+  // - The `unstable_rowSpanning` prop is updated (feature flag)
+  // - The filtering is applied
+  // - The sorting is applied
+  // - The `paginationModel` is updated
+  // - The rows are updated
+  const onRowsUpdate = React.useCallback(() => {
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts:322]: It doesn't run on row update only, maybe a name closer to it's behavior?
```suggestion
  const recomputeRowSpanningState = React.useCallback(() => {
```

**Review by MBilalShafi — APPROVED** [review]
Thank you for the PR, subscribing to `renderedRowsIntervalChange` rather than binding to the store does seem a better approach.

For my tests, it improved the safari performance ~30-40%, cherry-on-top I can observe a slight (~10-15%) performance improvement in Chrome too.

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts (hunk 1 above)
Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts]: Right, didn't see it for some reason. Changed it to early return instead for better readability.

File: packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts (hunk 2 above)
Comment (lauri865) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowSpanning.ts]: Agreed. Maybe `resetRowSpanningState` instead to align it with the `resetState` param in the handler it calls.

**Comment by lauri865** [comment]
> Thank you for the PR, subscribing to `renderedRowsIntervalChange` rather than binding to the store does seem a better approach.
> 
> For my tests, it improved the safari performance ~30-40%, cherry-on-top I can observe a slight (~10%) performance improvement in Chrome too.
> 
> As far as #15168 is concerned, the change certainly improved the Safari experience, we could do another benchmark on top of it if there are more areas we could improve in. However, that shouldn't be a blocker for merging this PR.

Great, thanks for testing!

Unrelated to the original issue – there are some other root-level hooks that can be optimised as well in the `useDataGridPremiumComponent` tree by removing instances of `useGridSelector`. `useGridSelector` on root level should be only used in exceptional cases to provide better isolation between components. Not every use can be avoided of course, but I quickly saw a number of instances where `useGridSelector` is used only to provide a dependency to `useCallback`. That's an easy refactor – just move the selector to `useCallback` without the hook.

Simple example: https://github.com/mui/mui-x/blob/758d8b8cbff00cada9a5998857395958a10e895a/packages/x-data-grid-pro/src/hooks/features/columnPinning/useGridColumnPinning.tsx#L61

But I'd probably move these to another PR.

**Comment by MBilalShafi** [comment]
> I quickly saw a number of instances where useGridSelector is used only to provide a dependency to useCallback. That's an easy refactor – just move the selector to useCallback without the hook.

Agreed 👍, however I remember a few use-cases where directly using selector caused a state out-of-sync issue, we gotta be careful of any such case when refactoring. In general, we should aim to keep things in the context they are required in, especially for the selectors that may regress the performance and opt-in features like row spanning which are not active at all the times.

File: packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts [hunk 3]
```diff
@@ -308,6 +308,7 @@ export const useGridDataSourceLazyLoader = (
 
   const handleScrolling: GridEventListener<'scrollPositionChange'> = React.useCallback(
     (newScrollPosition) => {
+      const renderContext = gridRenderContextSelector(privateApiRef);
```
Comment (romgrk) [inline packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: This kind of change is dangerous in my opinion. If we mix state from `useGridSelector` with state from the `apiRef` directly, we are mixing state from different render/update cycles. We should not use this pattern to fix performance issues.

Comment (lauri865) [reply packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: There's another PR I opened that takes care of the other useGridSelectors as well, which to me is the correct solution here. For reasons I described in the other PR.

Comment (romgrk) [reply packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: > which to me is the correct solution here

I'm open to removing code if we can prove that it won't introduce bugs, but mixing state from different update cycles is pretty important to avoid. For example, if part of the state comes from *before* a filter has been applied, and another part of the state comes from the latest `apiRef.current.state` *after* a filter has been applied, we'd be using state slices that aren't coherent with each other.

Using `apiRef` directly consistently would avoid the issue, though I'd be curious to see how reactive bindings are working.

I'm still catching up with notifications I missed during the holidays but I'll review #16001 in the next days.

Comment (lauri865) [reply packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: > but mixing state from different update cycles is pretty important to avoid

Completely agree, but you're more likely to do that with by accident with using `useGridSelector` on root level than not. Direct state selectors are more commonplace in the code pace as it stands today – either directly, or indirectly through `apiRef` methods. Using `useGridSelector`-s on root-level seems to be a more recent trend in the code base.

Compare the before and after of `useGridRowSpanning` hook. In which implementation can you answer the question more clearly – under what conditions is the row spanning state reset? 

I'm not trying to throw shade to anyone's code in particular, this is not an isolated example, and I could have easily written the same thing myself if I just started out from using `useGridSelector` instead hooking into the existing events. It's inevitable if you mix two paradigms, you end up writing duct tape to keep them in sync. That duct tape in React is `useEffect`, which becomes an implicit event that is run under certain conditions. Under which exactly can become quite difficult to understand the more direct and indirect dependencies we end up having, and the less isolated the code is to a particular component.

If you take a step back – no hook in the `useDataGridComponent` tree is directly responsible for rendering anything – they are not an explicit part of a rendering cycle of any particular component. However, the use of `useGridSelector` forces those into a declarative paradigm from the outset, while actually serving an imperative function in the context of the data grid.

Just to be clear, even if the motivation around this PR was to take care of a performance regression, the rationale around the other PR (#16001) is not performance per se, it's not me pushing my idea(s/ologies), it's not removing code. But it is to suggest a convention that enables writing more isolated features and easier to follow logic within those features – a foundation that would have prevented this regression in the first place. And it's a pretty simple one.

`useGridSelector`
* Perfect to use in component rendering life-cycle
* Should be avoided in root-level feature hooks / when hooking into the global state machine. The only true reason to use `useGridSelector` on root level is as a direct dependency of a `useEffect`, however that's seldom done and necessary, and usually a sign of a missing explicit event as `useEffect` itself will become that event implicitly, but may be invoked much more frequently than necessary.

FWIW, it doesn't seem to be a new convention either from my understanding of the code base. The older versions of the code base either explicitly or implicitly followed this very convention, at least to a much higher degree. Breaking seems to be a more recent trend.

Comment (romgrk) [reply packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: Your points make a lot of sense. The reactivity architecture via `useGridSelector()` has mostly been my effort, following the [point \#1 of this discussion](https://github.com/mui/mui-x/discussions/9001), and I initially established the guideline of "always use `useGridSelector`" as a way to provide a simple & clear rule for the rest of the team to follow. This in particular allows to easily refactor code between components & root-level hooks, which I've been doing a lot for the somewhat recent performance improvements.

> It's inevitable if you mix two paradigms, you end up writing duct tape to keep them in sync. That duct tape in React is useEffect, which becomes an implicit event that is run under certain conditions. Under which exactly can become quite difficult to understand the more direct and indirect dependencies we end up having, and the less isolated the code is to a particular component.

Yes that's a major source of bugs and it's been on my radar for some time. Our state management goes through various cycles of updates/renders before settling on a coherent state because we use the async `useEffect` to sync up parts of the state, whereas we should be using something that can synchronously settle on a valid state. For example, if the `rows` prop is updated, there are various rounds of (async) updates before the filtered, sorted, and grouped rows slices of state are updated to match the new `rows` prop.

I'm not sure yet what's the best way to solve the issue. Going all in into selectors could be a solution, because selectors can lazily sync with the latest state value, though they keep their state in a memoized memory cell that doesn't live on the `state` object so that's less debuggable. Alternatively, we could create some event-based system that updates the state synchronously when another part of the state changes, this would not be lazy but it would be more debuggable.

> useGridSelector: Perfect to use in component rendering life-cycle / Should be avoided in root-level feature hooks

I'm ok with that convention but it places a burden on the maintainers to be strict about observing those invariants, whereas creating specialized selectors would provide correctness without having to think about the context before using state data. Let me ping the team to see what's the consensus.

Comment (lauri865) [reply packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: Last comment for now, I promise – didn't mean to drag this into a big discussion ;)

> but it places a burden on the maintainers to be strict about observing those invariants, whereas creating specialized selectors would provide correctness without having to think about the context before using state data

I understand why you would want to favour simplicity there internally. However, the affected surface area is still much more contained in this (new) scenario. The flip-side of the current convention is that when shipping new (especially unstable) features, developers need to care for how the new feature may have spill-over effects to the whole code base, even if the new feature may not be enabled and doesn't even affect any rendered components – that's much more difficult, and that can come at either the cost of quality (cannot test everything all the time) or shipping velocity (afraid to break another thing in prod).

I do wonder, if the enforcement of the convention can be shifted over to an eslint rule or a test though.

Comment (romgrk) [reply packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: > I do wonder if the burden of enforcement of the convention can be shifted over to an eslint rule or a test though.

All our root-level hooks are grouped, so it wouldn't be too hard to do:

```js
// in useDataGridComponent()
if (DEV_MODE)
  disableUseGridSelector()

/* root-level hooks */

if (DEV_MODE)
  enableUseGridSelector()

// in useGridSelector()
if (DEV_MODE && isDisabled)
  throw new Error()
```

Comment (cherniavskii) [reply packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: > useGridSelector: Perfect to use in component rendering life-cycle / Should be avoided in root-level feature hooks

So in the feature hooks, we use plain state selectors in event listeners, and if there's no event, do we use `useGridSelector` + `useEffect`?

Comment (MBilalShafi) [reply packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: Really nice discussion points. A couple of cents from my side.

> If we mix state from `useGridSelector` with state from the `apiRef` directly, we are mixing state from different render/update cycles.

Yes, this should be avoided as much as possible, I supported the change in #15986 specific to the `renderContext` as this particular state update is a bit unusual, I suspected the performance lag in Safari is due to wrapping of the state update in `ReactDOM.flushSync`, extracting the value in the event listener seemed like a proper reactive handle for this case. The testing I did didn't exhibit any state mismatch too, we could revert if we find a case.

An alternate approach for this event (`handleScrolling`) could be to either extract the other state (`dimensions`) in the function too or use the argument (`params.renderContext`) passed to the event handler. 1 would avoid mixing of `useGridSelector` and `apiRef` slices, while 2 would remove state out-of-sync without extracting the selector slice.

> `useGridSelector` should be avoided in root-level feature hooks

If we manage to make that happen cleanly, it'll definitely make it harder for inactive features to impact the performance or unnecessarily re-render/re-compute some parts of the application, improving the overall performance, however, I'd be careful to avoid breaking an expected reactivity with this change.

> All our root-level hooks are grouped, so it wouldn't be too hard to do:

I assume there are some use cases where it's inevitable to avoid `useGridSelector` in root hooks, like when they are used as `useEffect` dependencies. We'd need to provide an escape hatch to make that happen.

Comment (lauri865) [reply packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: > If we manage to make that happen cleanly, it'll definitely make it harder for inactive features to impact the performance or unnecessarily re-render/re-compute some parts of the application, improving the overall performance, however, I'd be careful to avoid breaking an expected reactivity with this change.
> 
> >

I think the first question to ask if the event is missing is whether a new event should be added. If a state change triggers another piece of state to change as a side-effect, `useEffect/useLayoutEffect` are always worse options to write that logic in React than an event, as things will now happen in different render passes.

`useEffect` is an escape hatch from declarative rendering paradigm in react. In theory, the only appropriate use for `useEffect` in feature hooks (in relation to the internal state management) should be to sync props with the internal state. Of course there are other appropriate cases like subscribing to DOM events, etc.

I didn't see any obvious examples where I thought `useGridSelector` would be necessary in feature hooks, outside of `useGridDimensions` and `useGridRowsMeta` (although that could be fixed with more work as well, but since it's a core hook rather than feature hook, it's less of a concern to me; readability is much worse though with `useGridSelector`).

I'm curious to see if you have any examples though that would prove the inverse. The only theoretical case for `useGridSelector` I can think of – an event that mutates internal state needs to access the rendered value of the state (=old state). The only other case I can think of is that a feature hook needs to send the grid to re-render when no component depends on that state – but that smells of side-effects, and likely has a much nicer solution. If such cases would exist, they would likely be broken by react compiler in the future as well.

But I haven't found any such cases yet, and this change would have highlighted them as well:
https://github.com/mui/mui-x/pull/15666#issuecomment-2507682624

Comment (lauri865) [reply packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: Ah, almost forgot. An alternative escape hatch to `useGridSelector` could be `useGridSelectorChange`. Instead of creating/updating state, it would call a callback if the resulting selector value changes.

But I haven't seen a place where I would use it yet, except for `useGridDimensions` / `useGridRowsMeta`.

Comment (cherniavskii) [reply packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: > The only theoretical case for useGridSelector I can think of – an event that mutates internal state needs to access the rendered value of the state (=old state)

In this case, the old state = the current state (before the new one is applied), so a regular selector should work here. Does this make sense?

Comment (lauri865) [reply packages/x-data-grid-pro/src/hooks/features/serverSideLazyLoader/useGridDataSourceLazyLoader.ts:311]: > > The only theoretical case for useGridSelector I can think of – an event that mutates internal state needs to access the rendered value of the state (=old state)
> 
> In this case, the old state = the current state (before the new one is applied), so a regular selector should work here. Does this make sense?

I meant a case, e.g.:
* `onKeyDown` event fires
* `focusCell` state is changed (but updated state is not rendered until the next keyframe)
* `onCellKeyDown` internal event is fired
* For whatever reason, the `onCellKeyDown` consumer in a feature hook (=different hook than the one that manages focus state) needs to know the currently rendered `focusCell`

It's all purely theoretical though – I was just stretching my imagination to come up with a case where `useGridSelector` would be a necessary choice over straight selectors in **callbacks** (as I proposed), and hence tried to poke holes in my other PR. For avoidance of doubt, I haven't seen any practical example in the code where this is an actual use case.
