### PR TITLE
[charts] Fix TS bottle neck

### LINKED ISSUE #12921: [charts] Fix TS performances
In #12920 the Typescript usage for pickers has been improved. Remain the `AnimatedArea` and `BarElement` to improve on charts

**Search keywords**: TypeScript

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #12921

The issue seems to come from the `useSlotProps` which try to guess props types from the component `Bar`

Wich can be a `styled(animated.rect)` or a `rect` component with some additional props.

To simplify all that:

- I updated `BarProps` such that it knows it needs to expect props `x`, `y`, `width`, and `height` to be animated ones
- Override the type of `BarElementPath` such that `styles only get access the the `BarProps`

### CODE REVIEW

File: packages/x-charts/src/BarChart/BarElement.tsx [hunk 1]
```diff
@@ -130,7 +139,7 @@ function BarElement(props: BarElementProps) {
   };
   const classes = useUtilityClasses(ownerState);
 
-  const Bar = slots?.bar ?? BarElementPath;
+  const Bar = slots?.bar ?? (BarElementPath as React.ElementType<BarProps>);
```
Comment (flaviendelangle) [inline packages/x-charts/src/BarChart/BarElement.tsx:142]: Could this `as` be in the definition of `BarElementPath` or would this be problematic?

**Review by flaviendelangle — APPROVED** [review]
:ok_hand: Very nice improvement
