### PR TITLE
[TreeView] Fix hydration error

### LINKED ISSUE #14980: [TreeView] Hydration error from 7.19.0 onwards
### Steps to reproduce

Will not provide

### Current behavior

The Tree and TreeItem components **function as expected up until** version @mui/x-tree-view: 7.18.0.

After some investigation, it appears that **starting with version 7.19.0**, the **Tree component now requires a mandatory id attribute for each instance**. If this attribute is not supplied, a **hydration error occurs. In previous versions, this issue did not arise.**

Additionally, we are not using version 2 of the Tree and TreeItem components, which were recently refactored, so we cannot confirm whether this behavior is consistent in those versions.

To avoid confusion, we should update our documentation to reflect this requirement or consider fixing the issue to prevent users from having to investigate the code themselves.

### Expected behavior

_No response_

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: No duplicate found

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #14980
Extracted from #14210

Only sets the default id attribute after the hydration, like `useId` does

### CODE REVIEW

File: packages/x-tree-view/src/internals/corePlugins/useTreeViewId/useTreeViewId.ts [hunk 1]
```diff
@@ -37,4 +37,4 @@ useTreeViewId.params = {
   id: true,
 };
 
-useTreeViewId.getInitialState = ({ id }) => ({ id: { treeId: id ?? createTreeViewDefaultId() } });
+useTreeViewId.getInitialState = () => ({ id: { treeId: undefined } });
```
Comment (LukasTy) [inline packages/x-tree-view/src/internals/corePlugins/useTreeViewId/useTreeViewId.ts:40]: Couldn't we use `id` in the `getInitialState` if it is provided? 🤔 
```suggestion
useTreeViewId.getInitialState = ({ id }) => ({ id: { treeId: id ?? undefined } });
```

Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/corePlugins/useTreeViewId/useTreeViewId.ts:40]: I'll check if it causes problem :+1:

Comment (flaviendelangle) [reply packages/x-tree-view/src/internals/corePlugins/useTreeViewId/useTreeViewId.ts]: Updated
