### PR TITLE
[DataGrid] Restore main slot

### LINKED ISSUE #12601: [Datagrid-v7] theme.components.MuiDataGrid.styleOverrides.main no longer affects styles on 'MuiDataGrid-main' class/element
### Steps to reproduce

[Link to live example](https://stackblitz.com/edit/react-zumc2z-akdmhd?file=index.tsx,Demo.tsx)

Steps:
1. Modify MuiDataGrid main element styles through MUI Theme
2. Observe that styles are unchanged

### Current behavior

When upgrading from V6 to V7, we observed that some of the styles in our theme were no longer affecting the Datagrid appearance, specifically the border around our main grid body.  This didn't appear to be covered anywhere in the migration guide, so I'm assuming it is not intended.

### Expected behavior

I would expect the theme shown in my sandbox example: 
```
const theme = createTheme({
  components: {
    // Name of the component
    MuiDataGrid: {
      defaultProps: {
        showCellVerticalBorder: true,
        showColumnVerticalBorder: true,
      },
      styleOverrides: {
        footerContainer: {
          border: 0,
        },
        main: {
          borderRadius: 8,
          outline: `1px solid black`,
        },
        root: {
          border: 0,
          display: 'flex',
        },
      },
    },
  },
});
```
 To create a border around the main body of the datagrid, as it did in V6.

### Context

Currently we have a workaround by simply modifying the `MuiDataGrid-main` class directly, but this seems like it should be applying classes and isn't.

You can see here that the auto-generated class prefix gets created, but the expected full class name doesn't:

### V6
Screenshot 2024-03-28 at 10 27 02 AM

### V7 
Screenshot 2024-03-28 at 10 22 20 AM

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 Tested on Google Chrome

  System:
    OS: macOS 14.4
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    Yarn: 4.1.1 - ~/.asdf/installs/yarn/1.22.19/bin/yarn
    npm: 9.5.1 - ~/.asdf/installs/nodejs/18.16.0/bin/npm
  Browsers:
    Chrome: 123.0.6312.86
    Edge: Not Found
    Firefox: 123.0.1
    Safari: 17.4
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.15.14 
    @mui/icons-material: ^5.15.14 => 5.15.14 
    @mui/lab: ^5.0.0-alpha.169 => 5.0.0-alpha.169 
    @mui/material: ^5.15.14 => 5.15.14 
    @mui/private-theming:  5.15.14 
    @mui/styled-engine:  5.15.14 
    @mui/system:  5.15.14 
    @mui/types:  7.2.14 
    @mui/utils:  5.15.14 
    @mui/x-charts: ^7.0.0 => 7.0.0 
    @mui/x-data-grid:  7.0.0 
    @mui/x-data-grid-premium: ^7.0.0 => 7.0.0 
    @mui/x-data-grid-pro:  7.0.0 
    @mui/x-date-pickers:  7.0.0 
    @mui/x-date-pickers-pro: ^7.0.0 => 7.0.0 
    @mui/x-license:  7.0.0 
    @mui/x-license-pro: ^6.10.2 => 6.10.2 
    @types/react: ^18.2.70 => 18.2.70 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.4.3 => 5.4.3 
```
</details>

**Search keywords**: datagrid theme
**Order ID**: I'm filing this as a dev and don't have either of those things ^

### PR DESCRIPTION
**Pull request by romgrk**
Closes #12601 

The main slot got lost in the sticky PR, we restore it here.

### CODE REVIEW

File: packages/x-data-grid/src/components/virtualization/GridMainContainer.tsx [hunk 1]
```diff
@@ -2,7 +2,11 @@ import * as React from 'react';
 import { styled } from '@mui/system';
 import { useGridAriaAttributes } from '../../hooks/utils/useGridAriaAttributes';
 
-const Element = styled('div')({
+const Element = styled('div', {
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/components/virtualization/GridMainContainer.tsx:9]: Would align with other places (unless we are not following this convention any more)
```suggestion
const GridMainContainerRoot = styled('div', {
```

**Review by MBilalShafi — APPROVED** [review]

File: packages/x-data-grid/src/components/virtualization/GridMainContainer.tsx (hunk 1 above)
Comment (romgrk) [reply packages/x-data-grid/src/components/virtualization/GridMainContainer.tsx:9]: I find that very verbose for no tangible gain, I would like if we could adopt a more relaxed naming convention for internal components. This one never leaves the file.
