### PR TITLE
[charts] Fix error with empty dataset

### LINKED ISSUE #11032: [charts] Rendering a chart with an empty dataset throws an error
### Steps to reproduce

Link to live example: https://codesandbox.io/s/agitated-gould-tlj49f?file=/src/Demo.tsx

Steps:
1. Provide an empty `dataset`.
2. Provide a `series` value with a `dataKey` that can't be found due to no data available in the `dataset`.

### Current behavior

Throws an error:

```
TypeError
Cannot read properties of undefined (reading '1')
```

### Expected behavior

Renders empty chart, similar to when a dataset is not used & series data is empty.

### Context

I'm trying to render charts dynamically based upon user-defined filters.  When no data matches the filters that are applied, I want to render an empty chart.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  ```
  System:
    OS: macOS 14.0
  Binaries:
    Node: 20.3.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 119.0.6045.123
    Edge: Not Found
    Safari: 17.0
  npmPackages:
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.21 
    @mui/core-downloads-tracker:  5.14.15 
    @mui/icons-material: ^5.14.15 => 5.14.15 
    @mui/material: ^5.14.15 => 5.14.15 
    @mui/private-theming:  5.14.15 
    @mui/styled-engine:  5.14.15 
    @mui/system:  5.14.15 
    @mui/types:  7.2.7 
    @mui/utils:  5.14.15 
    @mui/x-charts: ^6.18.1 => 6.18.1 
    @mui/x-data-grid: ^6.16.3 => 6.16.3 
    @types/react: ^18.2.31 => 18.2.31 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.2.2 
  Browser:
    Electron app (Chrome?) on macOS
  ```
</details>

**Search keywords**: chart data dataset empty

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #11032

The issue was due to the initialisation of the reducer. It was looking for the first array item which does not exist when the data set is empty.

### CODE REVIEW

File: packages/x-charts/src/LineChart/extremums.ts [hunk 1]
```diff
@@ -21,21 +21,31 @@ export const getExtremumY: ExtremumGetter<'line'> = (params) => {
...
 
-        const getValues = isArea
-          ? (d: [number, number]) => d
-          : (d: [number, number]) => [d[1], d[1]]; // Id area should go from bottom to top, without area should only consider the top
+        const getValues: (d: [number, number]) => [number, number] = isArea
+          ? (d) => d
+          : (d) => [d[1], d[1]]; // Since this series is not used to display an area, we do not consider the base (the d[0]).
 
-        const [seriesMin, seriesMax] = series[seriesId].stackedData.reduce(
+        const seriesExtremums: ExtremumGetterResult = series[seriesId].stackedData.reduce(
```
Comment (flaviendelangle) [inline packages/x-charts/src/LineChart/extremums.ts:28]: You are accessing `series[seriesId].stackedData` 3 times
Maybes it's worth creating a variable for readability :+1:

File: packages/x-charts/src/LineChart/extremums.ts [hunk 2]
```diff
@@ -21,21 +21,31 @@ export const getExtremumY: ExtremumGetter<'line'> = (params) => {
...
           (seriesAcc, stackedValue) => {
             const [base, value] = getValues(stackedValue);
+
+            if (seriesAcc[0] === null) {
+              return [Math.min(base, value), Math.max(base, value)] as [number, number];
```
Comment (flaviendelangle) [inline packages/x-charts/src/LineChart/extremums.ts:33]: Can `seriesAcc[0]` be null in another scenario than `series[seriesId].stackedData.length === 0`?
If not, can we just skip the reduce when its empty?
