### PR TITLE
[codemod] Do not fail when props is missing

### LINKED ISSUE #8264: Codemod failures on Toolpad repo
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Run the codemod `v6.0.0/preset-safe` on https://github.com/mui/mui-toolpad/blob/d7fb0f17b81083e7e98899a9fccfc40b9f9ab0fe/packages/toolpad-components/src/DataGrid.tsx
2. Observe error:
```
 ERR /Users/janpotoms/Projects/toolpad/packages/toolpad-components/src/DataGrid.tsx Transformation error (Cannot read properties of undefined (reading 'name'))
TypeError: Cannot read properties of undefined (reading 'name')
    at find (/Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/util/removeObjectProperty.js:17:102)
    at Array.find (<anonymous>)
    at NodePath.<anonymous> (/Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/util/removeObjectProperty.js:17:69)
    at /Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/node_modules/jscodeshift/src/Collection.js:75:36
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/node_modules/jscodeshift/src/Collection.js:74:18)
    at removeObjectProperty (/Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/util/removeObjectProperty.js:16:6)
    at forEach (/Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/v6.0.0/data-grid/remove-stabilized-experimentalFeatures/index.js:20:38)
    at Array.forEach (<anonymous>)
    at transformer (/Users/janpotoms/.npm/_npx/a9b616de167a2c5b/node_modules/@mui/x-codemod/v6.0.0/data-grid/remove-stabilized-experimentalFeatures/index.js:19:12)
```

### Current behavior 😯

Codemod throws an error

### Expected behavior 🤔

Codemod modifies the file

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #8264

### CODE REVIEW

File: packages/x-codemod/src/util/removeObjectProperty.ts [hunk 1]
```diff
@@ -32,7 +32,7 @@ export default function removeObjectProperty({
     })
     .forEach((element) => {
       const targetAttribute = (element.value.openingElement.attributes as any).find(
```
Comment (Janpot) [inline packages/x-codemod/src/util/removeObjectProperty.ts:34]: IIUC `as any` is turning `attribute` into `any` as well, effectively removing the type safety. Would it be possible to avoid using `as any` in this file and replace with the babel type guards (e.g. `if (t.isIdentifier(...))`)?

Comment (alexfauquette) [reply packages/x-codemod/src/util/removeObjectProperty.ts:34]: I tries to remove the `any` of `path.value.openingElement.name as any` and after 30min I still do't have a clue about what are the differences between `JSXIdentifier`, `JSXNamespacedName`, and `JSXMemberExpression`

If someone is interested by this topic, you can find definition of various JSX types here:
https://etclabscore.github.io/json-schema-to-types/globals.html

Comment (LukasTy) [reply packages/x-codemod/src/util/removeObjectProperty.ts:34]: Of all the 3 items mentioned only `JSXMemberExpression` [does not seem to have](https://etclabscore.github.io/json-schema-to-types/interfaces/jsxmemberexpression.html) the `name` property.
So, maybe just do
```suggestion
      const targetAttribute = element.value.openingElement.attributes.filter(attribute => attribute.type !== 'JSXMemberExpression').find(
```
Or just include this case in the find criteria..? 🤔

**Review by LukasTy — APPROVED** [review]
