### PR TITLE
[test] Make focus state out-of-sync warning opt-in

### LINKED ISSUE #3850: [test] The cell with id=X and field= received focus
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Some of our tests trigger a new warning in tests:

```
console.error
    MUI: The cell with id=<redacted> and field=  received focus.
    According to the state, the focus should be at id=undefined, field=undefined.
    In the next render, the focus will be changed to match the state.
    Call `fireEvent.mouseUp` and `fireEvent.click` before to sync the focus with the state.
```

This is very recent.
We're following upgrades closely and are currently running v5.5.0. I can bissect if you want to find the precise version where this started happening.

### Expected behavior 🤔

No warning

### Steps to reproduce 🕹

Run tests of https://codesandbox.io/s/datagrid-tests-warning-9dy64?file=/src/App.spec.tsx

This is a very minimal example of our use case:
* A few columns
* The last columns contains buttons
* Some buttons trigger a Dialog with advanced controls

### Context 🔦

N/A

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.13 Linux Mint 20.3 (Una)
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: Not Found
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.3
```
</details>

### Order ID 💳 (optional)

31461

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #3850 

This PR changes to, by default, not fire the warning sent when a cell is clicked with `fireEvent.click` without `fireEvent.mouseUp`. Instead it will only be triggered if the new prop `experimentalFeatures.warnIfFocusStateIsNotSynced` is `true` and `NODE_ENV=test`.

### CODE REVIEW

**Comment by peterkmurphy** [comment]
I would love this fix to go into production. It would make our test code easier to understand having none of those `fireEvent.mouseUp` calls.

File: packages/grid/x-data-grid/src/models/props/DataGridProps.ts [hunk 1]
```diff
@@ -28,6 +28,11 @@ export interface GridExperimentalFeatures {
    * Will be part of the premium-plan when fully ready.
    */
   preventCommitWhileValidating: boolean;
+  /**
+   * Emits a warning if the cell receives focus without also syncing the focus state.
+   * Only works if NODE_ENV=test.
+   */
+  warnIfFocusStateIsNotSynced: boolean;
```
Comment (flaviendelangle) [inline packages/grid/x-data-grid/src/models/props/DataGridProps.ts:35]:
```suggestion
  warnIfFocusStateIsNotSyncedInTest: boolean;
```
Should we be 100% explicit ?

**Review by flaviendelangle — APPROVED** [review]

**Review by alexfauquette — APPROVED** [review]

File: packages/grid/x-data-grid/src/models/props/DataGridProps.ts (hunk 1 above)
Comment (m4theushw) [reply packages/grid/x-data-grid/src/models/props/DataGridProps.ts:35]: I'll leave as it is. In the comment already says the condition where it works.

image
