### PR TITLE
[DataGridPremium] Fix autosize grouping cell

### LINKED ISSUE #10848: [DataGridPro] Autosizing issues with row groups
### The problem in depth 🔍

I have a grouped grid and I wonder whether is there a way to make `autosizeOptions` to work for a grouped column? 
I've tried different options but still cannot make it work. Without grouping autosize works pretty well but if any of the column is grouped it doesn't work for that column.
Any help or advice is appreciated.
Here is a live example:
[https://codesandbox.io/s/async-sea-4r2smt?file=/src/Demo.tsx:945-960](https://codesandbox.io/s/async-sea-4r2smt?file=/src/Demo.tsx:945-960)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 14.0
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Edge: Not Found
    Safari: 17.0
  npmPackages:
    @emotion/react: ~11.11.1 => 11.11.1 
    @emotion/styled: ~11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.20 
    @mui/core-downloads-tracker:  5.14.14 
    @mui/icons-material: ~5.14.14 => 5.14.14 
    @mui/lab: ~5.0.0-alpha.149 => 5.0.0-alpha.149 
    @mui/material: ~5.14.14 => 5.14.14 
    @mui/private-theming:  5.14.14 
    @mui/styled-engine:  5.14.14 
    @mui/styles: ~5.14.14 => 5.14.14 
    @mui/system: ~5.14.14 => 5.14.14 
    @mui/types:  7.2.6 
    @mui/utils:  5.14.14 
    @mui/x-data-grid:  6.16.3 
    @mui/x-data-grid-premium: ~6.16.3 => 6.16.3 
    @mui/x-data-grid-pro:  6.16.3 
    @mui/x-date-pickers:  6.16.3 
    @mui/x-date-pickers-pro: ~6.16.3 => 6.16.3 
    @mui/x-license-pro:  6.10.2 
    @mui/x-tree-view: ~6.0.0-beta.0 => 6.0.0-beta.0 
    @types/react: ~18.2.21 => 18.2.21 
    react: ~17.0.2 => 17.0.2 
    react-dom: ~17.0.2 => 17.0.2 
    typescript: ~4.9.5 => 4.9.5 
```
</details>

**Search keywords**: datagrid
**Order ID**: 54867

### PR DESCRIPTION
**Pull request by romgrk**
Closes #10848

Fix the CSS width property so that the width calculation logic can figure it out properly.

Before: https://codesandbox.io/p/sandbox/async-sea-4r2smt
After: https://codesandbox.io/p/sandbox/strange-browser-d7x9ml

### CODE REVIEW

File: packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 1]
```diff
@@ -237,6 +237,9 @@ export const GridRootStyles = styled('div', {
         overflow: 'visible !important',
         whiteSpace: 'nowrap',
       },
+      [`& .${c.groupingCriteriaCell}`]: {
+        width: 'unset',
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:241]: This doesn't appear to work:

https://github.com/mui/mui-x/assets/13808724/a557b3ab-96c8-40f7-8711-be2d28579a8d

Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:241]: I could also spot a clipping with a number column having formatted values.

formatter

Comment (romgrk) [reply packages/grid/x-data-grid/src/components/containers/GridRootStyles.ts:241]: @cherniavskii It's working if you use the same case as the original issue. I've added the before/after links in the top comment. The issue with your case here is that the outliers filter is ignoring some cells. Maybe we should change the defaults for the outlier detection. But that would be a different issue.

@MBilalShafi Yes that's a bug. From what I can see it's a 1px difference triggering the text ellipsis. I think I'll not fix it here, because the cell DOM node change (removing `.cellContent`) is going to mess up the resizing code and I'll need to fix it again then, and I was planning to do that change as soon as possible.

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 2]
```diff
@@ -237,6 +237,12 @@ export const GridRootStyles = styled('div', {
         overflow: 'visible !important',
         whiteSpace: 'nowrap',
       },
+      [`& .${c.groupingCriteriaCell}`]: {
+        width: 'unset',
```
Comment (cherniavskii) [inline packages/x-data-grid/src/components/containers/GridRootStyles.ts:241]: It doesn't seem to work for nested groups, probably due to the margin-left offset applied to the nested cell content: https://codesandbox.io/p/sandbox/focused-thunder-pf5kdw?file=%2Fsrc%2FDemo.tsx%3A29%2C33

https://github.com/mui/mui-x/assets/13808724/ee1f0714-8a94-4de2-a628-473dfe32ec19

Should we change it to padding here?

https://github.com/mui/mui-x/blob/3a3263bef0ebeb52416b79a5b72fa431e2e50054/packages/x-data-grid-premium/src/components/GridGroupingCriteriaCell.tsx#L78-L83

Same for tree data.

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts [hunk 3]
```diff
@@ -237,6 +237,12 @@ export const GridRootStyles = styled('div', {
...
+      },
+      [`& .${c.treeDataGroupingCell}`]: {
+        width: 'unset',
```
Comment (cherniavskii) [inline packages/x-data-grid/src/components/containers/GridRootStyles.ts:244]: Added the same for tree data

**Review by cherniavskii — APPROVED** [review]

File: packages/x-data-grid/src/components/containers/GridRootStyles.ts (hunk 2 above)
Comment (romgrk) [reply packages/x-data-grid/src/components/containers/GridRootStyles.ts:241]: Yeah I think I'll rework the autosizing approach a bit with the cell DOM change, it will fix autosize for this case and the new cell DOM.
