### PR TITLE
[DataGrid] include `api` in `gridCellParams` interface

### LINKED ISSUE #14190: [data grid] `GridCellParams` TS type does not include `api` even though the object actually does
### Steps to reproduce

https://codesandbox.io/p/sandbox/14144-column-group-horizontal-borders-forked-9ctmlf

Steps:
1. Visit the linked codesandbox
2. Notice that TS is saying GridCellParams does not contain the api prop
3. Also notice that the example works without errors (aside from TS)

Originally found in #14144 

### Current behavior

_No response_

### Expected behavior

Need to update the GridCellParams TS type to include `api: GridApi`

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: GridCellParams api
**Order ID**: 0332927583

### PR DESCRIPTION
**Pull request by k-rajat19**
Fixes #14190

### CODE REVIEW

File: packages/x-data-grid/src/models/params/gridCellParams.ts [hunk 1]
```diff
@@ -65,6 +65,10 @@ export interface GridCellParams<
    * the tabIndex value.
    */
   tabIndex: 0 | -1;
+  /**
+   * The api of `DataGrid`.
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/models/params/gridCellParams.ts:69]:
```suggestion
   * GridApi that let you manipulate the grid.
```

For consistency with the other `api` annotations.

File: packages/x-data-grid/src/components/cell/GridCell.tsx [hunk 2]
```diff
@@ -75,9 +74,7 @@ export type GridCellProps = {
   [x: string]: any; // TODO v7: remove this - it breaks type safety
 };
 
-type CellParamsWithAPI = GridCellParams<any, any, any, GridTreeNodeWithRender> & {
-  api: GridApiCommunity;
-};
+type CellParamsWithAPI = GridCellParams<any, any, any, GridTreeNodeWithRender>;
```
Comment (KenanYusuf) [inline packages/x-data-grid/src/components/cell/GridCell.tsx:77]: Not sure this type name makes sense anymore, given GridCellParams has `api` - can we just use `GridCellParams` and remove this type?

Comment (k-rajat19) [reply packages/x-data-grid/src/components/cell/GridCell.tsx:77]: Thanks for the review,
can we just change the name of this type to let's say `CellParams` ? because we are using this type at one more place and ` GridCellParams<any, any, any, GridTreeNodeWithRender>` seems long to me .

Comment (k-rajat19) [reply packages/x-data-grid/src/components/cell/GridCell.tsx:77]: we should also probably change the name of this variable to `cellParams` ?
https://github.com/mui/mui-x/blob/496d64eac8400f6f06ba94886b7ae3695a7303c8/packages/x-data-grid/src/components/cell/GridCell.tsx#L186

Comment (KenanYusuf) [reply packages/x-data-grid/src/components/cell/GridCell.tsx:77]: Both of those suggestions make sense to me 👍

Comment (k-rajat19) [reply packages/x-data-grid/src/components/cell/GridCell.tsx]: we can remove the type I think  did a little refactoring  in [935aed2](https://github.com/mui/mui-x/pull/14201/commits/935aed229bcbd2a7ea359b358edf7f7719da3e0f)
