### PR TITLE
[charts] Fix grid with band scale

### LINKED ISSUE #18294: Error when enabling vertical cartesian grid on BarChart
### Steps to reproduce

Steps:
1. [Open this link to live example: (required)](https://codesandbox.io/p/sandbox/angry-pasteur-xv3xq4?file=%2Fsrc%2FDemo.tsx%3A28%2C54)
2. The error is shown immediately and it is caused by line 28 ("vertical: true"). Grid horizontal does not cause this issue.

### Current behavior

Image

On Chrome the error "Cannot read properties of undefined (reading 'getTime')" is shown. On Firefox the error is instead "value is undefined".

### Expected behavior

_No response_

### Context

_No response_

### Your environment

_No response_

**Search keywords**: BarChart grid vertical value is undefined

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #18294

### CODE REVIEW

File: packages/x-charts/src/ChartsGrid/ChartsHorizontalGrid.tsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ export function ChartsGridHorizontal(props: ChartsGridHorizontalProps) {
     <React.Fragment>
       {yTicks.map(({ value, offset }) => (
         <GridLine
-          key={`horizontal-${value.getTime?.() ?? value}`}
+          key={`horizontal-${value?.getTime?.() ?? value}`}
```
Comment (bernardobelchior) [inline packages/x-charts/src/ChartsGrid/ChartsHorizontalGrid.tsx:28]: Doesn't this mean our types are wrong? If value can be `null` or `undefined`, shouldn't we have gotten a TypeScript error?

Comment (alexfauquette) [reply packages/x-charts/src/ChartsGrid/ChartsHorizontalGrid.tsx:28]: Yes, it's because the `value` is set to `any`. Maybe `unknown` would be better
