### PR TITLE
[DataGridPro] Fix toggling detail panel using keyboard

### LINKED ISSUE #4387: [DataGridPro] Pressing `Space` on detail panel toggle cell doesn't toggle detail panel
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

`Space` doesn't toggle detail panel and moves focus to the bottom of the page:
https://mui.com/components/data-grid/group-pivot/#master-detail

https://user-images.githubusercontent.com/13808724/162194268-48934ad5-cbe9-4d46-8da6-34584b1ae821.mov

### Expected behavior 🤔

Similar to Row grouping, pressing `Space` on toggle cell should expand/collapse detail panel:
https://mui.com/components/data-grid/group-pivot/#row-grouping

https://user-images.githubusercontent.com/13808724/162194733-6386dda1-6216-4787-a5d4-f706eb902902.mov

### Steps to reproduce 🕹

Steps:

1. Go to https://mui.com/components/data-grid/group-pivot/#master-detail
2. Focus detail panel toggle cell (the one with `+`)
3. Press `Space` key
4. See that detail panel was not toggled

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### LINKED ISSUE #4388: [data grid] `Cmd+Enter` doesn't toggle detail panel on macOS
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

`Cmd+Enter` shortcut on macOS doesn't toggle detail panel

### Expected behavior 🤔

As per https://mui.com/components/data-grid/accessibility/#group-amp-pivot, `Ctrl+Enter` should toggle detail panel.
On macOS `Ctrl` should be replaced by `⌘ Command` key: (see https://mui.com/components/data-grid/accessibility/#key-assignment-conventions), therefore `Cmd+Enter` should toggle detail panel

### Steps to reproduce 🕹

Steps:

1. Go to https://mui.com/components/data-grid/group-pivot/#master-detail on macOS
2. Click on any cell in master/detail demo
3. Press `Cmd+Enter`

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by cherniavskii**
Closes #4387
Fixes #4388

Preview: https://deploy-preview-4409--material-ui-x.netlify.app/x/react-data-grid/group-pivot/#master-detail

### CODE REVIEW

File: packages/grid/x-data-grid-pro/src/DataGridPro/useDataGridProComponent.tsx [hunk 1]
```diff
@@ -120,9 +120,9 @@ export const useDataGridProComponent = (
 
   useGridRowGrouping(apiRef, props);
   useGridTreeData(apiRef);
+  useGridDetailPanel(apiRef, props);
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/DataGridPro/useDataGridProComponent.tsx:123]: Had to move it before `useGridKeyboardNavigation` to prevent `Space` moving focus to the bottom of the page

File: packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts [hunk 2]
```diff
@@ -74,10 +74,19 @@ export const useGridDetailPanel = (
...
-        return;
+      if (
+        (event.ctrlKey || event.metaKey) &&
+        event.key === 'Enter' &&
+        props.getDetailPanelContent != null
+      ) {
+        apiRef.current.toggleDetailPanel(params.id);
+      }
+
+      if (params.field === GRID_DETAIL_PANEL_TOGGLE_FIELD && event.key === ' ') {
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts:85]: Instead of early return, I've split the logic info two branches handling `Ctrl+Enter` and `Space` separately.

File: packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts [hunk 3]
```diff
@@ -74,10 +74,19 @@ export const useGridDetailPanel = (
...
+        apiRef.current.toggleDetailPanel(params.id);
+        event.stopPropagation();
+        event.preventDefault();
```
Comment (m4theushw) [inline packages/grid/x-data-grid-pro/src/hooks/features/detailPanel/useGridDetailPanel.ts:88]: Instead of `event.stopPropagation()`, could you add a check in https://github.com/mui/mui-x/blob/a84a5c52b240422019c49308b25f28b4211e9b0f/packages/grid/x-data-grid/src/hooks/features/keyboardNavigation/useGridKeyboardNavigation.ts#L117-L118?

We will have to duplicate the field identifier but I think it's OK.

Using `event.stopPropagation()` to disable default behaviors should be avoided whenever possible. If a listener is added to a parent element, it won't be called. I think that for #3844 we will have to create a global `keydown` listener, similar to the global `click` listener. https://github.com/mui/mui-x/blob/a84a5c52b240422019c49308b25f28b4211e9b0f/packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts#L266-L267

Any `event.stopPropagation()` will make it to not be called.

File: packages/grid/x-data-grid-pro/src/DataGridPro/useDataGridProComponent.tsx (hunk 1 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid-pro/src/DataGridPro/useDataGridProComponent.tsx]: Reverted

File: packages/grid/x-data-grid/src/hooks/features/keyboardNavigation/useGridKeyboardNavigation.ts [hunk 4]
```diff
@@ -129,6 +130,10 @@ export const useGridKeyboardNavigation = (
         }
 
         case ' ': {
+          const field = (params as GridCellParams).field;
+          if (field === GRID_DETAIL_PANEL_TOGGLE_FIELD) {
```
Comment (flaviendelangle) [inline packages/grid/x-data-grid/src/hooks/features/keyboardNavigation/useGridKeyboardNavigation.ts:134]: Could probably be a pre-processor like for `canBeReordered` at some point
Should we do the same check for the row grouping / tree data grouping columns ?

**Comment by flaviendelangle** [comment]
> We could have used a pre-processor indeed, but a check on the field does the job for now.

I think the pre-processor will be useful if we want the same logic on the row grouping (where the field is not a constant but is generated from the grouping criteria since you can have several grouping columns).

But for now I agree that it's fine

File: packages/grid/x-data-grid/src/hooks/features/keyboardNavigation/useGridKeyboardNavigation.ts (hunk 4 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/features/keyboardNavigation/useGridKeyboardNavigation.ts:134]: For tree data it's not a problem, but the check for row grouping is complex (see https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid-pro/src/hooks/features/rowGrouping/useGridRowGrouping.tsx) and I wouldn't duplicate it right now

**Review by flaviendelangle — APPROVED** [review]
