### PR TITLE
[DataGrid] Rework overlays layout

### LINKED ISSUE #5725: [data grid] Virtual scroller covers NoRowsOverlay
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When a component is passed to `NoRowsOverlay` slot, it will be covered by a div `.MuiDataGrid-virtualScroller` that prevents any interaction with it

### Expected behavior 🤔

Users should be able to define `NoRowsOverlay` that contains a call to action button that is clickable and not covered by virtual scroller

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/mui-x-norowsoverlay-bug-lwlcos?file=/src/App.tsx

### Context 🔦

Usually when no resources are found, it's a good UX practice to allow creating them in the same place where the message is located

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 12.4
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.4.0/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @emotion/react: 11.9.3 => 11.9.3
    @emotion/styled: 11.9.3 => 11.9.3
    @mui/base:  5.0.0-alpha.92
    @mui/icons-material: 5.8.4 => 5.8.4
    @mui/lab: 5.0.0-alpha.93 => 5.0.0-alpha.93
    @mui/material: 5.9.3 => 5.9.3
    @mui/private-theming:  5.9.3
    @mui/styled-engine:  5.8.7
    @mui/styles: 5.9.3 => 5.9.3
    @mui/system: 5.9.3 => 5.9.3
    @mui/types:  7.1.5
    @mui/utils:  5.9.3
    @mui/x-data-grid: 5.15.1 => 5.15.1
    @mui/x-date-pickers: 5.0.0-beta.4 => 5.0.0-beta.4
    @types/react: 18.0.14 => 18.0.14
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.7.4 => 4.7.4
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by cherniavskii**
Fixes #5725 (Demo: https://codesandbox.io/s/mui-x-norowsoverlay-bug-forked-fdlwd1?file=/src/App.tsx)
Keeps #3650 fixed

## The problem

Recently we had some traction around grid overlays solving the following issues:
1. Grid overlay is rendered behind the rows https://github.com/mui/mui-x/issues/3650
2. If grid overlay is rendered in front of virtual scroller, then users cannot scroll. We solved it with `pointerEvents: none` in https://github.com/mui/mui-x/pull/5558
3. Custom overlays with interactive elements ignore user events https://github.com/mui/mui-x/issues/5725. There’s a workaround https://github.com/mui/mui-x/issues/5725#issuecomment-1216503548 but the DX is not great and ideally custom overlays should handle user events out of the box.

It turned out there’s a vicious cycle - we can solve (1) and (2), but not (3).
Or we can fix (3) by removing `pointerEvents: none`, but it will cause (2) again.

So  as long as grid overlays are rendered outside of virtual scroller, it’s impossible to solve (1), (2) and (3) at the same time. 
Rendering grid overlays inside of virtual scroller allows to fix (1) while fixing (2) and (3) as well.

## The solution

Rendering overlays inside virtual scroller requires 2 wrapper `div`s:
1. Sticky wrapper to keep overlay in place while scrolling. This one should have 0x0px size to stay above the content instead of shifting it down 
2. Wrapper with actual width and height.

```jsx
<div className="MuiDataGrid-virtualScroller">
  <div // (1)
    style={{
      position: 'sticky', // To stay in place while scrolling
      top: 0,
      left: 0,
      width: 0, // To stay above the content instead of shifting it down
      height: 0, // To stay above the content instead of shifting it down
      zIndex: 4, // Should be above pinned columns, pinned rows and detail panel
    }}
  >
    <div style={{ width, height }}> // (2)
      {/* Actual overlays go here (e.g. GridLoadingOverlay) */}
    </div>
  </div>
</div>
```

## Breaking change

While layout changes a bit, it shouldn't cause breaking changes for the users, even for custom layouts. It's rather a bugfix.
I would be in favour of releasing it in v5.

We can hold it until v6 if there are any objections.

### CODE REVIEW

File: packages/grid/x-data-grid/src/components/base/GridOverlays.tsx [hunk 1]
```diff
@@ -29,24 +38,23 @@ function GridOverlayWrapper(props: React.PropsWithChildren<{}>) {
 
   let height: React.CSSProperties['height'] = viewportInnerSize?.height ?? 0;
   if (rootProps.autoHeight && height === 0) {
-    height = 'auto';
+    height = getMinimalContentHeight(apiRef); // Give room to show the overlay when there no rows.
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/base/GridOverlays.tsx:41]: The trick with `position: absolute; top: 0; bottom: 0; height: auto` to get full height won't work anymore, hence the change.

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 2]
```diff
@@ -504,27 +503,15 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
       minHeight: shouldExtendContent ? '100%' : 'auto',
     };
 
-    if (rootProps.autoHeight && currentPage.rows.length === 0) {
-      size.height = 2 * rowHeight; // Give room to show the overlay when there's no row.
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:508]: Seems like unnecessary duplication - same as few lines below

File: test/e2e/index.test.ts [hunk 3]
```diff
@@ -350,5 +350,16 @@ describe('e2e', () => {
         await page.evaluate(() => (document.activeElement as HTMLInputElement).value),
       ).to.equal('0-1');
     });
+
+    // https://github.com/mui/mui-x/issues/5590
+    it('should allow to click a button in NoRowsOverlay', async () => {
```
Comment (cherniavskii) [inline test/e2e/index.test.ts:355]: It's impossible to cover it with unit test, since firing click on a button will always work, even if the button is covered with another element and in real browser user won't be able to click on the button

File: packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx [hunk 4]
```diff
@@ -504,27 +503,15 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
...
-  ]);
+  }, [rootRef, columnsTotalWidth, rowsMeta.currentPageTotalHeight, needsHorizontalScrollbar]);
 
   React.useEffect(() => {
     apiRef.current.publishEvent('virtualScrollerContentSizeChange');
   }, [apiRef, contentSize]);
 
   if (rootProps.autoHeight && currentPage.rows.length === 0) {
-    contentSize.height = 2 * rowHeight; // Give room to show the overlay when there no rows.
+    contentSize.height = getMinimalContentHeight(apiRef); // Give room to show the overlay when there no rows.
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/virtualization/useGridVirtualScroller.tsx:514]: Extracted to a function to have it in a single place, since it's now used in `GridOverlays` as well

File: packages/grid/x-data-grid/src/hooks/features/rows/gridRowsUtils.ts [hunk 5]
```diff
@@ -144,3 +145,8 @@ export function calculatePinnedRowsHeight(apiRef: React.MutableRefObject<GridApi
     bottom: bottomPinnedRowsHeight,
   };
 }
+
+export function getMinimalContentHeight(apiRef: React.MutableRefObject<GridApiCommunity>) {
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/hooks/features/rows/gridRowsUtils.ts:149]: Wouldn't make more sense to have it in `useGridVirtualScroller`? Then `GridOverlays` could receive the height already calculated as prop.

File: packages/grid/x-data-grid/src/components/base/GridOverlays.tsx [hunk 6]
```diff
@@ -8,12 +9,20 @@ import {
...
 import { useGridApiContext } from '../../hooks/utils/useGridApiContext';
 import { useGridRootProps } from '../../hooks/utils/useGridRootProps';
-import { gridDensityTotalHeaderHeightSelector } from '../../hooks/features/density/densitySelector';
+import { getMinimalContentHeight } from '../../hooks/features/rows/gridRowsUtils';
+
+const GridOverlayWrapperRoot = styled('div')({
+  position: 'sticky', // To stay in place while scrolling
+  top: 0,
+  left: 0,
+  width: 0, // To stay above the content instead of shifting it down
```
Comment (DanailH) [inline packages/grid/x-data-grid/src/components/base/GridOverlays.tsx:18]: Should the width and height be `auto` or the size of the viewport? I'm asking because this has a `height = 0` but its child has `height > 0`?

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/base/GridOverlays.tsx:18]: This specific element should have size of 0x0px and this is intentional.
If it has non-zero size, it will shift pinned columns containers, which also use `position: sticky`.

File: packages/grid/x-data-grid/src/components/base/GridOverlays.tsx [hunk 7]
```diff
@@ -8,12 +9,20 @@ import {
 } from '../../hooks/features/rows/gridRowsSelector';
 import { useGridApiContext } from '../../hooks/utils/useGridApiContext';
 import { useGridRootProps } from '../../hooks/utils/useGridRootProps';
-import { gridDensityTotalHeaderHeightSelector } from '../../hooks/features/density/densitySelector';
+import { getMinimalContentHeight } from '../../hooks/features/rows/gridRowsUtils';
+
+const GridOverlayWrapperRoot = styled('div')({
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/components/base/GridOverlays.tsx:14]: The `name`, `slot` and `overridesResolver` are missing. Could you add them? Same for the inner div.

**Review by m4theushw — APPROVED** [review]
Well done! Finally we did the right thing.

File: packages/grid/x-data-grid/src/components/base/GridOverlays.tsx (hunk 7 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/base/GridOverlays.tsx]: @m4theushw Done, can you take a look?

Comment (m4theushw) [reply packages/grid/x-data-grid/src/components/base/GridOverlays.tsx]: How about `OverlayWrapper` and `OverlayWrapperInner` for the wrapper and the inner div, respectively? It's simpler.

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/base/GridOverlays.tsx]: Sounds good 👍

File: packages/grid/x-data-grid/src/components/base/GridOverlays.tsx [hunk 8]
```diff
@@ -29,24 +48,23 @@ function GridOverlayWrapper(props: React.PropsWithChildren<{}>) {
...
-        height,
-        width: viewportInnerSize?.width ?? 0,
-        position: 'absolute',
-        top: totalHeaderHeight,
-        bottom: height === 'auto' ? 0 : undefined,
-      }}
-      {...props}
-    />
+    <GridOverlayWrapperRoot>
+      <GridOverlayWrapperInner
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/components/base/GridOverlays.tsx:60]: You also need to set the class names.

image

**Review by m4theushw — APPROVED** [review]

**Comment by adammartiska** [comment]
Hello, is this solved somehow? I am trying to use more complex NoRowsOverlay component that will display button along with some text underneath. I am trying the workaround with styling noRowsOverlay through componentsProps but seems like it is nor working. Is there any workaround that is currently working for this? We are using mui version 5.6.1
