### PR TITLE
[pickers] Fix timezone `UTC` false positive

### LINKED ISSUE #10579: [pickers] Days go blank when selecting date outside DST
### Steps to reproduce

Link to live example: https://stackblitz.com/edit/react-blgysy?file=Demo.tsx

Steps:
1. Select 30th of October (end of Daylight Saving Time)
2. Observe days for October disappear and get `hiddenDaySpacingFiller` class name

https://github.com/mui/mui-x/assets/25098043/6c942ab3-2ee8-4dfc-8fcd-d7e3b0b30d28

### Current behavior

The days listed under October go blank and are getting `key="Mon Sep .."` instead of `key="Mon Oct"` and a class including `hiddenDaySpacingFiller`.

### Expected behavior

Days listed under October should not be given keys related to September but October, and should not include `hiddenDaySpacingFiller` class name. Days of October should be selectable.

### Context

Hello MUI X team! Many thanks for this awesome library. We are trying to allow users to select days outside DST in `Europe/London`. The issue seems to come from https://github.com/mui/mui-x//blob/master/packages/x-date-pickers/src/PickersDay/PickersDay.tsx#L112 and may be related to days rendering, because keys seem to be messed up when that happens.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 13.6
Chrome 117.0.5938.92
  
Not adding npm packages since it's reproductible on the provided live example
```
</details>

**Search keywords**: Pickers Moment Timezone blank days hiddenDaySpacingFiller

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #10579

The issue seems to be that `Europe/London` is `+01:00` in summer and `+00:00` during the winter. And for the latter, the `isUTC()` returns true which moves the internal timeZone from `Europe/London` to `UTC`

Here is a codesandbox to reproduce the bug: https://codesandbox.io/s/vibrant-zhukovsky-rcz9f4?file=/Demo.tsx (click on 30th or 31th of October)
Here is the same with a fix https://codesandbox.io/s/mystifying-lewin-v2tzj2?file=/Demo.tsx

The duplicate day for dayjs example is another issue #10584

### CODE REVIEW

**Review by LukasTy — APPROVED** [review]
Nice discovery and a quick fix! 👍 
WDYT about adding tests to cover this case? 🤔

File: test/utils/pickers/describeGregorianAdapter/testCalculations.ts [hunk 1]
```diff
@@ -169,6 +169,14 @@ export const testCalculations: DescribeGregorianAdapterTestSuite = ({
     setDefaultTimezone(undefined);
   });
 
+  it.only('should not mix Europe/London and UTC in winter', () => {
```
Comment (alexfauquette) [inline test/utils/pickers/describeGregorianAdapter/testCalculations.ts:172]:
```suggestion
  it('should not mix Europe/London and UTC in winter', () => {
```
