### PR TITLE
[charts] Remove component for axis event listener

### LINKED ISSUE #15857: [charts] onAxisClick is not working on IOS
```jsx
<LineChart
    xAxis={[
        {
            data: xAxisValues,
            scaleType: "point",
        },
    ]}
    bottomAxis={{
        tickLabelStyle: {
            angle: atrXDegreesOfRotation ?? 0,
            textAnchor: "middle",
        },
    }}
    grid={{ vertical: true, horizontal: true }}
    series={chartDataSet}
    margin={{}} 
    slotProps={{
        legend: {},
    }}
    onAxisClick={(event, d) => console.log("HIT4", event.target, d)}
/>
```

### Current behavior

It behaves well on web and android, however onAxisClick is not working on IOS. 

It does work when i use onMarkClick but i would like to click on the axis element instead of mark element. 
Also it does seem like the targetted area is very small for users to click. 

### Your environment

 System:
    OS: macOS 15.1.1
  Binaries:
    Node: 22.9.0 - ~/.nvm/versions/node/v22.9.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.9.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 131.0.6778.109
    Edge: Not Found
    Safari: 18.1.1
  npmPackages:
    @emotion/react: 11.11.4 => 11.11.4 
    @emotion/styled: 11.11.5 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  6.1.0 
    @mui/icons-material: 6.1.0 => 6.1.0 
    @mui/material: 6.1.0 => 6.1.0 
    @mui/private-theming:  6.1.0 
    @mui/styled-engine-sc:  6.1.0 
    @mui/system:  6.1.0 
    @mui/types:  7.2.16 
    @mui/utils:  6.1.0 
    @mui/x-charts: 7.23.0 => 7.23.0 
    @mui/x-charts-vendor:  7.20.0 
    @mui/x-data-grid:  7.23.0 
    @mui/x-data-grid-pro: 7.23.0 => 7.23.0 
    @mui/x-date-pickers:  7.7.1 
    @mui/x-date-pickers-pro: 7.23.0 => 7.23.0 
    @mui/x-internals:  7.23.0 
    @mui/x-license:  7.23.0 
    @mui/x-tree-view:  7.23.0 
    @mui/x-tree-view-pro: 7.23.0 => 7.23.0 
    @types/react: 18.3.3 => 18.3.3 
    react: 19.0.0-rc-4beb1fd8-20241118 => 19.0.0-rc-4beb1fd8-20241118 
    react-dom: 19.0.0-rc-4beb1fd8-20241118 => 19.0.0-rc-4beb1fd8-20241118 
    styled-components:  6.1.13 
    typescript: 5.6.2 => 5.6.2 

**Search keywords**: chart onAxisClick

### PR DESCRIPTION
**Pull request by alexfauquette**
I noticed we still had a `disableAxisListener` and `onAxisClick` in dedicated hooks. I moved them to the axis plugging such that:
- If you have cartesian axis => the axis listener are availabale
- If you don't have the cartesian puggin => the axis listener are not running :tada:

By doing that I got two side effect:

- fix #15857 got easier since everything is in the plugin now)
- I improved the typing such that pie chart don't get any props from the cartesian plugin might be useful for radar an funnel

### CODE REVIEW

File: packages/x-charts/src/ChartContainer/useChartContainerProps.ts [hunk 1]
```diff
@@ -5,15 +5,19 @@ import { ChartDataProviderProps } from '../ChartDataProvider';
...
   chartDataProviderProps: ChartDataProviderProps<TSeries, AllPluginSignatures<TSeries>>;
   chartsSurfaceProps: ChartsSurfaceProps & { ref: React.Ref<SVGSVGElement> };
   children: React.ReactNode;
 };
 
-export const useChartContainerProps = <TSeries extends ChartSeriesType = ChartSeriesType>(
-  props: ChartContainerProps<TSeries>,
+export const useChartContainerProps = <
+  TSeries extends ChartSeriesType = ChartSeriesType,
+  TSignatures extends readonly ChartAnyPluginSignature[] = AllPluginSignatures<TSeries>,
```
Comment (JCQuintas) [inline packages/x-charts/src/ChartContainer/useChartContainerProps.ts:18]: Do we need to be strict in these plugin types? Can't we simply have a type that accepts everything for these generic places and use a subset of the full type where it is needed? 🤔

File: docs/data/charts/bars/bars.md [hunk 2]
```diff
@@ -159,14 +159,10 @@ If you're using composition, you can get those click event as follows.
...
-import ChartsOnAxisClickHandler from '@mui/x-charts/ChartsOnAxisClickHandler';
-// ...
-
-<ChartContainer>
+<ChartContainer onAxisClick={onAxisClick}>
   {/* ... */}
-  <ChartsOnAxisClickHandler onAxisClick={onAxisClick} />
   <BarPlot onItemClick={onItemClick} />
-</ChartContainer>;
+</ChartContainer>
```
Comment (JCQuintas) [inline docs/data/charts/bars/bars.md:165]: Has this composition section become obsolete in both bar and line? I believe the idea was to show that to add interaction you need to use `<ChartsOnAxisClickHandler />` in your composition, but that is not the case anymore.

Also should we create a codemod for this `ChartsOnAxisClickHandler` removal? 🤔

File: packages/x-charts/src/ChartContainer/useChartContainerProps.ts (hunk 1 above)
Comment (alexfauquette) [reply packages/x-charts/src/ChartContainer/useChartContainerProps.ts:18]: I don't get your question. Which typing could be more flexible?

File: docs/data/charts/bars/bars.md (hunk 2 above)
Comment (alexfauquette) [reply docs/data/charts/bars/bars.md:165]: > Has this composition section become obsolete

I thaught first to remove it, but it's still relevant to show that the `onAxisClick` needs to be pass to the container and `onItemClick` to the plot element

**Review by JCQuintas — APPROVED** [review]

File: packages/x-charts/src/ChartContainer/useChartContainerProps.ts (hunk 1 above)
Comment (JCQuintas) [reply packages/x-charts/src/ChartContainer/useChartContainerProps.ts:18]: It seems that we need to define what plugins the `useChartContainerProps` function should use/return but it doesn't really care much about them, and we have to force some types with `as`. 

This probably means our types are either too flexible or not flexible enough, my comment was more of a thought provoking one, to see if you have other solution for this.
