### PR TITLE
[DataGrid] Fix autosizing with virtualized columns

### LINKED ISSUE #15048: Autoresize does not properly resize columns that are scrolled far off screen when the resize is requested
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/condescending-paper-lfpgkq?from-embed=&workspaceId=ff0972be-f965-4d9b-9731-28487014ad71

Steps:
1. Make sure your viewport is narrow enough that a large portion of the columns cannot be displayed and must be scrolled
2. Click the autosize columns button
3. Scroll the columns all the way to the right and observe that the last few columns have not been resized properly

### Current behavior

Columns that are far outside of the viewport at the time the resize is requested are not resized properly. The narrower your viewport, the more columns will be improperly resized. If your viewport happens to be wide enough, the resizing will work fine.

### Expected behavior

All columns should be resized correctly regardless of viewport

### Context

I am displaying a data grid with a large amount of columns. The rows are fetched from a server and then the columns are resized automatically once fetching is complete. I would like for the columns to properly resize themselves instead of hardcoding some minimum widths to the columns which I am currently doing to work around the issue.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 14.6.1
  Binaries:
    Node: Not Found
    npm: 10.9.0 - ~/projects/platform-web/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 129.0.6668.101
    Edge: Not Found
    Safari: 17.6
  npmPackages:
    @emotion/react: ^11.11.4 => 11.13.3 
    @emotion/styled: ^11.11.0 => 11.13.0 
    @mui/core-downloads-tracker:  6.1.3 
    @mui/icons-material: ^6.0.0 => 6.1.3 
    @mui/material: ^6.0.0 => 6.1.3 
    @mui/private-theming:  6.1.3 
    @mui/styled-engine:  6.1.3 
    @mui/system: ^6.0.0 => 6.1.3 
    @mui/types:  7.2.18 
    @mui/utils:  6.1.3 
    @mui/x-data-grid: ^7.3.0 => 7.20.0 
    @mui/x-data-grid-pro: ^7.4.0 => 7.20.0 
    @mui/x-date-pickers: ^7.1.1 => 7.20.0 
    @mui/x-date-pickers-pro: ^7.3.1 => 7.20.0 
    @mui/x-internals:  7.20.0 
    @mui/x-license: ^7.2.0 => 7.20.0 
    @types/react: ^18.3.1 => 18.3.11 
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1 
    typescript: ^5.5.0 => 5.6.3 
```
</details>

This was tested on Firefox and Chrome.

**Search keywords**: datagrid autoresize resize

### Order ID or Support Key
89478
(sorry for the edit, the person with the receipt wasn't available to give it to me until just now)

### PR DESCRIPTION
**Pull request by k-rajat19**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Closes #15048

When  `autosizeColumns` called then there is  a need to [disable virtualization](https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx#L720) to ensure that all columns are available for resizing, In [column headers](https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx#L166) this change takes effect but in case of row cells this doesn't, it means by disabling virtualization all columns get available but not all row cells.
This fix will ensure that all columns and all row cells are available when virtualization is disabled so that necessary calculations can be performed while resizing.

Before: https://codesandbox.io/p/sandbox/condescending-paper-lfpgkq
After: https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-g65n4r

### CODE REVIEW

**Review by KenanYusuf — COMMENTED** [review]
@k-rajat19 looks like it partially solves it, but I noticed if you scroll a bit to the right and then autosize, the columns on the left are incorrect

https://github.com/user-attachments/assets/0c3832e5-c00d-4726-814b-3c23c9f1a07e

**Comment by k-rajat19** [comment]
the problem seems to come from the first Index is not updated when virtualization is disabled, should we add a condition for that too ? or should we consider updating render context values when virtualization is disabled?

**Comment by k-rajat19** [comment]
@romgrk would you like to help us here 🙂 ?

**Review by cherniavskii — CHANGES_REQUESTED** [review]
Hi @k-rajat19 
Thanks for opening this PR!
I want to clarify that the current behavior is intentional: https://mui.com/x/react-data-grid/column-dimensions/#autosizing



I believe this should stay a default behavior, because otherwise, the tab might get out of memory and the app would crash (depending on the number of rows).

I think we can make this functionality opt-in, behind a flag in `autosizeOptions`.
What do you think?

**Comment by k-rajat19** [comment]
> I think we can make this functionality opt-in, behind a flag in `autosizeOptions`. What do you think?

makes sense to me,  I've made the changes.

File: packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx [hunk 1]
```diff
@@ -719,8 +720,10 @@ export const useGridColumnResize = (
       const columns = options.columns.map((c) => apiRef.current.state.columns.lookup[c]);
 
       try {
-        apiRef.current.unstable_setColumnVirtualization(false);
-        await columnVirtualizationDisabled();
+        if (!props.disableVirtualization && options.resizeAll) {
+          apiRef.current.unstable_setColumnVirtualization(false);
+          await columnVirtualizationDisabled();
+        }
```
Comment (cherniavskii) [inline packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx:726]: I'm not sure I follow, I thought this PR intended to disable *row* virtualization during auto resize 🤔
As you can see in the code, column virtualization is already disabled.

Comment (k-rajat19) [reply packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx:726]: so should I remove the column virtualization disabling logic along with this new option, because in default behavior it looks like we don't really need to disable column virtualization or we?

Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx:726]: I'm sorry, it's my bad. I thought this issue was about row virtualization not being disabled during autosizing, and [my comment above](https://github.com/mui/mui-x/pull/15116#pullrequestreview-2502334179) was referring to row virtualization as well.

Regarding column virtualization, as you pointed out, it works for column headers but doesn't work for actual cells. Your approach makes sense to me. Sorry about the confusion!

Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx:726]: However, we might need to add the `disableColumnVirtualization` option (defaulting to `true`).
The reason for this is that it's not always necessary.
For example, autosizing a single column on double-click – the horizontal scroll gets reset even though we don't need to disable column virtualization in this case: https://stackblitz.com/edit/react-4oxpjcvz?file=index.tsx

Comment (k-rajat19) [reply packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx:727]: thanks for the clarification, I have added `disableColumnVirtualization`

File: packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx [hunk 2]
```diff
@@ -687,6 +688,7 @@ export const useGridColumnResize = (
 
       apiRef.current.autosizeColumns({
         ...props.autosizeOptions,
+        disableColumnVirtualization: false,
```
Comment (k-rajat19) [inline packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx:691]: keeping it `false` here to avoid scroll reset.

Comment (cherniavskii) [reply packages/x-data-grid/src/hooks/features/columnResize/useGridColumnResize.tsx:691]: Exactly 👍🏻

**Review by cherniavskii — APPROVED** [review]
Thank you!

**Comment by lauri865** [comment]
I'm a bit confused about this PR:

Why is the first check necessary? It renders all the columns only if row-level virtualization has not been disabled, but column-level has been? This effectively prevents this from being unit-tested. If you remove the first check, you'll notice at least one test failing:
https://github.com/k-rajat19/mui-x/blob/292c3fd5df520e39d234bf1072fec9149c675c0d/packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx#L167

And the core thing I don't understand is the assumption here:
https://github.com/k-rajat19/mui-x/blob/292c3fd5df520e39d234bf1072fec9149c675c0d/packages/x-data-grid/src/hooks/features/columnHeaders/useGridColumnHeaders.tsx#L168

`firstColumIndex` doesn't always start from 0, and doesn't always end with `visibleColumns.length`. What if there are pinned columns? Now we would be rendering the pinned columns twice – both as pinned as well as in the non-pinned columns.

cc @cherniavskii, correct me if I'm wrong here 🤔 (I stumbled upon it rebasing an unrelated PR)

PS: I also think this should probably be handled within `useGridVirtualScroller` rather than within individual rows.

**Comment by lauri865** [comment]
And a reproduction:
https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-g65n4r

**Comment by lauri865** [comment]
I pushed a tentative fix (tests are passing now). But the question is if this side-stepping of `renderContext` is really necessary in multiple places? Wouldn't it be cleaner to just update the `renderContext` when virtualization is toggled and keep the logic centralized to `useGridVirtualScroller`?
