### PR TITLE
[DataGrid] Fix row reordering when filter hides rows

### LINKED ISSUE #22057: [data grid] Reordering rows on filtered rows
### Steps to reproduce

Steps:
1. Load a page with DataGrid
2. Filter a column such that some of the rows will disappear
3. Attempt to re-order the rows

Examples: https://mui.com/x/react-data-grid/row-ordering/
https://github.com/user-attachments/assets/22152c32-0a5e-45aa-9bbb-790f192b46b6
https://github.com/user-attachments/assets/0e3c5f50-b87f-4e30-8262-f3c5527ed9b8

### Current behavior

When re-ordering the rows with columns having a filter applied, the row re-ordering doesn't work as expected.

### Expected behavior

The row that is dropped to a specific location should move there.

### Context

I am trying to re-order the data grid that has filters on it. I am implementing a system that requires reordering of "active" and "inactive" rows within a filtered grid. The ordering of these rows matter with the rows higher up being higher priority. Usually, we want to only look at active rows, but we can also set inactive rows to active through the same data grid by having an action column for updating the status.

### Your environment

_No response_

**Search keywords**: Reorder, data-grid, filtering

**Order ID**: 112825

### PR DESCRIPTION
**Pull request by siriwatknp**
closes #22057

- **Sandbox:** [Try it on StackBlitz](https://stackblitz.com/edit/yupc5tfz?file=package.json)

## Summary

When a filter hides some rows in the Data Grid, row reordering drops the dragged row at the wrong position — often between hidden rows instead of next to the chosen target.

This PR fixes flat-data row reordering so that:

1. A drop lands next to the visible target row in the underlying row list.
2. Rows hidden by the current filter keep their relative position around the target.
3. A drop that would not change the visible order is a no-op (it does not silently reshuffle hidden rows).

Example (backing order `[A, X, B]`, filter hides `X`, visible `[A, B]`):

- Dragging `A` above `B` — already true in the visible view → no-op, backing stays `[A, X, B]`.
- Dragging `B` below `A` → visible stays `[A, B]` → no-op.
- Dragging `B` above `A` → backing becomes `[B, A, X]`, visible `[B, A]`.

## For reviewers

Root cause: [`setRowPosition`](https://github.com/mui/mui-x/pull/22096/files#diff-9b80abe2bfb795545847748e43ee6443f1d54ee5242a319d6d0b3b14327ac8ba) was mixing two index spaces. `targetRowIndexUnadjusted` and `sourceRowIndex` came from `gridExpandedSortedRowIndexLookupSelector` (indices into the **filtered** sorted view), but the splice was applied to `group.children` in the row tree (which contains **all** rows, including filtered-out ones). With any active filter the two spaces diverge and the row lands at an arbitrary position.

Fix design:

1. **Filtered-view no-op guard**, applied before mutating the tree. Mirrors the `isAdjacentNode` check in the reorder validator: if the source is already directly above/below the target (or equal) in the filtered view, return early. This matters because the public `setRowPosition` API can be called with filter-view no-ops, and a naive anchor-based splice would rewrite the backing order without any visible change — silently moving hidden rows across the source.
2. **Anchor by target row id, in full-children space**, for real moves. Remove the source id from `group.children`, find the target id in the result, and insert above/below the anchor. This keeps filtered-out rows that sit next to the anchor in place, and removes the need for the previous drag-direction arithmetic (which only existed to patch up the filtered/full index mismatch).

Tradeoff: for real moves that cross hidden rows, the hidden rows end up adjacent to the target anchor rather than preserving their absolute original slot. This is inherent to the "drop next to target" semantics and matches user expectation for flat data reordering.

Scope: this PR fixes the flat-data path only. The tree-data executor (`treeDataReorderExecutor`) already operates in per-parent `children` space via `calculateTargetIndex`, so the same failure mode does not apply identically; any tree-data filter+reorder quirks are out of scope here.

Tests added to [`rowReorder.DataGridPro.test.tsx`](https://github.com/mui/mui-x/pull/22096/files#diff-2481d137145a673eecd28152fc9e5f7c59ed49cd119709131996f055e46bdc60):

- Drag-below regression for the issue's reproduction (filter active, hidden rows between source and target).
- `apiRef.setRowPosition` no-op regression asserting that `gridDataRowIdsSelector` is unchanged when the requested drop is a visible no-op across a hidden row.

---

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/rows/useGridRowsOverridableMethods.ts
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/rows/useGridRowsOverridableMethods.ts:1]: Optional improvement to reduce `4 * O(n)` to `O(n)`:

```diff
diff --git a/packages/x-data-grid/src/hooks/features/rows/useGridRowsOverridableMethods.ts b/packages/x-data-grid/src/hooks/features/rows/useGridRowsOverridableMethods.ts
index c975ca941c..9a037344ef 100644
--- a/packages/x-data-grid/src/hooks/features/rows/useGridRowsOverridableMethods.ts
+++ b/packages/x-data-grid/src/hooks/features/rows/useGridRowsOverridableMethods.ts
@@ -60,17 +60,34 @@ export const useGridRowsOverridableMethods = (apiRef: RefObject<GridPrivateApiCo
         const group = gridRowTreeSelector(apiRef)[GRID_ROOT_GROUP_ID] as GridGroupNode;
         const allRows = group.children;
 
-        if (allRows.indexOf(sourceRowId) === -1 || allRows.indexOf(targetRowId) === -1) {
-          return state;
+        // Single pass: skip source and inline-insert it adjacent to the target
+        // anchor id so filtered-out rows between source and target keep their
+        // position next to the anchor.
+        const updatedRows: GridRowId[] = [];
+        let sourceFound = false;
+        let targetFound = false;
+
+        for (let i = 0; i < allRows.length; i += 1) {
+          const id = allRows[i];
+          if (id === sourceRowId) {
+            sourceFound = true;
+            continue;
+          }
+          if (id === targetRowId) {
+            targetFound = true;
+            if (position === 'above') {
+              updatedRows.push(sourceRowId, id);
+            } else {
+              updatedRows.push(id, sourceRowId);
+            }
+            continue;
+          }
+          updatedRows.push(id);
         }
 
-        // Remove source, then insert next to target anchor id so filtered-out
-        // rows between source and target keep their relative position.
-        const updatedRows = allRows.filter((id) => id !== sourceRowId);
-        const anchorIndex = updatedRows.indexOf(targetRowId);
-        const insertAt = position === 'above' ? anchorIndex : anchorIndex + 1;
-
-        updatedRows.splice(insertAt, 0, sourceRowId);
+        if (!sourceFound || !targetFound) {
+          return state;
+        }
 
         return {
           ...state,
```

**Review by MBilalShafi — APPROVED** [review]

File: packages/x-data-grid/src/hooks/features/rows/useGridRowsOverridableMethods.ts
Comment (siriwatknp) [reply packages/x-data-grid/src/hooks/features/rows/useGridRowsOverridableMethods.ts:1]: Applied. Verified semantic equivalence (source/target ordering, source===target, missing ids — the latter two are already caught by the filtered-view no-op and existence checks upstream, so the branch is defensive). Browser tests green (34/34 in `x-data-grid-pro`), typecheck + lint clean.
