### PR TITLE
[pickers] Add verification to disable skipped hours in spring forward DST

### LINKED ISSUE #12403: [pickers][DateTimePicker] not showing 2 in the hour category, but shows 3 twice and the first isn't selectable
### Steps to reproduce

Link to live example: (required)

https://mui.com/x/react-date-pickers/date-time-picker/

Steps:
1. any date time picker, even the demos on the mui site are broke 
2.
3.

### Current behavior

The hour category shows 12-1-3-3-4-5

### Expected behavior

The hour category shows 12-1-2-3-4-5

### Context

Select time from date time picker
image

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: DateTimePicker hour
**Order ID**: 39752

### PR DESCRIPTION
**Pull request by flaviendelangle**
Continuation of #15115
Closes #12403

I can't reproduce the bug in the tests :cry: 
Probably because the timezone is not the same...

I also noticed that in `TimeClock`, the `PageUp` / `PageDown` navigation could move outside of the displayed values, unlike the `MultiSectionDigitalClock`.
For example when using meridiem, pressing `PageUp` on the hour 8 PM would move you to the hour 1 AM, whereas on the `MultiSectionDigitalClock` it would move you to the hour 11 PM.
This was causing a test to fail with the new DST check since we start checking if the expected hour was correct (and it was not).

### CODE REVIEW

File: packages/x-date-pickers/src/TimeClock/Clock.tsx [hunk 1]
```diff
@@ -316,6 +321,10 @@ export function Clock(inProps: ClockProps) {
     }
   }, [autoFocus]);
 
+  const clampValue = (newValue: number) => Math.max(minViewValue, Math.min(maxViewValue, newValue));
```
Comment (flaviendelangle) [inline packages/x-date-pickers/src/TimeClock/Clock.tsx:324]: For the `PageUp` and `PageDown` we clamp the value (the min and max act as a boundary)
For the `ArrowUp` and `ArrowDown` we circle the value (when reaching the min, we go back to the max value and vice-versa)

File: packages/x-date-pickers/src/TimeClock/Clock.tsx [hunk 2]
```diff
@@ -42,6 +42,10 @@ export interface ClockProps extends ReturnType<typeof useMeridiemMode>, FormProp
    * The current full date value.
    */
   value: PickerValidDate | null;
+  /**
+   * Minimal and maximal value of the clock.
```
Comment (michelengelen) [inline packages/x-date-pickers/src/TimeClock/Clock.tsx:46]:
```suggestion
   * Minimum and maximum value of the clock.
```

According to the dictionary "minimal" is used for uncountable values.

**Review by michelengelen — APPROVED** [review]

File: packages/x-date-pickers/src/TimeClock/Clock.tsx [hunk 3]
```diff
@@ -325,27 +334,27 @@ export function Clock(inProps: ClockProps) {
...
         event.preventDefault();
         break;
       case 'End':
-        handleValueChange(type === 'minutes' ? 59 : 23, 'partial');
+        handleValueChange(maxViewValue, 'partial');
         event.preventDefault();
         break;
       case 'ArrowUp':
-        handleValueChange(viewValue + keyboardControlStep, 'partial');
+        handleValueChange(circleValue(viewValue + keyboardControlStep), 'partial');
```
Comment (LukasTy) [inline packages/x-date-pickers/src/TimeClock/Clock.tsx:345]: Nitpick: It's slightly annoying that this component does not jump over disabled values with arrow navigation. 🙈 
However, we recommend it for mobile use, so, I'm not sure if it's even worth treating as a problem. 🤷
