### PR TITLE
[DataGrid] Fix scrollbar position not being updated after `scrollToIndexes`

### LINKED ISSUE #14830: [data grid] Horizontal scrollbar position is not updated after scrollToIndexes
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/eager-satoshi-zvqygs

Setup:
1. DataGrid with with horizontal scrollbar & apiRef
3. Button, onClick call `apiRef.current.scrollToIndexes({ colIndex: 1 })`

Steps:
1. Refresh the page
2. Scroll DataGrid to the rightmost position (or just sufficiently to the right) via mouse click and drag on the scrollbar
3. Press the scroll button
4. If horizontal scrollbar behaves as expected repeat steps 2-3 again, sometimes initial scroll behaves correctly

Using gestures to scroll right does not reproduce this issue, only mouse click & drag on the scrollbar does

### Current behavior

Horizontal scrollbar position is not updated, leaving it in outdated state. Moving the scrollbar after this result is snapping back to initial scroll position

### Expected behavior

Horizontal scrollbar position is adjusted after programmatic scroll

### Context

Application requires programmatic scrolling to specific columns (in a wide table). This is achievable with current API, but horizontal scroll behavior is bad UX.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Linux 5.15 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: 9.9.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.13.3 => 11.13.3 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/icons-material: ^6.1.2 => 6.1.2 
    @mui/material: ^6.1.2 => 6.1.2 
    @mui/x-data-grid: ^7.18.0 => 7.18.0 
    @mui/x-date-pickers: ^7.18.0 => 7.18.0 
    @types/react: ^18.3.11 => 18.3.11 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    typescript: ^5.6.2 => 5.6.2
```
</details>

User agent: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0`

**Search keywords**: scrollbar position scrollToIndexes datagrid

### PR DESCRIPTION
**Pull request by arminmeh**
Reverts https://github.com/mui/mui-x/pull/14877, because of a [regression](https://github.com/mui/mui-x/pull/14877#discussion_r1792444616)

Fixes #14830 

Instead of changing the event listeners, new approach is to directly update scroll positions of the scrollbars together with the position of the scroller via refs

### CODE REVIEW

**Comment by JCQuintas** [comment]
Not sure you fixed it already, but wrapping the events in `act` seem to work on my side, I had encountered something similar [here](https://github.com/mui/mui-x/pull/14508/files#diff-fcd2e92675046e653eca4a5b71dad7a73ce15e91b841ebff27115043b5f2df6e) 🙃 

```
    const virtualScroller = container.querySelector('.MuiDataGrid-virtualScroller')!;

    await act(async () => {
      // arbitrary number to make sure that the bottom of the grid window is reached.
      virtualScroller.scrollTop = 12345;
      virtualScroller.dispatchEvent(new Event('scroll'));
    });

    await waitFor(() => {
      expect(handleRowsScrollEnd.callCount).to.equal(1);
    });
    await act(async () => {
      setProps({
        rows: baseRows.concat(
          { id: 6, brand: 'Gucci' },
          { id: 7, brand: "Levi's" },
          { id: 8, brand: 'Ray-Ban' },
        ),
      });
      // Trigger a scroll again to notify the grid that we're not in the bottom area anymore
      virtualScroller.dispatchEvent(new Event('scroll'));
    });

    expect(handleRowsScrollEnd.callCount).to.equal(1);

    await act(async () => {
      virtualScroller.scrollTop = 12345;
      virtualScroller.dispatchEvent(new Event('scroll'));
    });

    await waitFor(() => {
      expect(handleRowsScrollEnd.callCount).to.equal(2);
    });
```

**Review by cherniavskii — APPROVED** [review]

File: packages/x-data-grid/src/models/api/gridCoreApi.ts [hunk 1]
```diff
@@ -69,9 +69,17 @@ export interface GridCorePrivateApi<
...
    */
   virtualScrollerRef: React.RefObject<HTMLDivElement>;
+  /**
+   * The React ref of the grid's vertical virtual scrollbar container element.
+   */
+  virtualScrollbarVerticalRef: React.RefObject<HTMLDivElement>;
+  /**
+   * The React ref of the grid's horizontal virtual scrollbar container element.
+   */
+  virtualScrollbarHorizontalRef: React.RefObject<HTMLDivElement>;
```
Comment (romgrk) [inline packages/x-data-grid/src/models/api/gridCoreApi.ts:82]: Do these need to be public? I'd rather avoid exposing stuff until it needs to be exposed, once it's public it can't be refactored/removed.

Comment (romgrk) [reply packages/x-data-grid/src/models/api/gridCoreApi.ts:82]: I also wanted to refactor the names to remove the "virtual" prefix from everywhere, it would make for more readable names and shorter lines. It could be interesting to name those just `scrollbarXxxxRef`.

Comment (cherniavskii) [reply packages/x-data-grid/src/models/api/gridCoreApi.ts:82]: They're defined in the `GridCorePrivateApi` interface, so not public 👍🏻

Comment (arminmeh) [reply packages/x-data-grid/src/models/api/gridCoreApi.ts:82]: The only public thing around this are few classes
https://mui.com/x/api/data-grid/data-grid/#data-grid-classes-MuiDataGrid-virtualScroller

we can make the change in v8 if you want to have a cleanup
