### PR TITLE
[tree view] Introduce a Tree View Store to clean the internals

### LINKED ISSUE #14228: apiRef type is Partial<{}> which causes Typescript compilation to fail
### Search keywords

useTreeViewApiRef, apiRef, getItem

### Latest version

- [X] I have tested the latest version

### Affected products

Tree View

### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/infallible-nightingale-8h29cd?file=%2Fsrc%2FDemo.tsx%3A35%2C3

Steps:
1. In Demo.tsx line 50, apiRef has type React.MutableRefObject<Partial<{}> | undefined> 

### Current behavior

Typescript compilation fails with errors: "Property 'getItem' does not exist on type 'Partial<{}>'.", "Property 'getItemDOMElement' does not exist on type 'Partial<{}>'.". This is the sample use case of getItem in code: "const item = apiRef.current!.getItem(itemId);". This happens also when apiRef.current is explicitly checked for being defined (e.g. const item = apiRef.current ? apiRef.current!.getItem(itemId) : null;).

### Expected behavior

apiRef is properly typed, and there are no errors during compilation.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
  npmPackages:
    @emotion/react: ^11.13.0 => 11.13.0 
    @emotion/styled: ^11.13.0 => 11.13.0 
    @mui/base:  5.0.0-alpha.122 
    @mui/core-downloads-tracker:  5.16.7 
    @mui/icons-material: ^5.11.11 => 5.11.16 
    @mui/material: ^5.16.7 => 5.16.7 
    @mui/private-theming:  5.16.6 
    @mui/styled-engine:  5.16.6 
    @mui/system:  5.16.7 
    @mui/types:  7.2.15 
    @mui/utils: ^5.15.7 => 5.16.6 
    @mui/x-data-grid: latest => 6.9.0 
    @mui/x-date-pickers: ^6.3.0 => 6.3.0 
    @mui/x-internals:  7.12.0 
    @mui/x-tree-view: ^7.12.1 => 7.12.1 
    @types/react: ^18.0.28 => 18.0.28 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    typescript: ^4.9.5 => 4.9.5 
```
</details>

<details>
  <summary><code>tsconfig</code></summary>

```
{
  "compilerOptions": {
    "strict": true,
    "allowUnreachableCode": false,
    "exactOptionalPropertyTypes": false,
    "noImplicitReturns": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "noPropertyAccessFromIndexSignature": true,
    "skipLibCheck": true,

    "allowJs": true,
    "baseUrl": "src",
    "paths": {
      "@/*": ["./*"]
    },
    "jsx": "preserve",
    "lib": ["DOM", "DOM.Iterable", "ESNext", "WebWorker"],
    "module": "ESNext",
    "moduleResolution": "Node",
    "noEmit": true,
    "preserveConstEnums": true,
    "resolveJsonModule": true,
    "target": "ESNext",
    "sourceMap": true,

    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "isolatedModules": true,

    "forceConsistentCasingInFileNames": true,
    "useDefineForClassFields": true,
    "incremental": true,

    "types": ["node", "jest", "@testing-library/jest-dom"],
    "plugins": [{ "name": "typescript-plugin-css-modules" }]
  },
  "include": ["**/*.ts", "**/*.tsx", "next.config.js", "next-env.d.ts", "global.d.ts"],
  "exclude": ["node_modules"]
}

```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### LINKED ISSUE #19426: [tree view] The `apiRef` methods do not respect the type of the `items` prop
### Related page

https://mui.com/x/api/tree-view/simple-tree-view/#simple-tree-view-prop-apiRef

### Kind of issue

Missing information

### Issue description

I am trying to use `useTreeViewApiRef` to get back the `treeItems`.

```tsx
export interface ExplorerNode {
  id: string;
  text: string;
  children?: ExplorerNode[];
  count?: number;
  hasFolders: boolean;
}

const Component = ({ 
  items, 
  onItemsChange 
}: { 
  items: ExplorerNode[]; 
  onItemsChange: (newItems: ExplorerNode[]) => void
}) => {
  const treeApiRef = useTreeViewApiRef();

  return (
    <RichTreeViewPro
      apiRef={treeApiRef}
      items={items}
      onExpandedItemsChange={(_, expandedItems) => {
        const newItems = treeApiRef.current?.getItemTree() || [];
        //    ^ newItems is of type TreeViewBaseItem[]
        onItemsChange(newItems) 
        //            ^ TS Error:
        //              Argument of type 'TreeViewBaseItem[]' 
        //              is not assignable to parameter of type 'ExplorerNode[]'.
      }}
      dataSource={
        {
          // lazy load code
        }
      }
    />
  );
};
```

With the code as is `treeApiRef.current?.getItemTree()` returns `TreeViewBaseItem[]`.

I see that `useTreeViewApiRef` is a generic type. But I fail to see what I need to pass this generic, so that the the items returned from `getItemTree()` are of type `ExplorerNode[]`.

Is this possible? If so, could we add a dedicated page for `useTreeViewApiRef` that documents the generic? I really have a hard time parsing the actual type of it:

```ts
export type TreeViewAnyPluginSignature = {
  state: any;
  instance: any;
  params: any;
  paramsWithDefaults: any;
  dependencies: any;
  optionalDependencies: any;
  events: any;
  publicAPI: any;
};

export declare const useTreeViewApiRef: <
  TSignatures extends readonly TreeViewAnyPluginSignature[] = RichTreeViewPluginSignatures
>() => React.RefObject<TreeViewPublicAPI<TSignatures> | undefined>;
```

### Context

_No response_

**Search keywords**: useTreeViewApiRef typescrip generic

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #14228
Closes #19426

## Extracted PRs

- #20225
- #20233
- #20235
- #20240

## In this PR:

- The `store` object is created once on mount with all its method. There is no code run on every render to update its methods.
- The `contextValue.wrapRoot` property have been replaced by manual JSX in the various Tree View components.
- The parameters to pass to the store instead of the DOM are now hardcoded on a `useMemo` instead of being listed by each plugin.

## Differences with the Scheduler stores

- The product methods are stored in plugin instead of being defined by the store
 
  On the Scheduler, we call  methods like `store.setVisibleResources`. For the Tree View, the equivalent would be `store.resources.setVisibleResources`.
  This is because the main store create several sub-classes for each main feature (focus, keyboard navigation, expansion, ...) that expose there own methods. This make the codebase a lot more scalable.

### CODE REVIEW

File: packages/x-tree-view-pro/src/RichTreeViewPro/RichTreeViewPro.tsx [hunk 1]
```diff
@@ -125,7 +133,7 @@ RichTreeViewPro.propTypes = {
   // | To update them edit the TypeScript types and run "pnpm proptypes"  |
   // ----------------------------------------------------------------------
   /**
-   * The ref object that allows Tree View manipulation. Can be instantiated with `useRichTreeViewProApiRef()`.
+   * The ref object that allows Tree View manipulation. Can be instantiated with `useRichTreeViewApiProRef()`.
```
Comment (noraleonte) [inline packages/x-tree-view-pro/src/RichTreeViewPro/RichTreeViewPro.tsx:136]: Is this right? Isn't it `RichTreeViewProApiRef` instead of `...ApiProRef`?

File: packages/x-tree-view-pro/src/internals/plugins/itemsReordering/itemPlugin.ts [hunk 2]
```diff
@@ -86,11 +79,11 @@ export const useTreeViewItemsReorderingItemPlugin: TreeViewItemPlugin = ({ props
 
           // Check if the drag-and-drop was cancelled, possibly by pressing Escape
           if (event.dataTransfer.dropEffect === 'none') {
-            instance.cancelDraggingItem();
+            store.itemsReordering.cancelDraggingItem();
             return;
           }
 
-          instance.completeDraggingItem(itemId);
+          store.itemsReordering.completeDraggingItem(itemId);
```
Comment (noraleonte) [inline packages/x-tree-view-pro/src/internals/plugins/itemsReordering/itemPlugin.ts:86]: I like this DX - it's more explicit 👌

File: packages/x-tree-view/src/internals/plugins/items/TreeViewItemsPlugin.ts [hunk 3]
```diff
@@ -0,0 +1,266 @@
...
+  // We can't type `store`, otherwise we get the following TS error:
+  // 'items' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
+  constructor(store: any) {
+    this.store = store;
+  }
+
+  /**
+   * Determines if the items state should be rebuilt based on the new and previous parameters.
+   */
+  public static shouldRebuildItemsState = <R2 extends TreeViewValidItem<R2>>(
```
Comment (noraleonte) [inline packages/x-tree-view/src/internals/plugins/items/TreeViewItemsPlugin.ts:23]: `R2-D2` 🙊 - nothing against the naming, it's just what the `R2` generic reminded me of
image

**Review by noraleonte — APPROVED** [review]
Thank you for the work on this massive refactor 🙏 💙 Happy to see things getting more consistent across components 🎉

File: packages/x-tree-view-pro/src/RichTreeViewPro/RichTreeViewPro.tsx (hunk 1 above)
Comment (flaviendelangle) [reply packages/x-tree-view-pro/src/RichTreeViewPro/RichTreeViewPro.tsx:136]: Sorry can you elaborate here, I'm not following :eyes:

Comment (noraleonte) [reply packages/x-tree-view-pro/src/RichTreeViewPro/RichTreeViewPro.tsx:136]: there is a change to rename `useRichTreeViewProApiRef` to `useRichTreeViewApiProRef` - is it intentional?

There is no `useRichTreeViewApiProRef` on a search in the codebase 🤔 And the naming also feels wrong `Pro` should come before `ApiRef`, it shouldn't be `...ApiProRef`, right? I might be missing something... 🤔

Comment (flaviendelangle) [reply packages/x-tree-view-pro/src/RichTreeViewPro/RichTreeViewPro.tsx:136]: Nop, I fixed it in the extracted PR and failed during the merge :angel:

Comment (flaviendelangle) [reply packages/x-tree-view-pro/src/RichTreeViewPro/RichTreeViewPro.tsx:136]:
```suggestion
   * The ref object that allows Tree View manipulation. Can be instantiated with `useRichTreeViewProApiRef()`.
```
