### PR TITLE
[charts] Limit the trigger of exit charts

### LINKED ISSUE #13659: Tooltips for points on the edge of the chart are not always shown with tooltip trigger item
### Search keywords

I'm sorry, it's hard for me to articulate the problem

### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: [codesandbox.io](https://codesandbox.io/p/sandbox/cocky-volhard-76fpmf?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxcs663f0007356ljoedgr3s%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxcs663f0003356lnuze8crn%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxcs663f0004356l42xep5l7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxcs663f0006356l9h5s957u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxcs663f0003356lnuze8crn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxcs663f0002356lixrbihqd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxcs663f0003356lnuze8crn%2522%252C%2522activeTabId%2522%253A%2522clxcs663f0002356lixrbihqd%2522%257D%252C%2522clxcs663f0006356l9h5s957u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxcs663f0005356l6ta3a5yp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxcs663f0006356l9h5s957u%2522%252C%2522activeTabId%2522%253A%2522clxcs663f0005356l6ta3a5yp%2522%257D%252C%2522clxcs663f0004356l42xep5l7%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxcs663f0004356l42xep5l7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Steps:
1. Use LineChart
2. Set the series curve to "linear".
3. Set some numeric values for data
4. Let's try to move the cursor over the points that are on the borders of the chart (top, right, bottom, left).
5. Note that the tooltip does not always appear

### Current behavior

Points on the chart boundaries do not always have tooltips.

Animation

### Expected behavior

_No response_

### Context

_No response_

### Your environment

I'm use Google Chrome (126.0.6478.127)

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    System:
    OS: Windows 11 10.0.22631
  Binaries:
    Node: 21.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: Not Found
  Browsers:
    Chrome: Not Found
    Edge: Chromium (126.0.2592.81)
  npmPackages:
    @emotion/react: ^11.11.4 => 11.11.4
    @emotion/styled: ^11.11.5 => 11.11.5
    @mui/base:  5.0.0-beta.40
    @mui/core-downloads-tracker:  5.15.19
    @mui/icons-material: ^5.15.19 => 5.15.19
    @mui/material: ^5.15.19 => 5.15.19
    @mui/private-theming:  5.15.14
    @mui/styled-engine:  5.15.14
    @mui/system:  5.15.15
    @mui/types:  7.2.14
    @mui/utils:  5.15.14
    @mui/x-charts: ^7.6.1 => 7.6.1
    @mui/x-date-pickers: ^7.7.0 => 7.7.0
    @types/react: ^18.2.66 => 18.2.78
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ^5.2.2 => 5.4.5
```
</details>

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #13659

### CODE REVIEW

File: packages/x-charts/src/context/DrawingProvider.tsx [hunk 1]
```diff
@@ -86,11 +87,18 @@ export function DrawingProvider(props: DrawingProviderProps) {
...
 
   const isPointInside = React.useCallback<DrawingArea['isPointInside']>(
-    ({ x, y }) =>
-      x >= drawingArea.left &&
-      x <= drawingArea.left + drawingArea.width &&
-      y >= drawingArea.top &&
-      y <= drawingArea.top + drawingArea.height,
+    ({ x, y }, targetEvent) => {
+      // For element allowed to overflow, wrapping them in <g data-drawing-container /> make them fully part of the drawing area.
+      if (targetEvent && targetEvent.closest('[data-drawing-container]')) {
```
Comment (JCQuintas) [inline packages/x-charts/src/context/DrawingProvider.tsx:92]:
```suggestion
    ({ x, y }, targetElement) => {
      // For element allowed to overflow, wrapping them in <g data-drawing-container /> make them fully part of the drawing area.
      if (targetElement && targetElement.closest('[data-drawing-container]')) {
```

**Review by JCQuintas — APPROVED** [review]
Nice, just a small change for the param name
