### PR TITLE
[DataGrid] Replace eval with new Function

### LINKED ISSUE #11046: @mui/x-data-grid-premium "ReferenceError: atob is not defined"
### Steps to reproduce

Link to live example: (required)

We just bought MuiPremium and I was able to upgrade our Date-Pickers decently. However, I tried for 3 hours to make a live DataGridPremium example work with node 14.18.2, next 10.1.2, and the newest MUI packages - there are limitations within codesandbox that prevent the docker container for that node version from working. I can provide more elaborate code samples if needed, but I'm not going to waste any more time on a codesandbox when I found where the issue is in MUI's codebase.

### Current behavior

`next dev` throws "ReferenceError: atob is not defined" when loading a page with `DataGridPremium`

### Expected behavior

it should load a basic datagrid

### Context

I saw some other issues mentioning `atob` and `eval()` and pieced together that there are checks for `window.atob` in order to use `eval`. 

The version of Next (which we're stuck with for this project due to being locked on node 14.18) appears to be pre-rendering server side when in development mode in such a way that a package DataGridPremium relies on, [gridFilterUtils.ts](node_modules/@mui/x-data-grid/node/hooks/features/filter/gridFilterUtils.js), is unable to proceed. 

(it wouldn't be an issue for production for us, we serve MUI content as wholly statically generated, but watch mode for development is important)

Looks like it was fixed in some other utils but `gridFilterUtils.js` is missing -- a needle in a haystack that this big version-locked project came across. 

I'd love `next dev` to work without this temp workaround I'm using on [gridFilterUtils.ts#L27C76-L27C76](https://github.com/mui/mui-x/blob/4774eb7f55f403ffa1ebd3077b05f16d3bc50853/packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts#L27C76-L27C76)

```ts
const evalCode = undefined; // globalScope[atob('ZXZhbA==')];
```
...which definitely won't work editing the node_modules file for deployment!

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Chrome: Not Found
  npmPackages:
    @mui/base:  5.0.0-beta.24 
    @mui/icons-material: ^5.14.18 => 5.14.18 
    @mui/lab: ^5.0.0-alpha.153 => 5.0.0-alpha.153 
    @mui/material: ^5.14.18 => 5.14.18 
    @mui/private-theming:  5.14.18 
    @mui/styles: ^5.14.18 => 5.14.18 
    @mui/system:  5.14.18 
    @mui/x-data-grid:  6.18.1 
    @mui/x-data-grid-premium: ^6.18.1 => 6.18.1 
    @mui/x-data-grid-pro:  6.18.1 
    @mui/x-date-pickers:  6.18.1 
    @mui/x-date-pickers-pro: ^6.18.1 => 6.18.1 
    @types/react: ^16.9.49 => 16.14.5 
```
</details>

**Search keywords**: atob next nextjs node node14
**Order ID**: 78418

### PR DESCRIPTION
**Pull request by oliviertassinari**
I was curious if we could improve this logic:

- `getRowId` was removed in #10897, no need to provide it as an argument anymore.
- Avoid the need for `atob('ZXZhbA==')`, it feels like obfuscation and fix #11046
- ~eval and new Function are by default sloopy https://2ality.com/2014/01/eval.html, made it strict.~

### CODE REVIEW

File: packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts [hunk 1]
```diff
@@ -22,25 +22,21 @@ import {
   gridVisibleColumnFieldsSelector,
 } from '../columns';
 
-// Fixes https://github.com/mui/mui-x/issues/10056
-const globalScope = (typeof window === 'undefined' ? globalThis : window) as any;
-const evalCode = globalScope[atob('ZXZhbA==')] as <T>(source: string) => T;
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts:27]: We're not executing in sloppy mode, we're already executing in strict mode due to `eval` being stored in a variable with a different name.

File: packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts [hunk 2]
```diff
@@ -22,25 +22,21 @@ import {
...
-
-const getHasEval = () => {
+function getHasEval() {
   if (hasEval !== undefined) {
     return hasEval;
   }
 
   try {
-    hasEval = evalCode<boolean>('true');
+    hasEval = new Function('return true') as any;
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts:33]: This is assigning the function to `hasEval` instead of assigning a boolean value to it. Maybe something like this instead?

```js
new Function('');
hasEval = true;

// or

hasEval = new Function('return true')() as boolean;
```

File: packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts [hunk 3]
```diff
@@ -263,36 +259,37 @@ const buildAggregatedFilterItemsApplier = (
...
+  )
+  .join('\n')}
+};
+
+return result$$;`;
+
+  const filterItemCore = new Function(
+    'appliers',
+    'row',
+    'shouldApplyFilter',
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts:288]: I must say I don't like this version more because the parameters are listed at the `new Function()` call instead of at the top like they were before. The previous version feels a bit more readable.

As mentioned above, it's also already in strict mode because we don't call eval directly, so I don't see benefits to using `new Function`.

File: packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts (hunk 2 above)
Comment (oliviertassinari) [reply packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts]: True, I would be afraid with the first version that optimization tools remove `new Function('');` as side effect free.

File: packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts (hunk 1 above)
Comment (oliviertassinari) [reply packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts:27]: True

File: packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts (hunk 3 above)
Comment (oliviertassinari) [reply packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts]: Right, fair point. I have added a new commit to fix the readability regression.

File: packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts [hunk 4]
```diff
@@ -263,40 +259,36 @@ const buildAggregatedFilterItemsApplier = (
...
+
+return result$$;`.replaceAll('$$', String(filterItemsApplierId)),
   );
-  const filterItem: GridFilterItemApplierNotAggregated = (row, shouldApplyItem) => {
-    return filterItemCore(apiRef.current.getRowId, appliers, row, shouldApplyItem);
-  };
   filterItemsApplierId += 1;
 
-  return filterItem;
+  return (row, shouldApplyItem) => filterItemCore(appliers, row, shouldApplyItem);
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/features/filter/gridFilterUtils.ts:291]: Sometimes I like assigning functions to a variable because it gives a better debugging experience, the stack entry would read `filterItem - .../gridFilterUtils.js:294` instead of `(anonymous) - .../gridFilterUtils.js:291`. It's useful when stepping through code but also when collecting performance profiles. With this change I'm also not sure what the name of `filterItemCore` becomes.

It's fine to leave as it is, but just fyi.

**Review by romgrk — APPROVED** [review]

**Comment by oliviertassinari** [comment]
@romgrk thanks for the reviews.
