### PR TITLE
[DataGrid] Fix last column border inconsistency

### LINKED ISSUE #4200: [data-grid] Last column don't have a right border
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

image

The above image shows a datagrid in which the widths of the columns do not reach the end of the datagrid.
Although showColumnRightBorder is set, there is no right border applied to the final column.

### Expected behavior 🤔

If the combined widths of the columns are less than the datagrid's width, apply a right border to the column header and all cells.

### Steps to reproduce 🕹

Steps:

1. Forked the codesandbox: https://codesandbox.io/s/datagrid-v5-quick-start-forked-ofi0il?file=/src/App.tsx
2. Added "showCellRightBorder"
3. Added "showColumnRightBorder"

### Context 🔦

Helps to add styling options to the table

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #4200 

## Why headers and row behave differently

The inconsistency between header and rows comes from the computation of the last column, which should be modified as follow
```diff
-isLastColumn={columnIndex === columns.length - 1}
+isLastColumn={columnIndex === visibleColumns.length - 1}
```

It appears in the issue example because one of the columns was hidden

## Proposed solution

In #2444 the consistency has been added, and the chosen solution was to remove borders for the last column. I propose to do the opposite for two reasons:

- It seems that at that time if the last column was flex, it displayed a double border. One for the grid container, and one for the cell border. This problem does not occur now
- In the Pro version, we need handlers to resize columns. If `showColumnRightBorder=true` this handlers became invisible, and so we need a border to know exactly where doe the last column ends

### CODE REVIEW

File: packages/grid/x-data-grid/src/components/GridRow.tsx [hunk 1]
```diff
@@ -225,11 +221,7 @@ function GridRow(props: React.HTMLAttributes<HTMLDivElement> & GridRowProps) {
     const column = renderedColumns[i];
     const indexRelativeToAllColumns = firstColumnToRender + i;
 
-    const isLastColumn = indexRelativeToAllColumns === visibleColumns.length - 1;
-    const removeLastBorderRight = isLastColumn && hasScrollX && !hasScrollY;
-    const showRightBorder = !isLastColumn
-      ? rootProps.showCellRightBorder
-      : !removeLastBorderRight && rootProps.disableExtendRowFullWidth;
+    const showRightBorder = rootProps.showCellRightBorder;
```
Comment (m4theushw) [inline packages/grid/x-data-grid/src/components/GridRow.tsx:224]: I think part of the previous code we should keep. On systems that have 0px width scrollbar (e.g. macOS or mobile), I can still see the border.

msedge_WI93JzhmFc

**Review by m4theushw — COMMENTED** [review]
Shouldn't we fix `disableExtendRowFullWidth` too? Reading its description seems that we're supporting partially it = only removing the last border. If the description is correct, `disableExtendRowFullWidth=false` should behave like if the last column had `flex=1`.

https://github.com/mui/mui-x/blob/c746e61fb4baf2227ac4a5bf07d50e53bce8009f/packages/grid/x-data-grid/src/models/props/DataGridProps.ts#L163-L166

Currently, it gives the impression that the row is extending the full width, but once the cell is clicked I see its true width.

image

Changing the way `disableExtendRowFullWidth` works can be a breaking change, it depends on how we see its behavior.

**Comment by alexfauquette** [comment]
@m4theushw I reverted my changes, to only correct the `isLastColumn` computation such that rows and columns have the same behavior

About `disableExtendRowFullWidth=false` I gave it a try, but I did not succeed, because I tried to do the modifications in components rendering, style. But they are overridden when resizing.

In fact their is multiple level of implementations: 
- At the initialisation the with is considered as a `min-width` for the last column
- The last column always fill the remaining space

But this sounds like a low priority feature. As soon as the grid overflow in x-axis, it does not have any impact and I believe it's the most frequent case

**Review by flaviendelangle — APPROVED** [review]
We can continue the discussion for deeper changes later on
But this one-liner seems to fix an error so I would be in favor of moving forward

**Review by m4theushw — COMMENTED** [review]
> About disableExtendRowFullWidth=false I gave it a try, but I did not succeed, because I tried to do the modifications in components rendering, style. But they are overridden when resizing.

In v6 we can revisit this prop and make it work correctly. What about adding it to https://github.com/mui/mui-x/issues/3287?

**Comment by alexfauquette** [comment]
@m4theushw I added it
