### PR TITLE
[DataGrid] Scroll performance improvements

### LINKED ISSUE #569: [DataGrid] Explore scrolling performance issues
I've only just started using this component so I might be missing something, but it looks like there's a lot of unnecessary re-renders. The three I've split out are repeated many times, it looks like one repeat for every row, but I will test more.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behaviour 😯

```
whyDidYouRender.min.js:8 RowCells
whyDidYouRender.min.js:8 {RowCells: ƒ}RowCells: e=> {…}arguments: (...)caller: (...)length: 1name: ""__proto__: ƒ ()[[FunctionLocation]]: index-esm.js:15[[Scopes]]: Scopes[3]__proto__: Object "Re-rendered because of props changes:"
whyDidYouRender.min.js:8 props.hasScroll
whyDidYouRender.min.js:8 different objects that are equal by value. (more info at http://bit.ly/wdyr02)
whyDidYouRender.min.js:8 {prev hasScroll: {…}}prev hasScroll: x: falsey: false__proto__: Object__proto__: Object "!==" {next hasScroll: {…}}next hasScroll: x: falsey: false__proto__: Object__proto__: Object
```
```
whyDidYouRender.min.js:8 GridCell
whyDidYouRender.min.js:8 {GridCell: ƒ}GridCell: e=> {…}arguments: (...)caller: (...)length: 1name: ""__proto__: ƒ ()[[FunctionLocation]]: index-esm.js:15[[Scopes]]: Scopes[3]0: Closure {react__WEBPACK_IMPORTED_MODULE_0__: {…}, _material_ui_core_utils__WEBPACK_IMPORTED_MODULE_1__: Module, _material_ui_core_Checkbox__WEBPACK_IMPORTED_MODULE_2__: Module, _material_ui_core_Badge__WEBPACK_IMPORTED_MODULE_4__: Module, _material_ui_core_IconButton__WEBPACK_IMPORTED_MODULE_5__: Module, …}1: Closure (./node_modules/@material-ui/data-grid/dist/index-esm.js) {__webpack_exports__: Module, __webpack_require__: ƒ}2: Global {window: Window, self: Window, document: document, name: "", location: Location, …}__proto__: Object "Re-rendered because of props changes:"
whyDidYouRender.min.js:8 props.children
whyDidYouRender.min.js:8 different React elements (remember that the <jsx/> syntax always produces a *NEW* immutable React element so a component that receives <jsx/> as props always re-renders.). (more info at http://bit.ly/wdyr02)
whyDidYouRender.min.js:8 {prev children: {…}}prev children: {$$typeof: Symbol(react.element), type: {…}, key: null, ref: null, props: {…}, …}__proto__: Object "!==" {next children: {…}}next children: {$$typeof: Symbol(react.element), type: {…}, key: null, ref: null, props: {…}, …}$$typeof: Symbol(react.element)key: nullprops: {element: undefined, value: undefined, field: "__check__", data: {…}, getValue: ƒ, …}ref: nulltype: {$$typeof: Symbol(react.memo), compare: null, displayName: "CellCheckboxRenderer", type: ƒ}_owner: FiberNode {tag: 15, key: null, elementType: {…}, stateNode: null, type: ƒ, …}_store: {validated: true}_self: null_source: null__proto__: Object__proto__: Object
```
```
whyDidYouRender.min.js:8 CellCheckboxRenderer
whyDidYouRender.min.js:8 {CellCheckboxRenderer: ƒ}CellCheckboxRenderer: ({rowModel:e,value:t})=> {…}arguments: (...)caller: (...)length: 1name: ""__proto__: ƒ ()[[FunctionLocation]]: index-esm.js:15[[Scopes]]: Scopes[3]__proto__: Object "Re-rendered because of props changes:"
whyDidYouRender.min.js:8 props.getValue
whyDidYouRender.min.js:8 different functions with the same name. (more info at http://bit.ly/wdyr02)
whyDidYouRender.min.js:8 {prev getValue: ƒ} "!==" {next getValue: ƒ}
```

## Expected Behaviour 🤔

Little to no re-renders

## Steps to Reproduce 🕹

Using demo code for a basic Data Grid from the docs: https://codesandbox.io/s/material-ui-issue-forked-ni3nx

Open devtools console to see the output.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | 4.0.0-alpha.9  |
| React         |  ^16.13.1 |
| Browser       | Chromium 86.0.4240.183 (Official Build) snap (64-bit) |

### LINKED ISSUE #9013: Possibility to memoize rows when pinnedColumns are set
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hi, 
would it be possible to implement row memoization also if there are columns that are pinned ?
We currently pin by default the checkbox column and it causes the row memoization to fail, it fails at comparing renderedColumns although if I put into memo deepEqual it passes as equal.

### Examples 🌈

https://codesandbox.io/s/strange-shadow-717s3z?file=/demo.tsx

### Motivation 🔦

_No response_

### Order ID 💳 (optional)

#54652

### PR DESCRIPTION
**Pull request by romgrk**
Closes #569
Closes #9013
Discussion #9001 

This PR improves the scrolling performance as well as the overall performance by reducing the amount of re-renders, by applying the solution in point 1 of the discussion linked above. I have not included the proposed `useGridRootPropsSelector` in this PR to limit the scope & facilitate reviews. It can be added independently later.

Tasks:
 - [x] Ensure #9013 is handled
 - [x] Docs: update performance section
 - [x] Docs: https://github.com/mui/mui-x/issues/8932#issuecomment-1559725822
 - [x] Tests: make them pass
 - [x] Tests: add performance testing
 - [x] Post new benchmarks

<details>
<summary>Below are profiles of scrolling the following demo:</summary>

CPU: Intel Core 13th gen i7

```tsx
export default function Component() {
  const { data } = useDemoData({
    dataSet: "Commodity",
    rowLength: 100,
    editable: true,
    maxColumns: 15
  });

  return (
    <Box
      sx={{
        height: 750,
        width: '100%',
      }}
    >
      <DataGridPro
        {...data}
        initialState={data.initialState}
        rowHeight={38}
        checkboxSelection
        disableRowSelectionOnClick
      />
    </Box>
  );
}
```

</details>

| Before | After |
| --- | --- |
| Screenshot from 2023-05-24 19-12-19 | Screenshot from 2023-05-24 19-16-01 |

### CODE REVIEW

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx [hunk 1]
```diff
@@ -125,16 +107,111 @@ const GridCell = React.forwardRef<HTMLDivElement, GridCellProps>((props, ref) =>
...
+  const editRowsState = useGridSelector(apiRef, gridEditRowsStateSelector);
+
+  const { classes: rootClasses, getCellClassName } = rootProps;
+
+  const isSelected = useGridSelector(apiRef, () =>
+    apiRef.current.unstable_applyPipeProcessors('isCellSelected', false, {
+      id: rowId,
+      field,
+    }),
+  );
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/components/cell/GridCell.tsx:126]: Some of our `state` accesses are hidden behind pipe processors, this is why some selectors don't use their input parameter.

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx [hunk 2]
```diff
@@ -125,16 +107,111 @@ const GridCell = React.forwardRef<HTMLDivElement, GridCellProps>((props, ref) =>
...
+        return apiRef.current.getCellParams<any, any, any, GridTreeNodeWithRender>(rowId, field);
+      } catch (e) {
+        if ((e as Error).message.startsWith('No row with id')) {
+          return null as any;
+        }
+        throw e;
+      }
+    },
+    shallowCompare,
+  );
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/components/cell/GridCell.tsx:144]: This is quite ugly. The problem is that `.getCellParams()` reaction to accessing a cell that doesn't exist anymore is to throw an error. For selectors, we'd need a function that returns an empty value (`null` or `undefined`) if accessing a cell that doesn't exist.

The `catch` branch is hit when there is a cell that has been deleted from the state but the cell component hasn't been unmounted yet.

I'm open to suggestions if someone wants this to be prettier.

File: packages/grid/x-data-grid/src/hooks/features/rows/useGridParamsApi.ts [hunk 3]
```diff
@@ -133,12 +133,6 @@ export function useGridParamsApi(apiRef: React.MutableRefObject<GridPrivateApiCo
     (id, field) => {
       const colDef = apiRef.current.getColumn(field);
 
-      if (process.env.NODE_ENV !== 'production') {
-        if (!colDef && !warnedOnceMissingColumn) {
-          warnMissingColumn(field);
-        }
-      }
-
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/features/rows/useGridParamsApi.ts:141]: This makes our test suite fail due to the warning. Similar problem than the `try/catch` above, accessing an unexistent cell with `.getCellParams()` is considered an error.

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts [hunk 4]
```diff
@@ -2,31 +2,64 @@ import * as React from 'react';
...
+  apiRef: React.MutableRefObject<Api>,
+  selector: ((state: Api['state']) => T) | OutputSelector<Api['state'], T>,
+) {
+  if (isOutputSelector<Api, T>(selector)) {
+    return selector(apiRef);
+  }
+  return selector(apiRef.current.state);
+}
+
+export const defaultCompare = Object.is; // XXX: Do we need to polyfill?
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts:30]: Comments welcome here.

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts [hunk 5]
```diff
@@ -2,31 +2,64 @@ import * as React from 'react';
...
+      const state = stateRef.current;
+      const newState = applySelector(apiRef, selectorRef.current!);
+      if (!equals(state, newState)) {
+        stateRef.current = newState;
+        setState(newState);
+      }
+    });
+  }, EMPTY);
+
+  return state;
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts:64]: AFAICT, because all our store updates complete in a single operation, we don't need to worry about tearing in React 18, and thus we don't need to use `React.useSyncExternalStore`.

File: packages/grid/x-data-grid/src/utils/fastShallowCompare.ts [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+  }
+
+  for (const key in b) {
+    if (!(key in a)) {
+      return false;
+    }
+  }
+
+  return true;
+}
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/utils/fastShallowCompare.ts:30]: When the store updates, it publishes an event to all `useGridSelector` listeners. For the grid cells, one of those selectors is `.getCellParams()` which returns a bundle of props related to the cell. This function allows us to compare those bundles very quickly and avoid re-renders if none of those fields has changed.

I've looked at a few comparison packages & functions, they all use `Object.keys` twice, and/or `Object.hasOwnProperty`. Using a `for ... in` and `key in ...` allows us to avoid 2 array allocations & many function calls, which ensure this is as fast & resource-efficient as possible. The trade-off is that this function has subtle differences if it receives an exotic object (e.g. something with a prototype), but considering this is an internal function it feels ok to focus on speed.

With the current implementation, store updates don't even show up in the profiling logs because they're too fast.

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx (hunk 1 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx:126]: At first, I didn't understand why `useGridSelector` is used here.
But now I see 2 reasons:
1. To avoid calling `unstable_applyPipeProcessors` on each rerender
2. To call `unstable_applyPipeProcessors` on state change even if the cell is not rerendered (because of React.memo)

Do I understand it correctly?

File: packages/grid/x-data-grid/src/utils/fastShallowCompare.ts [hunk 7]
```diff
@@ -0,0 +1,34 @@
+const is = Object.is;
+
+export function fastShallowCompare<T extends Record<string, unknown> | null | undefined>(
+  a: T,
+  b: T,
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/utils/fastShallowCompare.ts:5]: I feel like we shouldn't assume that both values are of the same type. In some cases, we might compare `object` and `null`/`undefined`

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx [hunk 8]
```diff
@@ -125,16 +107,112 @@ const GridCell = React.forwardRef<HTMLDivElement, GridCellProps>((props, ref) =>
...
+    apiRef,
+    () => {
+      // This is required because `.getCellParams` tries to get the `state.rows.tree` entry
+      // associated with `rowId`/`fieldId`, but this selector runs after the state has been
+      // updated, while `rowId`/`fieldId` reference an entry in the old state.
+      try {
+        return apiRef.current.getCellParams<any, any, any, GridTreeNodeWithRender>(rowId, field);
+      } catch (e) {
+        if ((e as Error).message.startsWith('No row with id')) {
+          return null as any;
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/cell/GridCell.tsx:138]: With this assertion, `cellParams` is of type `any`. Can we avoid that?

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx (hunk 2 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx:144]: I think it's fine the way it is 👍

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx [hunk 9]
```diff
@@ -125,16 +107,112 @@ const GridCell = React.forwardRef<HTMLDivElement, GridCellProps>((props, ref) =>
...
+  const isEditable = cellParams.isEditable;
+  const valueToRender =
+    cellParams.formattedValue == null ? cellParams.value : cellParams.formattedValue;
+
   const ownerState = { align, showRightBorder, isEditable, classes: rootProps.classes, isSelected };
   const classes = useUtilityClasses(ownerState);
 
+  let children: React.ReactNode;
+  /* eslint-disable-next-line no-lone-blocks */
+  {
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/cell/GridCell.tsx:179]: This code block seems to be unnecessary

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx [hunk 10]
```diff
@@ -8,38 +8,27 @@ import {
...
-  hasFocus?: boolean;
   height: number | 'auto';
-  isEditable?: boolean;
-  isSelected?: boolean;
   showRightBorder?: boolean;
-  value?: V;
   width: number;
-  cellMode?: GridCellMode;
-  children: React.ReactNode;
-  tabIndex: 0 | -1;
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/components/cell/GridCell.tsx:42]: These are technically breaking changes because these props are passed to the [`cell` slot](https://github.com/mui/mui-x/blob/f03017b40ac72095b342a84dc30ed833f10f62e7/packages/grid/x-data-grid/src/constants/defaultGridSlotsComponents.ts#L23).
We might break people's code in cases where they're wrapping the default `GridCell` component **and** accessing the props that have been removed:
```jsx
const CellSlot = (props) => {
  // props.value is not here anymore
  <GridCell {...props} />
}

<DataGrid
  slots={{
    cell: CellSlot
  }}
/>
```

I think it's a rare use case, but quickly searching through the issues, I found one example:
https://github.com/mui/mui-x/issues/8511#issuecomment-1524001995

Maybe we can postpone changes to this interface until the next major version?

File: docs/data/data-grid/performance/performance.md [hunk 11]
```diff
@@ -2,43 +2,44 @@
...
+  );
+}
 ```
 
-The following demo show this trick in action.
-It also contains additional logic to highlight the components when they re-render.
+An easy way to prevent re-renders is to extract any object that can be a static object, and to memoize any object that
+depends on another object. This applies to any prop that is an object or a function.
 
-{{"demo": "GridWithReactMemo.js", "bg": "inline", "defaultCodeOpen": false}}
```
Comment (cherniavskii) [inline docs/data/data-grid/performance/performance.md:36]: Would it make sense to keep this demo to visualize the rerenders?

**Review by cherniavskii — COMMENTED** [review]
This looks very promising! Great work!

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx (hunk 1 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx:126]: It's used to create a reactive binding so that when the state changes, `isSelected` is recomputed, which trigger a re-render of the cell if it changed. Underneath, the pipe processor is [accessing the state here](https://github.com/mui/mui-x/blob/138dba77936385405ec92688aaabe323c74deb05/packages/grid/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts#L83-L89).

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx (hunk 2 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx:144]: Yeah I don't want to change it, changing the behavior/signature of `.getCellParams` would be semver major :|

File: packages/grid/x-data-grid/src/utils/fastShallowCompare.ts (hunk 7 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/utils/fastShallowCompare.ts:5]: The type constraint on T is `extends Record<string, unknown> | null | undefined`, IIUC `T` is at most `Record<string, unknown> | null | undefined`.

image

File: packages/grid/x-data-grid/src/utils/fastShallowCompare.ts [hunk 12]
```diff
@@ -0,0 +1,34 @@
+const is = Object.is;
+
+export function fastShallowCompare<T extends Record<string, unknown> | null | undefined>(
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/utils/fastShallowCompare.ts:3]: Indeed. It would return `true` for something like `[1, 2, 3]` and `{0: 1, 1: 2, 2: 3}` though.

I think we should not include arrays here, if the goal is "fast" then arrays can have an even faster specialized comparison function thanks to their `.length` prop and `while (i--)`.

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts [hunk 13]
```diff
@@ -2,31 +2,65 @@ import * as React from 'react';
...
     }
   }
 
-  if (isOutputSelector<Api, T>(selector)) {
-    return selector(apiRef);
-  }
+  const selectorRef = React.useRef<typeof selector>();
+  const [state, setState] = React.useState<T>(
+    (selectorRef.current ? null : applySelector(apiRef, selector)) as T,
+  );
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts:47]: The current implementation doesn't re-allocate the `() => applySelector(...)` initialization closure on every render.

For both this comment and the one before, I'm aware those are micro-optimizations. I generally prefer to focus on readability first, but sometimes when a function is called a lot I trade some readability for some performance. I've run a few examples, on a small datagrid with compact density there are around 300 `useGridSelector` hooks mounted at all times. On a fullscreen (laptop screen) datagrid, there are around 1400 of them. Those are numbers where I kinda wanna start trading off readability. Lmk what you think.

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts [hunk 14]
```diff
@@ -2,31 +2,65 @@ import * as React from 'react';
...
+  React.useEffect(() => {
+    return apiRef.current.store.subscribe(() => {
+      const newState = applySelector(apiRef, selectorRef.current!);
+      if (!equals(stateRef.current, newState)) {
+        stateRef.current = newState;
+        setState(newState);
+      }
+    });
+  }, EMPTY);
+  /* eslint-enable react-hooks/exhaustive-deps */
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts:63]: The linter isn't happy with `EMPTY` because it considers it a dynamic value.

File: packages/grid/x-data-grid/src/utils/fastShallowCompare.ts (hunk 6 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/utils/fastShallowCompare.ts]: Interesting thought, but I think we could make this run faster by create a comparison function generator, something like `function createShallowCompare() { return fastShallowCompare() {...} }`, and each object type would have its own comparison function, e.g. `const cellParamsCompare = createShallowCompare()`. This would allow JS engines' inline caches to only see specific object shapes go into each of those comparison functions, which could potentially allow them to JIT them to very specialized functions. All speculative though, and this is fine the way it is.

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx (hunk 9 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx:179]: Everything inside the block is initializing the `children`. I feel like it gives a bit of organization, and allows to fold that section of the code easily. I can remove it, I prefer it but I don't insist too much on it.

File: docs/data/data-grid/performance/performance.md (hunk 11 above)
Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:36]: It's not accurate anymore. If we want to visualize re-renders, we'd need to add the tracking code inside the rows/cells. Thanks to the new architecture, the cells can re-render even if their parent hasn't re-rendered. But I think I could implement it by adding a `useEffect` inside `.renderCell`.

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx (hunk 10 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx:42]: Damn, that's true. We lose quite a few benefits of this PR if we keep those fields where they are though. For example, if `hasFocus` is at the row level, then the whole row has to re-render when a cell gains/loses focus. If it's at the cell level, then only the specific cells that gained/lost focus need to re-render.

Do we have planned dates for major versions?

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx:42]: What if instead of using `rootProps.slots.cell` in `GridRow`, we add a wrapper component (`GridCellWrapper`) that will render `rootProps.slots.cell` with the same props as before?
Moving the code from `GridRow` to `GridWrapperCell` instead of `GridCell` would allow keeping the same interface for `GridCell`.
Does this make sense?

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx (hunk 2 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx]: Here's some context on why `getCellParams` throws an error if the row is missing https://github.com/mui/mui-x/pull/2010

File: packages/grid/x-data-grid/src/utils/fastShallowCompare.ts (hunk 7 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/utils/fastShallowCompare.ts:5]: Yes, you're right 👍

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts:47]: > Yes. The current implementation doesn't re-allocate the () => applySelector(...) initialization closure on every render.

I didn't even think about it as optimization 🤯

> I've run a few examples, on a small datagrid with compact density there are around 300 useGridSelector hooks mounted at all times. On a fullscreen (laptop screen) datagrid, there are around 1400 of them. Those are numbers where I kinda wanna start trading off readability.

Do you have any perf measurements for that? I'm curious to learn how impactful this is 🙂

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx (hunk 2 above)
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx]: Maybe use a custom error that extends `Error` and use `instanceof` instead of checking the error message?

File: docs/data/data-grid/performance/performance.md (hunk 11 above)
Comment (cherniavskii) [reply docs/data/data-grid/performance/performance.md:36]: Maybe this would work?
```jsx
const CellWithTracer = React.forwardRef((props, ref) => {
  return <TraceUpdates ref={ref} Component={GridCell} {...props} />;
});
const MemoizedCell = React.memo(CellWithTracer);
const slots = { cell: MemoizedCell }
```

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts:47]: > I didn't even think about it as optimization

Lol yeah I spent my last year doing low-level programming, I keep seeing allocations everywhere in javascript and it drives me crazy.

> Do you have any perf measurements for that?

No measurements :( Memory allocations are fast enough for closures that this won't appear in the profiles, what's slow is the GC pauses. And we can't measure those, so we can't really benchmark this properly.

In other cases, like filtering performance, it's easier to see the impact of allocations because there is much more upfront memory IO (i.e. reading all the values for the `cellParams` field, and writing those to the new object). Also the fact that filtering runs all its computations in a tight loop allows GC pauses to happen during those computation, unlike in event handlers where the engine can run the GC later.

File: docs/data/data-grid/performance/performance.md (hunk 11 above)
Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:36]: Not really, some of the cell updates now come from within the cell hooks, not because their parent re-rendered & changed their props.

File: packages/grid/x-data-grid/src/components/GridRow.tsx [hunk 15]
```diff
@@ -256,141 +255,49 @@ const GridRow = React.forwardRef<HTMLDivElement, GridRowProps>(function GridRow(
...
-      focusedCell,
-      tabbableCell,
-      CellComponent,
-      rowHeight,
-      slotProps?.cell,
-      rootClasses,
-    ],
+  const sizes = useGridSelector(
+    apiRef,
+    () => ({ ...apiRef.current.unstable_getRowInternalSizes(rowId) }),
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/GridRow.tsx]: I can confirm that this is required, some tests fail if we don't unwrap them. Because they are mutated directly, `fastShallowCompare`'s `a === b` check succeeds.

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx (hunk 10 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx]: I've applied the wrapper thing, works great.

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts (hunk 14 above)
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts]: I've grouped the refs so we get an up-to-date `equals` value.

File: docs/data/data-grid/performance/performance.md (hunk 11 above)
Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:36]: I've re-added the visualization here: https://deploy-preview-9037--material-ui-x.netlify.app/x/react-data-grid/performance/#visualization

It's cell-based now, so we can clearly see that only the required cells re-render.

File: .eslintrc.js [hunk 16]
```diff
@@ -70,6 +70,7 @@ module.exports = {
    */
   rules: {
     ...baseline.rules,
+    'prefer-object-spread': 'off',
```
Comment (romgrk) [inline .eslintrc.js:73]: `_objectSpread2` is at the top of stack traces in performance profiles and this rule keeps re-writing my `Object.assign` into `{ ... }`.

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts (hunk 14 above)
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts:75]: Is `EMPTY` a micro-optimization to avoid allocating a new array when passing the expected dependencies (`[apiRef, refs]`)?

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts]: Could you add a comment to clarify why the initializer function is not used here?

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts (hunk 14 above)
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts:75]: Yes

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts]: Done

File: docs/data/data-grid/performance/performance.md [hunk 17]
```diff
@@ -2,43 +2,51 @@
 
 <p class="description">Improve the performance of the DataGrid using the recommendations from this guide.</p>
 
-## Memoize inner components with `React.memo`
+## Extract static objects and memoize root props
```
Comment (cherniavskii) [inline docs/data/data-grid/performance/performance.md:5]: Is it fair to expect a visible performance improvement on scroll after this PR?

I tried to compare a build from this PR to the latest stable version with a 6x CPU slowdown:
v6.5.0: https://codesandbox.io/s/nostalgic-tdd-imricw?file=/demo.tsx

https://github.com/mui/mui-x/assets/13808724/ef3efc16-6195-4b80-b5fb-fc7d57a3a515

this PR: https://codesandbox.io/s/serene-frost-c0u0wh?file=/demo.tsx


https://github.com/mui/mui-x/assets/13808724/771c340b-c87b-4ef9-be5d-4f6c9e3286bb

File: docs/data/data-grid/performance/performance.md [hunk 18]
```diff
@@ -2,43 +2,51 @@
...
 
-The `DataGrid` component is composed of a central state object where all data is stored.
-When an API method is called, a prop changes, or the user interacts with the UI (e.g. filtering a column), this state object is updated with the changes made.
-To reflect the changes in the interface, the component must re-render.
-Since the state behaves like `React.useState`, the `DataGrid` component will re-render its children, including column headers, rows, and cells.
-With smaller datasets, this is not a problem for concern, but it can become a bottleneck if the number of rows increases, especially if many columns render [custom content](/x/react-data-grid/column-definition/#rendering-cells).
-One way to overcome this issue is using `React.memo` to only re-render the child components when their props have changed.
-To start using memoization, import the inner components, then pass their memoized version to the respective slots, as follow:
+The `DataGrid` component uses `React.memo` to optimize its performance, which means itself and its subcomponents only
```
Comment (cherniavskii) [inline docs/data/data-grid/performance/performance.md:7]: Also tried a sandbox from https://github.com/mui/mui-x/issues/569#issuecomment-1403571943
v6.5.0: https://codesandbox.io/s/loving-paper-2fhtsq?file=/src/Demo.js
This PR: https://codesandbox.io/s/great-hopper-ufcwdd?file=/src/Demo.js

File: docs/data/data-grid/performance/performance.md (hunk 17 above)
Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:5]: > Is it fair to expect a visible performance improvement on scroll after this PR?

Lol yes, that's the point of the PR.

> Note: both demos are being run in Codesandbox, which is using React in development mode, but I think it's OK for comparison like this

I'm not sure how it would affect it. The final profiles that I posted (in the top-level comment) were run in production mode, which is the only mode I trust for actual results. I generally use dev mode only to give me an idea of what to work on, in particular for rendering-heavy code where React adds a lot of validation & instrumentation.

I'll run more benchmarks to ensure the results are positive and I'll publish them early next week.

Have you tried comparing the [PR netlify deployment](https://deploy-preview-9037--material-ui-x.netlify.app/x/introduction/)? (which I assume is in production mode)

File: docs/data/data-grid/performance/performance.md (hunk 11 above)
Comment (cherniavskii) [reply docs/data/data-grid/performance/performance.md:36]: > Not really, some of the cell updates now come from within the cell hooks, not because their parent re-rendered & changed their props.

Oh, right.

> I've re-added the visualization here: [deploy-preview-9037--material-ui-x.netlify.app/x/react-data-grid/performance/#visualization](https://deploy-preview-9037--material-ui-x.netlify.app/x/react-data-grid/performance/#visualization)

> It's cell-based now, so we can clearly see that only the required cells re-render on scroll, both vertically and horizontally.

Looks awesome! 🎉
How did you make it work for the updates coming from the cell hooks?

Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:36]: `useGridSelector` now encapsulates a `useState`, and the store thing calls the `setState` function when the selector value changes, so the cells can update only when their `useGridSelector`ed value changes.

File: docs/data/data-grid/performance/performance.md (hunk 17 above)
Comment (cherniavskii) [reply docs/data/data-grid/performance/performance.md:5]: > Have you tried comparing the [PR netlify deployment](https://deploy-preview-9037--material-ui-x.netlify.app/x/introduction/)? (which I assume is in production mode)

Yes, I did, but then thought this comparison might not be fair because the demos do not memoize the `slots` prop:

https://deploy-preview-9037--material-ui-x.netlify.app/x/react-data-grid/#commercial-version

https://github.com/mui/mui-x/assets/13808724/c95707b4-20ef-41e4-a925-14605260657b

---

https://mui.com/x/react-data-grid/#commercial-version

https://github.com/mui/mui-x/assets/13808724/0f4cc7a2-b38c-4bfc-868e-b69bbd7ae176

Comment (cherniavskii) [reply docs/data/data-grid/performance/performance.md:5]: > I'll run more benchmarks to ensure the results are positive and I'll publish them early next week.

Cool, thanks!

Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:5]: Running proper benchmarks itself is a tricky task. For example, if you have the react-dev-tools extension installed in your browser, it's going to add a lot of `performance.mark()` calls _even when you're not using it_, so all the benchmarks run in that context are corrupted, or at least distorted (incidentally, it's also slowing down your day-to-day browsing if you have it enabled at all times). I generally benchmark results on a clean guest profile window, with as few applications open as possible, while avoiding to breathe too loudly.

Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:5]: > Yes, I did, but then thought this comparison might not be fair because the demos do not memoize the slots prop:

Yeah and the demo you linked is actually incorrect for this PR, this PR adds `React.memo` and that demo also adds `React.memo`, so there is a double `memo`. I need to update the docs to fix that.

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts (hunk 14 above)
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts:76]: Adding the `useOnMount` hook sounds like a good idea to me 👍

File: docs/data/data-grid/performance/performance.md (hunk 17 above)
Comment (cherniavskii) [reply docs/data/data-grid/performance/performance.md:5]: > For example, if you have the react-dev-tools extension installed in your browser, it's going to add a lot of performance.mark() calls even when you're not using it, so all the benchmarks run in that context are corrupted, or at least distorted

My assumption was that both demos are similarly impacted by external factors (not related to this PR), and therefore performance gains should be noticeable anyway.
But maybe that assumption was incorrect.

File: package.json [hunk 19]
```diff
@@ -22,6 +22,7 @@
     "l10n": "babel-node -x .ts ./scripts/l10n.ts",
     "jsonlint": "node ./scripts/jsonlint.mjs",
     "eslint": "eslint . --cache --report-unused-disable-directives --ext .js,.ts,.tsx --max-warnings 0",
+    "eslint:fix": "eslint . --cache --report-unused-disable-directives --ext .js,.ts,.tsx --max-warnings 0 --fix",
```
Comment (cherniavskii) [inline package.json:25]:
```suggestion
    "eslint:fix": "yarn eslint --fix",
```

File: packages/grid/x-data-grid/src/hooks/features/rows/useGridParamsApi.ts [hunk 20]
```diff
@@ -113,6 +104,7 @@ export function useGridParamsApi(apiRef: React.MutableRefObject<GridPrivateApiCo
         tabIndex: cellTabIndex && cellTabIndex.field === field && cellTabIndex.id === id ? 0 : -1,
         value,
         formattedValue: value,
+        isEditable: false,
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/features/rows/useGridParamsApi.ts:107]: Why is this necessary? It's overridden a few lines down

**Review by cherniavskii — COMMENTED** [review]
Great work! 🎉
Looking forward to more benchmarks!

File: docs/data/data-grid/performance/performance.md (hunk 11 above)
Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:36]: Yep, works thanks to the wrapper. For the tracing to work we need custom code inside the component, there is no way around that.

File: packages/grid/x-data-grid/src/hooks/features/rows/useGridParamsApi.ts (hunk 20 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/features/rows/useGridParamsApi.ts:107]: JS engines can create the object shape/map/hidden-class in one go, without transition.

File: scripts/x-data-grid-premium.exports.json [hunk 21]
```diff
@@ -1,4 +1,5 @@
 [
+  { "name": "applySelector", "kind": "Function" },
```
[the remark this answers is not in the document]
Comment (romgrk) [reply scripts/x-data-grid-premium.exports.json:2]: Not sure how this works, what is included in these JSON files? How do I avoid this being included?

File: docs/data/data-grid/performance/performance.md (hunk 17 above)
Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:5]: Oh so I just looked at the codesandbox code you posted for the comparison, the same comment I made earlier applies:

> Yeah and the demo you linked is actually incorrect for this PR, this PR adds React.memo and that demo also adds React.memo, so there is a double memo. I need to update the docs to fix that.

To be clear: the optimization that this PR does _is adding `React.memo` by default_. The difference is that this PR does it while also adding logic that will make things work as they do without `React.memo`. So the performance would be:

 - (master): slowest
 - (master) + `React.memo`: fastest
 - (PR) + `React.memo` + store updates logic: fast, but slightly less than above

**Comment by romgrk** [comment]
TODO: Check if we can remove:

https://github.com/mui/mui-x/blob/bfad5f8a204b49321215936f2f08e769c71f15f8/docs/babel.config.js#L58

File: .eslintrc.js (hunk 16 above)
Comment (romgrk) [reply .eslintrc.js]: I just realized that I've been doing benchmarks on our docs site, and our docs site uses a different babel config than our production release builds, which means our production builds have the `_objectSpread2` optimized away, but not our docs. So our components in the docs run slower than they will when used by our library users.

Comment (cherniavskii) [reply .eslintrc.js]: Can we optimize `_objectSpread2` in both?

File: docs/data/data-grid/performance/performance.md (hunk 17 above)
Comment (cherniavskii) [reply docs/data/data-grid/performance/performance.md:5]: > To be clear: the optimization that this PR does is adding React.memo by default. The difference is that this PR does it while also adding logic that will make things work as they do without React.memo

Right, so for visible performance gains we should be comparing:
1. master - without `React.memo`
2. this PR - without `React.memo` (now included by default)

I quickly compared them (again in Codesandbox):
- v6.6.0: https://codesandbox.io/s/sweet-lalande-tzoi3s?file=/demo.tsx

https://github.com/mui/mui-x/assets/13808724/9249502b-951a-4106-8a7e-a4160c5a80e9

- this PR: https://codesandbox.io/s/summer-feather-giow8o?file=/demo.tsx

https://github.com/mui/mui-x/assets/13808724/29c49c86-cc6b-451a-901c-32ac8fb99b00

File: .eslintrc.js (hunk 16 above)
Comment (romgrk) [reply .eslintrc.js]: Yes, but I'm waiting for core to merge https://github.com/mui/material-ui/pull/37461 so I can mirror their config.

File: packages/grid/x-data-grid/src/utils/fastShallowCompare.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/utils/fastShallowCompare.ts]: Done

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts (hunk 14 above)
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts]: Done

File: scripts/x-data-grid-premium.exports.json (hunk 21 above)
[the remark this answers is not in the document]
Comment (MBilalShafi) [reply scripts/x-data-grid-premium.exports.json:2]: All the values exported by the root `index.js` are added to these JSON files and are accessible to the users via something like:
```tsx
import { applySelector } from '@mui/x-data-grid'
```

File: packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx [hunk 22]
```diff
@@ -600,17 +600,17 @@ describe('<DataGrid /> - Keyboard', () => {
     it('should go back to same header when pressing "ArrowUp" and "ArrowDown" from column header', () => {
       render(<NavigationTestGroupingCaseNoScrollX />);
 
-      act(() => getColumnHeaderCell(4, 2).focus());
+      act(() => getColumnHeaderCell(2, 2).focus());
```
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx:603]: It indicates a behavior change in keyboard navigation:

https://mui.com/x/react-data-grid/column-groups/#define-column-groups

https://github.com/mui/mui-x/assets/13808724/5aa936db-1888-4b1c-8885-3c2897055b38

https://deploy-preview-9037--material-ui-x.netlify.app/x/react-data-grid/column-groups/#define-column-groups

https://github.com/mui/mui-x/assets/13808724/1c5bd4c1-36ae-42d8-89a5-27db0348b90e

File: scripts/x-data-grid-premium.exports.json (hunk 21 above)
[the remark this answers is not in the document]
Comment (cherniavskii) [reply scripts/x-data-grid-premium.exports.json:2]: It reflects all the exports that end up being exported in the package entry `index.js`.
Taking `applySelector` as example, it's exported in `useGridSelector.ts`:
https://github.com/romgrk/mui-x/blob/a2052c5dcb7fb6ce0e3246d7cf791c38036446e0/packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts#L21
And everything from `useGridSelector` is also exported in https://github.com/romgrk/mui-x/blob/a2052c5dcb7fb6ce0e3246d7cf791c38036446e0/packages/grid/x-data-grid/src/hooks/utils/index.ts#L4
Eventually, this export makes it to the top-level `index.js`.

In the case of `applySelector`, it's only used in the file where it's defined, so you can simply not export it.
In other cases, you might need to trace the export chain and restricts some export  - e.g. replace `export * from` with specific exports.

File: docs/data/data-grid/performance/performance.md (hunk 17 above)
Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:5]: Preliminary exploration, but from what I've seen the cell wrapper comes up a lot in the profiles. I haven't benchmarked again after splitting the cell & the wrapper, and the other refactoring, I'll test again.

The CPU profiles show a small improvement for this PR, but the experience while scrolling seems slightly better for master, though I don't trust myself much to scroll with the same intensity. I'll poke around some more.

Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:5]: Found the issue. The [why-did-you-render whack-a-mole](https://github.com/mui/mui-x/pull/8998) PR was meant to go with this one. It ensures the `React.memo()` can properly abort rendering. I'll cherry-pick the commits and test again.

File: packages/grid/x-data-grid/src/utils/fastObjectShallowCompare.ts [hunk 23]
```diff
@@ -0,0 +1,34 @@
...
+  }
+
+  for (const _ in b) {
+    bLength += 1;
+  }
+  /* eslint-enable no-restricted-syntax */
+  /* eslint-enable guard-for-in */
+
+  return aLength === bLength;
+}
```
Comment (romgrk) [inline packages/grid/x-data-grid/src/utils/fastObjectShallowCompare.ts:34]: I found another optimization, instead of validating in the second loop that `b` keys are in `a`, we just compute the length of `b` keys. And because we already check in the `a` loop that all `a` keys are in `b`, we can simply compare the keys length
. We can't bail out of the `b` loop, but arithmetic ops are so cheap compared to key checks that it's worth it.

Benchmark: https://jsben.ch/aZKxv

| | Chrome | Firefox |
| --- | --- | --- |
| a & b are equal | Screenshot from 2023-06-02 07-47-08 | Screenshot from 2023-06-02 07-50-14 |
| a & b's first key differs | Screenshot from 2023-06-02 07-49-16 | Screenshot from 2023-06-02 07-50-45 |

Interestingly, `fastOSC improved` beats `fastOSC` even if `a` and `b` differ on their first key. But when the objects are equal, `fastOSC improved` is by far superior to the alternatives.

Comment (cherniavskii) [reply packages/grid/x-data-grid/src/utils/fastObjectShallowCompare.ts:34]: Nice! Totally makes sense, since we don't need to know which keys of `b` are missing in `a` 🎉

Comment (romgrk) [reply packages/grid/x-data-grid/src/utils/fastObjectShallowCompare.ts:34]: ^ This is just me being fascinated by performance improvements, but in practice object shallow equality checks are already so fast that this doesn't matter much. No need to pay much attention to this.

Comment (romgrk) [reply packages/grid/x-data-grid/src/utils/fastObjectShallowCompare.ts]: Got another small improvement by inverting the order of the two if branches in the `a` loop:

```typescript
    if (!is(a[key], b[key])) {
      return false;
    }
    if (!(key in b)) {
      return false;
    }
```

But it only holds for V8. On SpiderMonkey, inverting the branches doesn't yield any significant change.

https://jsben.ch/obBsU

File: packages/grid/x-data-grid/src/utils/fastObjectShallowCompare.ts [hunk 24]
```diff
@@ -0,0 +1,34 @@
...
+  for (const key in a) {
+    aLength += 1;
+
+    if (!(key in b)) {
+      return false;
+    }
+    if (!is(a[key], b[key])) {
+      return false;
+    }
+  }
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/utils/fastObjectShallowCompare.ts]: Slightly faster?
```suggestion
  for (const key in a) {
    if (!(key in b)) {
      return false;
    }
    if (!is(a[key], b[key])) {
      return false;
    }
    aLength += 1;
  }
```

**Review by MBilalShafi — COMMENTED** [review]
Great work around overall performance and refactoring, especially the concept of subscribing to the store updates is really cool. Thank you!

**Comment by romgrk** [comment]
@MBilalShafi:

> especially the concept of subscribing to the store updates is really cool.

I know! I've been exploring solidjs, and the way they [model & explain reactivity](https://www.solidjs.com/guides/reactivity) has been my inspiration for a few of these changes.

File: packages/grid/x-data-grid/src/utils/fastObjectShallowCompare.ts (hunk 24 above)
Comment (MBilalShafi) [reply packages/grid/x-data-grid/src/utils/fastObjectShallowCompare.ts]: Sounds good, by the way, which tool you use to do these comparisons?

File: packages/grid/x-data-grid/src/components/GridRow.tsx
Comment (romgrk) [inline packages/grid/x-data-grid/src/components/GridRow.tsx:1]: _Note: This comment is the performance analysis report, unrelated to `GridRow.tsx`, I'm commenting here to have a dedicated comment thread._

### Performance analysis

#### Test cases

I used 2 test cases
1. the 100k rows commodity dataset with default columns,
2. the 100k rows commodity dataset with custom renderer, all columns render to `<button>` elements.

The methodology was to compile the `master` branch, then this branch, open both on a clean browser profile, and one after the other: start the profiler, execute `$0.scrollTo({ top: 7000, behavior: 'smooth' })` in the console, stop the profile. This ensures the scrolling is consistent.

#### Summary

This PR improves performance consistently, although as not much as one would expect. The first thing to keep in mind is that the faster the user is scrolling, the less the impact of `React.memo` applies, because the rows are simply being cycled too much on every event. If the user is scrolling so fast that every scroll lands on all unrendered rows, there is no performance benefit to `React.memo`. The test cases I chose scroll fairly quickly, which explains the results below. The initial profiles I did (top-level comment in this PR) were done by scrolling 3 rows down, thus why they appear much more impressive — but they didn't represent a realistic use-case.

I will also note that lower CPU usage in the profiler doesn't necessarily correspond to less white areas, or at least I haven't been able to get consistent results for this PR in its current form wrt white areas. The reason for that _might_ be that if the UI thread is busy, it has less time to handle scrolling, which means it could be displating old but complete (no white areas) frames. The CPU usage gains in this PR could be used to add more rows around the viewport, which would have a benefic effect on white areas.

#### Results

For test case:
1. 30% improvement
2. 8% improvement

| Test case | Before | After | 
| --- | --- | --- |
| 1 (default) | commodity-before | commodity-after |
| 2 (button) | button-before | button-after |

File: docs/data/data-grid/performance/performance.md (hunk 17 above)
Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:5]: I've added the performance report in a comment below, continue the discussion there.

File: packages/grid/x-data-grid/src/components/GridRow.tsx
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/GridRow.tsx:1]: Thanks for sharing this!

> Results
> For test case:
> 1. 30% improvement
> 2. 8% improvement

Well, that's still an improvement 👍
Could you clarify what measurements were used for calculations?

Comment (romgrk) [reply packages/grid/x-data-grid/src/components/GridRow.tsx:1]: > Could you clarify what measurements were used for calculations?

Total JS scripting time for the whole scroll sequence. It's the orange part in the summary at the bottom of each image above.

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx [hunk 25]
```diff
@@ -90,12 +123,127 @@ const useUtilityClasses = (ownerState: OwnerState) => {
 
 let warnedOnce = false;
 
+// GridCellWrapper is a compatibility layer for the V6 cell slot. If we can use the more efficient
+// `GridCellV7`, we should. That component is a merge of `GridCellWrapper` and `GridCell`.
+// TODO(v7): Remove the wrapper & cellV6 and use the cellV7 exclusively
```
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx:128]: TODO: This probably broke the visualization demo.

File: packages/grid/x-data-grid/src/components/GridRow.tsx
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/GridRow.tsx:1]: Wouldn't this give a 14% improvement in the second test case? `(187 - 161) / 187 = 0.14`

Comment (romgrk) [reply packages/grid/x-data-grid/src/components/GridRow.tsx:1]: Yes, seems like it's 14%.

File: packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx (hunk 22 above)
[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx]: Fixed

**Comment by romgrk** [comment]
I've finished fixing the issues & docs, this is ready for review.

File: packages/grid/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx [hunk 26]
```diff
@@ -168,7 +168,7 @@ describe('<DataGridPro /> - Row Editing', () => {
           apiRef.current.setEditCellValue({ id: 0, field: 'currencyPair', value: ' usdgbp ' }),
         );
         await act(() => apiRef.current.setEditCellValue({ id: 0, field: 'price1M', value: 100 }));
-        expect(renderEditCell1.lastCall.args[0].row).to.deep.equal({
+        expect(renderEditCell2.lastCall.args[0].row).to.deep.equal({
```
Comment (romgrk) [inline packages/grid/x-data-grid-pro/src/tests/rowEditing.DataGridPro.test.tsx:171]: No idea why this was working in the first place. Reading the test case, AFAICT, this is the correct check.

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx (hunk 25 above)
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx]: I'm fine with duplicating it for now (considering it a backward compatibility cost).
Is the difference substantial when using 2 components?

[the remark this answers is not in the document]
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx]: IIRC, on the test-case 1, it was adding 0.5ms per scroll event on my brand new machine, so the cost could go to 1-1.5ms on average & low-end devices. If we target 60 FPS, we have 16ms total budget per scroll event (because scroll triggers right after a repaint according to the spec), if we assume the browser does its thing in 6ms we have 10ms for us.

So using 2 components for each cell can chew 5-15% of our budget, because cells are the most numerous components on screen.

NOTE: Actually it could be a bit higher than that. The additional 0.5ms I observed was for the `React.createElement` function, but having more nodes in the tree also affects the diffing cost.

File: scripts/x-data-grid-premium.exports.json [hunk 27]
```diff
@@ -128,9 +128,11 @@
   { "name": "GridCellModes", "kind": "Enum" },
   { "name": "GridCellModesModel", "kind": "TypeAlias" },
   { "name": "GridCellParams", "kind": "Interface" },
-  { "name": "GridCellProps", "kind": "Interface" },
+  { "name": "GridCellProps", "kind": "TypeAlias" },
   { "name": "GridCellSelectionApi", "kind": "Interface" },
   { "name": "GridCellSelectionModel", "kind": "TypeAlias" },
+  { "name": "GridCellV7", "kind": "Variable" },
+  { "name": "GridCellWrapper", "kind": "Variable" },
```
Comment (cherniavskii) [inline scripts/x-data-grid-premium.exports.json:135]: Is there a need to export these components?

File: packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts [hunk 28]
```diff
@@ -1,32 +1,76 @@
...
+  selector: ((state: Api['state']) => T) | OutputSelector<Api['state'], T>,
+) {
+  if (isOutputSelector<Api, T>(selector)) {
+    return selector(apiRef);
+  }
+  return selector(apiRef.current.state);
+}
+
+const defaultCompare = Object.is;
+export const shallowCompare = fastObjectShallowCompare;
```
Comment (cherniavskii) [inline packages/grid/x-data-grid/src/hooks/utils/useGridSelector.ts:31]: Rename `shallowCompare` to `objectShallowCompare`? The reason is the same as for `fastObjectShallowCompare` - to emphasize that it should be used only for objects

**Review by cherniavskii — APPROVED** [review]

File: packages/grid/x-data-grid/src/components/cell/GridCell.tsx (hunk 25 above)
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/cell/GridCell.tsx]: Thanks for the details 👍

File: scripts/x-data-grid-premium.exports.json (hunk 27 above)
Comment (romgrk) [reply scripts/x-data-grid-premium.exports.json:135]: There are often `export * ...` statements, I could adjust them to restrict what is exported but it also messes with the imports in other places.

E.g. the following one would also need to be adjusted. I feel it would be less of a burden to maintain to keep things as they are, but I can update if needed.

https://github.com/mui/mui-x/blob/1d611c02e624ee63d358798914c0e890c81190d1/packages/grid/x-data-grid/src/constants/defaultGridSlotsComponents.ts#L2-L15

Comment (cherniavskii) [reply scripts/x-data-grid-premium.exports.json:135]: Yeah, we need to change exports in multiple places.
I generally prefer to avoid additional exports if possible, so that we can make internal changes without worrying about breaking changes 🙂
So if there's no need to export these components - let's not do it

File: docs/data/data-grid/performance/performance.md [hunk 29]
```diff
@@ -2,43 +2,51 @@
```
Comment (MBilalShafi) [inline docs/data/data-grid/performance/performance.md:2]: Should we explain a bit the reactive behavior of `useGridSelector` thanks to the Store possibly with a small demo so that users start using it more often in customizations?

**Review by MBilalShafi — APPROVED** [review]
Great work 👏 
Thank you!

File: packages/grid/x-data-grid/src/components/cell/index.ts [hunk 30]
```diff
@@ -1,4 +1,4 @@
-export * from './GridCell';
+export { GridCell, GridCellProps } from './GridCell';
```
Comment (MBilalShafi) [inline packages/grid/x-data-grid/src/components/cell/index.ts:1]:
```suggestion
export { GridCell } from './GridCell';
export type { GridCellProps } from './GridCell';
```

File: docs/data/data-grid/performance/performance.md (hunk 29 above)
Comment (romgrk) [reply docs/data/data-grid/performance/performance.md:2]: I've explained a bit more this one in the docs for the reactive part.

**Comment by romgrk** [comment]
Should I merge this one despite the argos differences or should I debug them?

File: packages/grid/x-data-grid/src/components/GridRow.tsx [hunk 31]
```diff
@@ -256,141 +257,51 @@ const GridRow = React.forwardRef<HTMLDivElement, GridRowProps>(function GridRow(
...
 
-  const {
-    slots,
-    slotProps,
-    classes: rootClasses,
-    disableColumnReorder,
-    getCellClassName,
-  } = rootProps;
+  const { slots, slotProps, disableColumnReorder } = rootProps;
+  const CellComponent = slots.cell === GridCellV7 ? GridCellV7 : GridCellWrapper;
```
[the remark this answers is not in the document]
Comment (cherniavskii) [reply packages/grid/x-data-grid/src/components/GridRow.tsx:261]: @m4theushw relevant discussion: https://github.com/mui/mui-x/pull/9037#discussion_r1205628055

File: packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts [hunk 32]
```diff
@@ -304,35 +305,45 @@ export const useGridFocus = (
...
-  const handleBlur = React.useCallback<GridEventListener<'columnHeaderBlur'>>(() => {
-    logger.debug(`Clearing focus`);
-    apiRef.current.setState((state) => ({
-      ...state,
-      focus: { cell: null, columnHeader: null, columnHeaderFilter: null, columnGroupHeader: null },
-    }));
-  }, [logger, apiRef]);
+  const handleBlur = React.useCallback<GridEventListener<'columnHeaderBlur'>>(
+    (_, ev) => {
+      if (ev.relatedTarget?.className.includes(gridClasses.columnHeader)) {
```
Comment (oliviertassinari) [inline packages/grid/x-data-grid/src/hooks/features/focus/useGridFocus.ts:331]: Fixed this in https://github.com/mui/mui-x/pull/9336

File: packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx [hunk 33]
```diff
@@ -36,16 +36,15 @@ const GridVirtualScroller = React.forwardRef<
...
   return (
     <VirtualScrollerRoot
       ref={ref}
-      className={clsx(classes.root, className)}
+      {...props}
+      className={clsx(classes.root, props.className)}
       ownerState={rootProps}
-      {...other}
     />
   );
```
Comment (oliviertassinari) [inline packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx:49]: I believe there are a good number of cases in Material UI where we could apply this optimization. To consider if it's worth doing.

File: packages/grid/x-data-grid/src/utils/fastMemo.ts [hunk 34]
```diff
@@ -0,0 +1,6 @@
+import * as React from 'react';
+import { fastObjectShallowCompare } from './fastObjectShallowCompare';
+
+export function fastMemo<T>(component: T): T {
```
Comment (oliviertassinari) [inline packages/grid/x-data-grid/src/utils/fastMemo.ts:4]: I think that it could be great to leave a comment that explains how this comparison is different from the one of React https://github.com/facebook/react/blob/4ddc019aca8e08fd59cb43de5e0032be77d6174e/packages/react-reconciler/src/ReactFiberBeginWork.js#L570

File: package.json [hunk 35]
```diff
@@ -22,6 +22,7 @@
     "l10n": "babel-node -x .ts ./scripts/l10n.ts",
     "jsonlint": "node ./scripts/jsonlint.mjs",
     "eslint": "eslint . --cache --report-unused-disable-directives --ext .js,.ts,.tsx --max-warnings 0",
+    "eslint:fix": "yarn eslint --fix",
     "eslint:ci": "eslint . --report-unused-disable-directives --ext .js,.ts,.tsx --max-warnings 0",
```
Comment (oliviertassinari) [inline package.json:26]: In the main repo, these are called "lint" (there are json, esm, css, etc. types of lints), I find it confusing. It's better here with eslint.

**Review by oliviertassinari — COMMENTED** [review]
👍

File: packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx (hunk 33 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/components/virtualization/GridVirtualScroller.tsx:49]: Yes, we're doing a lot of allocations. There is also [this issue](https://github.com/mui/material-ui/pull/37461#issuecomment-1592131330) with the spread operator.

File: packages/grid/x-data-grid/src/utils/fastMemo.ts (hunk 34 above)
Comment (romgrk) [reply packages/grid/x-data-grid/src/utils/fastMemo.ts:4]: it goes [faaaaast](https://github.com/mui/mui-x/pull/9037#discussion_r1214288683), but yeah we should explain also `fastObjectShallowCompare`, it's tailored for a specific use-case.
