### PR TITLE
[DataGridPro] Improve `treeData` and `rowGrouping` performance

### LINKED ISSUE #8581: [data grid] Performance degradation with v6.x and tree data
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/sad-night-kj9npb?file=/demo.tsx:975-1024
Necessary setup for it to occur: many rows, tree data

Steps:
1. Just load sandbox and measure time to render

### Current behavior 😯

After updating to 6.x (here 6.1.0) it takes much longer to pass first render. With 5.x the longest method was `sortRowTree` with e.g. 600ms execution with the given data set. With 6.x and the new row structure we see the new method `rowsStateInitializer` and deeper `createRowTree` which now costs around 10x, so with the given data set roughly 6s.

### Expected behavior 🤔

Same performance as with 5.x

### Context 🔦

I kept the sample as near as possible to our data without actually including the concrete data. Namely we're trying to use grouping + aggregation to display ~18200 rows of data with ~25 columns of which most are included in the aggregations so the values also show in the grouping rows. The problem is that performance degrades significantly when aggregations are activated (see https://github.com/mui/mui-x/issues/8579). So we switched over to tree data + custom aggregation directly within the data. But when trying to update to 6.x we experience a major performance degradation which hinders us from updating to the newest major version.

We're planning to buy the premium version but had problems with groupings + aggregations so we did a workaround with tree data instead.

### Your environment 🌎

See codesandbox.io sample, but here also my personal env

<details>
  <summary>`npx @mui/envinfo`</summary>
```
  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 18.14.2 - ~/.asdf/installs/nodejs/18.14.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 112.0.5615.49
    Edge: 112.0.1722.39
    Firefox: Not Found
    Safari: 16.3
  npmPackages:
    @emotion/react: 11.10.6 => 11.10.6
    @emotion/styled: 11.10.6 => 11.10.6
    @mui/base:  5.0.0-alpha.118
    @mui/core-downloads-tracker:  5.11.9
    @mui/icons-material: 5.11.9 => 5.11.9
    @mui/material: 5.11.10 => 5.11.10
    @mui/private-theming:  5.11.9
    @mui/styled-engine:  5.11.9
    @mui/system:  5.11.9
    @mui/types:  7.2.3
    @mui/utils:  5.11.13
    @mui/x-data-grid:  6.1.0
    @mui/x-data-grid-premium: 6.1.0 => 6.1.0
    @mui/x-data-grid-pro:  6.1.0
    @mui/x-license-pro:  6.0.4
    @types/react: 18.0.20 => 18.0.20
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: 4.8.3 => 4.8.3
```
</details>

### Order ID or Support key 💳 (optional)

68355

### LINKED ISSUE #8999: [DataGridPro] aggregations blow up exponentially
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

[CodeSandbox demo](https://codesandbox.io/p/sandbox/8t1722)

### Current behavior 😯

I've performed an informal grouping-and-aggregation benchmark across several popular grids (MUI, [Material React Table](https://www.material-react-table.com/), [Tanstack](https://tanstack.com/table/v8), and AG Grid) in the [above example](https://codesandbox.io/p/sandbox/8t1722?file=%2Fsrc%2FMUI.tsx%3A1%2C1). MUI's performance seems to degrade exponentially:

**Rough Loading Time (ms)[^1]**

|Rows|MUI    |MRT      |Tanstack  |AG     | Best Possible|
|--------|---------|-----------|------------|----------|-------------------|
|1k      | 250   |500        |250        |50        |50                  |
|10k    | 1000 | 1000     |500        |250      |50                  |
|50k    | 13000|2000     |1500      |800      |150                |  
|100k  |💣*    |2500      |2500      |1200    |250                |

*Somewhere between 50k and 100k records the MUI grid blows up and kills the whole browser tab. 

The expected computational complexity for this group-and-sum operation is linear (which is what we see, roughly, with the other solutions) so there seems to be a problem with the MUI algorithm.

[^1]: Most grids don't have a good way to instrument the exact loading time, so these are basically eyeballed and not very accurate. Obviously they'll be different on different machines. Nevertheless the overall trends are clear enough.

### Expected behavior 🤔

Clearly the MUI grid can't be quite as fast as the optimized custom aggregation, but at 50k+ records, the grid should still perform an aggregation in a reasonable amount of time (and not blow up).

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```

  System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 4.98 GB / 15.32 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.2.4 - ~/.yarn/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Managers:
    Cargo: 1.51.0 - ~/.cargo/bin/cargo
    pip3: 22.0.2 - /usr/bin/pip3
  Utilities:
    CMake: 3.22.1 - /usr/bin/cmake
    Make: 4.3 - /usr/bin/make
    GCC: 11.3.0 - /usr/bin/gcc
    Git: 2.34.1 - /usr/bin/git
    Ninja: 1.10.1 - /usr/bin/ninja
    FFmpeg: 4.4.2 - /usr/bin/ffmpeg
  Virtualization:
    Docker: 23.0.6 - /usr/bin/docker
  IDEs:
    Nano: 6.2 - /usr/bin/nano
    Vim: 0.10.0 - /usr/bin/vim
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Perl: 5.34.0 - /usr/bin/perl
    Protoc: 3.17.0 - /usr/local/bin/protoc
    Python3: 3.10.6 - /usr/bin/python3
  Databases:
  Browsers:
    *Chromium: 113.0.5672.63
  Monorepos:
    Yarn Workspaces: 3.2.4
    Lerna: 5.6.2


```
</details>

### Order ID or Support key 💳 (optional)

46840

### PR DESCRIPTION
**Pull request by MBilalShafi**
Fixes #8581

The regression was introduced due to a function [createRowTree](https://github.com/mui/mui-x/blob/2ef454a6a11bc376a15280eed0a711cf95077532/packages/grid/x-data-grid-pro/src/utils/tree/createRowTree.ts) introduced in the [new internal structure for v6](https://github.com/mui/mui-x/pull/4927).

### Initial benchmarks:

For the same data (size: 40000), (i.e the one used in the linked [codesandbox](https://codesandbox.io/s/dank-glitter-xchz7d?file=/demo.tsx))
- buildRowTree (v5) took 176ms which is approximately 0.004ms per row
- createRowTree (v6) took 3700ms which is approximately 0.09ms per row (almost 20x slow)

**Reason:**
Looking deeper into the main function being used in createRowTree (i.e. [insertNodeInTree](https://github.com/mui/mui-x/blob/2ef454a6a11bc376a15280eed0a711cf95077532/packages/grid/x-data-grid-pro/src/utils/tree/utils.ts#L78)) there are not many complex computations apart from some references being updated.

Doing a [comparison](https://jsperf.app/pubila) yielded that most of the time is being consumed in destructuring and updating references of variables `childrenFromPath` and `children`, so avoiding that and keeping the same reference improved the performance.

#### Macbook Pro M1, Chrome browser:
[v5 version](https://codesandbox.io/s/sad-wood-55zhpw?file=/demo.tsx): ~2s 
[v6 version](https://codesandbox.io/s/angry-panka-iiipul?file=/demo.tsx) (HEAD): ~10s
[v6 version (this PR)](https://codesandbox.io/s/wispy-tree-wr2o3d?file=/package.json): ~1.8s

#### Macbook Pro M1, Firefox browser:
[v5 version](https://codesandbox.io/s/sad-wood-55zhpw?file=/demo.tsx): ~8.5s 
[v6 version](https://codesandbox.io/s/angry-panka-iiipul?file=/demo.tsx) (HEAD): ~13s
[v6 version (this PR)](https://codesandbox.io/s/wispy-tree-wr2o3d?file=/package.json): ~8.9s

**Side note:** Chromium v8 seems to handle reference-based assignments way faster than Firefox, the performance on Chrome seems improved from the v5 version.

<hr />

Fixes #8999 

On my test (MacOS, Chrome v113), the time to render the grid (for 100,000 rows) reduced from 22s to 0.8s

Before: https://codesandbox.io/s/aggregation-performance-regression-zx0rrd?file=/src/App.tsx
After: https://codesandbox.io/s/aggregation-performance-regression-fixed-x7k6gm?file=/src/App.tsx

### CODE REVIEW

**Review by flaviendelangle — COMMENTED** [review]
Glad that this fix solves the performance problem that well !

I am a little worried about the idea of mutating the `children` property (`childrenFromPath` less so, it's never used outside of the tree-building process).

Because now if you have a `useMemo` in a component that relies on `rowNode.children`, it won't re-run on tree updates.

My proposal was to do one spread per parent instead of one spread per children.
Not sure how to do that cleanly in the code.
We could pass a `prevTree` object that equals the tree before the current batch and only spread if `prevTree[parentNode.id].children === tree[parentNode.id].children`.

**Comment by flaviendelangle** [comment]
Could even be `prevTree[parentNode.id] === tree[parentNode.id]`, if the parent has the same ref as on the prev tree, then it has never been touched during this batch of update and we need to recreate it to avoid mutation.
Otherwise we mutate because it's just locale mutation.

**Comment by MBilalShafi** [comment]
Thanks @flaviendelangle for the suggestions, I tried to do a comparison with the `previousTree`

 > Because now if you have a useMemo in a component that relies on rowNode.children, it won't re-run on tree updates.

If you have any example in mind using which I can validate that this use case works as expected now, please share.
Thanks

**Comment by flaviendelangle** [comment]
>  I tried to do a comparison with the previousTree

Is it working or is it causing some issue ?

> I didn't quite get that in what circumstances a user would need to memoize rowNode.children.

When providing a custom `renderCell`, the user gets props containing `rowNode` which is the object where the `children` key we are mutating is.

If you look at the demo `TreeDataCustomGroupingColumn`, imagine that we add some code like

```tsx
const lastHired = React.useMemo(() => {
  return rowNode.children.reduce((acc, el) => {
    if (!acc || acc.recruitmentDate.getTime() < el.recruitmentDate.getTIme()) {
      return el
    }

    return acc
  }, null)  
}, [rowNode.children])
```

And then we render this `lastHired`
Then I think your PR would be a breaking change, since `children` no longer changes its reference.

I honestly don't think a lot of people are using `rowNode.children`
We never do it in the doc as far as I'm aware
But having a prop that's mutated feels like a bad pattern that will lead to nasty bugs imho

**Comment by MBilalShafi** [comment]
> Is it working or is it causing some issue ?

Apparently it seems to be working, I will try with the example you mentioned. 👍

File: packages/grid/x-data-grid-pro/src/utils/tree/utils.ts [hunk 1]
```diff
@@ -95,27 +97,27 @@ export const insertNodeInTree = ({
...
-      childrenFromPath: {
-        ...parentNode.childrenFromPath,
-        [groupingField]: {
-          ...parentNode.childrenFromPath?.[groupingField],
-          [groupingKey.toString()]: node.id,
-        },
-      },
-      children: [...parentNode.children, node.id],
-    };
+    if (previousTree !== null && previousTree[parentNode.id] === tree[parentNode.id]) {
```
Comment (cherniavskii) [inline packages/grid/x-data-grid-pro/src/utils/tree/utils.ts:108]: Passing `previousTree` everywhere doesn't look great, but I don't really see a better option 🤨

**Review by cherniavskii — APPROVED** [review]

File: packages/grid/x-data-grid-pro/src/utils/tree/utils.ts (hunk 1 above)
Comment (flaviendelangle) [reply packages/grid/x-data-grid-pro/src/utils/tree/utils.ts:108]: An alternative is to create a dictionnary that contains all the updated nodes during a batch.
But same problem, we end up having an additional param all over the place.

**Comment by MBilalShafi** [comment]
@flaviendelangle I confirmed, the mentioned use-case seems to work fine: https://codesandbox.io/s/keen-spence-hqg9q4?file=/demo.tsx (note the dates correctly being picked of children)

> Does this one fix https://github.com/mui/mui-x/issues/8999?

It does, on my test (MacOS, Chrome v113), the time to render reduced from 22s to 0.8s

Before: https://codesandbox.io/s/aggregation-performance-regression-zx0rrd?file=/src/App.tsx
After: https://codesandbox.io/s/aggregation-performance-regression-fixed-x7k6gm?file=/src/App.tsx

**Comment by flaviendelangle** [comment]
For the title, it improved the row grouping and the tree data
It does not improve the aggregation, strictly speaking, just the aggregation is often used with the tree data / row grouping.
