### PR TITLE
[DataGridPremium] Handle `isRowSelectable()` checks for the rows missing due to `keepNonExistentRowsSelected`

### LINKED ISSUE #20568: [data grid] DataGridPremium RowGrouping/TreeData + isRowSelectable + server side data breaks Grid
### Steps to reproduce

Steps:
1. Open this link to live example: - https://stackblitz.com/edit/qzuyxzcr-at9tibxv?file=src%2FDemo.tsx
2. Select a grouped row
3. Go to next page
4. Observe

### Current behavior

Actual: Grid throws error. The error triggers only if RowGrouping or TreeData is enabled (in other words if we have row nesting). If we do not have row nesting there is no issue.

### Expected behavior

Expected: Should preserve the selected rows because of keepNonExistentRowsSelected

### Context

Example error: `No row with id #auto-generated-row-jobTitle/Tech Lead found`
The error occurs in [`getRowParams()`](https://github.com/mui/mui-x/blob/5405d77c86fd7f9b14b71eaeaaee49eefa5f691e/packages/x-data-grid/src/hooks/features/rows/useGridParamsApi.ts#L42) which is called by [`isRowSelectable()`](https://github.com/mui/mui-x/blob/5405d77c86fd7f9b14b71eaeaaee49eefa5f691e/packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts#L211) because `propIsRowSelectable !== undefined`.

The issue is not limited to just going to next page as long as the selected rows are no longer in the grid. (like when changing the grouping criteria, etc.)

I took this demo from [this comment](https://github.com/mui/mui-x/issues/19074#issuecomment-3167863535) in issue #19074 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>
Browser: all

```
    System:
    OS: Linux 5.0 undefined
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: latest => 11.14.0 
    @emotion/styled: latest => 11.14.1 
    @mui/core-downloads-tracker:  7.3.1 
    @mui/icons-material: latest => 7.3.1 
    @mui/material: latest => 7.3.1 
    @mui/private-theming:  7.3.1 
    @mui/styled-engine:  7.3.1 
    @mui/system:  7.3.1 
    @mui/types:  7.4.5 
    @mui/utils:  7.3.1 
    @mui/x-data-grid:  8.9.2 
    @mui/x-data-grid-generator: latest => 8.9.2 
    @mui/x-data-grid-premium: latest => 8.9.2 
    @mui/x-data-grid-pro:  8.9.2 
    @mui/x-internals:  8.9.2 
    @mui/x-license:  8.9.2 
    @mui/x-telemetry:  8.5.3 
    @mui/x-virtualizer:  0.1.0 
    @types/react: latest => 19.1.9 
    react: latest => 19.1.1 
    react-dom: latest => 19.1.1 
    typescript: latest => 5.9.2 
```
</details>

**Search keywords**: row grouping isRowSelectable propIsRowSelectable No row with id #id found

### PR DESCRIPTION
**Pull request by arminmeh**
Closes https://github.com/mui/mui-x/issues/20568

It will be easier to review by hiding the whitespace changes.
I have noticed that `removeOutdatedSelection` had a parameter that was never passed, so I have removed it.

Before: https://stackblitz.com/edit/qzuyxzcr-at9tibxv?file=src%2FDemo.tsx
After: https://stackblitz.com/edit/qzuyxzcr-xkqxpjke?file=src%2FDemo.tsx

Another issue https://github.com/mui/mui-x/issues/20568#issuecomment-3669069153

Before: https://stackblitz.com/edit/qzuyxzcr-fb99upf6?file=src%2FDemo.tsx
After: https://stackblitz.com/edit/qzuyxzcr-bziemeba?file=src%2FDemo.tsx

### CODE REVIEW

File: packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts [hunk 1]
```diff
@@ -214,6 +205,12 @@ export const useGridRowSelection = (
         return false;
       }
 
+      // If `keepNonExistentRowsSelected` is true, we might run in a case where row selectability is checked for a row that does not exist.
+      // Since that row was previously selected (otherwise it would not be checked at this point), we return true.
```
Comment (MBilalShafi) [inline packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:209]: > otherwise it would not be checked at this point

Are you sure about this?
For example `selectRow()` calls `isRowSelectable()` both with the `isSelected` argument values `true` and `false`.

Would it be better to return `true` if the row was previously selected but not in the lookup now?

Comment (MBilalShafi) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:209]: Also, "after" demo (https://stackblitz.com/edit/qzuyxzcr-xkqxpjke?file=src%2FDemo.tsx) crashes now, and requires the `valueFormatter` in the `salary` column to add a null check, which is weird because the check added is not related to the stack trace.

```diff
- valueFormatter: (value: number) => `$${value.toLocaleString()}`,
+ valueFormatter: (value: number) => (value ? `$${value.toLocaleString()}` : ''),
```

Could it be related to https://github.com/mui/mui-x/commit/456b211ff7fdbadca783910ffa08bcb2cdd7e0d2 and may potentially break some implementations?

Comment (arminmeh) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:209]: > Are you sure about this?
For example selectRow() calls isRowSelectable() both with the isSelected argument values true and false.
>
> Would it be better to return true if the row was previously selected but not in the lookup now?

I am returning `true`, because the same would happen when there is no `isRowSelectable()` prop. `rowNode` would not be found, and all following conditions would fail.

Since we don't have the row, we can't call `isRowSelectable()`, and whatever we return might not match what would be returned from that function, if the row were there.

Comment (arminmeh) [reply packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelection.ts:209]: > Also, "after" demo ([stackblitz.com/edit/qzuyxzcr-xkqxpjke?file=src%2FDemo.tsx](https://stackblitz.com/edit/qzuyxzcr-xkqxpjke?file=src%2FDemo.tsx)) crashes now, and requires the valueFormatter in the salary column to add a null check, which is weird because the check added is not related to the stack trace.
>
>- valueFormatter: (value: number) => `$${value.toLocaleString()}`,
>+ valueFormatter: (value: number) => (value ? `$${value.toLocaleString()}` : ''),
>Could it be related to https://github.com/mui/mui-x/commit/456b211ff7fdbadca783910ffa08bcb2cdd7e0d2 and may potentially break some implementations?

Before demo also crashes. I think that this is just an issue with the formatter, because it doesn't take into account grouped rows that don't have values.

**Review by MBilalShafi — APPROVED** [review]
