### PR TITLE
[DataGrid] Support `date` and `datetime-local` input types in `GridFilterInputMultipleValue` type

### LINKED ISSUE #13409: [data grid] `GridFilterInputMultipleValue`'s prop types are incorrectly typed
### Steps to reproduce

Link to live example: (required)
https://codesandbox.io/p/sandbox/dark-fire-x498pg?file=%2Fsrc%2FDemo.tsx

Steps:
1. Open the Filters Panel
2. Select `Created On` to filter by
3. Observe console error about `date` not being supported while input works perfectly with a `type = "date"`

### Current behavior

`GridFilterInputMultipleValue`'s prop types validation produces noisy error logs when a `type` that isn't `"text" | "number"` is supported for the underlying input, while in truth any valid HTML input type is supported out of the box.

### Expected behavior

Just like [`GridFilterInputValue`](https://github.com/mui/mui-x/blob/1a0ccab775fc75ec3fa32f1d2e216e9726f2387d/packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputValue.tsx#L12) does, [`GridFilterInputMultipleValue`](https://github.com/mui/mui-x/blob/1a0ccab775fc75ec3fa32f1d2e216e9726f2387d/packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputMultipleValue.tsx#L9) should expose all supported type values, not just `"text "| "number"`

### Context

I'm trying not to have noisy errors (oftentimes reported to 3rd party telemetry) for using a component's feature that is actually supported and works out of the box just because its prop types definition is unaware of it.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    pnpm: 9.2.0 - ~/.nvm/versions/node/v18.16.1/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.142
  npmPackages:
    @emotion/react: ^11.7.1 => 11.11.1
    @emotion/styled: ^11.6.0 => 11.11.0
    @mui/icons-material: ^5.3.1 => 5.14.3
    @mui/lab: ^5.0.0-alpha.102 => 5.0.0-alpha.140
    @mui/material: ^5.3.1 => 5.14.5
    @mui/styles: ^5.3.0 => 5.12.3
    @mui/utils: ^5.11.2 => 5.14.16
    @mui/x-data-grid-pro: ^5.17.4 => 6.2.1
    @mui/x-date-pickers-pro: ^6.2.1 => 6.2.1
    @mui/x-license-pro: ^5.17.0 => 6.0.4
    @types/react: ^18.0.21 => 18.2.20
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    typescript: ~5.2.2 => 5.2.2
```
</details>

**Search keywords**: GridFilterInputMultipleValue, GridFilterInputValue, unsupported, type, date

### PR DESCRIPTION
**Pull request by karudedios**
### Description

When using `type = date` or `type = datetime-local` the prop types on `GridFilterInputMultipleValue` produce an error despite actually working perfectly fine given that this component (by default) just uses a native input.

This change is also consistent with how [GridFilterInputValue](https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputValue.tsx#L12) handles this property's typing (except there's no enum enforcement in the prop types over there, for some reason).

Please do let me know if I missed something, the change in the prop-types/types seemed trivial enough to do by hand, but if I must clone this and and run `pnpm prototype` to have the codegen do it for me I can, I had just chosen to take the easy way and directly edited this in GitHub.

Fixes #13409

### From the template

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
  - There was something about signing a CLA- though I wasn't prompted to do so when opening the PR

### CODE REVIEW

File: packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputMultipleValue.tsx [hunk 1]
```diff
@@ -113,7 +113,7 @@ GridFilterInputMultipleValue.propTypes = {
     operator: PropTypes.string.isRequired,
     value: PropTypes.any,
   }).isRequired,
-  type: PropTypes.oneOf(['number', 'text']),
+  type: PropTypes.oneOf(['number', 'text', 'date', 'datetime-local']),
```
Comment (karudedios) [inline packages/x-data-grid/src/components/panel/filterPanel/GridFilterInputMultipleValue.tsx:116]: May instead remove this, as per [the issue's suggestion](https://github.com/mui/mui-x/issues/13409#issuecomment-2155269895), that would make this consistent with how the other input field does it, type but no enforcement in the prop types for it.

```suggestion
```

**Review by michelengelen — COMMENTED** [review]
LGTM... but I would like to know from the team if this would maybe have unforeseen effects elsewhere

**Review by arminmeh — APPROVED** [review]
